### ISSUE TITLE
bbb 2.3 alpha 7 shared notes cannot type in mobile browser

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#11441] opened 2021-02-20 13:06 UTC
**Describe the bug**
Keyboard won't pop-up when accessing shared notes in mobile browser
**To Reproduce**
1. Go to bbb-room in mobile browser
2. Click on shared notes
3. Try to type - no keyboard appears

**Expected behavior**
When tapped inside shared notes window keyboard should appear
**Actual behavior**
Welp - it doesn't.

bbb 2.3 alpha 7

**Smartphone (please complete the following information):**
 - Device: Essential PH1
 - OS: Android 10
 - Browser: Chrome

**Comment by EmmyGraugans** [comment] 2021-02-23 08:43
Neither is it possible to write in the chat (on iPad with iOS 14.4) - or is that a different bug?

**Comment by ramonlsouza** [comment] 2021-02-25 14:14
Could not reproduce on my smartphone, it may be a bug specific to your device model or does not happen in Android 11

Tested on:
- Device: Samsung Galaxy S10e
- OS: Android 11
- Browser: Chrome



https://user-images.githubusercontent.com/3728706/109165105-eef8a780-7759-11eb-8cee-3794d9830032.mp4

**Comment by ramonlsouza** [comment] 2021-02-25 14:24
Could not reproduce on my smartphone, it may be a bug specific to your device model or does not happen in Android 11

Tested on:

Device: Samsung Galaxy S10e
OS: Android 11
Browser: Chrome


https://user-images.githubusercontent.com/3728706/109166916-fc169600-775b-11eb-9464-68367135ce82.mp4

**Comment by markginter31** [comment] 2021-02-25 14:24
Went back and tried again - in Chat, tapping anywhere in the box immediately brings up the keyboard.  In shared notes - tapping in the box does not trigger the keyboard **but** tapping beside the cursor/on the cursor line brings up the keyboard.  So - a bit embarrassed that it works -- although it is inconsistent between interfaces (chat/shared notes).

**Comment by daminebenq** [comment] 2021-02-25 14:33
Hello @markginter31 
can you please take screenshots of all wrong behaviors you are catching ?
will be better if you record a video. and thank you so much for helping us to test !!

**Comment by markginter31** [comment] 2021-02-27 15:21
I took my (first ever) screen recording.  I couldn't figure out how to make the "taps" appear - so I'm initially tapping in the big white space, before I tap right beside the blinking cursor in the shared notes area.  It occurred to me that the public chat brings the keyboard up immediately because there's only 1 line to tap on (and it's beside the cursor).  This is not as intuitive in the shared notes area because of all the white space (looks like I should be able to tap anywhere, but it only opens the keyboard if I tap in the line with the blinking cursor).  I realized that some of my students complaints about the shared notes not working is because they weren't tapping right beside the cursor in order to make the keyboard appear. 



https://user-images.githubusercontent.com/7345618/109391512-7aeb0a80-78e5-11eb-946f-3d97d081b73d.mp4

**Comment by ramonlsouza** [comment] 2021-03-01 16:34
The "text editor" part of the notes takes only one line initialy, and expands as the user types in it...

Maybe making it use 100% of the page height would open the phone keyboard when clicking anywhere in the notes area

![Screenshot from 2021-03-01 13-28-20](https://user-images.githubusercontent.com/3728706/109527099-0c977b00-7a92-11eb-8af0-09f1cba6e45a.png)

**Comment by ramonlsouza** [comment] 2021-03-05 17:43
After some deep investigation (thanks @pedrobmarin), we found that this is a bug happening on current version of Etherpad, but not on older versions (an older version used in bbb 2.2 worked as expected).

I'm opening an issue on etherpad's repository describing this bug.

**Comment by ramonlsouza** [comment] 2021-03-24 11:33
Hello @markginter31! 

Just letting you know that the issue has been fixed in latest etherpad update and we are already using it in bbb 2.3

**Closed** 2021-03-24 12:14 UTC
Labels: HTML5 Client
