### ISSUE TITLE
open network ports on external ip address

### ISSUE THREAD

**Issue by mm-bln** [bigbluebutton/bigbluebutton#9002] opened 2020-04-06 23:25 UTC
hello,

thanks for the great work!
i have a question. after everything is up and running i was scanning the server 
from an external pc for open ports. the server isn't behind a firewall. the results are:

> 80/tcp    open  http            syn-ack
> 443/tcp   open  https           syn-ack
> 1935/tcp  open  rtmp            syn-ack
> 3000/tcp  open  ppp             syn-ack
> 5060/tcp  open  sip             syn-ack
> 5080/tcp  open  onscreen        syn-ack
> 7443/tcp  open  oracleas-https  syn-ack
> 8021/tcp  open  ftp-proxy       syn-ack
> 8080/tcp  open  http-proxy      syn-ack
> 8081/tcp  open  blackice-icecap syn-ack
> 8082/tcp  open  blackice-alerts syn-ack
> 8090/tcp  open  opsmessaging    syn-ack
> 8888/tcp  open  sun-answerbook  syn-ack
> 9999/tcp  open  abyss           syn-ack

it may be that the installation script configured the various services with the public ip address 
instead of the local one due to an error in the /etc/hosts or something like that. 
according to the https://docs.bigbluebutton.org/2.2/configure-firewall.html documentation, 
only a few ports should be open:

TCP/IP port 22 (for SSH)
TCP/IP ports 80/443 (for HTTP/HTTPS)
UDP ports in the range 16384 - 32768 (for FreeSWITCH/HTML5 RTP streams)

bbb-conf --check gives me:
(i've replaced the real ip with 1.2.3.4)
> 
> BigBlueButton Server 2.2.3 (1833)
>                     Kernel version: 4.15.0-91-generic
>                       Distribution: Ubuntu 16.04.6 LTS (64-bit)
>                             Memory: 65821 MB
>                          CPU cores: 12
> 
> /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
>        bigbluebutton.web.serverURL: https://connect.example.com
>                 defaultGuestPolicy: ALWAYS_ACCEPT
>                  svgImagesRequired: true
> 
> /etc/nginx/sites-available/bigbluebutton (nginx)
>                        server name: connect.example.com
>                               port: 80, [::]:80
>                               port: 443 ssl
>                     bbb-client dir: /var/www/bigbluebutton
> 
> /var/www/bigbluebutton/client/conf/config.xml (bbb-client)
>                 Port test (tunnel): rtmp://connect.example.com
>                               red5: connect.example.com
>               useWebrtcIfAvailable: true
> 
> /opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
>                        local_ip_v4: 1.2.3.4
>                    external_rtp_ip: stun:stun.freeswitch.org
>                    external_sip_ip: stun:stun.freeswitch.org
> 
> /opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
>                         ext-rtp-ip: $${local_ip_v4}
>                         ext-sip-ip: $${local_ip_v4}
>                         ws-binding: :5066
>                        wss-binding: 1.2.3.4:7443
> 
> /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
>                      playback_host: connect.example.com
>                  playback_protocol: https
>                             ffmpeg: 4.2.2-1bbb1~ubuntu16.04
> 
> /etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
>                         proxy_pass: 1.2.3.4
> 
> /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
>                         kurento.ip: 1.2.3.4
>                        kurento.url: ws://127.0.0.1:8888/kurento
>                     localIpAddress: 1.2.3.4
>                recordScreenSharing: true
>                      recordWebcams: true
>                   codec_video_main: VP8
>                codec_video_content: VP8
> 
> /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
>                              build: 870
>                         kurentoUrl: wss://connect.example.com/bbb-webrtc-sfu
>                   enableListenOnly: true

should i use a local firewall to close the ports or adjust the configuration of the services?
any help would be appreciated!

**Comment by mm-bln** [comment] 2020-04-07 12:49
my bad. i just activated ufw. as described here:
[Restrict access to specific ports](https://docs.bigbluebutton.org/2.2/customize.html)

**Comment by createwebinar** [comment] 2020-04-22 10:52
We have checked BBB behind firewall. And actually you need to open TCP ports in the range 16384 - 32768 as well or video will not work

**Comment by basisbit** [comment] 2020-05-15 11:51
@mm-bln could you please close this issue if the problem is "solved" for you by applying the suggested ufw firewall rules?

**Closed** 2020-05-15 11:54 UTC
