### ISSUE TITLE
[2.5-alpha-3] No notification when conference ends

### ISSUE THREAD

**Issue by sergey-balychev** [bigbluebutton/bigbluebutton#14553] opened 2022-03-07 22:44 UTC
**Describe the bug**
At the end of the conference, the conference moderator has a blue screen without notification of the end of the conference and a link to the learning-analytics-dashboardl. (tested on BigBlueButton Server version 2.5-alpha-3 (236))
for invited users, everything is OK, the completion notification is shown.

**To Reproduce**
1. Go to 'Start'
2. Click on 'End the conference'
![изображение](https://user-images.githubusercontent.com/63751589/157126758-b98dab3a-ddf6-4e35-bd11-1a643792d75e.png)
![изображение](https://user-images.githubusercontent.com/63751589/157126786-7463f1c5-98b5-4d43-bd8d-eb871a8c5b4e.png)
3. See error (I just have a blue screen with no notification of the end of the conference and a link to the learning-analytics-dashboard.)
![изображение](https://user-images.githubusercontent.com/63751589/157128555-8708fdbf-951c-4462-8c20-315c7b1e852f.png)

**Expected behavior**
a notification about the end of the conference and a link to the learning-analytics-dashboard will appear
_made on a possible version_
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.4.4 (2968)

![изображение](https://user-images.githubusercontent.com/63751589/157128078-f119fe69-1c0e-4233-8d26-86d941b65426.png)

**Actual behavior**
the notification about the end of the conference and the link to the learning-analytics-dashboard **did not** appear
![изображение](https://user-images.githubusercontent.com/63751589/157128555-8708fdbf-951c-4462-8c20-315c7b1e852f.png)

$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.5-alpha-3 (236)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version 99.0.4844.51

**Desktop:**
 - OS: Mac
 - Browser Safari
 - Version 15.3 (17612.4.9.1.8)

**Comment by PhMemmel** [comment] 2022-03-08 07:07
Most likely duplicate of #14545 which has already been fixed.

**Comment by sergey-balychev** [comment] 2022-03-08 07:13
@PhMemmel  most likely you are right. did not notice immediately [#14545](https://github.com/bigbluebutton/bigbluebutton/issues/14545). thanks.

**Closed** 2022-03-28 12:30 UTC
Labels: module: client
