### ISSUE TITLE
Recording ready callback URL not works

### ISSUE THREAD

**Issue by Brullworfel** [bigbluebutton/bigbluebutton#8392] opened 2019-12-04 08:40 UTC
Hello!

When I create meeting, I send meta_bbb-recording-ready-url parameter with URLEncoded API URL as in documentation ( https://docs.bigbluebutton.org/dev/api.html#recording-ready-callback-url ).

By API I can see in meetings list that the parameter has been successfully accepted by BBB:

```
["metadata":protected]=>
--
  | object(stdClass)#4 (4) {
  | ["date"]=>
  | string(16) "04.12.2019 12:00"
  | ["presenter"]=>
  | string(10) "Махди"
  | ["name"]=>
  | string(12) "Test webinar"
  | ["bbb-recording-ready-url"]=>
  | string(56) "https%3A%2F%2Fmedinaschool.org%2Fapi%2Fbbbrecordingready"
  | }
```

But when the recording is ready, the BigBlueButton server not makes any request to this URL!

**Comment by ffdixon** [comment] 2020-01-20 00:35
Is your recording ready URL HTTP or HTTPS?

**Comment by Brullworfel** [comment] 2020-01-20 06:30
HTTPS: https://medinaschool.org/api/bbbrecordingready

API is behind Sucuri Web-Firewall, but our BBB server IP-address in firewall whitelist.

**Comment by Froskur** [comment] 2020-04-15 14:55
Hi guys!

I have the same problem. At the same time, the CallBack at the end of the conference works well. Is it clear what the problem is?

**Comment by kdflint** [comment] 2020-05-06 01:35
Hello, I am having similar problem. Here is a dump of my CreateMeetingParameters state. I'm leveraging the PHP API.

I confess I'm a little confused by the `meta_` prefix. As best as I can discern, it should be assembled like below? See very bottom of the listing. At any rate, using the meta parameter property name `meta_bbb-recording-ready-url` also does not work.

I'd surely appreciate a practiced eye to guess what might be obviously wrong here.

```
20:58:49 05/05/20  [info] BigBlueButton\Parameters\CreateMeetingParameters::__set_state(array(
   'meetingId' => '5574fe95-456b-4523-881b-75bb2708cd2e',
   'meetingName' => 'The Demo Organization Conference Room',
   'attendeePassword' => 'ap',
   'moderatorPassword' => 'mp',
   'dialNumber' => NULL,
   'voiceBridge' => NULL,
   'webVoice' => NULL,
   'logoutUrl' => 'https://northbridgetech.org/dev/nexus/web/roomLogout.php',
   'maxParticipants' => NULL,
   'record' => true,
   'autoStartRecording' => false,
   'allowStartStopRecording' => true,
   'duration' => '0',
   'welcomeMessage' => NULL,
   'moderatorOnlyMessage' => NULL,
   'presentations' => 
  array (
  ),
   'meta' => 
  array (
    'network' => NULL,
    'organization' => '12345678',
    'group' => '1',
    'initiator' => '374',
    'uuid' => '5574fe95-456b-4523-881b-75bb2708cd2e',
    'bbb-recording-ready-url' => 'https%3A%2F%2Fnorthbridgetech.org%2Fdev%2Fnexus%2Fweb%2Fapi%2FpostBbbRecordingComplete.php',
  ),
))
```

**Comment by kdflint** [comment] 2020-05-07 16:34
Adding to above: This is an example of a meeting create url that I would expect to produce a recording complete callback. This url did create a good meeting session but I can't see evidence of the callback POST (which is just a simple message log at this point).

I would surely appreciate a practiced eye on this to spot what might be incorrect.

```
https://northbridgetech.api.rna1.blindsidenetworks.com/bigbluebutton/api/create?name=The+Demo+Organization+Conference+Room&meetingID=a1d&attendeePW=ap&moderatorPW=mp&logoutURL=https%3A%2F%2Fnorthbridgetech.org%2Fdev%2Fnexus%2Fweb%2FroomLogout.php&record=true&autoStartRecording=false&allowStartStopRecording=true&meta_organization=123&meta_group=1&meta_initiator=374&meta_uuid=a1d&meta_bbb-recording-ready-url=https%253A%252F%252Fnorthbridgetech.org%252Fdev%252Fnexus%252Fweb%252Fapi%252FpostBbbRecordingComplete.php&checksum=***
```

**Comment by kdflint** [comment] 2020-05-08 17:00
For whomever comes along next, I solved my issue.

In my post on May 5 I dumped a pretty-print of the CreateMeetingParameters state constructed by the PHP API library.

It is correct that the `bbb-recording-ready-url` property belongs inside the `meta` array. However, it is a mistake to url-encode the property value since the PHP API library will do that for you. So this:

```
   'meta' => 
  array (
    'network' => NULL,
    'organization' => '12345678',
    'group' => '1',
    'initiator' => '374',
    'uuid' => '5574fe95-456b-4523-881b-75bb2708cd2e',
    'bbb-recording-ready-url' => 'https%3A%2F%2Fnorthbridgetech.org%2Fdev%2Fnexus%2Fweb%2Fapi%2FpostBbbRecordingComplete.php',
  ),
```
should be this
```
   'meta' => 
  array (
    'network' => NULL,
    'organization' => '12345678',
    'group' => '1',
    'initiator' => '374',
    'uuid' => '5574fe95-456b-4523-881b-75bb2708cd2e',
    'bbb-recording-ready-url' => 'https://northbridgetech.org/dev/nexus/web/api/postBbbRecordingComplete.php',
  ),
```

Then the create meeting url comes out correctly like this. This formulation works. I got my callback, and a nice way to end the week :)

```
https://northbridgetech.api.rna1.blindsidenetworks.com/bigbluebutton/api/create?name=The+Demo+Organization+Conference+Room&meetingID=a1d&attendeePW=ap&moderatorPW=mp&logoutURL=https%3A%2F%2Fnorthbridgetech.org%2Fdev%2Fnexus%2Fweb%2FroomLogout.php&record=true&autoStartRecording=false&allowStartStopRecording=true&meta_organization=123&meta_group=1&meta_initiator=374&meta_uuid=a1d&meta_bbb-recording-ready-url=https%253A%252F%252Fnorthbridgetech.org%252Fdev%252Fnexus%252Fweb%252Fapi%252FpostBbbRecordingComplete.php&checksum=***
```
Notice how in my post from May 7 the url encoding of the `meta_bbb-recording-ready-url` property value in the create meeting url was fouled up because the input data had already attempted to encode it and so, boink.

```
&meta_bbb-recording-ready-url=https%253A%252F%252Fnorthbridgetech.org%252Fdev%252Fnexus%252Fweb%252Fapi%252FpostBbbRecordingComplete.php
```

Cheers all!

**Comment by dev-umesh** [comment] 2020-12-14 06:21
Hello All,

I have passed the non-encoded 'bbb-recording-ready-url' in the meta (solution given by @kdflint), still the callback url is not getting called after the end of the meeting. The call back url is correct which I verified in event.xml generated for each recording as well as calling the url in postman. Any suggestion or help will be appreciated

Thanks

**Comment by kumar-m-ecot** [comment] 2021-04-22 04:14
Hi All,

I checked the solution given by @kdflint and tried to apply that, but no sucess for me. Callback URL is not getting called after the end of meeting. In an another similar raised issue, [11072](https://github.com/bigbluebutton/bigbluebutton/issues/11072) @ffdixon confirmed that they are going to fix this in upcoming release but no kind of timeline was given yet. So I am waiting for this to get fixed in upcoming release. If anybody has already come up with any working solution then please share. 

Also, @ffdixon If you got any timeline to share for this issue, i ll appreciate your words on it.

Thanks much!

**Comment by dev-umesh** [comment] 2021-05-26 11:30
Hello All,

It's been more than 5 months since the actual issue was raised, it would be very helpful if we can get any timeline for this issue to be fixed. Any fixes would be much appreciated.

Thanks

**Comment by pedrobmarin** [comment] 2021-05-29 19:24
Tested this issue against the develop branch using [API Mate](https://mconf.github.io/api-mate/) and it seems to be working. As `meta_bbb-recording-ready-url` param I used this [webhook test web app](https://webhook.site).

It looks like folks on this thread may share different problems at the same subject. I will send a pull request with some refactor for the post publish script and recommendations to close this old issue down.

I suggest using a third party app as validator and, If anyone still experience some kind of problem regarding this callback, please open a new issue.

**Comment by pedrobmarin** [comment] 2021-05-31 15:31
@GhaziTriki could this be a [bigbluebutton-api-php](https://github.com/bigbluebutton/bigbluebutton-api-php) issue?

**Comment by saiprathap487** [comment] 2021-06-02 13:08
> Hi guys!
> 
> I have the same problem. At the same time, the CallBack at the end of the conference works well. Is it clear what the problem is?

i am trying since two days not able to figure out how to encode the meta_endCallbackUrl 
iam encoding like this

+"&meta_endCallbackUrl="+urlEncode(encodedCallBackUrl)
urlEncode will return : URLEncoder.encode(s, "UTF-8");
if i do like this check sum error is occuring...

if i have passonly string "https://192.168.43.57/services/common/api/callback" in the call back url then 
check sum error is not happening...but if moderator ends the meeting...the call back is not happening...
Note: should i install hooks in the bbb server for this??
please help  me @Froskur

**Comment by antobinary** [comment] 2022-01-12 16:36
Please check @pedrobmarin above. Closing now. Thanks all!

**Closed by antobinary** 2022-01-12 16:36 UTC
Labels: module: core, module: recording, type: bug, status: verify
