### ISSUE TITLE
Improve location of hint for mic/cam permission granting

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6836] opened 2019-02-21 16:13 UTC
Improve location of hint for permission granting. Verify in [ Chrome / FF / Safari / Edge] in both desktop and mobile (the browsers that apply)
![image](https://user-images.githubusercontent.com/6312397/53183513-7c341f00-35c9-11e9-80d8-5a13856892be.png)

**Comment by fcecagno** [comment] 2019-02-22 19:13
It only happens on super wide screens.

**Comment by BobakOftadeh** [comment] 2019-03-01 16:19
Could more details on how the issue is produced please be posted, such as px width/height, browser type, etc.

**Comment by capilkey** [comment] 2019-03-01 16:23
You can see the issue by stretching your Chrome browser over two monitors. The same thing can be done for the other browsers.

**Comment by capilkey** [comment] 2019-03-01 16:30
It's going to be really interesting to solve because sometimes Chrome puts the dialog on the left and sometimes they put it on the right.

**Comment by BobakOftadeh** [comment] 2019-03-08 17:22
I found out that permissions popup moves based on if the popup is off-screen. The size of the monitor is not the only reason why this issue occurs. This is making it difficult to find a consistent fix as any solution tied to screen size might disrupt other cases where the hint location would have been in the right location.

**Comment by KDSBrowne** [comment] 2019-03-08 17:25
I tried replicating this with my monitor in portrait mode, both the hint and popup were off screen.

**Comment by BobakOftadeh** [comment] 2019-03-08 18:03
Regardless of screen size on landscape, if the popup goes off screen, it switches sides and remains on that side even if the window is maximized.
![premission4](https://user-images.githubusercontent.com/32152296/54046238-bf81b680-41a1-11e9-8172-d864865d49fa.gif)

**Comment by BobakOftadeh** [comment] 2019-04-04 15:29
This issue will be closed as a constant solution cannot be implemented. Where the permission popup appears is based on browser behavior and the location of where it appears depends on different situations as outlined above.

**Closed** 2021-04-04 14:35 UTC
Labels: User Interface (UI), module: client
