### ISSUE TITLE
Recordings not shown in Moodle

### ISSUE THREAD

**Issue by WilmarCe** [bigbluebutton/bigbluebutton#9848] opened 2020-06-16 07:17 UTC
**Describe the bug**
Recordings are not shown in Moodle anymore after installing the june-2nd update. Some debugging showed that the API reports that there are no recordings. 
These recordings are however present on the bbb-server.
In bbb-web.log I find these lines:
2020-06-16T09:09:22.462+02:00 INFO  o.b.api2.util.RecMetaXmlHelper - Exception while loading /var/bigbluebutton/published/presentation/ec9c8ff79828ae4f490c16dfd9188b1bbd40f7dc-1591685568409/metadata.xml
2020-06-16T09:09:22.462+02:00 INFO  o.b.api2.util.RecMetaXmlHelper - Exception details: java.io.FileNotFoundException: /usr/share/bbb-web/WEB-INF/lib/bbb-common-web-0.0.1590163241-SNAPSHOT.jar (No such file or directory)

which is true. The folder only contains bbb-common-web-0.0.1591107979-SNAPSHOT.jar
I presume this causes the API to report that there are no recordings.
**To Reproduce**

**Expected behavior**
That bbb-web uses bbb-common-web-0.0.1591107979-SNAPSHOT.jar
**Actual behavior**
bbb-web uses bbb-common-web-0.0.1590163241-SNAPSHOT.jar

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by matiasilva** [comment] 2020-06-16 08:57
Duplicate of #8986.

**Closed by matiasilva** 2020-06-16 08:57 UTC
