### ISSUE TITLE
WebRTC Error 1002 when refusing to join WebRTC then joining audio using Flash

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#2813] opened 2015-10-02 06:42 UTC
Steps to reproduces :
- Click on microphone.
- Refuse to join audio via WebRTC.
- Accept to join audio via Flash.
- Join audio using Flash.

Current behaviour:
- An error message "WebRTC error 1002" is displayed.
- When clicking on "Yes" the join Flash audio is displayed.

Expected behaviour:
- Once joined audio via Flash, checking for WebRTC should be stopped.

An explanatory video can be found in this link http://screencast.com/t/9Ue851eOvt

**Comment by ffdixon** [comment] 2016-01-10 23:57
Hi Ghazi,

I just tested this against

  http://demo.bigbluebutton.org/

and was not able to reproduce.  Can you do a quick test and let us know if you can still reproduce it at your end.

**Comment by ffdixon** [comment] 2016-01-21 04:21
Closing this issue -- if it resurfaces we can open a new issue.

**Closed by ffdixon** 2016-01-21 04:21 UTC
Labels: Voice
