### ISSUE TITLE
pdf upload in presentation while in class issue

### ISSUE THREAD

**Issue by hamedunik** [bigbluebutton/bigbluebutton#13830] opened 2021-12-04 16:23 UTC
**Describe the bug**
I've recently upgrade my 11 bigbluebutton servers to 2.4 rc4 and now several times have issue with pdf upload in presentation. an error will occur and says "app.error.fallback.view.title"
I've also updated the server to recent 2.4 rc5 and not solved yet.

**To Reproduce**
1. Go to 'a new meeting'
2. Click on 'Manage Presentation' and upload a PDF file and select the uploaded PDF to display.
3. See error

**Screenshots**

**Desktop (please complete the following information): not tested a lot and seen yet

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy Tab A 10.1]
 - OS: [Android 10 and 11]
 - Browser [Chrome]
 - Version [95 and 96]

![1](https://user-images.githubusercontent.com/70991392/144716685-beddb363-8233-4274-9c94-ab25c6e92e01.jpg)
![2](https://user-images.githubusercontent.com/70991392/144716686-fd31159f-8015-4e59-a268-c70a9c11c5ad.jpg)

**Comment by vahidajorloo** [comment] 2021-12-07 10:54
it happened to me once and the problem was the file that i was trying to upload ,since then it didnt happen again
does it happen all the time or just with some files that you want to upload?

**Comment by ffdixon** [comment] 2021-12-07 13:41
Can you give more specific steps to reproduce -- we're interested to reproduce this issue.

**Comment by antobinary** [comment] 2021-12-07 15:16
Hi @hamedunik 

This appears to be a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/13659
It is fixed on the next version of BBB 2.4, coming out pretty soon.
We were able to trigger this when the file name of a presentation to be uploaded was in a RTL language (Arabic / Hebrew / Persian, etc).

We have propagated the fix to https://test24.bigbluebutton.org - feel free to upload one of your problematic presentations and see if the issue is reproducible there.

If anyone hits an issue similar to this one on BBB 2.4.0+, please open a new issue, provide the name of the file(s), the exact client build (three dots menu -> About) and a screenshot.

**Closed by antobinary** 2021-12-07 15:16 UTC
Labels: module: core
