### ISSUE TITLE
bbb-conf  restart issues

### ISSUE THREAD

**Issue by spinovation** [bigbluebutton/bigbluebutton#4783] opened 2017-12-08 07:36 UTC
Hello @ffdixon , 
I have tried to restart bbb-conf, But getting the errors like that

sudo bbb-conf --restart

# IP does not match:
#                           IP from ifconfig: 172.31.x.xxx
#   /etc/nginx/sites-available/bigbluebutton: www.chatx.live
chatx.live
meetings.chatx.live
Restarting BigBlueButton 1.1.0 ...
Stopping BigBlueButton
Starting BigBlueButton
** Potential problems described below **
# IP does not match:
#                           IP from ifconfig: 172.31.x.xxx
#   /etc/nginx/sites-available/bigbluebutton: www.chatx.live
chatx.live
meetings.chatx.live
.
/usr/bin/bbb-conf: line 1258: [: too many arguments

Please let me know, How can i will fixed the issues on server

**Comment by ffdixon** [comment] 2017-12-08 13:21
Are you able to login to BigBlueButton and start a session?

When you assign a hostname, to your server with SSL certificate, the hostname will not do a string match against the IP address, so you'll get a warning.

The title emphasis "Potential Problems".  If you have setup a hostname + SSL certificate and BigBlueButton is working (you can login through your front-end and start a meeting), then you can ignore this warning.

**Comment by transalm** [comment] 2017-12-09 14:54
Hi,
check the nginx configuration /etc/nginx/sites-available/bigbluebutton
Do you have more than one active entry "server_name" ?

That might be the cause of your troubles.
bbb-conf naively greps nginx config looking for server_name and choke in line 1258 if it gets more than one

Regards

**Comment by spinovation** [comment] 2017-12-11 06:36
@ffdixon ,

Yes I have connect with the meeting, But voice call are not working, I have checked multiple system, So I will need to fixed the voice issue Can  you suggest me How can I fixed this issue

@transalm  I will try to this Yes I have put more then one server_name here one for domain and other for sub domain.

**Comment by spinovation** [comment] 2017-12-11 07:21
@ffdixon && @transalm 

Hello I have checked the bbb-conf after remove multiple server_name within site-enabled folder bigbluebutton file and then restart the bbb and checking the bbb-config its not working,

Please see the error given below....
sudo bbb-conf --check

BigBlueButton Server 1.1.0 (561)
                    Kernel version: 4.4.0-1022-aws
                      Distribution: Ubuntu 16.04.2 LTS (64-bit)
                            Memory: 4045 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
  		Port test (tunnel): chatx.live
                              red5: chatx.live
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                    websocket port: 5066
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: www.chatx.live
chatx.live
                              port: 80, [::]:80
                    bbb-client dir: 

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: chatx.live

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: chatx.live


** Potential problems described below **
# IP does not match:
#                           IP from ifconfig: 172.31.3.177
#   /etc/nginx/sites-available/bigbluebutton: www.chatx.live
chatx.live

/usr/bin/bbb-conf: line 1258: [: www.chatx.live: binary operator expected

**Comment by ffdixon** [comment] 2017-12-11 12:37
Do you get an error in the client when trying voice?  The most common client errors are 1002 and 1009.    See http://docs.bigbluebutton.org/install/install.html#configuring-bigbluebutton-behind-a-firewall.

**Comment by transalm** [comment] 2017-12-12 19:26
The output of `bbb-conf --check` indicates that you still have two server_name entries. www.chatx.live and chatx.live.

The variable NGINX_IP in line 1258 is obtained by calling grep on /etc/nginx/sites-available/bigbluebutton. If more than one server_name were found, you will have a line break within this variable.
I run in the same problem and had to remove all the entries keeping the one.
`# workaround
function get_nginx_name() {
        local NGINX_IP=$(cat /etc/nginx/sites-available/bigbluebutton | grep -v '#' | sed -n '/server_name/{s/.*name[ ]*//;s/;//;p}' | cut -d' ' -f1)
        local words_count=$(echo ${NGINX_IP} | wc -w)
        if [ 1 -lt ${words_count} ]; then
                local t=''
                for n in ${NGINX_IP}; do # assuming all entries are the same keep the last
                        t=$n
                done
                echo ${t}
        else
                echo ${NGINX_IP}        
        fi
}`
good luck

**Comment by ffdixon** [comment] 2020-02-10 20:21
Closing this issue -- it's fixed.

**Closed by ffdixon** 2020-02-10 20:21 UTC
