### ISSUE TITLE
ios webcams displaying problem

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8100] opened 2019-09-11 14:04 UTC
Hi BBB,

we have a problem with ios devices webcams displays

**how it looks from Desktop**
![image](https://user-images.githubusercontent.com/33185490/64702713-6ad93400-d481-11e9-8104-1a147c09bda9.png)

**how it looks from iPad**
![IMG_0009](https://user-images.githubusercontent.com/33185490/64702761-82182180-d481-11e9-9094-db11f8ed31c2.PNG)

**Comment by prlanzarin** [comment] 2019-09-11 21:01
Isn't this kind of a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/8058?
I think the issues should be merged because the issue here is that the video container letterboxing is broken (_again_, it seems like a specialization of the defunct https://github.com/bigbluebutton/bigbluebutton/issues/6648), but this time on mobile Safari only.

**Closed** 2019-11-25 15:35 UTC
Labels: HTML5 Client
