### ISSUE TITLE
URGENT : Shared notes broken in release 2.2.32

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/bigbluebutton#11508] opened 2021-02-26 08:20 UTC
**Describe the bug**
Shared notes broken in release 2.2.32

**To Reproduce**
1. Go to 'shared notes'
2. Shared notes do not activate
3. error message is shown

**Expected behavior**
Shared notes should activate

**Actual behavior**
Error message shown in shared notes
```
An error occurred
The error was reported with the following id: 'JxQDpZHpMvq2gHMslh7u'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: JxQDpZHpMvq2gHMslh7u
URL: https://bbb.arawa.fr/pad/p/9c244156?showLineNumbers=false&showChat=false&noColors=true&showControls=true&rtl=false&userName=Thierry%20Kauffmann&userColor=%231565c0&lang=fr&sessionToken=sldtlz4lm6tparji
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
TypeError: pad.collabClient is null in https://bbb.arawa.fr/pad/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 3'
```
**Screenshots**

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.32 (2345)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04
 - Browser Firefox
 - Version 85.0.1

**Comment by PhMemmel** [comment] 2021-02-26 08:33
Duplicate of #11497

Have a look at this issue, a workaround is described there.

**Closed** 2021-02-26 15:04 UTC
Labels: HTML5 Client
