### ISSUE TITLE
add the possibility to extend the time limit for already running breakout rooms

### ISSUE THREAD

**Issue by ownhardy** [bigbluebutton/bigbluebutton#10684] opened 2020-10-20 18:37 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes I "kick" the participants into beakout rooms, leaving the default duratiion time as it is, e.g. 15 minutes. And afterwards I realize that I would prefer a longer duration time. (I might have even promised ot the the participants and just forgot the adjust the dudration setting in the creation dialog.)

**Describe the solution you'd like**
I would like to have some way to EXTEND the duration of a set of already running breakout rooms. This might be an addidtional setting in the "beakout room tab" where all the runnign breakout sessions are listed for the moderator, and where the remaining time is displayed.

**Describe alternatives you've considered**
No good alternatives. I could either wait for the wrong duration to finish, and then kick all participants into new breakout rooms. (But then they are mixed up differently, because I cannot reuse the old breakout rooms, but this is a different feature request.) Or I could imediatelly close all breakout rooms (this feature is already implemented in BBB) but the I have the same mentioned problem when I re-create the beakout rooms.

**Additional context**
I use breakout rooms during an online lecture, to kick the participants into small groups for group discussion or group work. Mostly the participants are randomly distributed to those breakout rooms. I also like to "pop  into" one breakout room after another the partly join those discussions. And when I don' manage to visit everyone in time, it would be nice to have the possibility to also extend this group work phase. Or I get the impression that most groups take more time to get to a useful result, in this case I would also like to extend the time limit for all groups.

**Comment by matiasilva** [comment] 2020-10-21 07:17
Thank you for this very well thought-out issue but I'm marking this as a duplicate of #5803 where it can referenced. Breakout rooms are nearly identical to normal rooms, so I expect the API to extend to both normal and breakout rooms if implemented.

**Closed by matiasilva** 2020-10-21 07:17 UTC
Labels: Enhancement

**Comment by ownhardy** [comment] 2020-10-21 19:34
Alright. Sorry for opening a duplicate issue. I didn't find that one before.
