### ISSUE TITLE
Wrong cursor position with screen sharing

### ISSUE THREAD

**Issue by matthiasbe** [bigbluebutton/bigbluebutton#11019] opened 2020-12-14 15:42 UTC
**Describe the bug**
We are three in a videoconference room. One of us (let's say person X) always have this problem : person X shares his screen, and use its cursor to point something on its screen, but we (the other two persons) don't seen the cursor on what person X is talking about. Instead, the cursor is few inches above on the left.

**To Reproduce**
1. Start a room with other people
2. Someone starts screensharing
3. Observe the place of the cursor

**Expected behavior**
The cursor should be at the same place for all participants

**Actual behavior**
For the people looking at the screen sharing, the cursor is a few inches above and on the left.

**Screenshots**
None

**Desktop (please complete the following information):**
For the person sharing the screen
 - OS: [Mac]
 - Browser [Firefox]
 - Version [83]

**Smartphone (please complete the following information):**
Not using smartphone

**Additional context**
None

**Comment by matthiasbe** [comment] 2020-12-14 15:45
This bug is particularly problematic when we are working on a text. We end up talking about different lines and sentences of the text, thus we cannot understand each other.

A workaround in this case is to either use the document uploading (but my collaborators are used to it yet) or to highlight the text in your document viewer (the highlighting shows the correct sentence).

**Comment by prlanzarin** [comment] 2020-12-14 16:49
Duplicate of  https://github.com/bigbluebutton/bigbluebutton/issues/10661 (defunct).

Skim through that issue. This is not a problem with BBB itself. Browser-vendor related.

**Closed by prlanzarin** 2020-12-14 16:49 UTC

**Comment by matthiasbe** [comment] 2020-12-14 17:33
Thank you for your quick reply. Indeed it seems related, especially because the person experiencing this when sharing is having a dual screen.
