### ISSUE TITLE
Whiteboard cursor jumps up and down

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#16129] opened 2022-12-14 09:44 UTC
**Describe the bug**
When the presenter is drawing on the whiteboard, the cursor visible to users jumps up and down.

**To Reproduce**
1. Start 2.6-beta-3 (build 253)
2. Join with two users
3. Slowly draw as the presenter
4. the viewer's pointer jumps up and down

**Expected behavior**
The pointer should be smooth

**Actual behavior**
Viewers see jitter (see attached video with presenter (chrome) on left and viewer (firefox) on the right).

https://user-images.githubusercontent.com/290351/207561421-cf68d53a-a275-4282-a948-9372ad9977ae.mp4

```
BigBlueButton Server 2.6.0-beta.3 (597)
                    Kernel version: 5.4.0-122-generic
                      Distribution: Ubuntu 20.04.5 LTS (64-bit)
                            Memory: 8148 MB
                         CPU cores: 4
```

**Comment by ramonlsouza** [comment] 2023-02-06 18:18
Could not reproduce it with the most recent release, likely fixed by #16607

**Closed by ramonlsouza** 2023-02-06 18:18 UTC
Labels: priority: high, component: whiteboard, module: client
