### ISSUE TITLE
Improve visual distinction for status changes

### ISSUE THREAD

**Issue by mkpelletier** [bigbluebutton/bigbluebutton#7972] opened 2019-08-23 07:50 UTC
BigBlueButton 2.2-beta-18 
HTML5 client

It is often difficult to pick up on changes in the user list when participants raise their hands as the visual indication is too subtle in the HTML5 client. I would suggest a colour change of the surrounding icon or a better fill option to the status icon. Perhaps we could use a bright colour for the hand icon (red?) as this is the single most commonly used status option in a lecture scenario.  Alternatively, it may be nice to have the option of an audio alert for a status change like there is for the chat.

Thanks for all the amazing work on BBB!

**Comment by ffdixon** [comment] 2019-08-23 10:34
Agreed (specially for larger number of users).  

In future updates, we're going to be exploring making it easier a user to change their emoji status and for presenters/moderators (and maybe users) to see the changes of status.

**Comment by mkpelletier** [comment] 2019-08-23 10:45
This may have been requested elsewhere, but now that you mention it, I have a class with about 30 users and when someone speaks it takes me a bit to figure out who is talking.  Perhaps the speaking indicator also needs to be more obvious?

**Comment by ffdixon** [comment] 2019-08-23 11:26
> Perhaps the speaking indicator also needs to be more obvious?

Agreed, see https://github.com/bigbluebutton/bigbluebutton/issues/6042

**Comment by mkpelletier** [comment] 2019-08-23 11:41
Brilliant stuff, as always.  I am looking forward to it!

**Comment by mtsonline** [comment] 2020-04-07 15:30
maybe you can separate speaking and raisingHand users completely from other users and users with other emoji status set.
the raisingHand users should be clearly visible also for visually impaired users.
bright colour background and other position on the page.
same for speaking users.

and even more important: please use live area regions so screenreaders tell the users about this changes.

And a last one: A button and keyboard shortcut to raiseHand would be very important too.

thanks for all your work.

**Comment by Nick-Netizen** [comment] 2020-05-06 19:48
This might be a duplicate of [#9072](https://github.com/bigbluebutton/bigbluebutton/issues/9072).

**Comment by pedrobmarin** [comment] 2021-04-04 21:34
Moving this discussion to #9072

**Closed by pedrobmarin** 2021-04-04 21:34 UTC
