### ISSUE TITLE
First attendee can start conference

### ISSUE THREAD

**Issue by miny1997** [bigbluebutton/bigbluebutton#10768] opened 2020-11-04 03:18 UTC
**Is your feature request related to a problem? Please describe.**
If I join a brand new meeting as a attendee, the system requires a moderator to be present in the conference first to let me in.

**Describe the solution you'd like**
An boolean flag in /api/create which let's indicate that a conference can be started by the first person joining in.

**Describe alternatives you've considered**
An API call to start a conference by giving it the meeting ID.

**Comment by matiasilva** [comment] 2020-11-04 07:36
Hi, that's not actually true. You can join a conference as an attendee and be the first person. You can verify this on demo.bigbluebutton.org and tick "Allow anyone to start the room".

**Comment by miny1997** [comment] 2020-11-04 12:27
Ok, how do I set this by the BigBlueButton API?

**Comment by matiasilva** [comment] 2020-11-05 07:38
The create call is idempotent, so just call it when a user requests to join. Closing this as it's not a bug/feature request.

**Closed by matiasilva** 2020-11-05 07:38 UTC
Labels: Enhancement

**Comment by miny1997** [comment] 2020-11-06 08:43
I found the issue. I created a room with the guest policy ASK_MODERATOR and even if my join link does not indicate that attendees are guests, they still need moderator approval.
