### ISSUE TITLE
More video sources for sharing in BBB chat

### ISSUE THREAD

**Issue by FreeScholar** [bigbluebutton/bigbluebutton#11213] opened 2021-01-23 22:16 UTC
**Is your feature request related to a problem? Please describe.**
Not a true problem, but a request --
Adding more video sources for users to post and share in BBB. Would like to post videos from lbry odysee.com

**Describe the solution you'd like**
Would like to post videos from https://lbry.tv/ and https://odysee.com like this one:
https://cdn.lbryplayer.xyz/api/v4/streams/free/The-Hated-One(480px)---Monero--More-Anonymous-Than-Cash/382baa2856ccf37c8dfd7c783064c3d4623e05c9/be220f

**Comment by basisbit** [comment] 2021-01-24 00:08
Duplicate of #10861

**Closed by basisbit** 2021-01-24 00:08 UTC
Labels: Enhancement
