### ISSUE TITLE
/mnt/mongo-ramdisk was 100% (BigBlueButton stopped loading at 3 dots)

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#11185] opened 2021-01-20 12:19 UTC
**Describe the bug**
The directory `/mnt/mongo-ramdisk` was at 100% on https://test.bigbluebutton.org/.

We leave this server running for users to test BigBlueButton.  After restarting BigBlueButton the size went back to normal

**To Reproduce**
Not available.

**Expected behavior**
The size of `/mnt/mongo-ramdisk` should stay constant under sustained load.

**Actual behavior**

**Screenshots**
Here's a list 

```
root@test:/mnt/mongo-ramdisk# df
Filesystem      1K-blocks     Used  Available Use% Mounted on
udev             16410148        0   16410148   0% /dev
tmpfs             3283768   400384    2883384  13% /run
/dev/md3       1919629232 61648584 1760446036   4% /
tmpfs            16418824    14180   16404644   1% /dev/shm
tmpfs                5120        0       5120   0% /run/lock
tmpfs            16418824        0   16418824   0% /sys/fs/cgroup
/dev/md1          1014616    78908     866952   9% /boot
tmpfs              524288   524288          0 100% /mnt/mongo-ramdisk
tmpfs             3283768        0    3283768   0% /run/user/0
root@test:/mnt/mongo-ramdisk# ls -al
total 436
drwxrwxrwt 5 mongodb mongodb    280 Jan 20 10:27 .
drwxr-xr-x 3 root    root      4096 May  4  2018 ..
drwxr-xr-x 2 mongodb mongodb    700 Dec 17 03:47 collection
drwxr-xr-x 2 mongodb mongodb    480 Jan 20 10:27 diagnostic.data
drwxr-xr-x 2 mongodb mongodb   1260 Dec 17 03:47 index
-rw-r--r-- 1 mongodb mongodb  73728 Dec 18 14:36 _mdb_catalog.wt
-rw-r--r-- 1 mongodb mongodb      6 Dec 17 02:14 mongod.lock
-rw-r--r-- 1 mongodb mongodb  36864 Jan 20 10:27 sizeStorer.wt
-rw-r--r-- 1 mongodb mongodb     95 Dec 17 02:14 storage.bson
-rw-r--r-- 1 mongodb mongodb     49 Dec 17 02:14 WiredTiger
-rw-r--r-- 1 mongodb mongodb   4096 Dec 17 02:14 WiredTigerLAS.wt
-rw-r--r-- 1 mongodb mongodb     21 Dec 17 02:14 WiredTiger.lock
-rw-r--r-- 1 mongodb mongodb   1028 Jan 20 10:27 WiredTiger.turtle
-rw-r--r-- 1 mongodb mongodb 307200 Jan 20 10:27 WiredTiger.wt
```

After a restart, this is the size

```
root@test:/mnt/mongo-ramdisk# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3.2G  393M  2.8G  13% /run
/dev/md3        1.8T   22G  1.7T   2% /
tmpfs            16G   15M   16G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/md1        991M   78M  847M   9% /boot
tmpfs           3.2G     0  3.2G   0% /run/user/0
tmpfs           512M  7.2M  505M   2% /mnt/mongo-ramdisk
root@test:/mnt/mongo-ramdisk# ls -al
total 436
drwxrwxrwt 5 mongodb mongodb    280 Jan 20 13:15 .
drwxr-xr-x 3 root    root      4096 May  4  2018 ..
drwxr-xr-x 2 mongodb mongodb    700 Jan 20 13:13 collection
drwxr-xr-x 2 mongodb mongodb     80 Jan 20 13:15 diagnostic.data
drwxr-xr-x 2 mongodb mongodb   1260 Jan 20 13:13 index
-rw-r--r-- 1 mongodb mongodb  73728 Jan 20 13:13 _mdb_catalog.wt
-rw-r--r-- 1 mongodb mongodb      6 Jan 20 13:11 mongod.lock
-rw-r--r-- 1 mongodb mongodb  36864 Jan 20 13:15 sizeStorer.wt
-rw-r--r-- 1 mongodb mongodb     95 Jan 20 13:11 storage.bson
-rw-r--r-- 1 mongodb mongodb     49 Jan 20 13:11 WiredTiger
-rw-r--r-- 1 mongodb mongodb   4096 Jan 20 13:11 WiredTigerLAS.wt
-rw-r--r-- 1 mongodb mongodb     21 Jan 20 13:11 WiredTiger.lock
-rw-r--r-- 1 mongodb mongodb   1025 Jan 20 13:15 WiredTiger.turtle
-rw-r--r-- 1 mongodb mongodb 307200 Jan 20 13:15 WiredTiger.wt
```

It looks like after restart Ubuntu made more memory available again to the ramdisk.  So it might have been a memory issue that constrained the ramdisk.

Also see this error in `journalctl -u bbb-htm5` log

```
Jan 20 10:31:17 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]: info: Removing Annotations streamer object for meeting d8b90d92baed9788647eb73a0d1450a182a904bd-1611134770383
Jan 20 10:31:17 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]: info: Removing Cursor streamer object for meeting d8b90d92baed9788647eb73a0d1450a182a904bd-1611134770383
Jan 20 10:31:29 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]: info: Skipping heartbeat, because websocket is sending data {"currentTime":1611135089448,"lastSentFrameTimestamp":1611135081910,"userId":"be2fba7907a15f2ae060572f938958212cd8b4f9-1611128195416--w_z16jqc6eymq9"}
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]: error: Error updating lastPing for w_z16jqc6eymq9: MongoNetworkError: connect ECONNREFUSED 127.0.1.1:27017
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]: error: Update voice call state=w_p3lwcfi7dyul: MongoNetworkError: connect ECONNREFUSED 127.0.1.1:27017
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]: error: UserBroadcastCamStartedEvtMsg: Error: connect ECONNREFUSED 127.0.1.1:27017
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:  => awaited here:
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at Function.Promise.await (/usr/share/meteor/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at Promise.asyncApply (packages/mongo/mongo_driver.js:1042:14)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at /usr/share/meteor/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:  => awaited here:
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at Promise.await (/usr/share/meteor/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1091:12)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1105:22)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at SynchronousCursor.map (packages/mongo/mongo_driver.js:1115:10)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1139:17)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:887:44)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at MongoConnection.findOne (packages/mongo/mongo_driver.js:794:56)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at Collection.findOne (packages/mongo/collection.js:356:29)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at getUserName (imports/api/video-streams/server/helpers.js:16:16)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at sharedWebcam (imports/api/video-streams/server/modifiers/sharedWebcam.js:15:16)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at EventEmitter.handleUserSharedHtml5Webcam (imports/api/video-streams/server/handlers/userSharedHtml5Webcam.js:15:10)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at EventEmitter.emitAsync (/usr/share/meteor/bundle/programs/server/npm/node_modules/eventemitter2/lib/eventemitter2.js:463:31)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at MeetingMessageQueue.handleTask (imports/startup/server/redis.js:96:7)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at PowerQueue.runTask (packages/cfs_power-queue.js:596:14)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at PowerQueue.updateThrottleUp (packages/cfs_power-queue.js:402:12)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]:     at PowerQueue.next (packages/cfs_power-queue.js:451:10)
Jan 20 10:31:35 m047.rna1.blindsidenetworks.com systemd_start.sh[21487]: error: Error updating lastPing for w_hhyotkrvoqpj: MongoNetworkError: connect ECONNREFUSED 127.0.1.1:27017
```
**Additional context**
BigBlueButton 2.2.31

**Comment by basisbit** [comment] 2021-01-20 16:55
Workaround for if your servers have plenty of RAM:
Increase MongoDB DB size limit by increasing its ramdisk in /usr/share/meteor/bundle/mongod_start_pre.sh
```
  mount -t tmpfs -o size=1024m tmpfs /mnt/mongo-ramdisk
```

**Comment by coderDem** [comment] 2021-03-14 20:39
Hello,

I got the same problem with the version 2.2.31 on both servers.
Since I don't know what is the problem, I restart every night the server:

`crontab -e

# reboot every night at 10 PM
0 4 *   *   *    /sbin/reboot`

**Comment by ffdixon** [comment] 2021-03-14 21:04
Update to the latest build of BigBlueButton 2.2 -- it now ensures that older content doesn't linger in the database.  

(Please let us know if you encounter the same issue after upgrade!)

**Comment by uka-support** [comment] 2021-03-15 11:07
In the df output, there is

```
Filesystem      1K-blocks     Used  Available Use% Mounted on
tmpfs              524288   524288          0 100% /mnt/mongo-ramdisk
```

So 512 MB of 512 MB used. I looked at one of our servers (2.2.31) which has been running for quite some time now:
```
/mnt/mongo-ramdisk# du -sk *
29236   collection
208732  diagnostic.data
14544   index
68      _mdb_catalog.wt
4       mongod.lock
36      sizeStorer.wt
4       storage.bson
4       WiredTiger
4       WiredTigerLAS.wt
4       WiredTiger.lock
4       WiredTiger.turtle
280     WiredTiger.wt
```

Around 200 MB of diagnostic data -> maybe that should be disabled or limited?

**Comment by basisbit** [comment] 2021-03-15 11:57
@uka-support that is already resolved in current versions of BBB 2.2. Please update your servers and then confirm here if the problem is fixed.

**Comment by uka-support** [comment] 2021-03-15 16:25
Confirmed. BBB 2.2.35 doesn't seem to have the issue. MongoDB has been started 2021-03-08, oldest diagnostic is from 2021-03-10. The other 2.2.31 system has a lot more of these, back to 2021-02-20, although started at 2021-01-13 and not as busy.

I just wanted to point out that the ramdisk memory wasn't the issue as fxdion stated but that the ramdisk was just full according to df's output. Agreed, the diagnostic data probably wasn't the issue.

**Comment by rasos** [comment] 2021-04-07 14:20
We had again the same issue on BBB 2.3alpha8. MongoDB was constantly growing. 

![df-pinpoint=1617340953,1617808377](https://user-images.githubusercontent.com/485723/113881871-1a40ce80-97bd-11eb-9242-1ff57c849839.png)

**Comment by antobinary** [comment] 2021-04-07 14:40
Thanks for the update @rasos !

I just checked the content of `/mnt/mongo-ramdisk` on demo2 (in the demo.bigbluebutton.org pool)
from total 376 MB, 300MB was in `300M	/mnt/mongo-ramdisk/journal/`

So this looks like a log retention issue at least from what I can tell

**Comment by basisbit** [comment] 2021-04-07 14:52
any reason why journaling was enabled for a temporary DB in ramdisk?

**Comment by tdjac0bs** [comment] 2021-04-08 19:02
Hello @basisbit .

In order to tail oplog we need a replicaset. 

Accordingly with [mongo documentation](https://docs.mongodb.com/v4.0/core/journaling/#journaling-and-the-wiredtiger-storage-engine) we need journaling enabled in order to use replica set members.

@jfsiebel is going to try what happens if journaling is disabled ( to be sure ), but I believe it will go into "poll and diff" mode.

**Comment by antobinary** [comment] 2021-04-08 21:30
```
root@demo3:~# sudo du -ah /mnt/mongo-ramdisk
4.0K	/mnt/mongo-ramdisk/WiredTiger.turtle
40K	/mnt/mongo-ramdisk/diagnostic.data/metrics.interim.temp
112K	/mnt/mongo-ramdisk/diagnostic.data/metrics.interim
7.8M	/mnt/mongo-ramdisk/diagnostic.data/metrics.2021-04-05T23-21-34Z-00000
10M	/mnt/mongo-ramdisk/diagnostic.data/metrics.2021-04-05T10-36-34Z-00000
10M	/mnt/mongo-ramdisk/diagnostic.data/metrics.2021-04-04T20-36-34Z-00000
10M	/mnt/mongo-ramdisk/diagnostic.data/metrics.2021-04-04T07-11-34Z-00000
10M	/mnt/mongo-ramdisk/diagnostic.data/metrics.2021-04-03T15-46-34Z-00000
10M	/mnt/mongo-ramdisk/diagnostic.data/metrics.2021-04-03T02-21-34Z-00000
10M	/mnt/mongo-ramdisk/diagnostic.data/metrics.2021-04-02T12-16-34Z-00000
10M	/mnt/mongo-ramdisk/diagnostic.data/metrics.2021-04-01T20-06-28Z-00000
78M	/mnt/mongo-ramdisk/diagnostic.data
36K	/mnt/mongo-ramdisk/index/144--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/142--4471910901717345332.wt
48K	/mnt/mongo-ramdisk/index/139--4471910901717345332.wt
112K	/mnt/mongo-ramdisk/index/138--4471910901717345332.wt
84K	/mnt/mongo-ramdisk/index/135--4471910901717345332.wt
52K	/mnt/mongo-ramdisk/index/134--4471910901717345332.wt
176K	/mnt/mongo-ramdisk/index/131--4471910901717345332.wt
76K	/mnt/mongo-ramdisk/index/130--4471910901717345332.wt
260K	/mnt/mongo-ramdisk/index/127--4471910901717345332.wt
112K	/mnt/mongo-ramdisk/index/126--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/123--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/122--4471910901717345332.wt
96K	/mnt/mongo-ramdisk/index/119--4471910901717345332.wt
52K	/mnt/mongo-ramdisk/index/118--4471910901717345332.wt
140K	/mnt/mongo-ramdisk/index/115--4471910901717345332.wt
64K	/mnt/mongo-ramdisk/index/114--4471910901717345332.wt
12K	/mnt/mongo-ramdisk/index/111--4471910901717345332.wt
4.0K	/mnt/mongo-ramdisk/index/110--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/107--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/106--4471910901717345332.wt
100K	/mnt/mongo-ramdisk/index/103--4471910901717345332.wt
52K	/mnt/mongo-ramdisk/index/102--4471910901717345332.wt
12K	/mnt/mongo-ramdisk/index/99--4471910901717345332.wt
4.0K	/mnt/mongo-ramdisk/index/98--4471910901717345332.wt
176K	/mnt/mongo-ramdisk/index/95--4471910901717345332.wt
68K	/mnt/mongo-ramdisk/index/93--4471910901717345332.wt
76K	/mnt/mongo-ramdisk/index/92--4471910901717345332.wt
64K	/mnt/mongo-ramdisk/index/89--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/88--4471910901717345332.wt
44K	/mnt/mongo-ramdisk/index/85--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/84--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/81--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/80--4471910901717345332.wt
216K	/mnt/mongo-ramdisk/index/77--4471910901717345332.wt
52K	/mnt/mongo-ramdisk/index/76--4471910901717345332.wt
216K	/mnt/mongo-ramdisk/index/73--4471910901717345332.wt
52K	/mnt/mongo-ramdisk/index/72--4471910901717345332.wt
204K	/mnt/mongo-ramdisk/index/69--4471910901717345332.wt
108K	/mnt/mongo-ramdisk/index/67--4471910901717345332.wt
80K	/mnt/mongo-ramdisk/index/66--4471910901717345332.wt
24K	/mnt/mongo-ramdisk/index/63--4471910901717345332.wt
24K	/mnt/mongo-ramdisk/index/61--4471910901717345332.wt
24K	/mnt/mongo-ramdisk/index/60--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/57--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/56--4471910901717345332.wt
192K	/mnt/mongo-ramdisk/index/53--4471910901717345332.wt
108K	/mnt/mongo-ramdisk/index/52--4471910901717345332.wt
60K	/mnt/mongo-ramdisk/index/49--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/48--4471910901717345332.wt
12K	/mnt/mongo-ramdisk/index/45--4471910901717345332.wt
4.0K	/mnt/mongo-ramdisk/index/44--4471910901717345332.wt
952K	/mnt/mongo-ramdisk/index/41--4471910901717345332.wt
240K	/mnt/mongo-ramdisk/index/40--4471910901717345332.wt
48K	/mnt/mongo-ramdisk/index/37--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/36--4471910901717345332.wt
44K	/mnt/mongo-ramdisk/index/33--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/32--4471910901717345332.wt
44K	/mnt/mongo-ramdisk/index/29--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/28--4471910901717345332.wt
44K	/mnt/mongo-ramdisk/index/25--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/24--4471910901717345332.wt
96K	/mnt/mongo-ramdisk/index/21--4471910901717345332.wt
52K	/mnt/mongo-ramdisk/index/20--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/18--4471910901717345332.wt
4.0K	/mnt/mongo-ramdisk/index/16--4471910901717345332.wt
20K	/mnt/mongo-ramdisk/index/14--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/index/12--4471910901717345332.wt
20K	/mnt/mongo-ramdisk/index/9--4471910901717345332.wt
20K	/mnt/mongo-ramdisk/index/7--4471910901717345332.wt
20K	/mnt/mongo-ramdisk/index/5--4471910901717345332.wt
4.0K	/mnt/mongo-ramdisk/index/3--4471910901717345332.wt
20K	/mnt/mongo-ramdisk/index/1--4471910901717345332.wt
5.5M	/mnt/mongo-ramdisk/index
52K	/mnt/mongo-ramdisk/collection/143--4471910901717345332.wt
96K	/mnt/mongo-ramdisk/collection/141--4471910901717345332.wt
140K	/mnt/mongo-ramdisk/collection/137--4471910901717345332.wt
212K	/mnt/mongo-ramdisk/collection/133--4471910901717345332.wt
520K	/mnt/mongo-ramdisk/collection/129--4471910901717345332.wt
644K	/mnt/mongo-ramdisk/collection/125--4471910901717345332.wt
40K	/mnt/mongo-ramdisk/collection/121--4471910901717345332.wt
188K	/mnt/mongo-ramdisk/collection/117--4471910901717345332.wt
860K	/mnt/mongo-ramdisk/collection/113--4471910901717345332.wt
4.0K	/mnt/mongo-ramdisk/collection/109--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/collection/105--4471910901717345332.wt
192K	/mnt/mongo-ramdisk/collection/101--4471910901717345332.wt
4.0K	/mnt/mongo-ramdisk/collection/97--4471910901717345332.wt
612K	/mnt/mongo-ramdisk/collection/91--4471910901717345332.wt
1.4M	/mnt/mongo-ramdisk/collection/87--4471910901717345332.wt
60K	/mnt/mongo-ramdisk/collection/83--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/collection/79--4471910901717345332.wt
336K	/mnt/mongo-ramdisk/collection/75--4471910901717345332.wt
2.1M	/mnt/mongo-ramdisk/collection/71--4471910901717345332.wt
1.4M	/mnt/mongo-ramdisk/collection/65--4471910901717345332.wt
24K	/mnt/mongo-ramdisk/collection/59--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/collection/55--4471910901717345332.wt
680K	/mnt/mongo-ramdisk/collection/51--4471910901717345332.wt
92K	/mnt/mongo-ramdisk/collection/47--4471910901717345332.wt
4.0K	/mnt/mongo-ramdisk/collection/43--4471910901717345332.wt
2.2M	/mnt/mongo-ramdisk/collection/39--4471910901717345332.wt
60K	/mnt/mongo-ramdisk/collection/35--4471910901717345332.wt
52K	/mnt/mongo-ramdisk/collection/31--4471910901717345332.wt
68K	/mnt/mongo-ramdisk/collection/27--4471910901717345332.wt
428K	/mnt/mongo-ramdisk/collection/23--4471910901717345332.wt
504K	/mnt/mongo-ramdisk/collection/19--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/collection/17--4471910901717345332.wt
4.0K	/mnt/mongo-ramdisk/collection/15--4471910901717345332.wt
20K	/mnt/mongo-ramdisk/collection/13--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/collection/11--4471910901717345332.wt
16M	/mnt/mongo-ramdisk/collection/10--4471910901717345332.wt
20K	/mnt/mongo-ramdisk/collection/8--4471910901717345332.wt
36K	/mnt/mongo-ramdisk/collection/6--4471910901717345332.wt
20K	/mnt/mongo-ramdisk/collection/4--4471910901717345332.wt
4.0K	/mnt/mongo-ramdisk/collection/2--4471910901717345332.wt
20K	/mnt/mongo-ramdisk/collection/0--4471910901717345332.wt
29M	/mnt/mongo-ramdisk/collection
4.0K	/mnt/mongo-ramdisk/storage.bson
92K	/mnt/mongo-ramdisk/_mdb_catalog.wt
36K	/mnt/mongo-ramdisk/sizeStorer.wt
4.0K	/mnt/mongo-ramdisk/WiredTigerLAS.wt
364K	/mnt/mongo-ramdisk/WiredTiger.wt
4.0K	/mnt/mongo-ramdisk/WiredTiger
4.0K	/mnt/mongo-ramdisk/WiredTiger.lock
100M	/mnt/mongo-ramdisk/journal/WiredTigerPreplog.0000000013
100M	/mnt/mongo-ramdisk/journal/WiredTigerLog.0000000012
100M	/mnt/mongo-ramdisk/journal/WiredTigerLog.0000000011
100M	/mnt/mongo-ramdisk/journal/WiredTigerPreplog.0000000001
400M	/mnt/mongo-ramdisk/journal
4.0K	/mnt/mongo-ramdisk/mongod.lock
512M	/mnt/mongo-ramdisk
```
Is from demo3

**Comment by antobinary** [comment] 2021-04-09 20:57
A temporary band-aid fix would be to increase the allocated memory from 512MB to 768 or 1024. Not the solution we're looking for but it should give a little bit of breathing room.
@jfsiebel could you please confirm how much of the 512 is used after a reboot with 0 users on?

**Comment by rasos** [comment] 2021-04-10 06:12
Same here, most memory is used for the journal:

```
...
100M	/mnt/mongo-ramdisk/journal/WiredTigerPreplog.0000000002
100M	/mnt/mongo-ramdisk/journal/WiredTigerPreplog.0000000001
100M	/mnt/mongo-ramdisk/journal/WiredTigerLog.0000000001
300M	/mnt/mongo-ramdisk/journal
346M	/mnt/mongo-ramdisk
```

We've increased it, but it is still growing (relative percentage values):

![df-week](https://user-images.githubusercontent.com/485723/114260331-6dd93500-99d4-11eb-9fdd-796a7c69eca2.png)

After a reboot, the values do not change!

**Comment by jfsiebel** [comment] 2021-04-13 16:24
> A temporary band-aid fix would be to increase the allocated memory from 512MB to 768 or 1024. Not the solution we're looking for but it should give a little bit of breathing room.
> @jfsiebel could you please confirm how much of the 512 is used after a reboot with 0 users on?

After restarting `mongod.service` a few times, every time it was using 301 MB of disk space.

**Comment by antobinary** [comment] 2021-04-15 17:59
I think I see a different issue which might be causing the mongo crash

```
root@demo2:~# du -sh /mnt/mongo-ramdisk/
419M	/mnt/mongo-ramdisk/
root@demo2:~# ls -lh /mnt/mongo-ramdisk/diagnostic.data/
total 80M
-rw------- 1 mongodb mongodb  10M Apr 13 03:58 metrics.2021-04-12T15-23-37Z-00000
-rw------- 1 mongodb mongodb  10M Apr 13 12:28 metrics.2021-04-13T03-58-42Z-00000
-rw------- 1 mongodb mongodb  10M Apr 13 21:13 metrics.2021-04-13T12-28-42Z-00000
-rw------- 1 mongodb mongodb  10M Apr 14 07:08 metrics.2021-04-13T21-13-42Z-00000
-rw------- 1 mongodb mongodb  10M Apr 14 14:58 metrics.2021-04-14T07-08-42Z-00000
-rw------- 1 mongodb mongodb  10M Apr 15 00:13 metrics.2021-04-14T14-58-42Z-00000
-rw------- 1 mongodb mongodb  10M Apr 15 09:28 metrics.2021-04-15T00-13-42Z-00000
-rw------- 1 mongodb mongodb 9.9M Apr 15 17:48 metrics.2021-04-15T09-28-42Z-00000
-rw------- 1 mongodb mongodb  80K Apr 15 17:52 metrics.interim
```

We have metrics - in 10MB chunks which take space.

```
root@test23:~# ls -lh /mnt/mongo-ramdisk/diagnostic.data/
total 26M
-rw------- 1 mongodb mongodb  10M Apr 13 23:38 metrics.2021-04-12T20-43-36Z-00000
-rw------- 1 mongodb mongodb  10M Apr 15 03:53 metrics.2021-04-13T23-38-47Z-00000
-rw------- 1 mongodb mongodb 5.4M Apr 15 17:53 metrics.2021-04-15T03-53-47Z-00000
-rw------- 1 mongodb mongodb  23K Apr 15 17:55 metrics.interim
```
^ on a less frequented server

@jfsiebel How much control do we have over these metrics files? Can we keep max 20 MB of them?

Note: **I am strongly considering bumping up the default allocated memory from 512MB to 768MB via packaging in 2.3-beta4**

**Comment by jfsiebel** [comment] 2021-04-15 18:15
According to mongo documentation (https://docs.mongodb.com/manual/reference/parameters/#mongodb-parameter-param.diagnosticDataCollectionFileSizeMB) it's possible to change those files size. By default the maximum size that diagnostic folder could reach is 200 mb (https://docs.mongodb.com/manual/reference/parameters/#mongodb-parameter-param.diagnosticDataCollectionDirectorySizeMB), after reaching the size it starts to remove old files.

**Comment by basisbit** [comment] 2021-04-15 20:26
increasing the memory from 512 to 768MB does neither solve the problem, nor is it necessary for the tiny amount of data.
Those 256MB of extra memory usage would probably break those setups which currently run BBB at 6GB RAM containers.
Alternatively, could `/mnt/mongo-ramdisk/diagnostic.data` be mounted/symlinked to the disk instead?

**Comment by antobinary** [comment] 2021-04-15 20:52
On demo pool I now set

`tail -4 /usr/share/meteor/bundle/mongo-ramdisk.conf `

```
setParameter:
  diagnosticDataCollectionEnabled: false
```

disabling the diagnostics collection altogether

**Comment by basisbit** [comment] 2021-04-15 21:47
On a side note, disabling diagnosticDataCollectionEnabled seems to also severely reduce CPU usage of the MongoDB process (or this might be just caused by having restarted BBB)

**Comment by antobinary** [comment] 2021-05-03 15:29
I have been checking the size of `/mnt/mongo-ramdisk/` on demo2 server (busy server with 200-600 users 24/7) and it has remained in the 320-350MB range, including running it now for 3 days on BBB 2.3.0.

I will be closing this issue now but please comment in future if you encounter any issues in this context and we can reopen! Thanks to all who commented!

**Closed by antobinary** 2021-05-03 15:29 UTC
Labels: priority: high

**Comment by rasos** [comment] 2021-05-03 18:25
I can confirm that disabling the diagnostics collection on a BBB 2.3.0 with heavy load the last days solved the issue.

```
# du -h /mnt/mongo-ramdisk/
320M	/mnt/mongo-ramdisk/
```
