### ISSUE TITLE
Does the latest update BBB API able to service native mobile apps?

### ISSUE THREAD

**Issue by deviprasaddayal12** [bigbluebutton/bigbluebutton#14007] opened 2022-01-05 06:51 UTC

**Comment by antobinary** [comment] 2022-01-05 17:50
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/8535
For questions like this it's best to use https://groups.google.com/g/bigbluebutton-dev Here in GitHub issues we track bugs/features

**Closed by antobinary** 2022-01-05 17:50 UTC
Labels: module: core
