### ISSUE TITLE
Does anyone else have problems with Safari on iPad? error 1002

### ISSUE THREAD

**Issue by github-luckow-org** [bigbluebutton/bigbluebutton#9445] opened 2020-05-06 21:14 UTC
**Describe the bug**
Since the last update of BBB, i get an error 1002 with safari on iOS (version 13.4.1) on an iPad (5. generation). Crazy: the same iOS version on an iPhone has no problems.

**To Reproduce**
1. Go to test.bigbluebutton.org on an iPad
2. Click on join with microphone
3. Wait
4. See error 1002

**Comment by basisbit** [comment] 2020-05-07 02:19
Probably a duplicate of #9438

**Comment by matiasilva** [comment] 2020-06-14 09:02
Have you tried testing your WebRTC connection at https.//test.webrtc.org? Safari is known to be troublesome with the HTML5 client. Perhaps try another browser. If this is sufficient, please close this issue.

**Comment by github-luckow-org** [comment] 2020-06-17 21:25
Thanks for the advice. I've tried the test.
Problems with cam not with microphone.
Testing from inside an ipv4 only network.
Changing browsers on iOS in conjunction with bbb :) no you need to use safari.
same behaviour with iOS 13.5.1 & test.bigbluebutton. 1002 for audio and 1020 for video. Crazy.

**Comment by basisbit** [comment] 2020-06-17 21:29
could you please post a screenshot of the result from https://test.webrts.org ?

**Comment by github-luckow-org** [comment] 2020-06-17 22:23
here we go. thanks for your interest.
![IMG_8DEDFA701327-1](https://user-images.githubusercontent.com/2720833/84956608-dd0a3380-b0f9-11ea-88bc-d7271f93c604.jpeg)

**Comment by basisbit** [comment] 2020-06-17 22:26
... please post a screenshot of the result... as in "when the test finished"

**Comment by github-luckow-org** [comment] 2020-06-17 22:27
yeah i know. but there is no "test finished". maybe i not able to wait more than 25 minutes to finish this test. that is all i got.

**Comment by basisbit** [comment] 2020-06-17 22:29
The test should finish within a minute or so. Could you maybe try again?

**Comment by github-luckow-org** [comment] 2020-06-17 22:37
Guess what. I've tried it again and again. Everytime the same "result". -> no result "test finished".
Because I read about other problems with iOS and no one had similar problems with "my special" problem, i decided to do a "factory restore" later this week. Maybe this helps to solve my problem.
I don't think it's a BBB problem. But what i've learned: WebRTC-Bugs are #computervoodoo :)
I will close this issue. Thank you for your engagement.

**Closed** 2020-06-17 22:39 UTC
Labels: HTML5 Client
