### ISSUE TITLE
ios 13.2.3 , Safari  Logout  Waiting for a long time without successful exit 

### ISSUE THREAD

**Issue by fungma** [bigbluebutton/bigbluebutton#8413] opened 2019-12-10 02:31 UTC
2.2-RC-3 and and previous versions

iPhone 11 ,ios 13.2.3 , Safari， click  Logout ， Waiting for a long time without successful exit.

We have to manual shut the Safari tab, Otherwise, the other viewer can hear my cell phone'mic talking.

**Comment by fungma** [comment] 2019-12-10 02:39
iPhone 11 ,ios 13.2.3 

Now
We test Chrome in iPhone, bigbluebutton tell me to use Safari for full support.
We test Firefox in iPhone, bigbluebutton  tell me to use Chrome or Firefox for for full support.

Why bigbluebutton  show different warnings?

**Comment by ffdixon** [comment] 2019-12-10 10:35
Regarding,

> We test Firefox in iPhone, bigbluebutton tell me to use Chrome or Firefox for for full support.

Thanks for reporting this, we opened an new issue to track it: https://github.com/bigbluebutton/bigbluebutton/issues/8414

**Comment by ffdixon** [comment] 2019-12-10 10:38
> iPhone 11 ,ios 13.2.3 , Safari， click Logout ， Waiting for a long time without successful exit.
> We have to manual shut the Safari tab, Otherwise, the other viewer can hear my cell phone'mic talking.

Tested on RC-4 and found the issue.  However, did a quick test on beta-21 and the logout works, so it looks like a regression.

**Comment by Dezit-Suda** [comment] 2020-04-17 06:16
Currently I am using "BIGBLUEBUTTON_RELEASE = 2.2.5", but the same phenomenon occurs.

I will report the situation confirmed by us.
    - This phenomenon occurs when you log out from the "joined meeting".
    - It does not occur when logging out from the "held conference" on the iSO side.

I hope that the module with the resolved problem will be released.

**Comment by Dezit-Suda** [comment] 2020-04-23 05:08
I confirmed the same phenomenon with FireFox.
The server used is "BigBlueButton 2.2.5".
The "bigbluebutton.access.log" when the phenomenon occurs is shown below.

---
For Android Chrome
```
192.168.---.--- - - [23/Apr/2020:13:03:43 +0900] "GET /bbb-webrtc-sfu?sessionToken=nq9jbwn9sjwos5hr HTTP/1.1" 101 16566 "-" "Mozilla/5.0 (Linux; Android 9; F1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.111 Mobile Safari/537.36"
192.168.---.--- - - [23/Apr/2020:13:03:43 +0900] "GET /html5client/sockjs/509/y2sakzb8/websocket HTTP/1.1" 101 12867 "-" "Mozilla/5.0 (Linux; Android 9; F1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.111 Mobile Safari/537.36"
192.168.---.--- - - [23/Apr/2020:13:03:43 +0900] "GET /ws HTTP/1.1" 101 3217 "-" "Mozilla/5.0 (Linux; Android 9; F1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.111 Mobile Safari/537.36"
192.168.---.--- - - [23/Apr/2020:13:03:43 +0900] "GET /html5client/resources/sounds/LeftCall.mp3 HTTP/1.1" 304 0 "https://******.jp/html5client/join?sessionToken=nq9jbwn9sjwos5hr" "Mozilla/5.0 (Linux; Android 9; F1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.111 Mobile Safari/537.36"
```
**Dialog is displayed**

---
For iPad Safari
```
192.168.---.--- - - [23/Apr/2020:13:20:36 +0900] "GET /bbb-webrtc-sfu?sessionToken=lefru9r80tbu6yba HTTP/1.1" 101 28761 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15"
192.168.---.--- - - [23/Apr/2020:13:20:36 +0900] "GET /html5client/locale?locale=ja&init=true HTTP/1.1" 200 12183 "https://******.jp/html5client/join?sessionToken=lefru9r80tbu6yba" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15"
```
**No dialog is displayed, blackout**

---
For FireFox
```
192.168.---.--- - - [23/Apr/2020:12:42:38 +0900] "GET /bbb-webrtc-sfu?sessionToken=f2esjgrhc2vudfn9 HTTP/1.1" 101 12597 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0"
192.168.---.--- - - [23/Apr/2020:12:42:38 +0900] "GET /html5client/locale?locale=ja&init=true HTTP/1.1" 200 12183 "https://******.jp/html5client/join?sessionToken=f2esjgrhc2vudfn9" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0"
```
**No dialog is displayed, blackout**

---

Look at the log and it fails to log out, it looks like it's frozen by calling "**GET /html5client/locale?**".
This happens when you join an **existing meeting** and then **log out**.

We hope for your reference.

**Comment by antobinary** [comment] 2021-07-31 13:35
Can't reproduce on the latest BBB

**Closed by antobinary** 2021-07-31 13:35 UTC
Labels: module: client
