### ISSUE TITLE
Pressing the undo button rapidly disconnects everyone from the meeting

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2274] opened 2015-08-12 08:04 UTC
Originally reported on Google Code with ID 1522
```
This is an issue to track the bug reported here, https://groups.google.com/d/msg/bigbluebutton-dev/wVhb3-lyU2s/Q1s4rudrxUkJ.

I'm reporting a bug with 0.81 instability when using "undo" on the whiteboard.

If you draw some annotations, then remove them all by clicking "undo" in quick succession,
ALL participants become disconnected from the meeting the moment the last annotation
is removed. This bug is highly reproducible (I've reproduced it many times now). See
the attached video for a demo. It happens when "undo" is clicked a large number of
times in quick succession to remove a large annotation.

Thanks, Andy



```

Reported by `capilkey` on 2013-05-22 21:51:38

**Comment by ffdixon** [comment] 2016-01-21 05:27
Closing as I'm unable to reproduce this in the latest build of BigBlueButton 1.0-beta (it was probably fixed earlier).

**Closed by ffdixon** 2016-01-21 05:27 UTC
Labels: Accepted, Defect, Normal Priority, Stability, Whiteboard
