### ISSUE TITLE
Conformation modal for removing users missing

### ISSUE THREAD

**Issue by christianwolters** [bigbluebutton/bigbluebutton#9614] opened 2020-05-20 07:14 UTC
**Describe the bug**
It es very likely to remove a user from a BBB session by accident as all context menu options are closly positioned and there is no confirmation dialog.
(This is not directly related but issue #9608 reminded me of this bug.)

**To Reproduce**
1. Go to user list on the left side
2. Click on the user you want to remove
3. Click 'Remove user'

**Expected behavior**
The moderator is asked for confirmation via modal dialog

**Actual behavior**
Users are directly ejected from the session without confirmation.

**Screenshots**
This kind of confirmation modal is already implented when a moderator wants to end a session. It would be very helpful to also have this modal for the 'remove user' function

![grafik](https://user-images.githubusercontent.com/2005580/82416269-093e8000-9a7a-11ea-859f-017884753f7e.png)

**Comment by louim** [comment] 2020-05-20 16:09
Are you using the latest version of BBB? This was added in https://github.com/bigbluebutton/bigbluebutton/pull/9475 which is included in https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.10

**Comment by antobinary** [comment] 2020-05-20 17:20
Duplicate of 9475

**Closed by antobinary** 2020-05-20 17:20 UTC
Labels: HTML5 Client

**Comment by christianwolters** [comment] 2020-05-22 06:13
Oh sorry, I'm new to BBB, you are releasing really fast : D

**Comment by christianwolters** [comment] 2020-05-22 09:59
One question though, as I haven't found the correct documentation:

The feature from #9475 is working, but the texts are not localized:

- Are the translations from transifex part of a future release,
- or are they automatically pulled by every bbb-node
- or do I have to run a script on every bbb-node

Best regards
Christian

**Comment by louim** [comment] 2020-05-22 17:44
I think @antobinary may have a more definitive anwser, but the translation seems to be pulled from [time to time into the repo](https://github.com/bigbluebutton/bigbluebutton/commit/c9faef96c92ec71d470c3c77819a4a0e9dc44e75).

**Comment by antobinary** [comment] 2020-05-22 19:00
Hi @christianwolters ,
The pull request #9475 (and just recently reiterated #9640 and #9642 ) introduced these strings. So the strings only became available in Transifex when we merged those PRs. It takes some time for the community to translate them. I just pulled whatever was available in Transifex( #9641 ) because we are working hard on putting out a new minor release out (2.2.12). Given that we only allowed for a few hours between the introduction of the [latest version of the] strings to Transifex and pulling the locales, it is likely that the strings will be unlocalized in most languages until the next minor release (2.2.13)
