### ISSUE TITLE
Presentation screen stuck on "Slides generated..." inconsistently 

### ISSUE THREAD

**Issue by iantaylor** [bigbluebutton/bigbluebutton#9551] opened 2020-05-15 13:57 UTC
**Describe the bug**

I apologize for the lack of information, we are struggling to reproduce this consistently or find any errors that may be happening when we do see the issue. I thought I would submit this in case anyone else may have run into the same issue or has more information.

Inconsistently in classes when viewing the upload presentation screen the default presentation displays "Slides generated...", we are still able to upload presentations but are not able to switch back to the default when this happens.

**To Reproduce**
1. Start a new Virtual Class
2. Click on the upload presentation screen
3. See the "Slides generated..." message
3. Upload and switch to a new presentation
4. See error with not being able to switch back to the default

**Screenshots**
![DefaultSlideStuck](https://user-images.githubusercontent.com/123982/82058202-cdcb3c80-969a-11ea-843b-f685388895f4.JPG)

**BBB version (optional):**
2.2.5

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 81.0.4044.138

**Comment by basisbit** [comment] 2020-05-15 15:25
can you reproduce this at https://test.bigbluebutton.com ?

**Comment by iantaylor** [comment] 2020-05-15 15:49
> Thank you for this great first issue! Can you please try to reproduce this at https://test.bigbluebutton.com ?

I tried several times but was not able to reproduce it there. But that being said it also took several weeks before it happened to me on our system. We run about 30 - 40 classes each morning and generally about 1 or 2 of them mention this happened to them, but not every day. We will dig deeper in our logs to see if we can find anything.

**Comment by pedrobmarin** [comment] 2021-04-04 21:38
I'm closing since seems staled. If anything new, please don't hesitate in opening a new issue.

**Closed by pedrobmarin** 2021-04-04 21:38 UTC
Labels: module: client
