### ISSUE TITLE
[Suggestion] BreakoutRooms

### ISSUE THREAD

**Issue by deLinhuberin** [bigbluebutton/bigbluebutton#9869] opened 2020-06-18 10:46 UTC
We used BBB for our online congress - worked well, thank you all a lot!
https://meet.gwdg.de/b worked for ~250 participants (just listening of course)
We missed:
- naming for breakout rooms
- more than 8 breakout rooms for building smaller work groups
- recording / saving the white board in breakout rooms
- (re-)entering a breakout room after loss of connection or participating late

**Comment by matiasilva** [comment] 2020-06-18 11:17
Hello! Thanks for this. I'll address your points in order:

1. There is a way to do this via the API but is yet to be implemented. I could have sworn I saw an issue about this here but I can't. So I encourage you to open a new issue with this feature request so we can keep track of this.
2. Duplicate of #8657
3. As of yet, recording of breakout rooms isn't enabled. Saving the whiteboard in general isn't implemented. I invite you to open a feature request for the first. The second is already here: #4882
4. This already exists. Simply invite the user to the breakout room from the main screen or enable the "allow user to join the room" option so they can choose where to go.

If you wish to discuss development of these features, you can subscribe and post to https://groups.google.com/forum/#!forum/bigbluebutton-dev. If you wish to guarantee that these features make it into BBB, I encourage you to reach out to the companies that provide commercial support as they are the ones developing and making major contributions to BBB for everyone: https://bigbluebutton.org/commercial-support/.

**Closed by matiasilva** 2020-06-18 11:17 UTC
