### ISSUE TITLE
Html5 client webcam not working on test

### ISSUE THREAD

**Issue by abertranb** [bigbluebutton/bigbluebutton#6739] opened 2019-02-08 11:36 UTC
Hi! I did a test on https://test.bigbluebutton.org and using my phone (Android) and Chrome 72.0.3626.76 I get this error
![screenshot_20190208_123156_com android chrome](https://user-images.githubusercontent.com/854229/52476139-0b8b0c80-2b9e-11e9-91d0-371c604bff71.jpg)
But using from computer works fine

Any idea?

**Comment by antobinary** [comment] 2019-02-08 15:03
Hi @abertranb 
Could you please provide some more detail:
1) If you retry sharing your webcam on your android device _but on WiFi connection_ instead, are you able to share?
2) Is your device Huawei by any chance? There were some issues with webrtc with that make a few months ago and knowing the producer could help narrow down the problem you're experiencing.

In future please post questions like this one on the Google mailing lists https://groups.google.com/forum/#!forum/bigbluebutton-users (or bigbluebutton-dev, etc)

**Comment by abertranb** [comment] 2019-02-08 20:13
Dear @antobinary I test it with and without wifi. But my device is a huawei

Thanks

**Comment by capilkey** [comment] 2019-02-08 21:48
The error message that the client shows isn't the most descriptive, but Huawei phones won't be able to use WebRTC video on test.bigbluebutton.org. The problem is because of the lack of comprehensive codec support on the different mobile platforms. There's two main video codecs (h264 and VP8) and iOS only supports h264 and Chinese phones like Huawei only support VP8. If we want to support both the server will need to transcode one codec into the other on demand so that they can work with each other. The transcoding takes a lot of CPU and adds a delay to the stream. By default BigBlueButton is configured to only support h264 because in North America there aren't a lot of Huawei devices in the wild and the iOS market share is large. We do have a configuration option in BBB to loosen the codec requirements and allow any video codecs, but it is opt-in for the administrator of the server. If you have your own BBB server you can edit `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml` and set `codec_video_main: "ANY"` and `codec_video_content: "ANY"`.

**Comment by matiasilva** [comment] 2020-06-15 23:47
Closing as an adequate response has been provided.

**Closed by matiasilva** 2020-06-15 23:47 UTC
