### ISSUE TITLE
Add ability for user to save current whiteboard as PDF

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2484] opened 2015-08-12 08:36 UTC
Originally reported on Google Code with ID 1732

```
after loading ablank pdf file to make changes or write on it 
how to save what have been writen on that blank pdf file 
```

Reported by `smartxman2010` on 2014-03-06 00:10:32

**Comment by herzkerl** [comment] 2021-01-21 14:35
@GhaziTriki Possible duplicate/similar to #4882?

**Comment by pedrobmarin** [comment] 2021-04-13 01:22
Duplicate of #4882

**Closed by pedrobmarin** 2021-04-13 01:22 UTC
Labels: component: whiteboard, priority: normal, type: enhancement
