### ISSUE TITLE
Whiteboard does not appear in screen

### ISSUE THREAD

**Issue by nrakurniawan** [bigbluebutton/bigbluebutton#8136] opened 2019-09-19 15:04 UTC
I have this problem, after finished install BBB on my server then try BBB Demo server. The whiteboard does not appear on the screen, and also I cannot upload a presentation file. how to fixed it?

note : I can use youtube sharing and screen sharing.

Regards,
Hendra
![bbb-whiteboard](https://user-images.githubusercontent.com/55402943/65255329-e1cc9780-db27-11e9-8bb1-eca7552706c2.JPG)

**Comment by ffdixon** [comment] 2019-09-19 21:58
Can you past in below the output of `bbb-conf --check` (you can mask out your hostname)

**Comment by nrakurniawan** [comment] 2019-09-20 00:35
@ffdixon ... this is output for bbb-conf --check

```
hendra@bbb:~$ sudo bbb-conf --check
[sudo] password for hendra:

BigBlueButton Server 2.2.0-beta-20 (1416)
                    Kernel version: 4.4.0-164-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8004 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.example.ac.id
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bbb.example.ac.id
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://bbb.example.ac.id
                              red5: bbb.example.ac.id
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 36.89.46.5
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.example.ac.id
                 playback_protocol: https
                            ffmpeg: 4.1.3-0york1~16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 36.89.46.5

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 36.89.46.5
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 36.89.46.5
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 721
                        kurentoUrl: wss://bbb.example.ac.id/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 10.20.105.19
#   /etc/nginx/sites-available/bigbluebutton: bbb.example.ac.id
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 10.20.105.19
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: bbb.example.ac.id

# Warning: The voice application may not have registered with the sip server.
#   Try running:
#
#      bbb-conf --clean
#

.
# Error: FreeSWITCH is listening on IP address 36.89.46.5 for SIP calls, but
# The IP address (10.20.105.19) set bbb.sip.app.ip.
#

# Warning: The setting of 36.89.46.5 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (10.20.105.19).
# (This is OK if you've manually changed the values)

# Warning: The setting of 10.20.105.19
36.89.46.5 for local_ip_v4 in
#
#    /opt/freeswitch/etc/freeswitch/vars.xml
#
# does not match the local IP address (10.20.105.19).
# (This is OK if you've manually changed the values)

# Warning: The API demos are installed and accessible from:
#
#    https://bbb.example.ac.id
#
# and
#
#    https://bbb.example.ac.id/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Warning: The IMS Learning Tools Integration (LTI) is accessible from:
#
#    https://bbb.example.ac.id/lti/tool
#
# To get the access parameters for LTI, run the command
#
#    bbb-conf --lti
```

**Comment by ffdixon** [comment] 2019-09-20 01:04
Can you check the output of the Javascript console to see if there are any network errors that failed to load content from your server.

If there are no errors, could you try updating the installation using the [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) command and then let us know if the whiteboard appears.

**Comment by capilkey** [comment] 2019-09-20 17:28
When the client looks like that it usually means that the SVGs weren't successfully created or the HTML5 server is unable to download the slides to find their size. I would check the HTML5 logs after starting a meeting to see if there are errors related to the slides.

journalctl -u bbb-html5

**Comment by otdftr** [comment] 2019-10-04 17:29
Same picture here: 
- I, too, can only see the navbar as in https://github.com/bigbluebutton/bigbluebutton/issues/8136#issue-495859128 above when entering a room
- default presentation is not shown 
- presentation upload fails
- everything else works fine (chat, screen sharing, audio & video)

## Our Setup
- I have a 1-page default PDF presentation in place which can be used as a whiteboard.
````
# Default Uploaded presentation file
beans.presentationService.defaultUploadedPresentation=${bigbluebutton.web.serverURL}/bigbluebutton/presentation/default.pdf
````
- when I enter my room, the presentation is converted and a structure is built like:
````
 # ls -Rl /var/bigbluebutton/presentation/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926
/var/bigbluebutton/presentation/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926:
total 4
drwxr-xr-x 3 bigbluebutton bigbluebutton 4096 Oct  4 17:53 f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926

/var/bigbluebutton/presentation/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926:
total 4
drwxr-xr-x 6 bigbluebutton bigbluebutton 4096 Oct  4 17:53 d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1570204406331

/var/bigbluebutton/presentation/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1570204406331:
total 44
-rw-r--r-- 1 bigbluebutton bigbluebutton 24654 Oct  4 17:53 d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1570204406331.pdf
drwxr-xr-x 2 bigbluebutton bigbluebutton  4096 Oct  4 17:53 pngs
drwxr-xr-x 2 bigbluebutton bigbluebutton  4096 Oct  4 17:53 svgs
drwxr-xr-x 2 bigbluebutton bigbluebutton  4096 Oct  4 17:53 textfiles
drwxr-xr-x 2 bigbluebutton bigbluebutton  4096 Oct  4 17:53 thumbnails

/var/bigbluebutton/presentation/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1570204406331/pngs:
total 16
-rw-r--r-- 1 bigbluebutton bigbluebutton 14831 Oct  4 17:53 slide-1.png

/var/bigbluebutton/presentation/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1570204406331/svgs:
total 24
-rw-r--r-- 1 bigbluebutton bigbluebutton 20566 Oct  4 17:53 slide1.svg

/var/bigbluebutton/presentation/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1570204406331/textfiles:
total 4
-rw-r--r-- 1 bigbluebutton bigbluebutton 41 Oct  4 17:53 slide-1.txt

/var/bigbluebutton/presentation/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1570204406331/thumbnails:
total 4
-rw-r--r-- 1 bigbluebutton bigbluebutton 1502 Oct  4 17:53 thumb-1.png
````
- I can access the slide e.g. by surfing to the link below, so I think the default presentation, conversion, directories are all OK:  `https:/OURSERVER/bigbluebutton/presentation/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1570204406331/pngs/slide-1.png`

- when trying an upload, the Chrome JS console shows a 404 and a strange POST path - and nothing is recorded in `/var/log/bigbluebutton/bbb-web.log`at all 
````
# Chrome JS console error
c88d10b8dbb8c2efe22ea77e8443ae17bce377f7.js?meteor_js_resource=true:125 POST https://OURSERVER/bigbluebutton/presentation/PresUploadToken-gl94al61DEFAULT_PRESENTATION_POD-w_xiywq2ktcs21/upload 404 (Not Found)
{code: 404, message: "Not Found"}
[18:45:40:0131] ERROR: clientLogger: Presentation uploader catch error on confirm 
````
````
# /var/log/nginx/error.log snippet - even after `chmod 777 /var/bigbluebutton/presentation/`
...
2019/10/04 17:57:24 [error] 29032#29032: *70 open() "/var/bigbluebutton/presentation/PresUploadToken-9dhv7slpDEFAULT_PRESENTATION_POD-w_xiywq2ktcs21/upload" failed (2: No such file or directory), client: 134.19.109.24, server: vc.ard-zdf-medienakademie.de, request: "POST /bigbluebutton/presentation/PresUploadToken-9dhv7slpDEFAULT_PRESENTATION_POD-w_xiywq2ktcs21/upload HTTP/1.1", host: "vc.ard-zdf-medienakademie.de", referrer: "https://vc.ard-zdf-medienakademie.de/html5client/join?sessionToken=7lkak6cqynitd5s9"
...
````
````
# /var/log/bigbluebutton/bbb-web.log snippet
2019-10-04T17:53:26.325+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#downloadAndProcessDocument(https://OURSERVER/bigbluebutton/presentation/default.pdf, f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926, )
2019-10-04T17:53:26.331+02:00 DEBUG o.b.p.PresentationUrlDownloadService - Creating dir [/var/bigbluebutton/presentation/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1570204406331]
...
data={"duration":0,"record":true,"logCode":"meeting_started","name":"Home Room","description":"Meeting has started.","meetingId":"f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926","externalMeetingId":"41c3aacf2fab756fde08bd4f3e2a92ed8fd3f1ee","isBreakout":false}
2019-10-04T17:53:26.671+02:00 INFO  o.b.web.controllers.ApiController - Session sessionToken for XXXXn [null]
2019-10-04T17:53:26.672+02:00 INFO  o.b.web.controllers.ApiController - Session user-token for XXXXn [null]
...
2019-10-04T17:53:26.681+02:00 INFO  o.b.web.controllers.ApiController - Redirecting to https://OURSERVER/html5client/join?sessionToken=7lkak6cqynitd5s9
data={"current":true,"filename":"default.pdf","logCode":"presentation_conversion_start","meetingId":"f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926","message":"Start presentation conversion.","podId":"DEFAULT_PRESENTATION_POD","presId":"d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1570204406331"}
2019-10-04T17:53:31.447+02:00 INFO  o.b.p.SupportedDocumentFilter - Received supported file /var/bigbluebutton/presentation/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1570204406331/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1570204406331.pdf
...
2019-10-04T17:53:34.787+02:00 INFO  o.b.w.services.turn.StunTurnService -
StunTurnService::getStunAndTurnServersFor w_xiywq2ktcs21
2019-10-04T18:08:45.116+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#index
2019-10-04T18:08:45.128+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#index
2019-10-04T18:17:06.770+02:00 INFO  o.b.w.services.turn.StunTurnService -
StunTurnService::getStunServers
2019-10-04T18:17:06.770+02:00 INFO  o.b.w.services.turn.StunTurnService -
StunTurnService::getStunAndTurnServersFor w_xiywq2ktcs21
2019-10-04T18:17:11.513+02:00 INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"role":"MODERATOR","externalUserId":"gl-ltfwujwxjgpu","logCode":"user_left_message","name":"Home Room","description":"User left the meeting.","meetingId":"f381776e5a7abf85970dec68822a322362f8e9cb-1570204405926","externalMeetingId":"41c3aacf2fab756fde08bd4f3e2a92ed8fd3f1ee","guest":false,"guestStatus":"ALLOW","userId":"w_xiywq2ktcs21","username":"XXXXn"}
````
- When, just for a change, I modified `presentationDir` in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` to read `presentationDir=/var/bigbluebutton/` instead of `/var/bigbluebutton/presentation` -
    * the default slide **was shown** upon entering a room
    * but uploads still did not work
    * (and the presentation dirs `f381776e5a7abf859...` appeared in `/var/bigbluebutton/` rather than `/var/bigbluebutton/presentation/` as exspected)


## Conclusion

So, to cut a long story short, I suspect some pathname mangling / filename operations in the html5 client to be at fault, because:
- presentationDir settings are obviously ignored by the client (or are hardcoded there / just not communicated to the client / or a default value gets applied)
- nothing appears in the servers logs when trying to upload a presentation file, but there should be at least an indication of a 404 ... so the upload POST does not get past the nginx webserver, if at all

## Data about our installation

I installed BBB step-by-step following `http://docs.bigbluebutton.org/2.2/install.html#step-by-step`.

Finally, this is the output of `bbb-conf --check`:
````
# bbb-conf --check

BigBlueButton Server 2.2.0-beta-18 (1273)
                    Kernel version: 4.15.0-55-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 65837 MB
                         CPU cores: 12

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://OURSERVER
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: OURSERVER
                              port: OUR_IPV4_ADDR:80127.0.0.1:80, [OUR_IPV6_ADDR]:80, [::1]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://OURSERVER
                              red5: OURSERVER
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: OUR_IPV4_ADDR
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: OUR_IPV4_ADDR:5066
                       wss-binding: OUR_IPV4_ADDR:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: OURSERVER
                 playback_protocol: https
                            ffmpeg: 4.1.3-0york1~16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: OUR_IPV4_ADDR

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: OUR_IPV4_ADDR
                       kurento.url: ws://OURSERVER:8888/kurento
                    localIpAddress: OUR_IPV4_ADDR
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 614
                        kurentoUrl: wss://OURSERVER/bbb-webrtc-sfu
                  enableListenOnly: true


** Potential problems described below **

#
````

**Comment by capilkey** [comment] 2019-10-04 19:33
@otdftr 

> When, just for a change, I modified presentationDir in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties to read presentationDir=/var/bigbluebutton/ instead of /var/bigbluebutton/presentation -

That's the cause. Changing the presentationDir property in bigbluebutton.properties only affects bbb-web. There's also another location that needs to be changed so that nginx knows where to serve up the presentations from. Edit /etc/bigbluebutton/nginx/presentation-slides.nginx and change the directory paths to match where you're storing the presentations.

For the upload problem it looks like you might have other issues with your nginx configurations. I've attached the default web.nginx file so you can compare it with what you have on your BigBlueButton server.
 
[web.nginx](https://github.com/bigbluebutton/bigbluebutton/files/3692019/bbb-web_nginx.txt)

**Comment by otdftr** [comment] 2019-10-06 10:16
@capilkey Thanks for the advice and for pointing me to the right file(s). I can confirm that

-  the presentation display problem is solved by putting the right paths into **/etc/bigbluebutton/nginx/presentation-slides.nginx**
- the upload / upload-test problem was caused by a forgotten location entry for .../presentation/... in **/etc/nginx/sites-available/bigbluebutton** that bybassed the proxy_pass to the tomcat webservice (arrgh!) and triggered nginx's 404 

With both issues fixed, presenations display and upload are both working fine.

**Comment by raheelrobson** [comment] 2020-04-03 09:58
I am having same issue. please help me.
what is the right path for /etc/bigbluebutton/nginx/presentation-slides.nginx
the output of sudo nano /etc/bigbluebutton/nginx/presentation-slides.nginx 
is 
 location ~^\/bigbluebutton\/presentation\/(?<meeting_id_1>[A-Za-z0-9\-]+)\/(?<meeting_id_2>[A-Za-z0-9\-]+)\/(?<pres_id>[A-Za-z0-9\-]+)\/svg\/(?<page_num>\d+)$ {
                default_type image/svg+xml;
                alias    /var/bigbluebutton/$meeting_id_2/$meeting_id_2/$pres_id/svgs/slide$page_num.svg;
        }

        location ~^\/bigbluebutton\/presentation\/(?<meeting_id_1>[A-Za-z0-9\-]+)\/(?<meeting_id_2>[A-Za-z0-9\-]+)\/(?<pres_id>[A-Za-z0-9\-]+)\/slide\/(?<page_num>\d+)$
                alias    /var/bigbluebutton/$meeting_id_2/$meeting_id_2/$pres_id/slide-$page_num.swf;
        }

        location ~^\/bigbluebutton\/presentation\/(?<meeting_id_1>[A-Za-z0-9\-]+)\/(?<meeting_id_2>[A-Za-z0-9\-]+)\/(?<pres_id>[A-Za-z0-9\-]+)\/thumbnail\/(?<page_num>$
                default_type image/png;
                alias    /var/bigbluebutton/$meeting_id_2/$meeting_id_2/$pres_id/thumbnails/thumb-$page_num.png;
        }

        location ~^\/bigbluebutton\/presentation\/(?<meeting_id_1>[A-Za-z0-9\-]+)\/(?<meeting_id_2>[A-Za-z0-9\-]+)\/(?<pres_id>[A-Za-z0-9\-]+)\/textfiles\/(?<page_num>$
                default_type text/plain;
                alias    /var/bigbluebutton/$meeting_id_2/$meeting_id_2/$pres_id/textfiles/slide-$page_num.txt;
        }
        location ~^\/bigbluebutton\/presentation\/(?<meeting_id_1>[A-Za-z0-9\-]+)\/(?<meeting_id_2>[A-Za-z0-9\-]+)\/(?<pres_id>[A-Za-z0-9\-]+)\/svg\/(?<page_num>\d+)$ {
                default_type image/svg+xml;
                alias    /var/bigbluebutton/$meeting_id_2/$meeting_id_2/$pres_id/svgs/slide$page_num.svg;
        }

        location ~^\/bigbluebutton\/presentation\/(?<meeting_id_1>[A-Za-z0-9\-]+)\/(?<meeting_id_2>[A-Za-z0-9\-]+)\/(?<pres_id>[A-Za-z0-9\-]+)\/slide\/(?<page_num>\d+)$
                alias    /var/bigbluebutton/$meeting_id_2/$meeting_id_2/$pres_id/slide-$page_num.swf;
        }

        location ~^\/bigbluebutton\/presentation\/(?<meeting_id_1>[A-Za-z0-9\-]+)\/(?<meeting_id_2>[A-Za-z0-9\-]+)\/(?<pres_id>[A-Za-z0-9\-]+)\/thumbnail\/(?<page_num>$
                default_type image/png;
                alias    /var/bigbluebutton/$meeting_id_2/$meeting_id_2/$pres_id/thumbnails/thumb-$page_num.png;
        }

        location ~^\/bigbluebutton\/presentation\/(?<meeting_id_1>[A-Za-z0-9\-]+)\/(?<meeting_id_2>[A-Za-z0-9\-]+)\/(?<pres_id>[A-Za-z0-9\-]+)\/textfiles\/(?<page_num>$
                default_type text/plain;
                alias    /var/bigbluebutton/$meeting_id_2/$meeting_id_2/$pres_id/textfiles/slide-$page_num.txt;
        }

what do you mean by forgotten location entry for .../presentation/

output of sudo nano /etc/nginx/sites-available/bigbluebutton

# Handle RTMPT (RTMP Tunneling).  Forwards requests
         # to Red5 on port 5080
      location ~ (/open/|/close/|/idle/|/send/|/fcs/) {
          proxy_pass         http://127.0.0.1:5080;
          proxy_redirect     off;
          proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;

          client_max_body_size       10m;
          client_body_buffer_size    128k;

          proxy_connect_timeout      90;
          proxy_send_timeout         90;
          proxy_read_timeout         90;

          proxy_buffering            off;
          keepalive_requests         1000000000;
      }

         # Handle desktop sharing tunneling.  Forwards
         # requests to Red5 on port 5080.
       location /deskshare {
proxy_pass         http://127.0.0.1:5080;
           proxy_redirect     default;
           proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
           client_max_body_size       10m;
           client_body_buffer_size    128k;
           proxy_connect_timeout      90;
           proxy_send_timeout         90;
           proxy_read_timeout         90;
           proxy_buffer_size          4k;
           proxy_buffers              4 32k;
           proxy_busy_buffers_size    64k;
           proxy_temp_file_write_size 64k;
           include    fastcgi_params;
       }

        # BigBlueButton landing page.
        location / {
          root   /var/www/bigbluebutton-default;
          index  index.html index.htm;
          expires 1m;
 }

        # Include specific rules for record and playback
        include /etc/bigbluebutton/nginx/*.nginx;

        #error_page  404  /404.html;

        # Redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
                root   /var/www/nginx-default;
        }
}

Please help me asap. i will be much obliged.

**Comment by raheelrobson** [comment] 2020-04-03 17:12
> @capilkey Thanks for the advice and for pointing me to the right file(s). I can confirm that
> 
> * the presentation display problem is solved by putting the right paths into **/etc/bigbluebutton/nginx/presentation-slides.nginx**
> * the upload / upload-test problem was caused by a forgotten location entry for .../presentation/... in **/etc/nginx/sites-available/bigbluebutton** that bybassed the proxy_pass to the tomcat webservice (arrgh!) and triggered nginx's 404
> 
> With both issues fixed, presentations display and upload are both working fine.

what are the right paths?  please help me as well

**Comment by capilkey** [comment] 2020-04-03 18:10
@raheelrobson Unless you have tried to change where the presentations are stored this issue doesn't apply to you. The reason why your presentation won't load will be an error in the bbb-html5 journal logs.

sudo journalctl -u bbb-html5 | grep error

**Comment by asifaziz01** [comment] 2020-04-06 13:10
Hi,
I am facing similar issue. I recently installed BBB on Digital Ocean server. I am using BBB APIs to connect. My meetings as created and joined. USers can chat, share webcams, audio and see the default presentation, but they are unable to see screen sharing and whiteboard toolbars.
![image](https://user-images.githubusercontent.com/12405659/78561817-fc512e80-7835-11ea-9c4f-87ce6ea36a0d.png). Please help

**Comment by jfsiebel** [comment] 2020-04-06 13:15
Hi @asifaziz01, only presenters can view the screen share button and the whiteboard toolbar(unless multi-user whiteboard is on). In your image you joined as viewer, could you join as moderator?

**Comment by asifaziz01** [comment] 2020-04-06 14:19
Hi @jfsiebel, On reviewing my code it looks like I am using attendee password for joining as moderator. Fixing it. Thanks for pointing out. Will come back after fixing.

**Comment by sinnlosername** [comment] 2020-05-10 20:39
Hi.

Having a similar issue where presentations aren't loading.
![screenshot](https://user-images.githubusercontent.com/17328331/81510010-1ab3b980-930f-11ea-9fe9-bf4a7c879121.png)

 `journalctl -u bbb-html5 | grep error` output: 
```
May 10 22:09:49 servername systemd_start.sh[22332]: error: No file found. Error: write EPROTO 139691266991936:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:
May 10 22:09:49 servername systemd_start.sh[22332]: error: Error parsing image size. Error: write EPROTO 139691266991936:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:
```

nginx ssl settings:
```
     server_name OUR-DOMAIN;
     listen 443 ssl;
     listen [::]:443 ssl;

     ssl_certificate /root/.lego/certificates/OUR-DOMAIN.crt;
     ssl_certificate_key /root/.lego/certificates/OUR-DOMAIN.key;
     ssl_session_cache shared:SSL:10m;
     ssl_session_timeout 10m;
     ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
     ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
     ssl_prefer_server_ciphers on;
     ssl_dhparam /etc/nginx/ssl/dhp-2048.pem
```

/etc/bigbluebutton/nginx/presentation-slides.nginx: 
```
        location ~^\/bigbluebutton\/presentation\/(?<meeting_id_1>[A-Za-z0-9\-]+)\/(?<meeting_id_2>[A-Za-z0-9\-]+)\/(?<pres_id>[A-Za-z0-9\-]+)\/svg\/(?<page_num>\d+)$ {                default_type image/svg+xml;
                alias    /var/bigbluebutton/$meeting_id_2/$meeting_id_2/$pres_id/svgs/slide$page_num.svg;
        }

        location ~^\/bigbluebutton\/presentation\/(?<meeting_id_1>[A-Za-z0-9\-]+)\/(?<meeting_id_2>[A-Za-z0-9\-]+)\/(?<pres_id>[A-Za-z0-9\-]+)\/slide\/(?<page_num>\d+)$                alias    /var/bigbluebutton/$meeting_id_2/$meeting_id_2/$pres_id/slide-$page_num.swf;
        }

        location ~^\/bigbluebutton\/presentation\/(?<meeting_id_1>[A-Za-z0-9\-]+)\/(?<meeting_id_2>[A-Za-z0-9\-]+)\/(?<pres_id>[A-Za-z0-9\-]+)\/thumbnail\/(?<page_num>$                default_type image/png;
                alias    /var/bigbluebutton/$meeting_id_2/$meeting_id_2/$pres_id/thumbnails/thumb-$page_num.png;
        }

        location ~^\/bigbluebutton\/presentation\/(?<meeting_id_1>[A-Za-z0-9\-]+)\/(?<meeting_id_2>[A-Za-z0-9\-]+)\/(?<pres_id>[A-Za-z0-9\-]+)\/textfiles\/(?<page_num>$                default_type text/plain;
                alias    /var/bigbluebutton/$meeting_id_2/$meeting_id_2/$pres_id/textfiles/slide-$page_num.txt;
        }
```

`presentationDir` is set to `/var/bigbluebutton` in bigbluebutton.properties. This is the default setting for me.

Any idea how to fix this?

**Comment by sinnlosername** [comment] 2020-05-10 21:06
Update: Solved this by generating a new certificate using certbot instead of lego (another lets encrypt client). I have compared the two certificate files. Lego creates ecdsa (id-ecPublicKey) certificates while certbot uses rsa. Looks like some component of bigbluebutton isn't able to work with ecdsa certificates.

**Comment by sinnlosername** [comment] 2020-06-11 11:28
@raheelrobson Can you share the command output?

**Comment by raheelrobson** [comment] 2020-06-30 17:10
> @raheelrobson Can you share the command output?

Excuse me. I was away from office. 
Today I restarted my bbb using bbb-conf --restart 
I am pasting the output:

Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.



# Potential problems described below
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 10.11.12.55
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: bigbluebutton.fccollege.edu.pk

# Not running:  Nginx
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://bigbluebutton.fccollege.edu.pk/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Warning: The setting of 58.27.197.148 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (10.11.12.55).
# (This is OK if you've manually changed the values)

# Warning: The API demos are installed and accessible from:
#
#    https://bigbluebutton.fccollege.edu.pk
#
# and
#
#    https://bigbluebutton.fccollege.edu.pk/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Error: Unable to reach default URL for presentation:
#
#    https://bigbluebutton.fccollege.edu.pk/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

**Comment by marvinwankersteen** [comment] 2020-07-06 14:25
We had the same problem. We solved it by removing the mount option `noexec` for `/tmp`.

**Comment by tomoxwell** [comment] 2020-08-25 21:06
How do I solve  error: No file found. Error: certificate has expired  when i run sudo journalctl -u bbb-html5 | grep error?
On the browser the certificate is not expired

**Comment by mreza73** [comment] 2020-08-26 05:19
i have this problem too
and not fixed by regenerating certificate
<img width="1440" alt="Screen Shot 1399-06-05 at 9 44 16 AM" src="https://user-images.githubusercontent.com/8023573/91258351-620c6b80-e781-11ea-8b5f-b3c903664a7f.png">

**Comment by matiasilva** [comment] 2020-08-26 10:51
Make sure the presentation is owned by the `bigbluebutton` user as well.

**Comment by tomoxwell** [comment] 2020-08-26 11:09
you mean /var/bigbluebutton/presentaion?

**Comment by matiasilva** [comment] 2020-08-26 11:51
Yes, the default presentation. I had issues where if I copied my own default presentation, it would be owned by another user and the system would fail to load it as it was rightfully not owned by the `bigbluebutton` user.

**Comment by Killtip74** [comment] 2021-03-07 14:16
Hello, I am writing to you from Russia via google translator. Sorry in advance if somewhere is not quite readable. My problem is that the presentation is not displayed when checking through wget, I get that the root certificate has not been verified. how to fix this problem?

**Comment by prlanzarin** [comment] 2021-04-04 22:14
@Killtip74 
> how to fix this problem?

Mailing lists.

**Closed by prlanzarin** 2021-04-04 22:14 UTC

**Comment by abhijit13** [comment] 2021-10-05 10:50
![image](https://user-images.githubusercontent.com/848989/136009290-409404cc-5b5c-4c28-a87a-ecc8757d0712.png)
Facing same problem
Can anyone help?

bbb-conf --check does not show any potential problems.

The site has suddenly stopped showing the white-board. No configuration changes were done in recent past, except skipping echo test.

**Comment by abhijit13** [comment] 2021-10-05 11:01
https://github.com/bigbluebutton/bigbluebutton/issues/6139#issuecomment-932712639  has solved my problem.
