### ISSUE TITLE
BBB 2.5.2 - Redis error with Redis-server versions 5.0+ bbb-rap-starter.service

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/bigbluebutton#15311] opened 2022-07-03 07:40 UTC
Jul 03 07:28:33 vclashost.it bbb-rap[328372]: Enqueueing job to keep events from archive {:meeting_id=>"889ce24b691d564ce7989ee497b34743b8d7fae9-1656597768581", :break_timestamp=>nil}
Jul 03 07:28:33 vclass-host.it rap-starter.rb[328372]: Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.
Jul 03 07:28:33 vclashost.it rap-starter.rb[328372]: redis.pipelined do
Jul 03 07:28:33 vclashost.it rap-starter.rb[328372]:   redis.get("key")
Jul 03 07:28:33 vclashost.it rap-starter.rb[328372]: end
Jul 03 07:28:33 vclashost.it rap-starter.rb[328372]: should be replaced by
Jul 03 07:28:33 vclashost.it rap-starter.rb[328372]: redis.pipelined do |pipeline|
Jul 03 07:28:33 vclashost.it rap-starter.rb[328372]:   pipeline.get("key")
Jul 03 07:28:33 vclashost.it rap-starter.rb[328372]: end
Jul 03 07:28:33 vclashost.it rap-starter.rb[328372]: (called from /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-namespace-1.8.2/lib/redis/namespace.rb:530:in `namespaced_block'}

minimum version of redis-server from any repository is 5.0.7

**Comment by GuiLeme** [comment] 2022-07-13 12:00
Hey @amg-web, could you give us steps to reproduce this bug? It may be a duplicate of this issue:  https://github.com/bigbluebutton/bigbluebutton/issues/15179, please, take a look and tell us if that makes sense?

**Comment by amg-web** [comment] 2022-07-13 13:12
@GuiLeme 
easy, 2 coomands one by one:
systemctl start bbb-rap-starter.service
systemctl status bbb-rap-starter.service

yes. looks duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/15179

**Closed** 2023-01-31 15:52 UTC
Labels: module: recording
