### ISSUE TITLE
Remove the initial selected state when the option menu is opened on mobile

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#7240] opened 2019-04-11 20:42 UTC
In the screenshot below, you will see that the default open state for the options menu on mobile has the first item selected. I believe it's best if we have nothing chosen by default, that way it's consistent with the other menu's within the interface (on mobile). 

![IMG_9312](https://user-images.githubusercontent.com/1273169/55991685-d3c14380-5c78-11e9-9871-d7e57ab3ed97.PNG)

**Comment by prlanzarin** [comment] 2021-04-04 21:10
Closing due to not being able to reproduce anymore (2.3-beta.2, but please re-open if it's still an issue).

**Closed by prlanzarin** 2021-04-04 21:10 UTC
Labels: module: client
