### ISSUE TITLE
Not an issue how to make the presenter cam bigger instead of presentation

### ISSUE THREAD

**Issue by Coinizy1** [bigbluebutton/bigbluebutton#7048] opened 2019-03-16 07:09 UTC
I want to disable presentation and have only webcams in the place of presentation how to do this permanently?
![image](https://user-images.githubusercontent.com/31903098/54474121-9e087680-4802-11e9-9a14-3e0eb50d61ec.png)

**Comment by Coinizy1** [comment] 2019-03-16 10:25
how can i disbale presentation so it shows only the webcams.
thanks

**Comment by Coinizy1** [comment] 2019-03-16 10:45
I want to disable presentation and have only webcams in the place of presentation how to do this permanently?
![image](https://user-images.githubusercontent.com/31903098/54474110-7fa27b00-4802-11e9-8cc0-24bbb0b4e7ec.png)
thanks

**Comment by Coinizy1** [comment] 2019-03-16 11:09
@ffdixon @antobinary 
please help fast.

**Comment by ffdixon** [comment] 2019-03-16 14:23
@Coinizy1 your post of twice in a few hours suggests you believe there is an implied service level agreement in these issue which all questions are answered within X hours.

There is not.

When you post, you need to be patient and wait for another developer to volunteer their time to help out.  If you are unable to wait until someone volunteers their time, we recommend you reach out to companies that provide commercial support, see https://bigbluebutton.org/support.

Closed as a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/6956.

**Closed by ffdixon** 2019-03-16 14:23 UTC

**Comment by Coinizy1** [comment] 2019-03-16 21:39
Hi i am sorry actually i delete my recent comments here as i knew i was
teying to grt something from different messages but soon i realized and
deleted my other comments here instead of one.
Sorry
So it is not implemented right now to make the cams default om presentstion
screen right?
Thanks

**Comment by antobinary** [comment] 2019-03-18 18:23
Responded in #7065
