### ISSUE TITLE
Raising Hand signals Presentator/ Moderator to get attention

### ISSUE THREAD

**Issue by svergata** [bigbluebutton/bigbluebutton#9396] opened 2020-05-03 08:07 UTC
**Is your feature request related to a problem? Please describe.**
If a Viewer raise hand to have a question, the moderator / presentator should always have an eye on the userlist and in detail on the Icons in this list. 
This requires the attention of the presentator.

**Describe the solution you'd like**
A Viewer changes his Status Icon to Raishand, this triggers a signal to the Presentator to request attention. 
A configurable settingsdialog to enable/disable Sound / Visual feedback as it exists for chat notification.

**Describe alternatives you've considered**
As alternative you can use the Notification by Chat and request all users to use this only for questions. 
**Additional context**

![image](https://user-images.githubusercontent.com/58933250/80909001-d9c31000-8d24-11ea-81dc-9b301edbc6a4.png)

**Comment by debuglevel** [comment] 2020-05-03 11:05
This might be a duplicate of #9072. But I absolutely second this issue. I had a meeting yesterday and I did not notice the raised hand of another user.

**Comment by mjencabh** [comment] 2020-05-04 21:56
Yeah Fred wrote they are working on it for the 2.3 version. Lets hope they get it wrapped up :)

**Comment by ostasevych** [comment] 2020-05-07 21:06
I also annoyed with any changes of the status and popping out status messages. Is it possible to make them more intuitive, with transparent frame, good explanation. Now they are more confusing.

With the raise hand I suggest to add the special button like in Jitsi on the screen in order a user may click over it. And all the participants may see that specifically this user would like to talk. Look how it is done by Zoom.

**Comment by melolontha-melolontha** [comment] 2020-12-04 09:39
[#10958](https://github.com/bigbluebutton/bigbluebutton/issues/10958) proposes to let people requesting to speak assign a keyword to their request and provide a list of all such requests sorted by keyword and under each keyword by time and other procedures to deal with such an automated list of speak requests.

**Comment by schrd** [comment] 2021-04-06 15:36
@svergata I think the raise hand feature has improved a lot with 2.3 beta 1. IMHO this issue is solved and can be closed.

**Comment by PhMemmel** [comment] 2021-04-06 16:34
Attendee's UX of hand raised button even better than in 2.3-beta-1 if #11773 is going to be merged. Can be closed IMHO.

**Closed** 2021-04-06 17:46 UTC
Labels: status: verify, type: enhancement
