### ISSUE TITLE
Could we check active BBB tab browser?

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#10062] opened 2020-07-14 14:15 UTC
Hi, I want to check some participants' status.
I want to check which participants' browser is active and not changed during each session.
For example, I'm student and you are host/ teacher.

I'm login into the class but minimize the browser or change the tab of the browser and go to WWW and done another task and not listen directly to the class. Therefore, if there is an option for you (teacher) which could control each student with some flag or some color or any other emoji for each online user and get the result of (http://jsfiddle.net/meehanman/40edh944/), It could be very well...

I want to track students and help teachers to manage better the class

Do you have any idea? Could help me?

**Comment by basisbit** [comment] 2020-07-14 15:20
duplicate of #9960

**Comment by basisbit** [comment] 2020-07-14 15:21
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users). This issue tracker here is only for BBB development related issues. Sorry.

**Closed by basisbit** 2020-07-14 15:20 UTC
Labels: HTML5 Client
