### ISSUE TITLE
iOS webcam fullscreen not working

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7217] opened 2019-04-10 09:36 UTC
We only see the tooltip if we try to put the webcam on fulscreen. We could whether to hide it on iOS or enable the feature.

![image](https://user-images.githubusercontent.com/4991088/55868455-6fb95500-5b7c-11e9-99d9-42611f818564.png)

**Comment by capilkey** [comment] 2019-04-29 16:51
Duplicate of #7185

**Closed by capilkey** 2019-04-29 16:51 UTC
