### ISSUE TITLE
[2.2.31 and 2.3-alpha6] Client crashes on "double screensharing" in Chrome

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#11387] opened 2021-02-12 14:47 UTC
**Describe the bug**
If you enable screensharing while you already are screensharing and then hit "Cancel" in the screenshare window, the client crashes: only blue screen

**To Reproduce**
1. Open session with Chrome
2. Share a window or screen
3. Before screensharing is fully loaded click again on screenshare icon
4. In the background the already shared screen now appears (which of course is intended)
5. Now hitting "Cancel" on the screenshare selection window of Chrome (because the presenter now realizes that screensharing did work as expected the first time) completely crashes the client

**Expected behavior**
Just close the screenshare tool window of Chrome, return to session

**Actual behavior**
HTML5-Client "blue screen", makes reload neccessary to rejoin the session

**Screenshots**
not very expressive, but template wants a screenshot... :-)
![grafik](https://user-images.githubusercontent.com/65113153/107781576-52410d80-6d48-11eb-8db5-79b3b5a4a4d2.png)

**BBB version (optional):**
Tested on 2.3 (test23.bigbluebutton.org) and 2.2.31

**Desktop (please complete the following information):**
 Windows 10, Chrome 88.0.4324.150 64bit

**Additional context**
Part of this problem is that the presenter still can hit the screensharing icon despite already having triggered a screensharing action.

Log of test23.bigbluebutton.org session of Chrome console:
```
abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:69 TypeError: Cannot read property 'pingInterval' of null
    at KurentoManager.exitScreenShare (kurento-extension.js?v=1353:112)
    at window.kurentoExitScreenShare (kurento-extension.js?v=1353:902)
    at x.kurentoExitScreenShare (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:353)
    at y (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:353)
    at f.componentWillUnmount (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:353)
    at xs (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:69)
    at js (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:69)
    at Is (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:69)
    at Vl (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:69)
    at n.unstable_runWithPriority (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:87)
ws @ abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:69
abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:1 Exception from Tracker recompute function:
abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:1 TypeError: Cannot read property 'pingInterval' of null
    at KurentoManager.exitScreenShare (kurento-extension.js?v=1353:112)
    at window.kurentoExitScreenShare (kurento-extension.js?v=1353:902)
    at x.kurentoExitScreenShare (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:353)
    at y (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:353)
    at f.componentWillUnmount (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:353)
    at xs (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:69)
    at js (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:69)
    at Is (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:69)
    at Vl (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:69)
    at n.unstable_runWithPriority (abb9d076914c5880e4b8e8a8bb5809633f69a61f.js?meteor_js_resource=true:87)

```

**Comment by PhMemmel** [comment] 2021-02-12 14:54
Maybe this is already solved by #11025, but wanted to report that specific behaviour, at least to add this as a test scenario for #11025.

**Comment by prlanzarin** [comment] 2021-02-12 15:09
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/10486 (which 11025 tentatively tackles).

**Closed by prlanzarin** 2021-02-12 15:09 UTC
Labels: HTML5 Client

**Comment by PhMemmel** [comment] 2021-02-12 15:20
Sorry, searching for "Chrome" didn't show me any results. Thx for closing.
