### ISSUE TITLE
Etherpad has external font dependency that is blocked by some firewalls

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8653] opened 2020-02-20 11:57 UTC
**Describe the bug**
When a user loads the BigBlueButton behind a restrictive firewall (such as in China) and tries to use Shared Notes, Etherpad makes a request to load fonts form Google that does not resolve and causes Etherpad to fail after a few minutes.

**To Reproduce**
1.  Setup latest version of BigBlueButton on a server on an Intranet that is connected to the internet
2.  Turn off connection to the Internet
3.  Attempt to load the BigBlueButton client and start Shared Notes 

**Expected behavior**
Etherpad should load.

**Actual behavior**
Etherpad shows an error after a few minutes.

**Screenshots**
Here's a screen shot

Network console

![image](https://user-images.githubusercontent.com/290351/74931524-c2bf8380-53ad-11ea-93e8-e4f07f900965.png)

Error that finally appears where Shared Notes should have loaded.

![image](https://user-images.githubusercontent.com/290351/74931700-2e095580-53ae-11ea-925e-8fc4a3e2a7c2.png)

**Desktop (please complete the following information):**
 - Occurred on Mac OS X 13 running FireFox 62

**Additional context**
The user was in China attempting to load BigBlueButton from a server setup in China

**Comment by pedrobmarin** [comment] 2020-02-20 14:03
It's probably because of Google restrictions in China. Etherpad is configured to use the same font as the BigBlueButton client.
I was trying to avoid include it as static files inside Etherpad's repository but this scenario doesn't give us much choice.

**Comment by ffdixon** [comment] 2020-02-20 15:28
Yeah, I think it would be best to include the fonts. 

For the moment, is it possible to edit the include directives and place the fonts on the server without having to deploy an updated package?

**Comment by pedrobmarin** [comment] 2020-02-20 15:52
You could just add the files and map them in a similar way the client does and restart the service. I believe all the modifications we did are in `/usr/share/etherpad-lite/src/static`.

**Comment by kitatek** [comment] 2020-03-05 15:44
Manually downloading fonts is a common workaround when blocked by such situations. A small procedure how to do this would be helpful until a fix is available.

**Comment by henriquebol** [comment] 2020-04-08 16:03
(2.2.3). When loading for the first time, on some servers, two differents error appears and only works after f5. Etherpad need any more open ports on the firewall besides those described in the doc?

![Captura de tela de 2020-04-08 12-36-53](https://user-images.githubusercontent.com/3309893/78804547-a6e06300-7996-11ea-9490-0da96411b68d.png)
![Captura de tela de 2020-04-08 12-34-44](https://user-images.githubusercontent.com/3309893/78804551-a8119000-7996-11ea-9e06-3da2fda4b475.png)
![Captura de tela de 2020-04-08 12-32-05](https://user-images.githubusercontent.com/3309893/78804553-a8aa2680-7996-11ea-9f69-0f8640d4d554.png)

In addition to this error, a different one is happening here:
![Captura de tela de 2020-04-01 08-52-46](https://user-images.githubusercontent.com/3309893/78804633-c5465e80-7996-11ea-870b-3559e46594e4.png)

Reloading the page is working for both errors.

Brazil. Linux. Chrome 80 64 bits

**Comment by pedrobmarin** [comment] 2020-04-08 16:15
@henriquebol there are 2 different things going on there. About `custom` files, it's not an issue and shouldn't affect your service. It's something Etherpad tries because we are not using it's most recent styles from version 1.8.
The other one is something we are not completely sure why happens. What you described is exact the same we notice: some servers, sometimes, first load. I believe it's related with our reverse proxy configuration that exposes Etherpad but still a little obscure.

**Comment by Franz-Heinz** [comment] 2020-04-13 10:12
Hello,
I'm seeing that opening the pad-function brings the browser to load from "fonts.gstatic.com" (you can reproduce it with "NoScript" in your browser). This is a big problem for me regarding the GDPR-compliance. Is there a short fix for this that outlives updates? If yes, I would be greatfull for a step-by-step guide on how to fix this.
Thanks a lot in advance.

**Comment by pedrobmarin** [comment] 2020-04-13 12:46
If you are running a single server or something that doesn't go too much beyond this scenario you can apply some simple changes on Etherpad's scripts to avoid getting it to load gstatic fonts. At `/usr/share/etherpad-lite/src/static/css`:

```
diff --git a/src/static/css/iframe_editor.css b/src/static/css/iframe_editor.css

index dee54ad0..c632bc08 100644

--- a/src/static/css/iframe_editor.css

+++ b/src/static/css/iframe_editor.css

@@ -3,7 +3,7 @@

 */

 

 @import url('./lists_and_indents.css');

-@import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro');

+/* @import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro'); */

 

 html { cursor: text; } /* in Safari, produces text cursor for whole doc (inc. below body) */

 span { cursor: auto; }

@@ -34,7 +34,8 @@ body.grayedout { background-color: #eee !important }

 

 #innerdocbody {

   font-size: 14px; /* overridden by body.style */

-  font-family: 'Source Sans Pro', sans-serif; /* overridden by body.style */

+  font-family: Arial, sans-serif; /* overridden by body.style */

+/*  font-family: 'Source Sans Pro', sans-serif; */  /* overridden by body.style */

   line-height: 18px; /* overridden by body.style */

   background-color: white;

   color: #4e5a66;

diff --git a/src/static/css/pad.css b/src/static/css/pad.css

index 0792f3a6..c50819f7 100644

--- a/src/static/css/pad.css

+++ b/src/static/css/pad.css

@@ -1,5 +1,5 @@

 

-@import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro');

+/* @import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro'); */

 

 *,

 html,

@@ -20,7 +20,8 @@ html {

 body,

 textarea {

   font-size: 14px;

-  font-family: 'Source Sans Pro', sans-serif;

+  font-family: Helvetica, Arial, sans-serif;

+/*  font-family: 'Source Sans Pro', sans-serif; */

 }

 iframe {

   position: absolute
```
At the end of the process, restart Etherpad service `sudo systemctl restart etherpad`.

This way you can fix it right away and won't depend on any package update.

**Comment by pedrobmarin** [comment] 2020-09-23 14:05
https://github.com/bigbluebutton/etherpad-lite/commit/b842cb8270a7136dc16116cc3524361f109eb177

**Closed by pedrobmarin** 2020-09-23 14:05 UTC

**Comment by hahaxd35** [comment] 2022-10-14 13:32
fonts from gstatic are loaded again in version 2.6, is this wanted?
