### ISSUE TITLE
 Easier way to access "raise hand"-function

### ISSUE THREAD

**Issue by fm-sys** [bigbluebutton/bigbluebutton#9394] opened 2020-05-02 22:34 UTC
I have the following problem: To use the "raise hand"-function, you always have to go to the corresponding submenu with 3 clicks. This is quite cumbersome and time consuming.
I also believe that this feature is used very often and is important for productive metings.

What do you think about integrating this function immediately available as a button next to hang up and microphone mute? 

Also a directly accessible button at another position would be conceivable. I would personally prefer the position mentioned above, however...

**Comment by lars-becker** [comment] 2020-05-02 23:11
I think this would clutter the user interface. We only use this symbol in small groups. With bigger groups we ask persons to use the chat to indicate that they want to speak. This way we also see who wanted to speak first etc.

**Comment by ffdixon** [comment] 2020-05-03 02:06
We've been working on improving the emoji icons in the next release (BigBlueButton 2.3) of BigBlueButton.

We'll be sharing some of the designs soon.

**Comment by mosyBG** [comment] 2020-05-03 05:26
> We've been working on improving the emoji icons in the next release (BigBlueButton 2.3) of BigBlueButton.
> 
> We'll be sharing some of the designs soon.

hello 
can i suggest some recommend idea for main page bigbluebutton UX/UI ?

**Comment by Nick-Netizen** [comment] 2020-05-06 19:47
This might be a duplicate of [#9072](https://github.com/bigbluebutton/bigbluebutton/issues/9072).

**Comment by bwurst** [comment] 2021-03-11 10:24
Just a side note:
There is a firefox plugin named bigbluebutton-plus created by a german pupil. It adds the "raise hand" feature to the UI.

**Comment by gigapeco** [comment] 2021-03-18 08:49
C'est une fonction très intéressante pour une Visio-conférence. J'ai testé ce plugin. 
This is a very interesting function for a videoconference. I tested this plugin.

**Comment by ffdixon** [comment] 2021-03-18 11:17
We can see the value of having the raise hand/emoji buttons front and centre. We're looking at adding a raise hand/emoji button to BigBlueButton as one of the enhancements after we release 2.3 (currently in development).

**Comment by bwurst** [comment] 2021-03-20 14:49
This plugin adds a few lines of javascript into the user interface. I don't know if there is anything firefox specific here (the volume control is way less important here, every device has such a feature) but perhaps this code could be integrated as is...

**Comment by ffdixon** [comment] 2021-03-20 14:58
We're looking at making a raise hand button on the toolbar below in BigBlueButton 2.3 to make it easier for students to raise their hand.  This will build upon the work to make it easier for the instructor to see the raised hand

 https://docs.bigbluebutton.org/dev/dev23.html#notifications-options-in-settings

**Comment by antobinary** [comment] 2021-04-07 18:35
Resolved via https://github.com/bigbluebutton/bigbluebutton/pull/11703

**Closed by antobinary** 2021-04-07 18:35 UTC
Labels: type: enhancement
