### ISSUE TITLE
[2.3-dev] Moderator approval does not work

### ISSUE THREAD

**Issue by miztaka** [bigbluebutton/bigbluebutton#10621] opened 2020-10-09 03:57 UTC
**Describe the bug**
I'm using greenlight v2.7 and have a room with moderator approval required.
When other participants try to join the room, "waiting approval screen" shows up,
but nothing appears in moderators HTML5 client.

**To Reproduce**
1. Go to greenlight and create a room with "moderator approval required"
2. Join the meeting and wait for the guest
3. with another user or guest, join the meeting
4. No waiting approval list is shown in moderator's screen

**Expected behavior**
1. The guest's name is listed in moderator's screen so you can approve/deny the guest
2. guest can be joined when moderator approved it

**Actual behavior**
 No waiting approval list is shown in moderator's screen

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 2.3.0-dev, (greenlight 2.7.4)
```
ii  bbb-apps-akka                               2.3.0-5                                         all          BigBlueButton Apps (Akka)
ii  bbb-config                                  1:2.3.0-7                                       amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                                1:2.3.0-11                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                         2:2.3.0-2                                       amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                       1:1.6.7-1                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                              2.3.0-3                                         all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                                   1:2.3.0-1250                                    amd64        The HTML5 components for BigBlueButton
ii  bbb-libreoffice-docker                      1:2.3.0-6                                       amd64        BigBlueButton setup for LibreOffice running in docker
ii  bbb-mkclean                                 1:0.8.7-1                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation                   1:2.3.0-3                                       amd64        BigBluebutton playback of presentation
ii  bbb-record-core                             1:2.3.0-6                                       amd64        BigBlueButton record and playback
rc  bbb-transcode-akka                          2.3.0-1                                         all          BigBlueButton Transcoder
ii  bbb-web                                     1:2.3.0-9                                       amd64        BigBlueButton API
ii  bbb-webrtc-sfu                              1:2.3.0-4                                       amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                               1:2.3.0-4                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                      7:4.2.2-1bbb1~ubuntu18.04                       amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                          7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                         7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                          7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                         7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                        7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                           7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                                 0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                         7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                        7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                           7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library for image scaling and various conversions - runtime files
```

**Comment by arjanadriaanse** [comment] 2020-10-09 18:12
This is fixed by #9979.

**Comment by neophrema** [comment] 2020-10-11 12:54
Hello, 
did I understand correctly that the approval-to-join functionality isnt at work right now cause code gets shuffeled into the bbb-html5 ?
Right now in our production server the Moderator is able to approve, but the user gets routed to nginex page with 404 error; He doesn't get routed to the waiting-screen;
Is there a posibility to update to git version, I couldn't find anything.

**Comment by arjanadriaanse** [comment] 2020-10-11 13:46
That seems to be the case indeed. I managed to make it work on a production server by applying the changes from #9979 to the v2.3-alpha-2 tag and building the HTML5 client using the instructions here: https://docs.bigbluebutton.org/2.2/dev.html

Note that you also need to apply the change of `defaultGuestWaitURL` in `bigbluebutton.properties`.

**Comment by neophrema** [comment] 2020-10-11 13:55
May I ask - you applied all the changes from #9979 ? Thank you for the pointing, I'll investigate.

**Comment by arjanadriaanse** [comment] 2020-10-11 13:59
Yes, see b002ba9937e6b560e273cdab0b85b1562ff110de.

**Comment by neophrema** [comment] 2020-10-12 11:05
Sadly I was not able to accomplish this task, I'll get an error and it seems like BBB cant connect to bbb-html5. I just get stuck at the waiting dots and the following was thrown out:

`error: {"logCode":"authenticatedhandlercomponent_setreason","logDescription":"Encountered error while trying to authenticate","connectionId":"rcKe2LenMgnqQwJ4q","extraInfo":{"reason":{"error":401,"description":"Authentication timeout."},"clientURL":"https:xxxxxxxxxxxxxxxxxxxxx.de/html5client/join?sessionToken=soikutc43hpibyfq","validUser":"valid"},"userInfo":{"sessionToken":"soikutc43hpibyfq","meetingId":"123ce8b94ad00afce04ab34ac88fc5ef53f2a98c-1602446333699","requesterUserId":"w_ztyrq6bej5yk","fullname":"Fred User","confname":"Startroom","externUserID":"gl-oslstbvnmaif","uniqueClientSession":null}}`

Since I wasn't able to get the Git version running.
Plan B: Is there any scheduling regarding a new version of 2.3-dev ?

**Comment by Beiri22** [comment] 2020-11-27 20:23
I'm also interested. The last alpha release is some time in the past; time for some update...

**Comment by Beiri22** [comment] 2020-12-26 13:58
Still not working for me, see https://github.com/bigbluebutton/bigbluebutton/issues/11053

**Comment by ratondeau** [comment] 2021-01-12 10:58
I can confirm this is still an issue an issue with BigBlueButton Server 2.3.0-alpha4 (1476)

The entry for guerstWaitingURL in bigbluebutton-properties:

# The url for where the guest will poll if approved to join or not.
defaultGuestWaitURL=${bigbluebutton.web.serverURL}/html5client/guestWait

I get an 404 as the request is rooted to https://bbb.example.com/html5client/guestWait?sessionToken=wb2ema4ao5ymb34w

Do you need futher information?

Best Regards
Matt

**Comment by stagestars** [comment] 2021-01-12 19:12
I have the same issue - lobby is not working in 2.3.3-alpha4

Does anyone have a workaround to get this fixed in the meantime?

**Comment by ffdixon** [comment] 2021-01-12 19:35
We'll have 2.3-alpha5 out soon with a fix to the moderator approval.

**Comment by stagestars** [comment] 2021-01-12 20:26
> We'll have 2.3-alpha5 out soon with a fix to the moderator approval.

Thank you, that's awesome. Any idea if it might be by Friday? We're hoping to roll out then instead of using Jitsi any longer (the raise hand notification meant we decided to start with 2.3 rather than 2.2)

**Comment by ffdixon** [comment] 2021-01-13 07:37
We can't make any promises on dates, and also 2.3-dev is under active development.  It's not ready for production yet.  If your looking for production deployment, we would recommend 2.2.x.

**Comment by basisbit** [comment] 2021-01-30 03:12
This should be fixed with today's release of 2.3-alpha5. Could someone test this and respond here with your results?

**Comment by Beiri22** [comment] 2021-01-31 20:23
I just tested it and it works for me. But, with 2.3a5 I got problems with the audio connection:

1.) When I enter with mic: The connection to echo test times out: Error 1006 ([21:22:29:0910] ERROR: clientLogger: Audio error - errorCode=1006, cause=Call timed out on start after 20s https://bbbb.beiri22.de/html5client/1/3db6e0bbbc534f411771528262979c2d67eb22de.js?meteor_js_resource=true:353:1107414
)
2.) When trying to enter "only to listen": nothing happens when clicking on that button. (nothing in console log, too)

Camera seems to work.

**Comment by stagestars** [comment] 2021-01-31 20:31
Exactly the same for me, I've given up and moved back to Jitsi I'm afraid for the stability

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by basisbit** [comment] 2021-01-31 20:51
@stagestars 2.3-alpha5 is an alpha release. If you complain about its stability, you only got yourself to blame. Do not use an alpha version for production.
2.2.x is the stable branch currently and it works very well for many millions of daily users.

**Comment by basisbit** [comment] 2021-01-31 20:52
@Beiri22 thank you for confirming that moderator approval in 2.3-alpha5 is fixed.

**Closed by basisbit** 2021-01-31 20:52 UTC

**Comment by stagestars** [comment] 2021-01-31 20:54
No... I'm more than happy and comfortable in blaming the project thanks 😃 I tried 2.2 and had the constant issues too. It's always a worry when someone won't allow criticism of a project, tends to indicate bigger issues... For me, Jitsi is reliable and I'm entitled to my opinion, ta

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
