### ISSUE TITLE
2.5-rc4 Recording fails

### ISSUE THREAD

**Issue by Davka** [bigbluebutton/bigbluebutton#15138] opened 2022-06-07 13:26 UTC
I freshly installed BBB 2.5-rc4 (via the Ansible role - but that shouldn't matter). After starting the server, it was noticed that the recording services had not started. Also, recordings that were made were not processed.

A bbb-record --rebuild then returned some error messages indicating missing dependencies.

After the following packages are installed, the recordings could be processed
```
apt-get install ruby2.7-dev libsystemd-dev

gem install redis builder fileutils yaml nokogiri loofah open4  absolute_time journald-logger resque

service bbb-rap-starter start
service bbb-rap-resque-worker start
```

**To Reproduce**
Install BBB 2.5-rc4 with enabled recordings (in our environment the recordings are stored on an NFS).  Start a meeting and activate recordings.

**Expected behavior**
Recordings will be published

**Actual behavior**
Recordings are not processed

For example, the following errors occurred

```
root@bbb3:/var/log/bigbluebutton/presentation# bbb-record --rebuild ID
Marking for rebuild ID
Traceback (most recent call last):
	7: from /usr/local/bigbluebutton/core/scripts/rap-enqueue.rb:21:in `<main>'
	6: from /usr/local/bigbluebutton/core/scripts/rap-enqueue.rb:21:in `require_relative'
	5: from /usr/local/bigbluebutton/core/lib/recordandplayback.rb:24:in `<top (required)>'
	4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	2: from /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:21:in `<top (required)>'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- redis (LoadError)
```

**Comment by lonesomewalker** [comment] 2022-06-07 16:12
There is an "official" Ansible role/playbook for installing BBB?

**Comment by Davka** [comment] 2022-06-08 08:05
> There is an "official" Ansible role/playbook for installing BBB?

Yes, https://github.com/ebbba-org/ansible-role-bigbluebutton

**Comment by antobinary** [comment] 2022-06-08 13:36
Hi @Davka ,
Thanks for reporting! I believe this is a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/15085
which is resolved via https://github.com/bigbluebutton/bigbluebutton/pull/15116

Expect to see it released in the next BBB 2.5.x release within a few days.

Please comment if you think this is different

**Comment by lonesomewalker** [comment] 2022-06-09 10:41
This looks not official to me.
ebbba is nothing official.

**Comment by Davka** [comment] 2022-06-12 11:06
@antobinary The services still don't start. I had to start it manually


```
NEXT LEFT LAST PASSED UNIT ACTIVATES

0 timers listed.
--
● bbb-rap-starter.service - BigBlueButton recording processing starter
     Loaded: loaded (/lib/systemd/system/bbb-rap-starter.service; disabled; vendor preset: enabled)
     Active: inactive (dead)

● bbb-rap-resque-worker.service - BigBlueButton resque worker for recordings
     Loaded: loaded (/lib/systemd/system/bbb-rap-resque-worker.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
--

```

**Comment by BrutalBirdie** [comment] 2022-06-13 09:24
> This looks not official to me. ebbba is nothing official.

Oh I just noticed in the doc of BigBlueButton about large-scale installations the [General Ansible role for BigBlueButton](https://github.com/n0emis/ansible-role-bigbluebutton) links to <https://github.com/n0emis/ansible-role-bigbluebutton> which redirects correctly to the eBBBa repository => <https://github.com/ebbba-org/ansible-role-bigbluebutton>.

I will have to create PR for the doc to be updated. Silly me never noticed this because of the redirect.

So yes we are officially documented but with a wrong URL redirecting correctly.

If your concern @lonesomewalker is about legitimacy you can visit us at <https://www.ebbba.org/>.
There is also a Matrix Channel with 49+ (mostly German) administrators of many universitys with over a Million Users each day using either the eBBBa Role for Ansible Setups or a slightly forked version for their needs.

**Comment by ffdixon** [comment] 2022-06-13 10:59
Hi everyone,

The organization at https://www.ebbba.org/ is officially supported by the BigBlueButton project.  It's an advocacy group in Europe for growing the BigBlueButton ecosystem, and the BigBlueButton community is stronger for them.

Thanks @BrutalBirdie for all your contributions, including the Ansible roles that you make available to everyone in the community.  While the core developers don't use those roles directly (not that I'm aware of!), we do appreciate the work you do to maintain them for the community.

Regards,... Fred
Product Manager, BigBlueButton

**Comment by kepstin** [comment] 2022-06-14 21:01
There is no need to install any additional packages or gems - the recording system package (bbb-record-core) includes a pre-built bundle of required gems. And the systemd units (and following #15116 the rap-enqueue tool too) are set up to load the bundler environment automatically.

I took a quick look through the ansible playbook, and it doesn't look like it's doing anything unusual to the system ruby installation, so I'm really not sure why it's not working. It's installing the packages from the `focal-250` BBB repository, so you should have the correct versions of the packages.

Can you please try running the following diagnostic commands?

```sh
# systemctl cat bbb-rap-resque-worker.service`
```
The systemctl output should contain `ExecStart=/usr/bin/bundle exec rake -f Rakefile resque:workers` and `WorkingDirectory=/usr/local/bigbluebutton/core/scripts` with no overrides.

The following commands show their expected output inline:

```sh
# /usr/bin/bundle --version
Bundler version 2.3.14
# which rake
/usr/bin/rake
# which ruby
/usr/bin/ruby
# cd /usr/local/bigbluebutton/core/scripts && bundle exec irb
irb(main):001:0> require '../lib/recordandplayback'
=> true
```

If you get an error or different output at any step, please share what you see.

**Comment by Davka** [comment] 2022-06-16 09:09
@kepstin Interesting, mine is different. But why? :D

```
/usr/bin/bundle --version
Bundler version 2.1.4
```

```
systemctl cat bbb-rap-resque-worker.service
# /lib/systemd/system/bbb-rap-resque-worker.service
[Unit]
Description=BigBlueButton resque worker for recordings
Wants=redis.service
After=redis.service

[Service]
Type=simple
ExecStart=/usr/bin/bundle exec rake -f Rakefile resque:workers
WorkingDirectory=/usr/local/bigbluebutton/core/scripts
Environment=QUEUE=rap:archive,rap:publish,rap:process,rap:sanity,rap:captions,rap:events
Environment=COUNT=1
# Environment=VVERBOSE=1
User=bigbluebutton
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
```


```
systemctl | grep rap
```
No services listed

**Comment by Davka** [comment] 2022-06-16 09:33
The problem seems to be that the services are not activated. 
The dependency on the Redis is also missing in the unit files (See Pull-Request https://github.com/bigbluebutton/bigbluebutton/pull/15100)

```
Jun 16 10:58:55 webm-4 bundle[96572]: Caused by:
Jun 16 10:58:55 webm-4 bundle[96572]: IO::EINPROGRESSWaitWritable: Operation now in progress - connect(2) would block
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/connection/ruby.rb:158:in `connect_addrinfo'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/connection/ruby.rb:196:in `block in connect'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/connection/ruby.rb:194:in `each'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/connection/ruby.rb:194:in `each_with_index'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/connection/ruby.rb:194:in `connect'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/connection/ruby.rb:308:in `connect'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:385:in `establish_connection'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:115:in `block in connect'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:344:in `with_reconnect'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:114:in `connect'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:417:in `ensure_connected'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:269:in `block in process'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:356:in `logging'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:268:in `process'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:161:in `call'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis.rb:263:in `block in send_command'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis.rb:262:in `synchronize'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis.rb:262:in `send_command'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/commands/strings.rb:191:in `get'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-namespace-1.8.2/lib/redis/namespace.rb:476:in `call_with_namespace'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-namespace-1.8.2/lib/redis/namespace.rb:352:in `block (2 levels) in <class:Namespace>'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/data_store.rb:231:in `get_worker_payload'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:752:in `job'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:670:in `unregister_worker'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:250:in `rescue in work'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:231:in `work'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/tasks.rb:20:in `block (2 levels) in <top (required)>'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Jun 16 10:58:55 webm-4 bundle[96572]: Caused by:
Jun 16 10:58:55 webm-4 bundle[96572]: Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:398:in `rescue in establish_connection'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:379:in `establish_connection'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:115:in `block in connect'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:344:in `with_reconnect'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:114:in `connect'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:417:in `ensure_connected'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:269:in `block in process'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:356:in `logging'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:268:in `process'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/client.rb:161:in `call'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis.rb:263:in `block in send_command'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis.rb:262:in `synchronize'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis.rb:262:in `send_command'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-4.6.0/lib/redis/commands/strings.rb:191:in `get'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-namespace-1.8.2/lib/redis/namespace.rb:476:in `call_with_namespace'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/redis-namespace-1.8.2/lib/redis/namespace.rb:352:in `block (2 levels) in <class:Namespace>'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/data_store.rb:231:in `get_worker_payload'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:752:in `job'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:670:in `unregister_worker'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/worker.rb:246:in `work'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/resque-2.0.0/lib/resque/tasks.rb:20:in `block (2 levels) in <top (required)>'
Jun 16 10:58:55 webm-4 bundle[96572]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Jun 16 10:58:55 webm-4 bundle[96572]: Tasks: TOP => resque:work
Jun 16 10:58:55 webm-4 bundle[96572]: (See full trace by running task with --trace)
Jun 16 10:58:55 webm-4 systemd[1]: bbb-rap-resque-worker.service: Failed with result 'exit-code'.
Jun 16 10:58:55 webm-4 systemd[1]: Stopped BigBlueButton resque worker for recordings.
```

**Comment by Davka** [comment] 2022-06-16 11:46
I adopted the changes from https://github.com/bigbluebutton/bigbluebutton/pull/15100 and then activated the recordings services via Ansible. Now everything works as expected @schrd

**Comment by danielgolf** [comment] 2022-06-23 07:37
> I wonder why we're not seeing any issues with servers built with bbb-install - perhaps the services are manually started due it using bbb-conf to restart all of BigBlueButton as part of configuring it.

I have exactly this problem. Calling bbb-install in another custom script to install BBB on a new Ubuntu 20.04 server. Afterwards the bbb-rap-*.service units are not enabled. So when the machine is rebooted after the install, no recordings will be processed. I've to enable both units manually.

**Comment by basisbit** [comment] 2022-06-23 08:23
> This is the thing why i wrote: NOT OFFICIAL. I know ebbba, and refused to be part of that (for good reasons, and A LOT of other professional companies also denied that). Just think about that...

@lonesomewalker: We,  the eBBBa, never interacted with you so far (from what we know) and we are still a very new and rather small group. So, I assume you are confusing us with someone else. If you want to talk with us about that, please feel free to contact us! One of our goals is to make it easier for BBB providers, developers and users in Europe to work together and to provide a platform for that. Thus it should be interesting for you, too. (We are not Cyber4Edu or infra.run or Teckids or Senfcall or so, we are a completely separate organization)

**Comment by ffdixon** [comment] 2022-06-23 11:16
@lonesomewalker I'm the Product Manager for BigBlueButton and one of the directors of BigBlueButton Inc., the not-for-profit organization that owns the trademark and source code under the open source license.

eBBBa, BigBlueButton Inc., the many commercial companies, educational institutions, developers, and teachers are all working together to make BigBlueButton the best virtual classroom for the world.  

I've worked closely with the eBBBa folks and they have been advocating and supporting BigBlueButton in Europe on behalf of the BigBlueButton community.  They are a great team.  BigBlueButton Inc.  fully supports their organization.  Not everyone has to join every organization, and no one organization (such as BigBlueButton Inc.) can do everything around the world.  We're a stronger community with eBBBa.

**Comment by wilkis3** [comment] 2022-07-20 17:09
I have the same issue. I also used the ebbba Ansible playbook - but that shouldn't matter.

This problem is fixed when `bbb-rap-starter.service` and `bbb-rap-resque-worker.service` are enabled in Systemd. Is `/build/packages-template/bbb-record-core/after-install.sh` the correct file to enable the service there or should the problem be solved differently?

**Closed** 2022-08-09 14:13 UTC
Labels: module: recording
