### ISSUE TITLE
Whiteboard activities cannot seen by viewers in version 2.2.28

### ISSUE THREAD

**Issue by dseral** [bigbluebutton/bigbluebutton#10784] opened 2020-11-06 13:13 UTC
Last week i updated all BBB servers from 2.2.27 to latest  2.2.28 edition. Previously multiple Kurento instances already enabled.
We use BBB with scalelite balancer and typically we haven't got more than 300 users on each server. Also sessions limited with 100 users by config. 
Many teacher started to claim that while they used whiteboard (pen, text or other functions) the actions not shown on viewers side. So what is the problem is the problem related to multiple Kurento?

**Comment by matiasilva** [comment] 2020-11-06 19:22
Probably a duplicate of #10739.

**Comment by serior** [comment] 2020-11-25 10:50
Same problem hier.

**Comment by basisbit** [comment] 2021-01-30 01:52
Closing this issue because
- can not reproduce
- not a problem of multiple kurento setup
- most likely the bbb server was just hitting its concurrent users limit, which probably is fixed by updating to 2.2.31 or 2.2.32, or by the administrator adding more servers to the scalelite setup.

**Closed by basisbit** 2021-01-30 01:52 UTC
