### ISSUE TITLE
2.3 beta-3 - webcam video don't start in break-out room 

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#11985] opened 2021-04-11 12:04 UTC
webcam video don't start in break-out room.!
**however if user connected to listen only before starting webcam, then the webcam broadcast will start normally.**
presentation reposition normally to make room for video but no video starting, and the video button is grayed. 
no error on browser console.

1) log in 1 moderators and 1 user
2) **join audio with microphone on user** !!
3) start break-out room.
4) join user to break-out room.
5) Wait for mic to connect  
 6) start video

**Expected behavior**
webcam broadcast will start normally

**Actual behavior**
the camera select window shows as it should and you can select a camera.
when you start video, select window closes and the camera area widens (like there was a web cam showing), but it remains black.

**BBB version (optional):**
2.3 beta-3 
tested on test23.bigbluebutton.org

**Desktop (please complete the following information):**
 - OS: Windows 10, 
Chrome

**Smartphone 
 - OS: android
 - Browser [chrome

**Comment by prlanzarin** [comment] 2021-04-11 12:22
Gotcha. We've seen reports in the user list, but what was really missing were steps 2 and 5. Able to reproduce now.

Seems like something was done to auto-join with mic on the breakout room if the user had it enabled on the parent room. I think that's tripping the weird code that doesn't mount the video-provider until _after_ the user joins audio or close the audio modal.

**Comment by prlanzarin** [comment] 2021-04-15 19:32
I've just noticed that a similar thing can be reproduced even in the **main** room, so it doesn't seem to be auto-join specific (or maybe a secondary issue).

The steps are straightforward:
  1. Join with two sessions (1, 2)
  2. Close the audio modal in both (without joining audio at all)
  3. Share camera in session 2. Session 1 will not load the camera because it's blocked on the modal barrier for some reason. Open-close the audio modal seems to lift the barrier.

**Comment by daminebenq** [comment] 2021-04-16 14:10
> I've just noticed that a similar thing can be reproduced even in the **main** room, so it doesn't seem to be auto-join specific (or maybe a secondary issue).
> 
> The steps are straightforward:
> 
> 1. Join with two sessions (1, 2)
> 2. Close the audio modal in both (without joining audio at all)
> 3. Share camera in session 2. Session 1 will not load the camera because it's blocked on the modal barrier for some reason. Open-close the audio modal again seems to lift the barrier.

Hi @prlanzarin, I couldn't reproduce this.
Hi @Jossef-767, looks like #12003 is a fix for this issue. Thanks for reporting it.

**Comment by prlanzarin** [comment] 2021-04-16 16:12
@daminebenq 

I just tried it again, could reproduce a few times in a row.
Firefox 87, Linux, **dev** server (not test). So it's reproducible somehow, even if those steps aren't 100% reliable.

**Comment by prlanzarin** [comment] 2021-04-16 16:18
There's something even weirder going on: if you join multiple times in a room in the **dev** server, only the first session seems to get the audio modal up on join. Subsequent session don't have the modal automatically mounted for you, so it will never be closed without an user action, so cameras can't be shared.

Not sure why the modal is not mounting for subsequent users. Surely not a Session/Cookie mishap because I've tested it cross-browser and incognito.

**Comment by ramonlsouza** [comment] 2021-04-16 19:03
> There's something even weirder going on: if you join multiple times in a room in the **dev** server, only the first session seems to get the audio modal up on join. Subsequent sessions don't have the modal automatically mounted for you, so it will never be closed without an user action, so cameras can't be shared.
> 
> Not sure why the modal is not mounting for subsequent users. Surely not a Session/Cookie mishap because I've tested it cross-browser and incognito.

Looks like it was caused by a [recent change](https://github.com/bigbluebutton/bigbluebutton/commit/4db28a2824114a951b12926899a9d5640cea1a23#diff-fb6608947529786a0ffa74b1a2db0e5335192623c2dad42bc2631e27192895a2L184-R185)

**Closed** 2021-04-16 20:08 UTC
Labels: component: webcam, module: client, status: accepted, type: bug
