### ISSUE TITLE
Looped sharing of the screen with BBB

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/bigbluebutton#9308] opened 2020-04-28 20:42 UTC
**Describe the bug**
Quite often it is necessary to train your users how to use BBB demonstrating its functionalities using shared screen. When I share the main screen of BBB I'm getting infinity loop effect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to main page of BBB
2. Share your screen
3. Observe the looping effect

![image](https://user-images.githubusercontent.com/5199030/80535940-4303f580-89aa-11ea-8d9f-b2b207443a40.png)

**Expected behaviour**
When I share the main screen the looping effect is eliminated by some static page used for the background.

**Comment by prlanzarin** [comment] 2020-04-28 21:55
Duplicate of #7183.

**Closed by prlanzarin** 2020-04-28 21:55 UTC
