### ISSUE TITLE
make the hand rising more visible

### ISSUE THREAD

**Issue by dfasani** [bigbluebutton/bigbluebutton#11188] opened 2021-01-20 14:51 UTC
**Is your feature request related to a problem? Please describe.**
Users are not that much visible when they raise their hands, using the update status features.

**Describe the solution you'd like**
Make them more visible. 

**Describe alternatives you've considered**
You could have a look at the google meet equivalent behaviour. People with raised hands are grouped at the beginning of the user list in a kind of sub-set that make them more visible.

**Additional context**
Very useful for large scale lessons (50+ students).

Regards,
David

**Comment by basisbit** [comment] 2021-01-20 16:48
duplicate of various issues. Please use the search feature before creating new issues.

**Closed by basisbit** 2021-01-20 16:48 UTC
Labels: Enhancement
