### ISSUE TITLE
Whiteboard text doesnt show up until confirmation in 2.3

### ISSUE THREAD

**Issue by RYNEQ** [bigbluebutton/bigbluebutton#12443] opened 2021-05-26 08:31 UTC
In bbb 2.2 when someone type on presentations others could see the text even before confirmation of writing box (clicking outside of typing area) but in 2.3 we need to click out of typing box to others be able to see the text  

Is there any setting for this?  
How can we have old type so users be able to see text while typing?

**To Reproduce**
1. Go to 'Presentation' 
2. Click on 'Text Tool'
3. Type
4. and until you click out of box no one can see anything

**BBB version (optional):** 2.3.1
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.3.1 (2199)

**Desktop (please complete the following information):**
 - OS: Linux/Windows
 - Browser Chrome

**Comment by HrHeun** [comment] 2021-05-26 08:35
Related to #12345

**Comment by hiroshisuga** [comment] 2021-05-26 11:57
duplicate of #12345

**Closed** 2021-05-26 12:03 UTC
Labels: module: client
