### ISSUE TITLE
Whiteboard drawing bug

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#5428] opened 2018-04-27 18:33 UTC
When you select the edge of the image before drawing and drag to draw it allows you to draw without hold the mouse button.

![whiteboard-bug](https://user-images.githubusercontent.com/15806883/39378925-1f302a0e-4a30-11e8-93fc-71bcef0239c7.gif)

**Comment by antobinary** [comment] 2018-04-27 19:54
Same result if you right-click ->inspect and then move the mouse around

**Comment by ffdixon** [comment] 2019-11-04 09:50
@capilkey Can we close this issue?

**Comment by capilkey** [comment] 2019-11-04 22:11
I can't reproduce anymore. The way the mouse movements are tracked has changed quite a bit since this issue was first opened.

**Closed by capilkey** 2019-11-04 22:11 UTC
Labels: Bug, HTML5 Client
