### ISSUE TITLE
Replace "You are now muted" sounds.

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/bigbluebutton#9352] opened 2020-04-30 09:38 UTC
**Describe the bug**
If you mute or unmute yourself, the nice lady tells you that "you are now (un)muted". This intereferes with other people speaking and yourself (people usually wait for the sounds to end until the strat to speak).

**To Reproduce**
(Un)mute yourself.

**Expected behavior**
* no sound at all
* a short sound (like the well-known Windows USB plug-in/out sound)

**Actual behavior**
The nice lady is speaking to me every time I (un)mute myself.

**Additional context**
I know that I can customize this. But I think the default should change.

**Comment by kfern** [comment] 2020-04-30 10:21
@debuglevel Have you seen https://docs.bigbluebutton.org/2.2/customize.html#turn-off-you-are-now-muted?

**Comment by flipreverse** [comment] 2020-04-30 12:37
Is it expected behavior that this files gets overwritten on update?
I just updated to the latest release and my changes to `conference.xml` are lost.

**Comment by debuglevel** [comment] 2020-04-30 16:10
@kfern Have you seen

> **Additional context**
> I know that I can customize this. But I think the default should change.

**Comment by basisbit** [comment] 2020-04-30 17:22
@flipreverse all your changes should be part of the [`apply-config.sh` script](https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart), so that they get reapplied at the end of updating BigBlueButton.

**Comment by debuglevel** [comment] 2020-04-30 18:24
Of course, it's not too hard to `diff` and then `patch` in `apply-config.sh`.

Nevertheless, sometimes the default should be oriented on what most other video conferencing softwares do. Furthermore the "you are now muted" sound is not part of i18n.

**Comment by ralferlebach** [comment] 2020-05-10 14:26
Here is a quick & dirty solution, I came up these days:

Just replace both files conf-muted.wav and conf-unmuted.wav in the directory
/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000

with, for example, these two ("beep" and "boob"). Feel free, also to produce files for 32000, 16000, and 8000 Hz sampling rates and place them into the directories accordingly.

This tiny & naive "hack" also survived the last update from 2.2.5  to 2.2.9 and my users highly appreciated these change. So have fun.

PS: You may also change the "Xou are the only person in this conference." announcement by this way as well. However, I did not came up with an idea for an appropriate sound for that.
[mute-unmute-sounds.zip](https://github.com/bigbluebutton/bigbluebutton/files/4605779/mute-unmute-sounds.zip)

**Comment by bpcurse** [comment] 2020-05-11 22:31
> Of course, it's not too hard to `diff` and then `patch` in `apply-config.sh`.
> 
> Nevertheless, sometimes the default should be oriented on what most other video conferencing softwares do. Furthermore the "you are now muted" sound is not part of i18n.

We have just begun using BigBlueButton on our own server and all users are pretty impressed, but almost everybody immediately wanted the mute/unmute audio playback removed oder replaced as it is quite annoying.

**Comment by paulmenzel** [comment] 2020-05-14 08:46
> Is it expected behavior that this files gets overwritten on update?
> I just updated to the latest release and my changes to `conference.xml` are lost.

https://github.com/bigbluebutton/bigbluebutton/issues/9376 is a dedicated issue for that.

**Comment by MartinHarran** [comment] 2020-10-31 12:00
I have followed the instructions at 
https://docs.bigbluebutton.org/2.2/customize.html#turn-off-you-are-now-muted and moved the parameters into comments.
It has no effect – I still get the audio notifications even after restarting BBB. Any suggestions on what I might be doing wrong?

**Comment by basisbit** [comment] 2020-10-31 12:18
@MartinHarran For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by MartinHarran** [comment] 2020-10-31 12:45
> @MartinHarran For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

Sorry about that

**Comment by matiasilva** [comment] 2020-10-31 16:02
Is there still a point in this issue? Instructions for removing it are in the documentation...

**Comment by larsan** [comment] 2020-10-31 16:21
@matiasilva Yes,
> **Additional context**
> I know that I can customize this. But I think the default should change.

And to me too, either option would be a better considered default.

**Comment by MartinHarran** [comment] 2020-10-31 16:58
> Is there still a point in this issue? Instructions for removing it are in the documentation...

The instructions are easy to get wrong; I didn't realize that there are a number of profiles in the conference.conf.xml file and I commented out the parameters in the first one 'default' which seemed the logical one. My mistake, obviously but am easy one to make.

**Comment by debuglevel** [comment] 2020-11-17 14:51
To be honest: I don't know anybody who likes to hear "You are now (un)muted" 20 times a day when they attend an online workshop. So, yes: The main point of the issue does still exist: Getting rid of this sound file and replacing it with none (state of most other online conferencing software) or at least a nice short beep.

**Comment by ralferlebach** [comment] 2020-11-18 08:50
> To be honest: I don't know anybody who likes to hear "You are now (un)muted" 20 times a day when they attend an online workshop. So, yes: The main point of the issue does still exist: Getting rid of this sound file and replacing it with none (state of most other online conferencing software) or at least a nice short beep.

I completely agree with you. Have you seen my solution to that problem? We are running this and are very satisfied with that.
https://github.com/bigbluebutton/bigbluebutton/issues/9352#issuecomment-626336465

**Comment by lentemoore** [comment] 2021-01-25 10:03
Could maybe a toggle in the settings be added? For users (and not hosters) it is impossible to get rid of the sound, so we are at the mercy of whoever is providing our BBB server.

**Comment by hatzfeld** [comment] 2021-02-03 19:56
Like @lentemoore I'd suggest to add a toggle to the individual settings which enables to enable / disable audio notices.

**Comment by alanna** [comment] 2021-07-05 23:08
Big +1 to this
> add a toggle to the individual settings which enables to enable / disable audio notices

**Comment by josx** [comment] 2021-09-20 14:25
Yes, would be great to have an UI to disabled this kind of sounds in the html5 client.

**Comment by ffdixon** [comment] 2021-11-25 15:37
We're leaning towards replacing these sound as well.  Here are two other sounds to replace those phrases

https://ubuntu.bigbluebutton.org/files/conf-muted.wav
https://ubuntu.bigbluebutton.org/files/conf-unmuted.wav

you can overwrite the two files with these sounds

/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/conf-muted.wav
/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/conf-unmuted.wav

**Comment by basisbit** [comment] 2021-11-25 15:43
Some other (public domain / cc-0 licensed) mute/unmute sounds: https://gitlab.senfcall.de/senfcall-public/mute-and-unmute-sounds

**Comment by ffdixon** [comment] 2021-11-25 20:51
@basisbit I think senfcall's sounds are the best so far :-)

**Comment by debuglevel** [comment] 2021-11-27 14:41
I think Zoom, MS Teams und my Android phone have the best sounds. ;-) In fact, most telephony solutions use those exactly same sounds.

**Comment by ffdixon** [comment] 2021-11-27 22:59
Unless a commercial company has open sourced their sounds (we would need to see a URL to the audio files, hosted by the company, with an associated open source license), we are not going to us them.

**Comment by ralferlebach** [comment] 2021-11-28 06:55
Dear Fred, dear all,

I've created these two sounds in Audacity by my very own and we used it at our universities BBB instance to our great satisfaction.

I hereby officially release them to public domain use und would be pleased to hear this beep and boop in BBB in future as well.
https://github.com/bigbluebutton/bigbluebutton/issues/9352#issuecomment-626336465

**Comment by debuglevel** [comment] 2021-11-28 17:38
MS Teams, Zoom sounds etc should be public domain. Just create an empty file `null.wav`.

**Comment by alanna** [comment] 2021-11-28 20:40
Please also include the option to turn it off entirely or select a silent
sound! Not being able to mute this sound was one of the key reasons we
stopped using BBB :(

**Comment by GhaziTriki** [comment] 2021-11-28 21:28
@alanna If you remove the sound files from the server or reconfigure the Freeswitch dial plan you should get rid of those sounds. Almost everything that can be configured is configurable in BigBlueButton.

**Comment by ffdixon** [comment] 2021-11-28 21:32
See also https://docs.bigbluebutton.org/admin/customize.html#turn-off-you-are-now-muted

**Comment by debuglevel** [comment] 2021-11-29 19:02
Of course everything can be configured somehow. That's the equivalent of "You want a new feature? Just fork it, it's open source." But most things do not need to be configurable, but just need a sane default setting. And in case you do not want to ask or listen to the audience, it's usually a good idea to use usability heuristics and have a look how all the other tools implemented this feature (because *they* probably asked their users).

Let's have a look:
* MS Teams: no sound on (un)mute
* Zoom: no sound on (un)mute
* Skype: no sound on (un)mute
* Jitsi: no sound on (un)mute
* Google Meet: no sound on (un)mute
* Every business phone: no sound on (un)mute
* Android: no sound on (un)mute

And if the next comment is "we are not the others": Please just close this issue with wontfix or something after 1,5 years.

**Comment by ffdixon** [comment] 2021-11-29 19:18
@debuglevel We have docs to remove it in 2.4 https://docs.bigbluebutton.org/admin/customize.html#turn-off-you-are-now-muted.  No need to fork, it's just a configuration change on your BigBlueButton server.

We are going to replace this sound in 2.5 with a very short sound (not words).

We will not close this issue until it's resolved.

**Comment by alanna** [comment] 2021-12-03 08:40
I am a user. I have no control over the configuration of the server. Well,
I WAS a user, until my company stopped using BBB in part due this annoying
sound.

**Comment by basisbit** [comment] 2021-12-03 09:58
@alanna then please contact your BigBlueButton provider, instead of complaining here about the configuration that your BBB provider uses.

**Comment by astrojuanlu** [comment] 2021-12-09 10:44
The [server configuration](https://docs.bigbluebutton.org/admin/customize.html#turn-off-you-are-now-muted) has been mentioned a number of times. But why can't this be configured on the client?

**Comment by hostbbb** [comment] 2021-12-09 14:40
the sounds are played from the freeswitch conference, and part of the conference settings and ESL events.  currently no way to pass these per meeting settings into freeswitch on conference create without bunch of code.

**Comment by debuglevel** [comment] 2021-12-09 20:14
FreeSWITCH should not play anything. The HTML5 client should play this sound. This way every user could disable this bug hisself.

**Comment by GhaziTriki** [comment] 2021-12-09 20:30
@debuglevel Freeswitch is a telco stack and playing the sounds should be there since it is the piece fully aware of audio users and doing the mixing. With some coding you can change few things on the dial plan. You cab change the audio files themselves on the server too.

**Comment by hostbbb** [comment] 2021-12-09 21:00
@debuglevel , so you can comment out the mute/unmute in conference profile, and work on a pull request to play localized client side audio prompts to the user.  One use case, where a teacher mutes a student(s) (setting in bbb-web) would require that you detect the ESL event change in mongo to play the client side audio clip to affected users.    Also, adding the localization, and ability to change via settings.yml more work.   Sounds like you "you are kicked", "you are only one in conference" have questionable value...   beauty of open source if its important to someone will get done eventually.

**Comment by debuglevel** [comment] 2021-12-10 07:37
@GhaziTriki Yes, I guess all the other commercial tools are just doing it wrong when their clients play user specific sound directly in the client.
@hostbbb God thanks, there is the "it's open source. fork it yourself" comment. I almost lost my faith.

I guess it would be too simple and too user-centric to implement this on the client side and allow users to disable it.

**Comment by MartinHarran** [comment] 2021-12-10 10:30
I have been watching this discussion. I see quite a few people who **do not** want these sounds; maybe I’ve missed something but I don’t see anyone who **does** want them. Defaults should be set to what most people are likely to want.

**Comment by hostbbb** [comment] 2021-12-10 10:45
A number of implementations provide telephone dial in access to conferences,  so need to make sure that its clear to a casual phone user that they have been muted, or unmuted.   Tones in the phone to a causal participant won't achieve this.

This enhancement request to do it client side is valid, why it is has remained open.   just a matter of a capable developer in the community working on it over the priorities, not a fork... a pull request.

**Comment by alanna** [comment] 2021-12-11 02:35
Why not only have it on for phone users then? Because it seems most
non-phone users really don't want this sound.

**Comment by hostbbb** [comment] 2021-12-11 10:14
Yes the esl events that trigger the mute are conference wide and its mod_confernece that sends this audio to member channel server side.   So need to be able to discern if member is a web user or dialin/sip user...   couple of ways to do this

**Comment by debuglevel** [comment] 2021-12-11 14:51
Or only enable those sounds (manually) if there is a telephony integration - because usually, there is none.

**Comment by basisbit** [comment] 2021-12-12 01:14
they are also needed for non-telephone users when a moderator mutes/unmutes the user.

**Comment by debuglevel** [comment] 2021-12-12 11:05
Works fine without such a sound in all other conference software, as they usually have a screen where they see such a notification.

**Comment by hostbbb** [comment] 2021-12-12 15:11
https://mconf.github.io/api-mate/ <-- start a meeting on test-install, listen to the mute/unmute currently deployed, and example of changing server side... i'll stick with stock freeswitch sounds..  you could change audio to "muted" "unmuted" to make it shorter 

but enabling client side and giving "user ability to turn off notifications", so its completely silent,  may need a new issue with the feature details.   if you turn off your sounds, and the teacher unmutes/mutes you cant tell unless your watching userlist.

**Closed** 2022-03-21 17:15 UTC
