### ISSUE TITLE
2 screens - one presentation full screen, other webcams

### ISSUE THREAD

**Issue by falkiy** [bigbluebutton/bigbluebutton#12171] opened 2021-04-27 12:19 UTC
Hi,

I'm not sure if this is some kind of feature requests, HTML5 issue or maybe missed something in documentation.
Intended behavior is:
Monitor 1: Presentation (full screen)
Monitor 2: Webcams/chat and so on (ideally also full screen)

So far I didn't find a proper way to do that without joining multiple times as "different" identities.
I already tested 2.3 beta, really like the new feature to move the webcam windows, but didn't figure out as intended.

Second idea was, is there a way to join as same identity/sessionToken on different browser windows/tabs, without kicked out of the first session(401)?
We're also open for some kind of workarounds.

Thank You!

**Comment by prlanzarin** [comment] 2021-04-27 12:29
> Intended behavior is:
> Monitor 1: Presentation (full screen)
> Monitor 2: Webcams/chat and so on (ideally also full screen)

I'm marking this as a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11403 (look at PR #11645)

> Second idea was, is there a way to join as same identity/sessionToken on different browser windows/tabs, without kicked out of the first session(401)?

Not that _I_ know of. There's the allowRequestsWithoutSession configuration you can try out at bbb-web/bigbluebutton.properties, but I'm not sure whether it prevents ejection of the first (derelict) session.

**Closed by prlanzarin** 2021-04-27 12:29 UTC
Labels: type: enhancement
