### ISSUE TITLE
Implement breakout rooms

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#2840] opened 2015-10-15 15:57 UTC
Sometimes in a meeting, there is a need to break the audience into smaller groups to be able to collaborate with each other. Then after, go back into the meeting and share what might have been discussed.

Moderators and presenter should be able to create breakout rooms and assign users into each room.

**Comment by GhaziTriki** [comment] 2016-03-10 22:18
It is a duplicate of #1934

**Comment by ffdixon** [comment] 2016-03-10 22:19
Duplicate of #1934

**Closed by ffdixon** 2016-03-10 22:19 UTC
