### ISSUE TITLE
Download Recording

### ISSUE THREAD

**Issue by voltan** [bigbluebutton/bigbluebutton#12935] opened 2021-08-07 13:22 UTC
Hello

Does BBB have an option or web service for download recordings as mp4?

**Comment by hiroshisuga** [comment] 2021-08-08 00:54
Officially not, but there are a couple of solutions proposed. Among these, 
https://github.com/danielpetri1/bbb-recording-exporter
is the best one in my personal opinion.

**Comment by antobinary** [comment] 2021-08-08 01:45
Link to the pull request: https://github.com/bigbluebutton/bigbluebutton/pull/12533 from the same author

**Comment by hiroshisuga** [comment] 2021-08-08 04:34
And it's a duplicate of #1969, which has been duplicated many times already...

**Comment by voltan** [comment] 2021-08-08 06:10
Thank you very much& I will text it

**Closed** 2021-08-08 14:13 UTC
Labels: module: recording
