### ISSUE TITLE
download recording feature

### ISSUE THREAD

**Issue by dfasani** [bigbluebutton/bigbluebutton#11190] opened 2021-01-20 15:12 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to download a session's recording.

**Describe the solution you'd like**
Propose a download button, that would allow me to download in a single archive :

- video/audio content
- présentation + whiteboard modification
- chat
- subtitles
- breakout rooms content
- 

**Describe alternatives you've considered**
Propose a feature that could allow me to upload the data directly to a cloud service (e.g. google drive, owncloud, ...)

**Additional context**

**Comment by basisbit** [comment] 2021-01-20 16:48
duplicate of #1969

**Closed by basisbit** 2021-01-20 16:48 UTC
Labels: Enhancement
