### ISSUE TITLE
Long poll choices displays very small

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#5265] opened 2018-03-21 17:41 UTC
When creating a custom poll with relatively long choices, they deisplay very small and can't be read.

![image 319](https://user-images.githubusercontent.com/4991088/37727139-5e28d5d2-2d37-11e8-91bf-8f5dee93a314.png)
![image 321](https://user-images.githubusercontent.com/4991088/37727146-60c4ed76-2d37-11e8-98b0-b97a83f36cf0.png)

**Comment by OZhurbenko** [comment] 2018-03-21 18:51
I think that's intended behavior, a shape always takes a certain % of the slide, and then 30% (if I'm not mistaken) of the shape's width is given to the label with the answer.

We just change the font-size to fit the whole answer to those 30%.

Long answers are not really usable.. :neutral_face:

**Comment by oswaldoacauan** [comment] 2018-03-23 18:04
A question, why we use SVG? Can`t we add a actual interface for the response in 2.1?

As far I remember it was done in SVG because was the quickest way to add it in the client, since is just a whiteboard message.

**Comment by capilkey** [comment] 2018-03-23 18:11
The polls don't have a question. If you tried to display the results on their own they wouldn't have any context. The intended usage is to have the question in the slide so it makes sense to show the result there also.

**Comment by oswaldoacauan** [comment] 2018-03-23 18:27
Well, that doesn't mean they need to be a annotation in the whiteboard :)

**Comment by ffdixon** [comment] 2019-04-07 03:45
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).

**Comment by ffdixon** [comment] 2019-04-07 03:46
Re-opened as this is still an issue with display of polling choices in HTML5 client.

**Comment by grinapo** [comment] 2020-04-25 12:55
That's #6782 in disguise?

**Comment by prlanzarin** [comment] 2021-04-04 13:37
Merging into #6782 (which is basically the same issue, but targeted at the HTML5 client).

**Closed by prlanzarin** 2021-04-04 13:37 UTC
Labels: module: client
