### ISSUE TITLE
Multi cursors while screen sharing is active

### ISSUE THREAD

**Issue by erdalkaraca** [bigbluebutton/bigbluebutton#10387] opened 2020-09-03 13:07 UTC
**Is your feature request related to a problem? Please describe.**
When one participant actives screen sharing, there is only verbal communication possible for the other users to interact with each other.

**Describe the solution you'd like**
It would be great if the mouse location of all participants could be layed over the shared screen such that a better interaction would be possible. I think the multi user whiteboard has similar functionality except it is meant for collaborative drawing.

**Describe alternatives you've considered**
Alternatives include collaborative external tools that have this functionality built in.

**Additional context**
Use case: one participant shares the screen showing some code to talk about (for example a code review process). Other participants want to highlight a specific code location visible on that screen but have no other way to communicate this than verbally.

**Comment by uka-support** [comment] 2020-09-03 13:29
This is a duplicate of #8929

**Comment by erdalkaraca** [comment] 2020-09-03 13:34
Thanks, indeed this is a duplicate of the linked issue.

> This is a duplicate of #8929

**Closed** 2020-09-03 13:33 UTC
Labels: Enhancement
