### ISSUE TITLE
Presentation area: "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by MaximKhlobystov** [bigbluebutton/bigbluebutton#8032] opened 2019-08-29 18:41 UTC
I was able to hit the following error that was displayed instead of the presentation area:
![error](https://user-images.githubusercontent.com/5004762/63966211-beeb1e00-ca68-11e9-8615-f664e6afa0e8.png)

**Comment by millad90s** [comment] 2020-10-14 08:18
occurred for me as well. what is the root cause ? and what is the solution ?

**Comment by matiasilva** [comment] 2020-10-14 09:20
@millad90s notice the date, if there were a solution then this issue would be closed ;) 

also, I believe a few things can give rise to such an error so more information is needed.

**Comment by millad90s** [comment] 2020-10-14 09:22
So lets work on this issue.

**Comment by matiasilva** [comment] 2020-10-14 09:27
How?

More information is needed to determine the cause of the issue.

**Comment by antobinary** [comment] 2021-04-07 23:36
Fixed by https://github.com/bigbluebutton/bigbluebutton/pull/11650

**Closed by antobinary** 2021-04-07 23:36 UTC

**Comment by testprepturkey** [comment] 2023-02-18 21:49
still persistent at 2.6.0 RC4
