### ISSUE TITLE
etherpad problem on 2.2.34

### ISSUE THREAD

**Issue by talpaworld** [bigbluebutton/bigbluebutton#11546] opened 2021-03-03 23:19 UTC
**Describe the bug**
Exporting from etherpad is not possible on a newly installed BBB server (v2.2.34).
"Error 401 Authorization Required - nginx"

**To Reproduce**
1. Start the conference
2. Enter text into the pad
3. Click on exportbutton (The selection of the format does not matter)
4. See error 401

**Expected behavior**
The text from the pad should be exported

**Actual behavior**
nginx shows "Error 401 Authorization Required"

**Desktop**
 - OS: [Windows, Mac, iPad]
 - Browser [Firefox, Chrome, Safari]
 - Version [FF 86]

**Comment by ichdasich** [comment] 2021-03-03 23:22
This is a duplicate of #11545; Please also check that for a hot-fix (with unclear security implications)

**Comment by prlanzarin** [comment] 2021-03-03 23:31
Duplicate of #11545.

**Closed by prlanzarin** 2021-03-03 23:31 UTC
