### ISSUE TITLE
Webcams do not disconnect from main room when breakout rooms are launched.

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#7368] opened 2019-05-07 21:42 UTC
when users are sharing a webcam in the main room they are not disconnected when the user joins the breakout room.

all media in the main room should be disconnected when the user joins a breakout.

**Comment by antobinary** [comment] 2019-05-07 21:58
Duplicate of #7291

**Closed by antobinary** 2019-05-07 21:58 UTC
