### ISSUE TITLE
Place warning before deleting everything on whiteboard

### ISSUE THREAD

**Issue by poetslipvis** [bigbluebutton/bigbluebutton#7034] opened 2019-03-15 13:03 UTC
It would be nice to have a warning like: are you sure - before deleting everything you sometimes have worked on for hours.... accidentally. See also #6798

**Comment by natewiebe13** [comment] 2020-08-06 19:42
@ffdixon The related issue #6798 mentions working on this after v2.2, would this be in a similar position? One of our clients using this have had this feature requested quite a number of times from their teachers.

**Comment by prlanzarin** [comment] 2021-04-04 14:27
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/6244

**Closed by prlanzarin** 2021-04-04 14:27 UTC
