### ISSUE TITLE
[2.3]Delete the chat kills room completely!

### ISSUE THREAD

**Issue by Smith-fms** [bigbluebutton/bigbluebutton#11427] opened 2021-02-18 20:40 UTC
**Describe the bug**

After opening a session and if someone has written something in the chat, the room will be irreparably destroyed if the delete button of the chat is pressed. Even freeswitch is killed and told that i am the only one, but audio still goes on.

**To Reproduce**
1. Open a room
2. type somethin to chat
3. click on delete of the public chat

**Expected behavior**

A delete command may be wrong here.

**Desktop (please complete the following information):**
-- Any Browser 

Logfiles dont show anything sus.

**Comment by daminebenq** [comment] 2021-02-18 20:44
Hi @Smith-fms 
this was already reported, and already fixed in [e05d888](https://github.com/bigbluebutton/bigbluebutton/pull/11173/commits/e05d8886c643e49dcabbd865ee942630246d52fb) #11173 
I suggest you update to the latest 2.3 version available.
Thanks for the report.

**Comment by antobinary** [comment] 2021-02-18 20:46
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11349

**Closed by antobinary** 2021-02-18 20:46 UTC
Labels: Chat, HTML5 Client
