### ISSUE TITLE
Adding Embed (Iframe) option

### ISSUE THREAD

**Issue by apckish** [bigbluebutton/bigbluebutton#16121] opened 2022-12-13 04:32 UTC
Hello, everyone!

I'm a BBB user and would like contribute with a sugestion.

I'd like to sugest to add embed option(ifame) to bigbluebutton so the users can embed games from the website similar to wordwall.net, so the students can play the game on their own screen. as far as I know mynaparrot company has done it and it is possible. this is a very functional option in making the classrooms and meetings more interactive. most of my friends have problem regarding playing online games in bigbluebutton.

Thanks

**Comment by ffdixon** [comment] 2022-12-13 09:44
Thanks for the suggestion.  Yes, we would like to support this as a core feature in BigBlueButton.   

There is already an issue open for this under a different github account (but the text looks very similar to the above).  Are you [tutooplus](https://github.com/tutooplus) you as well?

Closing this issue as a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/15482.

**Closed by ffdixon** 2022-12-13 09:44 UTC
Labels: type: enhancement
