### ISSUE TITLE
publish Persian poll bug

### ISSUE THREAD

**Issue by itum** [bigbluebutton/bigbluebutton#10675] opened 2020-10-17 12:00 UTC
**Describe the bug**
Hello
The problem we have in BigBlueButton software is in the Persian poll.
When we change the language of the software to Persian and select the poll in Persian, assuming yes / no and the users publish the poll results after announcing their opinion and the conference moderator, the yes / no results are **reversed**.
Also, in the survey results, Persian words are stuck together and some words become illegible.
Please see the video posted in this thread.
Thankful
**To Reproduce**
0. Set BBB language to Persian
1. Go to 'Actions'
2. Click on 'Start a Poll'
3. Publish poll for others
4. See error that reversed result.

**Expected behavior**
correct answers on public polls.

**Screenshots**
<a href="https://uupload.ir/view/nb6_screenshot.png" target="_blank"><img src="https://uupload.ir/files/nb6_screenshot_thumb.png" border="0" alt="" /></a>

video  :
[DOWNLOAD!
](https://uupload.ir/view/2fk_rec_0004.mp4/)
**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.26 (2165) even 2.2.27/2.2.23

**Desktop (please complete the following information):**
 - OS: Windowss
 - Browser : Chrome
 - Version Latest Version

**Smartphone (please complete the following information):**
 - Device:  iPhone 6
 - OS: iOS 12
 - Browser Safari
 - Version Latest Version

**Comment by itum** [comment] 2020-10-21 20:37
any idea ? @ffdixon  please help us.

**Comment by antobinary** [comment] 2020-10-26 14:49
Checking this as part of 2.2. Thanks for reporting!

**Comment by antobinary** [comment] 2020-10-27 14:38
Possibly related to https://github.com/bigbluebutton/bigbluebutton/issues/8082

**Comment by shahrooz-Sharghi** [comment] 2020-11-17 16:57
Dear Antobinary, Yes, it is the same problem #8082 as Persian letters and encoding is the same as Arabic. I have the same problem. You mean it will be solved in next release of BigBlueButton? We are currently using 2.2.

**Comment by qdzmc** [comment] 2021-01-31 08:17
With the same problem, when the number of people is relatively large, the blue screen will appear in the second vote and it needs to be refreshed, after which the voting function will not be used.
bbb2.3-p4

**Comment by pedrobmarin** [comment] 2021-04-11 16:48
Closing since it has being identified as a duplicate of #8082

**Closed by pedrobmarin** 2021-04-11 16:48 UTC
Labels: component: polling, module: client
