### ISSUE TITLE
Cannot leave meeting because of modal disappear. 

### ISSUE THREAD

**Issue by KapustinVadim1991** [bigbluebutton/bigbluebutton#16482] opened 2023-01-17 02:30 UTC
Linked issue https://github.com/bigbluebutton/bigbluebutton/issues/16453

After I join the conference, I close the window with the choice "Connect with a microphone or for listening only" and exit the conference through the options. A modal window appears with a confirmation to leave the conference. By pressing the OK button, a redirect occurs to the link specified in the logoutYURL parameter when creating the conference.

A modal window with an OK button appears for a fraction of a second and disappears, after which I am left with an dark blue screen and the following error is displayed in the browser console

<img width="1772" alt="image" src="https://user-images.githubusercontent.com/61548543/212792270-e2d9a69d-00ee-4168-886d-fe45335f1a60.png">

If you enter in listening mode or turn on the microphone, the error will rarely be reproduced.

**Expected behavior**
The modal window with the "OK" button does not disappear when leaving the conference.

**Actual behavior**
The modal window with the "OK" button does disappear when leaving the conference.

**BBB version:**
BigBlueButton Server 2.5.8 (3139)

**Additional settings**
Meeting create parameters string:
```
       //meetingId - integer
       var meetingIdString = "meeting-" + meetingId;
                var queryString =
                    "name={WebUtility.UrlEncode(subject)}
                    &meetingID={meetingIdString}
                    &logoutURL={WebUtility.UrlEncode(logoutUrl)}
                    &allowRequestsWithoutSession=true
                    &lockSettingsDisableNote=true
                    &allowStartStopRecording=false          
&disabledFeatures=chat,polls,breakoutRooms,customVirtualBackgrounds,captions,externalVideos,sharedNotes,learningDashboard,importPresentationWithAnnotationsFromBreakoutRooms,downloadPresentationWithAnnotations";
```
Get join url parameters string

```
var queryString = $"meetingID={meetingIdString}&fullName={WebUtility.UrlEncode(fullName)}&role=moderator&redirect=false&userdata-bbb_override_default_locale={language}&userdata-bbb_shortcuts=%5B%5D";
```

Changes in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

```
skipCheck: true // пропустить проверку работы микрофона при подключении
hidePresentation: true // скрыть презентацию
showParticipantsOnLogin: false // не показывать список участников сразу при подключении
showHelpButton: false // скрыть кнопку Помощь
selectRandomUser: 
enabled: false // отключить функцию рандомного выбора участника
presentation:
allowDownloadable: false // убираем кнопку презентации (не пропадает при hidePresentation true)
oldMinimizeButton: true  // убираем кнопку презентации (не пропадает при hidePresentation true)
enableNetworkStats: false // убрать кнопку со статистикой о подключении
enableCopyNetworkStatsButton: false // убрать кнопку копирования статистики подключения
stats: 
enabled: false // убрать статистику
label:
Moderator: false // при включенном параметре подпись появляется только в списке юзеров, но не под видео, сделали свою приписку при передаче имени пользователя при коннекте
dynamicGuestPolicy: false
enableGuestLobbyMessage: false
```

**Desktop (please complete the following information):**
 - OS: Mac, Windows
 - Browser Chrome, Safari, Firefox
 - latest
 
**Additional context**
End meeting button for moderator sometimes produces the same behavior

**Comment by antobinary** [comment] 2023-01-19 15:25
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/16483 which is a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/16453
Please use https://groups.google.com/g/bigbluebutton-dev for development related questions, this tracker is not the spot for it. You are building on top of BBB and here we track bugs/enhancement requests for BBB.


P.S. You may want to check https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.0-beta.6/bigbluebutton-html5/imports/startup/client/base.jsx and the logic / checks for meeting existing.
You may also want to put some checks so your code does not rely on potentially undefined objects.

**Closed by antobinary** 2023-01-19 15:25 UTC
Labels: module: client
