### ISSUE TITLE
Attendees mistaken with guests

### ISSUE THREAD

**Issue by soheilrahsaz** [bigbluebutton/bigbluebutton#9651] opened 2020-05-23 06:54 UTC
After updating to 2.2.12
When users are joining it goes to guest lobby but the guest parameter is false.
The same configuration on a 2.2.11 server is fine so the problem must be in 2.2.12.
It doesn't distinguish between attendees and guests.

**Comment by pedrobmarin** [comment] 2020-05-23 12:30
Did you make any changes in your guest policy?

**Comment by soheilrahsaz** [comment] 2020-05-23 12:50
> Did you make any changes in your guest policy?

Of course not. Everything is the same as before.
And also, the guest policy should not have to do anything with it, because I'm joining by users with guest=false and I include attendee password so they should not be considered as guests in the first place.

**Comment by krishnateja-ct** [comment] 2020-05-23 14:19
@pedrobmarin I am also seeing the same issue on 2.2.12 version. Meeting created with guest=false is prompting for moderator approval for authorized users.

**Comment by pedrobmarin** [comment] 2020-05-23 15:55
> Of course not. Everything is the same as before.
First of all, this kind of attitude is totally unnecessary. If I had someone trying to help me free of charge at his/her available weekend hour I would try to be as polite as possible. I was not planning on continuing discussing this thread but since @krishnateja-ct might be experiencing a similar problem I'll give this a second chance.

Checking the last code modifications at BBB core I couldn't bat an eye on what could have caused this change of behaviour. My best guess would be this https://github.com/bigbluebutton/bigbluebutton/pull/9189 but it looks like it is, indeed, a problem solver.

@soheilrahsaz when I first asked about the guest policy wasn't because I had anything better to ask. As far as I understand, BBB will prompt for authorization if any non-moderator user tries to join a meeting with ASK_MODERATOR policy enabled.

There might be a fourth guest policy that does approve all authorized users ALWAYS_ACCEPT_AUTH and will only prompt for true, no-moderator guests. You can try that out first and if that's the behaviour you would expect from an approval feature that's the one to go. For any other information I would need a lot more details on what's the situation since it's not obvious to anyone of the developers what kind of setup everyone uses.

**Comment by Erika31** [comment] 2020-05-26 19:35
As far as I understand the docs and the semantic, I think that "guestPolicy" should only apply to joins with "guest" param equals to "true".

I installed a BBB instance on a server, a few week ago, where the behaviour of "guestPolicy" is like I described above (a non-guest user can join a meeting, regardless of "guestPolicy" value).

> ii  bbb-apps                              1:2.2.0-42                                      amd64        BigBlueButton applications for Red5
> ii  bbb-apps-akka                         2.2.0-77                                        all          BigBlueButton Apps (Akka)
> ii  bbb-apps-screenshare                  1:2.2.0-42                                      amd64        BigBlueButton screenshare module for Red5
> ii  bbb-apps-sip                          1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
> ii  bbb-apps-video                        1:2.2.0-39                                      amd64        BigBlueButton video module for Red5
> ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
> ii  bbb-client                            1:2.2.0-33                                      amd64        BigBlueButton Flash client
> ii  bbb-config                            1:2.2.0-172                                     amd64        BigBlueButton configuration utilities
> ii  bbb-etherpad                          1:2.2.0-50                                      amd64        The EtherPad Lite components for BigBlueButton
> ii  bbb-freeswitch-core                   2:2.2.0-97                                      amd64        BigBlueButton build of FreeSWITCH
> ii  bbb-freeswitch-sounds                 1:1.6.7-6                                       amd64        FreeSWITCH Sounds
> ii  bbb-fsesl-akka                        2.2.0-61                                        all          BigBlueButton FS-ESL (Akka)
> ii  bbb-html5                             1:2.2.0-874                                     amd64        The HTML5 components for BigBlueButton
> ii  bbb-mkclean                           1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
> ii  bbb-playback-presentation             1:2.2.0-28                                      amd64        BigBluebutton playback of presentation
> ii  bbb-record-core                       1:2.2.0-63                                      amd64        BigBlueButton record and playback
> ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
> ii  bbb-transcode-akka                    2.2.0-8                                         all          BigBlueButton Transcoder
> ii  bbb-web                               1:2.2.0-119                                     amd64        BigBlueButton API
> ii  bbb-webhooks                          1:2.2.0-16                                      amd64        BigBlueButton Webhooks
> ii  bbb-webrtc-sfu                        1:2.2.0-99                                      amd64        BigBlueButton WebRTC SFU
> ii  bigbluebutton                         1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)

But I installed another BBB instance on another server 5 days ago, and I am unable to join a non-guest user to a meeting with "guestPolicy" equals to "ALWAYS_DENY".

> ii  bbb-apps                                    1:2.2.0-42                                      amd64        BigBlueButton applications for Red5
> ii  bbb-apps-akka                               2.2.0-82                                        all          BigBlueButton Apps (Akka)
> ii  bbb-apps-screenshare                        1:2.2.0-42                                      amd64        BigBlueButton screenshare module for Red5
> ii  bbb-apps-sip                                1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
> ii  bbb-apps-video                              1:2.2.0-39                                      amd64        BigBlueButton video module for Red5
> ii  bbb-apps-video-broadcast                    1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
> ii  bbb-check                                   1:2.2.0-5                                       amd64        Client check package for BigBlueButton
> ii  bbb-client                                  1:2.2.0-40                                      amd64        BigBlueButton Flash client
> ii  bbb-config                                  1:2.2.0-182                                     amd64        BigBlueButton configuration utilities
> ii  bbb-etherpad                                1:2.2.0-50                                      amd64        The EtherPad Lite components for BigBlueButton
> ii  bbb-freeswitch-core                         2:2.2.0-109                                     amd64        BigBlueButton build of FreeSWITCH
> ii  bbb-freeswitch-sounds                       1:1.6.7-6                                       amd64        FreeSWITCH Sounds
> ii  bbb-fsesl-akka                              2.2.0-62                                        all          BigBlueButton FS-ESL (Akka)
> ii  bbb-html5                                   1:2.2.0-910                                     amd64        The HTML5 components for BigBlueButton
> ii  bbb-mkclean                                 1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
> ii  bbb-playback-presentation                   1:2.2.0-29                                      amd64        BigBluebutton playback of presentation
> ii  bbb-record-core                             1:2.2.0-65                                      amd64        BigBlueButton record and playback
> ii  bbb-red5                                    1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
> ii  bbb-transcode-akka                          2.2.0-8                                         all          BigBlueButton Transcoder
> ii  bbb-web                                     1:2.2.0-125                                     amd64        BigBlueButton API
> ii  bbb-webrtc-sfu                              1:2.2.0-99                                      amd64        BigBlueButton WebRTC SFU
> ii  bigbluebutton                               1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)

Does someone have an explanation of this situation ? Is this a regression ?

NB: I don't understand the version numbers between the github repository and the ubuntu packages (16.04 LTS in my case), that's why I dumped the output of "bbb-conf --status" for each involved server...

**Comment by SamuelWei** [comment] 2020-07-15 08:01
@Erika31 I'm also confused by the paramters and the guest policy, see my comment on #9099. I found the code where authned is set. It can be configured with the undocumented parameter 'auth' on joining a meeting.

**Comment by SamuelWei** [comment] 2020-07-28 09:56
@soheilrahsaz @krishnateja-ct The problem can be found here: https://github.com/bigbluebutton/bigbluebutton/blob/c33ed683f37340e6a9d3585339fa04711cde7420/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L249

In case the request parameter is `guest=false`, the internal variable `authenticated` isn't set to true. 
I think it could be a bug in bbb. @pedrobmarin Can you explain this behavoir, what is the propose, is it a bug, ...?
See my issue on our php-api fork: https://github.com/littleredbutton/bigbluebutton-api-php/issues/36

If you want to login a user as non-guest, just don't send the `guest` parameter in the url or add the parameter `auth=true`

**Comment by pedrobmarin** [comment] 2020-07-28 12:18
@SamuelWei I was one of the developers of the `guest` feature a couple of years ago. Back then guest users were the same regular users (moderators and viewers) that would need a moderator's approval to join the meeting. Things got a little weird when `authenticated` users got mixed up with this feature and the problem is I have no idea of what an authenticated users is supposed to be.

At first I thought authenticated users were just the opposite of a guest user but then I went through the API code and found out that they can have any combination of values just like you pointed out. I reached out other developers and, as far as I understood, this is not a bug. It's just a beta-like custom feature that doesn't fit the bigbluebutton's regular use.

My advise right now is just to avoid using both guest and auth params at API calls. The guest as a feature should work well enough by just setting the guest policy since `ASK_MODERATOR` will prompt moderator for approval of any non-moderator participant trying to join the meeting. That's what Greenlight folks have being using so far.

**Comment by SamuelWei** [comment] 2020-07-28 14:51
@pedrobmarin Thank you for your response and the insight. It might help some people if you would update the api docs. https://docs.bigbluebutton.org/dev/api.html#join and inform about not sending guest=false, the authenticated param, the ALWAYS_ACCEPT_AUTH setting , maybe add experiential or something like that as a note.


---
**ALWAYS_ACCEPT_AUTH**
https://github.com/bigbluebutton/bigbluebutton/blob/41f19a2cd1bc7dae76cbd805cdc3ddfbf1e6ab18/bbb-common-web/src/main/java/org/bigbluebutton/api/domain/GuestPolicy.java#L7

**Comment by doothapp** [comment] 2020-08-14 11:17
> @soheilrahsaz @krishnateja-ct The problem can be found here:
> 
> https://github.com/bigbluebutton/bigbluebutton/blob/c33ed683f37340e6a9d3585339fa04711cde7420/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L249
> 
> In case the request parameter is `guest=false`, the internal variable `authenticated` isn't set to true.
> I think it could be a bug in bbb. @pedrobmarin Can you explain this behavoir, what is the propose, is it a bug, ...?
> See my issue on our php-api fork: [littleredbutton/bigbluebutton-api-php#36](https://github.com/littleredbutton/bigbluebutton-api-php/issues/36)
> 
> If you want to login a user as non-guest, just don't send the `guest` parameter in the url or add the parameter `auth=true`

Thank you @SamuelWei for the easy fix.

**Comment by skumarm** [comment] 2020-08-14 11:19
> @soheilrahsaz @krishnateja-ct The problem can be found here:
> 
> https://github.com/bigbluebutton/bigbluebutton/blob/c33ed683f37340e6a9d3585339fa04711cde7420/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L249
> 
> In case the request parameter is `guest=false`, the internal variable `authenticated` isn't set to true.
> I think it could be a bug in bbb. @pedrobmarin Can you explain this behavoir, what is the propose, is it a bug, ...?
> See my issue on our php-api fork: [littleredbutton/bigbluebutton-api-php#36](https://github.com/littleredbutton/bigbluebutton-api-php/issues/36)
> 
> If you want to login a user as non-guest, just don't send the `guest` parameter in the url or add the parameter `auth=true`

Thank you @SamuelWei for the easy fix.

**Comment by matiasilva** [comment] 2020-08-14 18:06
@SamuelWei would you mind submitting this in a pull request to the documentation repo?

**Comment by SamuelWei** [comment] 2020-08-14 18:18
@matiasilva I created the PR

**Comment by ffdixon** [comment] 2020-08-15 00:43
Merged https://github.com/bigbluebutton/bigbluebutton.github.io/pull/186.

**Closed** 2020-10-11 10:07 UTC
