### ISSUE TITLE
Update bbb-web

### ISSUE THREAD

**Issue by squid46** [bigbluebutton/bigbluebutton#9660] opened 2020-05-23 22:18 UTC
Hello.

File "bigbluebutton.properties" parameter defaultWelcomeMessage. 
Before update
defaultWelcomeMessage=\u0414\u043e\u0431\u0440\u043e \u043f\u043e\u0436\u0430\u043b....
after update
defaultWelcomeMessage=0414043e04310440043e 043f043....

**Comment by basisbit** [comment] 2020-05-25 00:21
Please use the `appy-config.sh` script to apply your customization after each bbb update. See https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart

**Comment by squid46** [comment] 2020-05-25 03:46
It's easier to prescribe with your hands than to sort it out.

**Comment by rasos** [comment] 2020-05-27 19:28
Duplicate of #9370 - upgrading removes the `\u` from escaped characters

**Comment by basisbit** [comment] 2020-05-31 01:39
Thank you @rasos!

**Closed by basisbit** 2020-05-31 01:39 UTC
