### ISSUE TITLE
Shared notes not highlighting when selected

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7628] opened 2019-06-15 20:08 UTC
Currently, when showing Public Chat, it's shown as highlighted in the Users list.

![highlight](https://user-images.githubusercontent.com/290351/59555879-c3cf2400-8f87-11e9-88bd-90b523bad500.gif)

However, selecting Shared Notes does not highlight the label in a similar format

**Comment by antobinary** [comment] 2019-06-17 12:08
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/7605

**Closed by antobinary** 2019-06-17 12:08 UTC
