### ISSUE TITLE
User can still interact with the application after he has been kicked out

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#3088] opened 2016-04-19 13:18 UTC
A kicked out user can interact with the application components. All interaction should be blocked even if he has been disconncted from the server components.

To watch the current behaviour: http://screencast.com/t/14davS6FN

**Comment by capilkey** [comment] 2016-04-19 15:50
Is this caused by this PR, https://github.com/bigbluebutton/bigbluebutton/pull/3049/files?

The lines that removed the MDIWindows were removed here, https://github.com/bigbluebutton/bigbluebutton/pull/3049/files#diff-50882930092d50283beabb13f7c50104L529

**Comment by GhaziTriki** [comment] 2016-04-19 16:14
The removeAllWindows was buggy and I had to replace it by using the module STOP events. I don't think the PR #3049 has to do something with it.

**Comment by capilkey** [comment] 2016-04-19 16:33
The problem is that the module stop functions are only called when the user logs out and not when they are kicked from the meeting.

**Comment by ffdixon** [comment] 2016-05-09 11:59
Fixed in

  https://github.com/bigbluebutton/bigbluebutton/pull/3120

**Closed by ffdixon** 2016-05-09 11:59 UTC
