### ISSUE TITLE
Failed to start Disable Transparent Huge Pages.

### ISSUE THREAD

**Issue by odenbach** [bigbluebutton/bigbluebutton#9411] opened 2020-05-04 14:42 UTC
**Describe the bug**
Service `disable-transparent-huge-pages.service` does not run correctly.

**To Reproduce**
Run a BBB server.
`systemctl status disable-transparent-huge-pages.service`

**Expected behavior**
Active: active

**Actual behavior**
Active: failed

**Screenshots**
```
root@birgit[~]# systemctl status disable-transparent-huge-pages.service
● disable-transparent-huge-pages.service - Disable Transparent Huge Pages
   Loaded: loaded (/usr/lib/systemd/system/disable-transparent-huge-pages.service; enabled; vendor prese
   Active: failed (Result: exit-code) since Mon 2020-04-27 16:06:10 CEST; 1 weeks 0 days ago
 Main PID: 1796 (code=exited, status=203/EXEC)

Apr 27 16:06:09 birgit systemd[1]: Starting Disable Transparent Huge Pages...
Apr 27 16:06:10 birgit systemd[1]: disable-transparent-huge-pages.service: Main process exited, code=exi
Apr 27 16:06:10 birgit systemd[1]: Failed to start Disable Transparent Huge Pages.
Apr 27 16:06:10 birgit systemd[1]: disable-transparent-huge-pages.service: Unit entered failed state.
Apr 27 16:06:10 birgit systemd[1]: disable-transparent-huge-pages.service: Failed with result 'exit-code
root@birgit[~]# systemctl cat disable-transparent-huge-pages.service
# /usr/lib/systemd/system/disable-transparent-huge-pages.service
[Unit]
Description=Disable Transparent Huge Pages

[Service]
Type=oneshot
ExecStart=/usr/bin/sh -c "/usr/bin/echo "never" | tee /sys/kernel/mm/transparent_hugepage/enabled"
ExecStart=/usr/bin/sh -c "/usr/bin/echo "never" | tee /sys/kernel/mm/transparent_hugepage/defrag"

[Install]
WantedBy=multi-user.target

```
**Additional context**
Easy solution: Use `/bin/sh` instead of `/usr/bin/sh`, and `/bin/echo` instead of `/usr/bin/echo`:

```
ExecStart=/bin/sh -c "/bin/echo "never" | tee /sys/kernel/mm/transparent_hugepage/enabled"
ExecStart=/bin/sh -c "/bin/echo "never" | tee /sys/kernel/mm/transparent_hugepage/defrag"

```

**Comment by hex-m** [comment] 2020-05-16 15:45
This may be a duplicate of #9077

**Comment by odenbach** [comment] 2020-05-18 15:29
Yes, it is. I just supposed a better fix for this in the other issue.

**Closed** 2021-04-11 13:05 UTC
