### ISSUE TITLE
add possibility to create more than 8 breakout rooms at once

### ISSUE THREAD

**Issue by ownhardy** [bigbluebutton/bigbluebutton#10685] opened 2020-10-20 18:45 UTC
**Is your feature request related to a problem? Please describe.**
I hold online lecture with BBB. There might be 40 participants. And every once in a while, I "kick" all participants into small groups, using the BBB breakout rooms, and let them do group discussions or group work. The ideal group size for this would be 2 or 3 participants per group. Therefore I would need 15 to 20 simultaneous breakout rooms. But currently the number of breakout rooms in BBB seems to be limited to 8.

**Describe the solution you'd like**
Allow for more breakout rooms, maybe 20.

**Describe alternatives you've considered**
Now I can only use 8 breakout rooms, so each of those rooms gets much more participants then I would like to.

**Additional context**
I know (for my case) that those very small groups are better than bigger groups. Because I also did this in lectures in lecture halls. Each participant is then supposed to talk to his direct neighbour.

**Comment by ffdixon** [comment] 2020-10-20 22:59
See https://github.com/bigbluebutton/bigbluebutton/pull/10434

**Comment by matiasilva** [comment] 2020-10-21 07:15
Duplicate of #8657

**Closed by matiasilva** 2020-10-21 07:15 UTC
Labels: Enhancement

**Comment by ownhardy** [comment] 2020-10-21 19:36
Sorry for opening a duplicate issue.  I haven't found #8657 (and the corresponding patch) myself before.
