### ISSUE TITLE
Fit to width not displaying properly for viewers 

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#6583] opened 2019-01-17 22:22 UTC
When "fit -to -width" is selected the presentation does not display properly for viewers:

-display area of the screen is not taken up on desktop or mobile:

Desktop:
![fittowidth](https://user-images.githubusercontent.com/18176998/51352638-38a33e00-1a7c-11e9-80ed-0d297d0c430c.PNG)

Mobile (landscape view):

![capture _2019-01-17-17-14-00](https://user-images.githubusercontent.com/18176998/51352676-55d80c80-1a7c-11e9-96e6-09dcf94f9554.png)

**Comment by antobinary** [comment] 2019-01-17 22:23
Is this a duplicate of #6489 ?

**Closed** 2019-01-17 22:44 UTC
