### ISSUE TITLE
Request annotation feature to a shared screen or application window

### ISSUE THREAD

**Issue by jingwenw** [bigbluebutton/bigbluebutton#8929] opened 2020-03-30 21:04 UTC
**Is your feature request related to a problem? Please describe.**
When my student is working on coding in a share application window, I always try to do some annotation on his code in addition to talk, but I could NOT while I know Zoom has such feature.

**Describe the solution you'd like**
When a screen or application window is shared, either from a student or tutor, the participants should be able to do annotation, just like the multi-user whiteboard, in addition to talk.

**Describe alternatives you've considered**
I have not figure out an alternative - all I can do is try to use white board, instead of screen or app sharing, but then I lose all the animation presentations.

**Additional context**
Zoom has such feature: when a student running a shared screen or app window, the tutor is able to do annotation on the students work.

**Comment by cdir** [comment] 2020-04-14 08:02
It would be very helpful to have at least the ability to point/click somewhere in someones else screen sharing to make clear about which aspect I am talking about. For example like pointing in TeamViewer.

**Comment by fsadlo** [comment] 2020-05-06 12:11
We definitely need annotation of shared screens!

**Comment by uka-support** [comment] 2020-09-01 18:01
Thinking about this from a technical perspective: You'd need at two displays for this to work or at least arrange windows in such a way that the browser stays visible all the time.

Reason: If you enable screen sharing and hide your browser, BBB will not be able to show you the annotations. It could only do that like the whiteboard on presentations - which you'll only see if the browser is still open.

Theres probably no way to have the browser overlay the whole screen - that would be a security nightmare. You need a real screen sharing application to do that.

**Comment by prlanzarin** [comment] 2021-04-05 00:00
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/5835

**Closed by prlanzarin** 2021-04-05 00:00 UTC
Labels: type: enhancement
