### ISSUE TITLE
"&" symbol displays; &amp

### ISSUE THREAD

**Issue by Balranaldpresy** [bigbluebutton/bigbluebutton#10271] opened 2020-08-16 02:37 UTC
People who sign on to bigbluebutton through Greenlight and who use the Ampersand  "&"  symbol in their name, for instance, Ken & Deb, have their name displayed as Ken "&amp"; Deb.

Instead of just displaying the "&" symbol it displays the following,   "&amp"    

I am using greenlight 2.7.1 and BBB client build 992

**Comment by hd42** [comment] 2020-11-17 10:21
Really confusing to some users.

**Comment by GhaziTriki** [comment] 2021-01-06 13:48
Duplicate of #10956

**Closed by GhaziTriki** 2021-01-06 13:48 UTC
Labels: HTML5 Client

**Comment by ErikLtz** [comment] 2021-03-11 08:30
The ampersand is a... difficult character... as & is used as separator in URL arguments. This seem to apply to both BBB room names and user names.

In my own code using the BBB API to create rooms and add users (...instead of Greenlight...) I now replace the ampersand with a simple character to avoid the &amp; entity - as a workaround.

I've tried encoding name of both room and user with ampersand in various ways like %26 but it appears it's reencoded into &amp; inside BBB but printed without sufficient entity decoding in user lists, video square and more places. Would be nice if issues are NOT just closed saying it's a duplicate of other issue with user name/room name.

**Comment by Balranaldpresy** [comment] 2021-03-11 09:30
I am glad that you have brought this issue back to the surface. It is still
an ongoing problem.
