### ISSUE TITLE
Adding Embed (iframe) option

### ISSUE THREAD

**Issue by apckish** [bigbluebutton/bigbluebutton#16122] opened 2022-12-13 04:34 UTC
Hello, everyone!

I'm a BBB user and would like contribute with a sugestion.

I'd like to sugest to add embed option to bigbluebutton so the users can embed games from the website similar to wordwall.net, so the students can play the game on their own screen. as far as I know mynaparrot company has done it and it is possible. this is a very functional option in making the classrooms and meetings more interactive. most of my friends have problem regarding playing online games in bigbluebutton.

Thanks
@ffdixon

**Comment by ffdixon** [comment] 2022-12-13 09:47
Ok apickish/tutooplus.  This is the third issue you've opened on the same request (it looks like a copy/paste job).

  https://github.com/bigbluebutton/bigbluebutton/issues/16121
  https://github.com/bigbluebutton/bigbluebutton/issues/15482

Opening multiple issues does not get you the feature any quicker, it only causes us to spend extra time to get everything back to the same issue :-(.

Closing (again) as a duplicate of   https://github.com/bigbluebutton/bigbluebutton/issues/15482.

**Closed by ffdixon** 2022-12-13 09:47 UTC
Labels: type: enhancement

**Comment by apckish** [comment] 2022-12-13 10:05
Hi Fred
Thanks so much for your reply, I didnt intend to open multiple tickets, my system hanged and I thought ticket is not submitted. So sorry for that

Sent from Yahoo Mail on Android 
 
  On Tue, Dec 13, 2022 at 1:17 PM, Fred ***@***.***> wrote:   


Ok apickish/tutooplus. This is the third issue you've opened on the same request (it looks like a copy/paste job).

#16121
#15482

Opening multiple issues does not get you the feature any quicker, it only causes us to spend extra time to get everything back to the same issue :-(.

Closing (again) as a duplicate of #15482.
