### ISSUE TITLE
BBB 2.3-Alpha 4 the keyboard shortcuts hide the HTML5 client

### ISSUE THREAD

**Issue by Kaabi** [bigbluebutton/bigbluebutton#11160] opened 2021-01-15 13:35 UTC
**Describe the bug**
When you click on the top-right menu 'Keyboard shortcuts' show a blue screen and the only way to get out of it by refreshing the page

**To Reproduce**
1. Go to Top-right Menu
2. Click on Keyboard shortcuts
3. See bluescreen and HTML5 client disappear

**Expected behavior**
Showing popup of Keyboard shortcuts

**Actual behavior**
Showing errors on console

> f04685d5396dd5527fbdd1b82ce20aca90b25a24.js?meteor_js_resource=true:69 Error: [React Intl] An `id` must be provided to format a message.
    at r (f04685d5396dd5527fbdd1b82ce20aca90b25a24.js?meteor_js_resource=true:141)
    at p (f04685d5396dd5527fbdd1b82ce20aca90b25a24.js?meteor_js_resource=true:141)
    at f04685d5396dd5527fbdd1b82ce20aca90b25a24.js?meteor_js_resource=true:353
    at Array.map (<anonymous>)
    at g (f04685d5396dd5527fbdd1b82ce20aca90b25a24.js?meteor_js_resource=true:353)
    at ha (f04685d5396dd5527fbdd1b82ce20aca90b25a24.js?meteor_js_resource=true:69)
    at Sl (f04685d5396dd5527fbdd1b82ce20aca90b25a24.js?meteor_js_resource=true:69)
    at Hl (f04685d5396dd5527fbdd1b82ce20aca90b25a24.js?meteor_js_resource=true:69)
    at Bl (f04685d5396dd5527fbdd1b82ce20aca90b25a24.js?meteor_js_resource=true:69)
    at Al (f04685d5396dd5527fbdd1b82ce20aca90b25a24.js?meteor_js_resource=true:69)

**Screenshots**
![2021-01-15 15-27-32](https://user-images.githubusercontent.com/1630141/104733287-216cb900-5747-11eb-9a70-860ca991c5b6.gif)

**BBB version (optional):**
BigBlueButton Server 2.3.0-alpha4 (1476)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 87.0.4280.141

**Comment by hiroshisuga** [comment] 2021-01-15 14:38
I believe this has been fixed by #11077 . Can you reproduce the bug on https://test23.bigbluebutton.org/ ?

**Comment by Kaabi** [comment] 2021-01-15 18:18
> I believe this has been fixed by #11077 . Would you mind double checking the BBB version?
> Can you also check if you can reproduce the bug on https://test23.bigbluebutton.org/ ?

I can't reproduce the bug on the test23.bigbluebutton.org but I noticed that on the test23 the build number is 1319 and the HTML5 client I'm currently using is 1312

**Comment by hiroshisuga** [comment] 2021-01-17 14:03
I misunderstood. #11077 has been merged to the current dev branch, which will be alpha 5. So the currently available alpha 4 still suffers this issue. You can either wait for alpha 5 or merge #11077 by yourself.

**Comment by hiroshisuga** [comment] 2021-01-17 14:04
duplicate of #11075 .

**Comment by antobinary** [comment] 2021-03-01 19:25
duplicate of #11075, which has already been closed.

**Closed by antobinary** 2021-03-01 19:25 UTC
Labels: HTML5 Client
