### ISSUE TITLE
Host can pin a audience screen to check their working status

### ISSUE THREAD

**Issue by suojian** [bigbluebutton/bigbluebutton#14933] opened 2022-05-02 21:48 UTC
It's a pure feature request, no bug related.
This feature is already existed in google meeting.

Feature description:
When a meeting starts, the host asks everyone share their screen.
The host can pin audience screen quickly, then check the screen shared by audience.

Benefits:
This feature is very useful for 1 to many class. 
The teacher is able to check every students working status;
The teacher is able to troubleshooting for particular student.
This feature adds the interactivity between teacher and students.

**Comment by prlanzarin** [comment] 2022-05-05 12:41
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/9152.

(in its essence - there are slight variations to what is written here but the core idea is the same).

**Closed by prlanzarin** 2022-05-05 12:41 UTC
Labels: type: enhancement
