### ISSUE TITLE
RTL Locales have problem

### ISSUE THREAD

**Issue by Rahimimojtaba** [bigbluebutton/bigbluebutton#11729] opened 2021-03-24 15:24 UTC
**Describe the bug**
When do change fallbackLocale and overrideLocale in settings.yml of HTML5 to some of RTL languages such as Arabic or Hebrew, on join time, the page objects still LTR. Not affected.

**To Reproduce**
1. Go to usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
2. Change fallbackLocale and overrideLocale to ar or he.
3. Then do bbb-conf --restart
4. Create a test room and join. Page still LTR.

**Expected behavior**
It should change to RTL and load language translations.

**Actual behavior**
Not change to LTR and load language translations.

BBB Version : 2.3 - Alpha 8
@antobinary 
@ffdixon

**Comment by antobinary** [comment] 2021-03-24 15:37
Thanks @Rahimimojtaba 
@ramonlsouza just fixed something similar via https://github.com/bigbluebutton/bigbluebutton/pull/11724 I will let him comment if this is a separate issue.
Thanks for reporting!

**Comment by ramonlsouza** [comment] 2021-03-24 16:37
> Thanks @Rahimimojtaba
> @ramonlsouza just fixed something similar via #11724 I will let him comment if this is a separate issue.
> Thanks for reporting!

I was not able to reproduce the issue in develop branch, before and after changes made in #11724... Maybe it was fixed by another recent PR?

**Comment by Rahimimojtaba** [comment] 2021-03-24 18:09
@antobinary Thanks for follow up.
@ramonlsouza I just did test on bigbluebutton online demo and same result. Upon joining, it's RTL and then move to LTR. Also some times in LTR mode, it show the RTL translates!
Maybe it's fixed in recent PRs.

**Comment by antobinary** [comment] 2021-03-24 18:20
I am not aware of recent PRs touching on LTR vs RTL mode.

@Rahimimojtaba could you please copy-paste the exact configs changes you made (this can help us reproduce locally and will accelerate the solution)

Is it
```
overrideLocale: ar
fallbackLocale: ar
```

**Comment by Rahimimojtaba** [comment] 2021-03-29 15:29
Fixed in Beta1

**Closed** 2021-03-29 15:29 UTC
Labels: HTML5 Client
