### ISSUE TITLE
Screenshare issues at some network conditions

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#14309] opened 2022-02-09 08:27 UTC
**Describe the bug**
The screen-sharing stops after few seconds under a 1Mbps. If the user reloads the browser page the screensharing is shown is active and cannot be stopped.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a new meeting and start screen sharing.
2. Throttle the connection.

**Expected behaviour**
Screensharing connection fail or reconnect, but it should not drop.

**Actual behaviour**
The screensharing is stopping.

**Screenshots**
After joining with another user while the screensharing is haning:
![image](https://user-images.githubusercontent.com/4991088/153155455-639990d7-6f62-44eb-85c4-e5d968bac20a.png)

**BBB version:**
BigBlueButton Server 2.4.2

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 96.0.3 (64-bit)

**Additional context**

**Comment by prlanzarin** [comment] 2022-02-09 11:13
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/14072

Please try again in v2.4.3 which is supposed to have mitigations.

**Closed by prlanzarin** 2022-02-09 11:13 UTC
Labels: module: client
