### ISSUE TITLE
GDPR: Don't show user names in polls.

### ISSUE THREAD

**Issue by laserrapt0r** [bigbluebutton/bigbluebutton#12473] opened 2021-05-31 18:11 UTC
To comply with GDPR there should be an option to do anonymous polls. 
The users don't know that it is visible for the creator of the poll what answer he selects. First of all the user can vote in a way that his answer falls back to him later and if the users know that the creator can see their answers, it is likely that the users don't answer at all or answer differently than if their name would not be shown. So it should be possible to configure bbb that the polls are anonymous.

**Comment by prlanzarin** [comment] 2021-05-31 18:12
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/9524

**Closed by prlanzarin** 2021-05-31 18:12 UTC
Labels: type: enhancement
