### ISSUE TITLE
Device microphone set as default not recognized - Failure on call (reason-WebRTC Error) [error 1004)"

### ISSUE THREAD

**Issue by Dominicjohn** [bigbluebutton/bigbluebutton#13650] opened 2021-11-06 06:12 UTC
hi all
In a Windows 10 machine with BBB 23 and 2,2 we are facing an issue with the detection of the microphone and gets the following error "Failure on call (reason-WebRTC Error) [error 1004)"

This error is happening when in windows audio settings if the default microphone is set as a built-in mic
(Please note, Google Meet in browser and zoom is working fine with the same settings without any issues)

If we change the default microphone in windows settings to Microphone Array, then this error is not happening and everything works fine.

OS - Windows 10
Browser used : Chrome - Version 95.0.4638.69 (Official Build) (64-bit)

Anybody experienced with this kind of issue please help

@ffdixon

**Comment by antobinary** [comment] 2022-01-10 20:24
Hi @Dominicjohn 
Looks like you did not receive any response here...
The recommended place for questions like this is (one of the) mailing lists, in this case likely the `setup` one - https://groups.google.com/g/bigbluebutton-setup/search?q=1004 with thousands of subscribers

Hopefully you found that resource earlier and were able to progress.
I will be closing this issue now. In future please use https://groups.google.com/g/bigbluebutton-dev for dev questions/discussions or https://groups.google.com/g/bigbluebutton-setup for setup related queries. Here we track development and confirmed bugs.

**Closed by antobinary** 2022-01-10 20:24 UTC
Labels: module: client
