### ISSUE TITLE
When watching a recording, display a link to any external shared videos in the chat

### ISSUE THREAD

**Issue by alfonsofernandezyf** [bigbluebutton/bigbluebutton#8478] opened 2020-01-10 23:04 UTC
**Is your feature request related to a problem? Please describe.**
External videos are not registered in recordings

**Describe the solution you'd like**
I would like to stamp a QR code in the presentation so viewers can scann the code and watch the video on their own. It could also be registered in the public chat with the link.

**Describe alternatives you've considered**
It could also be registered in the public chat. Or could launch the external media in an iFrame 

**Additional context**
I organize scientific meetings and many use videos as part of their lectures. This would be an easy way of keeping those videos consistent with the recording and the presentation.

**Comment by capilkey** [comment] 2020-01-10 23:14
We're looking at adding links to the videos as chat messages in the recordings. It won't have sync changes, but the videos will at least be shown.

**Comment by pedrobmarin** [comment] 2020-01-11 11:44
We started something a while ago in here https://github.com/bigbluebutton/bigbluebutton/pull/7484.
Back then the external media was only for YouTube videos so some adaptations might be needed

**Comment by pedrobmarin** [comment] 2021-04-13 00:47
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11051

**Closed by pedrobmarin** 2021-04-13 00:47 UTC
Labels: type: enhancement
