### ISSUE TITLE
Integration General Data Protection Regulation - Consent to use personal data

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#9304] opened 2020-04-28 19:33 UTC
Hello,

Would it be possible to integrate a consent button ( or something else ) for recording voice and another button  ( or something else ) for recording video during a conference. In France since May 2018, we must comply with the RGPD / General Data Protection Regulation (GDPR). These buttons ( or something else ) could appear during the echo test or once the user has logged in as a second pop-up.

This is a functionality relating to the security of personal data.

Regards,

**Comment by basisbit** [comment] 2020-04-29 12:43
Duplicate of https://github.com/bigbluebutton/greenlight/issues/1163

**Comment by basisbit** [comment] 2020-04-29 12:48
Thank your for the issue report! A "Confirm to our ToS & Data Protection information" should be implemented in the frontend (Greenlight / moodle plugin / ...), not in BBB-HTML5.
The suggested method would ask the user again every time they enable/disable audio, switch into a breakout room, or back into the main room. Also, to achieve GDPR compliance, the user has to confirm this before entering the session. Having the user agree to something when they already joined the session is too late, because they are already being recorded in that very moment.

**Comment by matiasilva** [comment] 2020-06-14 23:14
Excellent discussion here: https://github.com/bigbluebutton/greenlight/pull/1296. Closing as this belongs elsewhere.

**Closed by matiasilva** 2020-06-14 23:14 UTC
Labels: Enhancement
