### ISSUE TITLE
Problem while joining the HTML5 client

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#7113] opened 2019-03-26 21:39 UTC
![2019-03-26 18-22](https://user-images.githubusercontent.com/1778398/55035282-47ffb400-4ff6-11e9-881f-86a389954cf1.gif)
[1553635452913.log](https://github.com/bigbluebutton/bigbluebutton/files/3010477/1553635452913.log)

**Comment by antobinary** [comment] 2019-04-04 13:21
I have not encountered this before. How can we reproduce it?

**Comment by pedrobmarin** [comment] 2019-04-04 13:26
Not sure how to reproduce. Submitted as an issue for the record

**Comment by fcecagno** [comment] 2019-04-22 14:19
Just reproduced this issue. This is the client log that worked:

```
Apr 22 10:56:28 *** systemd_start.sh[32661]: #033[32minfo#033[39m: CLIENT LOG: {"language":"pt-BR","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0","screenSize":{"width":1920,"height":1080},"windowSize":{"width":1920,"height":955},"bbbVersion":"2.2-dev","location":"https://***/html5client/join?sessionToken=5nec396iper5vyym"}  {"meta":{"fullInfo":{"sessionToken":"5nec396iper5vyym","meetingId":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","requesterUserId":"w_6dbodsqhooa2","fullname":"User 571336","confname":"random-1337782","externUserID":"w_6dbodsqhooa2"},"validUser":"notFound"}}
Apr 22 10:56:28 *** systemd_start.sh[32661]: #033[32minfo#033[39m: CLIENT LOG: User successfully went through main.joinRouteHandler with [{"returncode":"SUCCESS","fullname":"User 571336","confname":"random-1337782","meetingID":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","externMeetingID":"random-1337782","externUserID":"w_6dbodsqhooa2","internalUserID":"w_6dbodsqhooa2","authToken":"tsq6xq3gaq28","role":"MODERATOR","guest":false,"guestStatus":"ALLOW","conference":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","room":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","voicebridge":"77104","dialnumber":"613-555-1234","webvoiceconf":"77104","mode":"LIVE","record":"false","isBreakout":false,"logoutTimer":0,"allowStartStopRecording":true,"welcome":"***","customLogoURL":"","customCopyright":"","muteOnStart":false,"logoutUrl":"https://***","defaultLayout":"NOLAYOUT","avatarURL":"https://***/client/avatar.png","customdata":[],"metadata":[]}].  {"meta":{"fullInfo":{"sessionToken":"5nec396iper5vyym","meetingId":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","requesterUserId":"w_6dbodsqhooa2","fullname":"User 571336","confname":"random-1337782","externUserID":"w_6dbodsqhooa2"},"validUser":"notFound"}}
Apr 22 10:56:28 *** systemd_start.sh[32661]: #033[32minfo#033[39m: CLIENT LOG: re-send validateAuthToken for delayed authentication  {"meta":{"fullInfo":{"sessionToken":"5nec396iper5vyym","meetingId":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","requesterUserId":"w_6dbodsqhooa2","fullname":"User 571336","confname":"random-1337782","externUserID":"w_6dbodsqhooa2"},"validUser":"notFound"}}
Apr 22 10:56:28 *** systemd_start.sh[32661]: #033[32minfo#033[39m: CLIENT LOG: re-send validateAuthToken for delayed authentication  {"meta":{"fullInfo":{"sessionToken":"5nec396iper5vyym","meetingId":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","requesterUserId":"w_6dbodsqhooa2","fullname":"User 571336","confname":"random-1337782","externUserID":"w_6dbodsqhooa2"},"validUser":"valid"}}
Apr 22 10:56:28 *** systemd_start.sh[32661]: #033[32minfo#033[39m: CLIENT LOG: re-send validateAuthToken for delayed authentication  {"meta":{"fullInfo":{"sessionToken":"5nec396iper5vyym","meetingId":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","requesterUserId":"w_6dbodsqhooa2","fullname":"User 571336","confname":"random-1337782","externUserID":"w_6dbodsqhooa2"},"validUser":"valid"}}
Apr 22 10:56:28 *** systemd_start.sh[32661]: #033[32minfo#033[39m: CLIENT LOG: re-send validateAuthToken for delayed authentication  {"meta":{"fullInfo":{"sessionToken":"5nec396iper5vyym","meetingId":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","requesterUserId":"w_6dbodsqhooa2","fullname":"User 571336","confname":"random-1337782","externUserID":"w_6dbodsqhooa2"},"validUser":"valid"}}
Apr 22 10:56:29 *** systemd_start.sh[32661]: #033[32minfo#033[39m: CLIENT LOG: Client loaded successfully  {"meta":{"fullInfo":{"sessionToken":"5nec396iper5vyym","meetingId":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","requesterUserId":"w_6dbodsqhooa2","fullname":"User 571336","confname":"random-1337782","externUserID":"w_6dbodsqhooa2"},"validUser":"valid"}}
Apr 22 10:56:29 *** systemd_start.sh[32661]: #033[32minfo#033[39m: CLIENT LOG: Subscriptions are ready  {"meta":{"fullInfo":{"sessionToken":"5nec396iper5vyym","meetingId":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","requesterUserId":"w_6dbodsqhooa2","fullname":"User 571336","confname":"random-1337782","externUserID":"w_6dbodsqhooa2"},"validUser":"valid"}}
```

This is the client log of a client that couldn't join (held on the Waiting for approval to join)
```
Apr 22 11:00:41 *** systemd_start.sh[32661]: #033[32minfo#033[39m: CLIENT LOG: {"language":"en-US","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36","screenSize":{"width":1280,"height":720},"windowSize":{"width":1280,"height":720},"bbbVersion":"2.2-dev","location":"https://***/html5client/join?sessionToken=005ljcqeadd9hsmd"}  {"meta":{"fullInfo":{"sessionToken":"005ljcqeadd9hsmd","meetingId":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","requesterUserId":"w_vvcl3kn2hdqg","fullname":"Streaming","confname":"random-1337782","externUserID":"w_vvcl3kn2hdqg"},"validUser":"notFound"}}
Apr 22 11:00:41 *** systemd_start.sh[32661]: #033[32minfo#033[39m: CLIENT LOG: User successfully went through main.joinRouteHandler with [{"returncode":"SUCCESS","fullname":"Streaming","confname":"random-1337782","meetingID":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","externMeetingID":"random-1337782","externUserID":"w_vvcl3kn2hdqg","internalUserID":"w_vvcl3kn2hdqg","authToken":"7xlglvggnzye","role":"VIEWER","guest":false,"guestStatus":"ALLOW","conference":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","room":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","voicebridge":"77104","dialnumber":"613-555-1234","webvoiceconf":"77104","mode":"LIVE","record":"false","isBreakout":false,"logoutTimer":0,"allowStartStopRecording":true,"welcome":"***","customLogoURL":"","customCopyright":"","muteOnStart":false,"logoutUrl":"https://***","defaultLayout":"NOLAYOUT","avatarURL":"https://***/client/avatar.png","customdata":[{"html5recordingbot":"true"},{"html5autoswaplayout":"false"},{"html5hidepresentation":"false"}],"metadata":[]}].  {"meta":{"fullInfo":{"sessionToken":"005ljcqeadd9hsmd","meetingId":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","requesterUserId":"w_vvcl3kn2hdqg","fullname":"Streaming","confname":"random-1337782","externUserID":"w_vvcl3kn2hdqg"},"validUser":"notFound"}}
Apr 22 11:00:41 *** systemd_start.sh[32661]: #033[32minfo#033[39m: CLIENT LOG: re-send validateAuthToken for delayed authentication  {"meta":{"fullInfo":{"sessionToken":"005ljcqeadd9hsmd","meetingId":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","requesterUserId":"w_vvcl3kn2hdqg","fullname":"Streaming","confname":"random-1337782","externUserID":"w_vvcl3kn2hdqg"},"validUser":"notFound"}}
Apr 22 11:00:41 *** systemd_start.sh[32661]: #033[32minfo#033[39m: CLIENT LOG: re-send validateAuthToken for delayed authentication  {"meta":{"fullInfo":{"sessionToken":"005ljcqeadd9hsmd","meetingId":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","requesterUserId":"w_vvcl3kn2hdqg","fullname":"Streaming","confname":"random-1337782","externUserID":"w_vvcl3kn2hdqg"},"validUser":"notFound"}}
Apr 22 11:00:42 *** systemd_start.sh[32661]: #033[32minfo#033[39m: CLIENT LOG: Client loaded successfully  {"meta":{"fullInfo":{"sessionToken":"005ljcqeadd9hsmd","meetingId":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","requesterUserId":"w_vvcl3kn2hdqg","fullname":"Streaming","confname":"random-1337782","externUserID":"w_vvcl3kn2hdqg"},"validUser":"valid"}}
Apr 22 11:00:42 *** systemd_start.sh[32661]: #033[32minfo#033[39m: CLIENT LOG: Subscriptions are ready  {"meta":{"fullInfo":{"sessionToken":"005ljcqeadd9hsmd","meetingId":"02263b2e5ae646240f3994f0ae0d4fab9854b229-1555941380342","requesterUserId":"w_vvcl3kn2hdqg","fullname":"Streaming","confname":"random-1337782","externUserID":"w_vvcl3kn2hdqg"},"validUser":"valid"}}
```

There's no steps to reproduce it, it looks like a race condition.

**Comment by antobinary** [comment] 2019-05-10 21:10
I hit this on two occasions and in both cases the cause was a mismatch between the bbb-* core packages and bigbluebutton-html5/* code - not pulled from master. In particular when we introduce a new `Meeting` prop...
The immediate issue is that we do not add a meeting to the collection if the structure of that meeting is not as expected. Then the client is trying to auth in a situation when there is no Meeting on record.
I am closing this now but do not hesitate to re-open if it reoccurs differently from described

**Closed by antobinary** 2019-05-10 21:10 UTC
Labels: Bug, HTML5 Client
