### ISSUE TITLE
Chat avatar offline after re-entering room

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#11081] opened 2020-12-27 06:55 UTC
**Describe the bug**
Since 2.3a3, user avatar image appears in the chat window. Great. But after exiting and re-entering the room, the past post becomes offline and squeezed at the upper part of the chat window. The avatar image reverts to the boring default avatar.

**To Reproduce**
1. do chat (message appears together with the avatar image - love it!)
2. get out of the room without closing the meeting
3. re-enter the room
4. your message is on the upper part of the window and the avatar image does not show up. Your messages are judged to be offline, although you are actually online. New messages behave as expected, showing the avatar image.

**Expected behavior**
BBB recognizes the user is back online (coming back to the meeting), and puts his message to the normal position together with the avatar image.

**Actual behavior**
Your old message becomes offline. Avatar image does not show up. The position of the message is weird.

**Screenshots**

![chatavatar](https://user-images.githubusercontent.com/45039819/103165655-f7b62580-485d-11eb-92d4-586a32917634.gif)

**BBB version (optional):**
BBB 2.3a3. The problem is reproducible also in test23 server.

**Another thought**
I am not quite sure this is an unexpected behaviour, or an intented one.

**Comment by hiroshisuga** [comment] 2020-12-28 11:25
The problem seems to be the userId differently assigned to the returning user. Not so many things to be improved, I suppose.

**Comment by pedrobmarin** [comment] 2020-12-28 11:44
Maybe related with this #10368

**Comment by hiroshisuga** [comment] 2020-12-28 23:58
@pedrobmarin , very likely. I personally prefer the user collection to be kept even though the traffic increases in a large meeting. I suppose you can discuss with the author of #10368 ...

**Comment by daminebenq** [comment] 2021-03-12 20:08
still reproducible.

**Comment by tdjac0bs** [comment] 2021-03-18 13:02
I believe that the motivation behind #10368 was to speed up the initial load of the meeting ( having a smaller collection to query in mongo and to sync ), as a meeting running for a long time can potentially have many disconnected users .

As a side effect of this PR the `group-chat-msg` received new fields:
- color ( it's the user color );
- sender.name ;

In my opinion this was a mistake, because for every message we're transferring the user name and color.

**Quick & dirty solution:**
A quick solution for this issue could be adding the avatar to this collection, however it's going to make it even heavier.

**Proposed solution:**

1 - New collection
- create a `user-persistent-data` collection ( that will have both online/offline users, but lesser fields ) ;
- don't synchronize this collection on client initialization ;

2 - Context
All user information will be read from `UserContext`, that will be filled as follows:
- On client load we insert all online users ( from `users` collection ) into this context;
- After client initial load ( before the chat history sync ) we subscribe to `user-persistent-data`, injecting the offline users too;

3 - Chat messages collection
- Remove the color and sender.name from this collection ( keeping only the userId );

This way we will not delay the initial client load, will reduce network traffic ( reduced chat-msg payload ) and display disconnected users information correctly.

**Comment by antobinary** [comment] 2021-03-19 14:14
^ I support the Proposed solution (but not the quick & dirty one :smile: )

**Comment by pedrobmarin** [comment] 2021-03-19 14:23
Already mentioned someplace else, but to keep the record, akka-apps RegisteredUser model is a good guideline for the persistent data we might want to keep.

**Comment by Tainan404** [comment] 2021-03-19 14:35
Hi @pedrobmarin, thank you.

I believe that only needed informantions are:

```
userId: string
meetingId: string
name: string
avatar: string
color: string
online: boolean
```

**Comment by Tainan404** [comment] 2021-03-19 14:46
I'm going to proceed with the following changes:

=> Create collection  `users-persistent-data`  with fields  `userId, meetingId, name, avatar, color, online`;
=> Subscribe to this collection (`users-persistent-data`) only after all subscribes are ok ( `subscriptionReady = true`  );
=> Change UsersContext adapter to read from the two collections - merging the records ( `users` e `users-persistent-data` ) ;
=> Refactor attribute assignment in `time-window-chat-item` to read `color` and `name` from user context;


After this we can remove `sender.name` and `color` from the message `GroupChatMessageBroadcastEvtMsg` in Akka

**Comment by antobinary** [comment] 2021-03-19 14:48
For referrence this is the current RegisteredUser model:

```
userId: String,
extId: String, 
name: String, 
roles: String,
token: String, 
avatar: String, 
guest: Boolean, 
authenticated: Boolean,
guestStatus: String, 
loggedOut: Boolean
```
We have this info in the `users` collection, but once a user is removed, it can't be obtained through there.

I can see how `guestStatus` could be useful to know after a user is removed, but as of now chat does not use it iirc.

**Comment by tdjac0bs** [comment] 2021-03-19 15:26
I would be interested in how `guestStatus` could be useful after user removal - can you elaborate this point?

**Comment by pedrobmarin** [comment] 2021-03-19 15:31
The ones I find useful are:
```
userId: String,
extId: String, 
name: String, 
roles: String, (isn't it role?)
token: String, 
avatar: String, 
guest: Boolean, 
```

**Comment by tdjac0bs** [comment] 2021-03-19 15:41
hello @pedrobmarin 

I would add `color` and `meetingId` to this list _( meetingId can be omitted when transferring to client using a projection )_

I don't see any benefit of having the `token` of a disconnected user in meteor, can you elaborate this one?

**Comment by tdjac0bs** [comment] 2021-03-19 16:26
So the final list is: `userId, extId, meetingId, name, role, token, avatar, guest, color, online`

**Comment by antobinary** [comment] 2021-03-19 17:14
>So the final list is: userId, extId, meetingId, name, role, [token?], avatar, guest, color, online

Does storing all of this info in `users-persistent-data` mean that you would no longer have some of these fielda in `users` collection?

**Comment by pedrobmarin** [comment] 2021-03-19 18:28
I don't this that would be the best approach, @antobinary , because it would probably reintroduce the problem that removing offline users from the user collection tried to solve. I didn't went through all caveats but maybe this persistent users stash should be updated when the user leaves the user collection with his/her last state.

**Comment by Tainan404** [comment] 2021-03-22 20:55
Hi @antobinary. The information will be stored in both collections.
Please see my partial work here: https://github.com/bigbluebutton/bigbluebutton/compare/develop...Tainan404:issue-11081
(will do more tests tomorrow before sending PR)

**Closed** 2021-03-26 12:56 UTC
Labels: HTML5 Client
