### ISSUE TITLE
Audio button placement (too easily confused with mute/unmute)

### ISSUE THREAD

**Issue by axelsimon** [bigbluebutton/bigbluebutton#10960] opened 2020-12-03 20:01 UTC
**Describe the bug**
The button to leave (and rejoin) audio is between the microphone toggle button and the video toggle button, because of that it is easy to click it by mistake, especially when trying to mute and unmute oneself.
Furthermore, when one is concentrating on the conversation, two similar looking buttons, with a similar theme ("audio things") and with the *same* colour scheme are too easy to confuse.

When that happens, it takes a while to reconnect to audio and one can lose a lot of the conversation (BBB asks for microphone, it's allowed, wait for echo test, do echo test, finally rejoin audio).

**To Reproduce**
N/A

**Expected behaviour**
I don't want to risk confusing the "mute" button with the "leave audio" button and clicking the wrong one.

**Actual behaviour**
I sometimes click the "leave audio" button when i simply wanted to unmute.

**BBB version (optional):**
Don't have it right now (but can obtain if necessary)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 32
 - Browser: Firefox
 - Version: 83.0

**Comment by basisbit** [comment] 2020-12-03 22:59
duplicate of #7959, #10011 and bunch of other issues related to the same problem.

**Closed by basisbit** 2020-12-03 22:59 UTC
Labels: HTML5 Client
