### ISSUE TITLE
[2.7] Phantom user bug

### ISSUE THREAD

**Issue by Arthurk12** [bigbluebutton/bigbluebutton#20251] opened 2024-05-14 14:13 UTC
**Describe the bug**
After a user is promoted to moderator, previously disconnected users who have sent messages in the chat reappear in the user list.

**To Reproduce**
1. Join meeting with 3 sessions: one moderator(m1) and two viewers(v1 and v2)(in anonymous tabs);
2. In v1 session, send a message in the public chat and leave by closing the browser tab;
3. Wait for user v1 to be removed from the user list (approximately 10 seconds);
4. In m1 session, promote v2 to moderator;
5. See error: in v2 session, the user v1 shows up in the user list again;

**Expected behavior**
After the user list updates, only online users should be displayed.

**Actual behavior**
Offline users who have previously sent messages in the chat reappear in the user list after a moderator promotion.

**Screenshots**
![Recording 2024-05-14 at 10 55 42](https://github.com/bigbluebutton/bigbluebutton/assets/32987232/8a727b57-9167-4996-8b86-e6353da77216)

**BBB version:**
dev27.bigbluebutton.org

**Comment by Ithanil** [comment] 2024-05-14 14:16
Related/duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/19564

**Comment by antobinary** [comment] 2024-09-13 12:50
Closed via #20253

**Closed by antobinary** 2024-09-13 12:50 UTC
Labels: component: chat, module: client, type: bug
