### ISSUE TITLE
NotReadableError: Failed to allocate videosource Elgato Camlink and OBS VirtualCam

### ISSUE THREAD

**Issue by patrick-dmxc** [bigbluebutton/bigbluebutton#9972] opened 2020-07-01 22:37 UTC
**Describe the bug**
NotReadableError: Failed to allocate videosource
I use the Elgate Camlink 4k and OBS with the Virtual Cam-Plugin.
If the Camlink is used by OBS and i want to start the Camera in a Konferece, i get the Errormessage.
if the Camlink is not used of any other Program im able to select the Camlink or the Virtual Cam.
I think there is an issue, if the first or any Cam is used by a other Program, the UI is not able to reach any other Cam

 - OS: Windows 10
 - Browser: Firefox  and Chrome
 - Version nn

**Comment by basisbit** [comment] 2020-07-01 23:16
Duplicate of #8995

**Closed by basisbit** 2020-07-01 23:16 UTC
Labels: HTML5 Client

**Comment by basisbit** [comment] 2020-07-01 23:20
Also, related to #9943
