### ISSUE TITLE
Add LaTeX support for Math symbols

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5730] opened 2018-06-21 12:02 UTC
When doing Math, the industry standard for description of formulas is LaTeX.   

Give the presenter the ability to enter a LaTeX formula into the client and have it render the equation in the presentation area.

**Comment by nekapoor** [comment] 2018-09-02 02:36
@ffdixon once implemented, would this also be available during chat (ie, we could type latex commands into the chatbox and have them render)? Or would that be another ticket you'd want to open?

**Comment by ffdixon** [comment] 2018-09-02 04:00
It could -- we would make a server-side call to render the latex as an image.  We need to first add support for displaying an image on the whiteboard and then in the chat.  

We can leave them together in this ticket for now as getting the images on the whiteboard would be the first step.

**Comment by nekapoor** [comment] 2018-09-04 02:15
Great. One thing I want to know in case you were going to head down the Mathjax path. You might want to also consider [Katex](https://github.com/Khan/KaTeX), a rendering library built by the Khan Academy. Just wanted to leave this here as you start to explore the most efficient way to implement this.

**Comment by vitovt** [comment] 2020-04-18 22:09
I need formulas feature too. LaTeX is very useful format.

**Comment by Geremia** [comment] 2020-05-15 23:10
@nekapoor Just to clarify, Katex doesn't use MathJax. It's a MathJax alternative.

**Comment by Geremia** [comment] 2020-05-15 23:13
This seems to be a duplicate of #2485.

**Comment by prlanzarin** [comment] 2021-04-04 13:59
Merging into #2485.

**Closed by prlanzarin** 2021-04-04 13:59 UTC
