### ISSUE TITLE
previews of recordings shows standard slides

### ISSUE THREAD

**Issue by ReimarBauer** [bigbluebutton/bigbluebutton#18082] opened 2023-06-03 09:56 UTC
**Describe the bug**
All our recordings show the same default.pdf slides preview instead of the recorded slides

**To Reproduce**
After recording look on the overview
![previews_identical](https://github.com/bigbluebutton/bigbluebutton/assets/278728/bfcaa314-6d3f-4396-84bc-2dda63d4344e)

**Expected behavior**
see the slides used in the presentation

**Actual behavior**
it shows the server configured default slides

**Screenshots**
see above.

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: firefox
 - Version: 113.0.2 

**Additional context**
BBB Server version 2.6.9

**Comment by hiroshisuga** [comment] 2023-06-04 01:20
Hi @ReimarBauer ,
It's working as expected here. How does your metadata.xml look like under the /var/bigbluebutton/published/presentation/(meetingId) directory? 
You seem to use a customised version of default presentation. How did you do it (where it is placed, and in what name)?

**Comment by ReimarBauer** [comment] 2023-06-04 13:00
@hiroshisuga I added into /etc/bigbluebutton/bbb-web.properties

`beans.presentationService.defaultUploadedPresentation=${bigbluebutton.web.serverURL}/ourdefaults/standard.pdf`


`ourdefaults` is defined as additional location in nginx

**Comment by hiroshisuga** [comment] 2023-06-05 00:42
Try renaming standard.pdf to default.pdf. 
The script sees the filename.
https://github.com/bigbluebutton/bigbluebutton/blob/7b5b29aaeabbc44a31c84a2b8a121c72fb3e4949/record-and-playback/core/lib/recordandplayback/generators/presentation.rb#L129

**Comment by ReimarBauer** [comment] 2023-06-05 15:28
@hiroshisuga that's it. 

but this is not so practical, if you don't want to overwrite the default pdf again and again on an update. Not anyone will add a different location.

**Comment by hiroshisuga** [comment] 2023-06-06 00:50
Are you sure that it will be overwritten by upgrading BBB? 
It seems to me that your default presentation pdf is located somewhere that would not be overwritten by an upgrading. 
Please note that the script only sees the name of the file, not the path to the file.

**Comment by ReimarBauer** [comment] 2023-06-06 06:19
mine is not overwritten, because of the location change.
In the past I used the same name and location and it was overwritten on some updates.

with the default.pdf file name it works

![changed_behaviour](https://github.com/bigbluebutton/bigbluebutton/assets/278728/662f3ab0-698a-4277-9960-5e6fba141aa2)

**Comment by ReimarBauer** [comment] 2023-06-06 06:22
I will later check what happens when a default slide was added by different name by greenlight.

**Comment by hiroshisuga** [comment] 2023-06-06 08:29
Your are right. There seem some problems in the doc.bigbluebutton.org.

If /var/www/bigbluebutton-default/assets/default.pdf is overwritten every time when the user upgrades the server, what's written there is sort of ridiculous.
`When a new meeting starts, BigBlueButton displays a default presentation. The file for the default presentation is located in /var/www/bigbluebutton-default/assets/default.pdf. You can replace the contents of this file with your presentation.`
Unfortunately I have not got any change to check the behaviour... If install-bbb.sh script can detect if the contents of defaut.pdf is actually replaced or not (and decide not to replace it back to the original default.pdf), the user would be more comfortable.

Another problem is in the following sentence:
`Alternatively, you can change the global default by adding an overwriting rule in /etc/bigbluebutton/bbb-web.properties specifying the URL for beans.presentationService.defaultUploadedPresentation`
We may want to add "Please keep the file name "default.pdf" so that thumbnails would not be generated from this file".

**Comment by hiroshisuga** [comment] 2023-06-07 03:26
I've found another problem. If you upload a new presentation file in the name "default.pdf", thumbnails won't be generated.

**Comment by GuiLeme** [comment] 2023-06-14 13:55
Hey guys, so, I tested here locally and for both 2.7-release and 2.6-release it works correctly, with the same scenario you described, so I am going to specify what I've done and you tell me if there are other steps in order to reproduce the issue:
 - Firstly, I added the line `beans.presentationService.defaultUploadedPresentation=${bigbluebutton.web.serverURL}/ourdefaults/standard.pdf` to the `/etc/bigbluebutton/bbb-web.properties` file;
 - Then I added a random PDF inside `/var/www/bigbluebutton-default/assets/ourdefaults` with the name `standard.pdf` (Note that since `ourdefaults` is under `/var/www/bigbluebutton-default/assets`, it will be served statically by the nginx with the same URL specified previously);
 - Bearing that in mind, I always checked the `metadata.xml` generated under `/var/bigbluebutton/published/presentation/<meetingId>` with the following scenarios:
   * Create a meeting with no pre-uploaded presentation (`metadata.xml` showed me the correct links pointing to `standard.pdf`);
   * Create a meeting with a pre-uploaded slides (again, the metadata got the correct links of the pre-uploaded presentation);
 - Also, before inserting `standard.pdf` under `ourdefaults` I made the same 2 tests with the ordinary `default.pdf`, and the `matadata.xml` also came out right.

So with that being said, I would also like to ask you if that greenlight is version 2 or version 3 (To discover that just do a `docker ps | grep greenlight`).

**Comment by antobinary** [comment] 2023-08-29 20:40
Closing. Please reopen if still hitting issues despite @GuiLeme 's thorough post above

**Closed by antobinary** 2023-08-29 20:40 UTC
Labels: module: recording, status: verify
