### ISSUE TITLE
Support for Ubuntu 20.04? 

### ISSUE THREAD

**Issue by D33M0N** [bigbluebutton/bigbluebutton#12339] opened 2021-05-10 14:09 UTC
**Is your feature request related to a problem? Please describe.**

Since the Ubuntu 16.04 LTS life support ended in April 2021, maybe we get support and compatibility with newer Ubuntu server release? I don't want to run the BBB on version of Linux that doesn't even get security updates anymore.

**Describe the solution you'd like**

Push BBB minimum requirements (or at least support) to up to date (latest LTS) Ubuntu version?

**Comment by andreas-bulling** [comment] 2021-05-10 14:13
there is beta support for Ubuntu 18.04 LTS - works really well for me so far...
https://docs.bigbluebutton.org/dev/dev23.html

**Comment by antobinary** [comment] 2021-05-10 18:01
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/10353

Kurento is not currently supported on 20.04.
BigBlueButton 2.3.x runs on Ubuntu 18.04 (bionic) Long Term Support. Please use BBB 2.3.x (on Ubuntu 18.04)

**Closed by antobinary** 2021-05-10 18:01 UTC
Labels: type: enhancement

**Comment by D33M0N** [comment] 2021-05-11 00:17
I have a working instance/server of BBB on Ubuntu 16.04 LTS.
BBB 2.3 is not offered as an upgrade there yet, via apt update && apt upgrade.
How do you exactly suggest one goes from there? do-release-upgrade to Ubuntu below or wait for the bbb 2.3 upgrade first?

> BigBlueButton 2.3.x runs on Ubuntu 18.04 (bionic) Long Term Support. Please use BBB 2.3.x (on Ubuntu 18.04)

Not going to install it from scratch, when you were suggesting something such...

**Comment by ffdixon** [comment] 2021-05-11 01:20
We recommend you start with a clean Ubuntu 18.04 64-bit server and let [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) do the heavy lifting for you.

The packages for 2.3 reduced (we removed a lot of legacy code related to Flash), and the scripts do not expect to have 2.2 server installed.

If you want to try upgrading from 2.2 in place, you could first completely remove the BigBlueButton packages, then upgrade the server to 18.04, then install 2.3.  However, we've not tried this ourselves.

**Comment by mohamedamara1** [comment] 2022-02-10 21:00
> 

Hello, do you still recommend using  Ubuntu 18.04 64-bit server now? If not , which ubuntu server version should I set up?

**Comment by ffdixon** [comment] 2022-02-10 23:33
See
  
  https://docs.bigbluebutton.org/2.4/install.html#minimum-server-requirements

**Comment by mohamedamara1** [comment] 2022-02-11 17:34
> See
> 
> https://docs.bigbluebutton.org/2.4/install.html#minimum-server-requirements

Thanks, I already followed that page.

**Comment by antobinary** [comment] 2022-02-11 20:09
Ubuntu 18.04 has support for 14+ months, see https://ubuntu.com/about/release-cycle

https://github.com/bigbluebutton/bigbluebutton/issues/14336 We plan to use Ubuntu 20:04 on the release after BBB 2.5. This should allow for months of transition time prior to the EOL of Ubuntu 18.04

**Comment by D33M0N** [comment] 2022-02-11 21:16
> Ubuntu 18.04 has support for 14+ months, see https://ubuntu.com/about/release-cycle
> 
> #14336 We plan to use Ubuntu 20:04 on the release after BBB 2.5. This should allow for months of transition time prior to the EOL of Ubuntu 18.04

No, it doesn't. ESM isn't exactly "support". It's paid service.

**Comment by prlanzarin** [comment] 2022-02-11 21:23
> No, it doesn't. ESM isn't exactly "support". It's paid service for anything else than very personal private use (where you can get 3 free ESM keys), thus unusable sadly. Are many of BBB users actually private individuals using it for I don't know... instead of Skype or something to talk to their family? Do you really expect every actual use case for BBB to pay Canonical for the ESM or be left without security patches?


Maybe this link is clearer: https://wiki.ubuntu.com/Releases

Bionic Beaver entries. End of Standard support: April 2023.
![image](https://user-images.githubusercontent.com/4529051/153671884-c57db019-5adb-4b5c-b830-e34c6444e6d8.png)


Don't know where the April/22 date comes from... If you have references, please link them.

**Comment by etopian** [comment] 2022-02-20 20:27
How about going to 22.04 as it's the same amount of effort and supports a secure BBB until 2027 rather than 2025. It will be released on April 21st.

**Comment by ffdixon** [comment] 2022-02-21 11:48
When we get to 20.04, we won't be far away from getting to 22.04.  Also, this issue is closed.  See further discussion: https://github.com/bigbluebutton/bigbluebutton/issues/14336
