### ISSUE TITLE
Enhancement- API -  way to insert text and HTML into chat window given you know the meeting-id.

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1119] opened 2015-08-12 07:17 UTC
Originally reported on Google Code with ID 364

```
When a conference is going... would like a simple way to call the API to 

insert-message given meeting-id.

the message can by plain text or HTML...

the message appears in everyones chat window..


Uses...  

1) Instructor can insert questions to students and see who responds first. 
Could be done from a simple web app with preconfigured questions.

2) I'd like to run simple network monitoring script, and insert server 
stats in window during conference. CPU utilization, DATA up/down etc..

3) If you can insert HTML in windows lots of other customizations.
```

Reported by `207TECH` on 2010-02-18 14:15:01

**Comment by ffdixon** [comment] 2018-06-16 21:04
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/1660

**Closed by ffdixon** 2018-06-16 21:04 UTC
Labels: API, Enhancement, Low Priority
