### ISSUE TITLE
"isListeningOnly" always true after disconnecting to audio in "getMeetings" and "getMeetingInfo" API calls

### ISSUE THREAD

**Issue by hipoloco** [bigbluebutton/bigbluebutton#8980] opened 2020-04-03 17:33 UTC
First of all, I apologize for my english (it's not very good).

When a participant connects to the audio in a conference, the status of the "isListeningOnly" parameter changes from false to true, but it remains true after it is disconnected (tested on BBB 2.2.3)

![bbb_01](https://user-images.githubusercontent.com/8184347/78388473-77f17800-75b7-11ea-9fd6-8b934d2fa6b6.jpg)
![bbb_02](https://user-images.githubusercontent.com/8184347/78388616-b1c27e80-75b7-11ea-975f-fbb6166cbbbc.jpg)

**Comment by matiasilva** [comment] 2020-06-14 22:34
Thanks for pointing this out. I have been able to reproduce this issue on the test install. This might be a bug. Asking for a second opinion from @ffdixon .

**Comment by prlanzarin** [comment] 2021-04-05 00:31
Seems to be fixed as of 2.3-beta.2.

**Closed by prlanzarin** 2021-04-05 00:31 UTC
