### ISSUE TITLE
2.3-RC1: Layout bug with webcam, waiting room

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#12143] opened 2021-04-24 08:16 UTC
In some weird occasions there is a layout bug when waiting room is opened and webcams are shared. Details below.

**Describe the bug**
Presentation and webcams not layouting properly.

I've already tried to report this in https://github.com/bigbluebutton/bigbluebutton/issues/11610#issuecomment-810628482, but couldn't provide proper steps to reproduce which I hope I am able to do now. As #11610 now has been fixed and the problem still exists I open another issue.

**To Reproduce**
1. Start new session
2. Share your webcam
3. Let other user join into the waiting room
4. Open waiting room (layout sometimes crashes the first time at this point, but in a different way)
5. Accept user to join
6. Waiting room window closes and layout breaks, see screenshot.

Additional information: As this is a layout problem, I try to provide some more information:
- Presentation is in 16:9 format
- Firefox inspection tools tell, body tag has **1650x867** pixels, can reproduce it with this resolution on chrome consistently as well. **This is the important point to reproduce!** For sure there are also other resolutions which break the layout, but at least I found one where it consistently happens for me.
- Moving Webcams or, for example, opening and closing public chat resets layout properly

**Expected behavior**
Layout doesn't crash

**Actual behavior**
Layout is weird, see screenshot

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65113153/115952106-9426c680-a4e4-11eb-98d4-9a113828bc1f.png)

**BBB version (optional):**
2.3-rc1, this has been there for a long time now though

**Desktop (please complete the following information):**
- Happened on FF 88 and current Chrome with **mentioned resolution**!

**Additional information**
- I've seen this bug as well with 2 webcams being shared.
- As the line to resize the webcam/presentation space is directly next to the presentation space when the bug happened, the webcam space is calculated as too big I think.
- After restoring the layout manually the bug cannot be reproduced when trying to join with next client to the waiting room. Only appears when leaving session (even when it's still running) and restarting client by joining again.

**Comment by berott** [comment] 2021-04-25 11:10
I can reproduce this Bug with Chrome and Firefox on an MacBook Air (M1) with a Body-Size of 1680x946 (Standard!).
To reproduce:

1. Start new session
2. Share your webcam
3. open "Shared Notes"
4. close "Shared Notes" (so there are no shared notes and no chat visible)

If I change the width of the user list, the layout is set back to the correct position.

I think, the width of the following **div** is wrong - it has a width of 1471px (limited with a max-width of 1086px), in the correct layout it has a width between 290px - 300px:
`<div class="overlay--nP1TK overlayToLeft--1n9e9S react-draggable" style="position: relative; user-select: auto; touch-action: none; margin-left: 0px; margin-right: 0px; z-index: 2; transform: translate(0px, 0px); width: 1471px; height: 161.8px; min-width: 294.2px; min-height: 161.8px; box-sizing: border-box; max-width: 1086px;"><div class="videoCanvas--Z1giNVE"><div class="videoList--1OC49P" style="grid-template-rows: repeat(1, 1fr); width: 218px; height: 163px; grid-template-columns: repeat(1, 1fr);"><div class="videoListItem--ZP5lQT"><div data-test="webcamItem" class="content--Z1CkMQ"><div class="videoContainer--rssHk"><video data-test="videoContainer" class="media--qsqlj cursorGrab--Z2fB4yK" autoplay="" playsinline=""></video><div class="wrapper--Z17x8k2 dark--Z1Y80Wt top--1p9eDv"><button aria-label="User 9793554 zum Vollbild machen" aria-disabled="false" class="button--Z2dosza sm--Q7ujg default--Z19H5du button--Z1ops0C fullScreenButton--Z1bf0vj" data-test="presentationFullscreenButton" position="bottom" id="tippy-132"><i class="icon--2q1XXw icon-bbb-fullscreen"></i><span class="label--Z12LMR3 hideLabel--2vEtaU">User 9793554 zum Vollbild machen</span></button></div></div><div class="info--1NTSXo"><div class="dropdown--Z10dYoc dropdown--ZEHEeO" tabindex="-1"><span keepopen="null" class="dropdownTrigger--Z1Fp5dg" aria-expanded="false">User 9793554</span><div data-test="dropdownContent" class="content--ZmitSl top-left--Z1G8Sn0 dropdownContent--GQxps" aria-expanded="false" keepopen="null"><div class="scrollable--4fyj"><ul class="verticalList--Ghtxj dropdownList--Z1XW4UX" role="menu"><li class="title--2cMK7V hiddenDesktop--w3Fzr" aria-hidden="true">User 9793554</li><li class="separator--Z1vmd5H hiddenDesktop--w3Fzr"></li><li tabindex="0" aria-labelledby="dropdown-item-label-134" aria-describedby="dropdown-item-desc-135" class="item--yl1AH" role="menuitem"><span class="itemLabel--Z12glHA">Spiegeln</span><span id="dropdown-item-label-134" hidden="">Spiegeln</span><span id="dropdown-item-desc-135" hidden="">Ausgewählte Webcam spiegeln</span></li></ul></div></div></div><i class="muted--quAxq icon-bbb-unmute_filled"></i></div></div></div></div></div><span class="resizeWrapper"><div style="position: absolute; user-select: none; width: 10px; height: 100%; top: 0px; right: -5px; cursor: col-resize;"></div></span></div>`

**Comment by antobinary** [comment] 2021-04-26 19:54
Likely duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/12050
Let's keep both open in case there's a slight difference.
Thanks for the detailed report!

**Closed** 2021-04-29 20:37 UTC
Labels: module: client
