### ISSUE TITLE
Flie upload size limit warning - BBB 2.6 RC3

### ISSUE THREAD

**Issue by amishbhavsar** [bigbluebutton/bigbluebutton#16758] opened 2023-02-18 00:57 UTC
**Describe the bug**
BBB 2.6 RC3 does not allow presentation file size to be over 30 MB.

**To Reproduce**
1. Start a BBB class
2. Upload a PDF file over 30MB
3. BBB will show an error message saying that file size exceeds 30MB.

**Expected behavior**
BBB should allow any file size to be uploaded - or let admin set the limit.

**Comment by hostbbb** [comment] 2023-02-18 13:14
Ask questions in google forum bigbluebutton-setup before opening issues...

https://docs.bigbluebutton.org/admin/customize.html#increase-the-file-size-for-an-uploaded-presentation

regards,
Stephen

**Comment by ffdixon** [comment] 2023-02-18 14:22
Thanks Stephen.  However, given its reproducible problem, we're happy to see the issue opened with steps on how to reproduce.

If it were a more general question, such as "How do I configure HAProxy?", we would move that to the forums.

**Comment by amishbhavsar** [comment] 2023-02-21 00:36
I am sorry for raising an issue for this, but since there is no documentation that states that there is now a file size limit - just like there was a limit added to [annotations](https://github.com/bigbluebutton/bigbluebutton/issues/16701).
In the past when I have asked questions in the forum, there is sometimes no response, but I will try to use them again before I raise an issue.

**Comment by antobinary** [comment] 2023-02-21 14:01
Hi @amishbhavsar 

If you wish to communicate the limit to the presenters, you can enable https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.x-release/bigbluebutton-html5/private/config/settings.yml#L694
See the screenshot of https://github.com/bigbluebutton/bigbluebutton/pull/14158 for visuals.

The limit of 30mb is done for a performance reason. There are limitations for number of pages, max size of the file, max size of a single page, etc. Typically when we implement such cap, the reason is that we have seen sessions / servers not able to handle large files (etc) and that leads to significant reduction of the service. BigBlueButton's default configuration is set to (what we think is) reasonable set of configs. If you deem that you would prefer changing the limitations, feel free -- it's your setup after all.

Thanks @hostbbb for the link to the docs on common customizations related to the presentation - https://docs.bigbluebutton.org/admin/customize.html#presentation
It might be a good idea to add a note about the newly imposed limit of 300 shapes per slide. The documentation portion of BBB is always work in progress and there are efforts underway to make updating it and keeping it up to date with a specific BBB release even smoother.

All that said, the file upload size limit is not a bug and

> should allow any file size to be uploaded

is not exactly a realistic expectation from the point of view of implementation, infrastructure provisioning, etc.

We are happy to see that you are making good use of BigBlueButton and we are hoping some of these caps we have set are helping your end users enjoy a stable service.

I have opened an issue for extending the docs to include the max cap for annotations per slide https://github.com/bigbluebutton/bigbluebutton.github.io/issues/488  -- thank you for the suggestion!

I will be closing this github issue as I don't believe it holds an issue that we should take action on.

**Closed by antobinary** 2023-02-21 14:01 UTC
Labels: module: core
