### ISSUE TITLE
Big blue button re process the PDF everytime

### ISSUE THREAD

**Issue by pedped** [bigbluebutton/bigbluebutton#10641] opened 2020-10-13 07:09 UTC
I am using the BBB 2.2.26 for my online classrooms, I am using the same PDF file every time for each meeting, the problem is that when a meeting started, it will re process the PDF files again and it take time and huge CPU usage, is there any workaround or fix for this operation?

**Comment by ffdixon** [comment] 2020-10-13 17:55
It's a good suggestion.  In the next release (upcoming 2.3) we're working on background conversion of slides so, after you upload the PDF, you'll be able to interact with others without having to wait for it to convert.

On a single server, caching the conversion isn't too hard, but most larger scale deployments run a pool of BigBlueButton servers, so ultimately you would need to have a caching mechanism that is outside the BigBlueButton server, which is more complex to implement.

The upcoming background processing in 2.3 should help.

**Comment by matiasilva** [comment] 2020-10-13 20:17
Would be interesting to note if @pedped detects any abnormally high CPU usage during the conversion process, is this the case?

**Comment by pedped** [comment] 2020-10-13 20:22
@ffdixon thanks for your description, but it would nice if there was another ability to give a zip file that contain losts of images. it does not require conversion anymore. Also it would be nice if the on server default pdf files just convert once.

**Comment by pedped** [comment] 2020-10-13 20:24
@matiasilva I am using 5 to 6 pdf files that each one have around 150 to 200 pages, I takes about 2 minutes for them to process with i7-4770 CPU and 24GB ram.

**Comment by matiasilva** [comment] 2020-10-14 05:55
@pedped It might not be high CPU usage but just that it is rather laborious for it to go through the hundreds of pages.  I agree that the non-blocking upload will help alot, but have you considered pre-uploading the presentations? This would solve all your problems. A solution that can be used by everyone cannot be server-dependent (like dropping files in) because users might not always be self-hosting. Have a look at the architecture of presentation uploading: https://docs.bigbluebutton.org/2.2/architecture.html#presentation-conversion-flow. It is possible to perhaps inject the files in somewhere, but even then, how would you guarantee that your image files are in the correct order? A standard would have to be made and perhaps brings more trouble than it's worth. If you pre-upload your presentations, they will be there for any subsequent meetings you start.

**Comment by pedped** [comment] 2020-10-14 05:58
thanks for you suggestion, yes I pre upload the presentation when I request 'create' api, but for each meeting it will re process again.

**Comment by matiasilva** [comment] 2020-10-14 09:20
What solution do you have in mind?

**Comment by GhaziTriki** [comment] 2020-11-30 19:23
It might be a good idea to look for previously converted files with the same hash however not sure about any privacy issues.

**Comment by pedped** [comment] 2020-11-30 19:27
That is really good idea and can be done easy, if I know what method do the proccing, I may do that...

**Comment by basisbit** [comment] 2021-01-30 03:07
besides the privacy issue for many installs (we have to delete the files asap after the session ends), as fred mentioned already on a typical cluster setup the presentations would not exist on the server where you are randomly thrown at by scalelite.
Background processing now works in bbb 2.3-alpha. Thus, I suggest closing this issue and suggesting everyone who still complains to stop uploading such huge presentation files and instead cut the pdf so it only contains the slides which the presenter will actually need. There exists the pages-limit exactly to prevent users from uploading such files with tons of slides which definitely will not be shown in the current session.

**Comment by tdjac0bs** [comment] 2021-04-26 18:55
Duplicate of #6975

**Closed by tdjac0bs** 2021-04-26 18:55 UTC
Labels: component: presentation, type: enhancement
