### ISSUE TITLE
In Android Screen share and Share external video  not showing to newly joined

### ISSUE THREAD

**Issue by erpsolns** [bigbluebutton/bigbluebutton#15453] opened 2022-07-27 04:48 UTC
**Describe the bug**
In 2.5 and 2.6 
In a Session when Moderator  1) share screen or
2) share an external video.
A. These screenshare and shared external video are not visible to those who join after the screen share/share external video started User is using android
B. But audio is heard by newly joined guests for both shared external video as well as shared screen

**To Reproduce**

**Expected behavior**
Screenshare and Share external video should ALSO be  visible to newly joined 

**Actual behavior**
Screenshare and Share external video is not  visible to newly joined 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Device:  Samsung S21 ultra
 - OS:  Android
 - Browser  chrome
 - Version 

**Additional context**

**Comment by ramonlsouza** [comment] 2022-07-27 18:04
Thanks for @erpsolns! Fixed in 2.6 (pull request #15455, should be part of the next 2.6 release), could not reproduce in latest 2.5 (likely fixed already)

**Closed by ramonlsouza** 2022-07-27 18:04 UTC
Labels: module: client

**Comment by erpsolns** [comment] 2022-07-29 03:09
Thank you for your response
