### ISSUE TITLE
PIN numbers

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1348] opened 2015-08-12 07:27 UTC
Originally reported on Google Code with ID 593

```
=====================

What steps will reproduce the problem?
1. Configuring the PIN with 0xxx

What is the expected output?

On the welcome screen you should see the message about dialing in with PIN 0xxx

What do you see instead?

It only displays xxx instead of 0xxx
Astrisk works fine and we can dial in using 0xxx but it doesn't show up in the configured
conference with that PIN

What version of the product are you using?
4098-2010-04-02

On what operating system?

Ubuntu

```

We wanted to use "0xxx" as the PIN on Astrisk, to a select conference
session.

But in BBB, the "0" is dropped and only displays "xxx".

Is there a way to us a "0" as the first number in BBB?

I know it works fine in Astrisk, just need BBB to allow it too?

Here's my current string:

 meeting.put("voiceBridge",   "0266");

Many thanks,

David 

```

Reported by `davidalexanderbutler` on 2010-08-05 19:45:33

<hr>
 * *Attachment: [logs.tar.gz](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-593/comment-0/logs.tar.gz)*
```

**Comment by ffdixon** [comment] 2019-04-07 11:55
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/2217.

**Closed by ffdixon** 2019-04-07 11:55 UTC
Labels: API, Enhancement, Normal Priority, Voice
