### ISSUE TITLE
Breakout room timer visuals are wrong

### ISSUE THREAD

**Issue by Bimi124** [bigbluebutton/bigbluebutton#11498] opened 2021-02-25 07:42 UTC
**Describe the bug**
If you add a breakout roum, the "time left" timer counts down from the set time but it starts from the time where you joined the room. This is only a visual bug and the breakout room will close even if the timer says "5:00 left" (and stuff like that)

**To Reproduce**
1. Create new Breakout rooms (10 minutes)
2. Wait one minute
3. Join the room
4. The described bug will be clearly visible

**Expected behavior**
Timer is set to the left time in the beginning to make sure all timers a syncronized

**Actual behavior**
Timer is set to ten minutes

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox. but it semms to "work" with the browser of your choice
 - Version 86.0 (64-Bit)

**Comment by antobinary** [comment] 2021-02-25 09:58
Thanks for reporting!
This is a duplicate of #11358 

> If you add a breakout roum, the "time left" timer counts down from the set time but it starts from the time where you joined the room. This is only a visual bug and the breakout room will close even if the timer says "5:00 left" (and stuff like that)

I think this is new info and should help resolve the problem! Thank you! I will link to this comment in 11358 but will still close this to avoid separate threads

**Closed by antobinary** 2021-02-25 09:58 UTC
Labels: HTML5 Client
