### ISSUE TITLE
Pressing ENTER key on empty chat causes exception

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7097] opened 2019-03-23 13:58 UTC
Open the latest build of BigBlueButton 2.2-beta and press the enter key a few times.  There is an exception thrown for each press.

![exception](https://user-images.githubusercontent.com/290351/54867021-27173480-4d52-11e9-9ee7-1572374c44d5.gif)

**Comment by capilkey** [comment] 2019-04-01 18:29
I can't reproduce this.

**Comment by jfsiebel** [comment] 2019-04-01 18:41
This `onloadwff.js` seems to be related to LastPass plugin for Chrome. (https://forums.lastpass.com/viewtopic.php?f=12&t=274205)

**Comment by capilkey** [comment] 2019-04-01 18:45
Good catch. There might be some way for us to work around this or not trigger LastPass.

**Comment by antobinary** [comment] 2019-04-08 20:00
Moving to post 2.2 since this is an edge case, depends on extensions installed

**Comment by antobinary** [comment] 2021-03-03 09:58
> This `onloadwff.js` seems to be related to LastPass plugin for Chrome. (https://forums.lastpass.com/viewtopic.php?f=12&t=274205)

**Closed by antobinary** 2021-03-03 09:58 UTC
Labels: HTML5 Client
