### ISSUE TITLE
Desktop sharing broken on multi-head displays

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1642] opened 2015-08-12 07:41 UTC
Originally reported on Google Code with ID 887
```
I'm trying out BBB on a two-monitor system that consists of two 1920x1200 displays side
by side. I'm using an nVidia Quadro FX 3500 with TwinView.

When I initiate screen sharing using the "full desktop" option, what gets displayed
is the right half of my 3840x1200 desktop compressed into the left half of a square,
and the right side of the square is noise. (see attachment)

If I try to use a region, I get different effects depending on which monitor I drag
it onto. On the left monitor, the region displays the corresponding image from the
right monitor. When I drag the region to the right monitor, the preview is black.

Any ideas on how to make screen sharing usable?
```

Reported by `tessa.lau` on 2011-03-02 02:11:52

<hr>
 * *Attachment: bug1.png<br>![bug1.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-887/comment-0/bug1.png)*

**Comment by ffdixon** [comment] 2016-01-30 19:04
Can't reproduce this on 1.0-beta.  Closing the issue -- we can always reopen if it reappears.

**Closed by ffdixon** 2016-01-30 19:04 UTC
Labels: Defect, DeskShare (Java), Normal Priority
