### ISSUE TITLE
Keep the state of the presentation after sharing the screen

### ISSUE THREAD

**Issue by klorydryk** [bigbluebutton/bigbluebutton#14069] opened 2022-01-12 16:17 UTC
**Describe the bug**
During a meeting, if you've chosen to minimize the current presentation, then someone share his screen, the presentation is maximized again once the sharing is finished.

**To Reproduce**
1. start a meeting with a presentation
2. minimize the presentation 
3. some other participant start a screen sharing
4. this participant stop the screen sharing

**Expected behavior**
the screen comes back to the previous organisation: presentation is still minimized, only the cameras are displayed (or no camera if nobody was sharing them)

**Actual behavior**
The default presentation is maximized again, reducing the size of the cameras.

**BBB version:**
BBB v2.3

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 95.0.2

**Comment by antobinary** [comment] 2022-01-12 16:24
Thanks for reporting this!
If I understand correctly, you're talking about minimizing the presentation, rather than reducing the size, right?

**Comment by klorydryk** [comment] 2022-01-12 16:29
yes, exactly, I fix the issue.

**Comment by ramonlsouza** [comment] 2022-01-13 14:19
Looks like it is (or was) the expected behavior (https://github.com/bigbluebutton/bigbluebutton/pull/9814)

Removing [this line](https://github.com/bigbluebutton/bigbluebutton/blob/v2.3.x-release/bigbluebutton-html5/imports/ui/components/screenshare/component.jsx#L90) _might_ be enough for this change in 2.3 (I don't have a working 2.3 setup to test it).

**Comment by klorydryk** [comment] 2022-01-13 18:04
Oh, thanks, interesting! In one or 2 weeks, we'll update to the v2.4. I tested it and found that it is exactly the same behavior as the 2.3. Is it possible to cancel the #9814 ?
This componentWillUnmount() function is different between 2.3 and 2.4. Do you have an idea of the modification needed in 2.4?

**Comment by ramonlsouza** [comment] 2022-01-14 13:17
> Oh, thanks, interesting! In one or 2 weeks, we'll update to the v2.4. I tested it and found that it is exactly the same behavior as the 2.3. Is it possible to cancel the #9814 ?
> This componentWillUnmount() function is different between 2.3 and 2.4. Do you have an idea of the modification needed in 2.4?

In 2.4 it's a bit different... I sent a PR with the changes needed (not sure if it will be merged, but if not you can reproduce the changes in your server).

**Comment by klorydryk** [comment] 2022-01-20 12:40
Thank you @ramonlsouza ! I hope it'll be merged, as I would like to avoid forking or patching my local version :/

**Comment by antobinary** [comment] 2022-01-20 14:11
Merged to be included in BBB 2.4.3! :confetti_ball:

**Closed by antobinary** 2022-01-20 14:11 UTC
Labels: module: client
