### ISSUE TITLE
Reconnected Flash users are getting kicked out of the voice conference

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6176] opened 2018-10-22 22:16 UTC
Sometimes when the user gets reconnected, akka-apps will disconnect the user from audio, which falls them back to the echo test.

The user will then (a) see their microphone in the user's list, but be in the echo test.

Investigate if we can delay kicking the user to give the client a chance to reconnect.

**Comment by capilkey** [comment] 2018-10-24 18:48
After some investigation it turns out that the problem wasn't in akka-apps nor was it in the Flash client. The problem was that the HTML5 server side was telling akka-apps to eject the reconnecting user from voice. The fix for the issue is in #6184.

**Comment by capilkey** [comment] 2018-10-24 20:04
Fixed in #6184

**Closed by capilkey** 2018-10-24 20:04 UTC
