### ISSUE TITLE
After Reboot, BBB Server doesn't work properly

### ISSUE THREAD

**Issue by daviduhl77** [bigbluebutton/bigbluebutton#9220] opened 2020-04-23 14:56 UTC
Hello

After a reboot of the BBB Server, installed with Greenlight, I can login to the UI to start a new session in my Home Room. Then, the three white buttons come up, but then 
it doesn't go on. I checked the Greenlight-Coniguration, everything ok. 
It is the second server with this issue. I used the bbb-install script to setup the server. Does anyone can help or give a hint, where I can find the problem?

**Comment by ProgDtn** [comment] 2020-04-23 19:24
I had the same issue, but in my case the server was hard reset twice (powerloss) before the issue appeared. It was fixed after manually stopping and restarting the bbb service.

**Comment by runout-at** [comment] 2020-04-24 16:18
maybe a duplicate? #9182

**Comment by matiasilva** [comment] 2020-06-14 23:31
Without further information, it can only be assumed to be a duplicate of either the above issue or #8981. Closing until further information is given.

**Closed by matiasilva** 2020-06-14 23:31 UTC
