### ISSUE TITLE
co-browse

### ISSUE THREAD

**Issue by Josecarpeniet** [bigbluebutton/bigbluebutton#9829] opened 2020-06-13 02:03 UTC
Hi, 
Cobrowse is a game-changer.
Imagine sharing your browser directly and both users, presenter, and attendee can collaborate in real projects and doing it in real-time.

When delivering/presenting content in BBB, right now we are just limited to a plain presentation. We could make the system more dynamic.

With co-browse, we would be opening a door to infinite possibilities because you could leverage any website introducing it in your workflow!
Think about using an online flashcards application or maybe a Codepen where you guide your student while collaborating in a real project, with browser sharing the sky is the limit. This is the closest to be in the same room sharing interactive tools/apps on a computer.

I'm using it on Vectera and it blew my mind (here you can see an example https://help.vectera.com/en/articles/3347286-how-do-you-set-up-co-browsing) and we 

Cheers!

**Comment by basisbit** [comment] 2020-06-13 10:23
Duplicate of #9785
Also, next time please stick to the issue template, so that it is easier to figure out what the issue actually is about. Thank you.

**Closed by basisbit** 2020-06-13 10:23 UTC
Labels: Enhancement
