### ISSUE TITLE
Bug moving notes to whiteboard

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#15773] opened 2022-10-03 16:59 UTC
**Describe the bug**
After the notes data is loaded as a presentation, it gets stuck in the current slide. If the presenter draws something, the presentation is updated to the correct slide.

_Obs.: There's no info about the progress_

**To Reproduce**
1. Join in the meeting;
2. Type something in the shared notes;
3. Click to move that to whiteboard;
4. Wait a few seconds;
5. See the notification and presentation's auto-resize;

**Video**

https://user-images.githubusercontent.com/56703993/193633866-c33dbea3-fe6c-41c2-9c49-969d2fac3e06.mp4

**Comment by danielpetri1** [comment] 2022-10-03 20:52
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/15259, but the reported behavior after adding the annotation is new.

**Closed** 2022-11-10 13:42 UTC
Labels: module: client
