### ISSUE TITLE
Web-Cam: neue Steuerungsoption

### ISSUE THREAD

**Issue by HE700** [bigbluebutton/bigbluebutton#12155] opened 2021-04-26 13:55 UTC
the following feature would be helpful in a Meeting for the Web-Cam Options

simultaneously 
•	Camera-Sharing: all participants are able to view my camera-transmission
•	suppress my own camera-stream for myself

result: I see everyone but myself having chosen this new option

Benefit: I tried this in two person dialogues through full-screen-modus of my partner in conference. Mental focussing and encounter is improved through the realizition of a real world optic without permanently mirroring yourself.

I would be thankful for programming this feature. Please give me a mail for questions or if this option is realized.

**Comment by prlanzarin** [comment] 2021-04-26 14:32
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11990

**Closed by prlanzarin** 2021-04-26 14:32 UTC
Labels: type: enhancement
