### ISSUE TITLE
Talking Indicator is not considered in See other viewers Lock in Users List

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#8420] opened 2019-12-12 18:55 UTC
Hi BBB,

The Talking Indicator isn't considering the **See other viewers Lock in Users List**

details below: 
![image](https://user-images.githubusercontent.com/5144311/70739819-79d8b800-1cf6-11ea-9643-dd4c0e623e39.png)

![image](https://user-images.githubusercontent.com/5144311/70740081-2450db00-1cf7-11ea-9b37-5f9996364944.png)

![image](https://user-images.githubusercontent.com/5144311/70740066-19964600-1cf7-11ea-952a-b05ed213db73.png)

**Comment by ffdixon** [comment] 2020-01-20 00:28
Good catch.

**Comment by antobinary** [comment] 2020-01-20 14:43
We discussed this is the past and the conclusion was that this request is beyond what "See other viewers in Users' list" was about.
The names of the other participants could still be revealed as they chat publicly/privately, share webcam, etc. So to achieve this fuller level of keeping things hidden the instructor will have to enable more lock settings (already existing).

In my mind this issue is a "non-issue" - not to be implemented.

**Comment by antobinary** [comment] 2021-02-02 14:05
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11252

**Closed by antobinary** 2021-02-02 14:05 UTC
Labels: HTML5 Client
