### ISSUE TITLE
minimize my own Video

### ISSUE THREAD

**Issue by Thorgrimson** [bigbluebutton/bigbluebutton#12307] opened 2021-05-06 15:22 UTC
**Is your feature request related to a problem? Please describe.**
Long sight-for-yourself in video conferences is very tiring.

**Describe the solution you'd like**
minimize my own Video

**Comment by prlanzarin** [comment] 2021-05-06 16:24
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11990

(please search the issue tracker before opening a new one. Have a nice day.)

**Closed by prlanzarin** 2021-05-06 16:24 UTC
Labels: status: duplicated
