### ISSUE TITLE
Firefox/Chrome on Linux showing as Chrome on iOS

### ISSUE THREAD

**Issue by dejageek** [bigbluebutton/bigbluebutton#8153] opened 2019-09-26 18:32 UTC
Running fresh install of BBB 2.2.0-beta using the HTML5 client.  Both Firefox and Chrome on Ubuntu 18.04 are getting an error upon entering a room. "At this time audio and video are not supported on Chrome for iOS."

Firefox version is 69.0.1 (64bit)
Chrome version is 77.0.3865.90 (64bit)
Ubuntu version is 18.04 (64bit)

Results of "https://demo.bigbluebutton.org/html5client/useragent"
Firefox: Firefox 69.0.0 / Ubuntu 0.0.0
Chrome: Chrome 77.0.3865 / Linux 0.0.0
![Screenshot from 2019-09-26 13-24-21](https://user-images.githubusercontent.com/19317610/65715117-1a0d3200-e062-11e9-9571-43b7b734dea3.png)

**Comment by capilkey** [comment] 2019-09-26 18:44
The problem is that there's one singular error message, not that the browsers are being misidentified. I'm going to guess that you don't have SSL setup so the browsers are blocking access to the getUserMedia API. 

You can find instructions for configuring SSL here, http://docs.bigbluebutton.org/2.2/install.html#configure-ssl-on-your-bigbluebutton-server.

Duplicate of #8112

**Closed by capilkey** 2019-09-26 18:44 UTC
