### ISSUE TITLE
bbb-record --delete <meeting-id> does not delete "video" folder

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/bigbluebutton#14241] opened 2022-01-31 21:49 UTC
Hi,
When using Daniel Petri Rocha's bbb-recording-exporter script (https://github.com/danielpetri1/bbb-recording-exporter) a new "video" folder is created in `/var/bigbluebutton/published/video/<internal-meeting-id>` for each "presentation" recording.

When running the command `bbb-record --delete <internal-meeting-id>` the folder `/var/bigbluebutton/published/presentation/<internal-meeting-id>` gets deleted but not folder `/var/bigbluebutton/published/video/<internal-meeting-id>`.
This results in inconstitency since API command `getRecordings` (with no additional parameters) replies with an existing "video" recording xml set although it should return an empty xml set.

Expected behavior is that `bbb-record --delete <internal-meeting-id>` command deletes both folders : "presentation" AND "video".

Kind regards,
Thierry

**Comment by antobinary** [comment] 2022-02-02 23:49
@danielpetri1 is the exporter part of BBB now? Is this to be considered an issue with BBB or outside of BBB?

@pielonet could you please write the version of BBB you're running - 2.4.2 / 2.3.17 / v2.5.x-release branch or...?

**Comment by danielpetri1** [comment] 2022-02-03 12:12
Hi @pielonet,
Thank you for detecting and reporting this issue.

I suggest closing this issue here and moving it to [my repository](https://github.com/danielpetri1/bbb-recording-exporter) or mentioning it in the PR #12533 since the script hasn't been merged and is therefore **not a part of BBB**.

The cause seems to be that when running `--delete` the `bbb-conf` script removes the published directories based on available recording formats which it detects from the processing script folder. In this case, though, `video` is not a worflow per se, but rather just a place to hold the `metadata.xml` file Greenlight/Moodle etc. require to give end users access to the video.

So what is problematic here is that the conversion to MP4 is occurring as a post publish script, being an extension of the presentation format, instead of a separate one. This is something @kepstin [had already mentioned](https://github.com/bigbluebutton/bigbluebutton/pull/12533#issuecomment-1016685948) in the PR for this script. The question that remains is how to best accomplish this while taking the upcoming changes to the whiteboard into account.

**Comment by pielonet** [comment] 2022-02-03 19:03
@danielpetri1 Thank you for taking my request into account.
I know your script is likely to be added to BBB core (congratulations !). This is why I decided to place this issue here.
@antobinary I use BBB 2.4.2
I hope Daniel's script will be soon added to the core and this issue solved at the same time (or sooner ;) )

**Comment by antobinary** [comment] 2023-07-19 20:29
>I suggest closing this issue here and moving it to my repository or mentioning it in the PR #12533 since the script hasn't been merged and is therefore not a part of BBB.

Closing. BBB has a different way for recording and producing a vvideo file of it.

**Closed by antobinary** 2023-07-19 20:29 UTC
Labels: type: defect, module: recording, status: verify
