### ISSUE TITLE
Problem with https

### ISSUE THREAD

**Issue by grunam** [bigbluebutton/bigbluebutton#8166] opened 2019-09-30 13:06 UTC
Hi,

When I try to load webcam I have an issue with https and http mixed content.

Mixed Content: The page at 'https://visio.formedlive.com/html5client/users' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://visio.formedlive.com/bbb-webrtc-sfu'. This request has been blocked; this endpoint must be available over WSS.

![image](https://user-images.githubusercontent.com/28531689/65881073-21e71200-e393-11e9-9416-d8c66d5232ed.png)

- I did  a setup using Let’s Encrypt
- I Configured FreeSWITCH for using SSL
- I Configured BigBlueButton to load session via HTTPS
- I Tested my HTTPS configuration

Could yo help me please ?

**Comment by ffdixon** [comment] 2019-09-30 15:38
Can you try using the [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) script to setup your server -- it implements all the steps (except configuring a firewall).

Try the above and let us know if you still encounter the same error.

**Comment by capilkey** [comment] 2019-09-30 15:49
You missed at least one step from this section, http://docs.bigbluebutton.org/2.2/install.html#configure-bigbluebutton-to-load-session-via-https. The Kurento websocket wasn't changed in settings.yml.

The install script that Fred linked will also configure it for you.

**Comment by grunam** [comment] 2019-09-30 15:52
Hi,

Thank you for your reply. 

I have already install bigbluebutton with bbb-install.sh.

Must I start over from the beginning?

However I must achieve the step below to set up ssl/https ? Isn’t it ?

- setup using Let’s Encrypt
- Configure FreeSWITCH for using SSL
- Configure BigBlueButton to load session via HTTPS
- Test HTTPS configuration

**Comment by capilkey** [comment] 2019-09-30 16:23
The install script has options for email and domain name and it will use those to generate a Let's Encrypt certificate. The only time the options won't work is if you're installing on a private server and you need to use the DNS challenge instead of the HTTP challenge. If you're installing on a public server then the easiest option would be to re-run the install script with the new options and it will try to fix the configuration. The script can be run as many times as you want with the same options and it should always end up with the same result.

You can also do all of the configurations manually and the steps are listed in the link that I posted. The full steps start here, http://docs.bigbluebutton.org/2.2/install.html#configure-ssl-on-your-bigbluebutton-server.

For the question about which version to install. The script should work with either 2.0 or 2.2. You just need to change the part with "xenial" to be "220-beta" or "200". If you're just getting started with BigBlueButton, and you're looking to use the HTML5 client, I would recommend using 2.2-beta. If you want to change from 2.0 to 2.2 the script will also handle the upgrade for you.

**Comment by ffdixon** [comment] 2019-09-30 16:28
I would echo Chad's comments as we recommend you install BigBlueButton 2.2-beta as it has the latest version of the HTML5 client.

**Comment by datapack** [comment] 2019-10-14 21:38
I had the same issue . The problem is with HTTPS

**Comment by grunam** [comment] 2019-10-15 06:51
For automatic installation of BBB server be careful not to make the same mistake like me : in the following command replace bbb.my-server.com by your server name and replace info@my-server.com by your email.


wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-beta -s bbb.my-server.com -e info@my-server.com

**Comment by matiasilva** [comment] 2020-06-15 13:17
Seems to be resolved. Closing for now but feel free to follow up.

**Closed by matiasilva** 2020-06-15 13:17 UTC

**Comment by monikawindzoon** [comment] 2020-07-29 03:34
Hello,

If I load with https it's not working, I have installed with this instruction, wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-beta -s bbb.my-server.com -e info@my-server.com

![Screen Shot 2020-07-29 at 9 03 36 AM](https://user-images.githubusercontent.com/27999642/88753689-78230e00-d17a-11ea-96b4-789303d23a32.png)

**Comment by matiasilva** [comment] 2020-07-29 07:37
Hi, for support requests please go to https://docs.bigbluebutton.org/2.2/getting-help.html
