### ISSUE TITLE
Whiteboard line issue

### ISSUE THREAD

**Issue by nikandlv** [bigbluebutton/bigbluebutton#9067] opened 2020-04-14 00:58 UTC
The current whiteboard is broken and can not draw lines, shapes work tho.
Probably because of https://github.com/bigbluebutton/bigbluebutton/commit/df40e6b2141945dbc636ee19e141a29f35c7a4a1

**Comment by ffdixon** [comment] 2020-04-14 02:05
That code is for the upcoming BigBlueButton 2.3 development.  It's not in BigBlueButton 2.2.5 (the current release).

I did a quick test on https://demo.bigbluebutton.org/ (which is running 2.2.5) and drawing of lines is working as expected.

**Comment by nikandlv** [comment] 2020-04-14 15:53
@ffdixon I know, I'm reporting this so we keep it as a known issue to fix for the next release

**Comment by Salamit** [comment] 2020-05-09 13:35
Sorry but how do I fix this issue? I have updated bbb to the latest version using the update instructions in the [docs](https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22) and I the pencil/pen is still not working.

Thanks in advance for the assistance.

**Comment by ffdixon** [comment] 2020-05-09 13:41
Can you test it on https://test.bigbluebutton.org/ and let us know if it works for you there.

**Comment by Salamit** [comment] 2020-05-09 13:47
@ffdixon I just tried an it works. Is there a setting that affects how the pen works? This only began when I updated a few updates ago.

**Comment by ffdixon** [comment] 2020-05-09 14:12
What version of BigBlueButton are you running?

**Comment by Salamit** [comment] 2020-05-09 14:15
Thanks again @ffdixon:  BigBlueButton Server 2.2.9 (1891)

**Comment by Bhargesh11** [comment] 2020-06-21 11:20
@Salamit  is your issue fixed ?
I am also facing a similar pencil not working issue on BigBlueButton Server 2.2.17 (1992)

**Comment by Salamit** [comment] 2020-06-21 11:37
@ Bhargesh11 no it isn’t. But I think it was supposed to be fixed in an update. I just haven’t updated yet.

T.Salami

**Comment by ffdixon** [comment] 2020-06-21 12:11
Can you reproduce this issue on https://test.bigbluebutton.org/?

**Comment by Bhargesh11** [comment] 2020-06-22 10:10
@ffdixon Thank you. 
It works on  https://test.bigbluebutton.org/

How can i get pencil working on my BigBlueButton Server 2.2.17 (1992) ?

**Comment by onuryarartr** [comment] 2020-12-08 15:25
> That code is for the upcoming BigBlueButton 2.3 development. It's not in BigBlueButton 2.2.5 (the current release).
> 
> I did a quick test on https://demo.bigbluebutton.org/ (which is running 2.2.5) and drawing of lines is working as expected.



Hi Fred,

We use BBB on Moodle. Some graphic tablets (Gaomon S620 etc) and Apple pencil (with iPad Pro) cannot write properly when using whiteboard. The drawing is not fluid, it continues intermittently and the characters are distorted. If we could share iPad screen, we could use the whiteboard application installed on the iPad. What can we do about this trouble?

**Comment by ffdixon** [comment] 2020-12-08 17:45
@Bhargesh11 Recommend updating your server to 2.2.30.

@onuryarartr Can you try out the next version of BigBlueButton (2.3-dev) at https://dev23.bigbluebutton.org/ and let us know if the writing is any better.

**Comment by onuryarartr** [comment] 2020-12-09 15:45
Thank you for your answer.
We have installed 2.3-dev on the server (Ubuntu 18.04) before, but we had to revert to earlier version 2.2 (Ubuntu 16.04) because of the problem of creating video recordings.

**Comment by onuryarartr** [comment] 2020-12-10 09:30
@ffdixon We try out the BigBlueButton (2.3-dev) at https://dev23.bigbluebutton.org/ 
Lines can't stick when I try to use the pen as in the image below. I think that the same problem with @Salamit 

![BigBlueButton-Demo-Meeting-Opera](https://user-images.githubusercontent.com/47314546/101752523-b2b29500-3ae2-11eb-8d89-3283b6262d2e.gif)

**Comment by ffdixon** [comment] 2020-12-10 18:31
We have that fixed in upcoming 2.2-alpha3.  Look for an announcement to [bigbluebutton-dev](https://groups.google.com/forum/#!forum/bigbluebutton-dev) when it is release.

**Comment by antobinary** [comment] 2021-02-10 16:48
I can no longer reproduce this. Please comment if the issue is still present in any form

**Closed by antobinary** 2021-02-10 16:48 UTC
Labels: HTML5 Client
