### ISSUE TITLE
Echo test fails with ICE error 1010 if more than one network interface on client

### ISSUE THREAD

**Issue by ArminXG** [bigbluebutton/bigbluebutton#10708] opened 2020-10-23 08:54 UTC
**Describe the bug**
Just updated to 2.2.28 and the echo test is now faster and works good. But if my client has another network interface in use (e.g. VPN to company), the echo test takes long and fails with ICE 1010.
Chrome/Chromium show that error. Firefox is slow too, but doesn't run into error 1010.

**To Reproduce**
Have another network interface active (like VPN to something).
Start a BBB meeting with Chrome/Chromium and choose with microfone.

**Expected behavior**
No error on echo test.

**Actual behavior**
Echo test takes very long and finally ICE error 1010 appears.
If second network interface is shutdown, echo test works perfectly.

This error didn't occur with version 2.2.26.

BigBlueButton Server 2.2.28 (2210)

Chrome/Chromium version 86.

**Comment by ffdixon** [comment] 2020-10-23 17:16
Are you able to reproduce this issue on https://test.bigbluebutton.org/?

**Comment by InfoFractal** [comment] 2020-10-23 19:52
I'm also having the same problem with 2.2.27. Can't figure out what is wrong. Once the VPN is disabled everything works again.
The test.bigbluebutton.org works fine with the VPN enabled.

**Comment by ffdixon** [comment] 2020-10-25 22:32
test.bigbluebutton.org has a TURN server configured.  Do you have a [TURN](https://docs.bigbluebutton.org/2.2/setup-turn-server.html) server setup with your BigBlueButton server?

**Comment by ArminXG** [comment] 2020-10-26 09:31
test.bigbluebutton.org works fine for me too.
TURN is not configured, but STUN is used.
The tcpdump shows the STUN queries and the correct answers from STUN server.
But BBB doesn't seem to use that answer, it sends more queries for all local IPs it found.

**Comment by carroarmato0** [comment] 2020-10-26 11:15
I just updated as well and suddenly have the same issue.

I'm running a work VPN, but it's not my default route, the VPN is only configured to route for IP addresses which are specifically meant to be reachable though it.

My BBB instance is reachable over a public IP address.

Before the 2.2.28 update this worked.  But after the update, I have to shutdown the VPN connection in order for the ICE test to work.

**Comment by carroarmato0** [comment] 2020-10-26 11:35
When I troubleshoot the issue in the browser console, I see the following:

My client sends out the networks it knows of:

- Work VPN:  192.168.14.9
- Wifi: 192.168.50.172
- Personal VPN: 10.10.0.4
- ... 
- My Public IP address: 78.23.27.142

Doesn't work -->

```
a=fingerprint:sha-256 22:44:3D:65:77:8E:31:26:0E:DC:90:E4:DD:C4:CE:CA:00:76:81:4A:05:92:F1:A9:ED:2D:83:5A:0E:04:52:DC
a=candidate:2642038044 1 udp 2122260223 10.10.0.4 43530 typ host generation 0 network-id 2 network-cost 50
a=candidate:3472871628 1 udp 2122194687 192.168.14.9 56320 typ host generation 0 network-id 1
a=candidate:868771161 1 udp 2122131711 2a02:1812:1615:1cf0:7961:ea6a:e98e:5beb 38695 typ host generation 0 network-id 4 network-cost 10
a=candidate:625464392 1 udp 2122066175 2a02:1812:1615:1cf0::9ce 45612 typ host generation 0 network-id 5 network-cost 10
a=candidate:247074094 1 udp 2121998079 192.168.50.172 33692 typ host generation 0 network-id 3 network-cost 10
a=candidate:3556356588 1 tcp 1518280447 10.10.0.4 9 typ host tcptype active generation 0 network-id 2 network-cost 50
a=candidate:2155621436 1 tcp 1518214911 192.168.14.9 9 typ host tcptype active generation 0 network-id 1
a=candidate:2102106537 1 tcp 1518151935 2a02:1812:1615:1cf0:7961:ea6a:e98e:5beb 9 typ host tcptype active generation 0 network-id 4 network-cost 10
a=candidate:1808017592 1 tcp 1518086399 2a02:1812:1615:1cf0::9ce 9 typ host tcptype active generation 0 network-id 5 network-cost 10
a=candidate:1077539294 1 tcp 1518018303 192.168.50.172 9 typ host tcptype active generation 0 network-id 3 network-cost 10
a=candidate:3258397373 1 udp 1685790463 78.23.27.142 33692 typ srflx raddr 192.168.50.172 rport 33692 generation 0 network-id 3 network-cost 10
a=ice-options:trickle
```

Works (without the Work VPN) -->

```
a=fingerprint:sha-256 8B:15:97:65:93:7E:1F:61:16:F3:90:34:42:7D:0B:6B:1B:1D:53:4F:22:73:BD:07:B6:79:24:B6:BF:93:B9:EF
a=candidate:2642038044 1 udp 2122260223 10.10.0.4 43861 typ host generation 0 network-id 1 network-cost 50
a=candidate:868771161 1 udp 2122197247 2a02:1812:1615:1cf0:7961:ea6a:e98e:5beb 39068 typ host generation 0 network-id 3 network-cost 10
a=candidate:625464392 1 udp 2122131711 2a02:1812:1615:1cf0::9ce 60126 typ host generation 0 network-id 4 network-cost 10
a=candidate:247074094 1 udp 2122063615 192.168.50.172 48590 typ host generation 0 network-id 2 network-cost 10
a=candidate:3556356588 1 tcp 1518280447 10.10.0.4 9 typ host tcptype active generation 0 network-id 1 network-cost 50
a=candidate:2102106537 1 tcp 1518217471 2a02:1812:1615:1cf0:7961:ea6a:e98e:5beb 9 typ host tcptype active generation 0 network-id 3 network-cost 10
a=candidate:1808017592 1 tcp 1518151935 2a02:1812:1615:1cf0::9ce 9 typ host tcptype active generation 0 network-id 4 network-cost 10
a=candidate:1077539294 1 tcp 1518083839 192.168.50.172 9 typ host tcptype active generation 0 network-id 2 network-cost 10
a=candidate:3258397373 1 udp 1685855999 78.23.27.142 48590 typ srflx raddr 192.168.50.172 rport 48590 generation 0 network-id 2 network-cost 10
a=ice-options:trickle
```

**Comment by carroarmato0** [comment] 2020-10-26 11:53
Looking at the rest of the console logs it looks like it's doing all the right things, connecting to the correct public IP address of the BBB instance.
Only during the ICE test it fails: 

```
[12:31:10:0624]  INFO: clientLogger: Audio call session accepted c (https://<BBB url>/html5client/d3c57d5494122295d6d06c8426cee650e4e1fd44.js?meteor_js_resource=true:121:1189830)
d3c57d5494122295d6d06c8426cee650e4e1fd44.js?meteor_js_resource=true:9 [12:31:10:0625]  INFO: clientLogger: Audio call - check if ICE is finished and FreeSWITCH is ready s (https://<BBB url>/html5client/d3c57d5494122295d6d06c8426cee650e4e1fd44.js?meteor_js_resource=true:121:1
```

So I'm guessing something funky happens in the backend of BBB itself.
I can help troubleshoot and provide data if necessary given some guidance.

**Comment by carroarmato0** [comment] 2020-10-26 12:10
This looks to to be something that was introduced in BBB 2.2.26

```
Webcams, screenshare, listenOnly audio
Backport Kurento/kms-elements#28

Fixed the networkInterfaces option to be dual stack (IPv4+IPv6) compatible and also work with network interfaces with multiple IP addresses of the same family
Added a new companion config ipIgnoreList: to be used alongside networkInterfaces to ignore unwanted IP addresses in the ICE gathering procedure. With the changes to networkInterfaces, private IP addresses will now also be gathered. If you don't need intranet connectivity with Kurento, add the private IP (and any other unwanted ones) from the interfaces in networkIntefaces to the ignore list and they won't be used.
Link-local IPs (169.254.* and fe80::*) are already ignored by default, so you don't need to set them up in the ignore list
Note: For best results we recommend the usage of externalIPv4+externalIPv6+ipIgnoreList
```
So since a VPN also uses a private local network, that's why it's being picked up. But it's difficult to predict what private networks users connecting are using.

**Comment by ffdixon** [comment] 2020-10-26 12:12
Kurento is only used for Listen Only, so if you are connecting with microphone it's going to FreeSWITCH.

Interested to figure out what is happening here.  See also https://groups.google.com/g/bigbluebutton-dev/c/YEQJDxT2Mbk/m/66oDWPKAAAAJ

**Comment by mariogasparoni** [comment] 2020-10-26 13:26
@carroarmato0 can you reproduce your problem on https://test.bigbluebutton.org/ ?

Another question, which VPN client are you using ? i am trying to reproduce the problem here

**Comment by ArminXG** [comment] 2020-10-26 13:33
With version 2.2.26 all worked good. So I think it was introduced with version 2.2.27.

In my case it is wireguard for VPN. Defaultroute is eth0 and wg0 just an internal network 192.168.0.0/16.

**Comment by carroarmato0** [comment] 2020-10-26 13:34
@mariogasparoni  I have the same issue on test.bigbluebutton.org  but different error when the VPN is running (Call timeout: 1006)

```
sip.js?v=1063:19081 WebSocket connection to 'wss://ipv4.test.bigbluebutton.org/ws?sessionToken=qlv7nzy2smprdpv6' failed: Error in connection establishment: net::ERR_CERT_COMMON_NAME_INVALID
_connect @ sip.js?v=1063:19081
connect @ sip.js?v=1063:18984
start @ sip.js?v=1063:17448
(anonymous) @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:121
createUserAgent @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:121
(anonymous) @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:1
sip.js?v=1063:9591 Mon Oct 26 2020 14:32:02 GMT+0100 (Central European Standard Time) | sip.Transport | WebSocket error occurred.
print @ sip.js?v=1063:9591
genericLog @ sip.js?v=1063:9571
genericLog @ sip.js?v=1063:9644
error @ sip.js?v=1063:9632
onWebSocketError @ sip.js?v=1063:19239
(anonymous) @ sip.js?v=1063:19084
error (async)
_connect @ sip.js?v=1063:19084
connect @ sip.js?v=1063:18984
start @ sip.js?v=1063:17448
(anonymous) @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:121
createUserAgent @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:121
(anonymous) @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:1
Promise.then (async)
n.then @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:21
doCall @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:121
(anonymous) @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:121
joinAudio @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:121
l @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:121
l @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:121
(anonymous) @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:121
setTimeout (async)
c @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:121
(anonymous) @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:121
(anonymous) @ sip.js?v=1063:11799
emit @ sip.js?v=1063:11799
stateTransition @ sip.js?v=1063:13821
(anonymous) @ sip.js?v=1063:14975
(anonymous) @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:1
Promise.then (async)
n.then @ 68473e020b2870e03381e47236372c467342096c.js?meteor_js_resource=true:21
onAccept @ sip.js?v=1063:14966
onAccept @ sip.js?v=1063:14750
receiveResponse @ sip.js?v=1063:10890
receiveResponse @ sip.js?v=1063:8068
receiveResponse @ sip.js?v=1063:6522
receiveResponseFromTransport @ sip.js?v=1063:10455
receiveIncomingResponseFromTransport @ sip.js?v=1063:9851
onTransportMessage @ sip.js?v=1063:17955
transport.onMessage @ sip.js?v=1063:17847
onWebSocketMessage @ sip.js?v=1063:19294
(anonymous) @ sip.js?v=1063:19086
sip.js?v=1063:9595 Mon Oct 26 2020 14:32:02 GMT+0100 (Central European Standard Time) | sip.Transport | WebSocket closed unexpectedly
print @ sip.js?v=1063:9595
genericLog @ sip.js?v=1063:9571
genericLog @ sip.js?v=1063:9644
warn @ sip.js?v=1063:9635
onWebSocketClose @ sip.js?v=1063:19223
(anonymous) @ sip.js?v=1063:19083
sip.js?v=1063:9599 Mon Oct 26 2020 14:32:02 GMT+0100 (Central European Standard Time) | sip.Transport | WebSocket closed wss://ipv4.test.bigbluebutton.org/ws?sessionToken=qlv7nzy2smprdpv6 (code: 1006)
``` 

The VPN is Cisco OpenConnect/AnyConnect on Ubuntu.

**Comment by carroarmato0** [comment] 2020-10-26 13:39
And just as @ArminXG  mentions, the VPN is only configured for accessing local (vpn) network resources.
Since it's a corporate VPN, a huge amount of routing rules are pushed, but if I'm not mistaking, only the network links are taken into consideration?

```
~ ip route
default via 192.168.50.1 dev wlp4s0 proto dhcp metric 600 
10.1.0.0/16 dev vpn0 proto static scope link metric 50 
10.4.0.0/24 dev vpn0 proto static scope link metric 50 
10.10.0.0/24 dev wg0 proto kernel scope link src 10.10.0.4 
10.15.0.0/16 dev vpn0 proto static scope link metric 50 
10.60.0.0/15 dev vpn0 proto static scope link metric 50 
10.60.239.0/24 dev vpn0 proto static scope link metric 50 
10.62.0.0/16 dev vpn0 proto static scope link metric 50 
10.112.0.0/16 dev vpn0 proto static scope link metric 50 
...
192.168.32.0/24 dev vpn0 proto static scope link metric 50 
192.168.33.0/24 dev vpn0 proto static scope link metric 50 
192.168.34.0/25 dev vpn0 proto static scope link metric 50 
192.168.35.0/24 dev vpn0 proto static scope link metric 50 
192.168.36.0/24 dev vpn0 proto static scope link metric 50 
...
192.168.49.0/24 dev vpn0 proto static scope link metric 50 
192.168.50.0/24 dev wlp4s0 proto kernel scope link src 192.168.50.172 metric 600 
192.168.50.0/24 dev wg0 scope link metric 1000 
192.168.50.1 dev wlp4s0 proto static scope link metric 600 
192.168.64.0/24 dev vpn0 proto static scope link metric 50 
...
```

**Comment by InfoFractal** [comment] 2020-10-26 15:20
I updated our severs to 2.2.28 and the issue stopped, very weird since we didnt really change any configurations. We have used our own turn server since 2.2.3.

**Comment by mariogasparoni** [comment] 2020-10-26 19:32
Thanks for your info @ArminXG and @carroarmato0. I am trying to reproduce it here (tried using OpenVPN - works with default gateway set for both my lan's and VPN)

@carroarmato0 could you please send me a dump of chrome://webrtc-internals from the moment you connected to your room ? Also send me the same dump for test.bigbluebutton.org.

@ArminXG,  could you please send the same dump from the moment this problem happened (in your own bbb's setup, not test.bigbluebutton.org) ?

**Comment by mariogasparoni** [comment] 2020-10-28 12:45
@carroarmato0 thanks for your report. Actually i was expecting this *should* be happening from the beginning. Having another interface may add a small delay to the audio connection, once more ICE candidates would be gathered and later tested against connectivity (we don't do trickle ICE so far). But, at the end, ICE would be able to find your default gateway and connect to the echo test.

If you guys get this "sometimes echo fail" behavior, i would recommend try increasing the value for [iceGatheringTimeout](https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bigbluebutton-html5/private/config/settings.yml#L291) option. This lets browser spend more time gathering possible candidates. 
_( be aware this will add delay for Firefox when using TURN on 443/TCP port - more info [here](https://github.com/bigbluebutton/bigbluebutton/pull/10716) )_

**Comment by krishnateja-ct** [comment] 2020-10-28 13:09
@mariogasparoni We had updated the BBB server from v2.2.23 to v2.2.28 on last Thursday after which users with a high number of network interfaces (these users were having services like docker running) than a normal user started facing **ICE Negotiation Timeout error 1010**. Last night we redeployed the html5Client with a higher value for **ICE_NEGOTIATION_TIMEOUT** which had resulted in 0 complaints of 1010 error from users.

**Comment by ArminXG** [comment] 2020-10-28 13:16
@mariogasparoni 
This is the requested dump of the problem with the own BBB setup when a wireguard vpn to a private network is
active. 
[webrtc_internals_dump.txt](https://github.com/bigbluebutton/bigbluebutton/files/5452047/webrtc_internals_dump.txt)

**Comment by InfoFractal** [comment] 2020-10-28 15:01
> @mariogasparoni We had updated the BBB server from v2.2.23 to v2.2.28 on last Thursday after which users with a high number of network interfaces (these users were having services like docker running) than a normal user started facing **ICE Negotiation Timeout error 1010**. Last night we redeployed the html5Client with a higher value for **ICE_NEGOTIATION_TIMEOUT** which had resulted in 0 complaints of 1010 error from users.

Where can you set that variable?
Thanks.

**Comment by mariogasparoni** [comment] 2020-10-28 15:06
> @mariogasparoni We had updated the BBB server from v2.2.23 to v2.2.28 on last Thursday after which users with a high number of network interfaces (these users were having services like docker running) than a normal user started facing **ICE Negotiation Timeout error 1010**. Last night we redeployed the html5Client with a higher value for **ICE_NEGOTIATION_TIMEOUT** which had resulted in 0 complaints of 1010 error from users.

That's a great info @krishnateja-ct , which value are you using at this moment ?

**Comment by mariogasparoni** [comment] 2020-10-28 15:19
> > @mariogasparoni We had updated the BBB server from v2.2.23 to v2.2.28 on last Thursday after which users with a high number of network interfaces (these users were having services like docker running) than a normal user started facing **ICE Negotiation Timeout error 1010**. Last night we redeployed the html5Client with a higher value for **ICE_NEGOTIATION_TIMEOUT** which had resulted in 0 complaints of 1010 error from users.
> 
> That's a great info @krishnateja-ct , which value are you using at this moment ?

The current value for ICE_NEGOTIATION_TIMEOUT is 20s, which is believed to be high enough to allow ICE connectivity to be estabilished.
This doens't mean ICE connectivity (which happens during the echo test) will take this long (for most use cases it won't), but this is the max time we wait for ICE connectivity. 
Also, this timeout is triggered after the timeout set by *iceGatheringTimeout* setting. This ICE_NEGOTIATION_TIMEOUT could be moved to settings, though.

@krishnateja-ct , atm i am wondering why the ICE connectivity/negotiation is taking longer than 20s for your server, are you guys using stun or turn setup ? 
Another question, does your use case is related to the problem described [here](https://github.com/bigbluebutton/bigbluebutton/pull/10716) ? (i mention the 1004 error, but 1010 error also could be related to this problem)

**Comment by mariogasparoni** [comment] 2020-10-28 15:42
@InfoFractal You can set it [here](https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bigbluebutton-html5/imports/api/audio/client/bridge/sip.js#L28) . It is default to 20000 (ms) or 20s.
I just read your comment about turn server.
Thanks for the info. That will help when debugging TURN server presence on this scenario.

**Comment by InfoFractal** [comment] 2020-10-28 15:51
> @InfoFractal You can set it [here](https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bigbluebutton-html5/imports/api/audio/client/bridge/sip.js#L28) . It is default to 20000 (ms).
> I just read your comment about turn server.
> Thanks for the info. That will help when debugging TURN server presence on this scenario.
I see thats for the development html5 client, is there no way to alter this setting on instances installed with bbb-install.sh ?
Searching for sip.js gave me 4 results, none of them seem to the correct one.

/usr/share/meteor/bundle/programs/web.browser.legacy/app/compatibility/sip.js
/usr/share/meteor/bundle/programs/web.browser/app/compatibility/sip.js
/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/sip.js
/var/www/bigbluebutton/client/lib/sip.js

**Comment by krishnateja-ct** [comment] 2020-10-28 17:39
> > > @mariogasparoni We had updated the BBB server from v2.2.23 to v2.2.28 on last Thursday after which users with a high number of network interfaces (these users were having services like docker running) than a normal user started facing **ICE Negotiation Timeout error 1010**. Last night we redeployed the html5Client with a higher value for **ICE_NEGOTIATION_TIMEOUT** which had resulted in 0 complaints of 1010 error from users.
> > 
> > 
> > That's a great info @krishnateja-ct , which value are you using at this moment ?
> 
> The current value for ICE_NEGOTIATION_TIMEOUT is 20s, which is believed to be high enough to allow ICE connectivity to be estabilished.
> This doens't mean ICE connectivity (which happens during the echo test) will take this long (for most use cases it won't), but this is the max time we wait for ICE connectivity.
> Also, this timeout is triggered after the timeout set by _iceGatheringTimeout_ setting. This ICE_NEGOTIATION_TIMEOUT could be moved to settings, though.
> 
> @krishnateja-ct , atm i am wondering why the ICE connectivity/negotiation is taking longer than 20s for your server, are you guys using stun or turn setup ?
> Another question, does your use case is related to the problem described [here](https://github.com/bigbluebutton/bigbluebutton/pull/10716) ? (i mention the 1004 error, but 1010 error also could be related to this problem)

@mariogasparoni Currently, we went with a high value of the 60s for TIMEOUT as we wanted to cover the complete base of users getting 1010 error. Please note the users who faced the 1010 error were stuck without an audio connection even after several retries.
The users behind standard network configurations without any additional virtual network interfaces were able to connect audio quickly. Ideally, I would like to revert back to the default value once we get a solution for this.

sip.js was the major upgrade in our BBB update from v2.2.23 to v2.2.28

We do use STUN and TURN servers and BBB servers are configured accordingly for ICE negotiation.

**Comment by mariogasparoni** [comment] 2020-10-28 17:52
@krishnateja-ct Thanks again. 
I get it. As you described, ICE should not take a long time for those 'standard' users. Glad this helps with your case.

At this moment i am trying to get more information to reproduce this problem, and your info (and other's) actually gives me a clue on how to achieve it: having multiple interfaces (VPN may won't be needed on this case), setting a turn/stun server, changing ICE_NEGOTIATION_TIMEOUT ,etc.

Hopefully i'll be able to reproduce it soon

**Comment by mariogasparoni** [comment] 2020-11-16 12:32
@ArminXG can you check if this still happens in 2.2.29 ? Thanks in advance

**Comment by ArminXG** [comment] 2020-11-17 16:44
I can confirm that the ICE error 1010 does not occur with 2.2.29 in my setup any more.
But connecting to echo test takes 35 seconds!

Without the VPN, it takes just 1 second and is faster than ever before.

**Comment by HeikoGr** [comment] 2020-12-02 20:43
i can partially confirm this error too (own system with turn seperate turn server an on test.bigbluebutton.org).

Windows with Chrome and Firefox (on WIFI) works like a charm
Iphone and Ipad with Safari (on WIFI) => error 1010
Iphone (on cellular/LTE) => works like a charm

**Comment by timm2k** [comment] 2020-12-03 08:43
@HeikoGr have a look at https://github.com/bigbluebutton/bigbluebutton/issues/10746#issuecomment-736754904. Can you please test to use TURN instead of TURNS? I've several MAC users with report exact the same behavior but I'm not able to reproduce this with my devices (MacBook Pro; MacOS 10.15.7).

**Comment by HeikoGr** [comment] 2020-12-03 09:33
I deleted the "turns" entry in  /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml and restartet the server. With no benefit - the negotiations still used to be around 30 seconds

**Comment by HeikoGr** [comment] 2020-12-08 16:56
The current openssl update by ubuntu solves this problem for me.

**Comment by mariogasparoni** [comment] 2020-12-08 20:06
How long it takes to connect now ?

**Comment by HeikoGr** [comment] 2020-12-08 20:15
ok. it stays strange. now Chrome and Firefox on Windows sometimes need about 35 seconds. 
Safari on IOS - between 5 an 35 seconds.

is there any logfile i can contribute? and how can i obtain it?

**Comment by HeikoGr** [comment] 2020-12-09 09:25
I disabled the stun server (as discussed here: https://github.com/bigbluebutton/bigbluebutton/issues/8824) - and now there are no more issues.

Is there any negative side effect if there is no more stun server configured? The turn(s) server ist still available.

**Comment by basisbit** [comment] 2020-12-18 00:42
Closing this issue as the problem of the issue starter was solved already.
For anyone with similar problems, I'd suggest following the [instructions for installing a TURNS+STUN server on another server](https://docs.bigbluebutton.org/2.2/setup-turn-server.html). It should be a current linux distribution with a current version of coturn. This usually fixes most network related problems and especially also Apple Safari related issues.

**Closed by basisbit** 2020-12-18 00:42 UTC
Labels: HTML5 Client

**Comment by miladstar77** [comment] 2024-05-14 09:25
i used 
bbb-conf --setip yourdomain.com
then everything works well
