### ISSUE TITLE
BBB 2.3 - others can't see my drawings during drowing

### ISSUE THREAD

**Issue by micpiotrowski** [bigbluebutton/bigbluebutton#12799] opened 2021-07-20 21:11 UTC
After upgrading to 2.3 I noticed that while one of users drawing something on whiteboard (or type a text) other users can't see it until that person release a mouse button (or exit a text field in case of texts).
I think it's a regression comparing to previous version.

**Screenshots**
![Screenshot from 2021-07-20 23-03-07](https://user-images.githubusercontent.com/56402877/126396246-79d128f5-a484-47cb-a611-4e3e02860900.png)

**BBB version:**
BigBlueButton Server 2.3.7 (2394)

Tested on:
**Desktop**
 - OS: Linux
 - Browser Chrome
 - Version 91.0.4472.164

**Smartphone:**
 - Device: Xiaomi Mi 10T Pro 5G
 - OS: Android 10
 - Browser Chrome
 - Version 91.0.4472.164

**Comment by hiroshisuga** [comment] 2021-07-20 21:51
duplicate of #12345

**Closed** 2021-07-21 01:00 UTC
Labels: module: client
