### ISSUE TITLE
Text and Note items get lost on whiteboard transfer from breakout to main meeting room.

### ISSUE THREAD

**Issue by easy-bios** [bigbluebutton/bigbluebutton#17927] opened 2023-05-16 08:09 UTC
**Describe the bug**
If you get a whiteboard from a breakout room, back to the mail room, "Text" and "Note" items will disappear.

**To Reproduce**
1. Start a meeting room
2. Create a breakout room with auto record whiteboard
3. Go to breakout room with clean whiteboard
4. Add some items including Text and Note items
5. Go back to main meeting room and end breakout rooms
6. Select the breakout whiteboard in the main meeting room
7. See Text and Note items are missing

**Expected behavior**
All added items from the breakout room should be safed.

**Actual behavior**
Text and Note items get lost.

**Screenshots**
Whiteboard in Breakout room:
![image](https://github.com/bigbluebutton/bigbluebutton/assets/42430994/bc999d50-8eb8-47fd-87af-2e2ad2564f1a)

Whiteboard in Main room:
![image](https://github.com/bigbluebutton/bigbluebutton/assets/42430994/53437439-9402-4e64-a094-1841e6344889)

**Version**
BigBlueButton Version: 2.6.7
Installed via bbb-install-2.6.sh

**Comment by ffdixon** [comment] 2023-05-16 08:47
We just did a test with BigBlueButton 2.6.7 and the notes came back from the breakout rooms

<img width="460" alt="image" src="https://github.com/bigbluebutton/bigbluebutton/assets/290351/5cc10e8c-d648-4771-a354-0f949af8c442">

What version of BigBlueButton are you running?

**Comment by easy-bios** [comment] 2023-05-16 09:55
BigBlueButton Version: 2.6.7
Installed via bbb-install-2.6.sh

Also Error log is empty.

**Comment by ffdixon** [comment] 2023-05-23 11:19
We just tried the steps on https://demo.bigbluebutton.org/ and the items reappeared.  

<img width="992" alt="image" src="https://github.com/bigbluebutton/bigbluebutton/assets/290351/dd52f235-1ca8-4ad2-86b6-287192ad9aa8">


Can you try to reproduce it on https://demo.bigbluebutton.org/ and let us know the steps.  If you can reproduce, we can take a look at the logs on the server.

**Comment by cschmitt-rma** [comment] 2023-05-31 10:31
We have the same problem on our BBB server (problem was reported while on version 2.6.5, we reproduced it after updating to 2.6.8 and client version 263). We normally use BBB with Moodle 3.9.21 and mod_bigbluebuttonbn plugin v2.4.7, but I also reproduced it in a room initiated via Grennlight 3.0.4. There were also no errors under bbb-conf --watch or --debug. I'll be glad to provide further information and/or try out things to help pinpoint the cause of this bug.

I was also not able to reproduce this problem on your demo server (2.6.8, client version 26**1**). FYI: Our system was upgraded from 2.5, we do some light customizations in /etc/bigbluebutton (e.g. in apply-config.sh) - is it possible to see the ones you do on demo.bigbluebutton.org for comparing them to ours? I'll be glad to provide further information and/or try out things to help pinpoint the cause of this bug.

**Comment by antobinary** [comment] 2023-05-31 13:53
Hi @cschmitt-rma 

demo.bigbluebutton.org is actually a pool of (currently two) servers. They have slightly different configurations.

Any chance you could actually try to reproduce this on test26.bigbluebutton.org ?
What is the version of `bbb-export-annotations` do you have on your server?

This is what we have on test26 right now

```
root@test26:~# dpkg -l | grep bbb-export-annotations
ii  bbb-export-annotations               1:2.6-26                          amd64        BigBlueButton Export Annotations
```

This is what I just tried in test26 (could not reproduce)

```
Client build: 622
BigBlueButton version: 2.6.8
```

breakout:
![Screenshot from 2023-05-31 09-46-37](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/12978f41-f21f-44a8-8d39-c3b8fb9d1382)


conversion
![Screenshot from 2023-05-31 09-46-57](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/5a625583-d26c-4633-8a62-b92ec6bfd8c6)

back in main room
![Screenshot from 2023-05-31 09-47-16](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/f46d2e92-21ea-4517-8fa3-b3dba8f9e681)

**Comment by cschmitt-rma** [comment] 2023-05-31 15:05
In case this is relevant: The error is not occuring in a consistent way regarding sticky notes – during some tries, at least their yellow backgrounds appeared (without text), on some tries nothing at all.

**Comment by antobinary** [comment] 2023-05-31 15:46
Thank you for trying this on the test26 server and for providing more information.

> Could this be an indication of something going wrong during the whiteboard export or are the PDFs themselves always named that cryptically?

We'll take a deeper look.


Just one more question -- when you have sticky notes (for example) in breakout 1, does everyone in that breakout see them? Or just the creator of the sticky notes?

**Comment by danielpetri1** [comment] 2023-06-05 10:33
Hi @cschmitt-rma,
After some investigation, these cryptic filenames are unrelated to the issue. They are used when no whiteboard annotations are present, and the export then defaults to the old download behavior to save time and resources. In 2.7, such downloads have been fixed to use the original filename.

Can you try exporting presentations from the main meeting directly (with text annotations) and seeing whether they annotations appear? If it doesn't work, I suspect you're running into #17303, especially if it's a Hetzner server.  In that case, I would give `apt install libmagickcore-6.q16-6-extra` a try.

**Comment by cschmitt-rma** [comment] 2023-06-05 13:41
Hi @danielpetri1,

thanks for your feedback! 

> Can you try exporting presentations from the main meeting directly (with text annotations) and seeing whether they appear?
Exporting a single slide via the three dots on the top right works - here's the screenshot from BBB:
![export_single-slide-dialogue](https://github.com/bigbluebutton/bigbluebutton/assets/77167566/a23a954e-348c-46e8-96a9-e6bc13afe198)

... and here's the resulting PNG:
![export_single-slide-result](https://github.com/bigbluebutton/bigbluebutton/assets/77167566/d8227e2c-13c5-478a-b8f9-31ab124ff97c)


Exporting the whole presentation via sending it to chat from the plus menu results in a PDF with missing text again:

**[annotated_slides.pdf](https://github.com/bigbluebutton/bigbluebutton/files/11652745/annotated_slides.pdf)**


> If it doesn't work, I suspect you're running into https://github.com/bigbluebutton/bigbluebutton/issues/17303, especially if it's a Hetzner server. In that case, I would give apt install libmagickcore-6.q16-6-extra a try.

We are indeed using a dedicated Hetzner server with this libmagickcore version:
`dpkg -l | grep libmagickcore
ii  libmagickcore-6.q16-6:amd64           8:6.9.10.23+dfsg-2.1ubuntu11.7    amd64        low-level image manipulation library -- quantum depth Q16
` 

After running `apt install libmagickcore-6.q16-6-extra` and `bbb-conf --restart`, text shows up in the PDF export from the main room:
![export_single-slide-dialogue_after-libmagick-extra-install](https://github.com/bigbluebutton/bigbluebutton/assets/77167566/274de9eb-63ad-4dda-83ab-741370cf6f96)
[annotated_slides_after-libmagick-extra-install.pdf](https://github.com/bigbluebutton/bigbluebutton/files/11652808/annotated_slides_after-libmagick-extra-install.pdf)

I then opened two breakout rooms with the option to export the whiteboard after closing it and entered the first breakout room with a test user. The first anomaly was that instead of displaying the current slide including the notes shown above in the breakout room, BBB omitted those notes. I then drew/wrote on the whiteboard in the first breakout room with the test user. After closing the breakout rooms, BBB stated that it couldn't detect any content in both of the whiteboards (which was not true for the one in the first room):
![image](https://github.com/bigbluebutton/bigbluebutton/assets/77167566/ec3599e5-b2fe-4461-90f6-668a745f28c6)

bbb-web.log showed no errors while closing the breakout rooms:
`2023-06-05T15:36:02.397+02:00 INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"duration":900,"record":false,"logCode":"meeting_ended","name":"Konferenzraum 1 (Raum 1)","description":"Meeting has ended.","MeetingId":"XXXXXXX","externalMeetingId":"XXXXXXX",}
2023-06-05T15:36:02.397+02:00 INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"duration":900,"record":false,"logCode":"meeting_removed_from_running","name":"Konferenzraum 1 (Raum 1)","description":"Meeting removed from list of running meetings.","MeetingId":"XXXXXXX","externalMeetingId":"XXXXXXX",}
2023-06-05T15:36:02.397+02:00 INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"duration":900,"record":false,"logCode":"meeting_ended","name":"Konferenzraum 1 (Raum 2)","description":"Meeting has ended.","MeetingId":"XXXXXXX","externalMeetingId":"XXXXXXX",}
2023-06-05T15:36:02.398+02:00 INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"duration":900,"record":false,"logCode":"meeting_removed_from_running","name":"Konferenzraum 1 (Raum 2)","description":"Meeting removed from list of running meetings.","MeetingId":"XXXXXXX","externalMeetingId":"XXXXXXX",}`

**Comment by danielpetri1** [comment] 2023-06-12 11:30
Thank you for the insightful comment after trying the workaround. I'll address each point below:

> Exporting a single slide via the three dots on the top right works
This feature is unrelated to the mechanism used to bring back annotations from breakout rooms. The breakout capturing mechanism is the same used by "Send to chat." So what I'm trying to figure out now is how the send to chat feature worked, but the breakout rooms didn't after installing the dependencies.

> The first anomaly was that instead of displaying the current slide including the notes shown above in the breakout room
That is intended behavior - just the slide is carried over to the breakout room, not the annotations.

> BBB stated that it couldn't detect any content in both of the whiteboards
That is strange, but it helps narrow down the issue. I'm looking into it.

**Comment by danielpetri1** [comment] 2023-06-16 21:19
Brief update: I've started up a Hetzner CPX31 instance running BigBlueButton Server 2.6.9 (1269) and the feature worked out of the box. Here's a sample output file:

[annotated_slides_Hetzner_Fresh_Install.pdf](https://github.com/bigbluebutton/bigbluebutton/files/11775884/annotated_slides_Hetzner_Fresh_Install.pdf)

The output of `dpkg -l | grep libmagickcore` was the same as the one you reported.

Capturing notes and the whiteboard from breakout rooms worked as intended, including the toast detection:

![Working_Toast](https://github.com/bigbluebutton/bigbluebutton/assets/33319791/bdac02b9-bbb4-4f92-aae3-0c829b5974df)

![Screenshot 2023-06-16 at 22 53 14](https://github.com/bigbluebutton/bigbluebutton/assets/33319791/738b898d-382a-47da-8e95-585cfeb6d0fd)

The fact that you could send files to chat while no content was detected in breakout rooms indicates there may be some async/timing issues happening where the breakout room closes before the whiteboard information is stored. I'm looking into possible causes for this.

**Comment by cschmitt-rma** [comment] 2023-06-28 11:56
@danielpetri1 Hello! I just updated our server to 2.6.10, checked to see if the error still occurs and it is gone! Let me know if this settles the matter or if I should conduct further tests and/or provide further details. Thank you and everyone else for your efforts!

**Closed** 2023-07-19 23:10 UTC
Labels: module: core, status: verify
