### ISSUE TITLE
Error 1004 only on android smartphone google chrome

### ISSUE THREAD

**Issue by Amorthis** [bigbluebutton/bigbluebutton#13008] opened 2021-08-16 14:39 UTC
I am getting this error "Failure on call (reason = ICE error) (error 1004)" on  android smartphone in google chrome.
Firefox work normaly.
The problem also occurs on demo.bigbluebutton.org and test.bigbluebutton.org
![WhatsApp Image 2021-08-16 at 17 29 24](https://user-images.githubusercontent.com/78219/129580668-32bd8954-79d8-4cb0-8208-95df48977bba.jpeg)
![WhatsApp Image 2021-08-16 at 17 34 18](https://user-images.githubusercontent.com/78219/129580866-1d548979-823a-4df8-ac56-9fc0303f3cd7.jpeg)
Smartphone Samsung A31,A41 not work in default settings, Samsung A51 Work normal (not default)
Version Google chrome it's the same everywhere 92,0,4515,131
Log Freeswitch 
021-08-16 14:24:53.312613 [DEBUG] switch_core_media.c:5517 Set telephone-event payload to 110@48000
2021-08-16 14:24:53.312613 [DEBUG] mod_opus.c:613 Opus encoder: set bitrate to local settings [72000bps]
2021-08-16 14:24:53.312613 [DEBUG] mod_opus.c:613 Opus encoder: set bitrate to local settings [72000bps]
2021-08-16 14:24:53.312613 [DEBUG] switch_core_media.c:3847 Set Codec sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su opus/48000 20 ms 960 samples 0 bits 1 channels
2021-08-16 14:24:53.312613 [DEBUG] switch_core_codec.c:111 sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su Original read codec set to opus:116
2021-08-16 14:24:53.312613 [DEBUG] switch_core_media.c:4340 Searching for rtp candidate.
2021-08-16 14:24:53.312613 [DEBUG] switch_core_media.c:4340 Searching for rtcp candidate.
2021-08-16 14:24:53.312613 [DEBUG] switch_core_media.c:4387 Look for Relay Candidates as last resort
2021-08-16 14:24:53.312613 [DEBUG] switch_core_media.c:4340 Searching for rtp candidate.
2021-08-16 14:24:53.312613 [DEBUG] switch_core_media.c:4340 Searching for rtcp candidate.
2021-08-16 14:24:53.312613 [DEBUG] switch_core_media.c:4393 sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su no suitable candidates found.
2021-08-16 14:24:53.312613 [DEBUG] switch_core_media.c:5860 Set telephone-event payload to 110@48000
2021-08-16 14:24:53.312613 [DEBUG] switch_core_media.c:5918 sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su Set 2833 dtmf send payload to 110 recv payload to 110
2021-08-16 14:24:53.312613 [NOTICE] switch_channel.c:3908 Hangup sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su [CS_EXECUTE] [INCOMPATIBLE_DESTINATION]
2021-08-16 14:24:53.312613 [DEBUG] switch_core_session.c:2914 sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su skip receive message [APPLICATION_EXEC_COMPLETE] (channel is hungup already)
2021-08-16 14:24:53.312613 [DEBUG] switch_core_state_machine.c:651 (sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su) State EXECUTE going to sleep
2021-08-16 14:24:53.312613 [DEBUG] switch_core_state_machine.c:585 (sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su) Running State Change CS_HANGUP (Cur 2 Tot 4)
2021-08-16 14:24:53.312613 [DEBUG] switch_core_state_machine.c:848 (sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su) Callstate Change RINGING -> HANGUP
2021-08-16 14:24:53.312613 [DEBUG] switch_core_state_machine.c:850 (sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su) State HANGUP
2021-08-16 14:24:53.312613 [DEBUG] mod_sofia.c:453 Channel sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su hanging up, cause: INCOMPATIBLE_DESTINATION
2021-08-16 14:24:53.312613 [DEBUG] mod_sofia.c:598 Responding to INVITE with: 488
2021-08-16 14:24:53.312613 [DEBUG] switch_core_state_machine.c:60 sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su Standard HANGUP, cause: INCOMPATIBLE_DESTINATION
2021-08-16 14:24:53.312613 [DEBUG] switch_core_state_machine.c:850 (sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su) State HANGUP going to sleep
2021-08-16 14:24:53.312613 [DEBUG] switch_core_state_machine.c:620 (sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su) State Change CS_HANGUP -> CS_REPORTING
2021-08-16 14:24:53.312613 [DEBUG] switch_core_state_machine.c:585 (sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su) Running State Change CS_REPORTING (Cur 2 Tot 4)
2021-08-16 14:24:53.312613 [DEBUG] switch_core_state_machine.c:936 (sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su) State REPORTING
2021-08-16 14:24:53.312613 [DEBUG] switch_core_state_machine.c:174 sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su Standard REPORTING, cause: INCOMPATIBLE_DESTINATION
2021-08-16 14:24:53.312613 [DEBUG] switch_core_state_machine.c:936 (sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su) State REPORTING going to sleep
2021-08-16 14:24:53.312613 [DEBUG] switch_core_state_machine.c:611 (sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su) State Change CS_REPORTING -> CS_DESTROY
2021-08-16 14:24:53.312613 [DEBUG] switch_core_session.c:1736 Session 4 (sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su) Locked, Waiting on external entities
2021-08-16 14:24:53.312613 [NOTICE] switch_core_session.c:1754 Session 4 (sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su) Ended
2021-08-16 14:24:53.312613 [NOTICE] switch_core_session.c:1758 Close Channel sofia/external/w_0mkxbakjxpqc_23-bbbID-R@conf2.biot.su [CS_DESTROY]

**Comment by prlanzarin** [comment] 2021-08-16 15:08
@Amorthis Can you please confirm whether cameras/listen only aren't working as well?

**Comment by mariogasparoni** [comment] 2021-08-16 15:38
If not working camera/listen only ,  could you please run this test? 
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

Simply click on 'Gather candidates' button and tell us if you get any candidate from your Samsung device. You may be hitting a bug

**Comment by Amorthis** [comment] 2021-08-16 16:04
I am  testing 2.2 and 2.3 version. In my subdomain conf 2.2.
I see only black area in Webcam zone. Another team don't see my connection. 
when I connect to the problematic device, I see a black square at the place of the video, I hear the rest of the conference participants, but they do not see me or hear me.
this problem has appeared in the last 2 months

**Comment by Amorthis** [comment] 2021-08-16 16:11
In Google Chrome on a41 problem
![Screenshot_20210816-190750_Chrome](https://user-images.githubusercontent.com/78219/129594957-8d701dd6-2c0a-4cf8-b295-29156da61a59.jpg)

In Firefox on a41 no problem
![Screenshot_20210816-190838_Firefox](https://user-images.githubusercontent.com/78219/129595014-bedf9dc7-1deb-4421-a88c-5d19679a5990.jpg)

**Comment by mariogasparoni** [comment] 2021-08-16 16:20
Thanks. It seems you are hitting a bug related to Chrome/Samsung browsers (not all, but specific devices) where the browser hangs at the beginning of media connection (for audio/video/screenshare).

**Comment by mariogasparoni** [comment] 2021-08-16 17:36
I filed a bug including these information.
https://bugs.chromium.org/p/chromium/issues/detail?id=1240237

**Comment by mariogasparoni** [comment] 2021-08-16 19:44
@Amorthis , could you share the device model (or chrome's user agent string) of your A41 device ? 
I am interested in the device model. We already confirmed this is not working for A31 (model: SM-A315G)

You can easily retrieve the device model by accessing this page from your mobile google-chrome:
https://faisalman.github.io/ua-parser-js/

Thanks in advance

**Comment by Amorthis** [comment] 2021-08-16 20:14
Mozilla/5.0 (Linux; Android 11; SM-A415F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Mobile Safari/537.36

And work it 
Mozilla/5.0 (Linux; Android 11; SM-A515F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Mobile Safari/537.36

**Comment by steffen-moser** [comment] 2021-08-17 09:04
No problem with Chrome 92.0.4515.159 on a Huawei P20 Pro. Tested against our BBB 2.3.12 and BBB 2.4-beta3.

**Comment by mariogasparoni** [comment] 2021-08-17 12:07
> No problem with Chrome 92.0.4515.159 on a Huawei P20 Pro. Tested against our BBB 2.3.12 and BBB 2.4-beta3.

Thanks @steffen-moser. 
This seems to be happening with Samsung devices, indeed.

**Comment by steffen-moser** [comment] 2021-08-22 14:12
My wife has just tested with her Samsung Galaxy S9+ (Android 10, browser: Samsung Internet 14.2.3.14) against our platform (BBB 2.4-beta3) and did not encounter any problem. We both tested with WIFI active (which does not mean that the WebRTC traffic necessarily uses WIFI only as long as mobile data is available, too!) and with LTE (WIFI having disabled). I did in parallel the same tests with my Huawei P20 Pro and the above-mentioned version of the Chrome browser. Also no problems. Bi-directional audio and camera worked fine for both devices under both WIFI settings.

Interestingly, our BBB platform is speaking IPv4 only (on purpose, as we ran into problems with IPv6 when it came to IPv6 Privacy Extensions). Could they've been playing a role in the problem @Amortis encountered?

**Comment by ardastan** [comment] 2021-09-22 13:06
Hi
The same error on samsung A31 and chrome browsers.

To the developers: sounds like I have the same issue on the same device and browser for another online meeting application (not bbb). I can't confirm if the error is the same, but the voice connecting issue is in place.

**Comment by pavelvasev** [comment] 2021-12-12 07:44
Same bug in my case. Samsung A22s. Firefox works ok, Chrome fails with same message.

**Comment by Rahu11224** [comment] 2022-01-14 09:23
Sir mera 1004 ice error

**Comment by mariogasparoni** [comment] 2022-02-18 13:51
This is already fixed in Chrome Canary. Let's wait for this to be merged in stable.
More info; https://bugs.chromium.org/p/chromium/issues/detail?id=1240237

**Comment by mariogasparoni** [comment] 2022-03-11 18:33
@Amorthis 
Fixed in chrome 99, for android.
More information here: https://bugs.chromium.org/p/chromium/issues/detail?id=1240237

**Closed by mariogasparoni** 2022-03-11 18:33 UTC
Labels: type: defect, status: accepted, module: audio, module: video
