### ISSUE TITLE
Presentation area has a deadzone

### ISSUE THREAD

**Issue by palimm** [bigbluebutton/bigbluebutton#9348] opened 2020-04-30 07:18 UTC
**Describe the bug**
It's not possible to use the presentation tools in a certain area.

**To Reproduce**
1. As a presenter select e.g. the drawing tool
2. Start drawing at a the center of the area (rectangle (100% width, maybe 15% pixels in height)
3. The cursor changes from the selected tool to a normal cursor
4. No lines will be drawn

**Expected behavior**
Tools should work across the whole area.

**Actual behavior**
You can draw through the area if you start drawing outside of it.

**BBB version (optional):**
BigBlueButton Server 2.2.8 (1887)

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Browser Firefox
 - Version 75

**Comment by bilias** [comment] 2020-04-30 08:15
Yes, I have it also with the last update.
Also the pointer (red dot) is missing in some places.

**Comment by bilias** [comment] 2020-04-30 12:38
In full screen it seems the problem is solved...

**Comment by svergata** [comment] 2020-04-30 12:58
seems to be the overlay a problem only without Webcam

**Comment by Puschek** [comment] 2020-04-30 13:02
Hey, 

it seems to be a problem with the aria for resizing.
`<div class="overlay--nP1TK hideOverlay--Z13uLxg autoWidth--24e2xI fullWidth--Z1RRil3 overlayToTop--1PLUSN react-draggable" style="position: relative; user-select: auto; touch-action: none; margin-left: 0px; margin-right: 0px; transform: translate(0px, 0px); width: 0px; height: 0px; box-sizing: border-box;"><span class="resizeWrapper"><div style="position: absolute; user-select: none; width: 100%; height: 10px; bottom: -5px; left: 0px; cursor: row-resize;"></div></span></div>`

If you delete this block in your browser, you can use the full slide to draw and point. This div is overlaying (without camera activated) over the presentation and creates a dead area. As soon as you start your webcam , this area moves aboth the presenation.

**Comment by robbi5** [comment] 2020-04-30 19:13
Is this already fixed in 2.2.9? I see a commit (https://github.com/bigbluebutton/bigbluebutton/commit/174660a27cf924e0c5ca3ee35fea73648df0ec74), merged yesterday, that tried(?) to fix the draggable Webcam Area Element appearing right over the Presentation Area when no cameras are active:
https://github.com/bigbluebutton/bigbluebutton/pull/9343

**Comment by palimm** [comment] 2020-05-01 04:10
I am not able to reproduce the behavior on BigBlueButton Server 2.2.9 (1898).

Thanks a lot for fixing the issue!

**Comment by ffdixon** [comment] 2020-05-01 04:20
Your welcome!

**Closed by ffdixon** 2020-05-01 04:20 UTC
Labels: HTML5 Client

**Comment by bilias** [comment] 2020-05-01 06:15
thanks, it works now :)
