### ISSUE TITLE
PDF conversion leads to poor quality with LaTeX/TikZ

### ISSUE THREAD

**Issue by daholzfeind** [bigbluebutton/bigbluebutton#11651] opened 2021-03-16 07:45 UTC
**Describe the bug**
When uploading a PDF genearted by pdfLaTeX or XeLaTeX, consisting a pgfplot, the PDF conversion yields to a poor quality (blurry) presentation. 

**To Reproduce**
1. Complile the following source code with either pdfLaTeX or XeLaTeX
```latex
\documentclass{standalone}
\usepackage{pgfplots}
\usepgfplotslibrary{colorbrewer}
\pgfplotsset{compat=newest}
\begin{document}
Hello World! 
\begin{tikzpicture}
  \begin{axis}[
    axis line style={draw=none},
    tick style={draw=none},
    colormap/Blues,
    data cs=polar,
    samples=50,
    domain=0:360,
    y domain=1:10,
    declare function={darkhole(\r)={-exp(-\r)};
      % added functions to calculate cartesian coordinates from polar coordinates
      pol2cartX(\angle,\radius) = \radius * cos(\angle);
      pol2cartY(\angle,\radius) = \radius * sin(\angle); },
    xtick={\empty}, ytick={\empty}, ztick={\empty}, ]
    \addplot3 [surf,shader=flat,draw=black,z buffer=sort] {darkhole(y)};
  \end{axis}
\end{tikzpicture}
\end{document}
```
2. Upload as new presenation

**Expected behavior**
High quality images in converted presentation. 

**Actual behavior**
Low quality blurry images and also text is affected by this. But only if the pgfplot from above is included. 

**Screenshots**
![issue](https://user-images.githubusercontent.com/22816159/111272957-87849800-8633-11eb-8beb-21dc3ce54005.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1
 - Browser Firefox

**Additional context**
--

**Comment by PlumedArcher** [comment] 2021-03-26 10:45
Could reproduce with Google Chrome Version 89.0.4389.90 and BBB built 2.3-alpha8. Without the plot the text becomes high definition again and uploading a simple screenshot of the plot is also high quality again.

**Comment by daholzfeind** [comment] 2021-04-05 19:31
@antobinary May you can add the correct labels to this issue please, since I can't add them on my own. Thank you.

**Comment by pedrobmarin** [comment] 2021-04-14 01:32
Hi @daholzfeind , thanks for your report.

I noticed this might be a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/8835 . Could you confirm that?

**Comment by afdw** [comment] 2021-04-14 08:54
I do not think it is related to #8835.

I think the cause of this problem is how BBB convert slides. It is described [here](https://docs.bigbluebutton.org/2.2/architecture.html#presentation-conversion-flow). What it does is it first tries to convert PDF to SVG. But [if the number of `<path>` elements is greater than a certain limit](https://github.com/bigbluebutton/bigbluebutton/blob/5189abb225247290d1954e10827853d5fc022b66/bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java#L118), it stops and instead produces a PNG file embedded in SVG.

The [default limit seems to be 800](https://github.com/bigbluebutton/bigbluebutton/blob/5189abb225247290d1954e10827853d5fc022b66/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L83), and the number of `<path>` elements in the generated SVG file (which you can by executing `pdftocairo -svg main.pdf main.svg`) is 14418, which is 18 times bigger

So this means that you should be able to solve the problem in your case by increasing this limit.

But this poses 2 question:
1. Is there something unusual about the SVG file generated which might have cause it to be so big? Can we generate smaller SVG files?
2. Why does the fallback PNG file have such a small resolution?

Here is what I think:
1. SVG looks sensible, there only thing that stands out to me is that each filled or stroked path is enclosed in 2 clips. This might be optimized, but it will not make the total number or `<path>` elements smaller than 800 I think.
2. My guess is that currently the PNG dimensions depend on the PDF dimensions, and as they are small, the resulting fallback PNG file also has low resolution. I think the solution to this problem is to always generate the PNG files of the same resolution regardless of the original PDF. Or perhaps take the maximum of the two.

**Comment by pedrobmarin** [comment] 2021-04-14 11:12
Thanks for such detailed feedback, @afdw ! @GhaziTriki @ritzalam any thoughts on this topic?

**Comment by daholzfeind** [comment] 2021-04-14 12:18
> Hi @daholzfeind , thanks for your report.
> 
> I noticed this might be a duplicate of #8835 . Could you confirm that?

Thanks for you answer. I encountered https://github.com/bigbluebutton/bigbluebutton/issues/8835 in a different setting. My solution to that problem was compiling the Beamer slides with XeLaTeX. 

In this Issue here, compiling with XeLaTeX, it doesn't solve my issue here. That's why I mentioned it explicitly above with the code example. 

Thank You @afdw , for your insightful answer.

**Comment by gustavotrott** [comment] 2021-04-19 19:15
I just sent PR #12087 that will fix this issue.

By default `svgPresentationResolutionPpi` will be 300. The quality will be much better than before.
But you can set it to 500 or more if you want a very high quality for the presentation.

**Closed** 2021-04-19 20:07 UTC
Labels: component: presentation, module: web, status: verify, type: enhancement
