### ISSUE TITLE
Create Breakout room option can disappear after breakout rooms are ended

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#16258] opened 2022-12-21 14:07 UTC
**Describe the bug**
As a moderator, after creating breakout rooms, joining them, then ending them, the gear icon does not show the Create breakout room option.

**To Reproduce**
See video

https://user-images.githubusercontent.com/290351/208923761-92581c59-5267-4d28-aee5-da1840c38cec.mp4

**Expected behavior**
The Create breakout option appears after the breakout rooms close.

**Actual behavior**
The Create breakout option does not reappear until triggering a refresh of the Users pane.

**BBB version:**
```
BigBlueButton Server 2.6.0-beta.3 (630)
                    Kernel version: 5.4.0-128-generic
                      Distribution: Ubuntu 20.04.5 LTS (64-bit)
                            Memory: 8148 MB
                         CPU cores: 4
```

**Smartphone (please complete the following information):**
Reproduced this issue on Chrome

**Additional context**
Closing and hiding the users list will restore the Create breakout rooms option.

**Comment by antobinary** [comment] 2022-12-21 17:54
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/16118

**Closed by antobinary** 2022-12-21 17:54 UTC
Labels: module: client
