### ISSUE TITLE
[3.0.0-alpha.4] No notification when conference ends

### ISSUE THREAD

**Issue by sergey-balychev** [bigbluebutton/bigbluebutton#19686] opened 2024-02-24 14:32 UTC
**Describe the bug**
At the end of the conference, the conference moderator has a blue screen without notification of the end of the conference and a link to the learning-analytics-dashboardl. (tested on BigBlueButton Server version 3.0.0-alpha4 (236))

**To Reproduce**
1. Go to 'Start'
2. Click on 'End the conference'
3. I just have a blue screen with the text "Meeting has ended  | 410 " without notification of the end of the conference and links to learning-analytics-dashboard , see screenshot

**Expected behavior**
a notification about the end of the conference and a link to the learning-analytics-dashboard will appear

**Actual behavior**
the notification about the end of the conference and the link to the learning-analytics-dashboard did not appear

**Screenshots**
![image](https://github.com/bigbluebutton/bigbluebutton/assets/63751589/9967a617-e053-47d6-96fc-bd0ef9149060)

**BBB version:**
```
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 3.0.0-alpha.4 (483)
```

**Additional context**
The same problem is now visible on the website https://test30.bigbluebutton.org
_Build: 168
Version BigBlueButton: 3.0.0-alpha.4_

And there has been such a problem before: 
- https://github.com/bigbluebutton/bigbluebutton/issues/14553
- https://github.com/bigbluebutton/bigbluebutton/issues/14545

**Comment by vasylOstrovskyi** [comment] 2024-03-08 16:03
duplicate of #19527

**Comment by antobinary** [comment] 2024-03-08 16:12
Thank you for reporting! Also thanks to @vasylOstrovskyi for spotting that there is a very similar report!

**Comment by antobinary** [comment] 2024-03-08 16:12
Merging into #19527

**Closed by antobinary** 2024-03-08 16:12 UTC
Labels: module: client
