### ISSUE TITLE
bbb-webrtc-sfu exception when sharing webcam.

### ISSUE THREAD

**Issue by elsemieni** [bigbluebutton/bigbluebutton#5376] opened 2018-04-23 15:10 UTC
I made a clean install of BigBlueButton 2.0 (following tutorial on BBB page, installed recommended versions of NodeJS (v8.11.1) /Mongo (v3.4.14) with the steps mentioned there) with HTML5 on Ubuntu 16.04 (64bits) LTS local server. It seems to everything working fine testing with HTML5 demo. However, when I try to share a webcam, after 10 seconds the clients shows "_Error on Sharing Webcam_" error on screen.

The browser inspect tool log shows the following error:
`CLIENT LOG (ERROR):  Camera share has not suceeded in 10000
6a30cc1eb29b9b8cc7a4e91aab2d50b675c10e7c.js:145:665566
CLIENT LOG (INFO):  Unsharing webcam
6a30cc1eb29b9b8cc7a4e91aab2d50b675c10e7c.js:145:665566
CLIENT LOG (DEBUG):  ------ Websocket connection closed.
6a30cc1eb29b9b8cc7a4e91aab2d50b675c10e7c.js:145:665566
CLIENT LOG (DEBUG):   [camera] Webcam disconnected, will try re-share webcam later.
`

And bbb-webrtc-sfu log shows throws the following: 
```
2018-04-23T14:52:50.515Z - info: [WebsocketConnectionManager] New connection with id [ 0 ]
2018-04-23T14:52:54.922Z - info: [WebsocketConnectionManager] Closed connection on [0]
2018-04-23T14:52:56.567Z - info: [WebsocketConnectionManager] New connection with id [ 1 ]
2018-04-23T14:53:13.867Z - info: [VideoManager] Received message [start] from connection 1
2018-04-23T14:53:13.868Z - info: [video] Starting video instance for w_6i6aljp5uadq
2018-04-23T14:53:13.868Z - info: [mcs-controller] Join room => w_6i6aljp5uadq as SFU
2018-04-23T14:53:13.869Z - info: [mcs-controller] Creating new room with ID w_6i6aljp5uadq
2018-04-23T14:53:13.870Z - info: [mcs-controller] Creating a new SFU user at room w_6i6aljp5uadq
2018-04-23T14:53:13.870Z - info: [mcs-controller] Resolving user shy-sound-tcmXcjw
2018-04-23T14:53:13.870Z - info: [video] MCS join for w_6i6aljp5uadq returned shy-sound-tcmXcjw
2018-04-23T14:53:13.871Z - info: [mcs-controller] Publish from user shy-sound-tcmXcjw to room w_6i6aljp5uadq
2018-04-23T14:53:13.871Z - info: [mcs-controller] Fetched user shy-sound-tcmXcjw
2018-04-23T14:53:13.887Z - info: [mcs-sfu-user] Added new SDP session floral-dust-pN5nTMG to user shy-sound-tcmXcjw
reconnect to server 0 100 undefined
reconnect to server 1 100 undefined
reconnect to server 2 200 undefined
Trace: ReferenceError: isError is not defined
    at MediaServer._handleError (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/media/media-server.js:329:5)
    at KurentoClient.mediaServerClient (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/media/media-server.js:45:24)
    at Promise.callback2 (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/promisecallback/index.js:27:25)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at Promise.callback2 (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/promisecallback/index.js:32:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2018-04-23T14:53:14.338Z - error: [VideoProcess] Unhandled Rejection at: Promise Promise {
  <rejected> ReferenceError: isError is not defined
    at MediaServer._handleError (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/media/media-server.js:329:5)
    at KurentoClient.mediaServerClient (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/media/media-server.js:45:24)
    at Promise.callback2 (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/promisecallback/index.js:27:25)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7),
  domain: [Getter/Setter],
  _events: [Getter/Setter],
  _eventsCount: [Getter/Setter],
  _maxListeners: [Getter/Setter],
  beginTransaction: [Function: bound ],
  endTransaction: [Function: bound ],
  transaction: [Function: bound ],
  getMediaobjectById: [Function],
  create: [Function: bound ],
  close: [Function],
  connect: [Function],
  getServerManager: [Function],
  setMaxListeners: [Function: setMaxListeners],
  getMaxListeners: [Function: getMaxListeners],
  emit: [Function: emit],
  addListener: [Function: addListener],
  on: [Function: addListener],
  prependListener: [Function: prependListener],
  once: [Function: once],
  prependOnceListener: [Function: prependOnceListener],
  removeListener: [Function: removeListener],
  removeAllListeners: [Function: removeAllListeners],
  listeners: [Function: listeners],
  listenerCount: [Function: listenerCount],
  eventNames: [Function: eventNames] } reason: ReferenceError: isError is not defined
    at MediaServer._handleError (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/media/media-server.js:329:5)
    at KurentoClient.mediaServerClient (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/media/media-server.js:45:24)
    at Promise.callback2 (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/promisecallback/index.js:27:25)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
Tried reinstalling bbb-webrtc-sfu without any luck. Also tried to trace that error log, but looks kinda complicated to trace it. Also sounds strange to me seeing that online demo works fine. Demo uses a particular build to test it in my dev place?

Any ideas?
Thanks!

**Comment by ffdixon** [comment] 2018-06-16 23:01
@elsemieni Can you update your server to the latest build of BigBlueButton 2.0-beta and test this again.

**Comment by umeshs88** [comment] 2018-07-12 12:39
Hey Fred! I configured it many times since yesterday! Getting same error. 

Any pointers? bbb-conf --status is all good:

red5: active
tomcat7: active
nginx: active
freeswitch: active
redis-server.service: active
bbb-apps-akka: active
bbb-transcode-akka: active
bbb-fsesl-akka: active
mongod: active
bbb-html5: active
bbb-webrtc-sfu: active
kurento-media-server: active

**Comment by prlanzarin** [comment] 2018-07-12 14:52
Hey @umeshs88,

Are you seeing exactly that same exception reported here? Can you paste your bbb-webrtc-sfu log when trying to share a webcam?

**Comment by antobinary** [comment] 2018-07-12 14:58
And also please specify the build number of bbb-webrtc-sfu by copy-pasting here the output of `dpkg -l | grep bbb-webrtc-sfu'

**Comment by umeshs88** [comment] 2018-07-13 05:53
@prlanzarin , this is what logs says:

{"level":"info","message":"[WebsocketConnectionManager] New connection with id [ 2 ]","timestamp":"2018-07-13T05:51:08.174Z"}
{"level":"info","message":"[VideoManager] Received message [start] from connection 2w_nancadvo3spb-share","timestamp":"2018-07-13T05:51:08.959Z"}
{"level":"info","message":"[video] Starting video instance for 2w_nancadvo3spb-share","timestamp":"2018-07-13T05:51:08.959Z"}
{"level":"info","message":"[mcs-controller] Join room => 183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1531461031637 as SFU","timestamp":"2018-07-13T05:51:08.961Z"}
{"level":"info","message":"[mcs-controller] Creating new room with ID 183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1531461031637","timestamp":"2018-07-13T05:51:08.961Z"}
{"level":"info","message":"[mcs-controller] Creating a new SFU user at room 183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1531461031637","timestamp":"2018-07-13T05:51:08.962Z"}
{"level":"info","message":"[mcs-controller] Resolving user bitter-bush-N38Bxv3","timestamp":"2018-07-13T05:51:08.962Z"}
{"level":"info","message":"[video] MCS join for 2w_nancadvo3spb-share returned bitter-bush-N38Bxv3","timestamp":"2018-07-13T05:51:08.962Z"}
{"level":"info","message":"[mcs-controller] Publish from user bitter-bush-N38Bxv3 to room 183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1531461031637","timestamp":"2018-07-13T05:51:08.962Z"}
{"level":"info","message":"[mcs-controller] Fetched user bitter-bush-N38Bxv3","timestamp":"2018-07-13T05:51:08.962Z"}
{"level":"info","message":"[SdpSession] Session is using the Kurento adapter","timestamp":"2018-07-13T05:51:08.962Z"}
{"descriptor":"v=0\r\no=mozilla...THIS_IS_SDPARTA-61.0.1 8530349431125796181 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=sendrecv\r\na=fingerprint:sha-256 E7:8A:24:4D:1C:F9:4E:69:E2:49:0E:F2:9D:$
{"level":"info","message":"[mcs-sfu-user] Added new SDP session purple-silence-6Wr8mOk to user bitter-bush-N38Bxv3","timestamp":"2018-07-13T05:51:08.963Z"}
{"meta":false,"level":"info","message":"[Video] RecordingStatusReply userId: w_nancadvo3spb recorded:","timestamp":"2018-07-13T05:51:08.967Z"}
{"level":"info","message":"[mcs-media] Created [WebRtcEndpoint] media element: c9f0660b-24a8-473f-900d-fabf38268b18_kurento.MediaPipeline/bdcc7e3a-6c50-4bf2-bdd5-ef5fd8ad5f57_kurento.WebRt$
{"level":"info","message":"[mcs-media-session] New media session purple-silence-6Wr8mOk in room 183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1531461031637 started with media server endpoint c9$
{"level":"info","message":"[mcs-media] Gathering ICE candidates for c9f0660b-24a8-473f-900d-fabf38268b18_kurento.MediaPipeline/bdcc7e3a-6c50-4bf2-bdd5-ef5fd8ad5f57_kurento.WebRtcEndpoint",$
{"level":"info","message":"[mcs-media] Triggered ICE gathering for c9f0660b-24a8-473f-900d-fabf38268b18_kurento.MediaPipeline/bdcc7e3a-6c50-4bf2-bdd5-ef5fd8ad5f57_kurento.WebRtcEndpoint","$
{"level":"info","message":"[video] MCS call for user bitter-bush-N38Bxv3 returned purple-silence-6Wr8mOk","timestamp":"2018-07-13T05:51:09.025Z"}
{"level":"info","message":"[WebsocketConnectionManager] Closed connection on [2]","timestamp":"2018-07-13T05:51:23.999Z"}
{"level":"info","message":"[VideoManager] Closing sessions of connection 2","timestamp":"2018-07-13T05:51:24.000Z"}
{"level":"info","message":"[VideoManager] Stopping session 2w_nancadvo3spb-share","timestamp":"2018-07-13T05:51:24.000Z"}
{"level":"info","message":"[video] Stopping video session bitter-bush-N38Bxv3 at room 183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1531461031637","timestamp":"2018-07-13T05:51:24.000Z"}
{"level":"info","message":"[mcs-controller] User => bitter-bush-N38Bxv3 wants to leave ","timestamp":"2018-07-13T05:51:24.000Z"}
{"level":"info","message":"[mcs-sfu-user] User sessions will be killed","timestamp":"2018-07-13T05:51:24.000Z"}
{"level":"info","message":"[mcs-sfu-user] Stopping session => purple-silence-6Wr8mOk","timestamp":"2018-07-13T05:51:24.000Z"}
{"level":"info","message":"[mcs-media] Releasing endpoint c9f0660b-24a8-473f-900d-fabf38268b18_kurento.MediaPipeline/bdcc7e3a-6c50-4bf2-bdd5-ef5fd8ad5f57_kurento.WebRtcEndpoint from room 1$
{"level":"info","message":"[mcs-media] Pipeline has a total of 0 active elements","timestamp":"2018-07-13T05:51:24.003Z"}
{"level":"info","message":"[mcs-media-session] Session purple-silence-6Wr8mOk stopped with status STOPPED","timestamp":"2018-07-13T05:51:24.006Z"}
{"level":"info","message":"[mcs-sfu-user] Session  purple-silence-6Wr8mOk stopped, cleaning it...","timestamp":"2018-07-13T05:51:24.006Z"}

**Comment by umeshs88** [comment] 2018-07-13 05:55
@antobinary , 

dpkg -l | grep bbb-webrtc-sfu shows:
ii  bbb-webrtc-sfu                        1:2.0.0-52                                amd64        BigBlueButton WebRTC SFU

**Comment by umeshs88** [comment] 2018-07-13 06:02
FYI, i tried using couple of public STUN servers from https://kurento.readthedocs.io/en/stable/doc/admin_guide.html#installation. getting same error every time!

**Comment by umeshs88** [comment] 2018-07-13 06:05
about:webrtc in firefox shows following:

(stun/INFO) STUN-CLIENT(consent): Received response; processing

(ice/INFO) ICE(PC:1531461589049000 (id=2147483660 url=https://classroom.xornor.co/html5client/users))/STREAM(0-1531461589049000 (id=2147483660 url=https://classroom.xornor.co/html5client/users) aLevel=0)/COMP(1): Consent refreshed

(stun/INFO) STUN-CLIENT(consent): Received response; processing

(ice/INFO) ICE(PC:1531461589049000 (id=2147483660 url=https://classroom.xornor.co/html5client/users))/STREAM(0-1531461589049000 (id=2147483660 url=https://classroom.xornor.co/html5client/users) aLevel=0)/COMP(1): Consent refreshed

(ice/INFO) z:/build/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

(ice/INFO) z:/build/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

(ice/WARNING) z:/build/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:617 function nr_socket_multi_tcp_listen failed with error 3

(ice/WARNING) ICE(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users)): failed to create passive TCP host candidate: 3

(ice/INFO) z:/build/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

(ice/INFO) z:/build/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

(ice/WARNING) z:/build/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:617 function nr_socket_multi_tcp_listen failed with error 3

(ice/WARNING) ICE(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users)): failed to create passive TCP host candidate: 3

(stun/INFO) STUN-CLIENT(srflx(IP4:192.168.1.16:60946/UDP|stun.l.google.com:19302)): Received response; processing

(stun/INFO) STUN-CLIENT(srflx(IP4:192.168.1.16:60947/UDP|stun.l.google.com:19302)): Received response; processing

(stun/INFO) STUN-CLIENT(srflx(IP4:192.168.1.16:60946/UDP|stun3.l.google.com:19302)): Received response; processing

(stun/INFO) STUN-CLIENT(srflx(IP4:192.168.1.16:60947/UDP|stun3.l.google.com:19302)): Received response; processing

(ice/NOTICE) ICE(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users)): peer (PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default) no streams with non-empty check lists

(ice/NOTICE) ICE(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users)): peer (PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default) no streams with pre-answer requests

(ice/NOTICE) ICE(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users)): peer (PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default) no checks to start

(ice/INFO) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default)/ICE-STREAM(0-1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users) aLevel=0): Starting check timer for stream.

(ice/WARNING) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default): no pairs for 0-1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users) aLevel=0

(ice/NOTICE) ICE(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users)): peer (PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default) is now checking

(ice/INFO) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default)/ICE-STREAM(0-1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users) aLevel=0): Starting check timer for stream.

(ice/WARNING) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default): no pairs for 0-1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users) aLevel=0

(ice/INFO) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default)/ICE-STREAM(0-1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users) aLevel=0): Starting check timer for stream.

(ice/WARNING) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default): no pairs for 0-1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users) aLevel=0

(ice/INFO) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default)/CAND-PAIR(wMAu): setting pair to state FROZEN: wMAu|IP4:192.168.1.16:60946/UDP|IP4:172.31.47.202:30358/UDP(host(IP4:192.168.1.16:60946/UDP)|candidate:4 1 UDP 2013266430 172.31.47.202 30358 typ host)

(ice/INFO) ICE(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users))/CAND-PAIR(wMAu): Pairing candidate IP4:192.168.1.16:60946/UDP (7e7f00ff):IP4:172.31.47.202:30358/UDP (780001fe) priority=8646913479229178367 (780001fefcfe01ff)

(ice/INFO) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default)/ICE-STREAM(0-1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users) aLevel=0): Starting check timer for stream.

(ice/INFO) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default)/CAND-PAIR(wMAu): setting pair to state WAITING: wMAu|IP4:192.168.1.16:60946/UDP|IP4:172.31.47.202:30358/UDP(host(IP4:192.168.1.16:60946/UDP)|candidate:4 1 UDP 2013266430 172.31.47.202 30358 typ host)

(ice/INFO) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default)/CAND-PAIR(wMAu): setting pair to state IN_PROGRESS: wMAu|IP4:192.168.1.16:60946/UDP|IP4:172.31.47.202:30358/UDP(host(IP4:192.168.1.16:60946/UDP)|candidate:4 1 UDP 2013266430 172.31.47.202 30358 typ host)

(ice/INFO) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default)/CAND-PAIR(HeFO): setting pair to state FROZEN: HeFO|IP4:192.168.1.16:52996/TCP|IP4:172.31.47.202:31701/TCP(host(IP4:192.168.1.16:52996/TCP) active|candidate:6 1 TCP 1010827775 172.31.47.202 31701 typ host tcptype passive)

(ice/INFO) ICE(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users))/CAND-PAIR(HeFO): Pairing candidate IP4:192.168.1.16:52996/TCP (7d7fc0ff):IP4:172.31.47.202:31701/TCP (3c4001ff) priority=4341472239724495359 (3c4001fffaff81ff)

(ice/WARNING) Peer offered candidates for disabled local component

(ice/WARNING) Peer offered candidates for disabled local component

(ice/INFO) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default)/CAND-PAIR(HeFO): setting pair to state WAITING: HeFO|IP4:192.168.1.16:52996/TCP|IP4:172.31.47.202:31701/TCP(host(IP4:192.168.1.16:52996/TCP) active|candidate:6 1 TCP 1010827775 172.31.47.202 31701 typ host tcptype passive)

(ice/INFO) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default)/CAND-PAIR(HeFO): setting pair to state IN_PROGRESS: HeFO|IP4:192.168.1.16:52996/TCP|IP4:172.31.47.202:31701/TCP(host(IP4:192.168.1.16:52996/TCP) active|candidate:6 1 TCP 1010827775 172.31.47.202 31701 typ host tcptype passive)

(generic/INFO) Write buffer not empty for IP4:172.31.47.202:31701/TCP 98 - already armed (@000002098195CDF4), not connected

(ice/WARNING) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default): no pairs for 0-1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users) aLevel=0

(ice/WARNING) Peer offered candidates for disabled local component

(ice/WARNING) Peer offered candidates for disabled local component

(ice/WARNING) Peer offered candidates for disabled local component

(ice/WARNING) Peer offered candidates for disabled local component

(stun/INFO) STUN-CLIENT(consent): Received response; processing

(ice/INFO) ICE(PC:1531461589049000 (id=2147483660 url=https://classroom.xornor.co/html5client/users))/STREAM(0-1531461589049000 (id=2147483660 url=https://classroom.xornor.co/html5client/users) aLevel=0)/COMP(1): Consent refreshed

(ice/INFO) ICE(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users)): peer (PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default) Trickle grace period is over; marking every component with only failed pairs as failed.

(stun/INFO) STUN-CLIENT(consent): Received response; processing

(ice/INFO) ICE(PC:1531461589049000 (id=2147483660 url=https://classroom.xornor.co/html5client/users))/STREAM(0-1531461589049000 (id=2147483660 url=https://classroom.xornor.co/html5client/users) aLevel=0)/COMP(1): Consent refreshed

(stun/INFO) STUN-CLIENT(wMAu|IP4:192.168.1.16:60946/UDP|IP4:172.31.47.202:30358/UDP(host(IP4:192.168.1.16:60946/UDP)|candidate:4 1 UDP 2013266430 172.31.47.202 30358 typ host)): Timed out

(ice/INFO) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default)/CAND-PAIR(wMAu): setting pair to state FAILED: wMAu|IP4:192.168.1.16:60946/UDP|IP4:172.31.47.202:30358/UDP(host(IP4:192.168.1.16:60946/UDP)|candidate:4 1 UDP 2013266430 172.31.47.202 30358 typ host)

(stun/INFO) STUN-CLIENT(consent): Received response; processing

(ice/INFO) ICE(PC:1531461589049000 (id=2147483660 url=https://classroom.xornor.co/html5client/users))/STREAM(0-1531461589049000 (id=2147483660 url=https://classroom.xornor.co/html5client/users) aLevel=0)/COMP(1): Consent refreshed

(stun/INFO) STUN-CLIENT(HeFO|IP4:192.168.1.16:52996/TCP|IP4:172.31.47.202:31701/TCP(host(IP4:192.168.1.16:52996/TCP) active|candidate:6 1 TCP 1010827775 172.31.47.202 31701 typ host tcptype passive)): Timed out

(ice/INFO) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default)/CAND-PAIR(HeFO): setting pair to state FAILED: HeFO|IP4:192.168.1.16:52996/TCP|IP4:172.31.47.202:31701/TCP(host(IP4:192.168.1.16:52996/TCP) active|candidate:6 1 TCP 1010827775 172.31.47.202 31701 typ host tcptype passive)

(ice/INFO) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default)/STREAM(0-1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users) aLevel=0)/COMP(1): All pairs are failed, and grace period has elapsed. Marking component as failed.

(ice/INFO) ICE-PEER(PC:1531461802868000 (id=2147483660 url=https://classroom.xornor.co/html5client/users):default): all checks completed success=0 fail=1

(generic/ERR) Error from TCPSocketChild: type: ConnectionRefusedError, name: Network

+++++++ END ++++++++

**Comment by prlanzarin** [comment] 2018-07-13 17:35
@umeshs88 Thanks for the detailed logs. The problem is indeed within the ICE exchange process because Firefox is unable to find a valid pair. And you're right, the remote candidates being listed with only the local IP address is one of the symptons.

Let's try a bunch of steps:
  - Install the package `stuntman-client` in your server, and then perform the following test with this STUN server (Google's public one): `stunclient --mode full --localport <some_free_udp_port> 74.125.134.127 19302`.
  - If everything goes right, set it up on Kurento following the guide in this page (http://doc-kurento.readthedocs.io/en/stable/user/installation.html#stun-and-turn-servers). Please use this instead of the Fiware one you sent because that one might be severely outdated. If stuntman fails, post the result here and make sure the firewall your server is in has port 19302 and an appropriate range of UDP ports open.
  - With that STUN server set up, try it again. If it doesn't work, there might be some issue resolving the IP address in the region you're in. Try finding a STUN server that suits your setup, or you might wanna consider setting up a coturn server (https://github.com/coturn/coturn) in a publicly available server and try that one out if it doesn't work.

Besides that, we should have an update coming soon that enables client-side configuration of STUN and TURN servers so you can determine which STUN server works for you best and configure it both in the server and clients. Moreover, be aware that if a peer is behind symmetric NAT and the server is either behind symmetric NAT or port-restricted NAT, you'll be needing a TURN server to make it work properly.

**Comment by umeshs88** [comment] 2018-07-14 11:39
@prlanzarin , i stunclient is showing following on console while connecting to 74.125.134.127 on 19302

Binding test: success
Local address: 172.31.47.202:32000
Mapped address: 35.155.213.38:32000
Behavior test: fail
Filtering test: fail

This still means some problem, right?

I have my setup on AWS EC2/Ubuntu 16.04, have opened all port for now to check this issue. Tried more stun servers with stun client but others are not even getting through binding test, seems like finding a stun server which connects from my location is a challenge. 

Will try and setup coturn now.

**Comment by fcecagno** [comment] 2018-07-14 13:23
Which AWS availability zone are you using?

**Comment by umeshs88** [comment] 2018-07-15 13:59
Its in US West (Oregon) @fcecagno

**Comment by prlanzarin** [comment] 2018-08-28 15:08
Hi Roger,

What BBB version are you on? From that log you posted, it seems like a *really* old one. Would you care to update it? To my knowledge, that exception has been fixed for a time now.

**Comment by rogercong** [comment] 2018-08-29 14:33
Yes, after redo the update and solve it. Thanks

**Comment by WaelSan** [comment] 2018-10-07 13:30
Hello umeshs88,

Did you find a solution for your problem? 
Because, I have the same as yours.

Thank you

**Comment by ffdixon** [comment] 2018-10-07 21:01
Hi @WaelSan, what version of BigBlueButton are you running?

**Comment by WaelSan** [comment] 2018-10-08 08:01
Hi Fred,

I am running the last version 2.0 RC6
The audio conference is great but when sharing the camera we get this error :  
"error 1107 ice negotiation failed"

Bellow the current configuration :
```
bbb-conf --status
red5: active
tomcat7: active
nginx: active
freeswitch: active
redis-server.service: active
bbb-apps-akka: active
bbb-transcode-akka: active
bbb-fsesl-akka: active
mongod: active
bbb-html5: active
bbb-webrtc-sfu: active
kurento-media-server: active
``` 

```
 dpkg -l | grep bbb-webrtc-sfu
ii  bbb-webrtc-sfu                        1:2.0.0-70                                 amd64        BigBlueButton WebRTC SFU

```

```

dpkg -l | egrep 'bbb|kurento|kms'
ii  bbb-apps                              1:2.0.0-52                                 amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.0.0-147                                  all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.0.0-41                                 amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.0.0-14                                 amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.0.0-29                                 amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.0.0-8                                  amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.0.0-384                                amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.0.0-79                                 amd64        BigBlueButton configuration utilities
ii  bbb-freeswitch-core                   2:2.0.0-47                                 amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-9                                  amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.0.0-27                                   all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.0.0-468                                amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-4                                  amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.0.0-27                                 amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.0.0-32                                 amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.8-40                                 amd64        The Red5 server for BigBlueButton
ii  bbb-swftools                          1:0.9.2-2                                  amd64        The swftools files for BigBlueButton
ii  bbb-transcode-akka                    2.0.0-6                                    all          BigBlueButton Transcoder
ii  bbb-web                               1:2.0.0-87                                 amd64        BigBlueButton API
ii  bbb-webrtc-sfu                        1:2.0.0-70                                 amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.0.0-13                                 amd64        Open source web conferencing platform (bbb)
ii  kms-core                              6.7.1+201806211620.27.ddca087              amd64        Kurento Core module
ii  kms-elements                          6.7.0+201806211634.24.3923f1a              amd64        Kurento Elements module
ii  kms-filters                           6.7.0+201806211640.18.d3dac3a              amd64        Kurento Filters module
ii  kms-jsonrpc                           6.7.0+201806190347.8.8357b5e               amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                            1.6.3.xenial.20170725151047.d78deb7        amd64        Kurento jsoncpp library
ii  kurento-media-server                  6.7.0+201806281201.25.cc67c2e              amd64        Kurento Media Server

```

```
netstat -putan | grep 8888
tcp6       0      0 :::8888                 :::*                    LISTEN      15897/kurento-media

```

```

ps aux | grep kurento
kurento  15897  0.0  0.2 312476 22896 ?        Ssl  07:10   0:00 /usr/bin/kurento-media-server --gst-debug-level=3 --gst-debug=3,Kurento*:4,kms*:4,KurentoWebSocketTransport:5
root     23878  0.0  0.0  12944  1088 pts/0    S+   08:01   0:00 grep --color=auto kurento

```

**Comment by hirsebrand** [comment] 2018-10-23 13:58
Hey,

Any news on that?
I am facing the same troubles as @WaelSan.

Cheers

**Comment by netlabs** [comment] 2019-01-23 07:17
Hey guys any update on this because I am facing the same.

Pls do help me @umeshs88 @prlanzarin @elsemieni @antobinary

**Comment by dancinglone** [comment] 2019-04-13 18:30
I am coming across with such issue too, any news? @umeshs88 @prlanzarin @elsemieni @antobinary @netlabs

**Comment by ffdixon** [comment] 2019-04-14 01:45
Hi @netlabs and @dancinglone,

Can you try installing BigBlueButton 2.2-beta and let us know if your getting the same error.  See

  http://docs.bigbluebutton.org/2.2/install.html

We've done more work in 2.2-beta for sharing of webcams and we're interested if you encounter the same issue in this release.

**Comment by ffdixon** [comment] 2019-11-04 09:49
Hi Guys, closing this issue as there was no update for testing again.  If you encounter an issue with sharing webcams, first test on 

  https://demo.bigbluebutton.org/

and if it doesn't work, let us know, see

  https://bigbluebutton.org/support

**Closed by ffdixon** 2019-11-04 09:49 UTC
