### ISSUE TITLE
Users are not removed from participants list

### ISSUE THREAD

**Issue by mokazemi** [bigbluebutton/bigbluebutton#15198] opened 2022-06-16 14:58 UTC
**Describe the bug**
When a user leaves the meeting, it's not removed from users list.

**To Reproduce**
1. Start a meeting and join with a few users (On of them with Firefox)
2. Leave the meeting with one of them (**By closing the tab/window**)
3. Check in Firefox that the user is not removed from list. 

(It doesn't occur if you click on leave button)

**BBB version:**
BigBlueButton Server 2.5.1 (3020)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 101.0.1

**Additional context**
(Maybe related to #14969 )

**Comment by mokazemi** [comment] 2022-06-16 15:05
**Edit:** It also happens in Chrome, But not in all cases! (I'm not sure when or why)

**Comment by antobinary** [comment] 2022-06-16 15:12
Thanks for reporting!

Possible duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/15069 cc @ramonlsouza ?

**Closed** 2022-06-16 17:39 UTC
Labels: module: client, status: verify
