### ISSUE TITLE
Sharing sound speakers device output along with sharing of window or screen function.

### ISSUE THREAD

**Issue by csevast** [bigbluebutton/bigbluebutton#9752] opened 2020-06-03 14:15 UTC
I want to send sound from a shared application window, e.g. Audacity. I tried to use some special sound mixing application software but the result was very disturbing acoustically because of the delayed presenter's microphone feedback. I think that the solution is when an application window or a screen is shared, the output of speakers device to be sent either. Other video conference applications offer this feature, which is important when the course has to do with sound and acoustics.

**Comment by prlanzarin** [comment] 2020-06-03 14:36
Duplicate of #8632

**Closed by prlanzarin** 2020-06-03 14:36 UTC
Labels: Enhancement
