### ISSUE TITLE
Chat box auto-scrolling interferes with user scrolling

### ISSUE THREAD

**Issue by BrentBaccala** [bigbluebutton/bigbluebutton#11378] opened 2021-02-11 00:52 UTC
I've noticed this on 2.3 pre-releases up to and including alpha6.

When the chat box fills to the point where it needs to scroll, I can't scroll with my scroll wheel.  It keeps auto-scrolling to the bottom of the chat box, even when there's no new input arriving.

Sometimes even the autoscrolling seems to create a jerky motion of the chat box, even when I'm not attempting to scroll by hand.

Suggested behavior: auto-scroll should only happen when the user has scrolled to the bottom of the chat box.  Auto-scroll should become disabled when the user scrolls up into the chat history.

**Comment by daminebenq** [comment] 2021-03-04 16:43
I can't reproduce this issue anymore on develop branch 2.3 alpha-8.
@BrentBaccala Can you please close this issue ?

**Comment by daminebenq** [comment] 2021-03-13 00:02
Confirming, this is still reproducible.

https://user-images.githubusercontent.com/5144311/111010756-2bd9b680-8376-11eb-807b-c10d5746e2d8.mp4

**Comment by daminebenq** [comment] 2021-04-06 18:10
I could find another way to reproduce this.
Just switching from anything to chat panel gives autoscrolling forces to scroll up for the very first seconds after switching back to chat panel.

https://user-images.githubusercontent.com/5144311/113758330-1a23ce80-96ea-11eb-9f51-7cf6ef7dae34.mp4

**Comment by daminebenq** [comment] 2021-04-15 18:10
**To reproduce:**
1. Join a bbb2.3 room with a user
2. Type in chat box some messages to be able to see the scrolling bar
3. Click and switch between any panel (shared notes/breakout panel/polling panel) to chat panel
4. Once you click chat panel, chat starts scrolling to top automatically

**Current behavior:**
Chat autoscrolls to top automatically..

**Expected behavior:**
Chat should not scroll to top, and it should stay at the same level where it was left before switching to another panel.

**Comment by daminebenq** [comment] 2021-04-19 17:46
I couldn't reproduce this anymore on develop branch.

**Comment by ramonlsouza** [comment] 2021-04-27 14:06
> Autoscrolling problem is again reproducible...
> 
> **To reproduce:**
> 
> 1. send multiple messages in chat until the scroll bar appears and starts gettings smaller
> 2. switch to Shared notes or to any other panel
> 3. Switch back to chat
> 4. Try to scroll to the bottom
> 5. See result..
> 
> **Expected behavior:**
> Scrolling down in chat should not get contradicted to scroll back to top.
> 
> **Current behavior:**
> Scrolling down in chat gets contradicted and scrolls back to top for the very first 3-4 seconds right after switching back to chat panel.
> 
>  deepin-screen-recorder_Select.area_20210426162435.mp4

This is a side effect of PR #12170.

Current solution is to recalculate the heights of messages multiple times when the user switches between private and public chats to ensure the correct size is set, which causes the scroll in the first seconds after the chat is open.

**Closed** 2021-04-29 20:00 UTC
Labels: component: chat, module: client

**Comment by PlumedArcher** [comment] 2021-05-05 09:51
This still doesn't work as intended i guess. 

https://user-images.githubusercontent.com/80673946/117124154-40e02e00-ad98-11eb-81b2-1081b6772369.mp4

**Comment by Tainan404** [comment] 2021-05-05 17:54
Hi @PlumedArcher, Could you describe the actions you took to do this? also your BBB version? I know that @ramonlsouza made some changes reducing the re-renders and the list height that would fix the scroll issues

**Comment by PlumedArcher** [comment] 2021-05-05 18:07
I just went to public chat, nothing more.
 If the https://test23.bigbluebutton.org does not get updated anymore, then this might be the reason, used Clientversion 1668. My bad!

On Clientversion 1669 it works better, the scroll bar jumps just once to the middle.
