### ISSUE TITLE
apply-config.sh not run on server startup

### ISSUE THREAD

**Issue by bilias** [bigbluebutton/bigbluebutton#9602] opened 2020-05-19 06:55 UTC
I've created /etc/bigbluebutton/bbb-conf/apply-config.sh and it works fine with
bbb-conf --stop/start

However after server reboot (or upgrade) the script is not being run.

**Comment by basisbit** [comment] 2020-05-19 14:47
as designed. There exist a couple issue here already about exactly this questions. Please next time use the search feature.

**Comment by basisbit** [comment] 2020-06-02 01:36
Duplicate of #9409

**Closed by basisbit** 2020-06-02 01:36 UTC
