### ISSUE TITLE
Record and playback mouse cursor in desktop sharing

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2538] opened 2015-08-12 08:38 UTC
Originally reported on Google Code with ID 1787
```
What steps will reproduce the problem?
1.  Join a recorded session as presenter
2.  Share your desktop for a few minutes and end the session
3.  View recording

The mouse cursor will not be visible in the recorded desktop sharing


```

Reported by `ffdixon` on 2014-08-22 22:47:21

**Comment by ffdixon** [comment] 2016-01-31 00:51
Duplicate of #2836.

**Closed by ffdixon** 2016-01-31 00:51 UTC
Labels: DeskShare (Java), Enhancement, Low Priority, Recording
