### ISSUE TITLE
Whiteboard stops working when you zoom in on the slide on android.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#6072] opened 2018-09-13 18:11 UTC
Steps to reproduce:
	1 - Opens 1 flash client and 1 HTML5 client (android).
	2 - Enable the multi whiteboard.
	3 - Zoom in on the presentation.
	4 - Try draw on html5 client on android. 

![peek 2018-09-13 15-03](https://user-images.githubusercontent.com/15806883/45506922-106ea000-b767-11e8-87e4-18930a0c169b.gif)

**Comment by antobinary** [comment] 2018-09-19 18:56
This issue was present on Chrome 68-, after updating to Chrome 69 we cannot reproduce. Firefox on Android also draws fine. Closing this issue

**Closed by antobinary** 2018-09-19 18:56 UTC
Labels: Bug, HTML5 Client
