### ISSUE TITLE
Add API call to upload a presentation in a live meeting

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2686] opened 2015-08-12 08:41 UTC
Originally reported on Google Code with ID 1938

```
Suggested in this thread

  https://groups.google.com/d/msg/bigbluebutton-dev/2ComTWMVIrI/FvDYlDOE7zoJ


```

Reported by `ffdixon` on 2015-05-07 15:57:03

**Comment by aogilvie** [comment] 2019-07-17 07:07
I see there is a caption file API now, would a file API be somewhat similar implementation wise?

**Comment by aogilvie** [comment] 2019-07-17 07:08
https://github.com/bigbluebutton/bigbluebutton/pull/7564

**Comment by ffdixon** [comment] 2019-07-17 11:36
We do intend to implement this API call as it would help 3rd party applications integrate with BigBlueButton.  

At the moment, we've been working on adding support for captioning the recordings after they have finished processed.

**Comment by paraviz02** [comment] 2020-11-13 16:22
Hello @ffdixon -- is there any update on this one? We'd love the ability to programmatically upload presentations to the list. Doesn't necessarily need the ability to switch, but to make it available for a presenter to take steps out of the process.

For example, if a teacher asks all of their students to drop their assignment into a web portal (with a naming convention so the presenter knows what's what), for those documents to be automatically made available in the list of presentations would be great. Or some sort of built-in functionality where non-presenters/moderators could drop/upload supported file types into a part of the BBB UI could be even better.

**Comment by privatejava** [comment] 2022-02-10 07:03
has this featrue been already created?

**Comment by antobinary** [comment] 2022-02-10 15:37
Possible duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/14014 ?
14014 is being developed right now, @privatejava , see https://github.com/bigbluebutton/bigbluebutton/pull/14264

**Closed** 2023-02-14 20:29 UTC
Labels: status: accepted, priority: normal, type: enhancement, module: api
