### ISSUE TITLE
Duplicate Instances of persons in a waiting room /waiting que

### ISSUE THREAD

**Issue by jwcrea** [bigbluebutton/bigbluebutton#12261] opened 2021-05-03 16:17 UTC
**Describe the bug**
When i open a meeting room as a moderator, when a single user is joining (via invitation link) the meeting room and is waiting in the waitingroom /waiting que, two instances of the same person are displayed in the frontend. This goes on for any additional person who is trying to join the meeting. It does not break the behaviour of accepting or denying the access to the meeting room but it is a strange behaviour in displaying two instances of the same person where it should be only displaying one instance.

**Expected behavior**
As a users trys to enter the meetingroom waiting for denial or approval of moderator only one instance of the user in the waiting que ( for the moderator to deny or accept ) is visible in the frontend.

**Actual behavior**
As a users trys to enter the meetingroom waiting for denial or approval of moderator two instances of the  same user in the waiting que ( for the moderator to deny or accept ) are visible

**Screenshots**
![Bildschirmfoto 2021-05-03 um 12 01 19](https://user-images.githubusercontent.com/78031623/116901445-39a30e00-ac3a-11eb-8e49-9fe815a6adc9.png)

**BBB version (optional):**
BigBlueButton Server 2.2.36 (2416)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version  90.0.4430.93 
 - BBB Clientversion: 992

**Comment by pedrobmarin** [comment] 2021-05-03 16:29
Looks like the same reported at https://github.com/bigbluebutton/greenlight/issues/2697

**Comment by jwcrea** [comment] 2021-05-03 16:36
Yes this ist nearly the same issue but for point 5) where it says "The correct number is shown 15-20 seconds later, also the duplicated names disappear. After that, that the correct number of waiting users is displayed. " In my experience this does not happen. Every users is shown twice until i accept their request to enter the room.

**Comment by pedrobmarin** [comment] 2021-05-03 18:10
The first thing we need to validate this as a bigbluebutton issue is having steps to reproduce it without greenlight. Could you try doing so using only the [API](https://mconf.github.io/api-mate/)?

**Comment by jwcrea** [comment] 2021-05-04 08:48
We are not using greenlight and start our meetingrooms with API calls.

**Comment by pedrobmarin** [comment] 2021-05-04 11:30
So what's an _invitation link_? I tried but could not reproduce this issue using API Mate.

**Comment by jwcrea** [comment] 2021-05-05 10:39
I am sorry, we are using greenlight in the frontend.So this issue is most likely the same as bigbluebutton/greenlight#2697 . Can you please close this one.

**Comment by pedrobmarin** [comment] 2021-05-05 11:57
Yeah. Looks like there's something triggering a join API call twice at some circumstances. I'll close this one and let's catch up at the GreenLight tracker.

**Closed by pedrobmarin** 2021-05-05 11:57 UTC
Labels: module: client
