### ISSUE TITLE
BigblueButton SSL ISSUE

### ISSUE THREAD

**Issue by wamiqueL** [bigbluebutton/bigbluebutton#9197] opened 2020-04-22 11:01 UTC
Hi,

I'm at the end of the installation, implemented SSL and after that its throwing the below error:

BigBlueButtonException: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")

can you guide me please #ffdixon

I;m getting the below error in log file:

ERROR: [9645fcb6-934d-44d8-b6f5-baef05f6ffe2] BigBlueButtonException: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 185
Last 80 unconsumed characters:

**Comment by basisbit** [comment] 2020-04-22 11:07
Duplicate of #9196

**Comment by basisbit** [comment] 2020-04-22 11:08
see the log file that you just mentioned. it contains exactly where you have to revert your changes.

**Comment by wamiqueL** [comment] 2020-04-22 11:10
the log file gives me thy same error again and again couldn't find the exact thing to fix it

when I login it gives me 

Server Error
Invalid BigBlueButton Endpoint and Secret

**Comment by basisbit** [comment] 2020-04-22 11:29
you might be faster to start your BigBlueButton installation from scratch or use a backup. Start with a new Ubuntu 16.04 image, then do
1. `apt update`
2. `apt dist-upgrade -y`
3. `wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -s yoursubdomain.yourdomain.tld -e your@emailaddress.tld`
4. Install the frontend which you like (for example Greenlight, or Moodle plugin, Wordpress plugin, ...)

**Comment by wamiqueL** [comment] 2020-04-22 11:30
ok let me check the issue arises soon when I brought everything to SSL without SSL everything is running perfect. but we require SSL to work

**Comment by basisbit** [comment] 2020-04-22 11:32
the `wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -s yoursubdomain.yourdomain.tld -e your@emailaddress.tld` will set up everything with SSL/TLS and get a certificate for you from https://letsencrypt.org/.

**Comment by wamiqueL** [comment] 2020-04-22 11:34
thanks, can you guide me that where I can set the certificate paths

**Comment by wamiqueL** [comment] 2020-04-22 11:39
meanwhile I'm going for other server setup can you tell me which file does above error could contain

**Comment by basisbit** [comment] 2020-04-22 11:43
sorry, I can't tell you which file is corrupted, because the parts of the log that you pasted here are too short and thus do not contain the affected file or the affected file content.

**Comment by basisbit** [comment] 2020-04-22 11:54
Regarding the path for your TLS certificate: the location of the certificate can be anywhere on your server. The location has to be specified in `/etc/nginx/sites-enabled/bigbluebutton` (but the bbb-install command which I mentioned above will handle all the required configuration for you)

**Comment by wamiqueL** [comment] 2020-04-22 14:07
i went through the script and install newly but still HTTPS is not working...the website is coming without https

**Comment by basisbit** [comment] 2020-04-22 14:09
did you execute the command as mentioned above including the domain name and your email address? If yes, what did it report during install?

**Comment by wamiqueL** [comment] 2020-04-22 14:28
I've fixed the issue by changing the Nginx conf file just made a separate body of port 80 and 443 with redirect parameter

thanks for everything!


Need one me more help if that's possible for you

I'm trying to setup the email verification thing using SMTP parameters from .env file:
For using the SMTP option do I need to install any mail utility on ubuntu server or is there any script just like you shared me above will do it by it self
SMTP_SERVER= 
SMTP_PORT=
SMTP_DOMAIN=
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_AUTH=
SMTP_STARTTLS_AUTO=

# Specify the email address that all mail is sent from
SMTP_SENDER=

**Comment by matiasilva** [comment] 2020-06-18 13:08
=> https://groups.google.com/forum/#!forum/bigbluebutton-greenlight

**Closed by matiasilva** 2020-06-18 13:08 UTC

**Comment by basisbit** [comment] 2020-06-18 15:02
has nothing to do with Greenlight. Thus, the correct support mailing list is https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by matiasilva** [comment] 2020-06-18 15:04
@basisbit The poster's first issue was solved. Notice their second request.
