### ISSUE TITLE
GTK-based application

### ISSUE THREAD

**Issue by digitalethics** [bigbluebutton/bigbluebutton#9724] opened 2020-05-30 17:31 UTC
Currently, BigBlueButton runs entirely in a browser window. When tutoring students I have to instruct them to click a button from within my moodle cloud to launch the BigBlueButton video conference. I'd like to start a discussion about the limits and possibilities of having BigBlueButton work from within a GTK-based application so that students can simply launch an app on their desktop (from a Linux-based system or via a Windows subsystem to run GTK applications on Windows) and connect to their tutors without relying on a browser window.

**Comment by basisbit** [comment] 2020-05-31 00:59
Creating a desktop client or app for BBB participants gets suggested occasionally. Anyhow, this issue tracker here is not for general development discussions - we have a forum / mailing list for that: https://groups.google.com/forum/#!forum/bigbluebutton-dev
I'd suggest you to search for previously started discussions of this topic there and thus find more people who are interested in discussing and working on this topic.

partial duplicate of #9513

**Here are my two cents regarding the topic:**
One of the easiest ways of doing this would probably be to use the Electron app framework. 

Writing a new (for example GTK based) client which implements all the necessary parts of the WebRTC standard and all the other required parts would probably be a lot of initial work and then also be a lot of maintenance work. To implement new features in the frontend (or when the backend API changed), a developer would not just have to change + test the web-frontend, but instead then additionally have to put work and time into adjusting the desktop client.

Another aspect is the deep integration into the various web-based [learning tools](https://bigbluebutton.org/integrations/): For example, the students are logged in to moodle in their webbrowser, then select their class section and then click on the BigBlueButton activity. Currently, this would then open the BBB session in the same browser tab, so the student can participate. When the session is over, the student clicks on exit session, and immediately the webbrowser changes to the "activity completed" page within the learning tool.  When using a BBB desktop application, the user would have been thrown from the webbrowser into a completely different environment -> desktop app. This transition would probably cause problems quite often, and it would also be much more difficult to switch back into the learning tool after the session ended.

All this sounds too much "against" development of an app... of course, such an app would have plenty of advantages:
- improve performance / experience on small or low end devices
- better use of native optimized code and hardware acceleration features
- work around the mobile devices not supporting WebRTC / HTML5 screen share
- improve user experience for using bbb without any learning tool integration

In the end, I guess development of such an app would depend on some companies throwing developer time at this, or we would need a sudden increase of other developers joining the project.

**Closed by basisbit** 2020-05-31 00:59 UTC
Labels: Enhancement
