### ISSUE TITLE
Chat messages disappearing

### ISSUE THREAD

**Issue by mk-hs** [bigbluebutton/bigbluebutton#12468] opened 2021-05-31 09:57 UTC
**Describe the bug**
There seems to be a bug, probably related to the auto-scroll function & WelcomeMessage, which can result in chat messages disappearing for users.

The chat itself is getting logged fine and can be retrieved completely by downloading the chatlog.

We've had a couple reports on this and I've been able to reproduce it successfully on demo.bigbluebutton.org.

**To Reproduce**
1. First user starts room, writes something until the scroll bar appears
2. Second user joins, writes something
3. First user switches to shared notes and back. 

**Expected behavior**
The chat can be accessed normally.

**Actual behavior**
The Chat is displayed correctly for a split second, but then the scroll bar disappears and all prior chat can't be accessed any more. While this seems temporary and can be fixed by waiting for more chat messages to come in, this can be very confusing for users. It's also possible that nobody writes any new chat messages for a while, so the user's left with a broken interface.
This is especially troublesome for people moderating larger sessions.
Reloading the client usually works temporarily, but the chat starts disappearing again under certain circumstances.

**Screenshots**
![scroll1](https://user-images.githubusercontent.com/63116186/120166642-18175100-c1fd-11eb-9654-414c952cfea2.png)
Although only the Welcome box is affected on this screenshot, this would also apply to all prior chat messages - being unreadable because the scroll bar is gone.

**BBB version (optional):**
The version deployed on demo.bigbluebutton, client version 1711.
We use the latest version, 2.3.1, client version 1720.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 88.0.1
 - However, this happens on Chrome as well, according to reports.

**Additional context**
This does seem related to the way the scrolling function handles the WelcomeMessage, particularly because the scroll bar seems to be 'jumping'.
When users join an ongoing session, the scroll bar will behave normally until new messages push up the WelcomeMessage into the non-visible area. From then on, the scroll bar gets repositioned/resized when you switch back to the chat.
(See this image - first normal, then a similar session seconds apart from switching back to chat - mirrored for a more obvious representation of the scroll bar differences)

![scroll2](https://user-images.githubusercontent.com/63116186/120166659-1e0d3200-c1fd-11eb-8034-e69c66a9e3f1.png)

**Comment by antobinary** [comment] 2021-05-31 15:14
Thanks for reporting this @mk-hs

**Comment by Tainan404** [comment] 2021-06-09 13:08
Hi @mk-hs, I've tried to reproduce with the steps in issue and could not see the bug, please see the following recording:

https://user-images.githubusercontent.com/15806883/121360160-8c8f7580-c90a-11eb-98e2-ce856dcf0e95.mp4

Can you please check if there is any extra step needed to reproduce the problem?

**Comment by antobinary** [comment] 2021-06-09 13:56
@Tainan404 could you please re-try this with passing a moderator only message on meeting create? 
![Screenshot from 2021-06-09 09-56-02](https://user-images.githubusercontent.com/6312397/121368251-ed1db300-c908-11eb-8d2d-a067ef57d15e.png)

**Comment by mk-hs** [comment] 2021-06-09 14:04
Yeah, the moderator-only message seems to be the culprit, I'm unable to reproduce it when it's missing as well.
Accessing shared notes doesn't matter, but the chat needs to be rerendered.

![w5ChS10qc2](https://user-images.githubusercontent.com/63116186/121369480-2f141c80-c93c-11eb-8724-379684745621.gif)

**Comment by daminebenq** [comment] 2021-06-10 15:34
Hi @mk-hs
Thanks for reporting this. I couldn't reproduce this at all. I remember we had it like a month ago reproducible but on the current 2.3.x-release couldn't reproduce it at all. I suggest to update your BBB server and if it's not anymore reproducible please close the issue. Thanks alot !

**Comment by mk-hs** [comment] 2021-06-10 15:43
Hey @daminebenq,
I've reproduced this yesterday (see Screencast on my last post) on demo.bigbluebutton.org and just now on my own server, which is running the latest release --> BigBlueButton Server 2.3.3 (2326)

**Comment by Tainan404** [comment] 2021-06-10 17:04
Hi @mk-hs, could you record a video reproducing it? maybe a step is not so clear

**Comment by mk-hs** [comment] 2021-06-10 17:20
Hey @Tainan404 sure, but it's basically the same as the last one in https://github.com/bigbluebutton/bigbluebutton/issues/12468#issuecomment-857723083

https://user-images.githubusercontent.com/63116186/121569233-d9657000-ca20-11eb-9815-9b85dac41f00.mp4

**Comment by mk-hs** [comment] 2021-06-16 22:34
Just a quick confirmation that this is still present on 2.3.4.

**Comment by czange** [comment] 2021-09-30 07:45
Hi, We can confirm, that this is still an issue in 2.3.7 - but apparently solved in 2.3.13? Is that right?

Any pointer as to why this happens, and where it is solved would be highly appreciated, as we have some servers that cannot go yet from 2.3.7 up to 2.3.13

**Comment by mk-hs** [comment] 2021-09-30 09:40
I'm unable to replicate it on demo.bigbluebutton.org, which already runs on 2.4-rc1, but I can still replicate it on my 2.3.14 servers.
So it appears to be fixed in the next version, BBB 2.4.

**Comment by czange** [comment] 2021-09-30 09:42
This is interesting, as we cannot replicate it on any of those 2.3.13 servers - but on 2.3.7 - so it seems it is still not understood what is actually causing this - and is probably not fixed anywhere ... and can happen also in 2.4

**Comment by antobinary** [comment] 2022-01-10 20:29
If anyone is able to reproduce on BBB 2.4.0+ please open a new issue and provide as much debug info as possible to help us narrow down a possible cause.
I don't think we'll be trying further to debug on 2.3 or trying to backport it to 2.3.

**Closed by antobinary** 2022-01-10 20:29 UTC
Labels: status: accepted, component: chat, module: client
