### ISSUE TITLE
bbb-resync-freeswitch failing due to missing password information

### ISSUE THREAD

**Issue by thegcat** [bigbluebutton/bigbluebutton#9801] opened 2020-06-09 09:20 UTC
**Describe the bug**

The Job `/etc/cron.hourly/bbb-resync-freeswitch` fails with error code `255`. The cronjob was added in https://github.com/bigbluebutton/bigbluebutton/pull/9597. The log holds the following error:

```
[ERROR] fs_cli.c:1691 main() Error Connecting []
```

Adding a little more debug yields the following logs:

```
root@bb7:~# /opt/freeswitch/bin/fs_cli -x 'fsctl sync_clock_when_idle' -d 7
[DEBUG] esl_config.c:56 esl_config_open_file() Configuration file is /root/.fs_cli_conf.
[DEBUG] esl_config.c:56 esl_config_open_file() Configuration file is /etc/fs_cli.conf.
[DEBUG] fs_cli.c:1641 main() no profiles found, using builtin profile
[DEBUG] fs_cli.c:1680 main() Using profile bb7 [127.0.0.1]
[DEBUG] esl.c:1303 esl_recv_event() RECV HEADER [Content-Type] = [auth/request]
[DEBUG] esl.c:1467 esl_recv_event() RECV MESSAGE
Event-Name: SOCKET_DATA
Content-Type: auth/request


[DEBUG] esl.c:1495 esl_send() SEND
auth ClueCon


[DEBUG] esl.c:1303 esl_recv_event() RECV HEADER [Content-Type] = [command/reply]
[DEBUG] esl.c:1303 esl_recv_event() RECV HEADER [Reply-Text] = [-ERR invalid]
[DEBUG] esl.c:1467 esl_recv_event() RECV MESSAGE
Event-Name: SOCKET_DATA
Content-Type: command/reply
Reply-Text: -ERR invalid


[ERROR] fs_cli.c:1691 main() Error Connecting []
```

From what we were able to gather the cronjob is missing the password set in https://github.com/bbb-pkg/bbb-config/commit/e9af62e39d6b09368005d65edbd9f5a252b67653#diff-e84700706ab06dd98849d33722be0255R2013

**Additional context**

The affected BBBs are installed using the ansible role https://github.com/n0emis/ansible-role-bigbluebutton and might be missing some things the official installer sets, we haven't found anything pertaining to this in the `bbb-conf` repo though, so this might be a problem in the core installation too.

**Comment by thegcat** [comment] 2020-06-09 09:25
From what I can gather from https://freeswitch.org/confluence/display/FREESWITCH/Command-Line+Interface+fs_cli#Command-LineInterfacefs_cli-ConfigurationOptions it is possible set a config file containing the password, that might be preferable to getting the password "by hand" each time `fs_cli` is called as done in https://github.com/bigbluebutton/bigbluebutton/pull/9663/files

**Comment by basisbit** [comment] 2020-06-09 09:47
Looks like this was caused by 3d6bedc

**Comment by ffdixon** [comment] 2020-06-09 11:48
Yes, that is the cause.  If you update `bbb-resync-freeswitch` to the following it should work again.  We'll fix this in the next update to 2.2.

~~~
#!/bin/bash

/opt/freeswitch/bin/fs_cli -x 'fsctl sync_clock_when_idle' -p $(xmlstarlet sel -t -m 'configuration/settings/param[@name="password"]' -v @value /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml)  > /var/log/freeswitch_sync_clock.log 2>&1

~~~

**Comment by bayden10** [comment] 2020-06-10 00:41
I've run that script but still getting 

```
run-parts: /etc/cron.hourly/bbb-resync-freeswitch exited with return code 255
```

**Comment by stweil** [comment] 2020-06-16 17:27
@bayden10, you have to modify `/etc/cron.hourly/bbb-resync-freeswitch` as a temporary fix.

**Comment by bayden10** [comment] 2020-06-16 19:35
@stweil Thank you.. done

**Comment by matiasilva** [comment] 2020-06-16 19:36
Looks like this has been solved. Closing.

**Comment by basisbit** [comment] 2020-06-16 19:38
Reopen the issue because the problem is not yet solved in the current bbb release.

**Comment by ffdixon** [comment] 2020-06-17 03:42
It should be solved in upcoming 2.2.18

**Comment by spblinux** [comment] 2020-07-18 17:09
The change [mentioned above](https://github.com/bigbluebutton/bigbluebutton/issues/9801#issuecomment-641173594) causes that the **_password_** given in /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml **_is required to open_** **fs_cli**

- _failing (with Error Connecting)_: /opt/freeswitch/bin/fs_cli -x "sofia status profile external"

- _works_: /opt/freeswitch/bin/fs_cli -p PASSWORD_FROM_FILE -x "sofia status profile external"

Maybe this could be documented at [troubleshooting section freeswitch](https://docs.bigbluebutton.org/2.2/troubleshooting.html#freeswitch), because it was not easy to find this information (observed using **_BigBlueButton_** Version **2.2.20**)

**Comment by basisbit** [comment] 2020-07-18 17:15
Issue was solved in 2.2.18. @spblinux to get this changed in the troubleshooting section, please either create a new issue for that, or - even better - please create a pull request containing your description at the documentation repository at https://github.com/bigbluebutton/bigbluebutton.github.io

**Closed by basisbit** 2020-07-18 17:15 UTC

**Comment by ffdixon** [comment] 2020-07-19 11:45
https://docs.bigbluebutton.org/2.2/troubleshooting.html#unable-to-connect-using-fs_cli

**Comment by alialic** [comment] 2020-08-26 10:32
> https://docs.bigbluebutton.org/2.2/troubleshooting.html#unable-to-connect-using-fs_cli

hi, i have this problem, Audio is out of sync with the webcam video after recording,Is the problem of clock synchronization in freeswitch?are metal servers  reccomended for best results?
