### ISSUE TITLE
When zooming in and then zooming out with the mouse wheel, the display doesn't go back to 100%

### ISSUE THREAD

**Issue by jorgelondo** [bigbluebutton/bigbluebutton#18701] opened 2023-09-04 04:39 UTC
**Describe the bug**
Hi, I installed the bbb 2.6.12 update and doing some testing noticed that when zooming in and then zooming out with the mouse wheel, the display doesn't go back to 100%. in the previous bbb version 2.6.11 with the same settings, the zoom was working fine.

**To Reproduce**
Zoom-in with the mouse wheel and then zoom-out
Slideshow doesn't return to full size (100%) when rolling mouse wheel all the way back... it stays zoomed in

**Expected behavior**
it would be expected that when zooming-out
The presentation returned to its size (100%) when the mouse wheel was fully rolled back.

**Actual behavior**
Slideshow doesn't return to full size (100%) when rolling mouse wheel all the way back

**BBB version:**
 bbb 2.6.12
Ubuntu 20.04 64-bit in aws EC2 instance c6a.xlarge

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Browser Firefox 117.0 (64-bit)

https://github.com/bigbluebutton/bigbluebutton/assets/672505/d8201d28-1f46-418d-b0c6-9dcc2b5fd7b8

**Comment by antobinary** [comment] 2023-09-06 00:49
Thanks for reporting! I believe this is a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/18645 which has been fixed and will be released shortly as part of 2.6.14.

**Closed by antobinary** 2023-09-06 00:49 UTC
Labels: module: client

**Comment by jorgelondo** [comment] 2023-09-13 10:49
> Thanks for reporting! I believe this is a duplicate of #18645 which has been fixed and will be released shortly as part of 2.6.14.

Hi, @antobinary , As I see the error still occurs in version 2.7.0. when zooming in and then zooming out with the mouse wheel multiple times, the error is raised again
Thanks
