### ISSUE TITLE
External video not visible on playback

### ISSUE THREAD

**Issue by pbdco** [bigbluebutton/bigbluebutton#9607] opened 2020-05-19 15:42 UTC
**Describe the bug**
External videos shared during a meeting are not visible on the recordings (only audio). Tested on BBB 2.2.11

**To Reproduce**
1. Start a meeting
2. Start recording
3. Share an external video. example: YouTube
4. Stop recording
5. End meeting
6. Open recorded session playback  

**Expected behavior**
See and hear the external shared video during the meeting on the recorded playback as well.

**Actual behavior**
Only audio on the playback but no image.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Checked on Mac + Windows + Linux
 - Browsers: Firefox, Chrome, Chromium

**Smartphone (please complete the following information):**
 - Device: iphone 10
 - OS: iOS Latest
 - Browser: Chrome
 - Version: Latest

**Comment by cipi1965** [comment] 2020-05-19 19:43
It is clearly explained in external video modal that external videos are not visible in recordings

**Comment by basisbit** [comment] 2020-06-04 00:24
Duplicate of #8478

**Closed by basisbit** 2020-06-04 00:24 UTC
Labels: Recording

**Comment by pbdco** [comment] 2020-06-04 00:26
> It is clearly explained in external video modal that external videos are not visible in recordings

Is not possible to get the playback into the recording (from the BBB recording feature, not from screen recording..) ??

**Comment by basisbit** [comment] 2020-06-04 00:35
there exists #7484 to work on that. See the other issue. linked above.

**Comment by pbdco** [comment] 2020-06-04 00:51
> there exists #7484 to work on that. See the other issue. linked above.

thanks
