### ISSUE TITLE
Setup for dynamic ip addresses

### ISSUE THREAD

**Issue by angelaki** [bigbluebutton/bigbluebutton#11464] opened 2021-02-23 11:14 UTC
I think for many users out there it is pretty interessting to be able to host BBB without having a **static** public ip address. I've found this issue here #10116, but it is more "multi instance" related.

Since there is no need for any component to know its external ip (at least as far as I know) I don't get why many components only listen on an explicit ip address and not on all. Even if they need to be known, that could be requested by a STUN server by default.

**Comment by basisbit** [comment] 2021-02-23 15:45
This problem would be "solved" by the same solution as for #10116. Also, this is not a supported use case because a location where you can't easily get a static IPv4 is not a location where you can operate reliable BBB services. Please do not try to run BBB form your home internet connection - that just causes users to be frustrated and then blame BBB for it.
Duplicate of #10116

**Closed by basisbit** 2021-02-23 15:45 UTC

**Comment by hostbbb** [comment] 2021-02-23 15:47
using the free public stun servers are problematic... the freeswitch and google stun servers,  have always had some down time.    if you run your own coturn with stun/turn you can control...  but admins doing this arent running with dynamic external ips...

if you need to autoscale in aws, you can use dynamic ips, and make dns api call to set the asisgned ip, and run 4 lines of bash to sed out and replace the new ip addresses.

**Comment by angelaki** [comment] 2021-02-23 15:51
Yeah, you guys are probably right - thank you anyways! :)

**Comment by devZer0** [comment] 2021-04-05 12:27
> This problem would be "solved" by the same solution as for #10116. Also, this is not a supported use case because a location where you can't easily get a static IPv4 is not a location where you can operate reliable BBB services. Please do not try to run BBB form your home internet connection - that just causes users to be frustrated and then blame BBB for it.
> Duplicate of #10116

sorry, but why shouldn't i be able to run bbb reliable with home internet connection?  there is ftth nowadays with lots of upstream bandwith, so some simple daily change of dynamic public ip should be something being supported in bbb.   i want to run my own bbb for use within family

**Comment by hostbbb** [comment] 2021-04-05 12:43
How often does the ISP change the IP address.   if DNS is updating this address dynamically during the day, your solution needs to monitor your external ip realtime, and autoconfigure when ip changes if you want the BBB service to always run... also,  live bbb meetings break when ip change in middle of meeting.

this is not difficult solution to develop.  the configs that need to change are listed in 10116 ticket.  The issue is its an edge use case...  and like babasit suggests, if its an option in bbb-conf will result in bad user exeperiences if miss used.

If you know linux, ssh, bash you should be able to deploy a cron job to auto config you...

**Comment by devZer0** [comment] 2021-04-05 15:27
>The issue is its an edge use case... 

if this is an edge use case, why does dynip.com even mention "running online video conferencing" as an example use case ?  

https://www.dynip.com/main/ns/110/doc/146/lang/EN

people may not use bbb with dynamic ip for NOW but if that works without a problem one day  (because of being supported and being easy to tell bbb that public ip changed), i'm sure, they will.

>this is not difficult solution to develop. the configs that need to change are listed in 10116 ticket

developing a 3rd party script which changes configs will likely break with every update. that needs to be supported feature by the product itself, otherwise it keeps developers busy...

**Comment by prlanzarin** [comment] 2021-04-05 15:33
> if this is an edge use case, why does dynip.com even mention "running online video conferencing" as an example use case ?

Because online video conferencing might be P2P or multiparty.
First scenario is absolutely ok with dynamic IPs.

Second scenario would also be ok, but the project didn't grow with that in mind.

There's an **open** issue about that. Take the discussion there. We didn't say we won't ever do this. Priorities.
