### ISSUE TITLE
Add ability to share screen or application window in FireFox

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6127] opened 2018-10-02 21:48 UTC
FireFox currently defaults to sharing a window, whereas Chrome let's you choose either window or screen.

The latter is more useful as it sharing a window can be problematic if the user resizes the window (and does not realize it's still fixed to the original size).

We would need to add UI that when the user clicks the share screen button, it puts up a dialog to ask whether to share **Full Screen** or **Region**.

**Comment by capilkey** [comment] 2018-10-24 16:08
#6142 was a duplicate of this, but it has more information and there's more activity in the other issue. I'm closing this one in favour of #6142

**Closed by capilkey** 2018-10-24 16:08 UTC
Labels: Design, HTML5 Client
