### ISSUE TITLE
Camera access dialog shows up several times in Firefox browser

### ISSUE THREAD

**Issue by paulmenzel** [bigbluebutton/bigbluebutton#11151] opened 2021-01-13 21:13 UTC
[Edit: This only happens with Mozilla Firefox.]

(No idea, if an issues already exists. Surprisingly, I could not find one.)

Using *bbb-html5* 2.2.0-1114, enabling the camera the browser access dialog appears several times, but should only be appear once.

1. Press the button to enable the camera.
2. The browser asks, if camera access is allowed. (For the camera selection?)
3. The browser asks again (accessing the quality setting?). → Only now the preview appears.
4. Changing the quality settings, the browser asks again.
5. Applying these settings (*Freigabe starten*) the browser asks again.
6. Before my image shows up on the board, the browser asks again.

This happens in all browsers, for example, Firefox 84.0.2 and Firefox Nightly 86.0a1 (20210112215931). But also Google Chrome and on Apple devices.

In the same tab, the browser dialog should only appear once.

**Comment by prlanzarin** [comment] 2021-01-13 21:20
This is a known (but I think not formally registered) issue with BBB + Firefox.
It should not happen with Chrome, though. Are you sure you could reproduce that with Chrome? If so, was it under an iframe? Was it desktop or mobile?

**Comment by paulmenzel** [comment] 2021-01-14 06:41
Thank you for the quick reply. Indeed, I wasn’t aware that (exemplary) a lot of our users use Firefox, so got the wrong impression. I just tested with Chromium 87.0.4280.141-0.1, and the permission dialog only showed up once.

Is that a Firefox problem, and, if yes, has it been reported to the [Mozilla bug tracker](https://bugzilla.mozilla.org/) already? Searching for *bigbluebutton* [does not show something related](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=bigbluebutton).

**Comment by Dimitrie23** [comment] 2021-01-14 08:44
This is actually wanted feature and not a bug by the firefox team. They are strictly holding to their privacy guidelines and this means that everytime a website requests webcam access and the user did not tik the "save decision". Firefox will ask you if you want to allowed access to the webcam, even so its from the same domain but on a sub-site or function of this website to prevent malicious and not allowed access to the webcam. For your users you might want to tell them that they can tik the "save decision" for the webcam on your domain. Only issue then is that you have to revoke the permission if you want to change to an external webcam for example you will have to revoke the saved permission to be able to switch the webcam again.

**Comment by prlanzarin** [comment] 2021-01-14 10:03
No. It is a usability bug. We're asking 1 or 2 too many gUMs. While this is FFs policy (not saving gUM permission by default), we could shave off the post preview gUM (after clicking share) and the profile switching gUMs. So still a UX bug because we can improve it.

**Comment by Dimitrie23** [comment] 2021-01-14 11:17
Okay, well than it is a bug. They also don't allowed the device names to be transferred. Maybe that the echo test need a lot of time compared to chromium based browsers to establish the connection with FF. Might be worth to take a look at that as well.

**Comment by paulmenzel** [comment] 2021-01-14 11:40
> Maybe that's why the echo test need a lot of time compared to chromium based browsers to establish the connection with FF. Might be worth to take a look at that as well.

Please create a separate issue for this. This issue is not about this, and it shouldn’t be mixed.

**Comment by prlanzarin** [comment] 2021-01-14 12:03
> Maybe that's why the echo test need a lot of time compared to chromium based browsers to establish the connection with FF. Might be worth to take a look at that as well.

Besides being off-topic, that's definitely not the same thing at all. There are open issues about this and explanations were given there (tldr trickle vs vanilla ICE).

**Comment by paulmenzel** [comment] 2021-06-14 12:07
I think that is at least fixed in BBB 2.2.36. Or Firefox was improved.

**Comment by prlanzarin** [comment] 2021-07-02 14:14
Yes, Firefox added a gUM grace period.
It isn't valid for iframes, though, so I'm re-opening this.

**Comment by prlanzarin** [comment] 2021-07-31 01:21
I'd it's as good as it can be with #12700 (while we wait for applyConstraints to propagate stuff properly when switching camera profiles).

**Closed by prlanzarin** 2021-07-31 01:21 UTC
Labels: component: webcam, module: client, type: enhancement
