### ISSUE TITLE
1002 socket error

### ISSUE THREAD

**Issue by hhuseyinpay** [bigbluebutton/bigbluebutton#10074] opened 2020-07-15 16:34 UTC
**Describe the bug**
We have some c5.2xlarge servers on AWS that opening and closing by our load balancer. Generally, there are 100-150 participants in 10-15 meetings on each server. Sometimes, one or two servers give 1002 socket errors in the middle of some meetings. Some participants instantly dropping and can not connect again. And some other participants continue without any issue. When they trying to connect to the echo test, 1002 error appears. When I trying to enter the demo meeting it gives a 1002 error also. After restarting the bbb, it working properly again. What is the cause of this? Which log file should I look for this issue?

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

These screenshots have taken when the error occurred.

![Ekran Resmi 2020-07-14 19 02 46](https://user-images.githubusercontent.com/14811488/87450272-f8883180-c606-11ea-80a3-0158cd2904df.png)

![Ekran Resmi 2020-07-14 19 05 58](https://user-images.githubusercontent.com/14811488/87450082-bfe85800-c606-11ea-95c2-abfbe74303a7.png)

![Ekran Resmi 2020-07-14 19 20 41](https://user-images.githubusercontent.com/14811488/87450450-31c0a180-c607-11ea-913e-81272bb971ad.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by matiasilva** [comment] 2020-07-15 18:26
Hi, thanks for posting a detailed issue. For support requests, please follow the guidelines at https://docs.bigbluebutton.org/2.2/getting-help.html. Also note that it is recommended that you keep that participant count below 100 for BBB 2.2.x.

**Comment by ffdixon** [comment] 2020-07-16 10:56
I think they are encountering the same issue as in #9667.

**Comment by hhuseyinpay** [comment] 2020-07-16 18:55
@ffdixon thank you for your interest. I think it's similar but not the same. Because in our case we are shutting down the servers after max 2 hours. And when the error occurs, restarting the bbb solves it.  But I don't know maybe it's the same. The error may occur while after X number of participants. 

In our use case, there are 4 sessions with 90 min in a day. In the most crowded session, there are 6000+ attendees on 40-45 c5.2xlarge servers. There are max 15 participants in a meeting and max 10 meetings on one server(In some situations there are 6-8 participants in a meeting and 15-20 meetings on a server ). But in any situation, there are max 180 participants in one server.
I'm going to try freeswitch-watchdog.

Btw I'm working for a nonprofit organization in Turkey. There is a distance learning event this month(for free). There are 25.000+ students and 3000+ volunteer teachers we are using bbb. We appreciated you for developing and maintaining this project!

**Comment by basisbit** [comment] 2020-07-18 17:22
@ffdixon very much looks like a duplicate, indeed. If it is, we might want to mark this as a duplicate and close the issue.

@hhuseyinpay next time the issue appears, does running `service freeswitch restart` temporarily fix the issue for you?

**Comment by ffdixon** [comment] 2020-07-18 20:09
> Sometimes, one or two servers give 1002 socket errors in the middle of some meetings.

We would like to fix this as well!

If you could come up with a script to reliability reproduce this issue, we could engage the SignalWire folks (developers of FreeSWITCH) to help fix the issue.  The problem at the moment is we've encountered the error, but not have had success in reproducing it.

Marking as duplicate of #9667.

**Closed by ffdixon** 2020-07-18 20:09 UTC
