### ISSUE TITLE
Issue on recording; shapes and text added to slide remains in later slides.

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2632] opened 2015-08-12 08:40 UTC
Originally reported on Google Code with ID 1884

```
When presenting there is no problem, and you write or draw somethings on the slide,
then you open next slide, and write and draw other things. after you watch the recording
all the shapes and drawings remains to the next slide. I also attached two screen shot
of this issue.
```

Reported by `idol.mesut` on 2015-02-18 07:21:26

<hr>
- _Attachment: 4.png<br>![4.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1884/comment-0/4.png)_
- _Attachment: 3.png<br>![3.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1884/comment-0/3.png)_

**Comment by ffdixon** [comment] 2017-01-15 23:29
Closing this issue as the user was unable to reproduce on BigBlueButton 1.0.

**Closed by ffdixon** 2017-01-15 23:29 UTC
Labels: Accepted, Defect, Normal Priority, Recording
