### ISSUE TITLE
Getting error Call timeout 1006 when setup behind the firewall(corporate network)

### ISSUE THREAD

**Issue by higunjan** [bigbluebutton/bigbluebutton#11128] opened 2021-01-09 08:42 UTC
**Describe the bug**
Facing the issue after installation of BBB, when tried with mic enable getting error like, *call timeout (error 1006)*

**Installation type**
bbb-install script

**Firewall and IP address type**
My server behind a firewall. BBB server have its own IPv4 address.

BBB server ( private address XX and public address YY )   <---> Gateway and Firewall ( Private address AA & Public address BB )  <--->  Client call YY ( bbb server public address YY)

**Console output**
```
INVITE sip:echo76786@xx.xxx.xxx.in SIP/2.0
Via: SIP/2.0/WS o8t73uhkqq1j.invalid;branch=z9hG4bK7361143
To: <sip:echo76786@xx.xxx.xxx.xx.in>
From: "w_hmva0cmz3m2j_2-bbbID-User 1806378" <sip:w_hmva0cmz3m2j_2-bbbID-User%201806378@xxx.xxx.xxx.xx.in>;tag=09vngs2mi4
CSeq: 1 INVITE
Call-ID: h0vslq467plrvebp1e23
.....

```
After 20 sec. call timeout (error 1006)

**Additional context**
When I click on mic then wait till 20 sec but no log in freeswitch too.
/opt/freeswitch/log/freeswitch.log

Also, my camera is working fine. ( Kurento )

```
bbb-conf --check

BigBlueButton Server 2.2.31 (2307)
                    Kernel version: 4.4.0-198-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 10205 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://BBB_SERVER_PUBLIC_DOMAIN
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: BBB_SERVER_PUBLIC_DOMAIN
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: BBB_SERVER_PRIVATE_IP
                   external_rtp_ip: STUN_SERVER
                   external_sip_ip: STUN_SERVER

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: BBB_SERVER_PRIVATE_IP:5066
                       wss-binding: BBB_SERVER_PUBLIC_IP:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: BBB_SERVER_HOST
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: BBB_SERVER_PUBLIC_IP
                          protocol: https

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: BBB_SERVER_PUBLIC_IP
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: BBB_SERVER_PRIVATE_IP
                    localIpAddress: BBB_SERVER_PRIVATE_IP
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1114
                        kurentoUrl: wss://BBB-DOMAIN/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun:xxx.xxxx.xx
```

**Comment by borhanreo** [comment] 2021-02-23 03:42
I facing the same error here

**Comment by mariogasparoni** [comment] 2021-02-23 13:07
Try switching  the value of `sipjsHackViaWs` config in the file:
```/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml```
If it is set to true, try changing it to false, and vice versa.

**Comment by higunjan** [comment] 2021-02-23 13:51
@borhanreo 
Kindly try with following 
[Freeswitch fails to bind to port 8021](https://docs.bigbluebutton.org/2.2/troubleshooting.html#freeswitch-fails-to-bind-to-port-8021)

Also, check the 
[Configure BigBluebutton/FreeSWITCH to support IPV6](https://docs.bigbluebutton.org/2.2/troubleshooting.html#configure-bigbluebuttonfreeswitch-to-support-ipv6)
edit the file `/etc/bigbluebutton/nginx/sip.nginx` to have the following:

`proxy_pass https://$freeswitch_addr:7443;`

**Comment by dcr18** [comment] 2021-04-08 08:08
user side call time error `1006` in google chrome browser and Firefox error bigbluebutton 2.3 dev 
![10](https://user-images.githubusercontent.com/37870003/113990962-a01d5200-986f-11eb-85f7-1dd134d32f98.png)

how to solve my problem and advance

**Comment by mariogasparoni** [comment] 2021-04-08 12:11
> @borhanreo
> Kindly try with following
> [Freeswitch fails to bind to port 8021](https://docs.bigbluebutton.org/2.2/troubleshooting.html#freeswitch-fails-to-bind-to-port-8021)
> 
> Also, check the
> [Configure BigBluebutton/FreeSWITCH to support IPV6](https://docs.bigbluebutton.org/2.2/troubleshooting.html#configure-bigbluebuttonfreeswitch-to-support-ipv6)
> edit the file `/etc/bigbluebutton/nginx/sip.nginx` to have the following:
> 
> `proxy_pass https://$freeswitch_addr:7443;`
@higunjan
Did you manage to solve your problem ?
If so, please close this issue.

@dcr18 , mailing lists are the appropriate place to ask for this.

**Comment by lastCent** [comment] 2021-04-16 18:26
Hello, it seems I'm having the same issue. 
My install broke about two weeks ago. Attempting join a call with a microphone gives the 1006 error, in the browser console I can see 
` Uncaught (in promise) ReferenceError: RTCPeerConnection is not defined`

Just reinstalled from scratch on a fresh VM using install.sh, yet the issue persists. 

Changing the value of sipjsHackViaWs or the proxy_pass line as proposes by @mariogasparoni didn't fix it, nor can I see the "Freeswitch fails to bind to port 8021" error message. 
No problems are listed by `bbb-conf --check`. 

`bbb-conf --debug` gives:

```
/var/log/bigbluebutton/bbb-web.log:2021-04-16T20:04:23.485+02:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
```
but I think this is unrelated?

Any ideas?

**Comment by mariogasparoni** [comment] 2021-04-16 20:06
> ...
> My install broke about two weeks ago. Attempting join a call with a microphone gives the 1006 error, in the browser console I can see
> ` Uncaught (in promise) ReferenceError: RTCPeerConnection is not defined`
> ...
Interesting, which version is this log from ? It seems your problem is related to some specific configuration, but this log shouldn't be shown (there's a chance you are also hitting a bug).

**Comment by lastCent** [comment] 2021-04-17 00:18
We're running (VM):
```
BigBlueButton Server 2.2.36 (2416)
                    Kernel version: 4.4.0-186-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 32922 MB
                         CPU cores: 16
```
Apart from the filling in some fields in Greenlight's .env file (LDAP, SMTP, etc) we haven't modified any settings after the install.sh process. 

`/etc/bigbluebutton/nginx/sip.nginx` currently contains:
```
location /ws {
        proxy_pass http://<server_IPv4>:5066;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 6h;
        proxy_send_timeout 6h;
        client_body_timeout 6h;
        send_timeout 6h;

        auth_request /bigbluebutton/connection/checkAuthorization;
        auth_request_set $auth_status $upstream_status;
```
The RTCPeerConnection error I found on Firefox 87.0-1, though there is a good chance that it may be caused by something in my own setup there.
In a vanilla Chromium there is no corresponding error, so probably unrelated then.

**Comment by laserrapt0r** [comment] 2021-04-27 16:17
I have some users with the same error (Uncaught (in promise) ReferenceError: RTCPeerConnection is not defined) and BBB giving 1006. Those are only a few clients and it maily occurs in Firefox but occasionally in Edge as well.
Using BBB 2.3 rc1

I have no clue what could trigger this issue.

**Comment by mariogasparoni** [comment] 2021-04-27 20:39
There are a few fixes related to firefox that may be related to your case.
https://github.com/bigbluebutton/bigbluebutton/pull/12172
https://github.com/bigbluebutton/bigbluebutton/pull/12054

Please, try to reproduce the problem in the next release

**Comment by lastCent** [comment] 2021-04-27 21:46
I have since been able to confirm that in my case the 'ReferenceError: RTCPeerConnection is not defined' error was due to to having 'media.peerconnection.enabled' set to false in about:config. 
However, the 1006 error persists. I was able to resolve this for now by reverting to a previous version, xenial-220-2.2.31. This works, but it would be nice with a fix so that we are able to use a more recent version.

**Comment by AbdulazizFayez** [comment] 2021-11-09 04:37
> 
> 
> Try switching the value of `sipjsHackViaWs` config in the file: `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` If it is set to true, try changing it to false, and vice versa.


This fixed the issue for me, Thanks a lot @mariogasparoni 💪

**Comment by aogilvie** [comment] 2021-12-08 09:55
I also have this issue on BigBlueButton Server 2.3.0-alpha7 (1656) - sipjsHackViaWs this also did nothing.
I do not see it on 2.3.1 so, you might have to update?

**Comment by prlanzarin** [comment] 2021-12-08 12:24
> I also have this issue on BigBlueButton Server 2.3.0-alpha7 (1656) - sipjsHackViaWs this also did nothing. I can confirm Chrome 96.0.4664.45 does not work, but Edge 96.0.1054.43 does. Every time reproducible. No funky networking needed.
> 
> I do not see it on 2.3.1 so, you might have to update?

https://github.com/bigbluebutton/bigbluebutton/issues/13843#issuecomment-987856477

v2.3-beta.1 is the baseline in 2.3, 2.2.36 in 2.2 and any version in 2.4.

**Comment by prlanzarin** [comment] 2021-12-08 12:25
Also this issue clearly lost focus and is an amalgamation of troubleshooting requests, so I'm closing it.

**Closed by prlanzarin** 2021-12-08 12:25 UTC

**Comment by je8n** [comment] 2021-12-09 06:57
Hello, I have a similar problem. I'm using BIGBLUEBUTTON RELEASE=2.2.33 and chrome. I started getting error 1006. didn't exist before. and firefox good working .. js console error : 

DOMException: Failed to construct 'RTCPeerConnection': Plan B SDP semantics is a legacy version of the Session Description Protocol that has severe compatibility issues on modern browsers and is no longer supported. See https://www.chromestatus.com/feature/5823036655665152 for more details, including the possibility of registering for a Deprecation Trial in order to extend the Plan B deprecation deadline for a limited amount of time.

**Comment by hostbbb** [comment] 2021-12-09 11:32
Need to update to 2.2.36 or 2.3 2.4 to fix.   Firefox and Edge work now. But Edge should break anytime since based on chrome
-------- Original message --------From: Serkan Özdemir ***@***.***> Date: 12/9/21  1:57 AM  (GMT-05:00) To: bigbluebutton/bigbluebutton ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [bigbluebutton/bigbluebutton] Getting error Call timeout 1006
  when setup behind the firewall(corporate network) (#11128) 
Hello, I have a similar problem. I'm using BIGBLUEBUTTON RELEASE=2.2.33 and chrome. I started getting error 1006. didn't exist before. and firefox good working .. js console error :
DOMException: Failed to construct 'RTCPeerConnection': Plan B SDP semantics is a legacy version of the Session Description Protocol that has severe compatibility issues on modern browsers and is no longer supported. See https://www.chromestatus.com/feature/5823036655665152 for more details, including the possibility of registering for a Deprecation Trial in order to extend the Plan B deprecation deadline for a limited amount of time.

**Comment by BMTTeam** [comment] 2022-08-28 20:14
> > Try switching the value of `sipjsHackViaWs` config in the file: `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` If it is set to true, try changing it to false, and vice versa.
> 
> This fixed the issue for me, Thanks a lot @mariogasparoni muscle

That did fix it for me as well. sipjsHackViaWs was "false", changing to "true" and restart the BBB services made the audio working again.
Thanks!
Cheers,
-Tiho
