### ISSUE TITLE
Always make presenter's video larger

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#4427] opened 2017-09-25 01:08 UTC
For some online teaching scenarios, the presenter may always want their video to be larger (which gives focus to them in the video dock.

**Comment by prlanzarin** [comment] 2021-04-04 13:01
Can't this be merged into https://github.com/bigbluebutton/bigbluebutton/issues/8388?

I don't think it makes sense to force focus on the presenter role once we have focus based on voice floors. The latter tackles what needs to be (directly or not) without making the UX convoluted.

**Comment by pedrobmarin** [comment] 2021-04-14 21:50
Marking as a duplicate of #8388

**Closed by pedrobmarin** 2021-04-14 21:50 UTC
Labels: component: webcam, type: enhancement
