### ISSUE TITLE
The YouTube player syncing can malfunction on a server

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#7537] opened 2019-05-30 18:20 UTC
When a presenter shares a YouTube video there is a scenario where the non-presenters are unable to properly sync and play the video as expected. 

![YouTubeLoop](https://user-images.githubusercontent.com/1395090/58511821-9bfb5600-8169-11e9-8a80-8ed971713ace.gif)
![YouTubeLoop2](https://user-images.githubusercontent.com/1395090/58511822-9bfb5600-8169-11e9-89f2-d414c8b837d0.gif)

The videos are from some tests on demo.bigbluebutton.org. There were no relevant log messages so details are sparse unfortunately.

**Comment by JustinMogel** [comment] 2021-04-01 10:21
i have not encountered this, is this still reproducable?

**Comment by pedrobmarin** [comment] 2021-04-04 11:59
I think this was covered in multiple improvements made for this feature since this issue was opened, @JustinMogel . I'm closing this up and we can open a new issue with more details if this comes back.

**Closed by pedrobmarin** 2021-04-04 11:59 UTC
Labels: HTML5 Client
