### ISSUE TITLE
Presenter next slide preview 

### ISSUE THREAD

**Issue by alfonsofernandezyf** [bigbluebutton/bigbluebutton#8331] opened 2019-11-15 18:52 UTC
It would be helpful to have a preview of the following slides for the presenter.

**Comment by capilkey** [comment] 2019-11-15 19:01
Duplicate of #5587.

We had this in the Flash client and we have plans to add it to the HTML5 client, but no timeline right now.

**Closed by capilkey** 2019-11-15 19:01 UTC
Labels: HTML5 Client
