### ISSUE TITLE
Whiteboard annotation events slow

### ISSUE THREAD

**Issue by kendrickluong** [bigbluebutton/bigbluebutton#9203] opened 2020-04-22 14:25 UTC
There appears to be a minor delay between repeated pen strokes (using a surface pro). It feels as though on release of the pen the data is sent off to the server, this time gap makes writing math forumla quite difficult.

Can this data be sent off async to allow for continual pen input.

**Comment by basisbit** [comment] 2020-04-22 17:36
Duplicate of #9185

**Closed** 2020-06-18 13:09 UTC
