### ISSUE TITLE
Problem starting/joining meeting using Microsoft Edge in 2.3 Beta-2

### ISSUE THREAD

**Issue by webmasterbsmhome** [bigbluebutton/bigbluebutton#11921] opened 2021-04-07 12:55 UTC
When trying to join or start a meeting (using greenlight), when BigblueButton screen comes up, I get the following error
![bbb23b2Error_Edge](https://user-images.githubusercontent.com/64402954/113869230-c4662980-97b0-11eb-812e-f378ff0c0105.PNG).
Here it stops for the user. 
User is runing W10Pro Build 19042.867 using Microsoft Edge Version 89.0.774.68.
This problem apears from 23 different Pcs (Desktop and Laptop)
Tested with Firefox latest Version and Google Chrome latest version. With both Versions from same PCs without any problems.
Language for both PCs is German (autodetected)

**Comment by prlanzarin** [comment] 2021-04-07 12:57
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11865

(fixed in current `develop` HEAD)

**Closed by prlanzarin** 2021-04-07 12:57 UTC
