### ISSUE TITLE
Screen sharing from Mobile browser

### ISSUE THREAD

**Issue by shopnse** [bigbluebutton/bigbluebutton#10051] opened 2020-07-13 09:23 UTC
Hi Team,
Thanks for the continuous support, I have noticed as a Host on mobile browser I do not have option to share Screen/Chrome/Specific application.

Kindly direct me if there are any solution or alternatives for the same?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ffdixon** [comment] 2020-07-13 10:15
Unfortunately, at this time, neither Android or iOS support the WebRTC screen sharing APIs within their mobile browsers.

**Comment by basisbit** [comment] 2021-02-08 16:03
It seems like Apple does not want to add screen sharing support to Webkit on iOS devices (requests for comments by journalists are not answered, bug reports are just closed). However, with the current pandemic, lots of institutions bought tons of iPads or Android tablets and handed those to their students and teachers because they are cheaper than the typical school-grade laptops.

To support screen sharing on those devices, a android & iOS app could be developed which does screen sharing and runs in background, while the user continues attending the BBB session in their default webbrowser.

Some initial ideas:
- Write a free/libre open source licensed screen sharing app for typical Android and iOS targets (proprietary apps for this will probably not get the needed BBB API changes / web-ui integration pushed to bbb source code).
- The app shall do screen-sharing in background using WebRTC video streaming
- The video stream shall the sent directly from the users device to the Kurento video handling service of the BigBlueButton server which handles the current meeting the user is attending
- For getting access to the WebRTC signalling port over websocket, the user shall initiate the screen sharing process in the BigBlueButton-html5 web interface
- The bbb-html5 web interface shall detect that the user is using an incompatible device using the `user-agent` string, and then offer the user a `screen sharing on mobile devices` link.
- If the user clicks on the link, it shall open (in a new browser tab) either the website to download the app, or the screen sharing app which registered a URL handler.
- The URL shall include the bbb server address as well as a ID/secret to identify the screen sharing app against Kurento.
- The above process requires addition/modification of the BBB server code and feature-set.
- For the Android & iOS apps, a great chunk of work probably can be reduced by using a framework like for example https://www.ovenmediaengine.com/olk
- The bbb-html5 client should wait a certain amount of time (30 seconds?) for the screen share process to have started, after that, the user has to restart the screen-sharing task in the web UI.
- While the screen is being shared, the user should be able to start other apps, use the bbb-html5 web UI and so on
- The video quality/bitrate and frame rate limits form the bbb-html5 should be complied to. If that is not done automagically over the websocket webrtc signalling, then the settings could be transferred as part of the URL (base64-encoded?)
- The app shall offer a button (and/or something in the notifications bar) so the user can stop the screen sharing.
- When the user leaves the web session or presses the end screen sharing button in the bbb-html5 client, the app should be notified and then the screen sharing shall be stopped.

**Comment by prlanzarin** [comment] 2021-02-08 16:19
> The above process requires addition/modification of the BBB server code and feature-set.

There's theoretically no need of server-side code changes to make a native app work.

> For the Android & iOS apps, a great chunk of work probably can be reduced by using a framework like for example https://www.ovenmediaengine.com/olk

Both iOS and Android have WebRTC SDKs. There's even a mobile-framework variants of it that work rather well AFAIK.

I think that a native app is a question of reverse engineering and implementing the public (undocumented) APIs and data structures of the client, not creating an appendage app that's treated as a 3rd party to a web view.
There's basically four of them (APIs):
  - Meteor/DDP
  - Video
  - Screen sharing
  - Listen only
  - Microphone
  
  Video/SS/LO are rather similar and simple APIs with minor inconsistencies between them due to how they evolved along time.
  Audio has no API per se. You only a couple of things: a SIP stack (there are barebone mobile SIP stacks) and reverse engineering the SIP session parameters.
  Meteor/DDP: the bulk of it. Requires mimicking/reverse engineering client-side state (which is doable) and micking the DDP method calls.
    
  There's a **great** example of what I'm talking about: https://github.com/bennyboer/bbb_app (cc @bennyboer).
  
  Of course the downside of this approach is keeping up with APIs that are undocumented.

**Comment by basisbit** [comment] 2021-02-08 16:28
oh come on, reverse engineering the BBB API and implementing all the web client features and keeping them up to date with BBB web client's changes and detecting which BBB server version is used so the app can adjust its feature set and API to the BBB server,.... is way to much additional work.

The BBB team already has too little amount of free time to resolve the huge amounts of open issues, it imho definitely currently doesn't have the time to develop and maintain for years an additional client which uses different API (not HTML5+Webbrowser API) and different languages and different build tools.

For some use cases, such a bbb app might work, but that is not a solution for the majority of BBB users, and also the BBB-html5 frontend does not point the user to the app (which definitely would require changing BBB code)

**Comment by PhMemmel** [comment] 2021-02-08 17:00
I feel like this problem can/should be addressed by sufficient documentation coverage.

There are a bunch of free apps which allow screen sharing from iPad/iOS/Android easily to a workstation (both Mac and PC, for iOS to Mac this is even possible without any additional software AFAIK).

Sharing the screen is mostly an issue for instructors. Managing a video/web conference is pretty challenging: you need to keep track of re-arriving users, chat messages, hand raising etc. This isn't possible from a mobile device like an iPad or even iPhone when sharing its screen anyway, so in most cases an instructor has to use a workstation for "meeting management" anyway. Sharing the window which contains the shared screen of the mobile device on the workstation is definitely easier than sharing directly from the mobile device (especially when you have to switch between presentation, mobile device "whiteboard" etc.: on workstation just switch between different windows to share). So IMO this "problem" could just be "solved" by good documentation of these possibilities instead of saying "not possible" like it is at the moment.

**Comment by prlanzarin** [comment] 2021-02-08 17:01
> oh come on, reverse engineering the BBB API and implementing all the web client features and keeping them up to date with BBB web client's changes and detecting which BBB server version is used so the app can adjust its feature set and API to the BBB server,.... is way too much additional work for the bbb team.
>
> The BBB team already has too little amount of free time to resolve the huge amounts of open issues, it imho definitely currently doesn't have the time to develop and maintain for years an additional client which uses different API (not HTML5+Webbrowser API) and different languages and different build tools.

If you assert that BBB can't document its APIs, deal with the "huge amount of open issues" nor come up with eg a React native app which reuses a reorganized bbb-html5 and a native WebRTC SDK, why would you think it would have the time to maintain a full fledged stitched behemoth which blends a WebView and offloads video, microphone and screen sharing capturing to external processes? getUserMedia also doesn't work in Safari WKWebViews, which is the only possible way of using web views in apps in iOS. So we have to re-implement audio and camera capture as well.

What you're suggesting looks to me like an intermediate step (coming up with a native BBB-WebRTC SDK and a  native-webview translation layer SDK). Thinking about **definitive** solutions and splitting them into deliverable chunks is always better IMHO if you're making a long term plan. Notice that I don't consider your solution invalid; I just think it should be treated as an intermediate step.

Thinking about an app that is 1st citizen would help the thing go a long way by:
  - Forcing the documentation of the client APIs that are public
  - Forcing stability of the public client APIs
  - Decoupling and modularization of client implementations
  - Decoupling mobile UX experience from the main client
  - Providing a better experience to native app users

Also: open source is also about facilitating decentralization of development and integrating stuff back and forth from upstream and downstream. If we'd get our public **client APIs** in order and documented, we'd give an easier times for folks like the ones from bbb_app to come up with alternative clients which the project could even endorse down the road. That's a goal I think the project would benefit to strive for.

I'm also not a mobile developer so I might be missing something here, but to me both things (reverse engineering and webview blend) seem equally hard to maintain ((as in hard enough, right now)) if you want full feature parity.

**Comment by basisbit** [comment] 2021-02-08 17:22
oh sorry, apparently my suggested solution was not clear enough.
The idea was to still run the bigbluebutton session within the users webbrowser, not within a webview (which does not support webrtc well on majority of devices). Only the screen sharing would have required users to install that third party app and then have it stream the phone's screen in the background (this is supported by iOS and Android)

**Comment by prlanzarin** [comment] 2021-02-08 18:17
Oh, got it. Really got the impression you were talking about a webview when I read video rate control stuff, but it's clear now.

In that case, that would be easier, yes. A bit clunky UX wise, but ok as a transition measure.

> The screen sharing app would be very little amount of code as there exists ready to use frameworks which also support a lot of the signalling stuff of the webrtc standard - only the initiate screen sharing would have to be "reverse engineered" by reading the open source code of bbb.

About the signalling: no end client deals with Kurento's control plane directly in BBB, but bbb-webrtc-sfu over a WebSocket. The API is rather simple and that's the only thing that would need to be re-implemented from the client in regards to media signalling.

Of course, taking for granted that the 3rd party app does have a WebRTC stack available (which is signalling agnostic, so one thing doesn't imply the other). I don't expect it to be _very little amount of code_ because you'll still have to get going whatever incarnation of JSEP the WebRTC wrapper framework of choice offers you, but it won't be much as well. Certainly reasonably larger than the old Chrome plugin (which was basically a net 30 LOCs capture polyfill). And it'll grow larger when you start factoring parallel stuff in like stream reconnections.

**Comment by prlanzarin** [comment] 2021-04-10 00:10
Btw, WKWebView has been shipping support for getUserMedia since late January and it has slowly been trickling down through iOS/iPadOS devices. >=14.2 or .3 I believe, I don't know for sure.

So doing a WKWebView shell app with just a screen capture shim isn't so far fetched as it was a few months ago, because at least we wouldn't need to shim basic things  (cam, mic capture) anymore, just screen.

**Comment by bennyboer** [comment] 2021-07-13 15:45
> 
> 
> > The above process requires addition/modification of the BBB server code and feature-set.
> 
> There's theoretically no need of server-side code changes to make a native app work.
> 
> > For the Android & iOS apps, a great chunk of work probably can be reduced by using a framework like for example https://www.ovenmediaengine.com/olk
> 
> Both iOS and Android have WebRTC SDKs. There's even a mobile-framework variants of it that work rather well AFAIK.
> 
> I think that a native app is a question of reverse engineering and implementing the public (undocumented) APIs and data structures of the client, not creating an appendage app that's treated as a 3rd party to a web view.
> There's basically four of them (APIs):
> 
>     * Meteor/DDP
> 
>     * Video
> 
>     * Screen sharing
> 
>     * Listen only
> 
>     * Microphone
> 
> 
> Video/SS/LO are rather similar and simple APIs with minor inconsistencies between them due to how they evolved along time.
> Audio has no API per se. You only need a couple of things: a SIP stack (there are barebone mobile SIP stacks) and reverse engineering the SIP session parameters.
> Meteor/DDP: the bulk of it. Requires mimicking/reverse engineering client-side state (which is doable) and micking the DDP method calls.
> 
> There's a **great** example of what I'm talking about: https://github.com/bennyboer/bbb_app (cc @bennyboer).
> 
> Of course the downside of this approach is keeping up with APIs that are undocumented.

Since I have more time now I was coming back to this topic. A little late but hey!
I mean yes, it is theoretically possible to do it as the BBB app proves.
Unfortunately in the past month I realized that newer BBB server versions really break the used "inofficial" HTML5 server API a lot. I was forced to introduce some kind of trial and error techniques for example for connecting audio, since in some version it drastically changed. Still I want to support more than the most current BBB server version with the app, as there would not be a point to not doing it.

So what's essentially missing is a way to check what BBB server version we're talking to (#12762), otherwise it's pretty much only being able to support a single BBB server version.

**Comment by kaystrobach** [comment] 2022-03-28 14:18
Maybe @ffdixon can help out with the needed info? 🤔

**Comment by TiagoJacobs** [comment] 2022-03-28 17:33
Hello everyone.

We're working in a mobile application, initially for IOS, but it's react native, so we will eventually add Android too.

This mobile application contains a Broadcast Upload Extension, loads BBB in a webview (with special user agent suffix).

BBB detects this userAgent suffix and replace the webRTC methods by `postMessage` calls.

These calls are then routed to react native, then to SWIFT UI app and then to SWIFT Broadcast Upload Extension app.

It's still an ongoing development, so don't expect to get it ready to use, this comment is more to say: we're working on this!

Some useful links with the ongoing work:
- HTML5 changes draft PR (constantly updated): https://github.com/bigbluebutton/bigbluebutton/pull/14437/files
- Mobile SDK: https://github.com/bigbluebutton/bigbluebutton-mobile-sdk

I'll assign this issue to myself and will post updates here whenever they are available!

**Comment by TiagoJacobs** [comment] 2022-03-29 19:17
And here goes a teaser:
![image](https://user-images.githubusercontent.com/2075267/160690115-13043afc-bc09-4512-b592-0eb45f758543.png)

PS: this works fine while the application is opened, when the app is backgrounded the connection is dropping, it's what we're working to fix right now.

**Comment by kaystrobach** [comment] 2022-03-29 19:38
Are you using the screencast functionality of iOS or something react native specific?

**Comment by TiagoJacobs** [comment] 2022-03-29 21:08
> Are you using the screencast functionality of iOS or something react native specific?

We're using a solution composed of react native (for webview + message handling) and IOS (SWIFT code for the broadcast upload extension + webRTC).

**Comment by kaystrobach** [comment] 2022-03-30 04:20
Awesome (and yes you are using ReplayKit) 👍

Maybe an Safari Extension can catch BBB Websites and suggest to launch the app. 🤔

**Comment by TiagoJacobs** [comment] 2022-04-07 02:53
Good news, now the app works while minimized: 13 minutes minimized and counting!

![image](https://user-images.githubusercontent.com/2075267/162110717-c0f0c367-a4dc-4d57-a134-360fb46f3bfa.png)

PS: next step is to cleanup [this PR](https://github.com/bigbluebutton/bigbluebutton/pull/14437) code and refactor it so it doesn't act when the webRTC call is about audio/video connection.

**Comment by kaystrobach** [comment] 2022-04-07 03:47
Awesome, will there be a Testpilot for interested users?

**Comment by TiagoJacobs** [comment] 2022-04-21 04:48
Hello @kaystrobach - we have the app running in an internal TestFlight since this Monday.
We collected some feedback, did some fixes, and now a new version is available.
I've just clicked in opening the app for a public TestFlight, however, Apple will need to review it. 
I don't know how much time it can take.
As soon as we get a public link, we'll share here.
Looking forward for getting feedback.

**Comment by kaystrobach** [comment] 2022-04-21 06:45
Can you invite me into the testflight? I would be glad to give serious feedback. Is there anything special needed in BBB?

**Comment by dluschan** [comment] 2022-05-24 08:54
Hello.
Screencasting works on the demo server, but not on mine. Can I enable it on my own server?

**Comment by TiagoJacobs** [comment] 2022-06-03 00:33
Hello @dluschan - the PR https://github.com/bigbluebutton/bigbluebutton/pull/14437/files is not yet merged, that's why you can't use in your server yet. Keep an eye on that PR, maybe it will be included in a future 2.4 release.

**Comment by TiagoJacobs** [comment] 2022-06-03 00:35
Hello @TeaObvious we're indeed using a "poor resolution" because the memory limitations of the broadcast upload extension. It's something we can try to improve in upcoming versions.

The thing is that if we increase the resolution, the application crashes (due to high memory usage), but we didn't investigated it extensively yet, maybe there is a solution.

Can you please add a detailed description of this on a new issue, [under this](https://github.com/bigbluebutton/bigbluebutton-mobile) repository?

Thank you!

**Comment by TiagoJacobs** [comment] 2022-06-16 15:08
Hello!
Now the system works with MediaSoup too.
For anyone that tried it with MediaSoup, please try again with the build 11 (available on test flight).

**Comment by TeaObvious** [comment] 2022-06-16 15:32
Hi,

> The thing is that if we increase the resolution, the application crashes (due to high memory usage), but we didn't investigated it extensively yet, maybe there is a solution.

Ahh so its not a bug, its feature to prevent crashes, good to know ^-^

> Can you please add a detailed description of this on a new issue, [under this](https://github.com/bigbluebutton/bigbluebutton-mobile) repository?

Will do as soon as testflight works again for me, i got kicked out of the bbb mobile browser beta.

**Comment by TiagoJacobs** [comment] 2022-08-29 17:09
Hello! 

After a few internal discussions this project is now called BigBlueButton tablet, and because of this change, we had to re-submit it to App Store.

The TestFlight of this new app is available here - https://testflight.apple.com/join/7k0KWvF6

Please give it a try and let us know in case of any problems.

PS: It will work out of the box with any BBB 2.6 server.

**Comment by MahmoudMamdoouh** [comment] 2022-09-06 14:07
> Hello!
> 
> After a few internal discussions this project is now called [BigBlueButton Tablet](https://github.com/bigbluebutton/bigbluebutton-tablet), and due this change, we had to re-submit it to App Store.
> 
> The TestFlight of this new app is available here - https://testflight.apple.com/join/7k0KWvF6
> 
> Please give it a try and let us know in case of any problems.
> 
> PS: It will work out of the box with any BBB 2.6 server.

When can we expect the IOS SDK ?!

**Comment by MahmoudMamdoouh** [comment] 2022-09-06 14:12
> Hello!
> 
> After a few internal discussions this project is now called [BigBlueButton Tablet](https://github.com/bigbluebutton/bigbluebutton-tablet), and due this change, we had to re-submit it to App Store.
> 
> The TestFlight of this new app is available here - https://testflight.apple.com/join/7k0KWvF6
> 
> Please give it a try and let us know in case of any problems.
> 
> PS: It will work out of the box with any BBB 2.6 server.

Awesome. 

When Can we expect the IOS SDK ?

**Comment by dluschan** [comment] 2022-10-12 20:08
I figured out the sequence of actions, but it doesn't work:
https://github.com/bigbluebutton/bigbluebutton-tablet/issues/51

**Comment by antobinary** [comment] 2023-02-14 17:01
> Please give it a try and let us know in case of any problems.
> PS: It will work out of the box with any BBB 2.6 server.

Please open new issues if problems are found.
We will be closing this one.

Good work @TiagoJacobs and team!

**Closed by antobinary** 2023-02-14 17:01 UTC
Labels: type: enhancement
