### ISSUE TITLE
HTML5-Webcam sharing on iOS 11.4 & Safari doesn't work on 2.0-RC1

### ISSUE THREAD

**Issue by Jarvil** [bigbluebutton/bigbluebutton#5765] opened 2018-06-28 11:38 UTC
Hello,

Webcam sharing doesn't work on iOS 11.4 & Safari. Tested on BBB 2.0-RC1. IT gives an error "error loading webcam". @ffdixon

**Comment by ffdixon** [comment] 2018-06-28 11:43
Which BigBlueButton server are you testing against (one that you setup)?  Can you test against

  https://test.bigbluebutton.org/

And let us know the results.  I just tested an iPhone with iOS 11.4 (15F79) with sharing webcam and audio and it worked against the above server.

**Comment by Jarvil** [comment] 2018-06-28 11:48
Hello,

that site doesn't work any better, webcam sharing gives the same error.

**Comment by Jarvil** [comment] 2018-06-28 11:53
The exact error is  "error on sharing webcam"

**Comment by henriquebol** [comment] 2018-06-28 14:06
Same problem here, but with several brands of smartphones. All with android 6.0 and chrome (67.0.33.96.87), only a Motorola G2 loaded the webcam, the others load and load and gives the error "error loading webcam" (also does not appear the motorola G2 webcam in them)

In firefox, all work.

A connection error occurs at https://test.bigbluebutton.org/.

Just confirming something else. The html5 version webcams do not appear in the flash version and the same on the other side. Is that right or is it just here?

**Comment by dahalday** [comment] 2018-07-21 14:57
Hi

I am having the same issue. But I found that the Puffin browser (https://www.puffinbrowser.com/) will works well on iOS and Android. 

I believe that the HTML5 code is still being developed. So we may have a little wait a bit.

**Comment by ffdixon** [comment] 2018-07-22 13:18
The HTML5 client is under (very) active development.  It's being built upon BigBlueButton 2.0.

@dahalday can you tell us more about which device you are using.

**Comment by prlanzarin** [comment] 2018-07-23 21:42
Hey @dahalday and @Jarvil 
Let's try to pinpoint the issue on your devices so we can patch it up and get them to work.
Could you paste the output of both these standard tests on the devices that are failing?
  - https://webrtchacks.github.io/WebRTC-Camera-Resolution/  (Quick Scan option)
  - https://test.webrtc.org/

**Comment by ffdixon** [comment] 2018-07-26 03:57
Hey @dahalday and @Jarvil

Can you test again on

   https://test.bigbluebutton.org/

and let us know the results (we recently applied some updates and want to know the result of testing with your device).

**Comment by dahalday** [comment] 2018-07-27 10:12
Hey  ffdixo 

I tried. No luck on Android Chrome browser

**Comment by ffdixon** [comment] 2018-07-28 13:18
@dahalday, can you respond to Paulo's earlier request for posting the results of testing with

   - https://webrtchacks.github.io/WebRTC-Camera-Resolution/ (Quick Scan option)
   - https://test.webrtc.org/

**Comment by Jarvil** [comment] 2018-08-06 13:15
Hello,

I tested and Webcam and desktop sharing works now with iPad.

**Comment by dahalday** [comment] 2018-08-18 04:36
For windows 10 Chrome see below. I will pass the android results soon

Browser | Device | Res Name | Ratio | Ask | Actual | Status
-- | -- | -- | -- | -- | -- | --
chrome 68 | camera 1 | 4K(UHD) | 16:9 | 3840x2160 | 0x0 | fail: OverconstrainedError
chrome 68 | camera 1 | 1080p(FHD) | 16:9 | 1920x1080 | 0x0 | fail: OverconstrainedError
chrome 68 | camera 1 | UXGA | 4:3 | 1600x1200 | 0x0 | fail: OverconstrainedError
chrome 68 | camera 1 | 720p(HD) | 16:9 | 1280x720 | 1280x720 | pass
chrome 68 | camera 1 | SVGA | 4:3 | 800x600 | 800x600 | pass
chrome 68 | camera 1 | VGA | 4:3 | 640x480 | 640x480 | pass
chrome 68 | camera 1 | 360p(nHD) | 16:9 | 640x360 | 640x360 | pass
chrome 68 | camera 1 | CIF | 4:3 | 352x288 | 352x288 | pass
chrome 68 | camera 1 | QVGA | 4:3 | 320x240 | 320x240 | pass
chrome 68 | camera 1 | QCIF | 4:3 | 176x144 | 176x144 | pass
chrome 68 | camera 1 | QQVGA | 4:3 | 160x120 | 160x120 | pass

**Comment by dahalday** [comment] 2018-08-18 04:40
From my android


Browser | Device | Res Name | Ratio | Ask | Actual | Status
-- | -- | -- | -- | -- | -- | --
chrome 68 | camera 1 | 4K(UHD) | 16:9 | 3840x2160 | 0x0 | fail: OverconstrainedError
chrome 68 | camera 1 | 1080p(FHD) | 16:9 | 1920x1080 | 1080x1920 | fail: mismatch
chrome 68 | camera 1 | UXGA | 4:3 | 1600x1200 | 1200x1600 | fail: mismatch
chrome 68 | camera 1 | 720p(HD) | 16:9 | 1280x720 | 720x1280 | fail: mismatch
chrome 68 | camera 1 | SVGA | 4:3 | 800x600 | 600x800 | fail: mismatch
chrome 68 | camera 1 | VGA | 4:3 | 640x480 | 480x640 | fail: mismatch
chrome 68 | camera 1 | 360p(nHD) | 16:9 | 640x360 | 360x640 | fail: mismatch
chrome 68 | camera 1 | CIF | 4:3 | 352x288 | 288x352 | fail: mismatch
chrome 68 | camera 1 | QVGA | 4:3 | 320x240 | 240x320 | fail: mismatch
chrome 68 | camera 1 | QCIF | 4:3 | 176x144 | 144x176 | fail: mismatch
chrome 68 | camera 1 | QQVGA | 4:3 | 160x120 | 120x160 | fail: mismatch

**Comment by dahalday** [comment] 2018-08-18 04:47
@ffdixon I test at http://test.bigbluebutton.org/. On desktop. webcam and desktop sharing was excellent. on Android webcam did not work. I configure my BBB server to select HTML5 by default. (http://docs.bigbluebutton.org/html/html5-install.html#making-the-html5-client-default) but I could not get webcam or desktop to work in chrome with same BBB build as  http://test.bigbluebutton.org/ even though chrome extension is installed,

**Comment by dahalday** [comment] 2018-08-18 04:49
@prlanzarin both 4G and wifi and LAN gives same results my devices.

**Comment by SivaRI** [comment] 2018-11-09 07:20
Hi.. I tested http://test.bigbluebutton.org/. Screen sharing is ended exactly at 5th mins. Is there any limitations to share the screen.

**Comment by ffdixon** [comment] 2018-11-09 13:04
@SivaRI Don't post the same issue twice (you already posted it here: https://github.com/bigbluebutton/bigbluebutton/issues/6233).  Posting twice doesn't help us solve your problem any faster, and it just makes more work as we have to follow-up in two different areas.

**Comment by dahalday** [comment] 2019-05-01 18:27
Good Day

Congrats to the BBB team. Noted with the update to BBB 2.2  beta 6 that the webcam now works with chrome on some generic Androids where it Only worked on Samsung due to missing codecs prior to this release.  

Interestingly however I am only able to used rare camera on both generic and Samsung. When I attempt to used front camera I get an error code to say that front camera is in used. Can this be looked at?



On the beta5 I  could use front and back camera with Firefox for Android but no cameras at all on chrome for beta 5.

Unfortunately I am not able to used beta 6 BBB html5 client with Firefox on Android. Report message says browser to old. Guess I have to wait for the update

DH

**Comment by capilkey** [comment] 2019-05-01 20:57
The front camera issue should be fixed once the video preview refactor is merged in (#7328).

The mobile Firefox is a regression related to the legacy browser alternate content. I'm going to be submitting a fix shortly that should allow it to load again. I had to add in an entry for "firefoxMobile" and that seems to solve it.

**Comment by dahalday** [comment] 2019-05-01 21:30
Thank you

On May 1, 2019 4:57 PM, Chad Pilkey <notifications@github.com> wrote:

The front camera issue should be fixed once the video preview refactor is merged in (#7328<https://github.com/bigbluebutton/bigbluebutton/pull/7328>).

The mobile Firefox is a regression related to the legacy browser alternate content. I'm going to be submitting a fix shortly that should allow it to load again. I had to add in an entry for "firefoxMobile" and that seems to solve it.

**Comment by ffdixon** [comment] 2019-05-04 00:26
Hey @dahalday and @Jarvil, can you test you webcam again on 

  https://test.bigbluebutton.org/

and let us know if you can now share the front and back camera.

**Comment by dahalday** [comment] 2019-05-04 12:19
Hey @ffdixon. Thank for your reply. I  used https://test.bigbluebutton.org/ on generic android. For Chrome able to use front cam but not back cam this time around. @ffdixon and @capilkey Firefox now works at  https://test.bigbluebutton.org/ but front cam only. Previously with beta 5 I could have used front or back cam with firefox for android. 

@ffdixon issue posted elsewhere regarding delayed echo test  still persist. 

Kind Regards
DH

**Comment by dahalday** [comment] 2019-05-04 14:30
Now got Firefox for Android front and back cameras to share. But still now only Front camera for Chrome Android to share. On Firefox I was promoted many times to allow site to access cameras.

**Comment by ffdixon** [comment] 2019-05-05 02:05
Thanks -- we have a bit more work to do on the access to webcams.

**Comment by ffdixon** [comment] 2019-11-04 10:14
Closing this issue as we added retrieval of video profiles for the webcams in the latest builds on BigBlueButton 2.2-beta.

If anyone reading this thread encounters a similar problem, please test first with

  https://demo.bigbluebutton.org/

and if you encounter an issue, let us know

  https://bigbluebutton.org/support

**Closed by ffdixon** 2019-11-04 10:14 UTC
Labels: HTML5 Client
