### ISSUE TITLE
Config `skipVideoPreviewIfPreviousDevice` is not restoring the device properly

### ISSUE THREAD

**Issue by gustavotrott** [bigbluebutton/bigbluebutton#20765] opened 2024-07-24 13:35 UTC
**Describe the bug**
The config `skipVideoPreviewIfPreviousDevice` is not restoring the device properly after a browser refresh.

**To Reproduce**
1. Set config `.public.kurento.skipVideoPreviewIfPreviousDevice = true`
2. Set config `.public.app.userSettingsStorage = "localStorage"` (not sure if it is necessary)
3. Join in a meeting
4. Click to Share webcam
5. If you have two cameras, select the non-default
6. Select a virtual background
7. Start sharing
8. Refresh the page
9. Click to Share webcam
10. It will start sharing the wrong camera without virtual background

**Expected behavior**
It should share the previous camera and set the same background

**Screenshots**

[Screencast from 2024-07-20 13-53-02.webm](https://github.com/user-attachments/assets/eb02e1b8-6bcc-4ddc-acf2-3b2acbe0314c)

**BBB version:**
BigBlueButton Server 3.0.0-beta.1 (1253)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Browser Chrome

**Comment by germanocaumo** [comment] 2024-07-25 18:10
Should be fixed in https://github.com/bigbluebutton/bigbluebutton/pull/20780
I couldn't reproduce the wrong webcam part, looks like it is because you set "localStorage" instead of 'local' in settings.yml, but I didn't investigate further.

**Closed** 2024-07-26 14:50 UTC
Labels: module: client
