### ISSUE TITLE
Whiteboard Touchscreen/Pen Precision

### ISSUE THREAD

**Issue by cb597** [bigbluebutton/bigbluebutton#9267] opened 2020-04-26 10:33 UTC
**Describe the bug**
Drawing small letters or icons with a pen on a touchscreen when using BBB Whiteboard is nearly impossible. The cursor gets stuck and paints a single dot instead of the desired letter. Larger handwriting gets better.

**To Reproduce**
1. Be presenter in a BBB Meeting, using a touchscreen with pen
2. Click on 'Pencil'
3. Try to draw some letters with the pen on the touchscreen in small size
4. See error, many letters are just dots

**Screenshots**
![Screenshot from 2020-04-26 12-28-17](https://user-images.githubusercontent.com/6097269/80304900-89463280-87b9-11ea-80bb-f7902abf09cc.png)

**BBB version:**
BigBlueButton Server 2.2.5 (1848)

**Desktop:**
 - Device: Surface 6 Pro with Surface Pen
 - OS: Windows 10
 - Browser Chrome Version 80.0.3987.136

**Comment by kendrickluong** [comment] 2020-04-27 06:57
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/9203

**Comment by maflo13** [comment] 2020-05-04 12:23
I confirm the current issue, and i **would strongly suggest the bbb team** to
- set it as bug
- set a high priority on this one

The use of pens at the whiteboard, is one of the new trends everyone is starting to do on all edu video meeting tools, and bbb has this as one of its strong advantages, 
it is a bad not to have that working smoothly, many of our clients have sent that as a strong issue, causing them to leave bbb for other platforms and ways that their pens work smooth

I would like to add on what cb597 said that 
- the delay is increased and the slowness much more strong even when you type large letters when the current session has a lot of cameras on , or when you have the sharing screen on, and surely on internet connections below 2MBIT UPLOAD (2mbit upload is a common ADSL standard in Greece). It looks that when something else is taking the upstream bandwidth the delays on whiteboard are increased, especially when that something is within the chrome browser at another tab

**My setup is**

BBB version:
BigBlueButton Server 2.2.2 (1781)

Desktop:

Device: Huwaei Matebook tablet, Wacom Intuos
OS: Windows 10
Browser Chrome Version 80.0.3987.132

**Comment by pedrobmarin** [comment] 2021-04-09 21:20
v2.3 has a couple of performance improvements for the whiteboard. If the problem persists we can iterate over a new issue.

**Closed by pedrobmarin** 2021-04-09 21:20 UTC
Labels: module: client
