### ISSUE TITLE
iPhone no audio when breakout room ends and after users returning back to the video conference

### ISSUE THREAD

**Issue by fwu2012** [bigbluebutton/bigbluebutton#9109] opened 2020-04-16 10:09 UTC
Everything works when iPhone users join the video, and it's fine when entered the breakout room. However, at the end of the breakout meeting, when the users tried to return and got back to the video conference, these iPhone users couldn't hear the meeting host. But the meeting host could hear the voice of the iPhone users.

iPhone 7 plus (same problems with other iPhones)
iOS 13.3.1

**Comment by JonasHeidemann** [comment] 2020-04-23 08:30
We had the exact same problem!

**Comment by frank-miller9** [comment] 2020-04-30 09:48
See: https://github.com/bigbluebutton/bigbluebutton/issues/8857

**Comment by fwu2012** [comment] 2020-04-30 09:54
> See: #8857

Thanks for sharing the issue tracking on #8857

**Comment by prlanzarin** [comment] 2021-04-05 00:55
Duplicate of #8857

(and I'm pretty sure this was fixed in WebKit in Safari 14.something; a few months ago. It was a WebKit [and hence Blink] issue)

**Closed by prlanzarin** 2021-04-05 00:55 UTC
