### ISSUE TITLE
Voice Disconnect on changing language

### ISSUE THREAD

**Issue by farbod302** [bigbluebutton/bigbluebutton#11091] opened 2020-12-29 10:12 UTC
Hi
I change the default language of client to "fa" (Persian)
I can connect to voice Bridge successfully of the beginning without any issue
But when client language change to English manually I can't hear anyone .

Notice that I still connected to voice Bridge and others can hear me

&& fixed with disconnect and reconnect to voice bridge

 Please keep connection alive on change language

bbb-v:22

**Comment by antobinary** [comment] 2021-02-08 21:39
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/8410

**Closed by antobinary** 2021-02-08 21:39 UTC
Labels: HTML5 Client
