### ISSUE TITLE
Huge number of open ports which BBB want to be used

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#10689] opened 2020-10-21 11:30 UTC
**Describe the bug**
There are a huge number of open UDP ports for BBB usage which noted at below:
UDP ports in the range 16384 - 32768 (for FreeSWITCH/HTML5 RTP streams)
This is an issue which we can not specialized the ports.
Is there any solution for just 60 person user for BBB usage? I mean when we have just 60 users (in company) and we want to connect to one foreign BBB serve, could we open just some specific UDP ports?
 
**Installation type**
Follow the user guide

**Firewall and IP address type**
Is your server behind a NAT or firewall? Does your BBB server have its own IPv4 addres?
Yes

**Comment by matiasilva** [comment] 2020-10-21 14:29
I suggest you consult FreeSWITCH and/or WebRTC documentation to see if you can close those ports. My guess would be no, because they are open for a reason.

**Comment by prlanzarin** [comment] 2020-10-21 14:49
This is just the default (safe) port range. It's not a requirement (and we do not state so). You can change it to whatever range you want (as long as it's not in the reserved range).
See https://docs.bigbluebutton.org/2.2/customize.html#change-udp-ports.

Closing this as it's not an issue.

**Closed by prlanzarin** 2020-10-21 14:49 UTC

**Comment by cod3r0k** [comment] 2020-10-21 16:30
> This is just the default (safe) port range. It's not a requirement (and we do not state so). You can change it to whatever range you want (as long as it's not in the reserved range).
> See https://docs.bigbluebutton.org/2.2/customize.html#change-udp-ports.
> 
> Closing this as it's not an issue.

Thank you @prlanzarin @matiasilva , Can we just open 100 of them?  (e.g we have just 100 member) ? Is it possible and whenever anyone wants to connect and use one of them automatically?

**Comment by prlanzarin** [comment] 2020-10-21 18:22
It really depends on a **lot** of moving pieces to determine how many UDP ports you need (not only  # of users). As it is, media is not relayed through a single socket through max bundling, so it's not even close to a 1:1 proportion.
My suggestion is to overestimate it, a lot. And have the worst case scenario in mind. 100 ports is too small a range for a BBB server (even more when we're talking about 60 concurrent users). If you have such a restrictive firewall, I suggest relying on TURN (which makes clients relay media through 443 at the expense of increased latency). 

But, first of all, I don't quite follow where the problem is: in the client side firewall (ie your company) or the BBB server (the host). If the problem is only in the client side, set up a TURN server in BBB and you can forget about dealing with the company firewall if you tolerate the increased latency/extra infrastructure piece.
