### ISSUE TITLE
Minimize presentation for all the participants if the moderator does it

### ISSUE THREAD

**Issue by pbdco** [bigbluebutton/bigbluebutton#9937] opened 2020-06-25 14:09 UTC
It would be great if the presentation minimizes/hides for all the connected users in the meeting, if the moderator does it. This feature would work similarly to the zoom/pan functions (if moderator changes them, all the users see the changes).

We have several meetings on wich the presentation is not used or needed at all, and if users that are new into BBB system have to figure out how to minimize it to change the full screen / gallery view to see all the participants.

Frequently several users doesn't figure out at all how to minimize it and they watch the whole meeting with the presentation unnecessarily on. This happens mostly when they enter to the meeting late so they missed the explanation/recommendation from the moderator to do it.

Turning it off completely ( autoSwapLayout: true // hidePresentation ) is not an option for us because we have the opposite scenario on which we need to the meetings to start with the presentation on. So having this feature would be the best for each meeting requirement and very useful.

Related to #9862

**Comment by ffdixon** [comment] 2020-07-13 01:53
We're thinking about how to best do this in BigBlueButton -- either auto hide the presentation for students or provide a UI where the teacher can apply their current state to all viewers.

We intend to implement one of these options in an upcoming release (no date set).

**Comment by pbdco** [comment] 2020-07-13 02:53
Thanks Fred! I think this will be a great improvement for many users.
Thank you guys! Keep it up with the great work 💪  We hope to see upcoming release soon 🙏  🤩  🙌

**Comment by matiasilva** [comment] 2020-07-13 10:30
The second suggestion is basically #7987. Disabling the presentation is already possible with https://docs.bigbluebutton.org/2.2/customize.html#layout-parameters. This is configurable per join API call, meaning per user.

**Comment by pbdco** [comment] 2020-07-13 13:56
Hi Matias, yes, but the pain starts when we need to open/hide the presentation several times during the same meeting. This is why moderator should have control over UI state for all viewers.

**Comment by matiasilva** [comment] 2020-07-13 14:32
Yeah, but this is essentially a duplicate of #7987, right?

**Comment by pbdco** [comment] 2020-07-13 15:38
Yes, we are on the same boat as Fred's request.

**Comment by matiasilva** [comment] 2020-07-13 15:40
I see, so I will just merge with #7987 for organization.

**Closed by matiasilva** 2020-07-13 15:40 UTC
Labels: Enhancement
