### ISSUE TITLE
Processing failed - Directory not empty

### ISSUE THREAD

**Issue by JGallot** [bigbluebutton/bigbluebutton#8867] opened 2020-03-25 09:11 UTC
When recording is processing, it always failed because of a directory which is not empty. But i see no file in it.

I've got this error in the logs : 
E, [2020-03-24T23:31:53.484654 #32183] ERROR -- : Directory not empty @ dir_s_rmdir - /var/bigbluebutton/recording/publish/presentation/c42b0fa8c934b3b0aa1245bca9fcbe1021fe1c27-1585088550960/c42b0fa8c934b3b0aa1245bca9fcbe1021fe1c27-1585088550960
E, [2020-03-24T23:31:53.484711 #32183] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1445:in `rmdir'
E, [2020-03-24T23:31:53.484738 #32183] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1445:in `block in remove_dir1'
E, [2020-03-24T23:31:53.484817 #32183] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1456:in `platform_support'
E, [2020-03-24T23:31:53.484840 #32183] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1444:in `remove_dir1'
E, [2020-03-24T23:31:53.484860 #32183] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1437:in `remove'
E, [2020-03-24T23:31:53.484880 #32183] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:779:in `block in remove_entry'
E, [2020-03-24T23:31:53.484912 #32183] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1494:in `postorder_traverse'
E, [2020-03-24T23:31:53.484933 #32183] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:777:in `remove_entry'
E, [2020-03-24T23:31:53.484952 #32183] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:635:in `block in rm_r'
E, [2020-03-24T23:31:53.484972 #32183] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:631:in `each'
E, [2020-03-24T23:31:53.484992 #32183] ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:631:in `rm_r'
E, [2020-03-24T23:31:53.485011 #32183] ERROR -- : publish/presentation.rb:1377:in `<main>'
E, [2020-03-24T23:31:53.485047 #32183] ERROR -- : exit
E, [2020-03-24T23:31:53.485089 #32183] ERROR -- : publish/presentation.rb:1383:in `exit'
E, [2020-03-24T23:31:53.485148 #32183] ERROR -- : publish/presentation.rb:1383:in `rescue in <main>'
E, [2020-03-24T23:31:53.485192 #32183] ERROR -- : publish/presentation.rb:1203:in `<main>'

Thanks for help

**Comment by hex-m** [comment] 2020-05-13 14:32
Are your recordings on NFS? Could be a duplicate of #9062.

**Comment by matiasilva** [comment] 2020-06-17 23:19
No follow up. Feel free to post to https://groups.google.com/forum/#!forum/bigbluebutton-users for further help.

**Closed by matiasilva** 2020-06-17 23:19 UTC
Labels: Recording
