### ISSUE TITLE
Many files in bbb root folder

### ISSUE THREAD

**Issue by sudanking** [bigbluebutton/bigbluebutton#20714] opened 2024-07-16 22:56 UTC
After each recording I find many folders in bbb folder (/var/bigbluebutton/) (Pic attached)
it is content the same folder in raw/{meetingid}/presentation/ 
I dont know why it is created there?

I process only video ( I stop keeping presentation)

![image](https://github.com/user-attachments/assets/077f4530-dd01-4230-a913-942ed83b7acf)

**Comment by antobinary** [comment] 2024-07-18 13:46
Hi @sudanking 
Here's some information on what the files in various recording related directories are: https://docs.bigbluebutton.org/2.7/development/recording/#media-storage

What you describe is not an issue, it's how BigBlueButton's recording system works by design. You can also transfer these files (or delete them if not needed) so they don't clutter your server.

I hope this helps! I will be closing this issue as it's not exactly an issue with the software.

**Closed by antobinary** 2024-07-18 13:46 UTC
Labels: module: core
