### ISSUE TITLE
Audio Issue

### ISSUE THREAD

**Issue by nplesa** [bigbluebutton/bigbluebutton#8960] opened 2020-04-02 10:19 UTC
Hi , We are using BBB version 2.2.
The system is working fine except an audio issue that we can not properly identify:

During the conference, before someone start speaking we can hear a small noise (half second) .
We usually don't hear this noise when someone speaks continuously but it appears as soon as it stop and speak again.
We don't know where this issue comes from and it is not related to the server hardware performance/bandwidth.

**Comment by mtsonline** [comment] 2020-04-07 13:01
seems to be relatet to #7007

**Comment by basisbit** [comment] 2020-06-02 01:34
Duplicate of #7007

**Closed by basisbit** 2020-06-02 01:34 UTC
