### ISSUE TITLE
Can't close the echo test.

### ISSUE THREAD

**Issue by JulienPalard** [bigbluebutton/bigbluebutton#12427] opened 2021-05-21 09:48 UTC
**Describe the bug**

On my machine the echo test is slow (https://github.com/bigbluebutton/bigbluebutton/issues/8824), and when I know my setup works, I'd gladly skip it.

But the `(X)` button on the top right of the windows does nothing.

**To Reproduce**
1. Join a room
2. Try to close the echo test window **before** it connected to the echo service

**Expected behavior**
I'd expect to join the room instantaneously, with microphone muted.

**Actual behavior**
Nothing happen, I have to wait for the echo server to connect in order to click this button, which takes like 20s on my setup.

**BBB version (optional):** 2.3.0 (2148)

**Desktop (please complete the following information):**
 - OS: Debian bullseye
 - Browser: Firefox 88.0.1

**Additional context**

Thanks for BBB, I have to use it often, and it works like a charm. I really enjoy using it, thank a lot and congratulations for all the work. ♥

**Comment by mk-hs** [comment] 2021-05-28 11:29
That's usually caused by a routing error.
Are you able to reproduce this on https://test23.bigbluebutton.org ?

**Comment by JulienPalard** [comment] 2021-05-28 15:13
Yes, during the "Connecting to the echo test ..." phase, the `(X)` button is unresponsive: I can't skip the echo test, even if I know my microhpone works (in case I was in the room one minute before for example, on in cases I'm switching from subrooms to subrooms).

**Comment by JulienPalard** [comment] 2021-05-28 15:15
What I would really like is to bind the `Esc` key to the `(X)` button, so I can switch from subrooms to subrooms really fast, without even having to focus the X :]

**Comment by antobinary** [comment] 2021-05-28 16:35
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/7903
The desire is to have this resolved and shipped as a patch to 2.3.x

**Closed by antobinary** 2021-05-28 16:35 UTC
Labels: module: client

**Comment by JulienPalard** [comment] 2021-05-29 14:26
> While "Connecting to echo test" is being shown your browser isn't trying to access the echo test

Maybe it could be rephrased then?
