### ISSUE TITLE
Download the current slide produces broken image

### ISSUE THREAD

**Issue by bugeater17** [bigbluebutton/bigbluebutton#21818] opened 2024-12-04 06:34 UTC
Download the current slide inside a conference produces a broken image.

**To Reproduce**
1. Start a conference
2. Click on the three dots in the left upper corner
3. Click on "Snapshot of current slide"
4. The broken image will be downloaded

**Screenshots**
![test27](https://github.com/user-attachments/assets/6ddd9df6-281a-4d51-a25b-0a9c1502f7fa)
![Presentation_Testraum_2024-12-04T06_32_01 254Z](https://github.com/user-attachments/assets/ba58525b-8b3b-44e1-9b93-da5154dccd72)

**BBB version:**
tested at https://test27.bigbluebutton.org/
and on our server on BigBlueButton 2.7.15

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Firefox

**Comment by antobinary** [comment] 2024-12-04 14:15
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/18739
BBB 2.7.16 will contain the patch.

**Closed by antobinary** 2024-12-04 14:15 UTC
Labels: module: client
