### ISSUE TITLE
Support export to PDF for shared notes in 2.3-dev

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#11251] opened 2021-01-28 11:33 UTC
**Is your feature request related to a problem? Please describe.**
In BigBlueButton 2.3-dev we isolate Libreoffice to run within a docker container to restrict it its capabilities.  

While the export to PDF option is disabled by default in Etherpad, a side effect is that Etherpad does not have the ability to directly call Libreoffice to convert a document to PDF if this option is enabled.

**Describe the solution you'd like**
A solution to enable an administrator to enable the export to PDF option in Etherpad and have it work.

**Describe alternatives you've considered**
More investigation needed on how to accomplish this.  At the moment, this is a low priority (but worthwhile to track) as we're not enabling export to PDF by default in Etherpad.

**Comment by ratondeau** [comment] 2021-01-28 11:53
As a workoround I installed abiword and changed the following lines in the config file /usr/share/etherpad-lite/settings.json

"soffice": null,
"abiword": "/usr/bin/abiword",

Its working nicely!

**Comment by basisbit** [comment] 2021-01-30 01:56
@ffdixon maybe a duplicate of #10778 ?

**Comment by antobinary** [comment] 2021-03-06 17:33
Merging into  #10778

**Closed by antobinary** 2021-03-06 17:33 UTC
Labels: Enhancement
