### ISSUE TITLE
2.4 - Rooms list continues to be displayed after are closed

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#12623] opened 2021-06-18 17:17 UTC
**Describe the bug**
After create breakout rooms, a list with them is available (for all users if this option has been enabled or just for moderators if not). When the rooms are closed, it's expected that the list will be closed, but it keeps showing to users - _with the remaining time stopped_;
_Note: tested on v2.3 and it works right_

**To Reproduce**
1. Create breakout rooms
2. with another user that can choose a room, open the list
3. end the breakout rooms

**Expected behavior**
The rooms list will be closed

**Actual behavior**
List keep open after all rooms are closed

**Video**

https://user-images.githubusercontent.com/56703993/122593805-8dc44f00-d03c-11eb-9351-38f18e9229b6.mp4

**Comment by antobinary** [comment] 2021-06-18 17:42
Possible duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/12581

**Closed** 2021-07-19 20:25 UTC
Labels: module: client
