### ISSUE TITLE
Downloading recorded files

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/bigbluebutton#9428] opened 2020-05-05 17:04 UTC
Greenlight allows operate with recorded materials, however there's missing option to download them for further processing. Greenlight developers refer to BBB functionality.

Please, add the functionality to download recordings from the server to my local work station for further processing.

Now this may be done using some 3rd party browser extensions only, what is not convenient.

**Comment by rasos** [comment] 2020-06-11 10:16
Here is a script uploading recordings to OpenCast https://weblog.lkiesow.de/20200318-integrate-bigbluebutton-opencast/

Genuine downloading would be perfect, though.

**Comment by matiasilva** [comment] 2020-06-14 23:05
Duplicate of #1969. The OpenCast recommendation is quite nice.

**Closed by matiasilva** 2020-06-14 23:05 UTC
Labels: Enhancement
