### ISSUE TITLE
2.3-beta-2: Edge not Working - "The token provided ('browser-microsoft edge') contains HTML space characters, which are not valid in tokens."

### ISSUE THREAD

**Issue by laserrapt0r** [bigbluebutton/bigbluebutton#11923] opened 2021-04-07 14:25 UTC
Fresh installation of BigBlueButton v2.3 does not work in new Edge Browser. The Frontend does not load.

The console gives this error message:

DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('browser-microsoft edge') contains HTML space characters, which are not valid in tokens.

**Comment by prlanzarin** [comment] 2021-04-07 14:29
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11865

**Closed by prlanzarin** 2021-04-07 14:29 UTC
Labels: module: client
