### ISSUE TITLE
External video sync requests to pause and resume are ignored

### ISSUE THREAD

**Issue by vlasov01** [bigbluebutton/bigbluebutton#9576] opened 2020-05-17 11:55 UTC
**Describe the bug**

**To Reproduce**
1. Start two clients
2. Share an external video from client 1 (presenter)  https://www.youtube.com/watch?v=Q2tG2SS4gXA&t=294s
3. Video starts playing on both clients
4. Pause the video from client 1 (presenter)

**Expected behavior**
The video in both clients should pause.

**Actual behavior**
The video in client 1 (presenter) will pause, but the video in client 2 will keep playing.

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.11 (1928)

Kernel version: 4.4.0-178-generic
Distribution: Ubuntu 16.04.6 LTS (64-bit)

BBB HTML Client 910

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome  81.0.4044.138, Firefox 76.0.1

**Additional context**
Resume play is not synchronized as well from client 1 (presenter) and client 2.
Closing video sharing is synchronized between client 1 (presenter) and client 2.

I've noticed the following error when video sharing starts in /var/log/bbb-apps-akka/bbb-apps-akka.log
```
2020-05-17T09:44:04.315-04:00 INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"VoiceConfCallStateEvtMsg","routing":{"voiceConf":"00015442037698390"},"timestamp":1589723044312},"core":{"header":{"name":"VoiceConfCallStateEvtMsg","voiceConf":"00015442037698390"},"body":{"voiceConf":"00015442037698390","callSession":"e2cb05ce-2ac3-4fb7-95fc-1f64b0f791cd","clientSession":"0","userId":"","callerName":"21","callState":"CALL_STARTED","origCallerIdName":"21","origCalledDest":"00015442037698390"}}}
2020-05-17T09:44:04.316-04:00 INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"VoiceConfCallStateEvtMsg","routing":{"voiceConf":"00015442037698390"},"timestamp":1589723044314},"core":{"header":{"name":"VoiceConfCallStateEvtMsg","voiceConf":"00015442037698390"},"body":{"voiceConf":"00015442037698390","callSession":"e2cb05ce-2ac3-4fb7-95fc-1f64b0f791cd","clientSession":"0","userId":"","callerName":"21","callState":"CALL_ENDED","origCallerIdName":"21","origCalledDest":"00015442037698390"}}}
2020-05-17T09:44:05.395-04:00 ERROR o.b.c.p.s.ReceivedJsonMsgHandlerActor - Cannot route envelope name StartExternalVideoMsg
```

I've noticed the following error when video sharing stops in /var/log/bbb-apps-akka/bbb-apps-akka.log
```
2020-05-17T09:44:26.639-04:00 INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"VoiceConfCallStateEvtMsg","routing":{"voiceConf":"8884660046406820601"},"timestamp":1589723066636},"core":{"header":{"name":"VoiceConfCallStateEvtMsg","voiceConf":"8884660046406820601"},"body":{"voiceConf":"8884660046406820601","callSession":"e2cb05ce-2ac3-4fb7-95fc-1f64b0f791cd","clientSession":"0","userId":"","callerName":"101","callState":"CALL_STARTED","origCallerIdName":"101","origCalledDest":"8884660046406820601"}}}
2020-05-17T09:44:26.639-04:00 INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"VoiceConfCallStateEvtMsg","routing":{"voiceConf":"8884660046406820601"},"timestamp":1589723066637},"core":{"header":{"name":"VoiceConfCallStateEvtMsg","voiceConf":"8884660046406820601"},"body":{"voiceConf":"8884660046406820601","callSession":"e2cb05ce-2ac3-4fb7-95fc-1f64b0f791cd","clientSession":"0","userId":"","callerName":"101","callState":"CALL_ENDED","origCallerIdName":"101","origCalledDest":"8884660046406820601"}}}
2020-05-17T09:44:32.343-04:00 INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"VoiceConfCallStateEvtMsg","routing":{"voiceConf":"680972595168471"},"timestamp":1589723072340},"core":{"header":{"name":"VoiceConfCallStateEvtMsg","voiceConf":"680972595168471"},"body":{"voiceConf":"680972595168471","callSession":"e2cb05ce-2ac3-4fb7-95fc-1f64b0f791cd","clientSession":"0","userId":"","callerName":"209","callState":"CALL_STARTED","origCallerIdName":"209","origCalledDest":"680972595168471"}}}
2020-05-17T09:44:32.343-04:00 INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"VoiceConfCallStateEvtMsg","routing":{"voiceConf":"680972595168471"},"timestamp":1589723072340},"core":{"header":{"name":"VoiceConfCallStateEvtMsg","voiceConf":"680972595168471"},"body":{"voiceConf":"680972595168471","callSession":"e2cb05ce-2ac3-4fb7-95fc-1f64b0f791cd","clientSession":"0","userId":"","callerName":"209","callState":"CALL_ENDED","origCallerIdName":"209","origCalledDest":"680972595168471"}}}
2020-05-17T09:44:34.070-04:00 ERROR o.b.c.p.s.ReceivedJsonMsgHandlerActor - Cannot route envelope name StopExternalVideoMsg
```

I've noticed the following warnings/errors in the client 1 browser' console logs when the external video started:

```
Feature Policy: Skipping unsupported feature name “accelerometer”. www-widgetapi.js:366:241
Feature Policy: Skipping unsupported feature name “autoplay”. www-widgetapi.js:366:241
Feature Policy: Skipping unsupported feature name “encrypted-media”. www-widgetapi.js:366:241
Feature Policy: Skipping unsupported feature name “gyroscope”. www-widgetapi.js:366:241
Feature Policy: Skipping unsupported feature name “picture-in-picture”. www-widgetapi.js:366:241
Feature Policy: Skipping unsupported feature name “accelerometer”. www-widgetapi.js:369:30
Feature Policy: Skipping unsupported feature name “autoplay”. www-widgetapi.js:369:30
Feature Policy: Skipping unsupported feature name “encrypted-media”. www-widgetapi.js:369:30
Feature Policy: Skipping unsupported feature name “gyroscope”. www-widgetapi.js:369:30
Feature Policy: Skipping unsupported feature name “picture-in-picture”. www-widgetapi.js:369:30
Feature Policy: Skipping unsupported feature name “accelerometer”. www-widgetapi.js:354:336
Feature Policy: Skipping unsupported feature name “autoplay”. www-widgetapi.js:354:336
Feature Policy: Skipping unsupported feature name “encrypted-media”. www-widgetapi.js:354:336
Feature Policy: Skipping unsupported feature name “gyroscope”. www-widgetapi.js:354:336
Feature Policy: Skipping unsupported feature name “picture-in-picture”. www-widgetapi.js:354:336
Some cookies are misusing the recommended “sameSite“ attribute 5
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed).

Loading failed for the <script> with source “https://static.doubleclick.net/instream/ad_status.js”. Q2tG2SS4gXA:1:1
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead.
```

And the following two errors in  the client 2 browser' console logs when the external video started:
```
Exception in onResRdy: TypeError: Cannot read property 'htmlRes' of undefined
Q2tG2SS4gXA?autoplay=1&mute=0&controls=2&start=294&origin=https%3A%2F%2Flearn.goevrika.com&playsinline=1&showinfo=0&rel=0&iv_load_policy=3&modestbranding=1&autohide=1&ecver=2&enablejsapi=1&widgetid=3:1 

Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
```

The issue seems similar to [External video sync requests are ignored after losing presenter #8044] (https://github.com/bigbluebutton/bigbluebutton/issues/8044) , which was fixed in [#8110](https://github.com/bigbluebutton/bigbluebutton/pull/8110)

And I think there are some related information about StartExternalVideoMsg / StopExternalVideoMsg in [Syncrhonized Youtube video player for meetings (WIP) #6372](https://github.com/bigbluebutton/bigbluebutton/pull/6372) which was closed in [Stop syncronized video sharing if presenter leaves #6596](https://github.com/bigbluebutton/bigbluebutton/issues/6596)

**Comment by lfzawacki** [comment] 2020-05-18 18:06
These akka logs are not relevant to the problem, as far as I know they always did that because akka-apps does not process the external video messages. The relevant messages are on the html5 server and client logs, make sure to set the log level to debug and test again. I tested on the latest version installed locally and haven't seen the same behavior.

**Comment by vlasov01** [comment] 2020-05-19 02:10
Hi Lucas,

Thank you for the prompt response!
I've enabled debug by modifying /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml and setting the following log parameters:
```
  clientLog:
    server: {enabled: true, level: debug}
    console: {enabled: true, level: debug}
    external: {enabled: false, level: info, url: 'https://LOG_HOST/html5Log', method: POST,
      throttleInterval: 400, flushOnClose: true, logTag: ""}
```
And I've restarted bbb: 
```
bbb-conf --clean
Restarting BigBlueButton 2.2.11 (and cleaning out all log files) ...
Stopping BigBlueButton
 ... cleaning log files
Starting BigBlueButton
....................
#    /usr/share/red5/log/sip.log not found
#    /usr/share/red5/log/video.log not found
#    /usr/share/red5/log/bigbluebutton.log not found
#    /usr/share/red5/log/screenshare-slf.log not found


# Potential problems described below
# Not running:  tomcat7 or grails
....................# Error: Red5 log files not found

# Unavailable red5 logs (/usr/share/red5/log):  bigbluebutton.log sip.log video.log screenshare-slf.log

# Error: The following log file was not found
#   /usr/share/red5/log/sip.log

#      No /usr/share/red5/log/bigbluebutton.log
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://learn.goevrika.com/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

```
And now the external video synchronization started working.

I've restored the original log settings and again reloaded bbb.

```
bbb-conf --clean
Restarting BigBlueButton 2.2.11 (and cleaning out all log files) ...
Stopping BigBlueButton
 ... cleaning log files
Starting BigBlueButton
....................
#    /usr/share/red5/log/sip.log not found
#    /usr/share/red5/log/video.log not found
#    /usr/share/red5/log/bigbluebutton.log not found
#    /usr/share/red5/log/screenshare-slf.log not found


# Potential problems described below
# Not running:  tomcat7 or grails
....................# Error: Red5 log files not found

# Unavailable red5 logs (/usr/share/red5/log):  bigbluebutton.log sip.log video.log screenshare-slf.log

# Error: The following log file was not found
#   /usr/share/red5/log/sip.log

#      No /usr/share/red5/log/bigbluebutton.log
.........................................

```
And the synchronization still working.

**Comment by lfzawacki** [comment] 2020-05-19 13:38
There are some situations where synchronization could stop working, but I've mostly seen them on a development environment (if meteor reloads the code while an external video is shared). If you can reproduce a situation where it does not work again please get the logs and include them here.

**Comment by vlasov01** [comment] 2020-05-19 22:40
Very good. I'll try to reproduce the issue again.

**Comment by enaut** [comment] 2021-02-26 20:38
hey @lfzawacki With the latest 2.3-dev build I have the problem that chrome ignores the playback sync signals of firefox... and vice versa. is that a known problem or can I help tackle it down? - I'm not so sure on what logs to enable and where to look for errors and such.

**Comment by antobinary** [comment] 2021-02-27 15:43
@enaut Yes, what you describe in 2.3-alpha7 is fixed in https://github.com/bigbluebutton/bigbluebutton/pull/11447, expected to ship within a week or so. Thanks for reporting

**Comment by enaut** [comment] 2021-02-27 16:16
You are an angel for doing so!

**Closed** 2021-03-06 18:06 UTC
Labels: HTML5 Client
