### ISSUE TITLE
Locking the microphone control in a meeting does not have effect on dial-in users

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#4787] opened 2017-12-08 19:57 UTC
Desired behavior:
When a moderator applies lock settings for microphone in the session the dial-in user should become muted.
The dial-in user should not be able to unmute themselves (currently able to mute/unmute freely via pressing '0' on the dialpad)

**Comment by ritzalam** [comment] 2017-12-20 21:34
Fixed in https://github.com/bigbluebutton/bigbluebutton/commit/b8af2fd5ee8badd8713faf09471142f083239959

**Comment by ritzalam** [comment] 2017-12-20 21:36
For pressing "0", we don't know if that was the cause of the unmute event, so we cannot check for it in akka-apps.

**Comment by ffdixon** [comment] 2019-09-10 03:16
Tested in the latest build of BigBlueButton 2.2-beta and when lock settings is Microphone

![image](https://user-images.githubusercontent.com/290351/64581362-c7403480-d357-11e9-8e4b-9aa1e7270ff2.png)

A user dialing into the conference still joins as unmuted and can mute/unmute themselves by pressing the '0' key on their phone's keyboard.

**Comment by sonerd** [comment] 2020-12-02 08:20
I can confirm that the dial-in user can unmute by pressing '0'

**Comment by lonesomewalker** [comment] 2020-12-09 11:33
Pushing it again, still not fixed.
Dial-in users are out of control in this case.

**Comment by ritzalam** [comment] 2020-12-09 15:21
We should expand this to handle dial-in users.

https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/akka-bbb-apps/src/main/scala/org/bigbluebutton/LockSettingsUtil.scala#L46

**Closed** 2022-02-25 14:10 UTC
Labels: module: core, module: audio, type: bug
