### ISSUE TITLE
Customize Css / hide features

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/bigbluebutton#8922] opened 2020-03-30 14:08 UTC
Hello, i want to custom the css from the html5 client, where can i add a custom.css file or something like that.

Thanks

Edit: I want to add the custom css to hide this option, http://prntscr.com/rokh7j i dont want to moderators be able to modify that option becouse it will consume a lot of bandwith having multiple cameras and its something that i cant afford, so is there a way to hide that option on the client? trough css or somethin? thanks

**Comment by iSamof** [comment] 2020-03-30 14:38
There are several discussions about CSS/JavaScript control of the UI and even a layout editor. Just search the issues for "layout". Here is a good post by Fred:

[https://github.com/bigbluebutton/bigbluebutton/issues/5836#issue-339267322](https://github.com/bigbluebutton/bigbluebutton/issues/5836#issue-339267322)

And your idea is extremely helpful to managers especially if it is not server wide but is open for UI builders (e.g. using the future layout editor) to control the display per layout and/or user account - the latter is not a BBB issue as long as the display control is not on/off server-wide.

**Comment by basisbit** [comment] 2020-06-08 13:00
Duplicate of #5836

**Closed by basisbit** 2020-06-08 13:00 UTC
Labels: HTML5 Client
