### ISSUE TITLE
BUG To publish record - "undefined method `text' for nil:NilClass"

### ISSUE THREAD

**Issue by rriscado** [bigbluebutton/bigbluebutton#9716] opened 2020-05-29 14:53 UTC
I found an error while publishing the recording.

Some text boxes needed to be removed from the events.xml file for the publication proccess to be finished.

**The folow text IDs was removed.**
ID w_r81u9kvwvcuj-12-1590614781387
ID w_foxqpff2dd58-17-1590614803020
ID w_r81u9kvwvcuj-13-1590614805560
ID w_foxqpff2dd58-16-1590614794699

Attached publish log and event.xml

[publish-9172515742a65c68f07f36d028a6018b16c94bb2-1590607363685.log](https://github.com/bigbluebutton/bigbluebutton/files/4702480/publish-9172515742a65c68f07f36d028a6018b16c94bb2-1590607363685.log)

[events.xml.txt](https://github.com/bigbluebutton/bigbluebutton/files/4702485/events.xml.txt)

**Comment by ffdixon** [comment] 2020-05-29 20:05
What version are you using?   We had a fix for this about a month ago : https://github.com/bigbluebutton/bigbluebutton/pull/8999 and it's in 2.2.14.

**Comment by kepstin** [comment] 2020-05-29 20:10
This issue is a duplicate of #9621

**Closed** 2020-05-29 20:11 UTC
Labels: Recording
