### ISSUE TITLE
bbb-conf can't read a stun-server from turn-stun-servers.xml when more than one stun-server is defined

### ISSUE THREAD

**Issue by gizmo1-11** [bigbluebutton/bigbluebutton#12416] opened 2021-05-20 08:01 UTC
If you define more than one stun-server in the turn-stun-servers.xml, then bbb-conf doesnt read any,
because the parsing fails
bbb-conf throws an error, that it was not able to connect to the stun-server

echo "# Warning: Failed to verify STUN server at $STUN_SERVER with command"

It's because the variable $STUN_SERVER is empty

What about more than one turn-server ?

**Comment by felcaetano** [comment] 2021-05-20 19:28
I can confirm this is happening to me too.

**Comment by prlanzarin** [comment] 2021-05-20 23:30
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/12416

(which I suspect is also a duplicate of some older issue I can't find.)

**Comment by antobinary** [comment] 2021-05-21 02:21
@prlanzarin which issue is the duplicate? You accidentally linked to this very issue...

**Comment by prlanzarin** [comment] 2021-05-21 02:23
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/12407

**Closed by prlanzarin** 2021-05-21 02:23 UTC
Labels: status: duplicated
