### ISSUE TITLE
new create param to enable \ disable Virtual background 

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#13964] opened 2021-12-21 15:49 UTC
**Is your feature request related to a problem? Please describe.**
some teachers find the use of Virtual background by students disrupting, and some find it useful.  there is only a server wide configuration to disable / enable Virtual background.

**Describe the solution you'd like**
less than server wide configuration to disable / enable Virtual background.

**Comment by defnull** [comment] 2021-12-28 15:17
Virtual backgrounds are a privacy feature, not just aesthetics. If a student chooses to hide the background, there is usually a reason for it. Allowing teachers to look into a students private space without consent is problematic at best, and may even be illegal in some countries. You could compare it with teachers wanting to remotely unmute microphones or enable webcams without consent. This crosses a line.

**Comment by kaystrobach** [comment] 2022-01-04 12:11
I also see it only as option on a per meeting base in the create meeting call.

An on the fly solution is a no go.

**Comment by defnull** [comment] 2022-01-04 12:37
Some problems do not need a technical solution. Teachers should just communicate that they prefer a visible background, or that the room must be visible in a 1-to-1 exam situation. Disabling background blurring is quick and easy for the user. It's literally just 2 clicks. Leaving control to the user at least gives them a chance to voice their concerns before they are forced to show their background.

There are lots of valid reasons for hiding the background and students, especially young students, deal with problems adults may not see or not regard as valid. This functionality is a great and long needed privacy feature. Force-disabling this feature, even if it's on a per-meeting basis, is way too easy to abuse. Some teachers might just disable blurred backgrounds out of personal preference, not intending any harm, but still forcing students to show more than they want to.

I'm a little surprised that this feature request was accepted so quickly without discussion or thinking about its implications.

**Comment by prlanzarin** [comment] 2022-01-04 12:59
> I'm a little surprised that this feature request was accepted so quickly without discussion or thinking about its implications.

I don't think it was accepted though? There's no `status: accepted` label (which I personally use as the indicator that something might be done eventually). The fact that it has a milestone assigned doesn't really mean the issue will be _implemented_, just analyzed for that milestone (again, from _my_ understanding).

**Comment by defnull** [comment] 2022-01-04 13:03
It's a milestone for 2.4. Or are milestones just used to categorize issues? I'm confused.

**Comment by prlanzarin** [comment] 2022-01-04 13:06
Yeah, it's in the milestone. Which, as I mentioned and from _my_ understanding, means this will be looked upon in the 2.4 scope. An issue is addressed once it's closed, whether as an accepted/implemented issue or a `wontfix` issue.

We digress, though. I already voiced my _nay_ as far as the issue is concerned. Will let others chime in.

**Comment by antobinary** [comment] 2022-01-04 21:15
Hi all!

This issue was opened shortly after we had spoken in the community call about the proctoring scenario of using BBB. So when I added the milestone 2.4, my thoughts were to look into introducing a _create_ parameter which disables virtual background for the meeting being created within the scope of 2.4. There was no chance to discuss this internally yet and afaik there is no work underway to implement such parameter yet.

> Toggling availability on the fly is a no-go.

100% agree.

One tricky use case would be the case of skipping video preview `userdata-bbb_skip_video_preview_on_first_join=true` or 

`userdata-bbb_skip_video_preview=true` coupled with `userdata-bbb_auto_share_webcam=true` where such new create parameter could cause revealing of the physical background with no option to protest...

**Comment by Jossef-767** [comment] 2022-01-06 23:15
>  Allow virtual backgrounds usage, statically and per meeting, for everyone (just expanding the current setting to a create param)
100% agree.
This is exactly what is meant by "less than server wide configuration..."

This issue has a specific use case, a school principal who has been using the system for several years, (before this feature existed) seeks to eliminate it because, he says, it interferes with the course of the lesson and distracts, (for very young students) and distracts,.
In such a situation I condemn all the other users of this server to get along without this important feature.
Generally, it is acceptable to allow the new features to be turned off in the configuration file. And allow the option for the discretion of the system administrator.
This is done in marginal and less substantial features.
And it is also important to allow different users to customize the system to the way they prefer to teach.

**Comment by antobinary** [comment] 2022-01-24 20:06
Implemented in #14075 and should ship with BBB 2.4.3

**Closed by antobinary** 2022-01-24 20:06 UTC
Labels: type: enhancement
