### ISSUE TITLE
Allow all users to share their screen simultaneously

### ISSUE THREAD

**Issue by hd42** [bigbluebutton/bigbluebutton#10405] opened 2020-09-07 11:04 UTC
**Is your feature request related to a problem? Please describe.**
When my training participants are working on their assignments, I'd like to be able to see their progress. Currently, I have to ask each in turn to share their screen.

**Describe the solution you'd like**
Ideally, all users could share their screens in addition to their camera. The presenter should be able to see all shared screens. For the participants it should be clear that they share their screen with the presenter and not with all other participants.

**Describe alternatives you've considered**
I've tried entering breakout-rooms with each participant and switching between them, but that is not working well.

**Comment by matiasilva** [comment] 2020-09-07 12:12
Duplicate of #9152. You'll see the current progress of the issue, so pull requests are welcome.

**Closed by matiasilva** 2020-09-07 12:12 UTC
Labels: Enhancement
