### ISSUE TITLE
Echo test mediasoup -- echo starts after a few seconds pause

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15140] opened 2022-06-07 16:38 UTC
**Describe the bug**

**To Reproduce**
On a server with **mediasoup** configured to handle the experimental two way audio (i.e. **microphone**)
1. Try joining with microphone
![Screenshot from 2022-06-07 12-32-59](https://user-images.githubusercontent.com/6312397/172435018-630173ac-accf-4a28-a12d-0b66b36d8f9d.png)

2. Click on 'Microphone'
3. You are presented with:
![Screenshot from 2022-06-07 12-33-06](https://user-images.githubusercontent.com/6312397/172435158-e89d2e8f-d1de-41e5-9947-c6540da2f078.png)

If you started verbally counting 1-2-3-4-5-6-7-8-9...

**Expected behavior**
Echo test lets you hear back 1-2-3-4-5-6-7-8-9...

**Actual behavior**
Echo test lets you hear back 5-6-7-8-9...  **the first few seconds there is no audio -- no 1-2-3-4-**

**Screenshots**

**BBB version:**
BigBlueButton 2.5.0-rc.4 with the experimental 2 way audio via mediasoup

**Desktop (please complete the following information):**
everyone encounters this afaik -- Chromium on Ubuntu, Safari MacOS, ...

**Comment by ffdixon** [comment] 2022-06-07 23:14
After some investigation, I found that 

~~~
fullAudioProxyActiveDirection=false
~~~

in `/etc/bigbluebutton/bbb-webrtc-sfu/production.yml` and restarting BigBlueButton had the echo test starting immediately.

**Comment by prlanzarin** [comment] 2022-06-21 12:18
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/14635

And yes, `fullAudioProxyActiveDirection=false` works around the issue at the expense of breaking it in servers with mismatched FS vs mediasoup announced IPs.

**Closed by prlanzarin** 2022-06-21 12:18 UTC
Labels: module: client
