### ISSUE TITLE
Can the profile image set in GreenLight be used as the BigBlueButton avatar?

### ISSUE THREAD

**Issue by Dezit-Suda** [bigbluebutton/bigbluebutton#9118] opened 2020-04-17 05:55 UTC
With Greenlight, you can change the **image** (profile image) for each user, but with BigBlueButton, it seems that you can not change the image of the **avatar**.

Isn't there a setting to display the profile **image** of the user set in GreenLight as the **avatar** of BigBlueButton?

I hope that the **image** set with Greenlight will be reflected as the **avatar** of BigBlueButton.

**Comment by matiasilva** [comment] 2020-06-18 08:39
Duplicate of #8566.

**Closed by matiasilva** 2020-06-18 08:39 UTC
Labels: Enhancement
