### ISSUE TITLE
Multi screen share

### ISSUE THREAD

**Issue by Olnyov** [bigbluebutton/bigbluebutton#11941] opened 2021-04-08 11:54 UTC
Is it technically possible to share several screens by participants  so that these screens can be watched by only a moderator? Just needed only HTML5 component customization?

**Comment by prlanzarin** [comment] 2021-04-08 11:58
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/9152

**Closed by prlanzarin** 2021-04-08 11:58 UTC
Labels: module: client
