### ISSUE TITLE
First Avatar image appears off-centered

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3770] opened 2017-03-30 11:57 UTC
If you enable avatars to appear for users who aren't enabling their video, the avatars first appear off center (and even outside of the window that should contain them). If you click the avatar, it centers up correctly.

Here is a video to illustrate.

  https://www.screencast.com/t/7QzcTVuGDP

Reported in
  
  https://groups.google.com/d/msg/bigbluebutton-dev/hpQRUxc-8qg/w_RFMfTsAAAJ

**Comment by capilkey** [comment] 2017-10-10 12:38
Duplicate of #3605

**Closed by capilkey** 2017-10-10 12:38 UTC
Labels: Duplicate
