### ISSUE TITLE
Losing microphone and camera connections!!

### ISSUE THREAD

**Issue by yazilimevde** [bigbluebutton/bigbluebutton#13743] opened 2021-11-23 13:17 UTC
When the class size is 50 and above, only when our teacher turns on his camera, our teacher's microphone and camera connections are disconnected.However, at the same time, classes are held in about 8 simultaneous classes. In other words, nearly 500 students attend the class at the same time, even if they are in different classes.How can we solve this?
We installed BBB on a dedicated server. The server gives an IPV4 address.

**Comment by ffdixon** [comment] 2021-11-23 13:21
Duplicate of #13741

**Closed by ffdixon** 2021-11-23 13:21 UTC
Labels: module: core
