### ISSUE TITLE
Cannot upload presentation file on Firefox ESR 52.2

### ISSUE THREAD

**Issue by sida-khalibre** [bigbluebutton/bigbluebutton#4112] opened 2017-07-18 03:52 UTC
Hi @ffdixon 

I found issue on Firefox ESR 52.2 that cannot upload presentation and freeze the screen. This can reproduce on BBB demo.

**Comment by sida-khalibre** [comment] 2017-07-18 04:00
This working on fine on 32 bit version

**Comment by mikhailnov** [comment] 2017-07-30 17:26
Cannot reproduce on firefox-esr 52 64 bit on Linux, Ubuntu 17.04, KDE

**Comment by ffdixon** [comment] 2018-05-25 10:04
While may be caused by different underlying issues, we are also seeing this here in FireFox 60 64-bit on Windows https://github.com/bigbluebutton/bigbluebutton/issues/5564.

In our tests FireFox  59 worked for upload, but not FireFox 60, and only FireFox 64-bit was affected.

Not sure if we can do anything with FireFox 52 but we are focused on FireFox 60 as it's the new ESR. 
 We have an open bug with Mozilla (see above link).

**Comment by ffdixon** [comment] 2019-04-07 03:28
@sida-khalibre Is this still an issue with the HTML5 client?  Can you give it a quick test at https://test.bigbluebutton.org/.

**Comment by ffdixon** [comment] 2019-05-19 02:59
Closing as FireFox ESR is now 68.  We can open a new issue if this problem arises again.

**Closed by ffdixon** 2019-05-19 02:59 UTC
