### ISSUE TITLE
Deskshare fails after 6-7 times of start-stop (v0.8)

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2142] opened 2015-08-12 08:00 UTC
Originally reported on Google Code with ID 1389
```
Deskshare fails after 6-7 start-stop actions. From Red5 logs it seems like servlet is
still running after deskshare window is closed - at first it gets CONSUMER_CONNECT_PUSH
event (and all others) once, then twice, trice, etc.

Logs attached
```

Reported by `upcFrost` on 2013-01-25 17:02:55

<hr>
 * *Attachment: [FirstRun.txt](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1389/comment-0/FirstRun.txt)*
 * *Attachment: [SecondRun.txt](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1389/comment-0/SecondRun.txt)*
 * *Attachment: [ThirdRun.txt](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1389/comment-0/ThirdRun.txt)*

**Comment by ffdixon** [comment] 2016-01-30 19:35
Unable to reproduce in latest builds of 1.0-beta.  Closing (we can re-open a new issue if this reappears).

**Closed by ffdixon** 2016-01-30 19:35 UTC
Labels: Accepted, Defect, DeskShare (Java), Normal Priority
