### ISSUE TITLE
Audio quality is degraded when two people talk at same time

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2551] opened 2015-08-12 08:38 UTC
Originally reported on Google Code with ID 1800
```
Reporting for further investigation.


- What steps will reproduce the problem?
1. Join a session with computer A 
2. Join a session with computer B
3. Join a session with computer C
4. Talk at same time in computer A and B
5. Computer C will notice a degraded audio

- What is the expected output? What do you see instead?
A good audio quality


```

Reported by `eu.tdj.cc` on 2014-09-16 20:30:52

**Comment by ffdixon** [comment] 2016-01-31 00:56
Closing issue as unable to reproduce on latest builds.

**Closed by ffdixon** 2016-01-31 00:56 UTC
Labels: Defect, Normal Priority
