### ISSUE TITLE
Your webcam stays shared if you unplug it while in use

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2697] opened 2015-08-12 08:42 UTC
Originally reported on Google Code with ID 1949
```
What steps will reproduce the problem?
1. Share your webcam
2. Unplug it (the stream with freeze)
3. Press the webcam button to stop sharing
4. Join the same meeting from a different browser

What is the expected output? What do you see instead?
When the stream is stopped or if possible when the webcam is unplugged the stream should
be removed from the server's list. Instead when you join on a new client the server
sends that "Client 1" is still sharing their webcam and it plays the recorded stream.



```

Reported by `capilkey` on 2015-06-04 22:31:33

**Comment by ffdixon** [comment] 2016-01-25 16:45
Unable to reproduce this issue anymore in BigBlueButton 1.0-beta (we've done an number of updates to the handling of webcams).  Closing this issue.

**Closed by ffdixon** 2016-01-25 16:45 UTC
Labels: Accepted, Client, Defect, Video
