### ISSUE TITLE
[HTML5]2.2-beta9 "Allow access to your microhone" modal close not working

### ISSUE THREAD

**Issue by vova-zush** [bigbluebutton/bigbluebutton#7521] opened 2019-05-28 13:49 UTC
![Selection_721](https://user-images.githubusercontent.com/29659152/58483212-93565000-8168-11e9-940a-89a45fbefeda.png)

**Comment by capilkey** [comment] 2019-05-28 16:36
You need SSL set up to get access to media devices. We can add in extra detection, but that's the cause of your issue.

**Comment by vova-zush** [comment] 2019-05-29 08:17
Yes, I know about ssl. If press enable mic then modal hide. But I just want to say what close button not working

**Comment by antobinary** [comment] 2019-06-04 17:11
I am able to reproduce this locally. I will look into resolving it. Thanks @vova-zush for reporting this!

**Closed** 2019-06-04 17:56 UTC
Labels: HTML5 Client
