### ISSUE TITLE
Independent volume control for other users

### ISSUE THREAD

**Issue by SmolBlackHole** [bigbluebutton/bigbluebutton#11501] opened 2021-02-25 12:00 UTC
The possibility to adjust the volume of individual users for yourself is missing. Some are way too loud, others too quiet. Having to constantly change the browser volume gets on my nerves. 

A solution that I would like to see:
Independent volume control for individual users within a web conference, client-sided not server-sided.

Alternatives? None. A major feature that is missing.

**Comment by prlanzarin** [comment] 2021-02-25 12:41
Duplicate of #11301

**Closed by prlanzarin** 2021-02-25 12:41 UTC
Labels: Enhancement
