### ISSUE TITLE
[2.3-alpha6] Cannot copy meeting url in public chat

### ISSUE THREAD

**Issue by miztaka** [bigbluebutton/bigbluebutton#11411] opened 2021-02-15 21:10 UTC
**Describe the bug**
When you enter meeting room, you can see the URL to share for someone,
but I cannot copy and paste this URL, it worked in 2.2

**To Reproduce**
1. Enter meeting room
2. Open public chat if it's closed
3. See "To invite someone to the meeting, send them this link:" section
4. Try to copy the URL by dragging mouse
5. It cannot be selected 

**Expected behavior**
The URL should be copied and pasted.

**Actual behavior**
The URL cannot be copied and pasted.

**Screenshots**

**BBB version (optional):**
2.3-alpha6

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 85.0.1

**Comment by basisbit** [comment] 2021-02-16 09:58
Duplicate of #11409

**Closed by basisbit** 2021-02-16 09:58 UTC
Labels: HTML5 Client
