### ISSUE TITLE
[2.2 Beta][HTML5] iPhone/iPad portrait camera overlaps presentation display for all users

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#6804] opened 2019-02-18 04:55 UTC
It is great that portrait video camera's are displayed in their entirety, however it overlaps the presentation when there are multiple video cameras shown above the presentation. Every user will experience the overlap.

**Comment by aogilvie** [comment] 2019-02-18 05:51
![example](https://user-images.githubusercontent.com/970364/52930662-9cc36580-338c-11e9-8b9c-24bddd938877.png)

**Comment by prlanzarin** [comment] 2019-02-18 17:57
Thanks for reporting. There's already an issue open for that https://github.com/bigbluebutton/bigbluebutton/issues/6648 :).

**Comment by capilkey** [comment] 2019-02-19 17:01
Duplicate of #6648

**Closed by capilkey** 2019-02-19 17:01 UTC
