### ISSUE TITLE
Welcome message not fully show it RTL 2.4 Beta4

### ISSUE THREAD

**Issue by Rahimimojtaba** [bigbluebutton/bigbluebutton#13160] opened 2021-09-05 06:22 UTC
Welcome message for RTL languages not show correctly and it seems that don't have enough height. It should be show fully.

1. Just change language overrides for HTML5 to some RTL Languages.
2. Then create and start a meeting with long welcome message.
3. You'll find that welcome message not show completely in chat area.

Keep in mind that the meeting should start with RTL language. Don't create and start meeting with LTR English language and then change the language!

**Expected behavior**
Should show the welcome message completely and clearly.

**Actual behavior**
Welcome message is not complete and show incorrectly.

**Screenshots**
https://imgur.com/a/Ze9YIh2

BBB version: 2.4 Beta 4

Desktop:
 - OS: Windows
 - Browser: Chrome, Safari
 - Version: 92.0.4515.159

**Comment by Rahimimojtaba** [comment] 2021-09-05 06:34
@ffdixon @antobinary

**Comment by Rahimimojtaba** [comment] 2021-09-22 12:25
Hi, Any news on this issue?
@antobinary @vitormateusalmeida

**Comment by ali-alhaidary** [comment] 2021-09-22 12:27
confirmed reproducible.

**Comment by vitormateusalmeida** [comment] 2021-09-23 13:11
1. Just change language overrides for HTML5 to some RTL Languages.
    **Where did you overwrite? settings.yml?**
2. Then create and start a meeting with long welcome message.
   **Where did you set the welcome message?**
   **Can you send a sample message for test?**

**Could you submit a video demonstrating?**

**Comment by Rahimimojtaba** [comment] 2021-09-28 05:55
@vitormateusalmeida 
1- Yeah, Just change `fallbackLocale` and `overrideLocale` in setting.yml to some RTL languages such as AR.
2- You can set the welcome message in https://mconf.github.io/api-mate/ when you are doing the test. Also you can set welcome message in bigbluebutton properties also. `defaultWelcomeMessage=` `defaultWelcomeMessageFooter=`

Sample message for test:
وینک قلبی اتعذب فی هواک وینک قلبی العاشق ما ینساک لا جوابات یا ناسینی فیهم شوق و ود وشایلین سلامات کل یوم راح تجینی ترد لقلبی البسمه و للیل النجمات عندما یحب الرجل المرأة بصمت .. یخسر کل شیء حتى هی… وعندما تحب المرأة الرجل بصوت.. تخسر کل شیء حتى هو! ففی الحب الصمت جریمة الرجل والصوت جریمة المرأة…
اربك تكست هو اول موقع يسمح لزواره الكرام بتحويل الكتابة العربي الى كتابة مفهومة من قبل اغلب برامج التصميم مثل الفوتوشوب و الافترايفكتس و البريمير و الافد ميدا كومبوزر و السموك و برامج اخرى كثيرة

**Comment by Rahimimojtaba** [comment] 2021-09-29 05:44
Will be any fix for this?
@antobinary

**Comment by Rahimimojtaba** [comment] 2021-10-04 15:10
Hope to have fix in new release. @ffdixon

**Comment by JoVictorNunes** [comment] 2021-10-06 18:43
The steps to reproduce the bug were followed on branch 2.4:
1. Changed the `fallbackLocale` and `overrideLocale` in setting.yml to AR.
2. Set the welcome message with long one through the API Mate.

Sample message tested:
وینک قلبی اتعذب فی هواک وینک قلبی العاشق ما ینساک لا جوابات یا ناسینی فیهم شوق و ود وشایلین سلامات کل یوم راح تجینی ترد لقلبی البسمه و للیل النجمات عندما یحب الرجل المرأة بصمت .. یخسر کل شیء حتى هی… وعندما تحب المرأة الرجل بصوت.. تخسر کل شیء حتى هو! ففی الحب الصمت جریمة الرجل والصوت جریمة المرأة…
اربك تكست هو اول موقع يسمح لزواره الكرام بتحويل الكتابة العربي الى كتابة مفهومة من قبل اغلب برامج التصميم مثل الفوتوشوب و الافترايفكتس و البريمير و الافد ميدا كومبوزر و السموك و برامج اخرى كثيرة

However no bugs was found and everything seems to work as expected:
![Captura de tela de 2021-10-06 15-12-46](https://user-images.githubusercontent.com/62393923/136263245-67e4eda1-9004-4695-8cf3-c3acdf149f2c.png)

**Comment by Rahimimojtaba** [comment] 2021-10-13 06:59
Dear @JoVictorNunes
Thanks for checking
I set the `fallbackLocale `and `overrideLocale ` to fa_IR and then checked again. Same issue.
Please check the recorded file:
https://screencast-o-matic.com/watch/cr6I1KVXxno
Thanks

**Comment by ali-alhaidary** [comment] 2021-10-20 03:30
Are these screenshots related
![Screenshot 2021-09-14 at 20-29-42 المجلس - المجلس - غرفة التعليم والتدريب المباشر ](https://user-images.githubusercontent.com/75235623/138023681-d87536ea-aa45-4cca-b6de-30d048c91c71.png)
![Screenshot 2021-10-12 at 17-33-05 المجلس - غرفة درس عقائد الامامية - Default](https://user-images.githubusercontent.com/75235623/138023698-b91699a9-48dd-4ac3-b76d-59b1e4b5c658.png)
?

**Comment by ali-alhaidary** [comment] 2021-10-20 06:37
@Rahimimojtaba just enter a room and it is there...

**Comment by Rahimimojtaba** [comment] 2021-11-01 19:28
@antobinary 
Hmmmm, it seems that not fixed yet!

**Comment by antobinary** [comment] 2021-11-01 19:40
We have not been able to reproduce this. We'd appreciate assistance from community members who can try this and provide detailed steps to reproduce this (or try to debug locally and see what might be causing this)

**Comment by ali-alhaidary** [comment] 2021-11-02 06:53
> We have not been able to reproduce this. We'd appreciate assistance from community members who can try this and provide detailed steps to reproduce this (or try to debug locally and see what might be causing this)

It does not fire an error, it seems that this issue is related to screen resolution, browser font size/type and page zooming. We were able to reproduce it on one client, and could not on another, using the same (as far as we know) settings as seen from the attached screen shots, there always some boarders missing.
![1](https://user-images.githubusercontent.com/75235623/139799368-19281ad7-ea4a-449b-aaff-60641420216e.png)
![2](https://user-images.githubusercontent.com/75235623/139799383-7d3b6294-758e-4083-88a5-379793d6383c.png)
![3](https://user-images.githubusercontent.com/75235623/139799469-7a85da4a-6d01-49f5-8164-dea8d9815aaa.png)

.

**Comment by Rahimimojtaba** [comment] 2021-11-22 16:59
Finally I found it! It'll be appear on 24-inches monitors and I think also it should happened on more than 24-inches!
Please advice
@antobinary @ffdixon @JoVictorNunes

**Comment by antobinary** [comment] 2021-12-17 16:28
I am still not able to reproduce the issue locally. Attached is a screenshot from my 24 inch monitor with RTL display and the chat is shown fine... 
Are you able to provide a screen-recording from clicking on Join onwards, maybe there's a step we miss.
Coud you please comment:
- show the browser dev tools, do you still hit the issue
- switch the browser locale to English, do you still hit the issue
- try changing the welcome message so it only contains "123", do you still hit the issue
- do you see a correlation between joining as the first user in a meeting vs joining an ongoing meeting? When is this more likely to happen?
I see a lot of white around the chat area in the screenshots, is this part of the issue or are you editing the screenshot to omit sensitive information?
Could you take a screenshot of the entire display?
Does this only happen when you have one 24+ monitor, or also if you have multiple screens?
Does this only happen in Arabic, or do Persian and Hebrew also trigger it? Have you ever seen this in a left-to-right locale?
Are you able to inspect the DOM tree (HTML) in the dev tools and see which elements are not looking correct (screenshot here can help too)
If you resize the browser window after hitting this issue, does it persist?
Are you able to reproduce these on https://test24.bigbluebutton.org?

![Screenshot from 2021-12-17 10-51-15](https://user-images.githubusercontent.com/6312397/146576502-b8c39a0d-51b3-443b-a32e-2636b3959d61.png)

**Comment by ali-alhaidary** [comment] 2021-12-17 18:22
Hi Anton,

Welcome message must be in RTL characters to reproduce, and strangely, 
only the first time entering the session, so if you end or exit from the 
session and return back, it will display OK.

see the attached please how the boarders are not visible and whatever 
comes after it.

Ali

**Comment by antobinary** [comment] 2021-12-17 19:29
Ali, the message above does not display images on GitHub, please try again when you have a chance.

I am still confused about the extra white space all around the chat area in the images above.
If it wasn't for that extra space, I'd say this issue resembles https://github.com/bigbluebutton/bigbluebutton/issues/12130 and https://github.com/bigbluebutton/bigbluebutton/issues/12178 
In play there is the timing of the chat sync and chat render, etc. 

Could someone please capture and include here an entire client screenshot next time this happens?

**Comment by ali-alhaidary** [comment] 2021-12-17 19:57
![1](https://user-images.githubusercontent.com/75235623/146600727-747abfea-d691-41f0-8b7d-e20aaffb257e.png)
![2](https://user-images.githubusercontent.com/75235623/146600742-02f1aeaa-0b29-4660-bcae-45608d3f09e8.png)
![3](https://user-images.githubusercontent.com/75235623/146600760-0c5694e6-7322-4241-9909-49fec826581c.png)

**Comment by ali-alhaidary** [comment] 2021-12-17 20:07
Bellow images numbers:
4. when starting the session.
5. when sending chat message
6. when exiting, or ending and re-starting the session (notice that default presentation is not loaded https://github.com/bigbluebutton/bigbluebutton/issues/13783 )
7.  when sending chat message.
![4](https://user-images.githubusercontent.com/75235623/146601580-90856fb9-6c27-408f-9d42-64b80d80f34c.png)
![5](https://user-images.githubusercontent.com/75235623/146601593-7300ae09-0278-41d0-aa25-7e66890c0218.png)
![6](https://user-images.githubusercontent.com/75235623/146601603-9e58102f-a863-4fc2-b2fb-f4957f956e0d.png)
![7](https://user-images.githubusercontent.com/75235623/146601614-4bd76a6d-e380-4284-9b3f-34c4c63988f1.png)

**Comment by ali-alhaidary** [comment] 2021-12-17 20:31
Note that this only on FF, edge shows OK.

**Comment by Rahimimojtaba** [comment] 2021-12-20 07:20
Dear @antobinary Thanks for follow up on this issue.
I did screen record for you.
https://screencast-o-matic.com/watch/crlY1tV2d2Y
Also I did another one in this topic a few months ago.
https://screencast-o-matic.com/watch/cr6I1KVXxno
Please check and advie.
Thanks

**Comment by Franz-Heinz** [comment] 2022-01-04 11:36
Can confirm the bug with Firefox 95.0.1 on Ubuntu 18.04 LTS with screen resolution 2560x1600.
BBB is version 2.4.

My custom defaultWelcomeMessage is formed with the following settings in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties:

```
defaultWelcomeMessage=Willkommen zu "<b>%%CONFNAME%%</b>"<br><br>Eine kurze BigBlueButton-Einf&uuml;hrung in Form von Video-Tutorials findet sich unter: <a href="event:https://bigbluebutton.org/html5/">https://bigbluebutton.org/html5/</a>.<br><br>Nach M&ouml;glichkeit bitte ein Headset bzw. Kopfh&ouml;rer nutzen, um St&ouml;rger&auml;uche zu vermeiden.
```

```
defaultWelcomeMessageFooter=<br>Um via Telefon teilzunehmen %%DIALNUM%% w&auml;hlen und folgende Konferenz-PIN eingeben: %%CONFNUM%% #<br><i>Hinweis: Mittels der Ziffer 0 k&ouml;nnen telefonisch zugeschaltete Personen selbst ihr Mikrofon ein- und ausschalten.</i><br><br><b>Weitere Steuerung bei telefonischer Teilnahme:</b><br><br>Mit 4 l&auml;sst sich das Mikrofon leiser stellen<br> Mit 5 l&auml;sst sich das Mikrofon auf Standard-Lautst&auml;rke stellen<br> Mit 6 l&auml;sst sich das Mikrofon lauter stellen<br><br>Mit * lassen sich sowohl Mikrofon als auch Lautsprecher ein- und ausschalten<br>Mit 0 l&auml;sst sich das Mikrofon ein- und ausschalten<br>
```
Screenshot:
![WelcomeMessageSizeBug](https://user-images.githubusercontent.com/63586284/148052306-514762ad-7fdc-4bd0-b6d4-1ee7defbfa30.png)

Workaround: After resizing the firefox window the issue disappears - but I can't really expect the users to figure that out.
So it would be really great if this could be fixed with the next update.

**Comment by antobinary** [comment] 2022-01-10 16:29
If either of you is able to pull #14023 and try to reproduce locally, that would be fabulous!
Otherwise - please comment here after trying 2.4.1 (not yet released) if you find an edge case we've missed

**Closed by antobinary** 2022-01-10 16:29 UTC
Labels: module: client
