### ISSUE TITLE
Video Preview pagination

### ISSUE THREAD

**Issue by einst44** [bigbluebutton/bigbluebutton#10008] opened 2020-07-08 04:15 UTC
Hi Teams, thanks for this great software, we use Bigbluebutton almost 2 years and quite happy with the feature and performance. 

**Is your feature request related to a problem? Please describe.**
We have many multiple session at 30-50 participant who share video, and the video preview from another participant get frozen at 20 video moreover the video player is too small especially in mobile device

**Describe the solution you'd like**
I hope we can have video pagination, and we can limit the video played for example 8 video per page 
1. we can have decent size for video player per page
2. Pause unseen/hidden video player/page to limit bandwidth consumption for client (especially client with low bandwidth)
3. Un-pause video if there is page change in client

Thanks

**Comment by matiasilva** [comment] 2020-07-08 08:44
Duplicate of #9655

**Comment by matiasilva** [comment] 2020-07-08 08:45
This is a sound enhancement and is being worked on at the moment. Feel free to tack on your ideas to the above issue.

**Closed by matiasilva** 2020-07-08 08:44 UTC
Labels: Enhancement
