### ISSUE TITLE
Chinese characters not showing.

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1924] opened 2015-08-12 07:52 UTC
Originally reported on Google Code with ID 1170

```
I am using ver .7 and now upgraded to ver .8. I am uploading Word, PDF or Powerpoint
files into the presentaion screen and the chinese letters are not shown in BBB. I have
attached a copy what is shown after importing and given a copy of the original that
includes the chinese characters. I have tried opening and saving using Openoffice instead
of other programs but it still does not work. 
```

Reported by `abnersilverio` on 2012-03-08 00:40:46

<hr>
- _Attachment: [Document6.pdf](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1170/comment-0/Document6.pdf)_

**Comment by ffdixon** [comment] 2017-01-07 20:59
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/3176

**Closed by ffdixon** 2017-01-07 20:59 UTC
Labels: Defect, Docs, Normal Priority, Presentation, Usability
