### ISSUE TITLE
Slides rendering incomplete/broken on 2.3-beta-1

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/bigbluebutton#11779] opened 2021-03-28 12:11 UTC
**Describe the bug**
Slide conversion on BBB 2.3-beta-1 creates different results (broken/missing fonts) than 2.2.31. Fonts are substituted, or missing.

**To Reproduce**
1. Upload the attached slide to BBB 2.3-beta-1
2. Smiley face is replaced by a box

**Expected behavior**
Fonts appear as in the uploaded pptx.

**Actual behavior**
Fonts seem to be missing/substituted. Further artifacts occur (slide 17 of Lecture 8). I suspect that this is due to the containers running on Debian, which might be missing certain fonts vs. the Ubuntu 16.04 with additional/MS fonts installed.

**Screenshots**
Missing special character (mental health slide):
![bbb23-bug1](https://user-images.githubusercontent.com/5586936/112751636-498e5900-8fcf-11eb-924b-af20cb966a57.PNG)

Missing fond (slide title) and artifact in slide itself:
![bbb23-bug2](https://user-images.githubusercontent.com/5586936/112751650-5743de80-8fcf-11eb-8518-774c7565cbef.PNG)

**Additional context**
PPTX of offending files:
[Lecture 8.pptx](https://github.com/bigbluebutton/bigbluebutton/files/6217262/Lecture.8.pptx)
[mentalhealthslide.pptx](https://github.com/bigbluebutton/bigbluebutton/files/6217263/mentalhealthslide.pptx)

**Comment by antobinary** [comment] 2021-04-07 19:21
Hi @ichdasich 
I downloaded the two attached files, uploaded them as .pptx (originals) on what is likely to be 2.3-beta-3 and experienced the exact same distortion.
Then I opened each pptx file in my local LibreOffice Version: 6.4.6.2 and exported them to pdf (default settings)
These are the results:
![Screenshot from 2021-04-07 15-17-51](https://user-images.githubusercontent.com/6312397/113921991-bdd9b100-97b4-11eb-908a-cba476b0119c.png)
![Screenshot from 2021-04-07 15-16-51](https://user-images.githubusercontent.com/6312397/113921992-be724780-97b4-11eb-96ba-bd87b001387c.png)

While this is not exactly a solution, it may be a workable temporary one.

**Comment by ichdasich** [comment] 2021-04-07 19:29
Heho,
yeah, for me it is workable; I usually just PDF/A export my slides before uploading. ;-) But thanks for trying this out. :-)

I was more thinking about my users. :-)

Note, btw... the first one (take care of yourself) should not be a palm at at beach but a :-) smiley... So, to a degree, this may be an inherent limitation of having to use libreoffice with pptx.

**Comment by gustavotrott** [comment] 2021-04-14 13:21
The overlay text problem seems to be related with this equation elements in the slide:

![image](https://user-images.githubusercontent.com/5660191/114716523-831ece00-9d0a-11eb-93c7-c8c4abcc8e06.png)

I can reproduce the problem creating a simple pptx and including a equation element:

PPTX
![image](https://user-images.githubusercontent.com/5660191/114716359-5d91c480-9d0a-11eb-83b1-637a044309f0.png)

Genereated PDF:
![image](https://user-images.githubusercontent.com/5660191/114716379-61254b80-9d0a-11eb-8380-c463ac920092.png)

I am making some tests to see if I can avoid this problem.

**Comment by gustavotrott** [comment] 2021-04-15 12:47
Fixed installing MS Fonts:
![image](https://user-images.githubusercontent.com/5660191/114870707-df4b2600-9dce-11eb-81de-dab7b346072b.png)

----

Fixed using version 7 of LibreOffice (before Docker was using v6).
LibreOffice 7 still can't handle Math objects, but it removes those elements, instead of compromising the entire slide.
![image](https://user-images.githubusercontent.com/5660191/114871175-64ced600-9dcf-11eb-9dfe-e677e1729bcd.png)

**Comment by ichdasich** [comment] 2021-04-24 15:54
So, i just rolled out RC1 with the fixes (Thanks for that!) but in the converted documents the transparent PNG for the TU Delft logo now gets a white background.

**Comment by gustavotrott** [comment] 2021-04-26 15:00
Hi @ichdasich ,

I can reproduce the problem in my desktop Libreoffice and confirm that it is a problem in Libreoffice 7:
![image](https://user-images.githubusercontent.com/5660191/116102194-df77db00-a684-11eb-8aed-928525b6fe69.png)
![image](https://user-images.githubusercontent.com/5660191/116102206-e3a3f880-a684-11eb-944d-176fac89d4c6.png)

I opened the PPTX and edited the "Slide Master". Then I figured out that the image with problem seems to not be a PNG.
If I try to save the image it will be saved with extension `.emf`.
![image](https://user-images.githubusercontent.com/5660191/116103360-e3582d00-a685-11eb-9fd5-33b3d1bd8534.png)

Then I tried to save the logo of the other slide and it will be saved as `.png`.
![image](https://user-images.githubusercontent.com/5660191/116103426-f408a300-a685-11eb-8461-eaa794567552.png)


- I made a test copying the TU Delft logo from last slide and also include BBB png logo, and the conversion worked with the new png images:

![image](https://user-images.githubusercontent.com/5660191/116103455-fb2fb100-a685-11eb-9324-85df47cd2637.png)


It seems Libreoffice 7 has problem with `.emf`, maybe you can edit Master Slide and change it with a png image.
Can you check if it solve the problem?

**Comment by ichdasich** [comment] 2021-04-26 15:03
Heho,
no worries about solving it for me (i usually just use PDF/A compliant PDFs ;-)). 

More a thing for users; But if this is LO, there is not a lot BBB can do about it. 

If using a PNG works as intended for you i'd say there is no need for me to reproduce. Thanks for figuring this out!

**Comment by antobinary** [comment] 2021-04-26 18:05
Do we know if there's an issue open at LibreOffice about this?

**Comment by gustavotrott** [comment] 2021-04-26 19:00
> 
> 
> Do we know if there's an issue open at LibreOffice about this?

Yes!
https://bugs.documentfoundation.org/show_bug.cgi?id=137413

And it was fixed in Libreoffice 7.1.1:
![image](https://user-images.githubusercontent.com/5660191/116135315-5cb44780-a6a7-11eb-844e-51297d566127.png)

We can wait for LO "stable release" with this fix or start testing 7.1 for Bbb 2.4.

**Comment by gustavotrott** [comment] 2021-06-11 14:31
This issue can be closed! In short:

- The problem with equation element:
Fixed after upgrade LibreOffice to version 7.

- Missing special character:
We reverted the MS fonts installation, thus this problem can remains.
But now you can install MS fonts in the system manually and LO will automatically use it.

**Closed** 2021-06-11 14:40 UTC
Labels: component: presentation, module: core, status: accepted, type: defect

**Comment by ashishkpaul** [comment] 2021-10-04 11:59
hello sir, fresh installed BigBlueButton Server 2.3.14 (2457)
characters are not rendering properly. its adding some special characters
client preview
![WhatsApp Image 2021-10-04 at 16 35 44](https://user-images.githubusercontent.com/16308863/135847133-aaa7ac24-fcfc-4997-8907-7b0e1d6a2320.jpeg)

on moderator side
![cutting-character-2](https://user-images.githubusercontent.com/16308863/135847485-c9e5ccb4-dc7f-4625-b872-9da3cb449504.png)

**Comment by gustavotrott** [comment] 2021-10-04 12:43
Hey @ashishkpaul ,
are you uploading a pptx presentation?

could you please create an example pptx with this problem and attach here? then I can reproduce here and help to fix.

**Comment by ashishkpaul** [comment] 2021-10-04 13:17
Sir, not pptx, I am uploading pdf file :
[21 JUNE READING ADVANCE SESSION.pdf](https://github.com/bigbluebutton/bigbluebutton/files/7278239/21.JUNE.READING.ADVANCE.SESSION.pdf)

**Comment by antobinary** [comment] 2021-10-04 15:45
This is not a conversion problem but a Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1253952&q=svg&can=2
We are receiving lots of reports of it, afaik all of them on Chrome/Chromuim 94+

**Comment by ashishkpaul** [comment] 2021-10-04 15:55
Sir the above report on mozilla firefox
![Screenshot_2021-10-04_21-24-18](https://user-images.githubusercontent.com/16308863/135883756-20187d7b-97e7-482a-aedc-f5266e7f881e.png)

**Comment by antobinary** [comment] 2021-10-04 16:53
Hi @ashishkpaul,

I uploaded the presentation you attached to BigBlueButton 2.3.15 and it converted and displayed fine. But in that PDF I do not actually spot the paraghraphs from your first screenshot. Also the screenshot looks like it comes from Android (a guess) and I see Chrome related applications open in the top banner area...

Would you, please, be able to upload here the file which appears incorrectly?
Would you, please, provide the browser  + version of the browser where you see the incorrect characters - in this case FireFox on Linux Mint is shown to display the screenshot in the issue, not the actual BBB session.
If you upload this file to [test.bigbluebutton.org](https://test.bigbluebutton.org) (a BBB 2.3.15 public server), do you see the issue present? Do you see it across different browsers you have access to?

Thanks in advance!

**Comment by ashishkpaul** [comment] 2021-10-05 04:10
You were right sir, its a bug in chromium based web browsers. Thanks
