### ISSUE TITLE
BigBlueButton Server 2.3.14 (2457) playback returns a 404 error when trying to play a transferred recording recorded without a camera (no video directory in recording directory)

### ISSUE THREAD

**Issue by kotovi** [bigbluebutton/bigbluebutton#13376] opened 2021-10-02 14:51 UTC
BigBlueButton Server 2.3.14 (2457) playback returns a 404 error when trying to play a transferred recording recorded without a camera (no video directory in recording directory).
Empirically copying the directory solves the problem( cp ./audio/audio.webm ./video/webcams.webm) .
Please fix it, killed all day (

**Comment by pedrobmarin** [comment] 2021-10-02 17:07
Duplicate of https://github.com/bigbluebutton/bbb-playback/issues/112

**Closed by pedrobmarin** 2021-10-02 17:07 UTC
Labels: module: recording
