### ISSUE TITLE
Infinite loop of BBB tab

### ISSUE THREAD

**Issue by ejgutierrez74** [bigbluebutton/bigbluebutton#9207] opened 2020-04-22 15:09 UTC
**Describe the bug**
When you select the tab of BBB in browser, it produces a infinite loop.
**To Reproduce**
1. Go to 'Share screen'
2. Click on 'Tab of the BBB meeeting'
3. See error

**Expected behavior**
AT least one tab with the first screen of BBB. No infinite loop.

**Actual behavior**
Infinite loop of BBB tab content.

 - OS: Ubuntu 18.04, Windows 10
 - Browser [e.g. Chrome, Safari] Firefox
 - Version [e.g. 22] 75

Its very annoying and other similar software like jitsi or zoom doesnt have this problem, so its NOT a expected behaviour.

Thanks in advance

**Comment by basisbit** [comment] 2020-04-22 16:01
please add more details or screenshots or a video recording of the problem. It is not clear what is actually the issue here.

**Comment by pedrobmarin** [comment] 2020-04-22 16:29
https://github.com/jitsi/jitsi-meet/issues/2506

**Comment by basisbit** [comment] 2020-04-22 16:41
Duplicate of #7183

**Comment by GhaziTriki** [comment] 2020-04-22 16:45
Closing as duplicate of #7183
Thank you @basisbit

**Closed by GhaziTriki** 2020-04-22 16:45 UTC
