### ISSUE TITLE
Push-to-Talk Function (Space-Bar to mute like in Zoom)

### ISSUE THREAD

**Issue by Leol214** [bigbluebutton/bigbluebutton#12358] opened 2021-05-12 11:23 UTC
Hi. In my institution, many people already complained that it is really a neccesary function to be able to mute yourself by pressing a hotkey like the spacebar. It would improve time-efficiency and voice chat participation rates which is very important in online schooling or other get-togethers. I'm willing to code some stuff on my own even although I'm not a specialist. Also, hotkeys in general would make a lot of sense like leaving voicechat or turning on screen sharing or switching between certain windows. Thanks for reading my idea.

**Comment by PhMemmel** [comment] 2021-05-12 12:19
BBB already has hot keys implemented. Just open a session, go to 3-dot-menu ->keyboard shortcuts to get a list of the shortcuts. It contains also a shortcut for mute toggling.

**Comment by antobinary** [comment] 2021-05-12 14:10
Duplicate of #2045 (with a pull request #9114 )

**Closed by antobinary** 2021-05-12 14:10 UTC
