### ISSUE TITLE
Failed to fetch config.xml

### ISSUE THREAD

**Issue by netlabs** [bigbluebutton/bigbluebutton#6350] opened 2018-12-07 12:55 UTC
Hey please help with this error. I have attached bbb-conf --check and error.
I am using Letsencrypt ssl certificate. I have godaddy certificate but dont have rsa key so used this.

![image](https://user-images.githubusercontent.com/45689540/49648773-1b2a8f80-fa4d-11e8-82df-90b75405c578.png)
![image](https://user-images.githubusercontent.com/45689540/49648804-36959a80-fa4d-11e8-870c-49c3bf608f18.png)

**Comment by ffdixon** [comment] 2018-12-07 13:37
A couple of questions

1.  How did you install BigBlueButton (step-by-step or bbb-install.sh)?
2.  Did you get any errors on the installation?
3.  Did you make any manual configuration changes after the installation?

**Comment by netlabs** [comment] 2018-12-08 05:51
1) Step by Step
2) No errors
3) No manual

Will it use any ports to fetch xml file because I have opened only 80,443,1935,7443 and udp ports thats all.

**Comment by netlabs** [comment] 2018-12-08 07:44
![image](https://user-images.githubusercontent.com/45689540/49683446-2af8b100-faeb-11e8-9885-ad03ff30f831.png)
 
Got this in browser console.

**Comment by ffdixon** [comment] 2018-12-08 21:04
If this is a new setup, could you try installing with bbb-install.sh, see

  https://github.com/bigbluebutton/bbb-install

and let us know if after it finishes you still have problems loading `config.xml`.

**Comment by capilkey** [comment] 2018-12-08 22:01
The browser console won't show you anything useful here. The network tab might have something interesting for the configXML response.

**Comment by netlabs** [comment] 2018-12-09 03:18
bbb-install: DNS lookup for meet.netlabsglobal.com resolved to 27.34.244.186 but didn't match local 172.21.10.14.



![image](https://user-images.githubusercontent.com/45689540/49693035-f50d0880-fb8e-11e8-8e40-6cec31bf272f.png)

![image](https://user-images.githubusercontent.com/45689540/49693038-035b2480-fb8f-11e8-84cd-a838450d3f15.png)

**Comment by netlabs** [comment] 2018-12-10 12:18
> 
> 
> bbb-install: DNS lookup for meet.netlabsglobal.com resolved to public Ip but didn't match local 172.21.10.14.
> 
> ![image](https://user-images.githubusercontent.com/45689540/49693035-f50d0880-fb8e-11e8-8e40-6cec31bf272f.png)
> 
> ![image](https://user-images.githubusercontent.com/45689540/49693038-035b2480-fb8f-11e8-84cd-a838450d3f15.png)
> 
> ![image](https://user-images.githubusercontent.com/45689540/49693274-3227c980-fb94-11e8-959a-1462048c2775.png)

Please help me .......Urgent.

**Comment by netlabs** [comment] 2018-12-10 12:33
![capture](https://user-images.githubusercontent.com/45689540/49732821-d0578480-fca5-11e8-963f-69d8b795680a.PNG)

Please help me.

**Comment by ffdixon** [comment] 2018-12-10 13:07
For the 500 error with GreenLight, see

  https://github.com/bigbluebutton/bbb-install#green-light-not-running

For the DNS error, the entry for meet.netlabsglobal.com is not resolving for the external IP address of your server.  Is your server internally on a network (behind a firewall) or external on the internet?

**Comment by ffdixon** [comment] 2018-12-10 13:39
Hi there, can you send me a direct e-mail (my github account name) at gmail dot com.  Would like to spend a few minutes taking a look at your server if possible.

**Comment by netlabs** [comment] 2018-12-11 01:48
> For the 500 error with GreenLight, see
> 
> https://github.com/bigbluebutton/bbb-install#green-light-not-running
> 
> For the DNS error, the entry for meet.netlabsglobal.com is not resolving for the external IP address of your server. Is your server internally on a network (behind a firewall) or external on the internet?

My server is behind firewall. Its Dns record is in Godaddy with A host record. Dns lookup for meet.netlabsglobal.com is resolving to my global ip.
I have added hosts file with external ip and external host name.

**Comment by netlabs** [comment] 2018-12-11 01:49
> Hi there, can you send me a direct e-mail (my github account name) at gmail dot com. Would like to spend a few minutes taking a look at your server if possible.


Sure will send a mail. If u want I can give you a remote access to my server. For troubleshooting.

**Comment by ffdixon** [comment] 2018-12-11 15:22
Hi,

Thanks for giving us a closer look at your server.  The problem is that GreenLight (running within Docker) can't connect to your host.  This is causing the 500 error.

We determined it by running the configuration check command

~~~
http://docs.bigbluebutton.org/install/greenlight-v2.html#verifying-configuration
~~~

This returned back errors when trying to connect.  Next, we logged into the docker container (using `docker exec -it <containerID> /bin/bash`) and tried to download the `default.pdf`

~~~
  wget https://<host>/default.pdf
~~~

We also saw this failed.  But applications running within the docker container have access to the internet, as we tried

~~~
  wget https://google.com/
~~~

from within the docker container and it worked.

It means that, for some reason, any application running within the docker container is unable to access the host.  Not sure why this is happening, but that's the cause of error you are seeing in GreenLight.

**Comment by netlabs** [comment] 2018-12-13 14:46
> Hi,
> 
> Thanks for giving us a closer look at your server. The problem is that GreenLight (running within Docker) can't connect to your host. This is causing the 500 error.
> 
> We determined it by running the configuration check command
> 
> ```
> http://docs.bigbluebutton.org/install/greenlight-v2.html#verifying-configuration
> ```
> 
> This returned back errors when trying to connect. Next, we logged into the docker container (using `docker exec -it <containerID> /bin/bash`) and tried to download the `default.pdf`
> 
> ```
>   wget https://<host>/default.pdf
> ```
> 
> We also saw this failed. But applications running within the docker container have access to the internet, as we tried
> 
> ```
>   wget https://google.com/
> ```
> 
> from within the docker container and it worked.
> 
> It means that, for some reason, any application running within the docker container is unable to access the host. Not sure why this is happening, but that's the cause of error you are seeing in GreenLight.

Hey Solved this Issue

I have installed dummy NIC which solved iseeue.

**Comment by ffdixon** [comment] 2018-12-13 16:54
Glad to hear you got it working!

**Closed by ffdixon** 2018-12-13 16:54 UTC
