### ISSUE TITLE
2.6 RC4   Tldraw whiteboard events are drawn off the slide with powerpoint document.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#16786] opened 2023-02-22 17:16 UTC
**Describe the bug**
The whiteboard drawing is not in proportion in the recording, for a single slide powerpoint.

**To Reproduce**
1. upload attached powerpoint
2. turn recording on.
3. draw a line around all four edges of the slide with whiteboard.
4. view recording

**Expected behavior**
whiteboard marks are in identical position in live session and recording.

**Actual behavior**
Scale and position of whiteboard only show part of the annotations, not in the correct location,

**Screenshots**
![image](https://user-images.githubusercontent.com/519542/220705002-38b45c9b-3fe1-4a5e-815c-aabf826e2c9e.png)
should see 2 rectangles along edges of slide,   tested in dev26 as well.   recordID 79226595599f6f0af0976658fa83ed3217efa2fe-1677084486762

[testpptwithannotationissue.pptx](https://github.com/bigbluebutton/bigbluebutton/files/10806535/testpptwithannotationissue.pptx)

**Comment by kepstin** [comment] 2023-02-22 23:18
What recording format is affected? I know that the "video" format needs some updates - see https://github.com/bigbluebutton/bbb-presentation-video/issues/17 - but is the presentation format also having problems?

**Comment by kepstin** [comment] 2023-02-22 23:20
Note that this issue is caused by the changes done in https://github.com/bigbluebutton/bigbluebutton/pull/16721

**Comment by DavidPruem** [comment] 2023-02-23 10:32
I got the same issue in the presentation and video format.

**Comment by hostbbb** [comment] 2023-02-23 10:39
yes,  the standard presentation format had this as well as the video.

**Comment by antobinary** [comment] 2023-03-02 18:48
Should be closed via https://github.com/bigbluebutton/bbb-playback/pull/236

**Comment by antobinary** [comment] 2023-03-02 19:59
Confirmed by replaying the same recording before and after

before:
![Screenshot from 2023-03-02 14-47-42](https://user-images.githubusercontent.com/6312397/222538755-7dea4db6-92dc-483f-8ceb-b68905a56d18.png)


after:
![Screenshot from 2023-03-02 14-57-34](https://user-images.githubusercontent.com/6312397/222538772-a703a3a8-a28c-4e11-8a4b-8c421d1fe26d.png)


Well done @germanocaumo !!

**Closed by antobinary** 2023-03-02 19:59 UTC
Labels: priority: high, module: recording

**Comment by hostbbb** [comment] 2023-03-03 12:38
Looks good! thanks
