### ISSUE TITLE
Start conference - Connecting to echo test is not established - BBB 2.2.35

### ISSUE THREAD

**Issue by lrit18** [bigbluebutton/bigbluebutton#11552] opened 2021-03-04 12:05 UTC
![echo](https://user-images.githubusercontent.com/20736613/109961504-5ed2d900-7cea-11eb-831d-2072e9b5671a.JPG)
I like to start a conference in my conference room.
I am then asked how I would like to participate. I choose with a microphone. Then normally the connection to the echo test is established. This takes a long time. But I don't get an error message. however, the echo test cannot be carried out.
I can't cancel the echo test either. The window does not react to the click on the x.

I cannot enter the standard room I have used up to now. SOMETIMES I get the message "security key endpoint invalid". If I want to go back into the room and click on "start" nothing happens anymore.

In my newly created room I can only participate as a listener (without a microphone). 

 - OS: Windows 10
 - BrowserChrome, Mozilla Firefox

sudo bbb-conf --check
and 
sudo bbb-conf --status 
both look ok 

I would appreciate your support

**Comment by 123re-book** [comment] 2021-03-04 14:38
Had this after upgrade BBB and could solve it by runnig:
bbb-conf --setip mybbb.domain.org

**Comment by lrit18** [comment] 2021-03-04 15:00
Okay, this solved my issue.
I see if it is stable and then close the issue.

But can you tell me please why bbb-conf --setip mybbb.domain.org was necessary at all? I didn't change anything in the configuration before the error occurred. **Does BBB carry out automatic updates and did this come about?**

**Comment by basisbit** [comment] 2021-03-05 10:02
closing this as a support issue, not a bug in bbb.

**Comment by basisbit** [comment] 2021-03-05 10:02
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Closed by basisbit** 2021-03-05 10:02 UTC

**Comment by ffdixon** [comment] 2021-03-05 12:22
See steps for manual update

  https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

There are many places that use the hostname and to ensure all places are correctly updated, we use bbb-conf to update the configuration.

**Comment by lrit18** [comment] 2021-03-05 13:35
Hello Fred,
can you tell me please why bbb-conf --setip mybbb.domain.org was necessary for my issue at all? 
I didn't change anything in the configuration before the error occurred and I have not made an update.
So, does BBB simply carry out **automatic** updates and did this come about?
If yes, how can I disable this behavior?
Thanks!

**Comment by basisbit** [comment] 2021-03-06 15:50
@lrit18 check if you have unattended-upgrades enabled on your system. Maybe you also had some other issue so that one of the bbb services stopped. You can run `bbb-conf --status` to see if the necessary services are up and running. If a service crashed, check the various logs for the reason.

**Comment by basisbit** [comment] 2021-03-09 13:52
yes. Also please read https://docs.bigbluebutton.org/2.2/customize.html#apply-confsh

**Comment by ffdixon** [comment] 2021-03-10 02:42
We're working on support for having override files, such as for bbb-web in `/etc/bigbluebutton/bbb-web.properties` that override settings in `bigbluebutton.properties`.  For now, run `bbb-conf --setip <hostname>` after an upgrade.
