### ISSUE TITLE
Losing microphone and camera connections

### ISSUE THREAD

**Issue by yazilimevde** [bigbluebutton/bigbluebutton#13740] opened 2021-11-22 20:07 UTC
**When the class size is 50 and above, only when our teacher turns on his camera, our teacher's microphone and camera connections are disconnected. How can we solve this?** 
 **We installed BBB on a dedicated server.The server gives an IPV4 address.**

**Comment by ffdixon** [comment] 2021-11-23 13:22
Duplicate of #13741

**Closed by ffdixon** 2021-11-23 13:22 UTC
Labels: module: core
