### ISSUE TITLE
(Smart layout) - Bug when repositioning layout when external video is being shared

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#12678] opened 2021-06-28 21:12 UTC
**Describe the bug**
Layout doesn't reposition correctly when resizing chat / shared notes content if sharing external video - webcam is behind video (at 00:20 in the video below).

**To Reproduce**
1. As presenter, share an external video
2. share webcam
3. resize the sidebar content width

**Video**

https://user-images.githubusercontent.com/56703993/123689885-22dbfa80-d82a-11eb-8038-797f1f1743ed.mp4

**Comment by ramonlsouza** [comment] 2021-07-29 14:10
I could not reproduce it, likely fixed by #12851

**Comment by antonbsa** [comment] 2021-07-30 19:38
Tested again and It seems to be fixed!

**Closed** 2021-07-30 19:40 UTC
Labels: module: client
