### ISSUE TITLE
Cursor stays with pointer icon when hover disabled button in firefox.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#5538] opened 2018-05-14 19:06 UTC
We should see the :no_entry_sign: on FireFox too when the button is disabled
firefox:
![not-allowed-missing](https://user-images.githubusercontent.com/15806883/40017413-af0f2d98-578f-11e8-8741-14917f393aaf.png)

chrome:
![chrome-sursor](https://user-images.githubusercontent.com/15806883/40017765-a8dff8e8-5790-11e8-9aa8-a799435c3bbd.png)

**Comment by GhaziTriki** [comment] 2020-11-30 14:10
@antobinary & @Tainan404 Can we please close this?

**Comment by schrd** [comment] 2021-04-02 10:24
can't reproduce with 2.3

**Closed** 2021-04-02 11:48 UTC
Labels: HTML5 Client
