### ISSUE TITLE
Conversion PDF make with LateX very very bad

### ISSUE THREAD

**Issue by GrosQuicKFR** [bigbluebutton/bigbluebutton#8835] opened 2020-03-22 19:11 UTC
Same issue on BBB demo room.
With this PDF for example.

If I put the fourier package it's ok. (\usepackage{fourier})
But by default it's horrible.

[ds01.pdf](https://github.com/bigbluebutton/bigbluebutton/files/4366061/ds01.pdf)

**Comment by ffdixon** [comment] 2020-03-22 20:01
Wow -- your right!

![image](https://user-images.githubusercontent.com/290351/77259212-5ce94480-6c56-11ea-871a-cec11a7d725f.png)

Thanks for the troubleshooting.  We'll take a closer look at this in the next version (BigBlueButton 2.3)

**Comment by GrosQuicKFR** [comment] 2020-03-22 20:03
thanx, I don't understand, is it a chars problem ?  how did bluebuetton convert pdf document ?
BR

**Comment by idnovic** [comment] 2020-03-23 13:34
I hope you can fix this error. Because of corona we use bigbluebutton at our university. But this error makes code blocks unreadable.

![SharedScreenshot](https://user-images.githubusercontent.com/28260793/77322032-64baee80-6d13-11ea-9d2f-f6278a31d119.jpg)

**Comment by maikmerten** [comment] 2020-03-23 13:55
Same issue here with LaTeX-slides. My workaround: I rasterize all slides before uploading them to BigBlueButton. My horrible helper script:


```
#!/bin/bash
INPUT=$1
pdf2djvu --bg-subsample=1 -d 300 "$INPUT" -o "$INPUT.djvu"
ddjvu -format=pdf "$INPUT.djvu" "$INPUT.rasterized.pdf"
```

**Comment by GrosQuicKFR** [comment] 2020-03-23 14:06
Thanx for the tip !!

**Comment by drazioti** [comment] 2020-05-16 17:46
Yes,I confirm also the problem :( . In the previous version the pdfs from LaTex were ok. I notice that if you follow the route, .tex-->.dvi-->.ps-->pdf the problem disappears. Sometimes is not possible or easy to produce a pdf via the ps file (you can have errors from ghostscript). Although, again you can try the following,

    $pdftk input.pdf cat 77-100 output output.pdf

where (for instance) 77 is the starting page and 100 the last page (so you can avoid some problematic pages). Hope that helps, until the bug be fixed by the devs.

**Comment by timm2k** [comment] 2020-07-09 07:44
For some of our users a successful workaround is to add `\usepackage{lmodern}` to the TeX doc.

Here is another example. With `\usepackage{lmodern}` output is fine converted by BigBlueButton.
[ex2.pdf](https://github.com/bigbluebutton/bigbluebutton/files/4895263/ex2.pdf)

**Comment by femmefractale** [comment] 2020-07-10 12:55
It seems that the problem is with bitmap fonts. Only OTF and TTF are handled well. Using `\usepackage{lmodern}` fixes the problem for the text font, however you need to load a math font such as `\usepackage{newtxmath}` and a monospaced font such as `\usepackage[ttdefault=true]{AnonymousPro}` as well. Else the same problem appears for these text passages. 

It is difficult to communicate this problem to students that are new to latex, therefore it would be good if the conversion could be improved.

**Comment by olberger** [comment] 2020-07-22 12:52
It would clearly be great to have a conversion to PNG that works for any document. Reworking slides to make sure they fit into BBB's presentation is clearly unacceptable for many users, and changing fonts tends to break layouts in other ways...

If Adobre reader, evince and others can rasterize fonts, BBB should be able to do the same.

The conversion to djvu seems to be working AFAICT... but there maybe other options (haven't gotten a clue of the background conversion at stake)

Thanks in advance.

**Comment by hex-m** [comment] 2020-12-12 00:45
Upstream issue: https://gitlab.freedesktop.org/poppler/poppler/-/issues/268

As this only happens when directly converting to svg, the [fallback to rasterized svg](https://docs.bigbluebutton.org/2.2/architecture.html#presentation-conversion-flow) (pdf -> png -> svg) should work in those cases.

**Comment by Sangokuss** [comment] 2021-01-27 12:40
Hi,

It is difficult to ask presenters to change the font at the last moment. I think it would be simpler if it works by default.
Changing a presentation at the last moment often also involves the need to change the layout. 

Thanks in advance.

**Comment by olberger** [comment] 2021-01-27 13:02
> 
> As this only happens when directly converting to svg, the [fallback to rasterized svg](https://docs.bigbluebutton.org/2.2/architecture.html#presentation-conversion-flow) (pdf -> png -> svg) should work in those cases.

I'm not sure to get you right... in concrete matters, is there a way to use the fallback systematically, then ?

**Comment by hex-m** [comment] 2021-01-28 13:53
I don't know if the documentation I linked to is up-to-date. You could try to set `generatePngs=true` in [bigbluebutton.properties](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-web/grails-app/conf/bigbluebutton.properties) and see if the issue is gone on iOS devices. That could be a helpful start but a fix will probably need someone who is familiar with the code-base.

**Comment by olberger** [comment] 2021-04-13 07:30
> Upstream issue: https://gitlab.freedesktop.org/poppler/poppler/-/issues/268
> 

which seems to have been resolved... so there's hope of getting benefits of this for BBB :-)

**Comment by afdw** [comment] 2021-04-13 12:00
> > Upstream issue: https://gitlab.freedesktop.org/poppler/poppler/-/issues/268
> 
> which seems to have been resolved... so there's hope of getting benefits of this for BBB :-)

Not yet fully resolved. I made a fix in [the MR](https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/152), but it is not merged yet (I wait for someone to review it).

**Comment by bongoambassador** [comment] 2021-04-15 07:03
I had the same problem and in my case it was the package **_mathabx_**. Since I used that package just for one single purpose it was easy for me to get rid of it

**Comment by hex-m** [comment] 2021-04-15 09:55
@bongoambassador Thanks! Any package that uses bitmap/raster fonts (Type 3) is problematic. There is a package called `mathabx-type1` which uses vector fonts (Type 1).

**Comment by GhaziTriki** [comment] 2021-04-27 04:34
@gugat With #12124 what is the suggested configuration to get the provided file render better?

**Comment by hex-m** [comment] 2021-04-27 06:08
Setting `forceRasterizeSlides=true` on BigBlueButton 2.3-rc-1 looks much better.

![Screenshot from 2021-04-27 07-54-16](https://user-images.githubusercontent.com/16013327/116192513-41404f80-a72e-11eb-8f5a-aad67c0c5a31.png)

It should be noted that this breaks the "quick polling" feature as BBB can't interpret the content of a slide when it is rasterized.

**Comment by gustavotrott** [comment] 2021-04-27 15:17
> 
> It should be noted that this breaks the "quick polling" feature as BBB can't interpret the content of a slide when it is rasterized.

Hey @hex-m,
The text extraction is based on the original PDF! So the rasterize param will not interfere in Quick Polling!

**Comment by gustavotrott** [comment] 2021-04-27 15:46
> 
> 
> @gugat With #12124 what is the suggested configuration to get the provided file render better?

Do you mean @gustavotrott ? hahaha

`forceRasterizeSlides=true` will solve this problem!

_This param can cause lower quality on zoom (for presentations without this LateX problem)._

**Comment by GhaziTriki** [comment] 2021-04-27 16:57
Sorry @gustavotrott, I definitely mean @gustavotrott, Github tricked me 😅. I think we can detect the slides with LateX by check for Type 3 font, in that case we don't have to choose between low quality LateX rendering and low zoom quality for normal slides.

**Comment by gustavotrott** [comment] 2021-04-27 17:01
> 
> 
> Sorry @gustavotrott, I definitely mean @gustavotrott, Github tricked me 😅. I think we can detect the slides with LateX by check for Type 3 font, in that case we don't have to choose between low quality LateX rendering and low zoom quality for normal slides.

Sounds good! I will explore this approach today and let you know if I have good results!
Thanks @GhaziTriki!

**Comment by gustavotrott** [comment] 2021-04-27 17:02
> 
> 
> I hope you can fix this error. Because of corona we use bigbluebutton at our university. But this error makes code blocks unreadable.
> 
> ![SharedScreenshot](https://user-images.githubusercontent.com/28260793/77322032-64baee80-6d13-11ea-9d2f-f6278a31d119.jpg)

Hey @idnovic, do you mind to share some problematic PDF?
I would like to have more samples for my tests.
Thank you

**Comment by koenr** [comment] 2021-05-10 08:19
Here is another sample for testing
[Kettingregel_bewijs.pdf](https://github.com/bigbluebutton/bigbluebutton/files/6450558/Kettingregel_bewijs.pdf)

**Comment by antobinary** [comment] 2021-06-11 14:43
>Here is another sample for testing
> Kettingregel_bewijs.pdf

This is what I get out-of-the-box on BigBlueButton 2.3.3:
![Screenshot from 2021-06-11 10-41-12](https://user-images.githubusercontent.com/6312397/121704537-d8285780-caa1-11eb-8694-985de0db9546.png)

**Closed** 2021-06-11 14:44 UTC
Labels: component: presentation, module: web, status: accepted, type: defect
