### ISSUE TITLE
Full Screen Presenter is tiny screen on student view 2.3a6

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#11369] opened 2021-02-10 13:21 UTC
**Describe the bug**
When the presenter goes to full screen, what is displayed on the student's screen becomes small.
**To Reproduce**
1. Go to '...' (as presenter) presentation
2. Click on '....' full screen

**Expected behavior**
Full screen should fill the available screen area of the student's display, not become smaller.
**Actual behavior**
A clear and concise description of what you happened.
Full screen in the presenter mode creates smaller display on student's screen
**Screenshots**
![IMG_20210209_101152](https://user-images.githubusercontent.com/7345618/107515320-dc3a7c00-6b78-11eb-8abc-0becb3391afa.jpg)
![IMG_20210209_101158](https://user-images.githubusercontent.com/7345618/107515344-e492b700-6b78-11eb-8d55-43f3e164da24.jpg)

**BBB version (optional):**
2.3a6
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.2 (1816)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - linux windows
 - Browser [e.g. Chrome, Safari]
 - chrome firefox

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by antobinary** [comment] 2021-02-10 14:16
> BBB version (optional):
> 2.3a6
> BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
> Example:
> $ sudo bbb-conf --check | grep BigBlueButton
> BigBlueButton Server 2.2.2 (1816)

Do you see this on BBB 2.3-alpha6 or BBB 2.2.2 ?

**Comment by antobinary** [comment] 2021-02-10 16:42
Marking this as duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11092
Thank you for reporting it still, the screenshot may help us narrow down the issue

**Closed by antobinary** 2021-02-10 16:42 UTC
Labels: HTML5 Client
