### ISSUE TITLE
Whiteboard Crash

### ISSUE THREAD

**Issue by Fingadumbledore** [bigbluebutton/bigbluebutton#18943] opened 2023-10-16 12:21 UTC
**Describe the bug**
Whiteboard crash 

**To Reproduce**
1. Go to whiteboard
2. draw some stuff and select it
3. another user has to clear the whiteboard by deleting all
4. See error: cannot read properties of undefined (reading 'isStateful')

**Expected behavior**
The whiteboard should be cleared and the user should continue to draw 

**Actual behavior**
The drawing user can't continue to draw 

**Screenshots**

**BBB version:**

BigBlueButton Server: 2.7.1 

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Firefox 
 - Version 118

**Comment by antonbsa** [comment] 2024-07-04 14:11
not able to reproduce in the latest BBB 2.7 and 3.0. I've tried on firefox and chrome, different user roles, different meeting settings, etc. 

Are you still able to reproduce it? if so, please comment below any information that might help to debug it, such as any settings, steps done, and so on. media files are welcome too!

**Comment by antobinary** [comment] 2024-07-04 15:27
Thank you for trying to reproduce @antonbsa 
We've fixed quite a few things regarding whiteboard in the past few months, both in BBB 2.7 (possibly 2.7.7) and 3.0. We're going through old reports trying to reproduce. I'll close this issue now but if anything new comes up about it we can reopen.
Thanks again to the original reporter too!

**Closed by antobinary** 2024-07-04 15:27 UTC
Labels: component: whiteboard
