### ISSUE TITLE
Extend time of breakoutrooms afterwards

### ISSUE THREAD

**Issue by h2o-commits** [bigbluebutton/bigbluebutton#11198] opened 2021-01-21 15:55 UTC
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**
After setting up breakingrooms with fixed timelimit, there is no possibility to extend the time to give studends additional time. The dialog to start breakoutrooms might be reachable while breakoutsrooms are active. The given time might extend (or even decrease ) the time until die rooms will die closed.

**Describe alternatives you've considered**

I think, that there ist no alternative for this feature request. You can delete the given time and manually chat the actual time that ist left to breakoutroom (This addressed a futue chat feature as well.)  

**Additional context**

No additional context

**Comment by basisbit** [comment] 2021-01-21 20:29
duplicate of #9435

**Closed by basisbit** 2021-01-21 20:29 UTC
Labels: Enhancement
