### ISSUE TITLE
Since 2.5.10 learning dashboard can not be disabled by /etc/bigbluebutton/bbb-web.properties

### ISSUE THREAD

**Issue by wolbernd** [bigbluebutton/bigbluebutton#16416] opened 2023-01-09 08:37 UTC
**Describe the bug**
For privacy reasons we disabled the learning dashboard. We did this by adding the line `learningDashboardEnabled=false` to `/etc/bigbluebutton/bbb-web.properties`. Until 2.5.9 this worked fine, after the update to 2.5.10 the link to the learning dashboard is shown on the modal that is shown after a meeting has ended. The dashboard itself also works. 

**To Reproduce**
* Install BBB 2.5.10
* `echo "learningDashboardEnabled=false" >> /etc/bigbluebutton/bbb-web.properties`
* `bbb-conf --restart`
* Start a meeting
* End the meeting
* see the link to the dashboard on the modal about the meeting having ended

**Expected behavior**
The learning dashboard should be disabled as stated in the configuration file. 

**Actual behavior**
A link to the learning dashboard is shown and the dashboard works. 

**Additional Notes**
Unfortunately disabling the learning dashboard is not documented in the official docs, I think I found the `learningDashboardEnabled` parameter in an old issue (not sure when/where)

**Comment by ReimarBauer** [comment] 2023-01-09 08:45
I confirm the behavior. 

similiar discussion for upcoming 2.6 started on https://groups.google.com/d/msgid/bigbluebutton-dev/1c0f1929-6424-4e01-9860-67a34520c9acn%40googlegroups.com

**Comment by steffen-moser** [comment] 2023-01-09 08:46
I have just been filing a similar issue when I saw yours appearing. We see the same problem since updating to 2.5.10 last weekend. So I can confirm it. Maybe there is a link to the problem mentioned in the following posting https://groups.google.com/g/bigbluebutton-dev/c/ebvBr0zT3uI/m/J5pNAVZqCAAJ and the bug got backported from 2.6 to 2.5.

**Comment by nephilim75** [comment] 2023-01-09 10:07
I can confirm the same behavior. Dashboard cannot be disabled.

**Comment by steffen-moser** [comment] 2023-01-09 10:11
Deactivating it directly via /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties does not seem to work, either. So it is definitely not a problem of a malfunction in configuration substitution/addition by /etc/bigbluebutton/bbb-web.properties.

**Comment by antobinary** [comment] 2023-01-09 11:54
Hi!

We're looking into what's happening but meanwhile you can pass `disabledFeatures=learningDashboard` on the CREATE command

**Comment by antobinary** [comment] 2023-01-09 12:16
Looks like this is relevant: https://github.com/bigbluebutton/bigbluebutton/pull/14572/files
and specifically the extra line in resources.xml

**Comment by wolbernd** [comment] 2023-01-09 12:18
> It is documented in https://docs.bigbluebutton.org/dev/api.html (search for dashboard). Perhaps we could add this info somewhere else. Where did you expect to see it?

@antobinary I would have expected this in https://docs.bigbluebutton.org/admin/customize.html . Since I was looking for a configuration entry I thought that the API-docs were not relevant to this.

**Comment by steffen-moser** [comment] 2023-01-09 14:49
I hadn't looked up the API docs as I have been thinking of a permanent site-wide configuration option. In https://docs.bigbluebutton.org/dev/api.html it is mentioned, that it is deprecated, but still handled in 2.5 – which seems to conform to #14961. Most probably, something backported from 2.6 to 2.5.10 disabled the handling of the deprecated option.

So switching from learningDashboardEnabled=false to disabledFeatures=learningDashboard will presumably fix it.

**Comment by steffen-moser** [comment] 2023-01-09 15:11
Using the new option "disabledFeatures=learningDashboard" helped in my case.

**Comment by antobinary** [comment] 2023-01-09 17:56
Hi again! Our investigation pointed to a discontinued syntax on the upgraded version of Spring.
Two properties were affected:
`learningDashboardEnabled` and `breakoutRoomsEnabled` https://github.com/bigbluebutton/bigbluebutton/blob/v2.5.x-release/bigbluebutton-web/grails-app/conf/spring/resources.xml#L156

We are preparing a patch for this to be shipped almost immediately as BigBlueButton 2.5.11.

The change we are doing is including these properties + the default value in bigbluebutton.properties so that they can be overriden in `/etc/bigbluebutton/bbb-web.properties`

**Comment by antobinary** [comment] 2023-01-09 18:09
https://groups.google.com/g/bigbluebutton-dev/c/ru-K9b95wf4 new post comment announcing BBB 2.5.11

**Comment by antobinary** [comment] 2023-01-09 22:12
`disabledFeatures=learningDashboard` is the desired format. The other one `learningDashboardEnabled` is going to be discontinued pretty soon (but not in 2.5)

Which release notes is the link from? 2.5.11 should not be listing that :eyes:

**Comment by werk21** [comment] 2023-01-09 22:24
1) Thank you for clarification (like described on API documentation).

2) The linked change for `#disabledFeatures` in bigbluebutton.properties was made in 2.5.10 and we did not find a hint in release notes.

**Comment by antobinary** [comment] 2023-01-10 01:16
@werk21 this is the full set of changes in BBB 2.5.11: https://github.com/bigbluebutton/bigbluebutton/compare/v2.5.10...v2.5.11

I'll wait for one of the original reporters to confirm all is set for them on 2.5.11 and I'll close this issue. Thank you all!!

**Comment by wolbernd** [comment] 2023-01-10 07:27
@antobinary I can confirm that both set of options (`learningDashboardEnabled`/`breakoutRoomsEnabled`/ and `disabledFeatures` work again in 2.5.11.

Thanks for the quick fix.

**Closed** 2023-01-10 11:31 UTC
Labels: module: core
