### ISSUE TITLE
Enable Annotations on Shared Desktop

### ISSUE THREAD

**Issue by fsadlo** [bigbluebutton/bigbluebutton#9439] opened 2020-05-06 11:38 UTC
**Is your feature request related to a problem? Please describe.**
Being able to annotate shared desktops in real-time, as e.g., possible in Zoom, is incredibly helpful. For example, an advisor can graphically instruct students in their development of a GUI, writing of theses etc.

**Describe the solution you'd like**
Add the "annotation layer", which is already available in presentations and the white board, to the shared desktop mode. I imagine this should be possible by simply extending the "annotation layer" functionality to the shared-desktop stream.

**Describe alternatives you've considered**
Many users (in particular academia) seem to prefer BBB over Zoom, but need the above annotation functionality.

**Comment by fsadlo** [comment] 2020-05-06 12:12
Please merge this issue with Issue #8929, sorry for duplicating.

**Comment by prlanzarin** [comment] 2020-05-06 12:39
Duplicate of #8929

**Closed by prlanzarin** 2020-05-06 12:39 UTC
Labels: Enhancement
