### ISSUE TITLE
Removing users from conference doesn't function

### ISSUE THREAD

**Issue by SashoVihVas** [bigbluebutton/bigbluebutton#14060] opened 2022-01-11 21:10 UTC
**Describe the bug**
When a moderator tries to remove a user from the conference, it doesn't function as expected

**To Reproduce**
1. Log in as moderator.
2. Remove a user from the conference.
3. If the bug doesn't appear at the first try, log in again with the same externId (from the same browser).
4. Remove the user again as moderator.

**Expected behavior**
Moderator removes a user from the conference. User is ejected from the conference and redirected to the logoutUrl. User disappears in the list of active users that the moderator sees.

**Actual behavior**
Moderator removes a user from the conference. While on the client of the moderator everything is fine and the removed user has disappeared from the list, the client of the user doesn't disconnects. It sends ValidateAuthTokenReqMsg constantly and while not connected to audio conference, presentation and other users are visible to him.

**BBB version:**
develop branch

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome, Firefox

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser [e.g. stock browser, Safari]

**Additional context**
As I am going to create a new PR for transfering users back to the guest lobby, it is tightly connected with removing users from the conference. I just wanted to report this issue, so that there are no misunderstandings about the functionality and robustness of the new PR.

**Comment by prlanzarin** [comment] 2022-01-12 00:09
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/14039

Thanks for reporting anyways.

**Closed by prlanzarin** 2022-01-12 00:09 UTC
Labels: module: client
