### ISSUE TITLE
After demoted to viewer, breakout rooms are out of sync (appear always on)

### ISSUE THREAD

**Issue by rob0403** [bigbluebutton/bigbluebutton#15554] opened 2022-08-17 14:42 UTC
**Describe the bug**
Breakout rooms currently do not end properly. When closing breakout rooms as a moderator the breakout rooms close but they can still be seen by users (but not joined). Additionally there seems to be an issue with the time which is counting down (might be due to closing the sidebar?). (BBB 2.5.5). I think this bug were already in at least 2.5.4 but probably got introduced in 2.5 with the new breakout room feature (that I don't fully understand).

**To Reproduce**
1. Create a room with 1 moderator and 2 users.
2. Create two breakout rooms and assign the two users randomly.
3. As the moderator user close the breakout rooms.
4. On demo6.bigbluebutton.org (2.5.5.) the moderator still sees the breakout rooms and it looks like the users are still assigned to the breakout rooms but they are not. They came back to the main room (Screenshot 1) 
5. The moderator can click on "end breakout rooms" but nothing will happen (Screenshot 2)
6. Additionally, the countdown doesn't really change linearly but somehow sometimes bumps up to a couple more minutes.

**Expected behavior**
Please help explain. I am not sure what the actual intention of "Easier Setup of breakout rooms" (https://docs.bigbluebutton.org/2.5/new.html#easier-setup-of-breakout-rooms) is.

**Actual behavior**
Please see "to reproduce"

**Screenshots**
![grafik](https://user-images.githubusercontent.com/15635417/185163773-6940cde6-5815-484a-9c96-e5072294430b.png)
![grafik](https://user-images.githubusercontent.com/15635417/185164317-2e579559-2863-4798-a62a-0954dd4572b0.png)

**Desktop (please complete the following information):**
 - OS: we tried on a mixture of linux, windows
 - Browser: Reproduced on Chrome and Firefox
 - Version: current

**Smartphone (please complete the following information):**
 - Device: not tested.

**Additional context**
This feature doesn't seem to work properly: https://docs.bigbluebutton.org/2.5/new.html#easier-setup-of-breakout-rooms

**Comment by rob0403** [comment] 2022-08-17 14:57
Additional information:

- User1 and User 2 don't see the breakout rooms anymore after "closing" but the moderator does
- The moderator can't join the breakout room; it only states "create url": 
![grafik](https://user-images.githubusercontent.com/15635417/185172602-0f518606-3a32-4d1a-9111-04fb91958e4b.png)

**Comment by antobinary** [comment] 2022-08-17 16:08
Hi @rob0403 
I just tried reproducing this on test25.bigbluebutton.org -- 2.5.5(prerelease) client build 2840
I could not reproduce it from quite a few attempts. I used API MATE to create a meeting and join. In all trials when the moderator hits "End breakout rooms", the breakouts are all destroyed. I tried both the case when User1 and 2 accept and join the breakouts (and then breakouts end) and the case when breakouts end while still empty.

Any chance you could clarify on the following:
- does it happen every time for you?
- do you end the breakouts when people are in them?
- perhaps if you could record a brief screen recording of this (ideally with English locale) this would help us reproduce
- if you're testing on test25 or demo, please copy-paste some sessionToken or use username issue15554 so I can try to look at the right logs


P.S. I am not sure what the actual intention of "Easier Setup of breakout rooms" -- if you intended for User1 to always go to breakout A and User2 to always go to breakout B, you would only have to do it once manually (or could even pass roster belonging via api). If you do the manual dragging of the users in the breakouts -> create breakouts, then end the breakouts and initiate a new set of breakouts, the columns with users will be pre-populated the way you wanted them, without any action on your part.

**Comment by rob0403** [comment] 2022-08-17 17:57
Hi @antobinary , thanks for looking into this. 
1. This happens every time for me. 
2. I open two breakout rooms and make the two users join one room each. Then, as the moderator, I close the breakout rooms from the main room. Then the behaviour is somewhat confusing. When I just reproduced the moderator didn't see the breakout rooms anymore but the users did. In the screenshot attached above the moderator still sees the breakout rooms. This is somewhat strange.
3. Maybe I can show you? Just texted you on element (matrix messenger).
4. Demo was just pretty slow and for test25 I don't know how to join the same room with multiple users.

**Comment by antobinary** [comment] 2023-02-06 20:33
Cannot reproduce anymore (BBB 2.6.0-rc.2)
It may have been resolved by @GuiLeme in https://github.com/bigbluebutton/bigbluebutton/pull/16492

**Closed by antobinary** 2023-02-06 20:33 UTC
Labels: status: accepted, module: core, type: bug, component: breakout rooms
