### ISSUE TITLE
Recording processing: process_worker.rb send success event before being done?

### ISSUE THREAD

**Issue by arapoport** [bigbluebutton/bigbluebutton#8778] opened 2020-03-14 00:13 UTC
Hi,

on some very rare occasions we get error from publish worker:
```
E, [2020-03-13T23:26:10.464408 #18300] ERROR -- : No such file or directory @ rb_sysopen - /var/bigbluebutton/recording/process/presentation/bdb5655a2b535a9f5869157d2d1625ed020b9f54-1584091302236/processing_time
```

However the "process" step completes after(!) "publish":
```
I, [2020-03-13T23:26:10.469777 #18297]  INFO -- : Publish format presentation failed for bdb5655a2b535a9f5869157d2d1625ed020b9f54-1584091302236
I, [2020-03-13T23:26:10.779764 #16970]  INFO -- : Process format presentation succeeded for bdb5655a2b535a9f5869157d2d1625ed020b9f54-1584091302236
```

The file "processing_time" exists. It is being written after the line "Process format presentation succeeded" is logged.

Simply rebuilding recordings usually helps.

I looked into sources and my guess is that "process" step sends "success" event before writing the file "processing_time". And in between "publish" may run and fail without that file...

Here is excerpt from [process_worker.rb](https://github.com/bigbluebutton/bigbluebutton/blob/master/record-and-playback/core/lib/recordandplayback/workers/process_worker.rb) with my comments:

```ruby
    # Send success (too soon?)
    @publisher.put_process_ended(@format_name, @meeting_id, success: step_succeeded, step_time: step_time)

    if step_succeeded
      @logger.info("Process format succeeded for #{@full_id}:#{@format_name}")
      FileUtils.mkdir_p("#{@recording_dir}/process/#{@format_name}/#{@full_id}")
      
      # Write file (too late?)
      IO.write("#{@recording_dir}/process/#{@format_name}/#{@full_id}/processing_time", step_time)
      
      run_post_scripts(@post_scripts_path)
    else
      @logger.error("Process format failed for #{@full_id}:#{@format_name}")
      FileUtils.touch(@processed_fail)
    end
    @logger.info("Process took #{step_time}ms")
```

**Comment by matiasilva** [comment] 2020-06-17 22:19
Interesting. Have you run into this problem ever since?

**Comment by arapoport** [comment] 2020-06-18 11:58
@matiasilva, actually no. I did not get to bottom of the problem. We switched to faster disk system and problem does not appear any more. I suspect the problem is still there but appears only when write operations are occasionally really slow.

**Comment by matiasilva** [comment] 2020-06-18 12:09
Interesting. Thanks for following up. Without a way to reproduce this, it's difficult to find the root cause of the problem. I'll close this but do feel free to comment if you run into this again.

**Closed by matiasilva** 2020-06-18 12:09 UTC
