### ISSUE TITLE
Autofocus on the speaker

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/bigbluebutton#9831] opened 2020-06-13 09:01 UTC
Please, add autofocus on a person which is currently talking. 

By now it is possible to do that manually, however, in case of a big group of people, talking one by one, this function doesn't make sense.

This will help to make the videoconference more comfortable for participants.

**Comment by prlanzarin** [comment] 2020-06-14 18:20
Duplicate of #8388

**Closed by prlanzarin** 2020-06-14 18:20 UTC
Labels: Enhancement
