### ISSUE TITLE
Members joining via phone don't appear in members list. BBB 2.3 beta 2

### ISSUE THREAD

**Issue by erichrueger** [bigbluebutton/bigbluebutton#11947] opened 2021-04-08 13:58 UTC
**Describe the bug**
Members joining via phone don't appear in members list.

**To Reproduce**
1. Start conference.
2. Dial into the conference from a phone.
3. Enter the PIN-code on the phone to join the conference room
4. The person using the phone can listen and talk inside the conference. 

**Expected behavior**
The phone number of the user connected via phone is being shown in the members list.

**Actual behavior**
The phone number of the user connected via phone is not being shown in the members list.

**BBB version (optional):**
2.3 beta 2

**Comment by prlanzarin** [comment] 2021-04-08 14:02
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11860

**Closed by prlanzarin** 2021-04-08 14:02 UTC
Labels: module: client
