### ISSUE TITLE
[2.3 RC2] Presentation gets overlapped on click to show/hide polling panel

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#12182] opened 2021-04-28 02:58 UTC
**PS:** This is depends to the screen size.
On my XLarge screen, I could only reproduce it after resizing the window to ~75% the width of the screen.
And on my 17" laptop's screen, I could reproduce it in full size window.

This is now reproducible on opening closing polling panel on 2.3 RC2

**To reproduce:**
1. Share webcam
2. Open polling panel
3. Click on polling button in userslist to hide it
4. See result on opening and closing polling panel

**Current behavior:**

https://user-images.githubusercontent.com/5144311/116339499-ebae8600-a7b3-11eb-83b6-628761950795.mp4

**Expected behavior:**
Presentation should not get any overlaps on clicking on any element (for this case; panels as polling, shared notes, chat... etc)

_Originally posted by @daminebenq in https://github.com/bigbluebutton/bigbluebutton/issues/12050#issuecomment-828104162_

**Comment by JustinMogel** [comment] 2021-05-12 08:29
was not able to reproduce this, i tried chrome, firefox and edge

**Comment by antobinary** [comment] 2021-05-12 14:12
I have seen this in ~2.3.1. Just can't consistently reproduce...

**Comment by jibon57** [comment] 2021-05-13 04:37
This problem still exist in 2.3.1 

<img width="924" alt="image" src="https://user-images.githubusercontent.com/6080277/118078035-20872380-b3d7-11eb-915c-2845ba0db9d7.png">

**Comment by ramonlsouza** [comment] 2021-08-25 13:10
not reproducible in 2.4 (likely fixed by changes made to layouts)

**Comment by antobinary** [comment] 2021-08-25 13:25
I am switching the milestone back to 2.3, but I am not sure if we'll be able to take a look at this soon. I am very happy this does not occur on 2.4+

**Comment by antobinary** [comment] 2021-10-12 19:00
@ramonlsouza does https://github.com/bigbluebutton/bigbluebutton/pull/13461 close this as well?

**Comment by ramonlsouza** [comment] 2021-10-13 11:19
> @ramonlsouza does #13461 close this as well?

Yes, it does

**Closed** 2021-10-13 12:27 UTC
