### ISSUE TITLE
"+" in CallerID presented as "%2B" i Listeners window

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1972] opened 2015-08-12 07:54 UTC
Originally reported on Google Code with ID 1218

```
Setup :

Up-to-date Ubuntu 10.04.
Fresh install of BBB, and FreeSwitch on a seperate server.
Dial into the voicebridge from a SIP-Provider/user connected to the FreeSwitch server
to the voicebridge.

I tested with Calling into Freeswitch on conference: 72013@wideband with a couple of
lines .. chatting away .. :)

Then you log in on the BBB demo3.jsp selecting english 2013, wich uses the same voiceBridge
number (72013) ..

Now Existing listeners with a preceding "+" in the CallerID, the "+" is presented as
"%2B".
New Listeners joining the class via the FreeSwitch voicebridge after the web is "opened"
is presented correctly (with a "+") ..
```

Reported by `torstein.knutsen` on 2012-05-04 15:35:03

**Comment by ffdixon** [comment] 2018-02-03 03:58
Unable to reproduce

![image](https://user-images.githubusercontent.com/290351/35762827-8fdb7fb6-086c-11e8-82ec-5daa443c1f03.png)

Closing this issue.

**Closed by ffdixon** 2018-02-03 03:58 UTC
Labels: Defect, Normal Priority, Usability, Voice
