### ISSUE TITLE
No Camera on iPadOS 16.4.x and BBB 2.6.6 and 2.6.7

### ISSUE THREAD

**Issue by makabar** [bigbluebutton/bigbluebutton#17926] opened 2023-05-16 05:45 UTC
While starting session or trying to start up camera on running session BBB shows an pop up message "Please update to iOS 12.2 or higher" but iPadOS 16.4.x is currently running.
Tested it on BBB 2.6.6 and 2.6.7
iPadOS not iOS - my fault

**Comment by makabar** [comment] 2023-05-16 08:45
Thank You. I´ll test it if current meetings are gone and will report soon

**Comment by antobinary** [comment] 2023-05-17 13:10
Thanks for reporting!

Marking as a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/17882
Fixed via https://github.com/bigbluebutton/bigbluebutton/pull/17904
Will be shipped as part of 2.6.8 as @ffdixon wrote above.

**Closed by antobinary** 2023-05-17 13:10 UTC
Labels: module: client
