### ISSUE TITLE
Under some conditions FreeSWITCH gradually consuming too much memory

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#13988] opened 2021-12-28 14:59 UTC
**Describe the bug**
FreeSWITCH is gradually consuming to much memory on the server.

**To Reproduce**
We don't have the steps to reliably reproduce this issue.  In a poll of 100's of 2.4 servers, we are seeing FreeSWITCH grow in size and use too much memory.

Working on reproducing it.

**Expected behavior**
FreeSWITCH memory uses grows and shrinks as normal in 2.3.

**Actual behavior**
Sometimes FreeSWITCH memory continues to slowly grow.

**Screenshots**
Here are screen shots from a 16 G server.

![f1](https://user-images.githubusercontent.com/290351/147578931-7190f836-89ec-4775-a075-de806f04dc86.jpeg)

![f2](https://user-images.githubusercontent.com/290351/147578938-096a7cb4-5606-489b-a652-86e72d5d2fc2.jpeg)

![f3](https://user-images.githubusercontent.com/290351/147579072-bcef0501-7254-44d0-916d-c5937a7c86fc.jpeg)

**Additional context**
BigBlueButton 2.4

Reference
  - https://groups.google.com/g/bigbluebutton-dev/c/AjgIq15hs9o/m/fzUAh_9MDgAJ

**Comment by ffdixon** [comment] 2021-12-28 15:03
To run FreeSWITCH commands use `fs_clibbb`.

A few questions on this
  - How many users are currently connected to FreeSWITCH (`show channels`)
  - Is there anything in particular around the voice usage ... large number of users in a voice conference?
  - If you execute `hupall` does the memory usage drop again?

**Comment by ali-alhaidary** [comment] 2021-12-28 15:11
For us, we noticed a decrease in memory usage after upgrade from the latest rc to 2.4

![Screenshot 2021-12-28 at 12-05-38 almajlis - DigitalOcean](https://user-images.githubusercontent.com/75235623/147579829-96d074a4-57d3-488f-a55a-148ff90c1489.png)

**Comment by ffdixon** [comment] 2021-12-28 16:14
Other components seem to be operating normally.  The problem is isolate to FreeSWITCH.  We're very interested if others encounter this issue and knowing what users were doing just before the memory started to increase.

**Comment by uozbek** [comment] 2021-12-29 06:25
After restart the BBB server and use for live classroom RAM usage back to normal values approximately 4 GB ~ 6 GB.  I will monitor the usage and I will be informed about this problem. 
@ffdixon When  I notice the high usage on the live classes max 3 rooms, 80 users and 4 microphones using. I mean didn't have any heavy load on the BBB and Freeswitch services.

**Comment by ffdixon** [comment] 2021-12-29 18:09
Thanks @uozbek -- we're working on trying to reproduce the issue under a simulated load.  How many BigBlueButton servers do you have?

**Comment by ffdixon** [comment] 2021-12-29 18:18
We're investigating a server now that was showing the memory issue.  It had 22 channels in FreeSWITCH from `show channels`. 

![image](https://user-images.githubusercontent.com/290351/147691887-2f410e8e-e27e-49c3-ab5a-53ebad401cec.png)


After taking the server out of the pool and letting some of the channels close (users disconnect), we checked it again and it had 8 channels and the memory had dropped to normal. 

![image](https://user-images.githubusercontent.com/290351/147691843-dd10210b-a7d9-4f01-aea5-cd28cc0860b1.png)

**Comment by rakibulinux** [comment] 2022-01-03 08:57
@ffdixon I am getting this error. I have 3 servers but just one public IP address. Can you please let me know what can be the problem?

https://user-images.githubusercontent.com/59226530/147913273-8aa8944f-cce4-48d0-9854-2ba7213c6661.mp4

**Comment by ffdixon** [comment] 2022-01-03 13:03
@rakibulinux Your question does not have anything to do with the current issue.  Trying to solve multiple problems in the same issue is not good. 

Please post this to bigbluebutton-setup and we'll try to help you there.  If we find an issue with BigBlueButton/Greenlight, we can open an issue in GitHub to track it.

**Comment by ffdixon** [comment] 2022-02-17 14:18
We are seeing that some companies are no longer experiencing this issue after deploying BigBlueButton 2.4.4 to production (we had patched FreeSWITCH in 2.4.3 and included the patched version in the build).  

We are interested if there are other organizations following this thread who are still seeing this issue in 2.4.4.

**Comment by SebastianZiegler** [comment] 2022-02-22 12:35
nearly same problem under 2.3.17

fs_clibbb

**Comment by ffdixon** [comment] 2022-02-22 12:37
Is it an option for you to upgrade to 2.4.4?

**Comment by prlanzarin** [comment] 2022-02-22 12:38
> nearly same problem under 2.3.17
> 
> fs_clibbb

@SebastianZiegler 

2.3.18 and 2.4.4 both have tentative fixes for this issue (as mentioned on their release notes). I recommend upgrading to either (whichever one is easiest for you).

**Comment by SebastianZiegler** [comment] 2022-02-22 13:01
thx for that information, I will update to 2.3.18 this evening. I let you know if it still occour after that

**Comment by SebastianZiegler** [comment] 2022-02-25 06:51
problem still exists, I updated on Thuesday evening to 2.3.18, today morning server had a lot of load 

# Potential problems described below
/usr/bin/bbb-conf: line 885:  6068 Done                    echo "/quit"
      6069 Segmentation fault      (core dumped) | /opt/freeswitch/bin/fs_cli -p                                                                  $ESL_PASSWORD - > /dev/null 2>&1

#
# Error: Unable to connect to the FreeSWITCH Event Socket Layer on port 8021
#

**Comment by SebastianZiegler** [comment] 2022-02-26 20:29
any ideas? here is a part of our syslog, there were no users on the server, cpu increaded by nearly 10% and didn't decrease until restart

Feb 25 23:58:46 bbb6 bbb-fsesl-akka[18863]: 2022-02-25T23:58:46.923+01:00 DEBUG o.b.f.v.f.a.CheckFreeswitchStatusCommand - Check FreeSWITCH Status.
Feb 25 23:58:46 bbb6 bbb-fsesl-akka[18863]: 2022-02-25T23:58:46.925+01:00 INFO  o.b.f.v.f.a.CheckFreeswitchStatusCommand - ["UP 0 years, 0 days, 14 hours, 40 minutes, 18 seconds, 596 milliseconds, 657 microseconds","FreeSWITCH (Version 1.10.7-release git 883d2cb 2021-10-24 16:39:33Z 64bit) is ready","133 session(s) since startup","0 session(s) - peak 71, last 5min 0 ","0 session(s) per Sec out of max 30, peak 2, last 5min 0 ","1000 session(s) max","min idle cpu 0.00/99.97","Current Stack Size/Max 244K/244K"]
Feb 25 23:58:47 bbb6 bbb-fsesl-akka[18863]: 2022-02-25T23:58:47.146+01:00 INFO  o.b.f.v.freeswitch.ESLEventListener - Received Heartbeat from Freeswitch.
Feb 25 23:58:58 bbb6 run-prod.sh[18824]: 2022-02-25T23:58:58.493+01:00 DEBUG o.b.web.controllers.ApiController - ApiController#getMeetings
Feb 25 23:58:58 bbb6 run-prod.sh[18824]: 2022-02-25T23:58:58.494+01:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=43c9e83763bbe9df8fb4bcb7e75fa81389cbbab31aaa3a34c4b679f82363031a length=64
Feb 25 23:58:58 bbb6 run-prod.sh[18824]: 2022-02-25T23:58:58.494+01:00 INFO  o.b.api.ParamsProcessorUtil - SHA256 43c9e83763bbe9df8fb4bcb7e75fa81389cbbab31aaa3a34c4b679f82363031a
Feb 25 23:58:58 bbb6 run-prod.sh[18824]: 2022-02-25T23:58:58.494+01:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=43c9e83763bbe9df8fb4bcb7e75fa81389cbbab31aaa3a34c4b679f82363031a length=64
Feb 25 23:58:58 bbb6 run-prod.sh[18824]: 2022-02-25T23:58:58.494+01:00 INFO  o.b.api.ParamsProcessorUtil - SHA256 43c9e83763bbe9df8fb4bcb7e75fa81389cbbab31aaa3a34c4b679f82363031a
Feb 25 23:59:07 bbb6 bbb-fsesl-akka[18863]: 2022-02-25T23:59:07.133+01:00 INFO  o.b.f.v.freeswitch.ESLEventListener - Received Heartbeat from Freeswitch.
Feb 25 23:59:07 bbb6 systemd_start_frontend.sh[18920]: #033[32minfo#033[39m: Active connections
Feb 25 23:59:07 bbb6 systemd_start_frontend.sh[18961]: #033[32minfo#033[39m: Active connections
Feb 25 23:59:27 bbb6 bbb-fsesl-akka[18863]: 2022-02-25T23:59:27.147+01:00 INFO  o.b.f.v.freeswitch.ESLEventListener - Received Heartbeat from Freeswitch.
Feb 25 23:59:37 bbb6 systemd_start_frontend.sh[18920]: #033[32minfo#033[39m: Active connections
Feb 25 23:59:37 bbb6 systemd_start_frontend.sh[18961]: #033[32minfo#033[39m: Active connections
Feb 25 23:59:40 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:40.092+01:00 DEBUG o.b.web.controllers.ApiController - ApiController#getMeetings
Feb 25 23:59:40 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:40.093+01:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=9c96d2349bd7f43cab69f40f94588489a7f8f8ce length=40
Feb 25 23:59:40 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:40.093+01:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=9c96d2349bd7f43cab69f40f94588489a7f8f8ce length=40
Feb 25 23:59:41 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:41.179+01:00 DEBUG o.b.web.controllers.ApiController - ApiController#getMeetings
Feb 25 23:59:41 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:41.179+01:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=9c96d2349bd7f43cab69f40f94588489a7f8f8ce length=40
Feb 25 23:59:41 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:41.179+01:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=9c96d2349bd7f43cab69f40f94588489a7f8f8ce length=40
Feb 25 23:59:42 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:42.243+01:00 DEBUG o.b.web.controllers.ApiController - ApiController#getMeetings
Feb 25 23:59:42 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:42.243+01:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=9c96d2349bd7f43cab69f40f94588489a7f8f8ce length=40
Feb 25 23:59:42 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:42.243+01:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=9c96d2349bd7f43cab69f40f94588489a7f8f8ce length=40
Feb 25 23:59:43 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:43.289+01:00 DEBUG o.b.web.controllers.ApiController - ApiController#getMeetings
Feb 25 23:59:43 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:43.289+01:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=9c96d2349bd7f43cab69f40f94588489a7f8f8ce length=40
Feb 25 23:59:43 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:43.289+01:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=9c96d2349bd7f43cab69f40f94588489a7f8f8ce length=40
Feb 25 23:59:44 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:44.310+01:00 DEBUG o.b.web.controllers.ApiController - ApiController#getMeetings
Feb 25 23:59:44 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:44.311+01:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=9c96d2349bd7f43cab69f40f94588489a7f8f8ce length=40
Feb 25 23:59:44 bbb6 run-prod.sh[18824]: 2022-02-25T23:59:44.311+01:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=9c96d2349bd7f43cab69f40f94588489a7f8f8ce length=40
Feb 25 23:59:47 bbb6 bbb-fsesl-akka[18863]: 2022-02-25T23:59:47.147+01:00 INFO  o.b.f.v.freeswitch.ESLEventListener - Received Heartbeat from Freeswitch.
Feb 25 23:59:51 bbb6 bbb-fsesl-akka[18863]: 2022-02-25T23:59:51.923+01:00 DEBUG o.b.f.v.f.a.CheckFreeswitchStatusCommand - Check FreeSWITCH Status.
Feb 25 23:59:51 bbb6 bbb-fsesl-akka[18863]: 2022-02-25T23:59:51.924+01:00 INFO  o.b.f.v.f.a.CheckFreeswitchStatusCommand - ["UP 0 years, 0 days, 14 hours, 41 minutes, 23 seconds, 595 milliseconds, 851 microseconds","FreeSWITCH (Version 1.10.7-release git 883d2cb 2021-10-24 16:39:33Z 64bit) is ready","133 session(s) since startup","0 session(s) - peak 71, last 5min 0 ","0 session(s) per Sec out of max 30, peak 2, last 5min 0 ","1000 session(s) max","min idle cpu 0.00/91.27","Current Stack Size/Max 244K/244K"]

**Comment by SebastianZiegler** [comment] 2022-02-27 08:32
that are virtual server with 16 cores 32 GB of RAM, we use our own STUN Server. I think problem began after 2.314 or 2.3.15 before that, the server run without problems. What else do you want to know?

Sometimes the increased cpu usage comes after days or weeks, last week I updated the server and on one server it starts 14 hours after reboot, the other servers a still fine.

**Comment by mariogasparoni** [comment] 2022-03-29 19:36
This problem was being caused by a regression introduced in FreeSWITCH.
Here's a patch for this https://github.com/signalwire/freeswitch/pull/1531 , which got it's fix included in another PR (see the history).
The current version of BBB already includes this fix

**Closed by mariogasparoni** 2022-03-29 19:36 UTC
Labels: status: accepted, module: core, module: audio, type: bug, component: microphone, component: listen only
