### ISSUE TITLE
Locking private chat also locks public chat

### ISSUE THREAD

**Issue by dsjiern** [bigbluebutton/bigbluebutton#12053] opened 2021-04-16 12:34 UTC
**Describe the bug**
I run BBB beta-3 with docker and when disabling private chat for users te public chat also was disabled. Also the participants cannot chat with the moderator.
With beta-2 the problem doesn't exist!

**To Reproduce**
1. restrict participant rights
2. disable private chat
3. try to chat as participant

**Expected behavior**
Public chat independant from this lock-settings

**Actual behavior**

**Screenshots**
as admin: ("lock private chat", public chat is not locked!)
<img width="512" alt="grafik" src="https://user-images.githubusercontent.com/29799323/115024627-a12e2f00-9ec0-11eb-8d40-177934aed0be.png">

as participant: (public chat: "chat is locked")
<img width="338" alt="grafik" src="https://user-images.githubusercontent.com/29799323/115024664-af7c4b00-9ec0-11eb-8611-5d7fb3d0f5d9.png">

**BBB version (optional):**
v2.3-beta-3 (running wirth docker)

**Comment by PhMemmel** [comment] 2021-04-16 12:49
Duplicate of #11986. I've fixed that in #11989 and #12013 which both have already been merged. So this problem should be fixed in beta4. Issue can be closed.

**Closed** 2021-04-16 16:01 UTC
Labels: module: client
