### ISSUE TITLE
Disconnect user's webcam when entering a breakout room

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7305] opened 2019-04-25 00:39 UTC
When putting users into breakout rooms, the HTML5 client currently disconnects the audio in the main room, but it should also disconnect the video as well.

(This was also how it worked in the Flash client).

**Comment by capilkey** [comment] 2019-04-25 05:27
Duplicate of #7291

**Closed by capilkey** 2019-04-25 05:27 UTC
