### ISSUE TITLE
BigBlueButton (maybe BigBlueButtonBN?) not respecting defaultWelcomeMessage

### ISSUE THREAD

**Issue by ed-Media** [bigbluebutton/bigbluebutton#10740] opened 2020-10-28 12:26 UTC
**Describe the bug**
The default welcome message was changed with this guide https://docs.bigbluebutton.org/2.2/customize.html

When creating a session with Greenlight the new welcome message is shown correctly. However if I start a session with Moodle and BigBlueButtonBN it does not work.

**To Reproduce**
Go into Moodle
Create a BigBlueButtonBN activity
Start created activity

**Expected behavior**

Just like in Greenlight it should show the defaultWelcomeMessage that was set using the customization.

**Actual behavior**

It uses the original default Message of defaultWelcomeMessage.

**BBB version (optional):**
Server 2.2.28 (2210)

**Desktop (please complete the following information):**

All devices

**Smartphone (please complete the following information):**

All devices

**Additional context**

I'm not sure if this is a BigBlueButton issue or a BigBlueButtonBN issue. I have also created a Topic in the Moodle forum (https://moodle.org/mod/forum/discuss.php?d=412677) however I have not had a reply there, so I can't really decide if it's a bug of BBB itself or the Moodle plugin.

**Comment by matiasilva** [comment] 2020-10-29 20:35
Can you confirm that the Moodle plugin uses the same server?

**Comment by ed-Media** [comment] 2020-10-29 22:12
Yes, can confirm that bigbluebuttonbn_server_url and bigbluebuttonbn_shared_secret are set to the same server as Greenlight.

**Comment by matiasilva** [comment] 2020-10-30 13:15
What welcome message is displayed? It's possible that the Moodle plugin overrides the server default. I highly doubt this is an actual bug though, probably just undesired behavior.

**Comment by ed-Media** [comment] 2020-10-30 13:27
This is what it shows (in German):

**Welcome Message:**
--------

Willkommen bei der Testraum-Konferenz !

Um zu zeigen, wie BigBlueButton arbeitet, haben wir [Tutorial-Videos](https://bigbluebutton.org/html5/) erstellt.

Verwenden Sie bitte ein Headset, um Störungen durch Geräusche zu vermeiden.

--------

Testraum --> The name of the activity in Moodle

It's basically the default welcome message.

This is what it should say:

defaultWelcomeMessage=Herzlich Willkommen im Online-Seminarraum der *client name redacted*!<br><br>Nutzen Sie diesen &ouml;ffentlichen Chat f&uuml;r alle Fragen und Beitr&auml;ge.<br><br>Am Ende der Veranstaltung k&ouml;nnen Sie die Inhalte des &ouml;ffentlichen Chats herunterladen.<br><br>Verwenden Sie bitte ein Headset, um St&ouml;rungen durch Nebenger&auml;usche zu vermeiden.<br><br>Ihr Mikrofon k&ouml;nnen Sie &uuml;ber das Mikrofonsymbol selbstst&auml;ndig frei- oder stummschalten.<br><br>Bei Audioproblemen k&ouml;nnen Sie Ihre Audioverbindung &uuml;ber das Telefonsymbol neu starten.

(The weird characters are ö ü ä)

**Footer:** 
----

Dieser Server wird mit BigBlueButton betrieben.

----

The Footer is actually the text that I've set in the config at:

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

defaultWelcomeMessageFooter=Dieser Server wird mit <a href="https://docs.bigbluebutton.org/" target="_blank"><u>BigBlueButton</u></a> betrieben.

**Comment by matiasilva** [comment] 2020-10-30 18:24
Yeah, as I thought -- not a bug. What's happening is that the Moodle mod overrides the server's Welcome message and specifies its own default (if you just search "welcome" in the GH repo: https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/search?q=welcome". Your custom welcome message will also need to be set in the Moodle interface. Closing this :)

**Closed by matiasilva** 2020-10-30 18:24 UTC
Labels: HTML5 Client
