### ISSUE TITLE
Changing audio device in the middle of a session

### ISSUE THREAD

**Issue by MAMEK70** [bigbluebutton/bigbluebutton#10683] opened 2020-10-20 17:09 UTC
**Describe the bug**
Changing audio devices (switching between internal and external devices) in the middle of a session works seamlessly when using a phone or a tablet (android). However on a windows 10 PC, changing an audio device requires leaving the audio bridge and reconnect again to be able to use the newly selected audio device. 

**To Reproduce**
1. log in a session using PC internal mic 
2. Once in a session, plug in external mic
3. BBB does not recognize the change of microphone. Audio ceases to work.
4. Unplugging the external mic does not solve the problem, switching off and on the audio bridge is necessary to join the audio again with either microphone.

**Expected behavior**
The new microphone should be recognized , according to the PC audio devices set up . It does work for android phones and tablets.

**Desktop :**
 - OS: Windows 10
 - Browser Chrome

**Comment by matiasilva** [comment] 2020-10-21 07:22
Duplicate of #9723

**Closed by matiasilva** 2020-10-21 07:22 UTC
Labels: HTML5 Client
