### ISSUE TITLE
BBB 2.6 Панель інструментів дошки

### ISSUE THREAD

**Issue by Nick64M** [bigbluebutton/bigbluebutton#17356] opened 2023-03-29 12:05 UTC
The toolbar closes part of the content of the presentation. I need to move further.

![panel](https://user-images.githubusercontent.com/95514883/228529723-d2539a6a-d66d-424d-9a39-dbb6db0cf0fb.jpg)

**Comment by antobinary** [comment] 2023-03-29 13:26
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/15739

**Closed by antobinary** 2023-03-29 13:26 UTC
Labels: module: client
