### ISSUE TITLE
Layout manager for html5

### ISSUE THREAD

**Issue by amguirado73** [bigbluebutton/bigbluebutton#9794] opened 2020-06-08 10:49 UTC
Hello,

We would like modify layout. We have found /var/www/bigbluebutton/client/conf/layout.xml but It seems to work only for flash client. Is there some planification for a layout manager for html5 client?.

We want to move the video to right side and make it smaller.

Thanks
Regards

**Comment by basisbit** [comment] 2020-06-08 12:57
Duplicate of #5836

**Closed by basisbit** 2020-06-08 12:57 UTC
Labels: HTML5 Client
