### ISSUE TITLE
sharing a local MP4 video to the students

### ISSUE THREAD

**Issue by ferrazza1** [bigbluebutton/bigbluebutton#9121] opened 2020-04-17 09:38 UTC
I would like to show a video (AVI or MP4) to the students before discussing it as part of a presentation, in class I usually embed the video within the presentation but when I deliver it on line the students can not see it or hear it.

thank you

Alex

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by ffdixon** [comment] 2020-04-17 11:17
Turns out if you use Chrome on Mac OS X, then share your screen in BigBlueButton, Chrome will broadcast both the screen (which is showing your video) and the audio of the video as well.

This isn't the case on Windows, but it does work on Mac OS X + Chrome.

**Comment by hex-m** [comment] 2020-06-08 10:11
This is a duplicate of #8276

**Closed** 2020-06-09 18:28 UTC
