### ISSUE TITLE
Restrict or limit maximum number of open wecams per meeting

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1523] opened 2015-08-12 07:35 UTC
Originally reported on Google Code with ID 768

```
1- This is a request to restrict or limit maximum number of webcams that can be opened
per meeting in bigbluebutton. 

This(setting maximum number of webcams that can be opened in a single meeting) must
be done before the meeting is started. 

Would be nice to have API call to do that.

Moderator or presenter should always be able to open webcams.
(you may except moderator or presenter from the maximum number of open webcams allowed
so that they can always open webcams regardles of maximum number set)

2- when meeting is in session, moderator or presenter is given ability to close/lock
all opened webcams and let only their(moderator or presenter) webcams open at anytime
when necessary.
This is something when meeting is in session, say, 5 webcams are open and  you want
to close all webcams and lock with single click when meeting is still going on. Moderator
or presenter is excepted, they individualy be able to open/close their own webcams
at any time.

Request "1" would be a good feature to have in bigbluebutton and I will be looking
forward to using this feature.
2 may not be as important, but would be nice to have.

Thanks and regards
deniro--



```

Reported by `ayhkor` on 2010-11-28 02:08:28

**Comment by hex-m** [comment] 2020-11-27 15:26
duplicate of #8844

**Closed** 2020-11-27 15:30 UTC
Labels: Enhancement, Low Priority, Video
