### ISSUE TITLE
Request To share audio when a video is playing in a shared application window

### ISSUE THREAD

**Issue by jingwenw** [bigbluebutton/bigbluebutton#8927] opened 2020-03-30 20:50 UTC
I am an online tutor, and using the amazing bbb for live classes for over 2 year. Everything looks great, util when I try to share a video to the class - only the screen or application window is shared, but no sound - this feature is available on Zoom or Skype, and I think bbb should have it as well, because I always believe bbb is one of the best in its category.

Your consideration will be highly appreciated as it is extremely useful for the tutors and kids.

Best regards,
James 
Wendu Education

**Comment by otdftr** [comment] 2020-04-06 07:45
Second that request: We too would love to share the PC audio along with application / screen sharing.

**Comment by debuglevel** [comment] 2020-04-20 19:37
Folks over at Jitsi implemented this. Works in Chrome, at least.

See also: https://stackoverflow.com/questions/19382444/is-it-possible-broadcast-audio-with-screensharing-with-webrtc

**Comment by rasos** [comment] 2020-06-23 09:49
At least chrome browsers support that feature

![Bildschirmteilung](https://user-images.githubusercontent.com/485723/85389169-5ca76080-b547-11ea-9948-d5513a38add6.png)

**Comment by prlanzarin** [comment] 2020-06-23 13:43
Duplicate of #8632

**Closed by prlanzarin** 2020-06-23 13:43 UTC
