### ISSUE TITLE
Share an External video player not sync Properly

### ISSUE THREAD

**Issue by premmohantyagi** [bigbluebutton/bigbluebutton#10020] opened 2020-07-09 17:29 UTC
We should use server time, but we are using here system time
that is the reason of the issue

**Comment by basisbit** [comment] 2020-07-09 20:06
Please read and follow the template instructions instead of ignoring them.
Duplicate of #9274

**Closed by basisbit** 2020-07-09 20:06 UTC

**Comment by premmohantyagi** [comment] 2020-07-11 13:52
Yes issue is fixed in 2.2.20
