### ISSUE TITLE
etherpad problem on 2.2.32

### ISSUE THREAD

**Issue by bilias** [bigbluebutton/bigbluebutton#11497] opened 2021-02-25 07:36 UTC
After upgrading to 2.2.32 etherpad stopped working.
Meeting starts but does not show "Shared notes"

etherpad process is at 100%
In syslog I have:

Feb 25 09:21:21 node[7955]: #033[32m[2021-02-25 09:21:21.500] [INFO] console - #033[39mAll relative paths will be interpreted relative to the identified Etherpad base dir: /usr/share/etherpad-lite
Feb 25 09:21:21 node[7955]: #033[36m[2021-02-25 09:21:21.509] [DEBUG] AbsolutePaths - #033[39mRelative path "settings.json" can be rewritten to "/usr/share/etherpad-lite/settings.json"
Feb 25 09:21:21 node[7955]: #033[36m[2021-02-25 09:21:21.511] [DEBUG] AbsolutePaths - #033[39mRelative path "credentials.json" can be rewritten to "/usr/share/etherpad-lite/credentials.json"
Feb 25 09:21:21 node[7955]: #033[32m[2021-02-25 09:21:21.537] [INFO] console - #033[39msettings loaded from: /usr/share/etherpad-lite/settings.json
Feb 25 09:21:21 node[7955]: #033[32m[2021-02-25 09:21:21.539] [INFO] console - #033[39mNo credentials file found in /usr/share/etherpad-lite/credentials.json. Ignoring.
Feb 25 09:21:21 node[7955]: #033[32m[2021-02-25 09:21:21.543] [INFO] console - #033[39mUsing skin "no-skin" in dir: /usr/share/etherpad-lite/src/static/skins/no-skin
Feb 25 09:21:21 node[7955]: #033[32m[2021-02-25 09:21:21.544] [INFO] console - #033[39mSession key loaded from: /usr/share/etherpad-lite/SESSIONKEY.txt
Feb 25 09:21:24 node[7955]: #033[32m[2021-02-25 09:21:24.676] [INFO] APIHandler - #033[39mApi key file read from: "/usr/share/etherpad-lite/APIKEY.txt"
Feb 25 09:21:25 node[7955]: #033[32m[2021-02-25 09:21:25.335] [INFO] console - #033[39mReport bugs at https://github.com/ether/etherpad-lite/issues
Feb 25 09:21:25 node[7955]: ENOENT: no such file or directory, lstat '/usr/share/etherpad-lite/.git'
Feb 25 09:21:25 node[7955]: ENOENT: no such file or directory, lstat '/usr/share/etherpad-lite/.git'

I cannot even systemctl stop the service
only kill -9

**Comment by crosscodr** [comment] 2021-02-25 11:37
I have the same problem here. `systemctl restart etherpad` takes approx. one minute.

**Comment by pedrobmarin** [comment] 2021-02-25 11:51
Could you raise the log level to DEBUG and restart it? Tou can find the configuration at https://github.com/bigbluebutton/etherpad-lite/blob/bf52feb1a5742e76585447a0dd117d5de09e9162/settings.json.template#L467-L472

Also, if you think would help, there is a way to isolate the logs from syslog by running it in the console:
- stop (or kill) the etherpad service
- `sudo /usr/share/etherpad-lite/bin/run.sh --root`

**Comment by simonschweizer** [comment] 2021-02-25 11:58
@pedrobmarin I had the same issue. After I tried your both commands I was able to start etherpad (in dev mode) and after that also using the systemd service.

**Comment by crosscodr** [comment] 2021-02-25 12:11
When stopping ehterpad (`systemctl stop etherpad`), I get this error-messages:

```
Feb 25 12:55:17 bbb03. systemd[1]: Stopping Etherpad Server...
Feb 25 12:56:47 bbb03 systemd[1]: etherpad.service: State 'stop-sigterm' timed out. Killing.
Feb 25 12:56:47 bbb03 systemd[1]: etherpad.service: Main process exited, code=killed, status=9/KILL
Feb 25 12:56:47 bbb03 systemd[1]: Stopped Etherpad Server.
Feb 25 12:56:47 bbb03 systemd[1]: etherpad.service: Unit entered failed state.
Feb 25 12:56:47 bbb03 systemd[1]: etherpad.service: Failed with result 'signal'.
```
Starting with  `/usr/share/etherpad-lite/bin/run.sh --root` leads to a massive amount of log messages.
Multiple times
`[INFO] ueberDB - garbage collected 500 values`
And in between a debug-message for each value...

I see some old shared notes contents of old pads?
Shouldn't they be cleaned when rebooting?

I don't what other debug information could help you.

**Comment by pedrobmarin** [comment] 2021-02-25 12:20
We did replace the old pad cleaner with a new one but I'm not sure if it was included in 2.2.32. Could you try to grep `ep_pad_ttl` in your logs?

**Comment by pedrobmarin** [comment] 2021-02-25 12:33
https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.32, at the `Packaging` section. @antobinary could you also raise this change to the `Privacy` section?

I'll bet what's going on is that a load of old pads are being removed from Redis on start. So let it run for a couple of minutes.

**Comment by timm2k** [comment] 2021-02-25 12:58
Two things bugged a colleague of mine:

1st: `node_modules` where missing:
```
# become root
systemctl stop etherpad
su - etherpad -s /bin/bash
export NODE_ENV=production
/usr/bin/node node_modules/ep_etherpad-lite/node/server.js
```
If you get `log4js` not found, run `npm install`.

2nd:
Some old Pads seem to break Etherpad. Remove them by cleaning Redis DB:
`redis-cli FLUSHALL && bbb-conf --restart`

Kind regards
@Davka & Timm

**Comment by pedrobmarin** [comment] 2021-02-25 13:08
I would be more careful when running `redis-cli FLUSHALL` because if there is any recordings to be processed it will be lost too.

**Comment by timm2k** [comment] 2021-02-25 13:44
> I would be more careful when running `redis-cli FLUSHALL` because if there is any recording to be processed it will be lost too.

Good point. I've modified the command to expired all pad entries.

**Comment by PhMemmel** [comment] 2021-02-25 13:47
> I'll bet what's going on is that a load of old pads are being removed from Redis on start. So let it run for a couple of minutes.

Can probably confirm: Started the node in production mode. After over an hour running at 100% CPU it is still generating new "garbage collected" messages from time to time. So the cleaning up process apparently just takes a really long time.

**Comment by pedrobmarin** [comment] 2021-02-25 13:59
@PhMemmel one hour seem too much. It would be nice to get a glimpse on those logs.

As @timm2k pointed out, this might be related with some really old pads stored in Redis. For those cases I would recommend his (and @Davka) updated redis-cli command

**Comment by PhMemmel** [comment] 2021-02-25 14:11
I'm running this command:
``
> systemctl stop etherpad
> su - etherpad -s /bin/bash
> export NODE_ENV=production
> /usr/bin/node node_modules/ep_etherpad-lite/node/server.js
> ``

 It starts up, everything looks nice, then the garbage collection starts. There are plenty of lines like
`[2021-02-25 14:34:01.950] [INFO] console - [ep_pad_ttl] 61717576 deleted`

They are being followed by plenty of lines like
`[2021-02-25 14:34:03.261] [INFO] ueberDB - garbage collected 1 values`

I think I will stop the process now and go the mentioned way of cleaning up redis manually.

I've had a look at the redis keys: It shows about 200,000 redis keys. The process is now running for 90 minutes.

Let me know, if I can provide you some more information and how.

**Comment by pedrobmarin** [comment] 2021-02-25 14:29
200,000 does look like a big number but I still would not expect this process take an infinite amount of time to finish. So big chances there is something looping in there.

@PhMemmel when you say there is plenty of lines like
```
[INFO] console - [ep_pad_ttl] 61717576 deleted
```
Do you mean the same identifier (`61717576`) too?

**Comment by bilias** [comment] 2021-02-25 14:39
I've cleaned the redis db from old pad keys using

`redis-cli --scan --pattern pad:* | xargs redis-cli del
`

which is much faster than the proposed method above.
Problem solved.

Can removing old pads from redis cause any problem? Maybe to old recordings or something else?

**Comment by PhMemmel** [comment] 2021-02-25 14:46
> ```
> [INFO] console - [ep_pad_ttl] 61717576 deleted
> ```
> 
> Do you mean the same identifier (`61717576`) too?

No, different identifiers. It took a long time, after about 45 minutes of not a single new message suddenly some new appeared. This led me to the assumption the cleaning up was still going. I now killed the process after 110 minutes and executed
```redis-cli keys pad:* | while read LINE; do echo $LINE; redis-cli EXPIRE $LINE 1; done``` which also took 13 minutes to execute. So this redis cache just accumulated a lot of stuff over the time I feel like.

Everything is running fine now.

**Comment by pedrobmarin** [comment] 2021-02-25 14:51
@bilias it wont cause any problems regarding the old recordings because those pads are archived someplace else. 

@PhMemmel I'll try to improve the plugin performance or even cap the number of pads it can delete per iteration to avoid those scenarios.

BigBlueButton's Etherpad had, since we made it's first integration to the project, a plugin that was responsible for removing those idle pad data from redis. At some point (probably when we made the update with Etherpad v1.8.0) it started to miss some data at Redis. I fixed that a couple of weeks ago and it was packed along with BBB v2.2.32.

Thanks everyone for the feedback.

**Comment by mk-hs** [comment] 2021-02-25 15:41
```
[DEBUG] ueberDB - #033[39mDELETE - pad:2ae8c83b:revs:691 - from database
[DEBUG] ueberDB - #033[39mSET    - pad:2ae8c83b:revs:691 - null - to buffer
[DEBUG] ueberDB - #033[39mDELETE - pad:2ae8c83b:revs:692 - from database
[DEBUG] ueberDB - #033[39mSET    - pad:2ae8c83b:revs:692 - null - to buffer
[DEBUG] ueberDB - #033[39mDELETE - pad:2ae8c83b:revs:693 - from database
[DEBUG] ueberDB - #033[39mSET    - pad:2ae8c83b:revs:693 - null - to buffer
[DEBUG] ueberDB - #033[39mDELETE - pad:2ae8c83b:revs:694 - from database
[DEBUG] ueberDB - #033[39mSET    - pad:2ae8c83b:revs:694 - null - to buffer
[DEBUG] ueberDB - #033[39mDELETE - pad:2ae8c83b:revs:695 - from database
[DEBUG] ueberDB - #033[39mSET    - pad:2ae8c83b:revs:695 - null - to buffer
```

When set to debug, the log spews out these messages ad nauseam.

**Comment by Davka** [comment] 2021-02-25 20:06
To make it faster (recordings were saved) I used the following command before I run the update

```redis-cli keys * pad * | xargs redis-cli DEL```

No guarantee for data loss :)

**Comment by pedrobmarin** [comment] 2021-02-25 20:20
To give some extra content to this. The keys removed by the plugin on a regular schedule are:
```
pad:*
pad:*:revs:*
globalAuthor:*
pad2readonly:*
readonly2pad:*
```
And since it uses the Etherpad API/DB interface it is able fetch all of those. IF you are running a server that does not have any active users, no recordings waiting in line and willing to flush an initial humongous amount of Redis data using redis-cli you might want to flush those down too.

**Comment by ffdixon** [comment] 2021-02-26 15:04
Fixed in 2.2.33.  See https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.33

**Comment by kinimodmeyer** [comment] 2021-02-27 16:59
@ffdixon i upgraded to 2.2.33 but i still have a error when i open etherpad:

> An error occurred
The error was reported with the following id: 'XobF4uSNln4JA02DnjRv'
Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: XobF4uSNln4JA02DnjRv
URL: https://xyze/pad/p/15b1fc0f?showLineNumbers=false&showChat=f

what do i have to do to fix that exactly?

**Comment by pedrobmarin** [comment] 2021-02-27 17:22
@kinimodmeyer just stop your etherpad service, run:
```
redis-cli keys pad:* | xargs redis-cli del
redis-cli keys sessionstorage:* | xargs redis-cli del
redis-cli keys globalAuthor:* | xargs redis-cli del
redis-cli keys token2author:* | xargs redis-cli del
```
and restart it

**Comment by EmmyGraugans** [comment] 2021-02-27 18:10
I have the impression, the "fix" in bbb 2.2.33 to address this is not enough. On at least one server I had an unusable etherpad after an upgrade from 2.2.31 to 2.2.31, the error-message was something like this

```
An error occurred
The error was reported with the following id: 'VdcgkCQmDNWgVGZgqCqC'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: VdcgkCQmDNWgVGZgqCqC
URL: https://fqdn.com/pad/p/xxxxxxxx?showLineNumbers=false&showChat=false&noColors=true&showControls=true&rtl=false&userName=Me&userColor=%231565c0&lang=de-de&sessionToken=XXXXXXXXXXXXXXXX
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36
Uncaught TypeError: Cannot read property 'setStateIdle' of null in https://fqdn.com/pad/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 3'
```

I managed to fix this with 
`redis-cli --scan "*" | egrep "^(sessionstorage|token2author|ueberDB|globalAuthor|pad|readonly2pad|pad2readonly):" | xargs redis-cli del`
followed by
`bbb-conf --restart`

I am not sure if this was due to the "ueberDB" still containing references to already-deleted other keys. At least syslog showed something regarding ueberDB in context with the "ErrorId" named above.

**Comment by lkiesow** [comment] 2021-03-02 09:12
Unfortunately that seems to be the case. The error you describe goes along with the following error in the etherpad server logs:

```
Mar 02 10:07:06 v220200330084111087 node[13475]: [2021-03-02 10:07:06.114] [INFO] ueberDB - Flushed 1 values
Mar 02 10:07:06 v220200330084111087 node[13475]: [2021-03-02 10:07:06.230] [INFO] ueberDB - Flushed 1 values
Mar 02 10:07:06 v220200330084111087 node[13475]: [2021-03-02 10:07:06.330] [INFO] ueberDB - Flushed 1 values
Mar 02 10:07:06 v220200330084111087 node[13475]: [2021-03-02 10:07:06.530] [INFO] ueberDB - Flushed 1 values
Mar 02 10:07:06 v220200330084111087 node[13475]: [2021-03-02 10:07:06.574] [ERROR] console - TypeError: Cannot set property 'timestamp' of null
Mar 02 10:07:06 v220200330084111087 node[13475]:     at /usr/share/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:326:41
Mar 02 10:07:06 v220200330084111087 node[13475]:     at fn (/usr/share/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:525:34)
Mar 02 10:07:06 v220200330084111087 node[13475]:     at /usr/share/etherpad-lite/src/node_modules/ueberdb2/node_modules/async/lib/async.js:449:34
Mar 02 10:07:06 v220200330084111087 node[13475]:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
Mar 02 10:07:06 v220200330084111087 node[13475]:     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
Mar 02 10:07:06 v220200330084111087 node[13475]: [2021-03-02 10:07:06.574] [INFO] console - graceful shutdown...
Mar 02 10:07:06 v220200330084111087 node[13475]: [2021-03-02 10:07:06.630] [INFO] console - db sucessfully closed.
Mar 02 10:07:06 v220200330084111087 systemd[1]: etherpad.service: Service hold-off time over, scheduling restart.
Mar 02 10:07:06 v220200330084111087 systemd[1]: Stopped Etherpad Server.
Mar 02 10:07:06 v220200330084111087 systemd[1]: Started Etherpad Server.
Mar 02 10:07:06 v220200330084111087 node[13501]: [2021-03-02 10:07:06.892] [DEBUG] console - Running on Node v8.17.0 (minimum required Node version: 8.9.0)
```

- It seems to disappear if a user completely wipes all cookies related to Etherpad but unfortunately reappears on a later date
- Since the error causes the server to crash and restart, other users will experiencing Etherpad to constantly reconnect , making it barely usable for them as well

**Comment by ffdixon** [comment] 2021-03-02 12:06
@lkiesow Can you confirm if the fix that @EmmyGraugans suggested works.

**Comment by pedrobmarin** [comment] 2021-03-02 12:42
Updated with ueberDB keys as well

```
redis-cli keys pad:* | xargs redis-cli del
redis-cli keys sessionstorage:* | xargs redis-cli del
redis-cli keys globalAuthor:* | xargs redis-cli del
redis-cli keys token2author:* | xargs redis-cli del
redis-cli keys pad2readonly:* | xargs redis-cli del
redis-cli keys readonly2pad:* | xargs redis-cli del
redis-cli keys ueberDB:* | xargs redis-cli del
```

**Comment by ichdasich** [comment] 2021-03-04 14:28
FYI, just got hit on this for 2.2.34 (update to 2.2.35 scheduled for tonight)

**Comment by ffdixon** [comment] 2021-03-04 16:02
Did you have a problem with the redis keys not cleared correctly on 2.2.34?

**Comment by ichdasich** [comment] 2021-03-04 16:23
I had (some) problem going from .31 to .32 (increased startup time) and cleaned keys manually as documented here; Upgrade to .34 went smooth, but today I experienced the issue reported by @EmmyGraugans and @lkiesow . Will do more debugging around ~1am UTC.

**Comment by pielonet** [comment] 2021-03-04 17:06
Upgraded to 2.2.35 and still a problem in shared notes :

```
An error occurred
The error was reported with the following id: 'ksJqvhMsKW2jKKHS7pRO'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: ksJqvhMsKW2jKKHS7pRO
URL: https://bbb.arawa.fr/pad/p/bb408d7461c84b0c97633f998bae387cb619c50f?userName=Thierry%20Kauffmann&lang=fr&rtl=false&sessionToken=0zcalmmi2l4ncg81
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
TypeError: pad.collabClient is null in https://bbb.arawa.fr/pad/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 3'
```

**Comment by ichdasich** [comment] 2021-03-04 17:08
Did you do the manual redis clean process from @pedrobmarin 's last comment?

**Comment by pielonet** [comment] 2021-03-04 17:13
I processed these redis clean commands and shared notes are back in my single session. I must now test with other users.

**Comment by pielonet** [comment] 2021-03-04 17:20
It also works in multi-user environment.

**Comment by ichdasich** [comment] 2021-03-05 10:58
Ok, this error persists (the one posted by @EmmyGraugans / @lkiesow ). 

Yesterday I upgraded to 2.2.35. Stopped 2.2.34, did the upgrade, cleared redis as in @pedrobmarin's latest comment, started 2.2.35.

Today, the shared notes again failed (actually for my own user). I would argue that this is _not_ related to a cache issue alone. Instead (conjecture, (tm)) i'd say that cookies from users spill something back into the cache, and the error should be handled in the affected code path. I can not instruct all users to clear their cookies.

**Comment by ichdasich** [comment] 2021-03-05 11:19
Ok, i did some further debugging. I could confirm that the issue is related to the `token' cookie. If this cookie is deleted _before_ a session is joined, etherpad works as intended. I would also assume that _changing_ the content of that cookie (if already set) will enable you to reproduce this bug (but i am too lazy to figure out how to test this right now.)

The the contents (partially redacted) of that token from when i experienced the bug:

```
Name: token
Content: <REDACTED>
Domain: <REDACTED>
Path: /
Send for: Secure connections only
Accessible to script: Yes
Created: Friday, February 5, 2021 at 10:02:06 AM
Expires: Tuesday, April 6, 2021 at 11:02:06 AM
```

The important part is the created/expired timestamp here. This cookie seems to have a livetime of ~2 Months. If, as introduced with the 2.2.33 upgrade, keys get purged in redis, i would _assume_ that the presence of such a cookie from _before_ the purge leads to the observed error. This has not happened before 2.2.32/2.2.33, as redis was not flushed then.

Given that this means that there are users with such cookies potentially stuck in their browsers for up to 2 months (from the last upgrade) and that this will reoccur with every update that purges redis, this needs a fix in the code-path. Furthermore, i'd suggest to set the `Expires` field to `When the browsing session ends`, as it is done for other room-cookies as well.

Related:
The same holds for the `perfs` cookie for etherpad, which in my case has an expirery date in the year 3000: `Expires: Wednesday, March 5, 3000 at 11:59:44 AM`.

**Comment by zeyadsaleh** [comment] 2021-03-10 12:05
Hello everyone,

I've been working on this issue for the last day and I found that the problem is in the Redis cashing, so the solution of this issue is:

Go to your server and run 
```sh
redis-cli flushall 
```


Hope it solves the problem with you too.

**Comment by pedrobmarin** [comment] 2021-03-10 12:11
> I would be more careful when running `redis-cli FLUSHALL` because if there is any recording to be processed it will be lost too.

https://github.com/bigbluebutton/bigbluebutton/issues/11497#issuecomment-785882526

**Comment by zeyadsaleh** [comment] 2021-03-10 12:20
@pedrobmarin for me I'm still on the development stage not live, so I'm good with that. But good to clarify that for anyone who is going on production.

**Comment by pedrobmarin** [comment] 2021-03-10 12:41
@zeyadsaleh there is a long discussion on all problems that are surging after some updates we had to do for shared notes and closed captions (Etherpad related). The community feedback has been great and, thanks to that, we have a solid idea of what the problem is. We are working on tuning things up at packaging.

**Comment by ichdasich** [comment] 2021-03-23 11:41
Are there any news on this? This started to reoccur again, and it is _heavily_ impacting users' work flows.

**Comment by pedrobmarin** [comment] 2021-03-23 11:56
Seems to be stable on the latest 2.2-dev packages so I would say it will be fixed in v2.2.36

**Comment by Davka** [comment] 2021-03-23 17:22
I think you can close the ticket. I have applied some of the changes from 2.2-dev to our systems and it does not cause any problems.

**Comment by relecand** [comment] 2021-03-29 22:28
> Go to your server and run
> 
> ```shell
> redis-cli flushall 
> ```

Same problem on various servers. This helped. Thanks!

**Comment by hex-m** [comment] 2021-03-31 12:11
I had the error on `2.2.35`:
```
An error occurred
The error was reported with the following id: 'JRG5RnMQLXrdN7Rk9jaO'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: JRG5RnMQLXrdN7Rk9jaO
...
```

Didn't try any workaround but ran `bbb-install.sh` with `-v xenial-220-dev22a` today to test the upgrade to `2.2.36`. Happy to report that the problem disappeared.

**Comment by pedrobmarin** [comment] 2021-04-01 19:39
Released with https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.36

**Closed by pedrobmarin** 2021-04-01 19:39 UTC

**Comment by relecand** [comment] 2021-04-28 19:52
Updated from 2.2.31 to 2.2.36. Problem remains. 

`redis-cli flushall ` solved it.

**Comment by sbdlt** [comment] 2021-05-03 13:20
Same here. 

Update from 2.2.32 to 2.2.36 did not fixed it.

**Comment by Intelartifice** [comment] 2021-05-25 11:37
You can try to change in /usr/share/etherpad-lite/settings.json, the cookie setting (near line 317) to false 
"forceSameSiteNone": false,
and restart etherpad service
However the speech to text (dictation) may no work
