### ISSUE TITLE
Clicking on "Try it now" gives white browser window

### ISSUE THREAD

**Issue by GabZach** [bigbluebutton/bigbluebutton#9706] opened 2020-05-28 20:38 UTC
I have just clicked on the "Try it now!" button (the green button) on the web page https://bigbluebutton.org , and all I get is an empty, white browser window.
The URL says https://demo.bigbluebutton.org , so that seems correct, but nothing else can be seen.

In the web inspector, I can see the error message:
"Failed to load resource: the server responded with a status of 503 (Service Unavailable: Back-end server is at capacity)".
I don't know if this is the true cause, but
In any case, there should be at least a human-readable error message.

Platform: macOS 10.15.4 , Safari (latest version).

**Comment by matiasilva** [comment] 2020-05-28 23:06
I believe the error message is pretty self-explanatory. Have you tried any other browser?

**Comment by GabZach** [comment] 2020-05-29 17:53
Maybe I didn't make myself clear. My issue was a suggestion to deal with such a situation in a more user-friendly manner.

**Comment by basisbit** [comment] 2020-05-31 01:19
@GabZach so, this is not a bug report, but instead a feature request for nice looking error pages? Than can easily be done by adjusting the [nginx configuration](https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-to-use-custom-error-pages-on-ubuntu-14-04).

@GabZach could you maybe help by starting work on this and creating a pull request containing these custom error pages?

**Comment by matiasilva** [comment] 2020-06-14 23:38
Seems like no progress has been made in the meantime. Closed due to inactivity.

**Comment by basisbit** [comment] 2020-06-14 23:41
The error messages of BBB are still not user friendly at all....

**Comment by matiasilva** [comment] 2020-06-14 23:44
I'm not quite sure what the error is here. I can click the "try now" button and it will redirect me perfectly to the demo site. In any case, this would be changing the demo site, which is managed directly by Blindside. Perhaps, I'm misunderstanding :)

**Comment by basisbit** [comment] 2020-06-15 08:44
@matiasilva 
> In any case, there should be at least a human-readable error message.

>My issue was a suggestion to deal with such a situation in a more user-friendly manner.

**Comment by matiasilva** [comment] 2020-06-15 09:45
Unfortunately, I can't emulate this error so I don't know how this can be fixed. Seems like it just takes modifying some string in the meteor app.

**Comment by GabZach** [comment] 2020-06-15 09:49
Maybe someone can try reproducing it using Safari.

**Comment by matiasilva** [comment] 2020-06-15 09:51
Sure, I'll reopen it then but will watch out for inactivity, as that's the reason why I closed it in the first place.

**Comment by ffdixon** [comment] 2020-06-15 10:19
It works for me in Safari.  This issue is a bit old, and there were times as we updated https://demo.bigbluebutton.org/ we encountered errors with Greenlight.  

Closing this issue.  If we encounter any new errors, we can open a new issue.

**Closed by ffdixon** 2020-06-15 10:19 UTC
