### ISSUE TITLE
unable to delete default presentation

### ISSUE THREAD

**Issue by afsharsafavi** [bigbluebutton/bigbluebutton#12237] opened 2021-05-02 12:14 UTC
Hi
Thanks for releasing version 2.3.
Sometimes presenters want to delete default/current presentation for expanding visible area for webcams.
In version 2.2, presenter could delete all presentation included default presentation from presentations manager window. Afterwards, webcams show larger.
But in version 2.3, we can't delete default presentation.
Hence in BigBlueButton changing layout by presentation doesn't any affect on attendant view, (in spite of similar program like Adobe Connect), the best way for maximizing webcams (when it needed), is deleting or disabling default presentation.
I think disabling is better than deleting. Sometimes presenter wants to maximize webcams for a limited period and then he/she needs whiteboard or last slides. So when he/she delete all presentations, he/she should upload them again. or upload an empty pdf for using as a whiteboard.
But if you provide a method to disable all presentation or changing the layout like Adobe Connect, it seems presenters will have less task and save the time.

**Comment by bwurst** [comment] 2021-05-03 15:34
Duplicate of #12103

**Comment by prlanzarin** [comment] 2021-05-20 23:39
Yeah, duplicate of #12103 and https://github.com/bigbluebutton/bigbluebutton/issues/7987

**Closed by prlanzarin** 2021-05-20 23:39 UTC
Labels: module: client
