### ISSUE TITLE
Make drawing over presentations downloadable

### ISSUE THREAD

**Issue by ajithgopi** [bigbluebutton/bigbluebutton#12125] opened 2021-04-23 06:02 UTC
**Is your feature request related to a problem? Please describe.**
Not really. But I hope the students as well as the teachers can benefit more from this feature.

**Describe the solution you'd like**
Add an additional download button which will allow the user to download the modified version of current presentation.

Technically,
1. Loop through each `<svg>` tag in slides.
2. Add `xmlns:xlink="http://www.w3.org/1999/xlink"` property to `<svg>` tag
3. Probably use something like [svg-to-pdfkit](https://www.npmjs.com/package/svg-to-pdfkit) to combine the images and avail download on client side.

**Describe alternatives you've considered**
One alternative is to screenshot after the teacher has completed writing.

**Additional context**
Right now, when the presentation is made downloadable, the actual file is getting downloaded without the figures drawn on them. It would be great if both versions of the file can be downloaded.

**Comment by basisbit** [comment] 2021-04-26 09:28
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/4882

**Closed by basisbit** 2021-04-26 09:28 UTC
Labels: type: enhancement
