### ISSUE TITLE
Chrome taking a long time to connect to echo test

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7323] opened 2019-04-30 02:00 UTC
In testing Version 74.0.3729.108 (Official Build) (64-bit) on Mac OS X 10.14.4, I found that Crome was taking a long time (about 5 seconds) to connect to the echo test.  Clicking 'Yes' before hearing myself would result in a 1008 Transfer Failed message.

![long](https://user-images.githubusercontent.com/290351/56937269-d8d02080-6ac9-11e9-8cc1-987dce4261a7.gif)

**Comment by capilkey** [comment] 2019-04-30 16:19
Duplicate of #7317

**Closed by capilkey** 2019-04-30 16:19 UTC
