### ISSUE TITLE
Whiteboard has unwriteable area

### ISSUE THREAD

**Issue by oxydon** [bigbluebutton/bigbluebutton#9383] opened 2020-05-01 17:48 UTC
Somewhere in the middle of every slide there is an overlay which prevents drawing lines or making annotations in that area. It can be drawn across though, if the startingpoint is located outside of this area.

**Reproduction**
1. Use whiteboard with any slide.
2. Move the cursor from top to bottom accross the whiteboard in pen-mode.
3. You will notice, that the red laserpointer dot disappears in the middle of the slide. In this area any click has no effect and no drawing can be started - not with shapes, not with the pen (blue dots). If the drawing is started outside of this area, drawing across it is possible (red lines).

**Expected behavior**
The whiteboard should not make a difference regarding startingpoints of annotations.

**Actual behavior**
It should have been possible to draw on the whiteboard no matter where.

**Screenshots**
![Bildschirmfoto 2020-05-01 um 19 36 54](https://user-images.githubusercontent.com/43959902/80827103-a462d900-8be3-11ea-8584-b954d51f95e1.png)

**BBB version (optional):**
BigBlueButton Server 2.2.8

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.4 sowie LinuxMint
 - Browser: Firefox
 - Version  75.0

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS13.4.1
 - Browser: Safari

**Comment by svergata** [comment] 2020-05-01 19:34
Problem was solved tonight with 2.2.9 see Issue #9348 for more Informations.

**Comment by basisbit** [comment] 2020-05-02 21:25
Duplicate of ##348

**Comment by basisbit** [comment] 2020-05-02 21:26
Duplicate of #9348

**Closed** 2020-05-27 13:06 UTC
Labels: HTML5 Client
