### ISSUE TITLE
Dowloading the presentation file with annotaion

### ISSUE THREAD

**Issue by dothanhhao** [bigbluebutton/bigbluebutton#12516] opened 2021-06-04 13:40 UTC
Hi all,
Currently, I want to dowload the presentation file with annotaion
Do we have any option configs or API to do this?
Thanks!

**Comment by hiroshisuga** [comment] 2021-06-07 03:25
Interesting suggestion, but I am afraid that there is no such option for now. One possibility is to capture the screen in playback. 

If you are skilled enough (which I am not), all the drawing data is stored in /var/bigbluebutton/published/presentation/{meetingID}/shapes.svg.  You may want to write a script to merge them to the slides using Imagemagick.

**Comment by danielpetri1** [comment] 2021-06-07 11:06
Hi @dothanhhao,

You can try using [this script](https://pastebin.com/9gyvZ5Pd) I've written to get each slide as an annotated .png image which you can then later merge into a .pdf. 

You will have to install librsvg and create a folder named 'slides' in the directory @hiroshisuga mentioned before running the script. 

If you don't have access to the server, you can download the files locally using [this script](https://github.com/danielpetri1/bbb-recording-exporter/blob/client-side/download_client.rb) before running the exporter.

Let me know if you have any questions.

**Comment by danielpetri1** [comment] 2021-06-07 11:29
Duplicate of #4882

**Closed** 2021-06-07 11:55 UTC
Labels: type: enhancement
