### ISSUE TITLE
Share audio while screen sharing

### ISSUE THREAD

**Issue by harriholappa** [bigbluebutton/bigbluebutton#11242] opened 2021-01-27 12:22 UTC
There are use cases when it is much easier to play audio with the Share your screen functionality rather than uploading an external file. This feature is missing in 2.4.-beta, although I have heard it was present in an earlier version. It would be great if we could get this functionality back.

**Comment by basisbit** [comment] 2021-01-27 22:13
duplicate of #8632

**Closed by basisbit** 2021-01-27 22:13 UTC
