### ISSUE TITLE
got 2200 error in performance test

### ISSUE THREAD

**Issue by mahmoodbagheri** [bigbluebutton/bigbluebutton#9028] opened 2020-04-09 19:55 UTC
Hi,
I got 2200 media server failed to process request error when we start 8 or 9 webcams. we started meeting with 30 people and turn on webcam one by one. After 8 or 9  webcams persons got error 2200 and nobody can share webcam. Some persons got error 1020 error too.
I think that the video needs some tune config. Have you any suggestions for me.

**Comment by mleu77** [comment] 2020-04-18 13:18
Hi, 
ich have exactly the same problems here. bbb 2.2.5
Absolut low CPU and RAM load.
Can you give me som advice, where to begin searching?

**Comment by beatwiz** [comment] 2020-04-18 13:34
I can confirm I have experienced the same behaviour in some of our servers. But its totally random. We had meetings with 20 webcams and no issues and some meetings that crashed after 8-9 users. Both meetings with max 25 users and a total of max 100 users on the server (8c / 16t Xeon's 32GB RAM 1Gbps). Thanks!

**Comment by mahmoodbagheri** [comment] 2020-04-21 13:06
Hi,
Guys I config TRUN Server for bigbluebutton and after that, I got the good performance and my users didn't get 1020 or 2200 error. After install and config TURN Server I can connect 30 video in a meeting without error too.

**Comment by mleu77** [comment] 2020-04-24 17:13
That's really interesting - for me problems are solved, when I don't configure a turn server.
I tried it in different installations, vserver and dedicated hardware.
My turn server has just poor performance on Oracle Free tier, but it fullfills requirements in https://docs.bigbluebutton.org/2.2/setup-turn-server.html#required-hardware

Is it possible, that more traffic than necesarry (maybe all) is routed through turn server?
This could be the reason, why mediaserver isn't reachable after just a few webcams turned on?

Regards

**Comment by matiasilva** [comment] 2020-06-18 19:47
Hi guys. I'm going to close this issue but if you have any further issues please feel free to follow up at https://groups.google.com/forum/#!forum/bigbluebutton-setup where your requests can be better handled.

**Closed by matiasilva** 2020-06-18 19:47 UTC
