### ISSUE TITLE
Webcam Video "Video preview" when autostart=YES

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1994] opened 2015-08-12 07:55 UTC
Originally reported on Google Code with ID 1240

```
Reported by a user in the mailing list:
https://groups.google.com/d/msg/bigbluebutton-dev/-/ntGZaZKPcLoJ

I have enabled autostart for the videoconf module in the config.xml. When the user
joins the conference, the webcam window says "Video Preview". Is this a timing issue?
When a second user joins the conference, the title of his webcam video window is: "Share
your webcam".
```

Reported by `fcecagno` on 2012-06-07 19:38:40

**Comment by GhaziTriki** [comment] 2017-05-23 15:36
Cannot be reproduced in 1.1.0. It seems like it has been fixed since it has been reported.

**Comment by ffdixon** [comment] 2019-04-07 00:21
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).

**Closed by ffdixon** 2019-04-07 00:21 UTC
Labels: Defect, Normal Priority, Usability, Video
