### ISSUE TITLE
When sharing one's own screen, it should not recursively be iterated

### ISSUE THREAD

**Issue by melolontha-melolontha** [bigbluebutton/bigbluebutton#10815] opened 2020-11-12 14:45 UTC
**Is your feature request related to a problem? Please describe.**
When sharing one's own screen or the BBB window, it appears recursively nested into itself. This is very distracting to the participants. Showing one's own screen (or only the BBB screen) is very helpful, especially when one wants to demonstrate computer issues or when introducing someone new to BBB.

**Describe the solution you'd like**

When BBB is set to transmit one's own full screen or only the BBB screen, the content on the BBB screen should be shown only on the first level, i.e. once. The BBB screen that currently appears on the BBB screen should be replaced by something else, e.g. a rectangle of its size with a blue inscription BBB in order to prevent the first and all subsequent recursions.

**Describe alternatives you've considered**
Crossing out the recursed BBB screen or transmitting just a rectangle with grey.

**Additional context**

**Comment by lonesomewalker** [comment] 2020-11-13 01:40
Consider as impossible.
If your share your screen, you share what you see at the moment.

**Comment by melolontha-melolontha** [comment] 2020-11-13 07:51
I think, you are wrong: The computer which shares its screen, knows where the BBB window is in its screen. So it also knows where the BBB-window on the shared screen will be displayed. Then it would only have to blank or replace that portion with the suggested uniformly painted rectangle displaying "BBB" once when it is reading its own screen content. That is the part to be shared and this modified screen content has to be uploaded.

Therefore I think it's possible. However, the exact position of the BBB window nested for the second time depends on where and in what size the BBB window takes on your own screen. The vanishing point of all nested own windows depends largely on the size and position of the primary BBB window on your own screen and how the split BBB window is displayed within BBB. To get an idea of the situation, try a test session in which you display your own BBB screen, when it does not take up the whole screen. Then resize the BBB window and move it around on your screen and observe what happens. All the nested windows' corners are on lines meeting in the vanishing point, but one only has to compute the first repetition and replace it by the placeholder.

To see how it should look like, take a screenshot and fill the second nested BBB window with a uniform pattern, e.g. grey throughout with a thick "BBB" on it. Then you can imagine that the situation becomes much less confusing for someone to whom you are explaining how BBB works, especially because all the nested cursor positions will simultaneously be suppressed for the other viewers.

**Comment by prlanzarin** [comment] 2020-11-13 11:22
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/7183.

**Closed by prlanzarin** 2020-11-13 11:22 UTC
Labels: Enhancement
