### ISSUE TITLE
Playwright tests stop on first issue encountered

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#13945] opened 2021-12-17 18:17 UTC
I followed the instructions from https://github.com/bigbluebutton/bigbluebutton/blob/v2.4.x-release/bigbluebutton-tests/playwright/README.md

I tried to run all the suites and every time there's an issue encountered, the tests stop, I check what's going on, add .skip() for that particular test so I can test the rest, and need to re-run the command, going through all 150 tests

Example
<details>
  1) [Chromium] › virtualizedlist/virtualizedlist.spec.js:5:3 › Virtualize list › Virtualized Users List 

    page.waitForSelector: Timeout 10000ms exceeded.
    =========================== logs ===========================
    waiting for selector "div[aria-label="Join audio modal"]" to be visible
    ============================================================

       6 |     test.setTimeout(0);
       7 |     const virtualizeList = new VirtualizeList(browser, page);
    >  8 |     await virtualizeList.init();
         |     ^
       9 |     await virtualizeList.test();
      10 |   });
      11 | });

        at Page.waitForSelector (/home/bigbluebutton/src/bigbluebutton-tests/playwright/core/page.js:94:21)
        at Page.closeAudioModal (/home/bigbluebutton/src/bigbluebutton-tests/playwright/core/page.js:89:16)
        at Page.init (/home/bigbluebutton/src/bigbluebutton-tests/playwright/core/page.js:45:43)
        at VirtualizeList.init (/home/bigbluebutton/src/bigbluebutton-tests/playwright/virtualizedlist/virtualize.js:21:7)
        at /home/bigbluebutton/src/bigbluebutton-tests/playwright/virtualizedlist/virtualizedlist.spec.js:8:5
        at WorkerRunner._runTestWithBeforeHooks (/home/bigbluebutton/src/bigbluebutton-tests/playwright/node_modules/@playwright/test/lib/workerRunner.js:478:7)

--- Test output ------------------------------------------------------------------------------------

Viewer-1 joined
Viewer-2 joined
Viewer-3 joined
Viewer-4 joined
Viewer-5 joined
Viewer-6 joined
Viewer-7 joined
Viewer-8 joined
Viewer-9 joined
Viewer-10 joined
Viewer-11 joined
Viewer-12 joined

----------------------------------------------------------------------------------------------------

  Slow test: [Chromium] › customparameters/customparameters.spec.js (3m)
  Slow test: [Chromium] › user/user.spec.js (2m)
  Slow test: [Chromium] › polling/polling.spec.js (1m)
  Slow test: [Chromium] › presentation/presentation.spec.js (1m)
  Slow test: [Chromium] › stress/stress.spec.js (1m)

  1 failed
    [Chromium] › virtualizedlist/virtualizedlist.spec.js:5:3 › Virtualize list › Virtualized Users List 
  69 skipped
  80 passed (4m)
bigbluebutton@anton24d:~/src/bigbluebutton-tests/playwright$ 
</details>

Now I need to re-run to cover the remaining 69 cases. But I have already forced skipping of a few specs and I've had to re-run 10 times. So I've essentially been re-running this all morning and still don't know the final number of passing vs failing cases.
Please add [default?] option to continue running Playwright tests even if one of them has failed.

**Comment by MaximKhlobystov** [comment] 2022-03-18 16:36
This seemed to be an environment-specific issue. We couldn't reproduce it anywhere else. Let's close this while keeping in mind that we need to run tests in various environments to spot potential issues.

**Closed by MaximKhlobystov** 2022-03-18 16:36 UTC
Labels: type: test
