### ISSUE TITLE
Update the z-index of the presenters preview window so that the window is above the whiteboard controls

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#4911] opened 2018-01-04 18:55 UTC
Currently, the presenter's preview window modal appears above the presentation module, but, under the whiteboard controls. Refer to the inbox below. 

<img width="738" alt="screen shot 2017-07-25 at 11 47 46 am" src="https://user-images.githubusercontent.com/1273169/34579405-e4b2d8a4-f156-11e7-95b7-b0d1b6028009.png">

**Comment by GhaziTriki** [comment] 2018-01-15 13:26
It is no more tha case in the current version. It looks like the screenshot below:

![image](https://user-images.githubusercontent.com/4991088/34944476-08a32b54-fa00-11e7-8455-1963e7f5b7a1.png)

**Comment by GhaziTriki** [comment] 2018-06-05 11:59
@tylercopeland Can you still reproduce it?

**Comment by tylercopeland** [comment] 2018-06-05 13:09
@GhaziTriki I'm still able to reproduce this issue. I'm using Chrome Version 66.0.3359.181 (Official Build) (64-bit). 


<img width="1552" alt="screen shot 2018-06-05 at 9 06 51 am" src="https://user-images.githubusercontent.com/1273169/40977878-26af4a1a-68a0-11e8-9eeb-b661fc0906cb.png">

**Comment by ffdixon** [comment] 2019-04-07 03:38
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).

**Closed by ffdixon** 2019-04-07 03:38 UTC
