### ISSUE TITLE
Firefox 77 many requests for access to devices 

### ISSUE THREAD

**Issue by rrolf** [bigbluebutton/bigbluebutton#9823] opened 2020-06-12 15:50 UTC
**Describe the bug**
With Firefox 77 I am asked 1-2 times for the access to the microphone and up to 4 times to allow the access the webcam, which is quite annoying. I am aware that firefox changed the behaviour, but maybe BBB can improve the situation a bit.

**To Reproduce**
1. Use Firefox 77.01
2. Open a BBB meeting. Sometimes I was asked immediately to allow to access the microphone (I could not find out under which exact conditions)
2. Select that you want to use the microphone you are asked a second time (okay this is expected)
3. Activate the webcam.
4. You are asked 2 times to access the webcam. 
5. change the camera, you will be asked again. 
6. select the camera and you will be asked again when you return to the main screen.

**Expected behavior**
Like in the past I would hope that it is enough to give the permission once for a device.

**Actual behavior**
I have to give the permission frequently. 

**BBB version (optional):**
2.2.17

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox
 - Version 77.01

**Comment by prlanzarin** [comment] 2020-06-12 15:52
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/8704.

**Closed by prlanzarin** 2020-06-12 15:52 UTC
Labels: HTML5 Client
