### ISSUE TITLE
Missing Chinese Simplified Fonts

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1154] opened 2015-08-12 07:19 UTC
Originally reported on Google Code with ID 399

```
What steps will reproduce the problem?
upload the attach pdf file to bbb server,and it will show messy code.
maybe the pdf file have Times New Roman fonts,the same pdf file upload to 
openmeeting server,it also show me the messy code,and i can see the error 
below:

Value:    **** Warning: Fonts with Subtype = /TrueType should be embedded.        

But Times New Roman is 

not embedded.ESP Ghostscript 815.02: Unrecoverable error, exit code 
1convert: Postscript delegate failed paste the 

i cant find any error on my bbb server,so i try it in my openmeeting 
server. i already have  upload the times.ttf to my centos box.
bbb0.63 centos5.3


Please provide any additional information below.

```

Reported by `lubaoxian` on 2010-03-10 13:16:16

<hr>
- _Attachment: [ITIL V3的五大生命周期管理.pdf](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-399/comment-0/ITIL V3的五大生命周期管理.pdf)_

**Comment by ffdixon** [comment] 2017-01-07 19:52
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/3176

**Closed by ffdixon** 2017-01-07 19:52 UTC
Labels: Defect, Localization, Normal Priority, Usability
