### ISSUE TITLE
Webcam not mirrowed when the server site option mirrorOwnWebcam ist set to true

### ISSUE THREAD

**Issue by horoe** [bigbluebutton/bigbluebutton#14224] opened 2022-01-28 10:31 UTC
**Describe the bug**
In 2.4.2
If in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml mirrorOwnWebcam is set to true
it will only mirror the preview image.
The webcam image in the meeting is not mirrowed.

**To Reproduce**
1. Edit /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
2. Set mirrorOwnWebcam: true (line 64)
3. Restart bbb
4. Join a meeting
5. Share your webcam
6. At the preview, the image is mirrowed.
7. At the meeting the image is not mirrowed.

**Expected behavior**
The own webcam image is mirrowed during the meeting.

**Actual behavior**
The own webcam image is not mirrowed during the meeting.
It can be mirrowed by choosing the mirror option of the webcam image.

**Screenshots**

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.4.2 (2885)

**Desktop (please complete the following information):**
 - OS: macOS 12.1
 - Browser Firefox
 - Version 96.0.2

**Comment by prlanzarin** [comment] 2022-01-28 10:54
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/14130

**Closed by prlanzarin** 2022-01-28 10:54 UTC
Labels: module: client
