### ISSUE TITLE
Add a connection quality indicator to the client

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1759] opened 2015-08-12 07:46 UTC
Originally reported on Google Code with ID 1004

```
> * It would be nice to have connection quality indicator on the client 
> (let say green dot for good connection, yellow, slow, red terrible, 
> gray or black - no connection with the server - after timeout - 
> session is closed). 

Posted in this thread
   http://groups.google.com/group/bigbluebutton-setup/browse_thread/thread/dfcf1fb5d310b120#



```

Reported by `ffdixon` on 2011-09-18 13:28:15

**Comment by ffdixon** [comment] 2019-04-07 04:30
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/5286

**Closed by ffdixon** 2019-04-07 04:30 UTC
Labels: Enhancement, Flash Client, Normal Priority
