### ISSUE TITLE
Error in bigbluebutton.log: Conference NNNNN not found on clean install

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1416] opened 2015-08-12 07:30 UTC
Originally reported on Google Code with ID 661
```
What steps will reproduce the problem?
1.  Install BigBlueButton 0.71-beta
2.  sudo bbb-conf --clean
3.  Join the Demo Meeting 

What is the expected output? What do you see instead?

The output from 

   sudo bbb-conf --debug

shows

firstuser@clean-vm-20101017-00:~$ sudo bbb-conf --debug
   -- ERRORS found in /usr/share/red5/log/* --
/usr/share/red5/log/bigbluebutton.log:2010-10-17 01:15:08,320 [NioProcessor-1] ERROR
o.b.w.v.f.a.PopulateRoomCommand - Not XML: [Conference 78989 not found]

Everthing seems to work, so not sure if this error was a real error or not.


Please use labels and text to provide additional information.

```

Reported by `ffdixon` on 2010-10-17 01:19:17

**Comment by ffdixon** [comment] 2016-01-30 17:55
Closing this issue -- this is not a bug, just a warning message.  Closing.

**Closed by ffdixon** 2016-01-30 17:55 UTC
Labels: Accepted, Apps, Defect, Low Priority
