### ISSUE TITLE
Configurable help URL

### ISSUE THREAD

**Issue by fcecagno** [bigbluebutton/bigbluebutton#6115] opened 2018-09-25 21:28 UTC
On the HTML5 client, if you click on the help option in the menu, you'll always be redirected to https://bigbluebutton.org/videos. It would be helpful if we could set `helpUrl` on settings-production.json.

**Comment by capilkey** [comment] 2018-09-26 01:02
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/6029

**Closed by capilkey** 2018-09-26 01:02 UTC
