### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Veteranfighter** [bigbluebutton/bigbluebutton#11602] opened 2021-03-10 13:09 UTC
Hello.

Please develop a feature to control the output volume of each Big Blue Button participant.

Thank you very much for your work.
Stay healthy.

**Comment by prlanzarin** [comment] 2021-03-10 14:42
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/9046.

**Closed by prlanzarin** 2021-03-10 14:42 UTC
Labels: Enhancement
