### ISSUE TITLE
Support coturn with TLS on same machine as BBB

### ISSUE THREAD

**Issue by Natureshadow** [bigbluebutton/bigbluebutton#8875] opened 2020-03-25 23:34 UTC
**Describe the bug**
The BBB installation guide has both nginx and coturn listen on port 443. When coturn is deployed on the same machine as BBB, this leads to a raise condition if coturn is started before nginx and nginx does not start, or to coturn not starting the TLS listener and one of the configured TURN servers in BBB thus being non-functional.

**Installation type**
Manually

**Additional context**
A possible solution is proposed by the friends over at Jitsi Meet: They have coturn and the nginx virtual host both listen on another port than 443, then add a stream proxy to nginx that detects the incoming protocol and proxies either to its own virtual host or to coturn:

https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.conf

Technically, nothing has to be changed, this is mostly an update to the documentation.

**Comment by rottaran** [comment] 2020-04-08 00:41
Unfortunately the solution proposed there does not seem to be sufficient. The problem is, that other websocket connections (wss) also go to port 433 and often cannot be distinguished from the TURN traffic because both do not contain ALPN fields. Just sending everything unknown to coturn by default is not good solution, especially since coturn silently drops it without debugging messages. 

For example, we have a mattermost installation on the same server. Some mobile clients got weird connection issues for their websocket connection. These disappered after deactivating the turn by default mapping.

**Comment by matiasilva** [comment] 2020-06-14 22:59
The solution is to have the TURN server that lives on the BBB host listen on 3478 for normal connections and 5349 for TLS. Then have a second TURN server that listens on 443 to allow traffic from more restrictive firewalls. Hope this helps. Closing for now.

**Comment by Norcoen** [comment] 2020-12-15 11:20
> The solution is to have the TURN server that lives on the BBB host listen on 3478 for normal connections and 5349 for TLS. Then have a second TURN server that listens on 443 to allow traffic from more restrictive firewalls. Hope this helps. Closing for now.

In this case you still have nginx and TURN listen on 443, so you need to something like haproxy in between, or how did you go about this?

**Comment by rottaran** [comment] 2020-12-15 12:21
You can also proxy port 443 via nginx to coturn if you use two separate DNS names for the same machine, ie. single IP address. For example turn.mymachine.org and bbb.mymachine.org. Thanks to ALPN nginx can figure out the target DNS name without decrypting the connection and thus forward the turn traffic to coturn. Especially easy, if you have a wildcard SSL certificate for your domain and you can add CNAME records.

**Comment by Norcoen** [comment] 2020-12-15 12:31
@rottaran do you have this setup running?
Using two separate subdomains on the same IP and differentiating by SNI is what I have some experience in using nginx as a reverse proxy, but I thought - reading this thread - that there are some problems with that

**Comment by rottaran** [comment] 2020-12-15 14:35
Oh I was a little bit unclear there. SNI is working perfectly to differentiate the actual target DNS name of different SSL connections to port 443. What is not working is using a single DNS name (on a single IP adress) and using ALPN to differentiate between HTTPS, TURNS and WSS connections on port 443. In theory it would also work, but in practise too many SSL clients don't send the ALPN header.

**Comment by rottaran** [comment] 2020-12-15 14:43
And sorry, I forgot about the second and more annoying issue with proxying via nginx to coturn. This is likely a big show stopper: the TURN server needs to know the client's public IP address. When the client is behind a NAT, the client itself does not know this address. Discovery of your own public IP is the purpose of asking the TURN server. However, the TURN server will see the nginx's IP address instead. 

There is something called the PROXY protocol to prepend yet another header that forwards the client's actual IP address to the internal server. This is implemented on coturn's end. Unfortunately I was unable to figure this out on the nginx side. Could not find any plugin or option for this. It is invented by and implemented in haproxy.

**Comment by rottaran** [comment] 2021-05-21 09:19
> Using ALPN with a default rule for STUN/TURN traffic is a pitfall in itself. We have other web applications on the same address and some mobile apps do not send propper ALPN headers. For example, the mattermost app failed to work erratically. I had a solution for that, will have to find it again.

Adding another proxy in front of coTURN is not good for the performance, especially latency. Thus larger setups would likely have a separate IP address for coTURN. As as entry-level setup using ALPN protocol dispatch would be useful for many users. Mixing the BBB Server with other websites is quite unusual.

> Maybe we can get this solved to finally allow the setup script to deploy corresponding nginx files using an alternate domain name. The script could even request LE certs for the turn domain.

This is not necessary because the BBB webserver and the coTurn on port 443 would use the same DNS name and SSL certificate. They are dispatched by nginx based on the protocol field of the ALPN header.

It seems not necessary to setup coTurn and the webRTC clients for SSL encryption, just use the TCP port 443. Propper  HTTPS connections on port 443 will have a ALPN header with h2 or http protocol field. All STUN and TURN connections on port 443 will have some other header data (non-ALPN) and, hence, only the ALPN default rule of nginx will match.

**Comment by hex-m** [comment] 2022-02-24 07:16
> The solution is to have the TURN server that lives on the BBB host listen on 3478 for normal connections and 5349 for TLS. Then have a second TURN server that listens on 443 to allow traffic from more restrictive firewalls.

As we currently have to `forceRelayOnFirefox` because of #13746, there is more load on the TURN servers and in some setups additional TURN servers are probably needed. Installing coturn on every BBB server would be a simple solution. Currently the [documentation](https://docs.bigbluebutton.org/admin/setup-turn-server.html) only describes a dedicated coturn server (because of 443).

Ideally `bbb-install` would install and configure coturn (without 443) on the BBB host, but explaining how to set it up in the documentation would be a great start.

**Comment by hex-m** [comment] 2022-12-16 15:52
> we explored using haproxy to listen on port 443 and proxy incoming packets: https packets for nginx and TURN packets for coturn.

> If you want to have BigBlueButton 2.6 installed with an integrated TURN server, when you run the bbb-install command, substitute `bbb-install-2.6.sh` for `bbb-install-2.6-turn.sh`.

[src](https://groups.google.com/g/bigbluebutton-dev/c/02DK0jxG8Jw/m/5Vfc8Av2AgAJ)

Thanks a lot @schrd!

**Comment by ffdixon** [comment] 2023-02-24 13:31
Installation of coturn on same machine as BigBlueButton now in [2.6 installer](https://github.com/bigbluebutton/bbb-install).

**Closed by ffdixon** 2023-02-24 13:31 UTC
