### ISSUE TITLE
Highlight questions in chat

### ISSUE THREAD

**Issue by alfonsofernandezyf** [bigbluebutton/bigbluebutton#8615] opened 2020-02-07 05:05 UTC
**Is your feature request related to a problem? Please describe.**
It would be a nice feature to be able to tell questions apart from all the chat messages

**Describe the solution you'd like**
Any message in the chat that contains a question mark "?" will be highlighted

**Describe alternatives you've considered**

if (chatMessage.indexOf('?') > -1)  highlightQuestion() 

**Additional context**
I'll try to work it out myself

**Comment by ffdixon** [comment] 2020-02-07 11:32
Hi Alfonso,

Thanks for your suggestion.  We're also considering adding a new module called Questions to let students submit a question and have others up-vote it.

**Comment by pedrobmarin** [comment] 2021-04-14 23:17
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/8280

**Closed by pedrobmarin** 2021-04-14 23:17 UTC
Labels: module: client, type: enhancement
