### ISSUE TITLE
Webcam quality in HTML5 recordings

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#7347] opened 2019-05-03 18:15 UTC
Webcam quality in live session versus recording is not the same; webcams in recording are significantly lower quality

**Comment by prlanzarin** [comment] 2019-05-09 16:17
Should've been fixed by https://github.com/bigbluebutton/bbb-webrtc-sfu/pull/29.

**Closed** 2019-05-10 21:02 UTC

**Comment by jmessy919** [comment] 2021-01-18 23:50
Hello, I cannot find the file to modify the environment variable discussed here and here: https://github.com/bigbluebutton/bbb-webrtc-sfu/pull/29. Just recorded a new meeting, and the video was terrible quality. Any help would be appreciated. Thanks!

**Comment by prlanzarin** [comment] 2021-01-18 23:54
Do not mess with that setting. It now works as intended.

This issue was badly described  at the time (it was discussed internally), but the original problem was that the recorded file was being transcoded due to a container vs codec mismatch (at the time we had just switched to VP8 and it was being dumped into an mkv which is H.264 only in Kurento).

Video recordings are now a straight dump from the source feed. If the video has a "terrible quality", take a look at the docs on how to bump the default bitrates/resolution and you can also probe bigbluebutton-users for opinions on that. Please do not revive year-old issues.

**Comment by jmessy919** [comment] 2021-01-19 00:03
I appreciate you clarifying that the setting no longer needs to be modified.

However, the rest of your post isn't very helpful as I have already configured the bitrates in settings.yml and was using the High Definition profile with a bitrate of 800 when I recorded the meeting. Others see me clearly during the meeting, but the recording video looks much lower quality. Am I missing something?

Also - if I found this post by searching for my issue, doesn't it help future users to have this page contain the answer rather than force them to probe other users? I sense a bit of hostility and I'm not sure why. Perhaps I'm off-base on this perception, but really what's important is a resolution to the issue and then making sure that when others search for this problem (and find this issue) they know not to mess around with some environment variable and the appropriate path to take.

BBB is an awesome piece of software, but the recording I just made was objectively terrible and I know it's likely something I overlooked in the config.

Thank you for your time.

**Comment by prlanzarin** [comment] 2021-01-19 02:51
> I sense a bit of hostility and I'm not sure why. 

Yeah, actually, sorry if I was a bit harsh.

The reason why I mentioned better fits are  1) mailing lists or 2) other old issues with more discussion involved (this one is barren and void of useful info), using examples:

- https://groups.google.com/g/bigbluebutton-setup/c/WF8ZGGH2VPo/m/uXvhDZCXAQAJ
- https://github.com/bigbluebutton/bigbluebutton/issues/2483#issuecomment-751905138 (you may say this is about speed, but if you pay attention you'll learn quite a trove of stuff about tuning RaP encoding parameters)
- https://groups.google.com/g/bigbluebutton-setup/c/tcveCULl7r8/m/iDdcLVTmBwAJ
- etc (you get the gist)

> Also - if I found this post by searching for my issue, doesn't it help future users to have this page contain the answer rather than force them to probe other users?

  - [Project's support policy](https://docs.bigbluebutton.org/2.2/getting-help.html#introduction) 
  - It might help, yes. But again, the information you're looking for might be already available in the recommended support mediums. By "probing the mailing list <x>" I do not necessarily mean "open a new thread in the mailing list". The first thing to do would be searching the lists (exactly like you did with the github issues; they are google groups with search built in).
  - You have a far greater chance of somebody answering you (or finding some worthy info) in the mailing lists. The only reason why I saw this is because I was involved in this issue. And it was a tricky issue at the time (that's why I still remember it in details), so you might imagine my _surprise_ (to put it mildly) when somebody revived it.
  - What would then be useful, for instance, is that after you find a mailing list post of interest (or someone answers a thread of yours), to link that thread here (eg "For future reference: `link`)
