### ISSUE TITLE
The ability to change enableLimitOfViewersInWebcam & viewersInWebcam over API call

### ISSUE THREAD

**Issue by misisol** [bigbluebutton/bigbluebutton#10040] opened 2020-07-11 07:38 UTC
Hi everyone.
There is no such an option to change **enableLimitOfViewersInWebcam** and **viewersInWebcam** on API call. It's very useful if you want to create a room with limited webcams enabled.

Regards.

**Comment by matiasilva** [comment] 2020-07-11 09:22
Hi @misisol, what is your use case for this? I don't really see a need to restrict the number of webcams on a per-meeting basis...

**Comment by misisol** [comment] 2020-07-11 09:59
Hi @matiasilva,
In my case I want to limit the viewersInWebcam based upon Moderator's Plan price  bought in my platform.

**Comment by matiasilva** [comment] 2020-07-11 12:11
I see. Seeing as you are using BBB for commercial purposes, is there any chance you would fund development by hiring a developer or reaching out to the companies providing commercial support? This would guarantee that the feature you want is integrated within your desired time frame.

**Comment by misisol** [comment] 2020-07-12 15:28
Unfortunately I don't know any developer in my area to hire on BBB development, thanks anyway.

**Comment by hex-m** [comment] 2020-11-27 15:25
duplicate of #8844

**Closed** 2020-11-27 15:30 UTC
Labels: Enhancement
