### ISSUE TITLE
restart self video window again after closing fails 

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2306] opened 2015-08-12 08:30 UTC
Originally reported on Google Code with ID 1554

```
closing self video, (use X on video window,) and immediately trying to start  video
again, will cause the video button to change icon but video will  not start, and button
functionality stops.
```

Reported by `yossia6` on 2013-06-12 07:09:21

**Comment by ffdixon** [comment] 2017-01-07 21:46
Closing this issue as we were not able to reproduce on latest build of BigBlueButton 1.1-beta.

**Closed by ffdixon** 2017-01-07 21:46 UTC
Labels: Accepted, Defect, Low Priority, Usability, Video
