### ISSUE TITLE
how to fix error "Not running:  tomcat7 or grails"

### ISSUE THREAD

**Issue by bijism** [bigbluebutton/bigbluebutton#8162] opened 2019-09-28 19:49 UTC
how to fix error "Not running:  tomcat7 or grails"

```
root@ubuntu:~# bbb-conf --restart
Restarting BigBlueButton 2.2.0-beta-19 ...
Stopping BigBlueButton
Starting BigBlueButton



# Potential problems described below
# Not running:  tomcat7 or grails
................................................................
# Warning: found only 2 cores, whereas this server should have (at least) 4 CPU cores
# to run BigBlueButton in production.
#
#   http://docs.bigbluebutton.org/install/install.html#minimum-server-requirements
#
```
```
root@ubuntu:~# bbb-conf --status
red5 ——————————————————► [✔ - active]
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

```
```
root@ubuntu:~# bbb-conf --check

BigBlueButton Server 2.2.0-beta-19 (1369)
                    Kernel version: 4.4.0-164-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 4046 MB
                         CPU cores: 2

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://x.x.x.x.x
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: x.x.x.x.x
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://x.x.x.x.x
                              red5: x.x.x.x.x
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: x.x.x.x.x
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: x.x.x.x.x:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: x.x.x.x.x
                 playback_protocol: https
                            ffmpeg: 4.1.3-0york1~16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: x.x.x.x.x

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: x.x.x.x.x
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: x.x.x.x.x
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 687
                        kurentoUrl: wss://x.x.x.x.x/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below

# Warning: found only 2 cores, whereas this server should have (at least) 4 CPU cores
# to run BigBlueButton in production.
#
#   http://docs.bigbluebutton.org/install/install.html#minimum-server-requirements
#
root@ubuntu:~# 



```

**Comment by ffdixon** [comment] 2019-09-28 23:11
To fix, see the message printed just below the error

~~~
# Warning: found only 2 cores, whereas this server should have (at least) 4 CPU cores
# to run BigBlueButton in production.
#
#   http://docs.bigbluebutton.org/install/install.html#minimum-server-requirements
#
~~~

Your server is underpowered, which is causing BigBlueButton to fail in unpredictable ways.  You need to ensure your server meets the minimum requirements, see

  http://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements

**Comment by 1manprojects** [comment] 2019-12-16 15:27
Im having the same issues as described here as well.

Installed BigBlueButton with the install script on a fresh Ubuntu 16 with  4 CpuCores and 16Gb-Ram per install script

wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/master/bbb-install.sh | bash -s -- -v xenial-220 -s bbb.mydomain.de -e info@mydomain.de -g

and he server is not running behind a fierwall.

```BigBlueButton Server 2.2.0-rc-3 (1661)
                    Kernel version: 4.4.0-170-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 16045 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.olyro.de
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bbb.olyro.de
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://bbb.olyro.de
                              red5: bbb.olyro.de
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: x.x.x.x
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: x.x.x.x:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.olyro.de
                 playback_protocol: https
                            ffmpeg: 4.2.1-2ubuntu1bbb3~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: x.x.x.x

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: x.x.x.x
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: x.x.x.x
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 c                     lient)
                             build: 815
                        kurentoUrl: wss://bbb.mydomain.de/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
# Not running:  tomcat7 or grails LibreOffice
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://bbb.mydomain.de/
#
# If your BigBlueButton server is behind a firewall, see FAQ.
```

In the bbb-web.log the following error is being logged.

 ```
ERROR o.a.catalina.core.ContainerBase - A child container failed during stop
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to stop component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
        at java.util.concurrent.FutureTask.report(java.base@9-internal/FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(java.base@9-internal/FutureTask.java:193)
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:1001)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1439)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1428)
        at java.util.concurrent.FutureTask.run(java.base@9-internal/FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
Caused by: org.apache.catalina.LifecycleException: Failed to stop component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:238)
        ... 6 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to stop component [WebappLoader[]]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:238)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5514)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
        ... 6 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make member of class sun.rmi.transport.Target accessible:  module java.rmi does not export sun.rmi.transport to unnamed module @4716851c
        at sun.reflect.Reflection.throwInaccessibleObjectException(java.base@9-internal/Reflection.java:420)
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(java.base@9-internal/AccessibleObject.java:174)
        at java.lang.reflect.Field.checkCanSetAccessible(java.base@9-internal/Field.java:170)
        at java.lang.reflect.Field.setAccessible(java.base@9-internal/Field.java:164)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesRmiTargets(WebappClassLoaderBase.java:2121)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1581)
        at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1518)
        at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:446)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
        ... 8 common frames omitted```

**Comment by ffdixon** [comment] 2019-12-16 17:00
~~~
# Potential problems described below
# Not running:  tomcat7 or grails LibreOffice
~~~

Can you run `sudo bbb-conf --check` again.  Sometimes tomcat7 takes a long time to first startup and `bbb-conf` gives the warning when, in fact, it's actually starts running a few moments later.

**Comment by 1manprojects** [comment] 2019-12-17 10:39
calling ```bbb-conf` --check``` again even after 15 minutes results in the same message already described above.

**Comment by ReimarBauer** [comment] 2020-01-03 12:56
Always I remove bbb-demo I get a list 

```
apt-get purge bbb-demo
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
authbind libcommons-collections3-java libcommons-dbcp-java libcommons-pool-java libecj-java libservlet3.0-java libtomcat7-java tomcat7 tomcat7-common
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
bbb-demo*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded. 
```

After I call `apt autoremove` than there is not any tomcat7 on my system. And it seems completly working. Is this maybe because I forced html5 on any place? Or I have not used something which needs it? If it is only needed for the demo than I can live with that, besides:

`bbb-conf --restart` of course shows me that tomcat7 is not installed

**Comment by ffdixon** [comment] 2020-01-03 23:02
Can you update to the latest build of BigBlueButton 2.2, see http://docs.bigbluebutton.org/2.2/install.html.

I think we've fixed this in a recent build, but we'd be interested to hear if you still get this error after upgrade.

If you installed using [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) you can just re-run the same command again and it will upgrade you to the latest version.

**Comment by ahmedelfaleh** [comment] 2020-01-25 20:01
Hi, I had just installed BBB by bbb-install.sh.
No errors appeared during installation.
But I had this error in the end

# Potential problems described below
# Not running:  tomcat7 or grails LibreOffice
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://mysubdomain.mydomain.com/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

Any idea?

**Comment by ffdixon** [comment] 2020-01-26 02:09
@ahmedelfaleh Are you installing BigBlueButton using `bbb-install.sh` on a local machine (behind a firewall) or on the internet with a publicly accessible IP address and a hostname that resolves to that IP address?

**Comment by ahmedelfaleh** [comment] 2020-01-26 20:54
I installed it with static IP address and resolved hostname, i have
installed it with bbb-install.sh.
I have resolved the issue by installing bbb-demo, demo works.
Now i removed the demo again.
But when opening the website again it opens on demo page.
Is this page will be disappear when provide the secret number and the url
of the website to the web developer to embed them into the code?

**Comment by ffdixon** [comment] 2020-01-27 03:13
Hmm ... I just did a fresh install and don't get this error.  Would it be possible to take a quick look at your server (login via SSH) and try and figure out why your getting this message/

Just e-mail me directly ffdixon .at. bigbluebutton .dot. org. if this is an option.

**Comment by misiektw** [comment] 2020-03-11 09:45
In my case i got this error after upgrade from 2.0 to 2.2. Seems like script removed Tomcat. So in my case "sudo apt install tomcat7" resolved situation, and everything seems to work.
Check systemctl status tomcat7, if it says that tomcat is not installed...

**Comment by sibil** [comment] 2020-03-15 09:30
Looks like this error can happen if you've a very powerful server. Running BigBlueButton 2.2.0-rc-3.

I was running BBB on AWS c5.xlarge(4 vCPUs), changed the instance type to c5.18xlarge(72 vCPUs) and got this error.  Tried m5.24xlarge(96 vCPUs) and got the same error. 

It is working fine with c5.9xlarge(36 vCPUs). Thanks.

**Comment by capilkey** [comment] 2020-03-16 14:53
@sibil The solution to bbb-web not starting with lots of CPUs is to edit `/lib/systemd/system/bbb-web.service` and change `LimitNOFILE` to `8024`.

It's also important to note that BigBlueButton is not designed to use that many cores on a machine so most of the capacity won't be utilized. Using a load BigBlueButton load balancer in front of many BBB servers is the recommended approach. See https://groups.google.com/forum/#!topic/bigbluebutton-dev/T3WKHrwpTnQ for one example of a BBB load balancer. The one in that post is recommended for beginners though.

**Comment by sibil** [comment] 2020-03-16 19:24
Thanks @capilkey - I'll try Scalelite. Appreciate it. Scalelite will help more organizations to adopt BBB. Thanks @ffdixon & team.

BBB is working fine with c5.9xlarge(36 vCPUs) 

- Do I need to edit /lib/systemd/system/bbb-web.service for maximum utilization of the CPUs? 
- Are there any other configuration options that can give me more performance?

**Comment by capilkey** [comment] 2020-03-16 19:26
No configuration option will make it scale better on one machine. There is a node.js process that is single threaded and it will be your bottleneck.

**Comment by ffdixon** [comment] 2020-03-20 02:51
Added a check on `bbb-install.sh` to detect servers with more than 36 cores and increase `LimitNOFILE `.

https://github.com/bigbluebutton/bbb-install/commit/e58a3c0b36b7b7b4b34ec380d744fc05dc4e7d84

**Comment by ahmedelfaleh** [comment] 2020-03-20 03:48
Dear Fred,

Thanks for your reply, the problem has been solved by
@Ahmad Farhan

**Comment by Ed-Lang** [comment] 2020-04-09 23:13
Fresh Install ubuntu 16.04
using
 sudo apt-get install bigbluebutton
$sudo apt-get install bbb-html5

Tomcat7 did not install. Manual install solved the issue.

**Comment by ReimarBauer** [comment] 2020-04-09 23:22
I have this also on one instance, there it comes with installing bbb-demo
after removing bbb-demo it gets in the list of packages which can be
'autoremoved'.



Ed-Lang <notifications@github.com> schrieb am Fr., 10. Apr. 2020, 01:14:

**Comment by maaeps** [comment] 2020-04-22 15:43
I had this error occur by having a miss configuration in `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml` (I can't belief this, too.)
Maybe this helps someone.

**Comment by dmunozvenegas** [comment] 2020-04-22 18:16
I also had my server connection error, after having switched to a more powerful machine (56 CPU / memory cores 32528)

I just continue with the Tomcat7 message that it is not running, but in the state it is active.

Thank you @capilkey

**Comment by tomdrops** [comment] 2020-05-28 21:09
> I had this error occur by having a miss configuration in `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml` (I can't belief this, too.)
> Maybe this helps someone.

what kind of misconfiguration?
i'm having the same problem and can't find it...

**Comment by maaeps** [comment] 2020-05-30 14:08
@tomdrops 
I am not quite sure any more. I think i revered to "turn1" without defining it before.
Wrong comments have been a issue, too.

**Comment by labretagne** [comment] 2020-06-13 22:45
Hello, i have the same problem

**Comment by caos30** [comment] 2020-07-06 03:39
I had the same problem: i saw the same missing tomcat7 message. But when after 15 minutes i executed the command ```bbb-conf --check``` the message had gone :-)

Said this, i would like to share with you that i've used a DigitalOcean droplet of 2 cores and 4Gb of RAM, and i can say that the result was amazingly good!! I shared the performance graphs of the server (CPU, Bandwith and I/O) and the HTOP screenshot in this article on my blog. Because -you know- the official recommendation always is a minium of 4 cores and 8Gb of RAM.

So, with the half of resources BBB run smoothly. The unique bottleneck  is when it has to compress the session recording after close the room. It can do it, but consuming a lot of CPU and very slow. Please check my screenshots on my article.

[https://imasdeweb.com/index.php?pag=m_blog&gad=detalle_entrada&entry=78](https://imasdeweb.com/index.php?pag=m_blog&gad=detalle_entrada&entry=78)

**Comment by teshnizi** [comment] 2020-11-01 17:27
I tested the solutions offered in the thread but none of them worked. My server was satisfying the minimum requirements. 
However, I solved the problem by installing tomcat7 before installing BBB: 
`$ sudo apt-get install tomcat7`

**Comment by misiektw** [comment] 2020-11-02 14:33
> However, I solved the problem by installing tomcat7 before installing BBB:
> `$ sudo apt-get install tomcat7`

That's what I said in march... :)

**Comment by teshnizi** [comment] 2020-11-02 16:13
> > However, I solved the problem by installing tomcat7 before installing BBB:
> > `$ sudo apt-get install tomcat7`
> 
> That's what I said in march... :)

Right. Actually I wasn't able to install it when BBB was already installed, and I though that's what you have done as you said you were upgrading.

**Comment by higunjan** [comment] 2020-11-26 12:41
I faced same issue following problem resolve the issue.

Updated the file `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml`
1. Missed secret to in turn server.
2. Missed the closing tag slash `<ref .....="turn1" **/**>`

Restarted the BBB with clean command,  `bbb-conf --clean`

**Comment by pabloapico** [comment] 2021-02-05 04:39
> No configuration option will make it scale better on one machine. There is a node.js process that is single threaded and it will be your bottleneck.

Could you please tell me which one?

**Comment by M3dS0** [comment] 2021-02-14 21:06
the problem is in bbb-conf around line 393 before "systemctl start" it should be a
if [ -d $TOMCAT_DIR ]; then
      TOMCAT_SERVICE=$TOMCAT_USER
    fi
to find out correct version of installed tomcat

**Closed** 2021-04-04 22:52 UTC

**Comment by goekce** [comment] 2022-10-16 08:21
https://github.com/bigbluebutton/bigbluebutton/issues/8162#issuecomment-734276324 helped me, thanks @higunjan !

After decommenting the following while configuring the TURN server, I was too lazy to remove the strings between the XML nodes which is a syntax error.
```
    <bean id="turn1" class="org.bigbluebutton.web.services.turn.TurnServer">
        Secret:
        <constructor-arg index="0" value="VALUE"/>
        TURN server URL, use turn: or turns:
        <constructor-arg index="1" value="turns:turn.example.de:443"/>
        TTL in seconds for shared secret
        <constructor-arg index="2" value="86400"/>
    </bean>
```
should be:

```
    <bean id="turn1" class="org.bigbluebutton.web.services.turn.TurnServer">
       <!--Secret:-->
        <constructor-arg index="0" value="VALUE"/>
        ...
```
Pity that XML does not allow nested comments (`--` not allowed inside comments).

**Comment by clementgoclock** [comment] 2024-07-01 09:20
> Added a check on `bbb-install.sh` to detect servers with more than 36 cores and increase `LimitNOFILE `.
> 
> [bigbluebutton/bbb-install@e58a3c0](https://github.com/bigbluebutton/bbb-install/commit/e58a3c0b36b7b7b4b34ec380d744fc05dc4e7d84)

We could imagine another solution to set this on the fly ? I mean since withing the cloud provider you can scale up & down everyday we should have the good parameter at each time. 
Don't know how because it's a systemd service limitation. Or maybe just increase it by default ?
