### ISSUE TITLE
Error 1020 with iPadOS/iOS only

### ISSUE THREAD

**Issue by Rhywden** [bigbluebutton/bigbluebutton#10801] opened 2020-11-09 07:36 UTC
**Describe the bug**
Users with an iPadOS or iOS device cannot share their webcam if they‘re within my school‘s network. If they are at home it **may** work (though some users have reported running into a 1020 at home as well). All other devices work 100% (within the usual user error margins).

**To Reproduce**
1. Start or join a meeting
2. Enable audio
3. enable webcam on iOS/iPadOS
4. Get a 1020 error

**Expected behavior**
Both audio and video are shared

**Actual behavior**
Only audio works, video runs into 1020

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro, iPad Pro 2018
 - OS: iOS 14.2
 - Browser: Safari

**Additional context**
The BBB server runs on a hosted root server and is directly connected to the internet, not behind a firewall. The referenced ports (443 and 16384 - 32768) are reachable from inside my school‘s network.
I‘ve also setup a TURN/STUNS-Server on an AWS EC2-instance - while that one works fine, it does not make a difference at all. Demo.bigbluebutton.org showed the same problem (though this might also be related to the performance issues the demo server is currently having - will try again later)

**Comment by Lukas2000** [comment] 2020-11-09 18:12
This is a major issue for us as well on 2.2.27. Have had to instruct all students to switch to Chrome. It's causing a mess.

**Comment by prlanzarin** [comment] 2020-11-09 18:13
test.bigbluebutton.org is usually the test server you're looking for to **verify** if this is an actual issue or a setup issue.

**Comment by prlanzarin** [comment] 2020-11-09 18:15
Also check https://github.com/bigbluebutton/bigbluebutton/issues/10746 and it's comments. The vast majority of the situations where this happened were related to faulty STUN servers or misconfigured coturn instances or a misconfigured STUN+TURN pair in bbb-web.

**Comment by Rhywden** [comment] 2020-11-09 18:27
Yes, but why isn't it affecting all devices equally if it's a case of misconfiguration?

**Comment by prlanzarin** [comment] 2020-11-09 18:35
> Yes, but why isn't it affecting all devices equally if it's a case of misconfiguration?

Because not all endpoint environments are equal. Behaviour varies between Blink, Gecko and WebKit. And each version of them have a potentially distinct set of bugs like all software do. And like all software, their behaviour also depends on where they're running on (as in operating system, mobile or desktop, ...).

For instance: some Safari versions (not all) choke in spectacular ways when ie a STUN entry is botched. Most common scenario is the offer generation for the WebRTC peer getting **stuck** when an entry in the iceServers configuration is botched. It's silent. Just doesn't work. 1020. That doesn't happen in Chrome and/or Firefox because they properly ignore the botched entry.

The reason why I never close this kind of issue firsthand is because I'll never discard the possibility that it might be a bug on our side. The first thing to do to pinpoint where this is breaking is testing in test.bigbluebutton.org, which is the baseline, with an endpoint as close as the one you're reporting this issue for. If it works there, reviewing every setup process as outlined in the issue I mentioned is the next step.

If it doesn't work @test, we can debug this further.

**Comment by DDQW** [comment] 2020-11-10 11:22
In my case it was a turnserver using lets encrypt beacause ios safari has a problem with lets encrypt and the turn (unknown CA) 

Try disabling your turn server if you are using one.

**Comment by matiasilva** [comment] 2020-11-10 12:13
Isn't this a duplicate of #10746 ?

**Comment by xolf** [comment] 2020-12-17 10:05
My first approaches were also to try different STUN/TUN(S) servers and configurations, but unfortunately everything didn't work for me. Also reconfiguring ports and firewalls was useless.

For me, the problem came from the fact that I activated the multiple Kurento instances shortly before. As soon as I deactivated them, everything works again on iPadOS/iOS and Safari for Mac. See https://github.com/bigbluebutton/bigbluebutton/issues/10467#issuecomment-693382174  
Hope this helps you.

**Closed** 2020-12-19 00:43 UTC
