### ISSUE TITLE
The webcam image fliped horizontally

### ISSUE THREAD

**Issue by DronKram** [bigbluebutton/bigbluebutton#8355] opened 2019-11-22 11:29 UTC
Hello.
I installed BBB 2.2.0-rc-1 and have the webcam image flipped horizontally while in Skype and Nextcloud Talk image is ok.

**Comment by ffdixon** [comment] 2019-11-22 11:50
Thanks for reporting this -- can you give us the details to reproduce.

**Comment by Diaron** [comment] 2019-11-25 15:38
Just joint to the session and enable webcam.
I tried different browsers and a couple of webcams. Same behavior.
My setup is Moodle LMS + BBB Moodle plugins + BBB

**Comment by daminebenz** [comment] 2019-11-25 16:10
Hi,
can you please record this with a GIF recorder ? so we can understand the problem better !

**Comment by antobinary** [comment] 2019-11-27 14:09
Thank you for reporting this @Diaron !
Funny that we did not spot this earlier :smiley: 

This is my right ear in 2 different views
JitsiMeet
![Screenshot from 2019-11-27 09-05-31](https://user-images.githubusercontent.com/6312397/69729990-42162180-10f5-11ea-9729-f7bdf2361a99.png)


BBB 2.2-rc2
![Screenshot from 2019-11-27 09-06-23](https://user-images.githubusercontent.com/6312397/69729989-42162180-10f5-11ea-8fba-6222ab049f5f.png)

So indeed BBB flips the image horizontally

**Comment by antobinary** [comment] 2019-11-27 14:23
One benefit of the way we have it is that we can read normally any text displayed with the webcam:
![Screenshot from 2019-11-27 09-16-16](https://user-images.githubusercontent.com/6312397/69730759-a4bbed00-10f6-11ea-8ed5-b3bd5316266f.png)

vs the other app I tried:
![Screenshot from 2019-11-27 09-21-20](https://user-images.githubusercontent.com/6312397/69731125-50653d00-10f7-11ea-9179-83d1bb3a35b6.png)

@Diaron is there any negative consequence [from the flip] for your use of the webcam?

**Comment by Diaron** [comment] 2019-11-27 14:43
I am also didn't noticed that from the start. Users started complaining.
The negative consequence is - users are disoriented and scared )
But I agree that an ability to read text is a real benefit. Maybe an option in config for this case will be the best solution?

**Comment by capilkey** [comment] 2019-11-27 14:50
What everyone else sees is the same with us and other applications. What actually happens in the other applications is that they take the local preview of the webcam and flip it for the user. We don't do any of that manipulation and leave it as the raw. The users are expecting their webcam to act like a mirror and when it doesn't it can throw them off.

There's never any change to what is actually sent and displayed in other users clients.

I don't think we need to add any more configurations for something like this. We just need to make a decision about whether or not we want to start flipping the local preview.

**Comment by raphaelm** [comment] 2020-04-13 12:56
After having used BBB for a while, I still find it mighly confusing to see myself non-mirrored. Any plans on how to make a decision here? :)

**Comment by micw** [comment] 2020-04-22 12:11
Hello,
today we did a test conference with BBB (8 Partipiciants) and _everyone_ complained about the "mirrored" picture. People use to see themself in a mirror, so showing their own picture un-mirrored is very confusing.

**Comment by GitHorst** [comment] 2020-04-22 17:45
I think it's fair to say that everybody assumes their own preview to act like a mirror. I can confirm people being confused by seeing their 'raw' camera output instead of mirrored one.

**Comment by iSamof** [comment] 2020-04-22 19:16
I am not particularly leaning one way or the other but the entire "video web", with some exceptions, works the way BBB currently works. This is not a BBB issue. It is a video issue and has been around since recordings and original CCTV began. Even the movies (old celluloid films) work this way and do not mirror you. 

Every YouTuber is familiar with this issue and soon gets used to it. As @antobinary stated, if the video is flipped, all text gets flipped too ... yuk!  << that's a technical term meaning too much effort for too little return ;-) 

My view is, it does no harm and we all soon get used to it. But I guess there could be a config switch to select which to flip ... if not too much effort for the team.

**Comment by micw** [comment] 2020-04-22 19:38
I'm using different conferencing solutions for years and never had one that showed me to myself not like a mirror does.
IMO there's a big difference between video production and conferencing. Maybe video production people are used to see theirself "unmirrored" (like singers get used to hear their own voice via headphones only when they are recording). But to all other people both is very irritating.

**Comment by raphaelm** [comment] 2020-04-23 06:37
Funny thing is , it'd trivially easy even to do via a custom CSS if there was a way to identify which video is my own and which isn't.

```
video.myown { transform: scaleX(-1); }
```

**Comment by melodoi** [comment] 2020-04-23 11:46
Hi,
They are any news about this topic? I have the same problem and some of my colleagues too.

**Comment by cdir** [comment] 2020-04-23 19:33
Indeed this is reported by many of my collegues since we evaluate bbb for about one week. I also do not know any other video conference  system which does not mirror the own video.

**Comment by iSamof** [comment] 2020-04-24 08:08
@raphaelm - true ... here is an exciting prospect:

I think a Layout Editor for the HTML5 client is coming! If this allows custom CSS/JS then so many possibilities open up. And yes the reversal becomes as easy as you said although that can be config function ... hopefully per meeting or even per webcam (with a preset default of say mirror: true).

**Comment by melodoi** [comment] 2020-04-24 10:19
The current situation is good for a class room because you can read the text on a white- or blackboard. In my opinion, it is nesessery to be tble to switch between boot camera views (normal and mirrored) online while a meeting.

**Comment by cdir** [comment] 2020-04-24 11:10
@melodoi evey student still see your video correctly, only your own view of your video is mirrored. When you write something on a physical board which is recorded by your camery, you better read directly from the board. Still I think it is reasonable when your self-view reacts like a mirror.

**Comment by melodoi** [comment] 2020-04-24 11:52
Hi cdir,
I checked it and all videos are equal oriented. My and the students screen looks identical. I can read a in the camera holded text in all screens.
Best
Sylvio

**Comment by raphaelm** [comment] 2020-04-24 11:58
@cdir This issue is not about the status quo. The issue is about the wish that you own picture (and only your own) should be flipped (and only for you!)

**Comment by cdir** [comment] 2020-04-24 12:12
@raphaelm I know and I want to have my own picture be flipped!

**Comment by melodoi** [comment] 2020-04-24 13:39
Ah. That's true. I am slowly understanding. I am a German. :-)

**Comment by n2o** [comment] 2020-05-06 19:10
I'd also like to have my own image flipped, because it feels kind of weird to not see myself mirrored 😬

**Comment by kamischi** [comment] 2020-05-08 12:55
Please flip my video as a default or have an option to flip. Waving or moving an object is horrible when seeing myself not mirrored.

**Comment by n2o** [comment] 2020-05-08 17:07
Jep. You can add `transform: scale(-1, 1);` as CSS to your Video DOM Entity. This mirrors it as you wish. But these Divs seem to have random identifier, which I can't write a generic Code to automatically mirror my video... 🤔

**Comment by introlinux** [comment] 2020-05-15 06:19
Sometimes the presenter uses his own camera as a "Document Camera" to display text or to manipulate objects or also directly uses his own Document Camera as a normal webcam for videoconference. Although BBB displays readable text, it is not comfortable for the presenter to have to read with the book reversed. And it is a real madness if the presenter has to talk about what he is doing and give directions ("as you can see here on the left ..."). You would have to look directly at the screen and it is really annoying.
Therefore, it would be highly recommended that BBB has an option to flip the image from left to right, top to bottom, and the both options at the same time. For example, in Jitsi you can flip clicking in the webcam miniature, but it is still an incomplete solution, you should have the three options that I have commented before.

Thanks in advance.

**Comment by DronKram** [comment] 2020-05-21 12:00
The option is the best thing here, as for me.

**Comment by diacritica** [comment] 2020-05-26 15:15
We have been testing BBB for 2 weeks now at my company. We are heavy videocall users and there is just ONE complaint. Guess what? Yes, self-mirror option not present. I wouldn't go as far as to say it has to be mirrored for yourself ALL the time because showing text requires it to be readable (we don't do that but we understand people can do that). So option/toogle under pane or personal settings option would be fine.

**Comment by matiasilva** [comment] 2020-06-03 13:42
@ffdixon Could we have your thoughts on this? Not sure how difficult this would be to implement.

**Comment by n2o** [comment] 2020-06-03 13:48
It's simply adding `transform: scale(-1,1)` to the Speaker's `video`-Tag. Optional via button would be awesome. Currently, I am mirroring all screens in the session just to see my own video flipped, which is much more comfortable than the non-mirrored version. Code for this: `for (let v of document.getElementsByTagName("video")) { v.style.cssText = "transform: scale(-1,1)" }`

**Comment by Beiri22** [comment] 2020-06-05 07:47
I would also prefer an option to flip my own preview-video; would be awesome.

**Comment by prlanzarin** [comment] 2020-06-09 14:52
It shouldn't be optional. This doesn't warrant an option. We either mirror it or not.
I'll see to it that the local cameras get mirrored in 2.3 if that's so big of an issue.

**Comment by matiasilva** [comment] 2020-06-09 15:40
@prlanzarin Thanks! I believe it is an issue many are concerned with, yes.

**Comment by kamischi** [comment] 2020-06-10 07:00
> It shouldn't be optional. This doesn't warrant an option. We either mirror it or not.
> I'll see to it that the local cameras get mirrored in 2.3 if that's so big of an issue.

I completely disagree. It should definitely be an option. This is more important than what the default setting is. I can't claim all video clients have this, but many do. Flipped or non-flipped are appropriate in different situations. Adjusting your appearance requires mirrored image, but reading non-mirrored.

**Comment by matiasilva** [comment] 2020-06-10 09:05
Not to mention that it is an option that is not present in many other platforms. Could give BBB a leading edge...

**Comment by melodoi** [comment] 2020-06-10 10:19
The flip problem is one the reasons that I can't cancel our zoom licences. Some of my colleagues 
gets sick with the wrong mirror image at the moment - no joke!

I don't understand the long discussion here. The solution shuld be easy (video.myown { transform: scaleX(-1); } plus the Icon to activate.

**Comment by matiasilva** [comment] 2020-06-10 10:24
@melodoi I suspect that the devs are focusing on 2.3 and fixing more critical bugs. In any case, since you've found a solution, make a PR so we can make some noise there and hopefully have that integrated as soon as possible.

**Comment by micw** [comment] 2020-06-10 10:42
I'd say a "UX flaw that bugs so many users" counts as a critical bug...

**Comment by matiasilva** [comment] 2020-06-10 10:51
@antobinary What are your thoughts? Any chance you could integrate a PR for this?

**Comment by matiasilva** [comment] 2020-06-11 15:24
@melodoi I've looked into this and unfortunately such a simple solution is not possible. The HTML5 client doesn't distinguish between your own video feed and someone else's. Presently, it's only possible to change all video feeds.

**Comment by prlanzarin** [comment] 2020-06-11 15:33
https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx

An `User` object is passed as a prop. Import the Auth service utilitary. Compare `Auth.userID` to the prop's `user.userId`. If it's equal (meaning it's your local feed), apply the transform to the video tag. Can do that directly in the render or just extend the style in video-list/styles.scss with a transform and apply it only when the conditional is valid.

So it's possible.

If this ships in 2.2, **it has to be behind a configuration flag** so it can ship as it is now by default (non mirrored), but can be enabled in HTML5's settings.yml if you want. The reason for that is to minimize visible changes in minor patches. If we do this out of the blue in a **minor** patch, the complaints will turn their way around (folks asking why my webcam is now mirrored???).

Also, what I said about not giving an option is that saying that "putting a button in the UI" and just "triggering the transform" is not as simple as it sounds. An extra button is yet another thing to think about in UX. Not trivial. More buttons, more complexity, more decision points, more of a convoluted experience. I sincerely don't think we need a button for that. We either mirror it or not. It's mirrored and you wanna read to some object pointed at your camera? Look at the object IRL.

**Comment by matiasilva** [comment] 2020-06-11 16:09
@prlanzarin Thanks so much for this. I agree with your remarks.

If I were to implement this in a custom fork of the bbb-html5 client, how would I repackage and deploy?

**Comment by melodoi** [comment] 2020-06-11 16:18
@matiasilva: I*m sorry. I'm not an programer. I have't more. but maybe prlanzarin.

**Comment by matiasilva** [comment] 2020-06-12 23:37
Hi everyone,

I have written up a PR for this issue that works nicely and implements all of the changes above. For those who really want it, the mirroring is configurable per user via the API call. This is a more elegant method than having to add a completely new item to the UX, which only further delays implementation of this PR. Please have a go and test this yourself following the instructions on BBB docs for development of the HTML5 client. PR  #9828.

**Comment by prlanzarin** [comment] 2020-06-12 23:38
Cool. I'll review it.

**Comment by Beiri22** [comment] 2020-06-13 07:49
When I open a BBB room and I have activated that switch, will only I see my video mirrored; or will all users of the room see their own videos mirrored?

**Comment by Sea444** [comment] 2020-06-14 09:21
> 
> 
> It shouldn't be optional. This doesn't warrant an option. We either mirror it or not.
> I'll see to it that the local cameras get mirrored in 2.3 if that's so big of an issue.

It really should be an option.

BigBluebutton is designed for the education sector. Here the webcam function is used in two completely different ways:
a) As a normal webcam: To show the image of the person speaking
b) As a document camera: To show objects or to design/draw something on paper.

For variant a) the mirror effect would be great. Ideally as default.
For variant b) the mirror effect is very annoying.

Therefore, there should be the possibility for every participant to easy enable/disable the mirror effect at any time. This should be possible via a small additional button (e.g. like https://de.clipdealer.com/photo/media/A:42492276) next to the close button at the top of the camera image. Alternatively in the name menu at the bottom of the camera image.

**Comment by prlanzarin** [comment] 2020-06-14 17:28
If it ships as an option in 2.3 it will go under the user name dropdown in the webcam container. The fullscreen button is already a gigantic eyesore and I don't think we need any more buttons taking up space in the webcam view (which already gets pretty noisy the smaller it gets).

**Comment by Beiri22** [comment] 2020-06-14 17:31
What about hiding those buttons unless you hover the video?

**Comment by prlanzarin** [comment] 2020-06-14 17:32
Don't know how hover buttons play with accessibility (which is a main concern in BBB). Probably not nicely. I'd have an UX folk chime in on that, though.

**Comment by matiasilva** [comment] 2020-06-19 18:00
Glad to say this has been merged! For additional UX feature requests, I suggest opening another issue.

**Closed by matiasilva** 2020-06-19 18:00 UTC
Labels: HTML5 Client
