### ISSUE TITLE
Video transmission of other participants freezes after short disconnections

### ISSUE THREAD

**Issue by Oremountainflorian** [bigbluebutton/bigbluebutton#11108] opened 2021-01-06 09:24 UTC
**Bug description**
We often start BBB-session with cameras/webcams turned on. Unfortunately, my connection breaks once in a while for some seconds. The audio transmission then reconnects as expected without refreshing/reconnecting, but the camera transmission of the others stays frozen. Your own and the camera transmission of new participants will still be displayed fluently.

**Steps to reproduce the behavior**
1. Start a meeting with at least 2 persons.
2. Activate cameras.
3. Disconnect for a short moment and then reconnect.
4. The camera transmission of the other participants is frozen. 

**Expected behavior**
Camera transmission of the other meeting participants should reconnect as the audio transmission does. 

**Actual behavior**
Camera transmission of the other meeting participants freezes if you don't refresh browser window/reconnect to the BBB session. 

**BBB version**
- greenlight release-2.7.12
- BigBlueButton 2.2.31

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser: Firefox 84.0.1

**Comment by aguerson** [comment] 2021-01-06 10:10
same problem
2.2.31 build 1115
with chrome and windows 10

**Comment by prlanzarin** [comment] 2021-01-06 16:39
This is a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/10756.
I'm working on it.

**Closed by prlanzarin** 2021-01-06 16:39 UTC
Labels: HTML5 Client
