### ISSUE TITLE
Whiteboard annotations not propagated to all users

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#14804] opened 2022-04-12 15:23 UTC
**Describe the bug**
When a presenter starts drawing the other users can see the indicator moving but not the shape being drawn.

**To Reproduce**
1. Start drawing a shape with a presenter.
2. Have a second user join the meeting.

**Expected behavior**
The annotation should be shown for everyone.

**Actual behavior**
The annotation is shown for the presenter onyly.

**Screenshots**
![image](https://user-images.githubusercontent.com/4991088/162997148-2bf09f22-6ae2-4c53-bece-38c8b16a103b.png)

**BBB version:**
BigBlueButton Server 2.4.5

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All

**Comment by antobinary** [comment] 2022-06-01 15:30
In case this is not fixed within BBB 2.5, it should be re-tested on 2.6 with the new whiteboard - #14976

**Comment by antobinary** [comment] 2022-12-05 16:25
Not able to reproduce on the tldraw whiteboard on 2.6+. Please reopen with extra steps if you are able to.

**Closed by antobinary** 2022-12-05 16:25 UTC
Labels: component: whiteboard, module: client
