### ISSUE TITLE
Is it possible to use TCP instead of UDP port for freeswitch

### ISSUE THREAD

**Issue by burakguder** [bigbluebutton/bigbluebutton#10432] opened 2020-09-10 14:39 UTC
Most users say the sound is of poor quality, high-pitched and intermittent. If we don't mind the delay, is it possible to increase the quality of the sound, add buffer and send the packets via tcp?

**Comment by burakguder** [comment] 2020-09-10 22:01
I want to remove mcu for sound. when two people speak, voices stop and overlap

the settings below did not work

/opt/freeswitch/etc/freeswitch/sip_profiles/internal.xml

    
    <param name="inbound-bypass-media" value="true"/>

    
    <param name="inbound-proxy-media" value="true"/>

**Comment by uka-support** [comment] 2020-09-11 13:33
TCP won't help for audio communication. Reason: if a packet get's lost, TCP will retransmit to ensure it arrives before any other data is delivered. Which will introduce a delay.

But a lost packet is not a big deal in voice communication - it should just be tolerated. The priority is that the stream of packets keeps flowing. There's a reason most Voice-over-IP protocols use UDP!

**Comment by basisbit** [comment] 2020-12-12 19:44
Closing this issue because it is "as designed". For further custom developmment questions, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-dev).

For how to adjust the audio quality, jitter bufer size and so on, please see https://github.com/bigbluebutton/bigbluebutton.github.io/pull/212/files

**Closed by basisbit** 2020-12-12 19:44 UTC
