### ISSUE TITLE
Allow mods to close opened webcams

### ISSUE THREAD

**Issue by pedped** [bigbluebutton/bigbluebutton#10674] opened 2020-10-17 07:46 UTC
I would be nice for mods to have ability to all or one of specific webcam, while it is open. mods already have this feature for microphone, but they do not have any ability for webcams

**Comment by ReimarBauer** [comment] 2020-10-17 07:59
you can kick all at once by the Locks ;)
![lock_viewers](https://user-images.githubusercontent.com/278728/96331668-60637380-105f-11eb-8e6e-8e473a2813b3.png)

lock share webcams :)

**Comment by pedped** [comment] 2020-10-17 08:12
yes, but it lock all viewers, we need to have ability to disable specific webcam while teaching exactly like mic

**Comment by matiasilva** [comment] 2020-10-20 05:23
Duplicate of #9995

**Closed by matiasilva** 2020-10-20 05:23 UTC
Labels: Enhancement
