### ISSUE TITLE
Unauthorized Authentication failed due to missing credentials when joining breakout rooms.

### ISSUE THREAD

**Issue by Bevito** [bigbluebutton/bigbluebutton#10540] opened 2020-09-28 08:29 UTC
Hi

**Describe the bug**
When you try to create breakout rooms with people, they got "Unauthorized Authentication failed due to missing credentials.
401" .

**To Reproduce**
1. Go to a meeting (with Moodle or Greenlight)
2. Click on 'Create breakout rooms'
3. Join the breakout rooms

**Expected behavior**
People should be able to join the breakout rooms

**Actual behavior**
Error Unauthorized Authentication failed due to missing credentials

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.26 (2165)

**Desktop (please complete the following information):**
 - OS: Linux Debian 10 / Windows 10 LTSC
 - Browser : Firefox ESR 68.12.0esr and Chromium Version 83.0.4103.116

**Additional context**
We use scalelite with 6 BBB servers.

Best regards.

**Comment by ffdixon** [comment] 2020-09-28 08:34
> Browser : Firefox ESR 68.12.0esr and Chromium Version 83.0.4103.116

Can you reproduce the error on https://demo.bigbluebutton.org/?

On your servers, can you try with the latest version of FireFox (81.0) and let us know if you still see the error.

**Comment by Bevito** [comment] 2020-09-28 08:49
Hi Fred, 

Thank you for your reply.
I did some tests : 

- I just tested on https://demo.bigbluebutton.org/ and It works.
- I tested it with Firefox 81 on our servers : I had the same error.
- I had tested to create a session without scalelite (using API Mate) on one of our servers : I had the same error.

Best regards

**Comment by ffdixon** [comment] 2020-09-28 09:40
How did you update your server (manual update or using `bbb-install.sh`)?

**Comment by Bevito** [comment] 2020-09-28 10:08
All the servers are updated with cron-apt (using your repository)

**Comment by and1bm** [comment] 2020-09-28 14:05
Hi all,
we see exactly the same. Approximately half of our machines have been updated from 2.2.25 to 2.2.26 with 
`apt full-ugrade --autoremove`, as we always did before. These machines show the error now.
Regards,  Andi

**Comment by bigbluemeeting** [comment] 2020-10-01 07:05
Same problem observed by users. Definitely an issue in the 2.26 release.

**Comment by caiadogithub** [comment] 2020-10-01 15:15
Same here! I can not join a session!

Updated from 2.23 to 2.26 via "apt-get upgrade"

**Comment by RYNEQ** [comment] 2020-10-02 02:22
I just upgraded to 2.2.26
i have same problem
greenlight and breakout rooms cannot join at all
while
moodle works
and

**Comment by matiasilva** [comment] 2020-10-02 06:48
> 
> 
> Same here! I can not join a session!
> 
> Updated from 2.23 to 2.26 via "apt-get upgrade"

Make sure you also `sudo bbb-conf --setip yor.fqdn`

**Comment by RYNEQ** [comment] 2020-10-02 22:58
> > Same here! I can not join a session!
> > Updated from 2.23 to 2.26 via "apt-get upgrade"
> 
> Make sure you also `sudo bbb-conf --setip yor.fqdn`

It doesnt seem this fix the problem; setting ip again had no effect and still the Authorization error happens

**Comment by RaphaelWimmer** [comment] 2020-10-03 11:43
Same problem here. Have not yet found the root cause.

FWIW, here's the `bbb-web.log`. 

```
2020-10-03T13:26:33.862+02:00 INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"duration":15,"sequence":1,"record":false,"logCode":"create_meeting","name":"REDACTED (Room - 1)","description":"Create meeting.","meetingId":"1a13397a387c885aa4297c5081b84333bc9bed17-1601724393836","externalMeetingId":"8d129ef2abf75a6d099a87d0c93b0f5739ebbf38-1601724393836","isBreakout":true,"freeJoin":true,"parentMeetingId":"939e325e6f16bd0ce6015d10354753034b32d82d-1601723245785","webcamsOnlyForModerator":false}
2020-10-03T13:26:33.862+02:00 INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"duration":15,"sequence":2,"record":false,"logCode":"create_meeting","name":"REDACTED (Room - 2)","description":"Create meeting.","meetingId":"c1e9a1ea0d6c8ce6804f1bf0b6af6b5d58bb6d20-1601724393837","externalMeetingId":"7d5f79656dc9d56138d672ea7180126877357bb7-1601724393837","isBreakout":true,"freeJoin":true,"parentMeetingId":"939e325e6f16bd0ce6015d10354753034b32d82d-1601723245785","webcamsOnlyForModerator":false}
2020-10-03T13:26:33.864+02:00 INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"duration":15,"record":false,"logCode":"meeting_started","name":"REDACTED (Room - 1)","description":"Meeting has started.","meetingId":"1a13397a387c885aa4297c5081b84333bc9bed17-1601724393836","externalMeetingId":"8d129ef2abf75a6d099a87d0c93b0f5739ebbf38-1601724393836","isBreakout":true,"parentMeetingId":"939e325e6f16bd0ce6015d10354753034b32d82d-1601723245785"}
2020-10-03T13:26:33.865+02:00 INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"duration":15,"record":false,"logCode":"meeting_started","name":"REDACTED (Room - 2)","description":"Meeting has started.","meetingId":"c1e9a1ea0d6c8ce6804f1bf0b6af6b5d58bb6d20-1601724393837","externalMeetingId":"7d5f79656dc9d56138d672ea7180126877357bb7-1601724393837","isBreakout":true,"parentMeetingId":"939e325e6f16bd0ce6015d10354753034b32d82d-1601723245785"}
2020-10-03T13:26:37.419+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#join
2020-10-03T13:26:37.420+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=c03a64984a3daeb1f84bc25946a17f75dbba4409f37d35f919133979e36b2714 length=64
2020-10-03T13:26:37.420+02:00 INFO  o.b.api.ParamsProcessorUtil - SHA256 c03a64984a3daeb1f84bc25946a17f75dbba4409f37d35f919133979e36b2714
2020-10-03T13:26:37.420+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=c03a64984a3daeb1f84bc25946a17f75dbba4409f37d35f919133979e36b2714 length=64
2020-10-03T13:26:37.420+02:00 INFO  o.b.api.ParamsProcessorUtil - SHA256 c03a64984a3daeb1f84bc25946a17f75dbba4409f37d35f919133979e36b2714
2020-10-03T13:26:37.421+02:00 INFO  o.b.web.controllers.ApiController - Retrieving meeting 1a13397a387c885aa4297c5081b84333bc9bed17
2020-10-03T13:26:37.421+02:00 INFO  o.b.web.controllers.ApiController - Session sessionToken for REDACTED REDACTED [null]
2020-10-03T13:26:37.422+02:00 INFO  o.b.web.controllers.ApiController - Session user-token for REDACTED REDACTED [null]
2020-10-03T13:26:37.422+02:00 INFO  o.b.web.controllers.ApiController -  --analytics-- data={"extMeetingid":"8d129ef2abf75a6d099a87d0c93b0f5739ebbf38-1601724393836","logCode":"join_api","name":"REDACTED REDACTED","sessionToken":"tjfzppobl5fzlee4","description":"Handle JOIN API.","meetingid":"1a13397a387c885aa4297c5081b84333bc9bed17-1601724393836","userid":"w_gtz50e3ytej1"}
2020-10-03T13:26:37.422+02:00 INFO  o.b.web.controllers.ApiController - Redirecting to https://REDACTED/html5client/join?sessionToken=tjfzppobl5fzlee4
2020-10-03T13:26:43.043+02:00 INFO  o.b.web.controllers.ApiController - No session for user in conference.
```

And the browser's error console (from another session):

```
[13:36:25:0827]  INFO: clientLogger: Connection to Meteor took 7.40s https://REDACTED/html5client/982375322d29a214765f0c8929117f65f6bd0a15.js?meteor_js_resource=true:121:1030127 982375322d29a214765f0c8929117f65f6bd0a15.js:9:353658
[13:36:27:0229] ERROR: clientLogger: User faced an error on main.joinRouteHandler. https://REDACTED/html5client/982375322d29a214765f0c8929117f65f6bd0a15.js?meteor_js_resource=true:121:1032609 982375322d29a214765f0c8929117f65f6bd0a15.js:9:353658
[13:36:27:0239] ERROR: clientLogger: Encountered error while trying to authenticate https://REDACTED/html5client/982375322d29a214765f0c8929117f65f6bd0a15.js?meteor_js_resource=true:121:997594 982375322d29a214765f0c8929117f65f6bd0a15.js:9:353658
[13:36:27:0253] ERROR: clientLogger: User could not log in HTML5, hit 401 https://REDACTED/html5client/982375322d29a214765f0c8929117f65f6bd0a15.js?meteor_js_resource=true:121:1205937 982375322d29a214765f0c8929117f65f6bd0a15.js:9:353658
[13:36:28:0129] ERROR: clientLogger: User could not log in HTML5, hit 401 https://REDACTED/html5client/982375322d29a214765f0c8929117f65f6bd0a15.js?meteor_js_resource=true:121:1205937
```
(for the record: no lines logged in `greenlight/log/production.log` or `/var/log/nginx/error.log`)

**Comment by pedrobmarin** [comment] 2020-10-03 13:44
The missing session issue might be related with a `JSESSIONID` cookie problem. 2.26 included a configuration to provide an extra layer of security to cookies. bbb-web (API related) cookies now have mandatory `HttpOnly` and `Secure` tags (https://github.com/bigbluebutton/bigbluebutton/pull/10511). You can verify if that's the problem by temporary removing this configuration from `/usr/share/bbb-web/WEB-INF/classes/application.yml` (and restarting the service).
 
Check if your setup supports secure cookies (some reference here https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) and, If it doesn't, try fixing that before just permanently removing the `Secure` from the cookie.

**Comment by RaphaelWimmer** [comment] 2020-10-03 15:56
> The missing session issue might be related with a `JSESSIONID` cookie problem. 2.26 included a configuration to provide an extra layer of security to cookies. bbb-web (API related) cookies now have mandatory `HttpOnly` and `Secure` tags (#10511). You can verify if that's the problem by temporary removing this configuration from `/usr/share/bbb-web/WEB-INF/classes/application.yml` (and restarting the service).

Indeed - that resolved the problem. Breakout rooms work as expected now.
Thank you!

> Check if your setup supports secure cookies (some reference here https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) and, If it doesn't, try fixing that before just permanently removing the `Secure` from the cookie.

Hmm, if I understand correctly, everything should work as expected if the web server uses https. I'm using a LetsEncrypt certificate within the standard environment (installed 2.2.23, upgrade to 2.2.26 like the other people who have this issue). Any suggestions on how to find the problematic configuration?

**Comment by pedrobmarin** [comment] 2020-10-03 16:16
Not sure about that yet. I would expect demo.bigbluebutton.org to have the same issue if it was something regarding the cookie security and it seems to be working fine there. Maybe the join URL that is being generated for the breakout room has an insecure protocol.

**Comment by pedrobmarin** [comment] 2020-10-03 20:57
Just to add some more information about my previous comment, you can check if this URL https://github.com/bigbluebutton/bigbluebutton/blob/c868beed6a6cbf886c6c13ed6bb0c8256507c50a/akka-bbb-apps/src/universal/conf/application.conf#L46 has HTTPS set. You can find this file at `/usr/share/bbb-apps-akka/conf/application.conf`.

**Comment by RaphaelWimmer** [comment] 2020-10-03 21:25
> Just to add some more information about my previous comment, you can check if this URL has HTTPS set. 

Nope, it has not! Changing it to `https://` (and re-enabling the secure cookie) has fixed the issue completely.
Thank you!

I'm not sure why this happened at all. Maybe I used a `http://` URL when setting up the system for the first time, then enabled HTTPS, but did not know that I had to change an URL in this config file, too. Or should this have happened automatically but failed for some reason?

(Having all config files in a central place (e.g. `/etc/bigbluebutton/`) might have made finding the source of the problem much easier, and might also have avoided this error altogether in my case. )

**Comment by Bevito** [comment] 2020-10-03 21:39
Thank you very much pedrobmarin and RaphaelWimmer for your help.
Like RaphaelWimmer my application.conf used http:// ustead of https:// for bbbWebAPI parameter.

**Comment by RYNEQ** [comment] 2020-10-03 21:59
I confirm using **https** in for API url fixes this problem
Thanks

I think a redirection of http to https would be good in nginx configuration to prevent such problems

**Comment by bigbluemeeting** [comment] 2020-10-04 00:30
One liner to fix this:

sed -i 's,bbbWebAPI="http://,bbbWebAPI="https://,g' /usr/share/bbb-apps-akka/conf/application.conf

**Comment by bigbluemeeting** [comment] 2020-10-04 01:05
> I confirm using **https** for API url fixes this problem
> Thanks
> 
> I think a redirection of http to https would be good in nginx configuration to prevent such problems

http still needs to exist for lets encrypt renewal.

**Comment by and1bm** [comment] 2020-10-04 15:17
> > Same here! I can not join a session!
> > Updated from 2.23 to 2.26 via "apt-get upgrade"
> 
> Make sure you also `sudo bbb-conf --setip yor.fqdn`

This seems to have fixed the issue for us -- before, the fqdn was set to just "HOST" instead of the hostname. Somehow the latter must have disappeared during upgrade.

Many thanks,  Andi

**Comment by greatfireball** [comment] 2020-10-22 13:48
We have an installation of scalelite with 3 BBB-servers and the sed command which replaces the http:// link by a https:// link solved the issue for us.

**Comment by Bevito** [comment] 2020-11-02 12:11
Upgrade from 2.2.26 to 2.2.27 and to 2.2.28, the /usr/share/bbb-apps-akka/conf/application.conf file was modified by upgrading (I don't know if it's 2.2.27 or 2.2.28 update that modified the file).
Is there a way to fix this definitivly ?

Thanks a lot

**Comment by Richardvi** [comment] 2020-11-04 17:06
We are running into this problem as well (upgrade to version 2.2.28). What should we do to fix this?

**Comment by RaphaelWimmer** [comment] 2020-11-04 20:33
> We are running into this problem as well (upgrade to version 2.2.28). What should we do to fix this?

You might have to change the `bbbWebAPI` URL in `/usr/share/bbb-apps-akka/conf/application.conf` to https (again).
See: https://github.com/bigbluebutton/bigbluebutton/issues/10540#issuecomment-703163803 and https://github.com/bigbluebutton/bigbluebutton/issues/10540#issuecomment-703181363 above.

**Comment by canonex** [comment] 2020-12-02 09:33
> > I confirm using **https** for API url fixes this problem
> > Thanks
> > I think a redirection of http to https would be good in nginx configuration to prevent such problems
> 
> http still needs to exist for lets encrypt renewal.

It is possible to avoid redirection for `.well-known/acme-challenge`
It is suggested in https://blog.rimuhosting.com/2018/11/29/solve-letsencrypt-including-certbot-problems-caused-by-rogue-htaccess-files/
(is for Apache but the idea can be applied to Nginx)

**Comment by amishbhavsar** [comment] 2021-01-09 19:31
Hi.

I am having s smiliar issue...

**Describe the bug**
When you try to create breakout rooms with people, they got "Unauthorized Session not found. 401".

**To Reproduce**
Go to a meeting (Greenlight)
Click on 'Create breakout rooms'
Join the breakout rooms
See error
Expected behavior
People should be able to join the breakout rooms

**Actual behavior**
Unauthorized Session not found. 401

**BBB version (optional):**
BigBlueButton Server 2.2.31 (2298)

**Desktop (please complete the following information):**
OS: Windows 10
Browser : Chrome Version 87.0.4280.88

**Comment by SoerenBusse** [comment] 2021-01-11 09:10
Hey there,

suddenly we're seeing the same issue. We only get a 401 error on the client side.

In the bbb-web.log it is says that it cannot find the session. It also shows the sessionToken and userSession as `null` altough the session manager of tomcat should already contain these sessions from the "non-breakout-room-join" before:
```
2021-01-11T10:06:00.093+01:00 INFO  o.b.web.controllers.ApiController - Retrieving meeting d05715bdecbbe5d47942ad3a589854f39e5b54ba
2021-01-11T10:06:00.093+01:00 INFO  o.b.web.controllers.ApiController - Session sessionToken for XXX [null]
2021-01-11T10:06:00.093+01:00 INFO  o.b.web.controllers.ApiController - Session user-token for XXX [null]
....
2021-01-11T10:06:00.094+01:00 INFO  o.b.web.controllers.ApiController - Redirecting to https://bbb.kst-vechta.de/html5client/join?sessionToken=m4ld2bp5peievk41
2021-01-11T10:06:01.470+01:00 DEBUG o.b.web.controllers.ApiController - ApiController#enter
2021-01-11T10:06:01.470+01:00 INFO  o.b.web.controllers.ApiController - Session for token m4ld2bp5peievk41 not found
2021-01-11T10:06:01.470+01:00 INFO  o.b.web.controllers.ApiController - Meeting related to m4ld2bp5peievk41 doesn't allow requests without session
```

**Comment by ffdixon** [comment] 2021-01-11 09:52
@SoerenBusse Interesting.  Which version of BigBlueButton are you running?

**Comment by SoerenBusse** [comment] 2021-01-11 10:06
@ffdixon Currently I'm running 2.2.30 (I've not updated to 2.2.31, because 2.2.30 worked very solid until now).

I had also a look into the redis database. Is it correct, that all sessionstorage key looks like this:
```
127.0.0.1:6379> GET "sessionstorage:cvQbWxE3SVxCPfxKfyPArNbcz2GbNr9q"
"{\"cookie\":{\"path\":\"/\",\"_expires\":null,\"originalMaxAge\":null,\"httpOnly\":true,\"sameSite\":\"None\",\"secure\":false}}"
```

I'm wonder about the `secure: false`, the very few informations and the missing JSESSIONID (is it even required?) in the redis key. 

The http -> https fix of bbb-aka-apps is already applied and doesn't fix this bug.

**Comment by SoerenBusse** [comment] 2021-01-11 14:34
Ok, it's working again. I stopped all bigbluebutton services using `bbb-config --stop` and manually started redis using `service redis start`. I cleaned up all 50.000 entries using the `FLUSHALL` command and started BigBlueButton again.

I cannot tell what the issue was. Maybe some strange redis entries from older versions?
Nice side effect: The echo test is now much faster.

@amishbhavsar 
Does this work in your case, too?

@ffdixon 
I think it would be useful to disable the "autosave" persistence functionality of redis to make sure that an BigBlueButton restart uses a fresh and clean redis database.

**Comment by ffdixon** [comment] 2021-01-11 15:47
You can flush the redis database by putting the following in `/etc/bigbluebutton/bbb-conf/apply-conf.sh`

```
systemctl start redis-server
until [ `redis-cli ping | grep -c PONG` = 1 ]; do echo "Waiting 1s for Redis to load"; sleep 1; done
redis-cli flushdb
systemctl stop redis-server
```

If you do this (not recommended) any active meetings that will be in progress will be completely flushed from the server (no recordings can be created as all the events are removed from the server).

See also: https://docs.bigbluebutton.org/2.2/customize.html#apply-confsh

**Comment by ffdixon** [comment] 2021-01-11 15:48
See also https://stackoverflow.com/questions/28785383/how-to-disable-persistence-with-redis

**Comment by pedrobmarin** [comment] 2021-04-03 19:44
Closing this since the original issue seems to be resolved.

**Closed by pedrobmarin** 2021-04-03 19:44 UTC
Labels: HTML5 Client
