### ISSUE TITLE
Make links in uploaded presentations clickable

### ISSUE THREAD

**Issue by mgbleichner** [bigbluebutton/bigbluebutton#14903] opened 2022-04-28 09:50 UTC
I am always frustrated when presenters have a link in their presentation that I cannot follow. 

It would be great if a link (in an uploaded presentation) is clickable

**Comment by jibon57** [comment] 2022-04-28 11:10
This is expected as after uploading PPT or DOC file those converted into image (svg) file & display in canvas (whiteboard). Only way if those would be converted into HTML5 format directly, which won't be easy to do. Again there will be new limitation like drawing, marking etc :-D.

**Comment by hostbbb** [comment] 2022-04-28 11:40
Just looking at this,  its possible to  detect videos and urls as they appear in active slides with little redis service and no modifications to core BBB code,  the presentation conversion actually places this data in textfiles for screenreaders.   So could actually detect slide change events and place URLS in the chat for everyone to click on..  Like wise could fire off an external video automatically if it was on a page with PLAY: (videoURL) format as an example.

Just did a quick test, seems like it would work as stop gap until formal feature exists in product.

**Comment by basisbit** [comment] 2022-04-30 00:44
Closing this as a duplicate of #6708.

**Closed by basisbit** 2022-04-30 00:44 UTC
Labels: type: enhancement

**Comment by hostbbb** [comment] 2022-10-11 09:12
Just looking at this,  its possible to  detect videos and urls as they appear in active slides with little redis service and no modifications to core BBB code,  the presentation conversion actually places this data in textfiles for screenreaders.   So could actually detect slide change events and place URLS in the chat for everyone to click on..  Like wise could fire off an external video automatically if it was on a page with PLAY: (videoURL) format as an example.

 

Just did a quick test, seems like it would work as stop gap until formal feature exists in product.

 

Regards,

Stephen

**Comment by basisbit** [comment] 2022-10-11 09:39
@hostbbb, this issue here was closed as duplicate. Please use the other linked issue for any further discussion.

**Comment by hostbbb** [comment] 2022-10-11 13:26
this must have been a stuck email from april :) looks like i posted it today, but didnt.  thanks for referencing
