### ISSUE TITLE
Drawing functionality while sharing screen

### ISSUE THREAD

**Issue by juliananegrete** [bigbluebutton/bigbluebutton#9071] opened 2020-04-14 09:08 UTC
It would be nice to be able to draw while people are sharing screens. Same as when you upload a presentation and you can draw on it, this featured should be available when people share the screen as well.

**Comment by matiasilva** [comment] 2020-06-17 23:50
Duplicate of #5835.

**Closed by matiasilva** 2020-06-17 23:50 UTC
Labels: Enhancement
