### ISSUE TITLE
BBB return userId & meetingId not matched the ones passed in

### ISSUE THREAD

**Issue by chivitc1** [bigbluebutton/bigbluebutton#4714] opened 2017-11-22 10:34 UTC
I intend to maintain userId & meetingId in our own system, but getMeetingInfo api & webhook api return internal IDs instead. Can we have a workaround? I need both web api & web hook return the ID passed in whilte create room, join room.

Appreciate your help

**Comment by ffdixon** [comment] 2017-11-26 14:40
Duplicate of #4660.

We're going to fix #4660 as part of BigBlueButton 2.0-beta.  We'll have it working again for you shortly.

**Closed by ffdixon** 2017-11-26 14:40 UTC
