### ISSUE TITLE
Black screen instead of camera in Firefox 91.5.x ESR

### ISSUE THREAD

**Issue by MiStErLu** [bigbluebutton/bigbluebutton#14246] opened 2022-02-01 15:15 UTC
**Describe the bug**
We create a bbb session, we join as a moderator with a browser Firefox 91.5.1 ESR (latest stable version) with camera enable
We join with another browser (Egge / Chrome / or lastest Firefox version) with camera enable
All enable camera sharing
On the Firefox 91.5.1 browser, we only seen own camera. We see a black scren for the second camera
On the other Browser, we see the two camera correctly
The sound work perfectly, no problem.

**To Reproduce**
We create a bbb session, we join as a moderator with a browser Firefox 91.5.1 ESR 32bits on a Windows 10 Professionnel version with camera enable
We join with another browser (Egge / Chrome / or lastest Firefox version) with camera enable
All enable camera sharing
On the Firefox 91.5.1 browser, we only seen own camera. We see a black scren for the second camera. Sometimes, without any rease the content of the camera appear.
On the other Browser, we see the two camera correctly
The sound work perfectly, no problem.

**Expected behavior**
We need to see the two camera

**Actual behavior**
We see a black image install of the camera content

**Screenshots**
![image](https://user-images.githubusercontent.com/5516692/151995095-34f62f8b-1c4b-435d-83c7-c3393b0ef8ab.png)

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.4.2 (2885)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 91.5.1 ESR

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by prlanzarin** [comment] 2022-02-01 15:18
Is this reproducible in demo.bigbluebutton.org

**Comment by MiStErLu** [comment] 2022-02-01 15:28
Of course it's working with demo.bigbluebutton.com problem is on my installation. I will check.

**Comment by prlanzarin** [comment] 2022-02-01 17:09
> Of course it's working with demo.bigbluebutton.com problem is on my installation. I will check. Sorry for the trouble :)

demo has a bit of a special spice added to its configuration. I marked it as verify so that I can test it on a fully stock v2.4.2 server. Short on time will do it tomorrow.

**Comment by prlanzarin** [comment] 2022-02-03 12:06
@MiStErLu 

Can you please set `iceTcp=0` in `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini`, run sudo systemctl restart kurento-media-server.service and try reproducing the issue again? Thanks.

**Comment by shad0wfax-de** [comment] 2022-02-04 21:43
Hi,
we ran into a similar Issue with our BigBlueButton Server. Unfortunately only two people (so far) out of roughly 100 can reproduce the issue so far. We were yet not able to pinpoint the issue down.
@prlanzarin setting iceTCP to 0 didn't help.
But yeah, the problem is on our server, demo.bigbluebutton.org works just fine.

**Comment by prlanzarin** [comment] 2022-02-04 21:45
Then may I recommend testing mediasoup if you're using 2.4? :)

**Comment by MiStErLu** [comment] 2022-02-04 22:13
Hi,

   We have probably identify the problem with the turn server connected to my BBB serveur. The turn is located on an other network (with other BBB backend - if you ask why, we deployed BBB backend on 2 differents virtualisation system in order to shared the load). We reinstall a turn server in the same network (and adapt configuration) and all work fine with firefox and other browser. I think there is a problem with the turn server / network or something like that.

MiStErLu

**Comment by prlanzarin** [comment] 2022-02-04 22:50
> Hi,
> 
> We have probably identify the problem with the turn server connected to my BBB serveur. The turn is located on an other network (with other BBB backend - if you ask why, we deployed BBB backend on 2 differents virtualisation system in order to shared the load). We reinstall a turn server in the same network (and adapt configuration) and all work fine with firefox and other browser. I think there is a problem with the turn server / network or something like that.
> 
> MiStErLu

Cool. Can you please close the issue if it was figured out? thanks.

**Closed** 2022-02-07 13:31 UTC
Labels: module: client, status: verify
