### ISSUE TITLE
Cannot destructure property 'width' of 'slidePosition' as it is undefined.

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#8932] opened 2020-03-31 13:50 UTC
**Describe the bug**

`I20200401-11:44:42.879(0)? error: {"logCode":"startup_error","logDescription":"TypeError: Cannot destructure property 'width' of 'slidePosition' as it is undefined.","extraInfo":{"stackTrace":"TypeError: Cannot destructure property 'width' of 'slidePosition' as it is undefined.\n    at PresentationArea.componentDidMount (https://amine23.blindside-dev.com/html5client/app/app.js?hash=6f2ee2bdff5b243c8b08f54b248fb086b348a503:14036:14)\n    at commitLifeCycles (https://amine23.blindside-dev.com/html5client/packages/modules.js?hash=0738c48913b99a59d22c4fde094121053dfd3d41:30221:22)\n    at commitLayoutEffects (https://amine23.blindside-dev.com/html5client/packages/modules.js?hash=0738c48913b99a59d22c4fde094121053dfd3d41:33464:7)\n    at HTMLUnknownElement.callCallback (https://amine23.blindside-dev.com/html5client/packages/modules.js?hash=0738c48913b99a59d22c4fde094121053dfd3d41:8456:14)\n    at Object.invokeGuardedCallbackDev (https://amine23.blindside-dev.com/html5client/packages/modules.js?hash=0738c48913b99a59d22c4fde094121053dfd3d41:8505:16)\n    at invokeGuardedCallback (https://amine23.blindside-dev.com/html5client/packages/modules.js?hash=0738c48913b99a59d22c4fde094121053dfd3d41:8560:31)\n    at commitRootImpl (https://amine23.blindside-dev.com/html5client/packages/modules.js?hash=0738c48913b99a59d22c4fde094121053dfd3d41:33202:9)\n    at unstable_runWithPriority (https://amine23.blindside-dev.com/html5client/packages/modules.js?hash=0738c48913b99a59d22c4fde094121053dfd3d41:36690:12)\n    at runWithPriority$2 (https://amine23.blindside-dev.com/html5client/packages/modules.js?hash=0738c48913b99a59d22c4fde094121053dfd3d41:20269:10)\n    at commitRoot (https://amine23.blindside-dev.com/html5client/packages/modules.js?hash=0738c48913b99a59d22c4fde094121053dfd3d41:33042:3)","validUser":"valid"},"userInfo":{"sessionToken":"nj1uy4qbvu4rrgop","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1585741473848","requesterUserId":"w_eyqpr8wjnnwm","fullname":"b","confname":"Demo Meeting","externUserID":"w_eyqpr8wjnnwm","uniqueClientSession":"nj1uy4qbvu4rrgop-k99y84"}}`
![image (1)](https://user-images.githubusercontent.com/5144311/78033661-0f976200-733d-11ea-9688-7976a937c172.png)
**To Reproduce**
it happens alot in 2.3 servers

**Expected behavior**
the presentation should be displayed.

**Actual behavior**
difficulty to display presentation, due to some calculations errors

**Screenshots**
![f515d501-c318-439f-a1d2-8f598328fad2](https://user-images.githubusercontent.com/5144311/78033799-40779700-733d-11ea-954c-01bc17cf14ba.jpeg)

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.3.0-dev (1176)

**Comment by riteshmaddala** [comment] 2020-08-23 20:17
Hi Team,

Any updates on this. Getting this error in Dev Environment after Cloning the latest development branch.

Thanks

**Comment by antobinary** [comment] 2021-02-03 21:34
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11270

**Closed by antobinary** 2021-02-03 21:34 UTC
Labels: HTML5 Client
