### ISSUE TITLE
Whiteboard Text Tool not working in alpha 7

### ISSUE THREAD

**Issue by 123re-book** [bigbluebutton/bigbluebutton#11555] opened 2021-03-04 14:56 UTC
Hope so. Hope I'm not boring you.

**Describe the bug**
All tools from the whiteboard tools are working except the Text / Font-tool

**To Reproduce**
When you click on the default.pdf with the text-tool selected nothing happens.

**Expected behavior**
On demo if you do so a square field selection on the document is shown where you can type your text in.

**Actual behavior**
No nothing happens when you try to write some text glyphs on the document.

$ sudo bbb-conf --check | grep BigBlueButton
Server 2.3.0-alpha6 (1642)

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser FireFox
 - Version 85.0.1

**Additional context**
Thanks a lot for your great work - stay healthy.

**Comment by everton137** [comment] 2021-03-04 15:06
I can confirm this bug on versions 2.3 alpha 6 and 2.3 alpha 7 when test on a Firefox browser (Linux and Mac).

**Comment by antobinary** [comment] 2021-03-04 15:09
Thanks for reporting this!
Sounds like a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11472 and #10774 ?
The fix should be released with 2.3-alpha8

**Closed by antobinary** 2021-03-04 15:09 UTC
Labels: HTML5 Client
