### ISSUE TITLE
Add a way to filter users

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#13646] opened 2021-11-05 05:08 UTC
A moderator needs to find a users in the list by scrolling. It would be interesting to have a filter field to make user search easier.

**Comment by prlanzarin** [comment] 2021-11-05 12:26
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/8688

**Closed by prlanzarin** 2021-11-05 12:26 UTC
Labels: type: enhancement
