### ISSUE TITLE
Rendering of poll results broken on slides in 2.3

### ISSUE THREAD

**Issue by tibroc** [bigbluebutton/bigbluebutton#11648] opened 2021-03-15 15:55 UTC
**Describe the bug**
The poll results are not correctly rendered when shown on the slides:

![screenshot](https://user-images.githubusercontent.com/39943803/111181270-18189500-85ae-11eb-9db5-2d4df5507772.png)

This behavior is neither consistent between all the users in the video conference, nor for each single user . Some don't see the poll results at all, some see them as shown in the screenshot above, and for some this problem solves itself when resizing the presentation while for others it persists throughout the meeting and some don't have this problem at all. It does not seem to depend on browser type.

**To Reproduce**
1. Do a poll
2. Open the slides
3. Resize/re-open the slides to see if problem persists 

**BBB version (optional):**
2.3-alpha-7

**Desktop (please complete the following information):**
 - several OSs with different browsers

**Comment by PhMemmel** [comment] 2021-03-15 15:58
Problem disappeared for me after the presenter shared his screen and stopped screensharing again. After that the poll results on the presentation were perfectly readable again.

**Comment by antobinary** [comment] 2021-03-15 18:17
@tibroc thanks for reporting! Do you recall zooming in/out of the presentation at all?

@PhMemmel Are you referring to the exact same session or you have observations from different sessions/servers?

I am tagging this to 2.3, we'll keep an eye on it (I have not spotted this before)

**Comment by PhMemmel** [comment] 2021-03-15 18:35
I'm referring to the same session.
Speaking for myself, I minimized/maximized the presentation a few times before this happened (I couldn't observe a correlation between this and the appearance of these strange numbers/letters, though). Minimizing/maximizing of the presentation or window resizing couldn't make it disappear for me. This only disappeared after the presenter shared his screen and stopped screen sharing again.

Sorry for not being able to provide better steps on how to reproduce.

**Comment by tibroc** [comment] 2021-03-16 08:33
For me, once resizing solved the problem, another time on a different trial it did not.

**Comment by lkiesow** [comment] 2021-03-16 20:51
We were a number of participants in this session and pretty much everyone could reproduce this occasionally regardless of browser or operating system. The problem would disappear when closing and re-opening the presentation but would also occasionally reappear later.

**Comment by schrd** [comment] 2021-04-02 10:49
I saw something similar on 2.3 Beta1 too. For some participants results were rendered correctly, for others it was broken. We tried to figure out what triggered this but there seemed to be nothing obvious to reproduce this. 

@antobinary if we get such a result again, what data can we collect so this can be tracked down? Would a DOM snapshot from the browser help? Logs from the browser console?

**Comment by pedrobmarin** [comment] 2021-08-19 14:01
We observed this issue several times when the poll is published while the user has her/his presentation not visible.

**Comment by ramonlsouza** [comment] 2021-08-23 18:01
I was not able to reproduce this issue (2.3 and 2.4).

Tested with/without cameras, with presentation hidden, zoom in/out in browser, +/- font-sizes in settings.

My guess is: we need very specific conditions for it to happen OR it is already fixed.

**Comment by pedrobmarin** [comment] 2021-08-23 18:03
Alright, thanks @ramonlsouza .

I'll let it sit here for a while before closing it.

**Comment by tibroc** [comment] 2021-08-25 07:24
@pedrobmarin we didn't observer this bug any more in stable versions of 2.3 (neither did we observe it in 2.4).

**Closed** 2021-08-25 10:31 UTC
Labels: type: defect, module: client, component: polling
