### ISSUE TITLE
Pen tool disappears when annotating documents

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5778] opened 2018-06-29 17:58 UTC
When annotating an uploaded document, the pen tool will disappear on the edges of the document.

![untitled](https://user-images.githubusercontent.com/290351/42107174-688a5a44-7ba4-11e8-8164-81304c90b423.gif)

**Comment by capilkey** [comment] 2018-06-29 18:00
Possible duplicate of #5768

**Comment by antobinary** [comment] 2018-06-29 18:07
Closing in favor of #5768

**Closed by antobinary** 2018-06-29 18:07 UTC
Labels: HTML5 Client
