### ISSUE TITLE
2.3-alpha6: Client crashes when returning audio to breakout room

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#11367] opened 2021-02-10 07:38 UTC
**Describe the bug**
Client crashes on returning audio to the breakout room

**To Reproduce**
1. Open breakout rooms
2. Stay connected via freeswitch audio in the main room
3. join the listen-only kurento audio of a breakout room via the breakout room panel: "Join Audio"
4. Click on "Return audio"
5. See error 403

**Expected behavior**
Returning audio/disconnecting audio from breakout room

**Actual behavior**
Client crashes, error 403, see section "Screenshots"

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65113153/107478880-81098900-6b7a-11eb-984e-f42b50e52ae6.png)

**BBB version (optional):**
2.3-alpha6, tested on Firefox 85.0.2 64bit on own alpha6-dev-installation and test23.bigbluebutton.org

**Comment by ffdixon** [comment] 2021-02-10 11:37
Thanks for the report.

**Comment by mariogasparoni** [comment] 2021-02-13 02:43
Possible duplicate of #11029

**Comment by mariogasparoni** [comment] 2021-02-23 15:53
@antobinary you can close this one. This is covered by #11029

**Closed** 2021-02-23 15:54 UTC
Labels: HTML5 Client
