### ISSUE TITLE
"n is null" during window resize

### ISSUE THREAD

**Issue by matiasilva** [bigbluebutton/bigbluebutton#10606] opened 2020-10-07 12:11 UTC
**Describe the bug**

When resizing the window (ie. moving it from one display to another) with the presentation area and camera on (not sure if these are needed to trigger this), the presentation area displays "n is null".

**To Reproduce**
1. Activate camera and presentation area
2. Drag client window from one display to another

**Expected behavior**
Presentation area should resize fine.

**Actual behavior**
An error is logged, refreshing works fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/23108156/95329037-41662400-089e-11eb-8998-709893088811.png)

**BBB version (optional):**
BigBlueButton Server 2.2.26, HTML5 client build 1032

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 81.0.1

**Additional context**

The console output: http://paste.debian.net/1166206/

**Comment by pedrobmarin** [comment] 2020-10-07 12:47
That error description is, by far, the best error description in BigBlueButton. I'm not sure how this gets translated to _old fashioned tuga portuguese_ but running the client using the _zueira portuguese_ this translates as `Ele estava logado. Por favor, tente recarregar a página.`. What a gem!

**Comment by matiasilva** [comment] 2020-10-29 20:15
@pedrobmarin should this be closed?

**Comment by pedrobmarin** [comment] 2020-10-29 20:23
@matiasilva I believe the resizing source of this issue is resolved but I'm sure other things might cause similar issues at the media/presentation/cameras area. Since the issue is quite direct to the resize/firefox problem I guess we can close this one.

**Closed** 2020-10-29 20:29 UTC
Labels: HTML5 Client
