### ISSUE TITLE
Add server option to enable unmute of viewers by moderators

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6814] opened 2019-02-20 14:26 UTC
There are use cases in the HTML5 client where moderators need to be able to unmute other users.  See

  https://groups.google.com/d/msg/bigbluebutton-dev/HjkhYAeA6WU/TT4owN-uBQAJ

Add a server option in settings.yml to enable a moderator in the HTML5 client to unmute other users.

**Comment by capilkey** [comment] 2019-02-20 17:17
This can't be changed in just the client. If a user tries to unmute someone else they will be ejected for permission violations. To make this configurable would require having a flag in akka-apps and in the client.

**Comment by capilkey** [comment] 2019-02-20 17:31
I see where the confusion came in. Prior to 2.2 we only had enforcement of this in the Flash client, but that isn't how it works now and we've actually removed the "moderatorUnmute" option from config.xml when we put in the server controls.

**Comment by antobinary** [comment] 2019-05-09 22:22
Duplicate of #7092

**Closed by antobinary** 2019-05-09 22:22 UTC
Labels: Enhancement
