### ISSUE TITLE
iOS speaker not correctly set

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6591] opened 2019-01-18 17:26 UTC
Likely related to #6590 
In some rare cases iPad/iPhone user on Safari joins in audio fine but cannot hear anything in the meeting.
The user _can_ hear playing of the test file in the Echo test used for testing speaker volume

**Comment by antobinary** [comment] 2019-01-18 19:12
@akiwenziec Any more details to add here?

**Comment by akiwenziec** [comment] 2019-01-18 19:17
Additionally the user cannot hear themselves during the echo test - if they select yes the audio joins and their mic transmits but they cannot hear audio from the meeting.

**Comment by gustavotrott** [comment] 2019-01-21 15:43
Hello @akiwenziec , do you know if the clients that have this problem. If they have the problem always or if has a randomic behavior, sometimes just refresh the page and the sound works well. Do you know?

It would be very helpful if you have a little more information about some case with this problem:
- Device model
- ios version
- Internet Connection (Wireless or 3g/4g)

This details would be important because if I can reproduce the problem here, it will be much easier to fix.

**Comment by boblmartens** [comment] 2019-08-09 16:03
I am actually hitting up against this exact thing with my iOS setup as well. iPhone 7 with iOS 12.4 and iPad Pro 9.7" with iOS 12.4. I am wondering what has been found out about this.

**Comment by boblmartens** [comment] 2019-09-25 19:17
Still seeing the speaker issue where mic works, webcam works, but audio from the call itself (and during the echo test) does not work. This is on an iPad pro 9.7" with iPadOS 13.1.

**Comment by zagzam** [comment] 2020-01-06 09:00
I have the same exact problem where my mic and webcam works, but I can't hear any audio, either from another user or my own (echo test).

I'm using iPad Air 2019 on iPadOS 13.3 using WiFi network.

**Comment by shashwatadi** [comment] 2020-03-01 11:59
Same problem for iPad iOS version 13.1.2

**Comment by ffdixon** [comment] 2020-03-01 13:08
We've been working on some updates to address this iOS audio issue and would be very interested if you could test with

  https://demo.bigbluebutton.org/

and let us know if it now works.

**Comment by shashwatadi** [comment] 2020-03-01 14:17
Sure, thanks a lot for the prompt response as usual Fred :)

**Comment by ffdixon** [comment] 2020-03-01 14:53
@shashwatadi looking forward to hearing the results of your testing.  What made this problem difficult to resolve is none of our iOS devices exhibited the problem.  By working with the community, we were able reproduce this issue and get enough logging to (hopefully) fix.

**Comment by shashwatadi** [comment] 2020-03-01 17:45
Looks like it is working fine on https://demo.bigbluebutton.org/ 

Anything that we need to do from our end to integrate these changes to our instance of bigbluebutton?

**Comment by ffdixon** [comment] 2020-03-01 21:49
Thanks for the feedback.  These fixes for iOS audio will be included in the next update to BigBlueButton 2.2-RC (coming soon).

**Comment by germeier** [comment] 2020-04-08 22:30
Hi there!

I am hitting this bug under very specific circumstances. Background: I am new to bigbluebutton and just setup an instance for my girlfriend to help her teaching her classes during "corona times".

OS: Ubuntu 16.04.6 LTS, installed via bbb-install.sh with a Let's Encrypt certificate

Client: iPad Air 2, iOS 13.4.1, connected via wifi

Creating and joining a room works a expected. Creating and joining a breakout room also works as expected. The breakout room opens in a new tab in safari.

After closing the breakout room (and the corresponding tab) and re-joining the main room, I am unable to hear my voice during the echo test. The test sound plays just fine. After re-joining the room, I can enable the microphone and camera. Other room members can see and hear me but I am unable to hear anything from the room.

I was also able to trigger this bug if i change the window and open the settings app and then return to the bigbluebutton room.

I tried a lot of things to enable the audio again but nothing works. Even a reload of the tab does not bring the audio back. The only "fix" I found was to copy the location from the location bar, close the tab and then open the room in a new tab.

Other platforms, tested on my laptop with Ubuntu 18.04.4 and firefox, were not affected.

The usage scenario here is a class of 20 to 25 pupils with most of them using iPads so any help fixing this bug is greatly appreciated.

**Comment by jtaynl** [comment] 2020-05-08 14:58
> Hi there!
> 
> I am hitting this bug under very specific circumstances. Background: I am new to bigbluebutton and just setup an instance for my girlfriend to help her teaching her classes during "corona times".
> 
> OS: Ubuntu 16.04.6 LTS, installed via bbb-install.sh with a Let's Encrypt certificate
> 
> Client: iPad Air 2, iOS 13.4.1, connected via wifi
> 
> Creating and joining a room works a expected. Creating and joining a breakout room also works as expected. The breakout room opens in a new tab in safari.
> 
> After closing the breakout room (and the corresponding tab) and re-joining the main room, I am unable to hear my voice during the echo test. The test sound plays just fine. After re-joining the room, I can enable the microphone and camera. Other room members can see and hear me but I am unable to hear anything from the room.
> 
> I was also able to trigger this bug if i change the window and open the settings app and then return to the bigbluebutton room.
> 
> I tried a lot of things to enable the audio again but nothing works. Even a reload of the tab does not bring the audio back. The only "fix" I found was to copy the location from the location bar, close the tab and then open the room in a new tab.
> 
> Other platforms, tested on my laptop with Ubuntu 18.04.4 and firefox, were not affected.
> 
> The usage scenario here is a class of 20 to 25 pupils with most of them using iPads so any help fixing this bug is greatly appreciated.
> 
> Update: I can also trigger this bug on https://demo.bigbluebutton.org/
> => enter room => enter breakout room => leave breakout room and re-enter initial room => no audio

Same here we are also facing the exact same issue when leaving the Breakout Room and re-enter the initial room via Safari browser on iPad and iPhone. And no matter how many times we refresh the page and re-enter no one can hear each another. The only workaround is to have the existing tab closed and then open the initial room in a new tab. Is there something that we missed out? We are using BBB v2.2.9.

**Comment by ffdixon** [comment] 2020-05-19 03:29
Loosing audio in Safari when returning back from the breakout rooms is an issue with the recent versions if Safari and Safari Mobile.  See https://github.com/bigbluebutton/bigbluebutton/issues/8857.

>  only workaround is to have the existing tab closed and then open the initial room in a new tab. Is there something that we missed out? We are using BBB v2.2.9.

That's the workaround for the moment.

**Comment by jtsre** [comment] 2020-06-03 21:00
Could not maintain audio connection on iOS 13.5.1 on iPhone MT6j2ll/a. And that is the very limited instances I could get audio to come through, all but 2 attempts over the last few hours, I couldld not get any audio on my iPhone. I joined the same conference with my iPad Pro and had no issues. When joining listen only I could not get it to load the audio at all. The bbb audio messages "you are muted etc" came through, but not the audio stream of the presenter. Video loaded fine. Everything else working as expected. When I enabled microphones, I was able to get the audio to play once or twice but only briefly before it went silent again. We first experienced the problem on our server, but then tried with demo.bigbluebutton.org which found the above results.

**Comment by jtsre** [comment] 2020-07-08 20:40
The only way I have been able to get this to work on my above referenced iPhone is by allowing mic access for learners. Our classes are more lecture style and the chat serves as a great way to communicate one too many. Having 50 people all on the mic simultaneously would be a nightmare. Not being able to say our courses are mobile compatible is a major detractor for us compared to our competition. If anyone knows how to fix this, we are will to pay for the solution!

**Comment by pedropalitot** [comment] 2020-09-03 18:55
Hello,
I’m having the same problem with bigbluebutton video calls on safari
I’m using an Ipad 6th gen. with ipadOS 13.6.1

When I get to the call, I make the mic. testing and sometimes i can hear myself  and sometimes it doesn’t work at all. Usually, when I can’t hear myself The audio from the teacher or anyone in the room won’t work (for me only).
A few times when I refresh the page it comes back to how it should be (but it’s not a certain thing).

I wonder if there’s an app or something that will make my experience much better.

Thanks,
Pedro

**Comment by hombit** [comment] 2020-09-07 10:55
I have the same issue with iOS 13.6, iPadOS 13.6 and macOS 10.15.6

**Comment by amiivice** [comment] 2020-09-09 05:14
Hi! have the same issue with iPadOS 13.6.1...at first attempt I can join audio and successfully echo test, but after a couple minutes or when I attempt to attach earphones, audio cuts out completely and I cannot ever hear it again. At this point I am using my iPhone 7 to listen in and my iPad Pro 2018 to watch.

**Comment by Aidagh98** [comment] 2021-01-17 06:51
I have the same exact problem where my mic and webcam works, but I can't hear any audio from another user , Sometimes i hear myself During echo test, sometime I don’t. 
on iOS 13.7 on iPhone MT962LL/A
i’m having real problems, because i can’t attend my exams, help me please.

**Comment by mariogasparoni** [comment] 2021-06-01 18:18
@Aidagh98 , please try again in latest release (2.2.31) and open a new issue with your info , if this problems happens with this version.

This should be fixed with the changes done in audio-manager and SIP.js (2.2.28+)

@antobinary , i believe this can be closed. We can handle the problem reported here on a different issue.

**Closed** 2021-06-01 18:32 UTC
Labels: module: client, status: verify
