### ISSUE TITLE
2.6 HTML5 Client Crashes when Sharing Video

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#16079] opened 2022-12-01 10:54 UTC
Using 2.6-beta1, if you join a meeting in a Firfox incognito windowand try sharing your webcam the whole client crashes. We could confirm this with multiple testers, devices and installations.

![Screenshot from 2022-12-01 11-47-55](https://user-images.githubusercontent.com/1008395/205034688-f296c517-2c6e-4e7a-98b5-8a42f2537bae.png)

```
[11:47:40:0006] DEBUG: clientLogger: Enumerate devices came back. There are 3 devices and 1 are video inputs https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2…e31900c091f70ac793355.js?meteor_js_resource=true:432:1256160 59dfa324aef2b6dd3a4e31900c091f70ac793355.js:139:65128
[11:47:40:0757]  WARN: clientLogger: Error on load custom backgrounds from IndexedDB: undefined https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2…e31900c091f70ac793355.js?meteor_js_resource=true:432:1244299 59dfa324aef2b6dd3a4e31900c091f70ac793355.js:139:65128
[11:47:40:0768]  INFO: clientLogger: Camera feed stop requested. Role viewer, restarting false https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2…4e31900c091f70ac793355.js?meteor_js_resource=true:432:455060 59dfa324aef2b6dd3a4e31900c091f70ac793355.js:139:65128
TypeError: t.backgrounds.forEach is not a function
    d https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    La https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    useReducer https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:37
    c https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    Oa https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    gs https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    Al https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    ru https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    tu https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    eu https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    Ul https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    Fo https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    unstable_runWithPriority https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:79
    bo https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    Fo https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    yo https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    Hl https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    ns https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    u https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    a https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    r https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    l https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    u https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    g https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:106
    m https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:106
    C https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:106
    B https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    du https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    unstable_runWithPriority https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:79
    bo https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    lu https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    su https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    A https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:79
    onmessage https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:79
    e https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:79
    g https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    n https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    t https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    e https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:70
    g https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    n https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    t https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    e https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    g https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    n https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    t https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    e https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:52
    g https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    n https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    o https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:9
    e https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    g https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    n https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    t https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    <anonymous> https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
59dfa324aef2b6dd3a4e31900c091f70ac793355.js:61:82896
[11:47:40:0852] ERROR: clientLogger: TypeError: t.backgrounds.forEach is not a function https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2…e31900c091f70ac793355.js?meteor_js_resource=true:432:1633474 59dfa324aef2b6dd3a4e31900c091f70ac793355.js:139:65128
Uncaught TypeError: t.backgrounds.forEach is not a function
    d https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    La https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    useReducer https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:37
    c https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    Oa https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    gs https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    Al https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    ru https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    tu https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    eu https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    Ul https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    Fo https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    unstable_runWithPriority https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:79
    bo https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    Fo https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    yo https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    Hl https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    ns https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    u https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    a https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    r https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    l https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    u https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    g https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:106
    m https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:106
    C https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:106
    B https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    du https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    unstable_runWithPriority https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:79
    bo https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    lu https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    su https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    A https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:79
    onmessage https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:79
    e https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:79
    g https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    n https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    t https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    e https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:70
    g https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    n https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    t https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    e https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:61
    g https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    n https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    t https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    e https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:52
    g https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    n https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    o https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:9
    e https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
    g https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    n https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    t https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:7
    <anonymous> https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2b6dd3a4e31900c091f70ac793355.js?meteor_js_resource=true:432
59dfa324aef2b6dd3a4e31900c091f70ac793355.js:432:1242731
[WASM] Loading model of size: 407248 tflite-simd.js:20:11140
INFO: Created TensorFlow Lite XNNPACK delegate for CPU. tflite-simd.js:20:11140
[11:47:41:0266] ERROR: clientLogger: Failed to toggle virtual background: HTMLCanvasElement.captureStream: Argument 1 is not a finite floating-point value. https://webconf62.uni-osnabrueck.de/html5client/59dfa324aef2…e31900c091f70ac793355.js?meteor_js_resource=true:432:1261350 59dfa324aef2b6dd3a4e31900c091f70ac793355.js:139:65128
XHRPOSThttps://webconf62.uni-osnabrueck.de/html5log
[HTTP/2 404 Not Found 21ms]

Browser Bunyan: A server log write failed 59dfa324aef2b6dd3a4e31900c091f70ac793355.js:139:68059

```

**Comment by antobinary** [comment] 2022-12-01 13:42
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/16065

**Closed** 2022-12-01 13:43 UTC
Labels: module: client, type: bug
