### ISSUE TITLE
Moderator lowering hand from toast broken

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#18815] opened 2023-09-21 01:06 UTC
**Describe the bug**
Can't lower users' hand from the toast.

**To Reproduce**
1. Join a meeting as moderator
2. Join the meeting also as a viewer.
3. The viewer raises hand via the action bar reactions.
4. The moderator sees a toast about the raised hand. Hovers over it, the message reads "Lower V's hand". Clicks on it.

**Expected behavior**
V's hand is lowered.

**Actual behavior**
V's hand remains raised.

**Screenshots**
![Screenshot from 2023-09-20 21-01-16](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/584defe3-e1ea-4ff8-b54f-7c7a7ca46f00)

**BBB version:**
BigBlueButton 2.7.1

**More**
First reported in https://groups.google.com/g/bigbluebutton-dev/c/RbpJG4PLpLk

**Comment by vasylOstrovskyi** [comment] 2023-09-26 08:48
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/18698 ?

**Closed** 2023-10-23 14:41 UTC
Labels: module: client
