### ISSUE TITLE
Building RPM packages of BigBlueButton

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#10971] opened 2020-12-05 19:06 UTC
I would like to package BigBlueButton in RPM.

Why I want to do it?
The main reason is that I want to deploy it via packages, but I cannot rebuild original deb packages and cannot controbute to BBB due to that.

I prefer building and maintanining RPM, not deb, and would like to do it in rosa2019.1 distro in contrib repository. Building for a distro repo means that:
* builds must not require network (I think it will require some work in case of BBB)
* builds must be reprodisble
* builds must be fully automatic
* packages must be of a rather high quality
* `/usr/local` should not be used

Right now the process how you get official deb packages is not clear.

For example, `bbb-apps-akka`.
Do I inderstand correctly that `sbt debian:packageBin` is run in https://github.com/bigbluebutton/bigbluebutton/blob/develop/akka-bbb-apps/Dockerfile ? Then you get a deb package and copy it into your repository?

What about, for example, `bbb-html5`?
I can't find anything about deb packaging in https://github.com/bigbluebutton/bigbluebutton/tree/develop/bigbluebutton-html5

Then what about freeswitch, for example?

Could you please describe the process of building BigBlueButton from source?
Documentation tells to install from source on top of deb packages, it is not full build from source, I do not know how much will be used from installed deb packages.

Thanks!

**Comment by basisbit** [comment] 2020-12-10 01:50
partial duplicate of #8978 and #8876 . Definitely a duplicate of #8956 and #1379 . Please next time use the search before opening new issues. Thank you.

Any help for writing new scripts/tools/configuration that can build bigbluebutton packages AND which can be published would be very welcome!

**Closed by basisbit** 2020-12-10 01:50 UTC
Labels: Enhancement, Packaging
