### ISSUE TITLE
When microphone is blocked everything disappears

### ISSUE THREAD

**Issue by nikos-pappas** [bigbluebutton/bigbluebutton#11433] opened 2021-02-19 09:49 UTC
**Describe the bug**
When joining a room and browser has blocked the microphone or microphone cannot be found the whole interface goes black.

**To Reproduce**
1. Block microphone in browser
2. Join a meeting room
3. Press button "Join with microphone"
4. Everything disappears 
**Expected behavior**
Previous versions showed a popup error window message
**BBB version (optional):**
BigBlueButton Server 2.3.0-alpha6 (1573)

**Desktop (please complete the following information):**
 - OS: Windows, Mac
 - Browser: Chrome 
 - Version Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by mariogasparoni** [comment] 2021-02-19 18:32
Thanks for you reporting @nikos-pappas , but i am not able to reproduce it.
Tested on same browser/os as your, and also on chrome/ubuntu-focal.

Here are the steps i did: 
![screen](https://user-images.githubusercontent.com/1780868/108545702-e40bc600-72c6-11eb-8007-76646c1eb0db.gif)

**Comment by nikos-pappas** [comment] 2021-02-22 16:07
That's strange because this is happening to other browsers (Firefox and Edge). Maybe something is wrong in my configuration. I will try also to upgrade to alpha-7 to see if it persists.
I attach a video with what I am experiencing. 

https://user-images.githubusercontent.com/74572602/108735069-c6459780-7538-11eb-815d-f0624340380c.mp4

Thank you

**Comment by mariogasparoni** [comment] 2021-02-22 16:35
Sure, could you please also test it on test23.bigbluebutton.org ? This server is running current bbb2.3-alpha7

**Comment by nikos-pappas** [comment] 2021-02-22 16:52
Yes I tested with your server and everything works fine!  I will upgrade as soon as possible. 
Thanks for your help

**Comment by mariogasparoni** [comment] 2021-02-22 16:55
You are welcome. Please, close this issue as soon as you confirm upgrading to alpha7 solves it for you.

**Comment by nikos-pappas** [comment] 2021-03-16 08:59
I 've just upgrade my system to alpha8. The above issue is resolved.. 
Congrats all contributors for this great project

**Comment by nikos-pappas** [comment] 2021-03-22 12:28
I am reopening this issue since it exists in alpha8 with specific configuration.
If I set to true the mutedAlert (very useful feature) in settings.yml:
...
 mutedAlert:
      enabled: true
...
then when you try to join a session with microphone and this is blocked by the browser the whole UI disappears as shown in my screencast at previous post.

BigBlueButton Server 2.3.0-alpha8 (1797) in Windows, Browsers: Chrome/Edge/Firefox

**Closed** 2021-03-23 17:48 UTC
Labels: HTML5 Client
