### ISSUE TITLE
youtube video sharing at Presenter reconnection no synchronization

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8123] opened 2019-09-16 19:01 UTC
Hey guys,
just connect from two browser tabs, start sharing youtube video and refresh the page
at your reconnection as a Presenter, there is no interval synchronization

![zzzzz](https://user-images.githubusercontent.com/33185490/64985229-cac54580-d89a-11e9-9c46-d86ad81b16d9.gif)

**Comment by lfzawacki** [comment] 2019-09-16 21:03
I've arrived at the conclusion this is a WONTFIX for me. Right now the html5 client does not store any state about the video playing, it just follows the presenter. This means that refreshing the page as presenter will reset the video back to the beginning, as it would happen if you were watching it on YouTube and refreshed the page.

This is by design. We sync the state using Meteor Streamer so that we don't need to push object updates to all clients every second and don't tax the html5 clilent if we happen to be syncing several concurrent users. The fix for this would involve storing the current time in an object and I'm not sure it's worth it just for this edge case.

**Closed** 2021-04-04 12:02 UTC
Labels: HTML5 Client, status: wontfix
