### ISSUE TITLE
mongod service fails to restart

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#6413] opened 2018-12-17 10:05 UTC
We have seen the `mongod` failing to start in the following tow cases:

1. Manually updating the server using `apt-get dist-upgrade`.
2. Having a cron for rebooting the server daily.

**Comment by ffdixon** [comment] 2018-12-17 12:41
Thanks for pointing this out Ghazi -- we need to fix this in 2.0 before we ship the final version.

**Comment by s-at-dq** [comment] 2019-01-15 09:01
Can it be that this is a typo in the BigBlueButton source code somewhere? I also have the problem that "mongod" isn't starting. bbb-config --status tells me that mongod is inactive, but systemd doesn't know of a service named "mongod":

    :~# service mongod start
    Failed to start mongod.service: Unit mongod.service not found.
    :~# service mongod status
    service mongod status
    ● mongod.service
       Loaded: not-found (Reason: No such file or directory)
       Active: inactive (dead)

The service "mongodb" however is known to systemd:

    :~# service mongodb start
    :~# service mongodb status
   ● mongodb.service - An object/document-oriented database
       Loaded: loaded (/lib/systemd/system/mongodb.service; enabled; vendor preset: enabled)
       Active: active (running) since Tue 2019-01-15 09:43:16 CET; 13s ago
         Docs: man:mongod(1)
     Main PID: XXXXX (mongod)
        Tasks: 10
       Memory: XX.XM
          CPU: 58ms
       CGroup: /system.slice/mongodb.service
               └─XXXXX /usr/bin/mongod --config /etc/mongodb.conf

**Comment by s-at-dq** [comment] 2019-02-25 16:00
Any news regarding this bug?

**Comment by ffdixon** [comment] 2019-02-25 17:59
We've fixed this in 2.2-dev and just ported back the fixes to 2.0.  It will be in the next update to BigBlueButton 2.0 (to be released shortly).

**Closed by ffdixon** 2019-02-25 17:59 UTC

**Comment by s-at-dq** [comment] 2019-03-08 14:15
Is there a plan when the next BigBlueButton 2.0 version is going to be released?

**Comment by hettipeti** [comment] 2019-04-23 19:33
The problem is the broken parameter options for the mongo deamon. Therefore mongodb will not start.
It doesn't start because of **Unrecognized option: storage.wiredTiger.indexConfig.prefixCompression**

`xxx@bigbluebutton:~$ systemctl status mongod
● mongod.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/etc/systemd/system/mongod.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-04-23 21:26:53 CEST; 18s ago
     Docs: https://docs.mongodb.org/manual
  Process: 3632 ExecStart=/usr/bin/mongod --config /usr/share/meteor/bundle/mongo-ramdisk.conf --oplogSize 8 --replSet rs0 --noauth --nojournal (code=exited, status=2)
  Process: 3620 ExecStartPre=/usr/share/meteor/bundle/mongod_start_pre.sh (code=exited, status=0/SUCCESS)
 Main PID: 3632 (code=exited, status=2)

Apr 23 21:26:53 bigbluebutton systemd[1]: Starting High-performance, schema-free document-oriented database...
Apr 23 21:26:53 bigbluebutton systemd[1]: Started High-performance, schema-free document-oriented database.
Apr 23 21:26:53 bigbluebutton mongod[3632]: Unrecognized option: storage.wiredTiger.indexConfig.prefixCompression
Apr 23 21:26:53 bigbluebutton mongod[3632]: try '/usr/bin/mongod --help' for more information
Apr 23 21:26:53 bigbluebutton systemd[1]: mongod.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 23 21:26:53 bigbluebutton systemd[1]: mongod.service: Unit entered failed state.
Apr 23 21:26:53 bigbluebutton systemd[1]: mongod.service: Failed with result 'exit-code'.
`

trying to temp fix it.

**Comment by amirazad1** [comment] 2020-08-11 06:28
Hello,
I receive 404 Not Found when Start room

root@ubuntu-bbb:~# bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✘ - failed]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

root@ubuntu-bbb:~# bbb-conf --restart
mongod failing to start 

root@ubuntu-bbb:~# systemctl status mongod.service
● mongod.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/etc/systemd/system/mongod.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-08-11 06:14:55 UTC; 13min ago
     Docs: https://docs.mongodb.org/manual
  Process: 7080 ExecStartPre=/usr/share/meteor/bundle/mongod_start_pre.sh (code=exited, status=217/USER)

Aug 11 06:14:55 ubuntu-bbb systemd[1]: Starting High-performance, schema-free document-oriented database...
Aug 11 06:14:55 ubuntu-bbb systemd[1]: mongod.service: Control process exited, code=exited status=217
Aug 11 06:14:55 ubuntu-bbb systemd[1]: Failed to start High-performance, schema-free document-oriented database.
Aug 11 06:14:55 ubuntu-bbb systemd[1]: mongod.service: Unit entered failed state.
Aug 11 06:14:55 ubuntu-bbb systemd[1]: mongod.service: Failed with result 'exit-code'.

What's my problem?

**Comment by amirho3inhashemi** [comment] 2020-08-11 08:59
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✘ - failed]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

root@meet:~# systemctl status mongod.service
● mongod.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/etc/systemd/system/mongod.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-08-11 08:59:19 UTC; 4s ago
     Docs: https://docs.mongodb.org/manual
  Process: 17530 ExecStartPre=/usr/share/meteor/bundle/mongod_start_pre.sh (code=exited, status=217/USER)

Aug 11 08:59:19 meet systemd[1]: Starting High-performance, schema-free document-oriented database...
Aug 11 08:59:19 meet systemd[1]: mongod.service: Control process exited, code=exited status=217
Aug 11 08:59:19 meet systemd[1]: Failed to start High-performance, schema-free document-oriented database.
Aug 11 08:59:19 meet systemd[1]: mongod.service: Unit entered failed state.
Aug 11 08:59:19 meet systemd[1]: mongod.service: Failed with result 'exit-code'.

What's my problem?

**Comment by ffdixon** [comment] 2020-08-11 10:25
@amirho3inhashemi Can you post this to bigbluebutton-setup mailing list (see https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton).

**Comment by shaikhreza43** [comment] 2020-09-30 11:57
● mongod.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/etc/systemd/system/mongod.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-09-30 11:56:33 UTC; 5s ago
     Docs: https://docs.mongodb.org/manual
  Process: 32257 ExecStart=/usr/bin/mongod --config /usr/share/meteor/bundle/mongo-ramdisk.conf --oplogSize 8 --replSet rs0 --noauth --nojournal (code=exited, status=1/FAILURE)
  Process: 32244 ExecStartPre=/usr/share/meteor/bundle/mongod_start_pre.sh (code=exited, status=0/SUCCESS)
 Main PID: 32257 (code=exited, status=1/FAILURE)

Sep 30 11:56:33 ip-10-0-0-201 systemd[1]: Starting High-performance, schema-free document-oriented database...
Sep 30 11:56:33 ip-10-0-0-201 systemd[1]: Started High-performance, schema-free document-oriented database.
Sep 30 11:56:33 ip-10-0-0-201 systemd[1]: mongod.service: Main process exited, code=exited, status=1/FAILURE
Sep 30 11:56:33 ip-10-0-0-201 systemd[1]: mongod.service: Unit entered failed state.
Sep 30 11:56:33 ip-10-0-0-201 systemd[1]: mongod.service: Failed with result 'exit-code'.

**Comment by matiasilva** [comment] 2020-09-30 13:27
Please do not revive an old issue. Please also just don't paste code or errors and expect people to magically know how to help you. Follow the established guidelines for getting help.
