### ISSUE TITLE
error for large number of sessions and high engagement

### ISSUE THREAD

**Issue by burakguder** [bigbluebutton/bigbluebutton#11090] opened 2020-12-29 09:58 UTC
I use a very powerful server. But I cannot reach even 50% efficiency.  

After 500 contacts, html5 page hangs in three spots and won't open. It takes a long wait to login. It is almost impossible to share after logging in. Most users are getting kicked out of the system or the meeting crashes completely

Some settings made on the server:
---Ulimit --

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 514949
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 131072
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 131072
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Freeswitch PORT
```
    <param name="rtp-start-port" value="9384"/> 
    <param name="rtp-end-port" value="32767"/>
```

Kurento PORT  :
```
minPort=32769
maxPort=65535
```

Limits: 
```

* soft     nproc          131072
* hard     nproc          131072
* soft     nofile         131072
* hard     nofile         131072
root soft     nproc          131072
root hard     nproc          131072
root soft     nofile         131072
root hard     nofile         131072
nginx soft     nproc          131072
nginx hard     nproc          131072
nginx soft     nofile         131072
nginx hard     nofile         131072
www-data soft     nproc          131072
www-data hard     nproc          131072
www-data soft     nofile         131072
www-data hard     nofile         131072

kurento soft     nproc          131072
kurento hard     nproc          131072
kurento soft     nofile         131072
kurento hard     nofile         131072

freeswitch soft     nproc          131072
freeswitch hard     nproc          131072
freeswitch soft     nofile         131072
freeswitch hard     nofile         131072

bigbluebutton soft     nproc          131072
bigbluebutton hard     nproc          131072
bigbluebutton soft     nofile         131072
bigbluebutton hard     nofile         131072

tomcat8 soft     nproc          131072
tomcat8 hard     nproc          131072
tomcat8 soft     nofile         131072
tomcat8 hard     nofile         131072
```

Nginx Conf
```
worker_processes auto;
worker_rlimit_nofile    200000;
pid /run/nginx.pid;

events {
    worker_connections 131072;
    use epoll;
    multi_accept on;
        # multi_accept on;
}

```

I added link to download all report files: 
https://we.tl/t-YnQBpiPmRW

Number of rooms and participant types

![console2](https://user-images.githubusercontent.com/560147/103275357-0d9a2680-49d5-11eb-85a1-ad891c28589d.png)

server network output 60 Mbit

Server CPU

![console](https://user-images.githubusercontent.com/560147/103275464-45a16980-49d5-11eb-83c2-b6c438277691.png)

**Comment by burakguder** [comment] 2020-12-29 12:00
additional information : 
bbb 2.2.30
```

ii  bbb-apps                               1:2.2.0-50                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                          2.2.0-96                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                   1:2.2.0-50                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                           1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                         1:2.2.0-48                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast               1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                             1:2.2.0-40                                      amd64        BigBlueButton Flash client
ii  bbb-config                             1:2.2.0-225                                     amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                           1:2.2.0-63                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                    2:2.2.0-113                                     amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                  1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                         2.2.0-72                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                              1:2.2.0-1095                                    amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                            1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation              1:2.2.0-33                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                        1:2.2.0-71                                      amd64        BigBlueButton record and playback
ii  bbb-red5                               1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                     2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                                1:2.2.0-148                                     amd64        BigBlueButton API
ii  bbb-webrtc-sfu                         1:2.2.0-108                                     amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                          1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                 7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                     7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                     7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                      7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                            0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                      7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for image scaling and various conversions - runtime files

```

+ When these crashes occurred, some users started appearing more than 1 in the list.

**Comment by ffdixon** [comment] 2020-12-29 13:45
> I am ready to do whatever I can.

If you feel bold, you can try running 2.3-alpha4 on a production server with multiple nodejs processes enabled.  Let us know if that does a better job of scaling to a higher number of users.

**Comment by burakguder** [comment] 2020-12-29 14:08
quite risky to run this test with real users. We need to prepare a new server for this test and tell users that it is a test. after i do this test, i will share the whole report with you.  

As for my other questions. Is it now possible to have multiple bbb-html5 for stable bbb version? I can test this faster, and share the report.

**Comment by ffdixon** [comment] 2020-12-29 15:06
> As for my other questions. Is it now possible to have multiple bbb-html5 for stable bbb version? I can test this faster, and share the report.

It is not -- that work is only happening in 2.3-dev.

**Comment by burakguder** [comment] 2020-12-29 15:39
I currently have a 2.3-dev install on an 8 core server.  I see that many errors I have encountered before have been fixed. 
After general error and device checks, I will take a risk and do a 600-person trial.

**Comment by basisbit** [comment] 2020-12-29 18:34
Closing this because it is a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/10739
Please especially read the last comment of that issue thread.
Also, please do not create new issues just because of whatever happens to be the current limit, there will always be some vertical scaling limit.
You can keep using this issue for discussing and especially also for reporting your experience / user limit for 2.3.x. Thank you for helping!

**Closed by basisbit** 2020-12-29 18:34 UTC
