### ISSUE TITLE
user  gets ICE 1004 error when connecting with microphone in android mobile/tablet in chrome,We are Currently using BBB stable release-version 2.4

### ISSUE THREAD

**Issue by bharath-k99** [bigbluebutton/bigbluebutton#14136] opened 2022-01-19 09:19 UTC
**Describe the bug**
When the user tries to join the audio in android mobile/tablet with Chrome especially in android 11, everytime user will get a "Failure on call (reason=ICE error) (error 1004)" error after allowing their browser to share the microphone .

**To Reproduce**
1. Make sure that the BigBlueButton server HTML5 client settings 
    (/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml) has 
    public.app.skipCheck set to true (this instructs the HTML5 client to skip the EchoTest)

2. Join a meeting from a browser that has not been allowed to share the microphone 
   with it

3. Choose to join with microphone

4. Allow the browser to use your microphone

5. See error

**Expected behavior**
   Audio conference should be joined without problems.

**Actual behavior**
   A "Failure on call (reason=ICE error) (error 1004)" error is presented to the user,when 
   pushing neither "Microphone" or "Listen only"

**Screenshots**
![WhatsApp Image 2021-12-20 at 10 45 44 AM](https://user-images.githubusercontent.com/58478098/150101651-81900394-7e70-454b-b98e-852c1465b18d.jpeg)

**Smartphone **
 - Device: Android Mobile/tablets...
 - OS: Android 11
 - Browser chrome
 - Version [96.0.4]

**Comment by spreeni151** [comment] 2022-01-19 10:07
Which BBB version did you use? 2.4.2?

**Comment by bharath-k99** [comment] 2022-01-19 10:12
> Which BBB version did you use? 2.4.2?

No,we have used 2.4.0

**Comment by spreeni151** [comment] 2022-01-19 10:33
I tried our 2.4.0 server and the actual 2.4.2 version on another machine. My smartphone is Android 10, it works without problems. Can you try the BBB-Testserver test24.bigbluebutton.org to make sure it's not your server installation?

**Comment by bharath-k99** [comment] 2022-01-19 10:37
> I tried our 2.4.0 server and the actual 2.4.2 version on another machine. My smartphone is Android 10, it works without problems. Can you try the BBB-Testserver test24.bigbluebutton.org to make sure it's not your server installation?

https://test.bigbluebutton.org/ yes i had tried the demo test and still its giving same error in android 11 mobile/tablet

**Comment by spreeni151** [comment] 2022-01-19 10:43
So this can be a problem with Android 11. Unfortunately I don't have any A11 devices, can someone else check?

**Comment by prlanzarin** [comment] 2022-01-19 12:26
This is most probably a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/13008.
Which points to a Chrome+Androind|Samsung issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1240237.

Recommend the affect users to use Firefox until Chromium doesn't fix it.

**Closed by prlanzarin** 2022-01-19 12:26 UTC
Labels: module: core
