### ISSUE TITLE
Hide presentation for viewers

### ISSUE THREAD

**Issue by meaz** [bigbluebutton/bigbluebutton#9347] opened 2020-04-30 05:31 UTC
Hi,

as a moderator, it would be nice to be able to hide the presentation for viewers. At the moment, the viewer has to do ii himself. It would make things easier for moderators to be able to handle this.

**Comment by YoniMeidan** [comment] 2020-05-18 09:07
Yes this is needed. Also the ability to disable presentation as we are not using this feature at all.

**Comment by AInteriorB** [comment] 2020-12-10 12:59
So many related issues but nothing is happening here ... #7987

**Comment by prlanzarin** [comment] 2020-12-10 13:03
Duplicate of #7987

**Closed by prlanzarin** 2020-12-10 13:03 UTC
