### ISSUE TITLE
Create live push ability

### ISSUE THREAD

**Issue by rfakit** [bigbluebutton/bigbluebutton#13098] opened 2021-08-30 11:08 UTC
I thinks if you add sth to push live class to nginx rtmp inorder to make it as live stream class, that would be a blast feature.
hope you add this one to next update

**Comment by GhaziTriki** [comment] 2021-08-31 01:10
@rfakit Do you find what you need in https://github.com/bigbluebutton/bigbluebutton/issues/8295?

**Comment by prlanzarin** [comment] 2021-08-31 01:36
Duplicate of #8295

**Closed by prlanzarin** 2021-08-31 01:36 UTC
Labels: type: enhancement
