### ISSUE TITLE
[2.4-beta-3] - Breakout room invitation bug

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#13022] opened 2021-08-17 21:03 UTC
**Describe the bug**
Sometimes, the Attendee doesn't receive the breakout room invite. Has the possibility of the Moderator cannot generate the URL to join in a room if this happens (I don't see any error log). I can only reproduce this NOT allowing users to choose a room.

_Obs:. When the invitation works, it's taking longer than usual_ 

**To Reproduce**
1. Join with a moderator and a attendee;
2. Create the breakout rooms;

**Video**

https://user-images.githubusercontent.com/56703993/129798523-99b556a0-0555-4e5b-a974-16e62cd94f0e.mp4

**Comment by pedrobmarin** [comment] 2021-08-17 21:06
v2.4?

**Comment by antonbsa** [comment] 2021-08-17 21:14
> v2.4?

Yes! I couldn't reproduce this in v2.3

**Comment by pedrobmarin** [comment] 2021-08-17 21:15
I think this might be solved on our next merge

**Comment by spreeni151** [comment] 2021-09-02 10:41
I don't know if this is the same bug or a new one, but it seems to be very similar. I realized this behavior in 2.3.12 and 2.3.13:
The manual breakout room invitation, with which a Moderator can direct a user to a breakout room is not working (look at video). On the other hand a user is able to choose a room for himselb, so the room links seem to work.
[Video](https://www.mir-studios.de/breakoutinvitation.mp4)

**Comment by PhMemmel** [comment] 2021-09-02 12:06
I can observe the following behavior in 2.3.13:

1. Mod opens breakout rooms for the first time, assigns user1 to room1
2. Modal appears as it's supposed to, user1 just closes modal
3. Mod: Reopening breakout room window and moving user1 to room2
4. Modal appears as it's supposed to, user1 just closes modal
5. From now whenever the moderator tries to reassign the user to a room he already just closed the invitation modal for the invitation modal doesn't pop up.
6. Shutting down alle breakout rooms and creating new ones make the modal again appear when moving user to a specific breakout room. See steps 1 to 5

@spreeni151 Is it possible that this is the exact problem you are experiencing or do you encounter even more cases in which the modal doesn't pop up?

BTW: Sometimes the invitation modal takes a really long time (up to 10s).

**Comment by PhMemmel** [comment] 2021-09-02 12:11
Can observe the same bug in 2.4 latest with an additional bug on moderator side:

Whenever I try to open the breakout room organisation panel I have to do it twice. The first time there seems to be a quick rerender, but the panel isn't opening. Second try always works.

**Comment by spreeni151** [comment] 2021-09-02 13:37
@PhMemmel 
Yes, that is the behavior and problem that I was trying to describe. 
I also realized the long time it took to generate the invitation links, I had never perceived it to be so time-consuming before.

**Comment by jfsiebel** [comment] 2021-09-14 17:20
Good afternoon @PhMemmel,
could you open two issues with the problems that you found?

**Comment by PhMemmel** [comment] 2021-09-14 17:48
@jfsiebel Second one was already reported in #13143 and @ramonlsouza provided a PR for that.

First one is being tracked in this issue, I just added some more detailed information on how to reproduce.

Sorry if I don't get your exact point right now. Can you please be more precise. I'm happy to provide anything I can :-)

**Comment by PhMemmel** [comment] 2021-09-14 18:10
@jfsiebel I realized there is a chance we are talking about different issues in this very same thread, so i opened up a new one for the one I discovered, see #13223

**Comment by antobinary** [comment] 2021-10-05 13:07
@ramonlsouza is this still an issue?

**Comment by ramonlsouza** [comment] 2021-10-05 16:06
> @ramonlsouza is this still an issue?

This issue can be closed... Fixed by #13173

**Closed** 2021-10-05 16:19 UTC
Labels: module: client
