### ISSUE TITLE
corners of the board not clickable on the Chrome desktop

### ISSUE THREAD

**Issue by mahdidev70** [bigbluebutton/bigbluebutton#18145] opened 2023-06-10 12:15 UTC
I can't draw in the corner of the board and the mouse goes out of pointer mode.

The problem occurred for **BBB v2.5.14** and **Chrome Desktop** v114.0.5735.106.

If you want to reprduce must try drawing from corner to center.
pay attention. this issue is not in other browser like Firefox or even Chrome mobile version.
![Screenshot from 2023-06-10 15-23-31](https://github.com/bigbluebutton/bigbluebutton/assets/91634743/517ba503-37bc-4cdd-a2f5-879e948c556c)
![Screenshot from 2023-06-10 15-23-54](https://github.com/bigbluebutton/bigbluebutton/assets/91634743/186c29b8-0674-4c3c-a7f1-16d8b3d6e6dc)

**Comment by antobinary** [comment] 2023-06-10 12:26
Hi, this looks like a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/18066 which was fixed on  BBB 2.5.18.
Could you please try to reproduce this issue on test.bigbluebutton.org (running BBB 2.5.18 at the moment)
If all looks well, we recommend you upgrade your server.
Please comment back here either way.

**Comment by mahdidev70** [comment] 2023-06-12 11:11
@antobinary 
After the update to BBB 2.5.18, the problem was solved.
thank you

**Closed** 2023-06-12 12:36 UTC
Labels: module: client
