### ISSUE TITLE
Room host not able to join the conference

### ISSUE THREAD

**Issue by leoniscsem** [bigbluebutton/bigbluebutton#10275] opened 2020-08-16 21:12 UTC
**Describe the bug**
When a user creates a room for others to join, all the invited users are able to connect, join and use the full conference suite. Yet the user who created the room just sees the loading screen and then a blank dark screen.

**To Reproduce**
1. Go to the home screen (e.g. in Greenlight)
2. Click on a room and then the start button
3. Wait for conference session to load

**Expected behavior**
After starting the room, the room host should be able to connect and participate in the conference.

**Actual behavior**
Blank BBB background screen, no UI. When only one other user joins the conference, BBB informs him/her "you are the only person in this conference".

**BBB version:**
BigBlueButton Server 2.3.0-dev (1044)

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser: Chromium
 - Version: 84.0.4147.105

**Additional context**
Chromium console error log:

`447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:69 TypeError: Cannot read property 'map' of undefined
    at 447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:336
    at Array.map (<anonymous>)
    at 447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:336
    at t.getMeteorData (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:300)
    at 447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:300
    at t._compute (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:262)
    at new t (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:262)
    at Object.o.autorun (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:262)
    at 447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:300
    at Object.o.nonreactive (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:262)
    at calculateData (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:300)
    at t.componentWillMount (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:300)
    at Wi (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:69)
    at rl (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:69)
    at Ss (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:69)
    at Hs (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:69)
    at Ws (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:69)
    at Rs (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:69)
    at 447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:69
    at n.unstable_runWithPriority (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:87)
    at ui (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:69)
    at di (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:69)
    at pi (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:69)
    at Cs (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:69)
    at Object.enqueueForceUpdate (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:69)
    at t._.forceUpdate (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:45)
    at 447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:300
    at t._compute (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:262)
    at t._recompute (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:262)
    at Object.o._runFlush (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:262)
    at a (447336066de6f305390348246a610239fe7e86ef.js?meteor_js_resource=true:1)`

**Comment by ku4b** [comment] 2020-08-18 06:28
It seems test23.bigbluebutton.org has the same (or similar) problem.
I ran into that issue on my own server (ver 2.3 in testing).

**Comment by ku4b** [comment] 2020-08-18 06:30
It is interesting that the /demo/demo1.jsp link does work on both boxes, but 
not the greenlight enabled URL.

**Comment by leoniscsem** [comment] 2020-08-20 02:57
I also noticed this bug does not show up when starting a session through an API call, e.g. through an integration with Moodle LMS.

**Comment by Qhawaq** [comment] 2020-09-02 08:08
Same problem on my installation .
Just a question: Is this bug only on version 2.3 ?

**Comment by matiasilva** [comment] 2020-09-02 21:04
This should've been fixed in the newest release of 2.3, can you confirm @leoniscsem. And no @qburst-praven this is not a bug in 2.2 as far as i'm aware.

**Comment by Qhawaq** [comment] 2020-09-04 09:54
@matiasilva: Confirmed. It works after an update to last commit of 2.3-dev.

**Closed** 2020-09-04 13:20 UTC
Labels: HTML5 Client
