### ISSUE TITLE
Unable to connect to redis after installation

### ISSUE THREAD

**Issue by atrex123** [bigbluebutton/bigbluebutton#9300] opened 2020-04-28 16:27 UTC
**I installed the BBB according to guidelines, with requirement 16.04 8 core 32 g r.
 after the installation process.**

```
BigBlueButton Server 2.2.6 (1871)
                    Kernel version: 4.4.0-177-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 32929 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: http://***.***.3.195
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: ***.***.3.195
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://***.***.3.195
                              red5: ***.***.3.195
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: ***.***.3.195
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: ***.***.3.195
                 playback_protocol: http
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: ***.***.3.195

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: ***.253.3.195
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: ***.***.3.195
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 882
                        kurentoUrl: ws://***.***.3.195/bbb-webrtc-sfu
                  enableListenOnly: true
```

nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

**but it is not running**

sudo bbb-conf --debug

-- ERRORS found in /var/log/bigbluebutton/* --
/var/log/bigbluebutton/bbb-web.log:2020-04-28T11:36:15.801-04:00 ERROR o.b.web.services.KeepAliveService - BBB Web pubsub error!

  -- ERRORS found in /var/log/bigbluebutton/* --
/var/log/bigbluebutton/bbb-web.log:2020-04-28T09:18:40.216-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-28T09:18:40.216-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-28T09:18:40.219-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-28T09:18:40.222-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-28T09:18:40.224-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-28T09:25:52.956-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379

&&&&&&&&&&&&&

xception: Connection refused: /127.0.0.1:6379
Apr 28 09:28:28 khwarizmi-foundation run-prod.sh[13338]: 2020-04-28T09:28:28.609-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
Apr 28 09:28:28 khwarizmi-foundation run-prod.sh[13338]: 2020-04-28T09:28:28.611-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
Apr 28 11:35:45 khwarizmi-foundation bbb-fsesl-akka[15719]: java.net.ConnectException: Connection refused
Apr 28 11:35:51 khwarizmi-foundation red5-shutdown.sh[19550]: Exception connecting to 127.0.0.1
Apr 28 11:35:51 khwarizmi-foundation red5-shutdown.sh[19550]: java.lang.ArrayIndexOutOfBoundsException: 0
Apr 28 11:52:26 khwarizmi-foundation bbb-fsesl-akka[4937]: java.net.ConnectException: Connection refused
Apr 28 11:53:54 khwarizmi-foundation red5-shutdown.sh[7053]: Exception connecting to 127.0.0.1
Apr 28 11:53:54 khwarizmi-foundation red5-shutdown.sh[7053]: java.lang.ArrayIndexOutOfBoundsException: 0
Apr 28 11:53:54 khwarizmi-foundation run-prod.sh[5367]: 2020-04-28T11:53:54.912-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
Apr 28 11:53:55 khwarizmi-foundation run-prod.sh[5367]: 2020-04-28T11:53:55.045-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
Apr 28 11:53:55 khwarizmi-foundation run-prod.sh[5367]: 2020-04-28T11:53:55.060-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
Apr 28 11:53:55 khwarizmi-foundation run-prod.sh[5367]: 2020-04-28T11:53:55.084-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
Apr 28 11:53:55 khwarizmi-foundation run-prod.sh[5367]: 2020-04-28T11:53:55.085-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
Apr 28 11:57:36 khwarizmi-foundation red5-shutdown.sh[10015]: Exception connecting to 127.0.0.1
Apr 28 11:57:36 khwarizmi-foundation red5-shutdown.sh[10015]: java.lang.ArrayIndexOutOfBoundsException: 0
Apr 28 11:57:37 khwarizmi-foundation run-prod.sh[7896]: 2020-04-28T11:57:37.335-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
Apr 28 11:57:37 khwarizmi-foundation run-prod.sh[7896]: 2020-04-28T11:57:37.343-04:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379

**Comment by hansnull** [comment] 2020-04-28 20:37
Same happend to me after doing a simple
`apt-get upgrade`
Result was also an ICE 1007 error.
The machine was installed 1 week ago and I had no snapshot. So I installed everything again, now it works.
BBB seems to be an admin nightmare.

**Comment by basisbit** [comment] 2020-04-29 12:40
Please read the documentation. After installing any updates, you should always execute `bbb-conf --setip your.domainname.tld`. If this solves your problem, please close this issue here.

**Comment by hansnull** [comment] 2020-04-29 16:06
I've executed to command above and tried the fixes suggested for ICE 1007, but without success. The problem seemed to be related to Redis.

**Comment by basisbit** [comment] 2020-04-29 16:10
Could you maybe try if rebooting fixed the problem? if not, does bbb-conf --check complain about any issues (maybe IP address not fitting?)

**Comment by hansnull** [comment] 2020-04-29 16:15
I've tried almost everything I found in the documentation including rebooting, checking, debugging... What I've learned: I need to take a snapshot before an update.
Thank you anyway for your help.

**Comment by martinhenits** [comment] 2020-05-09 08:25
I'm also having the same issue. Installed the latest version of BBB and log file is filled with
` Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379`

**Comment by potatoattack** [comment] 2020-05-19 11:56
I think: bigbluebutton/bbb-install#215
May be related to this issue.

**Comment by beatwiz** [comment] 2020-09-22 15:18
I'm having the same issue. 
Clean 16.04 install via install.sh as usual. I have many running  version < 2.2.20 and never had this issue.

But on the latests im getting logs filled with:
Connection refused: /127.0.0.1:6379

**Comment by basisbit** [comment] 2020-09-22 15:38
@beatwiz please restart your freeswitch service. It probably "froze".

**Comment by beatwiz** [comment] 2020-09-22 16:27
tried all sorts of restarts
bbb-conf --restart for example, never returns. It just stays there forever:

# Potential problems described below
# IP does not match:
#                           IP from ifconfig: xx.xxx.xx.xxx
#   /etc/nginx/sites-available/bigbluebutton: xxxx.xxxxxxx.xx
...........................................^C

And then bbb-conf --debug has all sorts of:

Sep 22 15:32:12 sv21 bbb-apps-akka[7804]: Exception in thread "main" io.lettuce.core.RedisConnectionException: Unable to connect to 127.0.0.1:6379
Sep 22 15:32:12 sv21 bbb-apps-akka[7804]: #011at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
Sep 22 15:32:12 sv21 bbb-apps-akka[7804]: #011at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
Sep 22 15:32:12 sv21 bbb-apps-akka[7804]: Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
Sep 22 15:32:12 sv21 bbb-apps-akka[7804]: Caused by: java.net.ConnectException: Connection refused
Sep 22 15:32:12 sv21 bbb-fsesl-akka[7893]: Exception in thread "main" io.lettuce.core.RedisConnectionException: Unable to connect to 127.0.0.1:6379
Sep 22 15:32:12 sv21 bbb-fsesl-akka[7893]: #011at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
Sep 22 15:32:12 sv21 bbb-fsesl-akka[7893]: #011at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
Sep 22 15:32:12 sv21 bbb-fsesl-akka[7893]: Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
Sep 22 15:32:12 sv21 bbb-fsesl-akka[7893]: Caused by: java.net.ConnectException: Connection refused
Sep 22 15:32:13 sv21 bbb-transcode-akka[8001]: Exception in thread "main" io.lettuce.core.RedisConnectionException: Unable to connect to 127.0.0.1:6379
Sep 22 15:32:13 sv21 bbb-transcode-akka[8001]: #011at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
Sep 22 15:32:13 sv21 bbb-transcode-akka[8001]: #011at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
Sep 22 15:32:13 sv21 bbb-transcode-akka[8001]: Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
Sep 22 15:32:13 sv21 bbb-transcode-akka[8001]: Caused by: java.net.ConnectException: Connection refused
Sep 22 15:35:21 sv21 red5-shutdown.sh[23770]: Exception connecting to 127.0.0.1
Sep 22 15:35:21 sv21 red5-shutdown.sh[23770]: java.lang.ArrayIndexOutOfBoundsException: 0
Sep 22 15:35:21 sv21 run-prod.sh[9369]: 2020-09-22T15:35:21.653Z WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379

**Comment by basisbit** [comment] 2020-09-22 22:11
well, `bbb-conf --set-ip your.domain.tld`, see documentation for how to update bbb.

**Comment by platu** [comment] 2020-11-14 14:12
Hello,
Just hit the same issue after upgrading from 2.2.28 to 2.2.29.

bbb-conf --watch is filled by: 
`/var/log/bigbluebutton/bbb-web.log:2020-11-14T14:56:21.877+01:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-11-14T14:56:21.877+01:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-11-14T14:56:21.877+01:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-11-14T14:56:21.877+01:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379`

The 2.2.28 was running ok within a LXD container.

Any hint ?

**Comment by ffdixon** [comment] 2020-11-14 21:19
For some startup sequences, `bbb-apps-akka` will start before `redis-server`.  Try running the following file

~~~
#!/bin/bash -ex

mkdir -p /etc/systemd/system/bbb-apps-akka.service.d
cat > /etc/systemd/system/bbb-apps-akka.service.d/override.conf <<HERE
[Unit]
Requires=redis-server.service
After=redis-server.service
HERE

mkdir -p /etc/systemd/system/bbb-fsesl-akka.service.d
cat > /etc/systemd/system/bbb-fsesl-akka.service.d/override.conf <<HERE
[Unit]
Requires=redis-server.service
After=redis-server.service
HERE


mkdir -p /etc/systemd/system/bbb-transcode-akka.service.d
cat > /etc/systemd/system/bbb-transcode-akka.service.d/override.conf <<HERE
[Unit]
Requires=redis-server.service
After=redis-server.service
HERE
~~~

and then restarting the container.   Let us know if the above gets you going.

**Comment by platu** [comment] 2020-11-15 17:05
Hi,

I ran the bash script and restarted the container. Everything works fine since this restart.

Thanks a lot for your help ;)

**Comment by ffdixon** [comment] 2020-11-15 20:31
Added to [bbb-install.sh](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L369).

**Comment by goekce** [comment] 2020-11-16 10:58
After updating from 28 to 29 I had the same issue.

https://github.com/bigbluebutton/bigbluebutton/issues/9300#issuecomment-727266897 fixed redis connection problem, thank you Fred!

**Closed** 2021-04-09 02:20 UTC

**Comment by goekce** [comment] 2022-10-26 16:53
Installed a fresh BBB 2.6. I still see this error after a `bbb-conf --clean`, but it does not persist and BBB seem to work fine. The reason for these errors is probably that it takes a while until Redis is started.
