### ISSUE TITLE
view recording in full screen white display

### ISSUE THREAD

**Issue by shabir-khan** [bigbluebutton/bigbluebutton#9052] opened 2020-04-13 09:29 UTC
Hello,

Viewing my recording have no problem , but when i full screen it , it is having white screen and no display at all, voice is working fine.

Will be thankful if anyone have a solution for that.

Best Regards,

Shabir Khan

**Comment by basisbit** [comment] 2020-06-02 00:00
@shabir-khan were you able to resolve this problem by updating to a new version of BigBlueButton?

**Comment by julloa1411** [comment] 2020-06-17 18:15
I have the same issue. I have the latest version (Even did a clean install on a separate server), the issue persists.

**Comment by matiasilva** [comment] 2020-06-17 18:42
Are you running on bbb 2.2.17? Can you reproduce the same error on demo.bigbluebutton.org?

**Comment by julloa1411** [comment] 2020-06-17 18:53
Hi Mathias. I do have bbb 2.2.17 installed. Im not able to reproduce the error on demo.bigbluebutton.org, since recordings are temporarily disabled.

**Comment by pedrobmarin** [comment] 2020-06-17 18:57
Does your recording has video or any webcam shared? The playback control bar will only display the primary media when on fullscreen mode.

**Comment by julloa1411** [comment] 2020-06-17 19:54
I did a test, it was just me in the conference room, sharing a pdf presentation. I reviewed the test recording, it shows the presentation just fine, when NOT in fullscreen. As soon as I toogle to FULLSCREEN, the screen goes white, and stops showing the presentation. Only audio works in fullscreen. Im doing another test just now, sharing my webcam, to see if that shows up.

**Comment by pedrobmarin** [comment] 2020-06-17 20:04
Yep, this happens because the fullscreen will ONLY DISPLAYS the PRIMARY MEDIA. If you want the whole playback in fullscreen I recommend using your browser's fullscreen (F11 maybe).

**Comment by julloa1411** [comment] 2020-06-17 20:27
Problem I see, is that not even primary media shows when in fullscreen

**Comment by pedrobmarin** [comment] 2020-06-17 20:30
Just let us know if you have a full white screen when there is a webcam playing in your recording

**Comment by julloa1411** [comment] 2020-06-17 20:36
> Just let us know if you have a full white screen when there is a webcam playing in your recording

Tried a recording with webcam video, and it works.  That means then, the fullscreen mode is ony intended to show shared webcams in the conference, but no other media in the presentation?

**Comment by pedrobmarin** [comment] 2020-06-17 20:45
Yes. The playback syncs all the recorded data following the primary media current time. The control bar really just controls the primary media that's the video in your case.

**Comment by julloa1411** [comment] 2020-06-17 21:27
Thank you. I have renamed the button's caption to "Webcam fullscreen mode", to avoid confusion on the users.

**Comment by matiasilva** [comment] 2020-06-17 21:32
Great :) Worth noting it also works for screenshare (I think) as mentioned above in examples of "primary media". Closing then.

**Closed by matiasilva** 2020-06-17 21:32 UTC
Labels: Recording

**Comment by Zvangi** [comment] 2025-05-30 16:26
This issue remains on version 3.0.8 for mobile devices.

Latest version of Android and Chrome on Mi 12 device.

Sometimes it plays OK for few seconds for chat and webcam only. But as soon as document is loaded, it's blank white screen.
