### ISSUE TITLE
Screensharing IPad OS

### ISSUE THREAD

**Issue by Herrki** [bigbluebutton/bigbluebutton#11837] opened 2021-04-01 07:33 UTC
Right now screensharing is not supported on IPad OS.

Screensharing should be possible like ist is on desktop devices.

**Comment by mrkeksi** [comment] 2021-04-01 07:52
Screensharing is not supported in this browser. From Apple, the implementation in the mobile Safari is not supported.

**Comment by prlanzarin** [comment] 2021-04-01 12:09
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/10051

**Closed by prlanzarin** 2021-04-01 12:09 UTC
Labels: Enhancement
