### ISSUE TITLE
When deleting the current presentation, upload dialog blocks user until they select a new presentation

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7849] opened 2019-07-29 03:22 UTC
Currently, when deleting the current presentation, the UI blocks the user until they select a new presentation (this requirement is not clear to the user).

![delete](https://user-images.githubusercontent.com/290351/62019780-676a4180-b18e-11e9-9b93-331bccf8de24.gif)

Instead, after deleting the current presentation, automatically select the default slide to the user can return back to the main screen.

**Comment by antobinary** [comment] 2019-07-29 13:25
This has been addressed recently. What version of the client did you encounter it on?

**Comment by capilkey** [comment] 2019-10-18 22:57
Can't reproduce this anymore so I'm going to close it.

**Closed by capilkey** 2019-10-18 22:57 UTC
Labels: HTML5 Client
