### ISSUE TITLE
Echo test stuck on Chrome Browser

### ISSUE THREAD

**Issue by parimalgajjar** [bigbluebutton/bigbluebutton#13843] opened 2021-12-07 07:35 UTC
**Describe the bug**

Suddenly, Echo test stuck in chrome browser - however it's working properly in FF.  We tried to restart all the services and also rebooted instance, but still issue with Chrome browser. Can you please help how to debug this Chrome browser specific issue.

**Comment by 2carus** [comment] 2021-12-07 08:33
I also have the same problem.
The websocket that occurs after clicking the echo test is abnormal.
In other browsers, messages from INVITE to ACK are generated in WS, but not in Chrome.
I want to know the cause and solution.

Ubuntu version is 16.04.6 and
BBB is 2.2.17.

**Comment by novastream** [comment] 2021-12-07 10:29
Same issue here with BBB 2.2.32 and Ubuntu 16.04.7 LTS

**Comment by saeed-parsaee** [comment] 2021-12-07 10:40
same issue with BBB 2.2.23 ubuntu 16.04

**Comment by novastream** [comment] 2021-12-07 11:02
It has something to do with SDP Plan-B in Chrome. Is there a fix for 2.2x or is this fixed in 2.3x and/or 2.4x ?

**Client error:**
Uncaught (in promise) DOMException: Failed to construct 'RTCPeerConnection': Plan B SDP semantics is a legacy version of the Session Description Protocol that has severe compatibility issues on modern browsers and is no longer supported. See https://www.chromestatus.com/feature/5823036655665152 for more details, including the possibility of registering for a Deprecation Trial in order to extend the Plan B deprecation deadline for a limited amount of time.

**Client log:**
[https://pastebin.com/A7KnhBTC](url)

**Comment by prlanzarin** [comment] 2021-12-07 11:54
> It has something to do with SDP Plan-B in Chrome. Is there a fix for 2.2x or is this fixed in 2.3x and/or 2.4x ?

It's fixed on >= 2.3.

2.2 has reached EOL for a few months now. Upgrade to 2.3 or later.

About the issue: yeah, Plan B is being phased out in Chrome via a Reverse Origin Trial.
In the current phase it's usage has been removed and it's only usable via an opt-in that you have
to orchestrate with Google. So I recommend just updating your BBB.

FYI:
  - https://github.com/bigbluebutton/bigbluebutton/pull/11631
  - https://github.com/bigbluebutton/bigbluebutton/pull/11728

**Closed by prlanzarin** 2021-12-07 11:54 UTC
Labels: module: core

**Comment by prlanzarin** [comment] 2021-12-07 12:08
Actually the thing was even backported to 2.2 (2.2.36), see: https://github.com/bigbluebutton/bigbluebutton/pull/11798.

Please make an effort to at least use the latest 2.2.......

**Comment by novastream** [comment] 2021-12-07 12:10
@prlanzarin thank you for your help, now we have some options :).
