### ISSUE TITLE
Participants are not assigned evenly spread to breakout rooms

### ISSUE THREAD

**Issue by mwuttke** [bigbluebutton/bigbluebutton#13414] opened 2021-10-05 16:17 UTC
**Describe the bug**
Assigning people randomly to breakout rooms and then hitting create does not work as expected. We had a session with around 60 participants. The moderator has choosen 16 breakout rooms to create and tried to assign all participants to these rooms. In 13 rooms were 4 participants assigned to and for the 3 remaining rooms 3 participants were assigned to. But in the end after creating the rooms and assigning the participants in one room were 8 participants, in 2 rooms six participants and in some rooms were just one participant.

**To Reproduce**
 1. Install of BBB 2.3.14 on Ubuntu 18.04 via https://ubuntu.bigbluebutton.org/bbb-install.sh
 2. Several participants join a room.
 3. The Moderator creates 16 breakout rooms and tries to assign the participants randomly to breakout rooms.
 4. In some breakout rooms are a lot of participants and in some breakout rooms is nobody.

**Expected behavior**
All participants should be assigned randomly to the breakout rooms, of course evenly spread.

**Actual behavior**
Described above.

**BBB version:**
BigBlueButton Server 2.3.14 (2457)

**Additional context**
Kernel version: 4.15.0-159-generic
Distribution: Ubuntu 18.04.6 LTS (64-bit)
Memory: 16424 MB
CPU cores: 8

**Comment by antobinary** [comment] 2021-10-05 16:20
Possible duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/13250

**Comment by ramonlsouza** [comment] 2021-10-05 20:39
Hello @moodle-mw, I ran a test meeting with 60 participants + 1 moderator on a 2.3.14 server and all of them received an invitation to the same room that appeared in rooms creation.

Is there a possibility that **Allow users to choose a breakout room to join** was checked when the wrong assignment happened?

<img width="603" alt="Screen Shot 2021-10-05 at 17 24 37" src="https://user-images.githubusercontent.com/3728706/136099228-12374544-57f2-4259-8058-8702357577eb.png">


If that's the case, pressing "Randomly assign" or dragging users to a room should have no effect (see https://github.com/bigbluebutton/bigbluebutton/issues/13250#issuecomment-926003985)

<img width="503" alt="Screen Shot 2021-10-05 at 17 03 28" src="https://user-images.githubusercontent.com/3728706/136095362-3c67b078-38e4-4632-bc71-ff72f7f72f9a.png">

**Comment by moodle-mw** [comment] 2021-10-06 08:45
Hello @ramonlsouza, the teacher/moderator of the said session told me that he didn't used the possibility to "Allow users to choose a breakout room to join". The moderator only used "Randomly assign", he told me.

But you are right, using both "Allow users to choose a breakout room to join" & "Randomly assign" or dragging users to a room has no effect. I've tested it with 20 participants and 10 breakout rooms.

Thanks & Greetings,
Michael

**Comment by gustavotrott** [comment] 2022-01-07 20:24
I sent a fix for this problem in #13816.

**Comment by antobinary** [comment] 2022-01-07 20:52
The refactor #13816 will ship as part of BBB 2.5-alpha-1
Thanks all!

**Closed by antobinary** 2022-01-07 20:52 UTC
Labels: module: client
