### ISSUE TITLE
"maxParticipants" param works incorrectly when creating a meeting through API

### ISSUE THREAD

**Issue by arapoport** [bigbluebutton/bigbluebutton#8456] opened 2019-12-28 23:22 UTC
When creating new meeting using API if parameter `maxParticipants` is passed then the actual number of allowed participants will be `maxParticipants-1`.

**To Reproduce**
1. Create a new meeting with `maxParticipants=2`
2. Join meeting with one user
3. Try to join meeting with another user
4. The second one will be redirected to an error page

I tried with 5 too and only 4 could join.

BigBlueButton 2.2-RC-4:

```
ii  bbb-apps                              1:2.2.0-35    
ii  bbb-apps-akka                         2.2.0-67      
ii  bbb-apps-screenshare                  1:2.2.0-35    
ii  bbb-apps-sip                          1:2.2.0-11    
ii  bbb-apps-video                        1:2.2.0-32    
ii  bbb-apps-video-broadcast              1:2.2.0-8     
ii  bbb-client                            1:2.2.0-33    
ii  bbb-config                            1:2.2.0-139   
ii  bbb-etherpad                          1:2.2.0-47    
ii  bbb-freeswitch-core                   2:2.2.0-79    
ii  bbb-freeswitch-sounds                 1:1.6.7-6     
ii  bbb-fsesl-akka                        2.2.0-52      
ii  bbb-html5                             1:2.2.0-815   
ii  bbb-mkclean                           1:0.8.7-3     
ii  bbb-playback-presentation             1:2.2.0-26    
ii  bbb-record-core                       1:2.2.0-52    
ii  bbb-red5                              1:1.0.10-16   
ii  bbb-swftools                          1:0.9.2-2     
ii  bbb-transcode-akka                    2.2.0-8       
ii  bbb-web                               1:2.2.0-106   
ii  bbb-webrtc-sfu                        1:2.2.0-81    
ii  bigbluebutton                         1:2.2.0-4     
```

**Comment by GhaziTriki** [comment] 2020-01-01 16:20
This issue is already reported in https://github.com/bigbluebutton/bigbluebutton/issues/5843

**Comment by capilkey** [comment] 2020-01-06 22:47
Duplicate of #5843

**Closed by capilkey** 2020-01-06 22:47 UTC
Labels: Duplicate
