### ISSUE TITLE
BBB still relies on Ubuntu 16.04 which is going to be out off support soon. Asking for version on Ubuntu 20.04 LTS!

### ISSUE THREAD

**Issue by melolontha-melolontha** [bigbluebutton/bigbluebutton#11258] opened 2021-01-29 13:49 UTC
**Describe the bug**
BBB still relies on Ubuntu 16.04 server 64-Bit which is going to be out off support in April this year. There should be a version for Ubuntu 18.04 LTS server 64-Bit or even better for Ubuntu 20.04 LTS server 64-Bit (both are long-term supported versions, I don't care which of the two you select. If 20.04 is feasible, that would be better since it has some more life time ahead of it).

But maybe it already runs on such a newer OS version: In this case rust update the documentaion, e.g. on https://docs.bigbluebutton.org/2.2/install.html#Install_ where it currently says:
"To set up for a successful install of BigBlueButton, we recommend starting with a ‘clean’ Ubuntu 16.04 64-bit server dedicated for BigBlueButton." Then say that it works on that version and in addition on ... (the tested new ones) ...

**Installation type**
not yet.

**Firewall and IP address type**
Is your server behind a NAT or firewall? Does your BBB server have its own IPv4 address?

**Console output**
Please include the full console output from the install.

**Additional context**

**Comment by BOZG** [comment] 2021-01-29 20:41
Version 2.3 (which is in development) is based on 18.04. According to [this](https://github.com/bigbluebutton/bigbluebutton/issues/8474#issuecomment-750237498) comment, 20.04 is not yet feasible due to Kurento not having support in 20.04.

**Comment by basisbit** [comment] 2021-01-30 01:04
Duplicate of various other issues.

**Closed by basisbit** 2021-01-30 01:04 UTC
