### ISSUE TITLE
iOS 15 only: unable to join a conference as speaker

### ISSUE THREAD

**Issue by krim404** [bigbluebutton/bigbluebutton#13247] opened 2021-09-21 09:51 UTC
When joining a conference on either our own servers or test.bigbluebutton.org with an ios15 device on safari some strange behaviour occurs:

- the echo test is working well (albeit some times its volume is very low)
- clicking on the green button results in an error "trying to reconnect audio" and opening the audio selector again (microphone/headphones)
- then one of the following happens: 
* either a second echo test succeeds, resulting in a restart of the "trying to reconnect audio" loop
* the echo test window reappears, the notification "trying to reconnect audio" and "you have joined the conference" is popping up at the same time - so closing the echo test dialogue by pressing on the X results in a working conference
* the connection fails after a successful echo test with error 1006 - which will be this way until you close safari completly and try again
* the connection fails after a successful echo test with error 1008 - which will then change in an error 1006

when the connection succeedes there is a posibility that the volume is so low, that you cant understand a word of the conference

Using a mobile internet connection (LTE) results in a 1006 all the time.

Strangest thing: using an app with BBB works all the time
https://github.com/bennyboer/bbb_app

Issue is with BBB only, jitsi is working well - except the volume problem
Issue is new to the release version of ios15, Beta4-8 and RC only had the volume problem.
Volume problem seems related to: https://groups.google.com/g/bigbluebutton-dev/c/kGqreyFXvZo

** Tested with **
iPad Pro M1, iPhone 7, iPhone 8, iPhone X, iPhone 11, 3x iPad Air 2 - all on different apple ids and with different owners.
already tried all possible security features like private relay in each possible way, switching on/off webcontent filters, desktop mode - all without any effect on this issue

**Comment by ali-alhaidary** [comment] 2021-09-21 10:58
BigBlueButton Server 2.4-rc-1 (2486)
client 2276
macOS: Catalina 10.15.7 safari 14.1.12 and 15.0
iPhone 5SE: iOS 15
works as expected

**Comment by krim404** [comment] 2021-09-21 11:02
as far as i know as apple has started adding vpn features and security / data protection algorithm which are not rolled out worldwide, it is possible this issue is region locked.

**Comment by ali-alhaidary** [comment] 2021-09-21 11:14
@krim404 No, I tested it on our production server with the release stated above.

**Comment by Daedalus3** [comment] 2021-09-21 12:48
Works fine here (on test.bigbluebutton.org) and has been working since iOS 15 beta 1. Tested again on iPhone XS, iOS 15 final and with and without private relay enabled (but restricted to Europe).

**Comment by sam9032** [comment] 2021-09-21 14:18
Hm, same problems here, connection problems and volume problems.

Tested on test.bigbluebutton.org, test24.bigbluebutton.org and my own server with 2.3.13.

Also tested with IP Tracking option activated and deactivated, but this made no difference.

**Comment by krim404** [comment] 2021-09-21 14:32
> Hm, same problems here, connection problems and volume problems.
may i ask where u're from? 
i have these issues in germany.

a small update: when i route my traffic thru the united states (via vpn on my router) it seems to work...

**Comment by sam9032** [comment] 2021-09-21 15:02
> > Hm, same problems here, connection problems and volume problems.
> 
> may i ask where u're from?
> i have these issues in germany.
> 
> a small update: when i route my traffic thru the united states (via vpn on my router) it seems to work...

I tested it from germany too..

The tests above are with IPv4 only (Vodafone cable and mobile internet) and now I tested it with IPv4 and IPv6 Dual Stack (vodafone cable only), but I don't know if iOS chooses IPv6. Both the same behaviour.

**Comment by sam9032** [comment] 2021-09-21 15:12
According to bbb connection status iOS does not use a turn server, maybe this is a problem?
In the past I often had problems with iOS when the turn server was not used.

**Comment by PhMemmel** [comment] 2021-09-21 15:14
Just stumbled over this: https://developer.apple.com/forums/thread/689293

Can anyone of you try the experimental settings described there? Maybe this helps track down the problem.

**Comment by krim404** [comment] 2021-09-21 15:16
when i'm using my iphone in hotspot mode i dont need a turn server. but it is possible

> Just stumbled over this: https://developer.apple.com/forums/thread/689293
> 
> Can anyone of you try the experimental settings described there? Maybe this helps track down the problem.

already tried that - did not help.

**Comment by sam9032** [comment] 2021-09-21 15:47
> Just stumbled over this: https://developer.apple.com/forums/thread/689293
> 
> Can anyone of you try the experimental settings described there? Maybe this helps track down the problem.

I tried it too, didn't change anything.

Is there a way to force iOS to use a turn server?

**Comment by mariogasparoni** [comment] 2021-09-21 16:48
I can confirm this is happening on iOS 15.

**Comment by ali-alhaidary** [comment] 2021-09-21 17:10
Just tested it on iPhone SE (second generation) iOS 15, it can be reproduced, however, using VPN connection makes it work as expected.

**Comment by Daedalus3** [comment] 2021-09-22 06:42
I tested again on a different internet (DSL) access point (not the one I'm usually using which is Vodafone Cable based (Germany)) and I can now reproduce this issue as well. Retried with iOS 15.1 beta 1 -works fine while using Vodafone Cable -does not when using the DSL line.

**Comment by coderDem** [comment] 2021-09-22 08:06
Have the same error with iOS 15 on iPhone 11 Pro Max from Germany DSL.

**Comment by ali-alhaidary** [comment] 2021-09-22 08:58
BigBlueButton Server 2.4-rc-1 (2490)

Feedback from teachers/students
iOS 15 devices
With VPN mic echo test connects, sound transmuted is good, but received sound is scrambled and unrecognizable.
Without VPN mic echo test does not connect with 1006 error, and received sound is scrambled and unrecognizable.

**Comment by sam9032** [comment] 2021-09-22 10:58
Strange that it works with a VPN. Does this perhaps prevent Apple from influencing the connection setup in any way, be it through anti-tracking or other things?

> I'd try to block the high udp ports in your firewall. This usually forces the browsers to use the turn relay, but I don't know if iOS/Safari behaves the same

I tried what you suggested and now the turn server is used. It still doesn't change the problems.

**Comment by ali-alhaidary** [comment] 2021-09-22 11:33
The strange thing is that it works as expected on the iPhone 5SE with iOS 15 !!!

**Comment by lioJkt** [comment] 2021-09-22 11:34
I have the same issue with two different iPad (model 5) on PadOs15.
Test had been made with different BBB Serveurs and also test.bigbluebutton.org from Indonesia (Jakarta)
Impossible to join even with a lot of attempts.

On a third one, (model 6) still on PadOs15, this is a little bit different. Sometimes connexion succeed, sometimes failed but without error 1006. With that iPad I'm usually able to join after some attempts.

**Comment by mariogasparoni** [comment] 2021-09-22 12:42
hi @krim404  , @lioJkt , @ali-alhaidary , @sam9032  (and anyone else who can help)  , could you please share some logs from browser console ?

I am able to reproduce it, but the problem doesn't happen all the time. Sometimes it needs 5 attempts to reproduce the bug.
(i would like to be sure we are hitting the same problem)
Thanks in advance.

**Comment by ali-alhaidary** [comment] 2021-09-22 12:54
@mariogasparoni console reports on iOS safari is tricky as it needs a mac connected by cable.

**Comment by sriharsha-CT** [comment] 2021-09-22 13:37
> hi @krim404 , @lioJkt , @ali-alhaidary , @sam9032 (and anyone else who can help) , could you please share the logs from browser console ?
> 
> I am able to reproduce it, but the problem doesn't happen all the time. Sometimes it needs 5 attempts to reproduce the bug.
> (i would like to be sure we are hitting the same problem)
> Thanks in advance.

```
[Error] WebSocket connection to 'wss://www.codetantra.com/ws?sessionToken=xzq5opwswspc2wv2' failed: The operation couldn’t be completed. Socket is not connected
[Error] Wed Sep 22 2021 18:57:04 GMT+0530 (IST) | sip.Transport | WebSocket error occurred.
	print (sip.js:9594)
	genericLog (sip.js:9574)
	genericLog (sip.js:9647)
	error (sip.js:9635)
	onWebSocketError (sip.js:19246)
[Warning] Wed Sep 22 2021 18:57:04 GMT+0530 (IST) | sip.Transport | WebSocket closed unexpectedly (sip.js, line 9598)
[Warning] Wed Sep 22 2021 18:57:23 GMT+0530 (IST) | sip.UserAgent | User agent already stopped (sip.js, line 9598)
[Error] Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
	(anonymous function)
	rejectPromise
	play
	playHangUpSound (29cff6ea6e9dfc93e2bc59d61cf10d6acc80e51b.js:329:1347671)
	onAudioExit (29cff6ea6e9dfc93e2bc59d61cf10d6acc80e51b.js:329:1344278)
	(anonymous function) (29cff6ea6e9dfc93e2bc59d61cf10d6acc80e51b.js:329:1345305)
	Promise
	callStateCallback (29cff6ea6e9dfc93e2bc59d61cf10d6acc80e51b.js:329:1344479)
	callStateCallback
	bound callStateCallback
	c (29cff6ea6e9dfc93e2bc59d61cf10d6acc80e51b.js:329:1392792)
	(anonymous function) (29cff6ea6e9dfc93e2bc59d61cf10d6acc80e51b.js:329:1402655)
```

**Comment by mariogasparoni** [comment] 2021-09-22 13:43
Thanks.

@sriharsha-CT  , it seems this is the same error i am reproducing (websocket failure) , here's my log:
```
WebSocket connection to 'wss://myhost.com/ws?sessionToken=iwsip5pcgfuxr9zz' failed: The operation couldn’t be completed. Socket is not connected
    sip.js?v=2277:9594 Tue Sep 21 2021 16:57:10 GMT+0000 (UTC) | sip.Transport | WebSocket error occurred.
```

**Comment by mariogasparoni** [comment] 2021-09-22 13:59
@ali-alhaidary , @sriharsha-CT , would you be willing to try it in my test environment ?
(i am testing a possible fix)
if so, please email me: mariogasparoni at gmail

**Comment by mariogasparoni** [comment] 2021-09-22 14:12
@ali-alhaidary  not sure, the problem i have is related to the connection. You should get an Audio Error 100x

**Comment by mariogasparoni** [comment] 2021-09-22 14:30
But feel free to help testing this. I can give you the URL of my dev server

**Comment by ali-alhaidary** [comment] 2021-09-22 14:48
@mariogasparoni no errors, but sound is not clear.

**Comment by sam9032** [comment] 2021-09-22 14:54
I can test it on your dev server, but I have no MacOS Device to get the logs out of safari..

**Comment by mariogasparoni** [comment] 2021-09-22 14:57
> I can test it on your dev server, but I have no MacOS Device to get the logs out of safari..

Please email me , it's ok . I don't need logs right now

**Comment by mariogasparoni** [comment] 2021-09-22 16:29
> @mariogasparoni your server works fine, amazing! Tested it with iOS 15, iOS 14 and firefox on linux.
> Except if I block the ports above 443 but I think this is because there is no turn server available?

Glad to hear that.
Yes , i didn't set turn server, that's why you can't join when blocking your ports (except 443). 
Will keep testing it, thanks a lot for your help

**Comment by mariogasparoni** [comment] 2021-09-22 17:43
Hi @krim404 and others.
There's a fix for this here: https://github.com/freeswitch/sofia-sip/pull/94

We are bringing this to the next releases. Thanks for all your help.

**Comment by antobinary** [comment] 2021-09-22 21:02
BBB 2.3.14 has been [released](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3.14) and the fix was included. Could someone confirm the issue resolved on a 2.3.14 server of their own, so we can close this?
Thanks all!! :confetti_ball:

**Comment by ravi-ct** [comment] 2021-09-23 04:23
Can this be back-ported to 2.2 as well please?

**Comment by Daedalus3** [comment] 2021-09-23 07:18
@antobinary @mariogasparoni : works fine on my server, tested on iOS 15 and 15.1 beta 1.

Thank you  for this very fast fix!

**Comment by sam9032** [comment] 2021-09-23 07:41
> BBB 2.3.14 has been [released](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3.14) and the fix was included. Could someone confirm the issue resolved on a 2.3.14 server of their own, so we can close this?
> Thanks all!! 🎊

I installed the new version on my server and it works perfectly fine. No more connection problems. 🎉

**Comment by ali-alhaidary** [comment] 2021-09-23 09:51
is it merged for 2.4-rc-1 ?

**Comment by PhMemmel** [comment] 2021-09-23 09:59
Not yet, but according to @ffdixon they will release 2.4-rc2 soon which will include this fix.

**Comment by ali-alhaidary** [comment] 2021-09-23 10:01
@PhMemmel is it on 2.4-dev?

**Comment by PhMemmel** [comment] 2021-09-23 10:03
@ali-alhaidary Sorry, don't know, as this is a packaging change and these are not publicly available yet. Have a try :-)

**Comment by antobinary** [comment] 2021-09-23 13:50
Thanks for the confirmation!

This fix (already released on 2.3) will become part of 2.4 via 2.4-rc-2. I am closing this issue now but please comment if new concerns arise. Thanks all!

**Closed by antobinary** 2021-09-23 13:50 UTC
Labels: status: accepted, module: audio, target: stability, type: bug, component: microphone

**Comment by ali-alhaidary** [comment] 2021-09-23 15:47
confirmed on 2280

**Comment by friedohs** [comment] 2021-09-24 03:07
Hi,
I was updating from 2.3 to 2.4 and having 1002 error. I was having this problem before at the very beginning of implementing BBB in our organization. My fix was just adjusting the firewall to allow http, https, udp from 16000-33000 (based on the installation guide).

Our BBB was installed in Google Cloud Platform and it's working fine with the abovementioned conf. Any new adjustments for the 2.4 version?

**Comment by tickytacky** [comment] 2022-03-12 06:52
> Can this be back-ported to 2.2 as well please?

This question wasn't answered...
Is there a chance to get iOS 15 to work with  BBB 2.2.36?

Thanks!

**Comment by ffdixon** [comment] 2022-03-12 11:53
No, you would need to upgrade to a more recent version of BigBlueButton.  At the time of this writing, that would be 2.4.x.
