### ISSUE TITLE
Videolist selection like Slideshows / PDFs

### ISSUE THREAD

**Issue by Dtrieb** [bigbluebutton/bigbluebutton#11643] opened 2021-03-13 11:19 UTC
You can upload and choose between your pdf, ptt, etc.
I would like to have the same menu for videos (mp4) 

So before I start the meeting i can put all Videos I need in the list choose with I want to show my audience.

**Comment by basisbit** [comment] 2021-03-13 23:56
closing as duplicate of various other issues where people ask for sharing video files.
TLDR: thats not so easy, however screen share with audio will probably "solve" most of the use cases.

**Closed by basisbit** 2021-03-13 23:56 UTC
Labels: Enhancement

**Comment by hiroshisuga** [comment] 2021-03-14 00:09
Let me comment although it's closed. 
As already a core developer commented, there has been a high interest in this feature. But there would be a lot of new issues coming up once it is implemented. For instance, because not everybody is running BBB on a server powerful enough to host video sharing service, there might be a lot of complaint, which will destroy the core developers.
However, in my personal opinion, those who understand the problem and do not expect any support can do it in their own server. Try to search the past PR enabling a generic upload of media files. The PR has been already closed probably on purpose, but it was working well at that time. The PR is quite outdated and you will need some work to make it working. Good luck!
