### ISSUE TITLE
Fullaudio bridge does not work with TURN

### ISSUE THREAD

**Issue by jpetrihst** [bigbluebutton/bigbluebutton#14460] opened 2022-02-25 12:15 UTC
Using BBB 2.4.4, we tried using the new experimental fullaudio bridge and found out that there are problems with users which can only connect via a TURN server (p.a. if they are behind a restrictive firewall). The can not connect to the audio bridge and get error 1007.

So I did a little test:
I tried connecting to the server with fullaudio bridge activated, all was going fast and smooth as expected.
Then I blocked every outgoing port on my system to the BBB server except for TCP 80&443. Now I am getting error 1007, too. Then I deactivated the fullaudio bridge on the server and restarted bbb, now I was able to connect my audio successfully.

So it seems that TURN is not working with fullaudio bridge at the moment.

**Comment by prlanzarin** [comment] 2022-02-25 12:20
BigBlueButton version, please.

**Comment by jpetrihst** [comment] 2022-02-25 12:22
oops, forgot. Version 2.4.4, I corrected this.

**Comment by prlanzarin** [comment] 2022-02-25 12:29
I'll verify this based on 2.5 (only) next week. Track the issue for updates.

**Comment by prlanzarin** [comment] 2022-03-10 22:59
Cannot reproduce in 2.5 using mediasoup as the adapter for the full audio bridge.
Please retry in 2.5 with mediasoup as the adapter (it is the default).

The process for running the experimental bridge in 2.5 is the same as outlined in 2.4's docs.
As for mediasoup, you might need to configure correct IPs for it. Refer to https://github.com/bigbluebutton/bbb-webrtc-sfu/blob/development/docs/mediasoup.md#using-mediasoup-in-bigbluebutton-25.

I'm closing this since everything seems to be ok with using TURN in the bridge. Please provide feedback - if still doesn't work we can tinker a bit more and re-open if necessary.

**Comment by jpetrihst** [comment] 2022-03-11 09:02
So, I now completely reinstalled the server from scratch, including ubuntu. The server is not behind a NAT and has an official v4 and v6 address.
I used bbb 2.5 alpha3, installed with bbb-install.sh
I entered one turn server and blocked (this time on the server) in iptables connections from my ip adresses (v4 and v6) except for tcp ports 80 and 443.
I used the demo web interface for the tests.
The turn server is defined by 
` <constructor-arg index="1" value="turns:<hostname of turn server>:443?transport=tcp"/>`
The turn server is the only thing I changed from default configuration.
So here are the results:

Default audio config, IP unblocked: works
Default audio config, IP blocked: works
Default audio config, IP blocked, turn disabled: doesn't work

So far so good, expected behavior. But now:

exp. audio config, IP unblocked: works
exp. audio config, IP blocked: doesn't work (error 1007)

switching back to default audio by disabling the entries in bbb-html5.yml and restarting bbb makes things work again.

I am using coturn as a turn server on a distinct machine (but in the same subnet) with a simple config:
```
listening-port=3478
tls-listening-port=443
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=xxx
realm=xxx
cert=xxx
pkey=xxx
dh2066
no-tlsv1
no-tlsv1_1
log-file=xxx
simple_log
```

**Comment by prlanzarin** [comment] 2022-03-18 14:00
@jpetrihst Noted. I'll dig some more.

**Comment by prlanzarin** [comment] 2022-04-25 12:46
Re-opening for further analysis.

**Comment by jpetrihst** [comment] 2022-05-12 10:05
I just tested with a new clean install on 2.5-rc1.

Problem is gone EXCEPT for clients that use ipv6 only (ipv4 protocol disabled on client side). However, since it also does not work for these clients even if they do not have to use the TURN server it likely is an issue with the new fullaudio and  IPv6-only clients.

Note: To make things work for IPv6-only clients I had to implement the changes described [HERE](https://docs.bigbluebutton.org/support/troubleshooting.html#configure-bigbluebuttonfreeswitch-to-support-ipv6)

**Comment by prlanzarin** [comment] 2022-05-12 10:29
> Note: To make things work for IPv6-only clients I had to implement the changes described [HERE](https://docs.bigbluebutton.org/support/troubleshooting.html#configure-bigbluebuttonfreeswitch-to-support-ipv6)

That should make no difference at all for the experimental bridge, just the default one.

Did you set up an IPv6 address in mediasoup?

**Comment by jpetrihst** [comment] 2022-05-12 10:46
> Did you set up an IPv6 address in mediasoup?

Apologies, I was not aware of this.
It now works like a charm for v6-only clients too, with and without TURN.
Thanks!

**Comment by prlanzarin** [comment] 2022-05-12 11:09
I'll add that to the docs.

Please close the issue if it was addressed, thanks.

**Closed** 2022-05-12 11:13 UTC
Labels: module: client, type: bug, status: verify, component: microphone
