### ISSUE TITLE
BBB for desktop using flex air1.5

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1734] opened 2015-08-12 07:45 UTC
Originally reported on Google Code with ID 979

```
Hi,

Is it possible to develop a Desktop BigBlueButton application using adobe air which
installed and run on user desktop/pc. And is it possible for desktop sharing, because
in BBB for desktop sharing module using applets concept

regards,
Harikrishna. 
```

Reported by `vhk009` on 2011-08-03 10:38:43

**Comment by GhaziTriki** [comment] 2017-05-23 17:25
This is a duplicate of #1602

**Comment by ffdixon** [comment] 2018-12-06 02:21
Closing this issue as we are moving to an HTML5 client.

**Closed by ffdixon** 2018-12-06 02:21 UTC
Labels: Flash Client, Low Priority, Research
