### ISSUE TITLE
One can submit several poll votes

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10705] opened 2020-10-22 21:13 UTC
Not an HTML5 issue, but not sure how to rank it

**Describe the bug**
This week BBB works slower than before and the poll dialog does not disappear immediately after students vote. Thus, they keep clicking, assuming the dialog would disappear after submission and vote multiple times.

**Screenshots**
Here 74 users voted 145 times:
![image](https://user-images.githubusercontent.com/38284875/96928494-e72dab80-14b8-11eb-974e-0032036d51cc.png)

**BBB version (optional):** 2.2.28

**Comment by ravi-ct** [comment] 2020-10-23 14:47
We saw the exact same behaviour, moving from v2.2.23 to v2.2.28.

1. The number of votes was counted many times over for the same voter, happens frequently enough. We could not pin down the conditions on which this happens. We could not reproduce the issue when there is only one meeting on the server. A simple approach to reproduce is by clicking on the poll options repeatedly.
1. The client definitely appeared to slow down. Over the same client base which was on 2.2.23 yesterday, where we had 0 complaints of client freezing/slowing down in the last 1 week, with 2.2.28, we had 62 clients in just the first couple of hours.

Reverting the changes to bigbluebutton-html5/imports/api/polls/server/methods/publishVote.js made in the PR [10564](https://github.com/bigbluebutton/bigbluebutton/pull/10564) resolved the issue for us. However, we could not confirm if the client freezing and slowing down has been resolved.

**Comment by paul1278** [comment] 2020-10-27 18:46
I also think this is kinda server-related, when running the following script inside the js-console of my browser, i can submit big amounts of poll votes, which are just simply send over the ws-connection.

```js
let answerIndex = 0;
let answers = 50;
let button = document.querySelectorAll('[class^=pollButton]')[answerIndex].children[0];
for(let i = 0; i < answers; i++) { button.click() }
```

Maybe there is also some duplicate-checking on the server needed, because by hiding the button faster this should still be possible.
This is also reproducable on servers with only one meeting and BigBlueButton v2.2.28 using the snippet above.

**Comment by basisbit** [comment] 2021-01-30 02:09
Closing this issue because it was fixed already by the above PR.

**Closed by basisbit** 2021-01-30 02:09 UTC
Labels: HTML5 Client
