### ISSUE TITLE
whiteboardToolbarAutoHide seems not to take effect

### ISSUE THREAD

**Issue by mwuttke** [bigbluebutton/bigbluebutton#21686] opened 2024-11-15 11:17 UTC
**Describe the bug**
Enabling

```
public:
  app:
    defaultSettings:
      application:
        whiteboardToolbarAutoHide: true
```

for `/etc/bigbluebutton/bbb-html5.yml` does not seem to have effect

**Expected behavior**
Hide Whiteboard Toolbars from start on.

**Actual behavior**
Whiteboard Toolbars  remains visible.

**BBB version:**
BigBlueButton Server 3.0.0-beta.4 & 3.0.0-beta.5 (Client build: 875)

**Desktop:**
 - OS: [Linux]
 - Browser [Firefox]
 - Version [132]

**Comment by Ithanil** [comment] 2024-11-18 18:29
For some reason, I can't reproduce the issue on our beta.5 servers.

When the meeting is started with `whiteboardToolbarAutoHide: true` and the presentation is loaded, the toolbar will be initially hidden if the mouse is outside the presentation area. If the mouse is inside the presentation area, the toolbar will be visible until the mouse is moved outside the area and then fade away.

As a note, in my tests `userdata-bbb_hide_presentation_on_join=true` was passed as join parameter. I don't think that plays a role, because it actually doesn't work on 3.0. :D But that's a separate issue.

**Closed** 2024-11-26 12:29 UTC
Labels: module: client

**Comment by ramonlsouza** [comment] 2024-11-26 14:28
I could not reproduce it either - it was probably fixed in a recent PR... We can reopen the issue if it happens again
