### ISSUE TITLE
Avoid repeated gUM calls on webcams

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#8704] opened 2020-03-04 16:21 UTC
We ask for permission to getUserMedia multiple times prior to sharing webcam AND screenshare. Very visible on FireFox. Remember the result and (re)use it.

**Comment by prlanzarin** [comment] 2020-03-04 16:23
That's a problem for webcams. Screenshare only calls getDisplayMedia once per sharing requisition AFAIK. Do you have a reproducible scenario for screenshare?

**Comment by schrd** [comment] 2021-04-02 16:21
Firefox will ask for device permission every time gUM is called. Firefox will not ask for permission again, if you apply other constraints on the MediaStreamTrack that was returned by the first gUM call as long as no other device is involved.

see https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/applyConstraints or https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints

**Comment by prlanzarin** [comment] 2021-04-02 17:34
Yeah. That's known. I've detailed what's wrong in https://github.com/bigbluebutton/bigbluebutton/issues/11151. I'm closing this in favor of that one because the latter is better explained.

**Closed by prlanzarin** 2021-04-02 17:34 UTC
Labels: HTML5 Client
