### ISSUE TITLE
Action-bar mute/unmute has no throttling (can be spammed)

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#11227] opened 2021-01-26 16:26 UTC
**Describe the bug**

Muting/unmuting via the action-bar has no throttling nor debounce, so it can be spam clicked. If enough people do it concurrently, it's enough to put some unwarranted stress to a meteor instance. 

**To Reproduce**

1. Join a session in test.bigbluebutton.org
2. Enable microphone
3. Focus on the mute/unmute action-bar button
4. Hold enter pressed, check console logs for time between toggles

**Expected behavior**

There should be a throttle wrapping the toggle to prevent spam clicking it.
The throttle should be configurable since it affects mute/unmute state responsiveness.

**Desktop and smartphones (please complete the following information):**
 - OS: any OS
 - Browser: any browser
 - Version: any version

**Additional context**

Example ts diff between toggles:

```
[16:54:20:0592]  INFO: clientLogger: microphone muted by user toggleMuteMicrophone
[16:54:20:0623]  INFO: clientLogger: microphone muted by user toggleMuteMicrophone 
[16:54:20:0654]  INFO: clientLogger: microphone unmuted by user toggleMuteMicrophone
[16:54:20:0684]  INFO: clientLogger: microphone muted by user toggleMuteMicrophone
```

**Comment by daminebenq** [comment] 2021-01-26 16:36
duplicate of #9731
closing #9731 to avoid duplications.

**Comment by prlanzarin** [comment] 2021-01-26 16:39
This is definitely not a duplicate of #9731.
I'm not talking about the talking indicator, I'm talking about the action bar mute toggle.

**Comment by basisbit** [comment] 2021-01-26 16:54
As general rule of thumb, when finding duplicates, please close the new issue and keep the old issue, while adding new details to the old issue if available.

**Comment by basisbit** [comment] 2021-01-27 22:15
fixed by 11227

**Closed by basisbit** 2021-01-27 22:15 UTC
Labels: HTML5 Client
