### ISSUE TITLE
bbb-html5.nginx configuration in bbb-html5 2.3.0-1767 causing nginx errors

### ISSUE THREAD

**Issue by vlasov01** [bigbluebutton/bigbluebutton#12570] opened 2021-06-13 02:44 UTC
**Describe the bug**
I've just completed a fresh installation of BigBlueButton Server 2.3.3 (2326). It seems working fine, big thanks to BBB team. I'm not using Greenlight as I'm using Moodle. I run bbb-conf --check and no problems were reported. 

But my niginx error.log got filled up with errors from Meteor.

**To Reproduce**
1. Install BigBlueButton Server 2.3.3 (2326) without Greenlight and demo API
2. Join meeting from Moodle
3. Join a meeting

**Expected behavior**
No errors should be generated for html5client static files requests. nginx should serve static content, like js files. 

**Actual behavior**
nginx invokes Meteor for static html5client files, gets error, then returns static content, like js files. As well it generates error in /var/log/nginx/error.log like: `2021/06/12 08:39:46 [error] 25278#25278: *297 connect() failed (111: Connection refused) while connecting to upstream, client: 33.33.43.43, server: meeting1.mydomain.ca, request: "GET /html5client/compatibility/sip.js?v=1767 HTTP/1.1", upstream: "http://127.0.0.1:4105/html5client/compatibility/sip.js?v=1767", host: "meeting1.mydomain.ca", referrer: "https://meeting1.mydomain.ca/html5client/join?sessionToken=abcmytockenxyz"`

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Safari
 - Version [ 2.3.3]

**Additional context**
I think it is something wrong with the location resolution order in **/etc/bigbluebutton/nginx/bbb-html5.nginx** . It seems to me that the last statement in the nginx config file gets processed first ( location ~ ^/html5client/ ). It requests static resources from Meteor. A Meteor process doesn't have requested resources and returns errors and than nginx retrieves resources from correct locations (location /html5client/compatibility).

According to  [nginx documentation](https://nginx.org/en/docs/http/ngx_http_core_module.html#location)
_Then regular expressions are checked, in the order of their appearance in the configuration file. The search of regular expressions terminates on the first match, and the corresponding configuration is used. If no match with a regular expression is found then the configuration of the prefix location remembered earlier is used._

Here is the content of the configuration file  bbb-html5 2.3.0-1767 :
```
location /html5client/locales {
  alias /usr/share/meteor/bundle/programs/web.browser/app/locales;
}

location /html5client/compatibility {
  alias /usr/share/meteor/bundle/programs/web.browser/app/compatibility;
}

location /html5client/resources {
  alias /usr/share/meteor/bundle/programs/web.browser/app/resources;
}

location /html5client/svgs {
  alias /usr/share/meteor/bundle/programs/web.browser/app/svgs;
}

location /html5client/fonts {
  alias /usr/share/meteor/bundle/programs/web.browser/app/fonts;
}

location ~ ^/html5client/ {
  # proxy_pass http://127.0.0.1:4100; # use for development
  proxy_pass http://poolhtml5servers; # use for production
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
}
```
And the same file in bbb-html5 2.2.0 (1157) has the last section a bit different:
```
location /html5client {
  alias /usr/share/meteor/bundle/programs/web.browser;
  try_files $uri @html5client;
}

location @html5client {
  proxy_pass http://127.0.0.1:3000;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
}
```

**Comment by uka-support** [comment] 2021-06-17 09:06
This is a duplicate of #12291 - see there for the cause.

**Comment by antobinary** [comment] 2021-06-17 10:52
Merging into #12291

**Closed by antobinary** 2021-06-17 10:52 UTC
Labels: module: core
