### ISSUE TITLE
v2.3dev webcamsDefaultPlacement does nothing

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#11627] opened 2021-03-12 01:58 UTC
`bbb-install` command with `bionic-230-dev`

```
sudo yq w -i /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml public.layout.webcamsDefaultPlacement "left"

sudo bbb-conf restart
```

Create a meeting.
Share cam.

Camera starts at the top. It should start on the left.

**Comment by basisbit** [comment] 2021-03-12 02:18
looks like a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/9532
Please create a pull request to get your suggested change applied.

**Closed by basisbit** 2021-03-12 02:18 UTC
Labels: HTML5 Client

**Comment by aogilvie** [comment] 2021-03-12 05:17
@basisbit technically it's for a different version. 2.2 does not support side cams. Only 2.3 supports side cams. But in both major branches the setting does nothing. Previous issue was not tagged as part of 2.3 sprint. Posting above for clarity.
Anyway thanks.

**Comment by basisbit** [comment] 2021-03-12 09:32
Then please update your previous issue for the current version, as that is where this would have to be fixed. There is no use in having more than one open issue for that
