### ISSUE TITLE
Avatar img doesn't shows up by passing it throught php api

### ISSUE THREAD

**Issue by shiwamavg** [bigbluebutton/bigbluebutton#9325] opened 2020-04-29 08:26 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by frank-miller9** [comment] 2020-04-30 16:04
See: https://github.com/bigbluebutton/bigbluebutton/issues/8566

**Comment by GhaziTriki** [comment] 2020-05-05 11:56
Duplicate of #8566. The avatar image was in the Flash client and it is planned to be implemented in the HTML5 client.

**Closed by GhaziTriki** 2020-05-05 11:56 UTC
