### ISSUE TITLE
Preview of User Avatar on video containers if Webcam Disabled

### ISSUE THREAD

**Issue by NarsimaChilkuri** [bigbluebutton/bigbluebutton#16346] opened 2022-12-24 14:58 UTC
Showing User Avatar on video containers if Webcam Disabled with some animations of Reconnecting (if connection gets lost)

**Comment by antobinary** [comment] 2023-02-01 11:20
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/13844

**Closed by antobinary** 2023-02-01 11:20 UTC
Labels: type: enhancement
