### ISSUE TITLE
Shared Notes: Etherpad not working - 404 Not Found

### ISSUE THREAD

**Issue by baltaner** [bigbluebutton/bigbluebutton#11565] opened 2021-03-05 15:14 UTC
Hello,
after updating from BigBlueButton 2.2.33 to BigBlueButton 2.2.35
I get an 404 Not Found error when accessing the shared notes.
I do everything like everytime - apt update && apt upgrade and after that a complete

`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -s....`

Any ideas?

**Comment by pedrobmarin** [comment] 2021-03-05 16:04
Hi @baltaner ,

Is your Etherpad's service running?
`sudo systemctl status etherpad`

If it's not, could you check the logs if there is something blocking from starting?
`sudo journalctl -u etherpad` (usually the last lines are the ones that matter)

**Comment by DanielW1064** [comment] 2021-03-05 18:57
Hi,

I have the same problem. After upgrading to BigBlueButton 2.2.35 I just get an 404 Not Found error wenn accssing the shared notes.
Etherpad´s service ist running:

`
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
`

`
● etherpad.service - Etherpad Server
   Loaded: loaded (/usr/lib/systemd/system/etherpad.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-03-05 19:30:45 CET; 22min ago
 Main PID: 28018 (node)
    Tasks: 11
   Memory: 50.2M
      CPU: 3.114s
   CGroup: /system.slice/etherpad.service
           └─28018 /usr/bin/node node_modules/ep_etherpad-lite/node/server.js
`

sudo journalctl -u etherpad (only the last lines):
`
Mar 03 19:59:02 dbhserver1 node[23883]: [2021-03-03 19:59:02.106] [ERROR] console - [ep_pad_ttl] apierror: padID does not exist
Mar 03 19:59:02 dbhserver1 node[23883]: [2021-03-03 19:59:02.106] [ERROR] console - [ep_pad_ttl] apierror: padID does not exist
Mar 03 19:59:02 dbhserver1 node[23883]: [2021-03-03 19:59:02.106] [ERROR] console - [ep_pad_ttl] apierror: padID does not exist
Mar 03 19:59:02 dbhserver1 node[23883]: [2021-03-03 19:59:02.106] [ERROR] console - [ep_pad_ttl] apierror: padID does not exist
Mar 03 19:59:02 dbhserver1 node[23883]: [2021-03-03 19:59:02.106] [ERROR] console - [ep_pad_ttl] apierror: padID does not exist
Mar 03 19:59:02 dbhserver1 node[23883]: [2021-03-03 19:59:02.106] [ERROR] console - [ep_pad_ttl] apierror: padID does not exist
Mar 03 19:59:02 dbhserver1 node[23883]: [2021-03-03 19:59:02.106] [ERROR] console - [ep_pad_ttl] apierror: padID does not exist
Mar 03 19:59:02 dbhserver1 node[23883]: [2021-03-03 19:59:02.106] [ERROR] console - [ep_pad_ttl] apierror: padID does not exist
Mar 03 19:59:02 dbhserver1 node[23883]: [2021-03-03 19:59:02.106] [ERROR] console - [ep_pad_ttl] apierror: padID does not exist
Mar 03 19:59:02 dbhserver1 node[23883]: [2021-03-03 19:59:02.106] [ERROR] console - [ep_pad_ttl] apierror: padID does not exist
`

**Comment by pedrobmarin** [comment] 2021-03-05 19:18
Hi @DanielW1064 ,

`[ERROR] console - [ep_pad_ttl] apierror: padID does not exist` might be happening because there is still old pad's data at redis. There's been an extensive discussion about it in this other issue https://github.com/bigbluebutton/bigbluebutton/issues/11497.

Regarding the 404 error, maybe there is something wrong with the proxy configuration in nginx or your html5 client's settings.

`/etc/bigbluebutton/nginx/notes.nginx` should look like:
```
# https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy
location /pad/p/ {
    rewrite /pad/p/(.*) /p/$1 break;
    rewrite ^/pad/p$ /pad/p/ permanent;
    proxy_pass http://localhost:9001/p;
    proxy_pass_header Server;
    proxy_redirect /p /pad/p;
    proxy_set_header Host $host;
    proxy_buffering off;

    proxy_set_header X-Real-IP $remote_addr;  # http://wiki.nginx.org/HttpProxyModule
    proxy_set_header X-Forwarded-For $remote_addr; # EP logs to show the actual remote IP
    proxy_set_header X-Forwarded-Proto $scheme; # for EP to set secure cookie flag when https is used
    proxy_http_version 1.1;

    auth_request /bigbluebutton/connection/validatePad;
    auth_request_set $auth_status $upstream_status;
}

location /pad {
    rewrite /pad/(.*) /$1 break;
    rewrite ^/pad$ /pad/ permanent;
    proxy_pass http://localhost:9001/;
    proxy_pass_header Server;
    proxy_redirect / /pad/;
    proxy_set_header Host $host;
    proxy_buffering off;
}

location /pad/socket.io/socket.io.js {
    rewrite /pad/socket.io/socket.io.js /socket.io/socket.io.js break;
    proxy_pass http://localhost:9001/;
    proxy_set_header Host $host;
    proxy_buffering off;
}
    
location /pad/socket.io {
    rewrite /pad/socket.io/(.*) /socket.io/$1 break;
    proxy_pass http://localhost:9001/;
    proxy_redirect / /pad/;
    proxy_set_header Host $host;
    proxy_buffering off;
    proxy_set_header X-Real-IP $remote_addr;  # http://wiki.nginx.org/HttpProxyModule
    proxy_set_header X-Forwarded-For $remote_addr; # EP logs to show the actual remote IP
    proxy_set_header X-Forwarded-Proto $scheme; # for EP to set secure cookie flag when https is used
    proxy_set_header Host $host;  # pass the host header
    proxy_http_version 1.1;  # recommended with keepalive connections
    # WebSocket proxying - from http://nginx.org/en/docs/http/websocket.html
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";

    auth_request /bigbluebutton/connection/checkAuthorization;
    auth_request_set $auth_status $upstream_status;
}

location /static {
    rewrite /static/(.*) /static/$1 break;
    proxy_pass http://localhost:9001/;
    proxy_set_header Host $host;
    proxy_buffering off;
}
```

And client settings at `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` with this adjusts:
```
...
  note:
    enabled: true
    url: https://bbb.example.com/pad
...
```

**Comment by baltaner** [comment] 2021-03-05 19:21
Hi @pedrobmarin,
thank's  - but etherpad is up and running.
I can access etherpad with
`wget http://127.0.0.1:9001
`
/var/log/nginx:
```
2021/03/05 20:16:11 [error] 24129#24129: *55679 auth request unexpected status: 500 while sending to client,
2021/03/05 20:16:11 [error] 24129#24129: *55679 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory),
```
Thanks for looking at it!

**Comment by pedrobmarin** [comment] 2021-03-05 19:24
Hi @baltaner , could you check if the problem is the missing **https** configuration at the client's settings?

**Comment by DanielW1064** [comment] 2021-03-05 19:32
Hi @pedrobmarin,

my /etc/bigbluebutton/nginx/notes.nginx - I could not find a difference:

```
# https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy
location /pad/p/ {
    rewrite /pad/p/(.*) /p/$1 break;
    rewrite ^/pad/p$ /pad/p/ permanent;
    proxy_pass http://localhost:9001/p;
    proxy_pass_header Server;
    proxy_redirect /p /pad/p;
    proxy_set_header Host $host;
    proxy_buffering off;

    proxy_set_header X-Real-IP $remote_addr;  # http://wiki.nginx.org/HttpProxyModule
    proxy_set_header X-Forwarded-For $remote_addr; # EP logs to show the actual remote IP
    proxy_set_header X-Forwarded-Proto $scheme; # for EP to set secure cookie flag when https is used
    proxy_http_version 1.1;

    auth_request /bigbluebutton/connection/validatePad;
    auth_request_set $auth_status $upstream_status;
}

location /pad {
    rewrite /pad/(.*) /$1 break;
    rewrite ^/pad$ /pad/ permanent;
    proxy_pass http://localhost:9001/;
    proxy_pass_header Server;
    proxy_redirect / /pad/;
    proxy_set_header Host $host;
    proxy_buffering off;
}

location /pad/socket.io/socket.io.js {
    rewrite /pad/socket.io/socket.io.js /socket.io/socket.io.js break;
    proxy_pass http://localhost:9001/;
    proxy_set_header Host $host;
    proxy_buffering off;
}
    
location /pad/socket.io {
    rewrite /pad/socket.io/(.*) /socket.io/$1 break;
    proxy_pass http://localhost:9001/;
    proxy_redirect / /pad/;
    proxy_set_header Host $host;
    proxy_buffering off;
    proxy_set_header X-Real-IP $remote_addr;  # http://wiki.nginx.org/HttpProxyModule
    proxy_set_header X-Forwarded-For $remote_addr; # EP logs to show the actual remote IP
    proxy_set_header X-Forwarded-Proto $scheme; # for EP to set secure cookie flag when https is used
    proxy_set_header Host $host;  # pass the host header
    proxy_http_version 1.1;  # recommended with keepalive connections
    # WebSocket proxying - from http://nginx.org/en/docs/http/websocket.html
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";

    auth_request /bigbluebutton/connection/checkAuthorization;
    auth_request_set $auth_status $upstream_status;
}

location /static {
    rewrite /static/(.*) /static/$1 break;
    proxy_pass http://localhost:9001/;
    proxy_set_header Host $host;
    proxy_buffering off;
}
```

```
note:
    enabled: true
    url: https://bbb.dbh-fachverband.de/pad
```

**Comment by pedrobmarin** [comment] 2021-03-05 19:41
@DanielW1064 can you try this out https://github.com/bigbluebutton/bigbluebutton/issues/11497#issuecomment-788880841 and restarting your server?

**Comment by baltaner** [comment] 2021-03-05 19:43
Hi @pedrobmarin,
same here - no differences in both files (/etc/bigbluebutton/nginx/notes.nginx and /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml)

> Hi @baltaner , could you check if the problem is the missing **https** configuration at the client's settings?
I'm not sure what exactly you mean - my bbb-server works with https, certificate is a valid (let's encrypt).

I can access etherpad with
`wget http://127.0.0.1:9001`
from my bbb-server
If I try to access with
`wget http://127.0.0.1:9001`
I get an error:
```
--2021-03-05 20:41:03--  https://127.0.0.1:9001/
Connecting to 127.0.0.1:9001... connected.
Unable to establish SSL connection.
```

**Comment by DanielW1064** [comment] 2021-03-05 19:51
@pedrobmarin thanks. I restartet the server. Unfortunately etherpad is still not available (404).

/var/log/nginx/error.log:

```
2021/03/05 20:44:02 [error] 1659#1659: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 2a01:4f8:13b:3529::2, server: bbb.dbh-fachverband.de, request: "GET /bigbluebutton/api/getMeetings?checksum=64f08eb79aacbd1115539773a77284fcc777ffd9 HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/api/getMeetings?checksum=64f08eb79aacbd1115539773a77284fcc777ffd9", host: "bbb.dbh-fachverband.de"
2021/03/05 20:44:02 [error] 1659#1659: *1 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 2a01:4f8:13b:3529::2, server: bbb.dbh-fachverband.de, request: "GET /bigbluebutton/api/getMeetings?checksum=64f08eb79aacbd1115539773a77284fcc777ffd9 HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/api/getMeetings?checksum=64f08eb79aacbd1115539773a77284fcc777ffd9", host: "bbb.dbh-fachverband.de"
2021/03/05 20:44:02 [error] 1665#1665: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 2a01:4f8:13b:3529::2, server: bbb.dbh-fachverband.de, request: "GET /bigbluebutton/api/getRecordings?checksum=98ee5a55d484ad28d8d9af7cae4392fa38c3e112&state=unpublished HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/api/getRecordings?checksum=98ee5a55d484ad28d8d9af7cae4392fa38c3e112&state=unpublished", host: "bbb.dbh-fachverband.de"
2021/03/05 20:44:02 [error] 1665#1665: *3 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 2a01:4f8:13b:3529::2, server: bbb.dbh-fachverband.de, request: "GET /bigbluebutton/api/getRecordings?checksum=98ee5a55d484ad28d8d9af7cae4392fa38c3e112&state=unpublished HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/api/getRecordings?checksum=98ee5a55d484ad28d8d9af7cae4392fa38c3e112&state=unpublished", host: "bbb.dbh-fachverband.de"
2021/03/05 20:45:16 [error] 1665#1665: *48 auth request unexpected status: 500 while sending to client, client: 37.201.193.62, server: bbb.dbh-fachverband.de, request: "GET /pad/p/30587b4d4f5d04ba7bf9a8a2490c29dac87af5cd?userName=DBH&lang=de&rtl=false&sessionToken=uirokmrgpjchzuah HTTP/1.1", host: "bbb.dbh-fachverband.de", referrer: "https://bbb.dbh-fachverband.de/html5client/join?sessionToken=uirokmrgpjchzuah"
2021/03/05 20:45:16 [error] 1665#1665: *48 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 37.201.193.62, server: bbb.dbh-fachverband.de, request: "GET /pad/p/30587b4d4f5d04ba7bf9a8a2490c29dac87af5cd?userName=DBH&lang=de&rtl=false&sessionToken=uirokmrgpjchzuah HTTP/1.1", host: "bbb.dbh-fachverband.de", referrer: "https://bbb.dbh-fachverband.de/html5client/join?sessionToken=uirokmrgpjchzuah"
2021/03/05 20:46:05 [error] 1659#1659: *140 auth request unexpected status: 500 while sending to client, client: 2a02:908:381:9a1:b970:8623:92c3:e07d, server: bbb.dbh-fachverband.de, request: "GET /pad/p/30587b4d4f5d04ba7bf9a8a2490c29dac87af5cd?userName=DBH&lang=de&rtl=false&sessionToken=uirokmrgpjchzuah HTTP/1.1", host: "bbb.dbh-fachverband.de"
2021/03/05 20:46:05 [error] 1659#1659: *140 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 2a02:908:381:9a1:b970:8623:92c3:e07d, server: bbb.dbh-fachverband.de, request: "GET /pad/p/30587b4d4f5d04ba7bf9a8a2490c29dac87af5cd?userName=DBH&lang=de&rtl=false&sessionToken=uirokmrgpjchzuah HTTP/1.1", host: "bbb.dbh-fachverband.de"
2021/03/05 20:46:08 [error] 1659#1659: *130 auth request unexpected status: 500 while sending to client, client: 37.201.193.62, server: bbb.dbh-fachverband.de, request: "GET /pad/p/30587b4d4f5d04ba7bf9a8a2490c29dac87af5cd?userName=DBH&lang=de&rtl=false&sessionToken=uirokmrgpjchzuah HTTP/1.1", host: "bbb.dbh-fachverband.de", referrer: "https://bbb.dbh-fachverband.de/html5client/join?sessionToken=uirokmrgpjchzuah"
2021/03/05 20:46:08 [error] 1659#1659: *130 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 37.201.193.62, server: bbb.dbh-fachverband.de, request: "GET /pad/p/30587b4d4f5d04ba7bf9a8a2490c29dac87af5cd?userName=DBH&lang=de&rtl=false&sessionToken=uirokmrgpjchzuah HTTP/1.1", host: "bbb.dbh-fachverband.de", referrer: "https://bbb.dbh-fachverband.de/html5client/join?sessionToken=uirokmrgpjchzuah"

**Comment by pedrobmarin** [comment] 2021-03-05 19:59
@DanielW1064 check your bbb-web log at `/var/log/bigbluebutton/bbb-web.log` and see if there is any exception being thrown there

**Comment by DanielW1064** [comment] 2021-03-05 20:05
@pedrobmarin,
perhaps this is relevant:

```
2021-03-05T19:31:57.699+01:00 ERROR o.g.w.e.GrailsExceptionResolver - NullPointerException occurred when processing request: [GET] /bigbluebutton/connection/validatePad
Stacktrace follows:
java.lang.NullPointerException: null
	at java.net.URLDecoder.decode(URLDecoder.java:136)
	at org.bigbluebutton.api.util.ParamsUtil.getSessionToken(ParamsUtil.java:39)
	at org.bigbluebutton.web.controllers.ConnectionController$_closure2.doCall(ConnectionController.groovy:51)
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-05T19:31:57.707+01:00 ERROR o.a.c.c.C.[.[.[.[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'] with root cause
javax.servlet.ServletException: Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1266)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2021-03-05T19:31:57.710+01:00 ERROR o.a.c.c.C.[.[.[.[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] threw exception
javax.servlet.ServletException: Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1266)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:472)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:395)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:254)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:349)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:175)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pedrobmarin** [comment] 2021-03-05 20:16
It does, @DanielW1064 . I'll take a closer look. Thanks

**Comment by baltaner** [comment] 2021-03-05 20:21
Hi @pedrobmarin,
same here:
```
2021-03-05T20:47:46.735+01:00 ERROR o.g.w.e.GrailsExceptionResolver - NullPointerException occurred when processing request: [GET] /bigbluebutton/connection/validatePad
Stacktrace follows:
java.lang.NullPointerException: null
2021-03-05T20:47:46.739+01:00 ERROR o.a.c.c.C.[.[.[.[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'] with root cause
javax.servlet.ServletException: Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1266)

```

**Comment by pedrobmarin** [comment] 2021-03-05 20:24
You can both try replacing `auth_request /bigbluebutton/connection/validatePad;` with `auth_request /bigbluebutton/connection/checkAuthorization;` at the nginx file while we investigate this further

**Comment by DanielW1064** [comment] 2021-03-05 20:38
this worked! 
thanks for the quick help!

**Comment by baltaner** [comment] 2021-03-05 21:40
Thank you - works for my too!

**Comment by hex-m** [comment] 2021-03-08 13:23
I had the same problem and the fix worked for me too.

In my case the problem appeared when the server was updated from `xenial-220-dev22a` to `2.2.35`.

**Comment by Supersonic112** [comment] 2021-03-08 22:50
> You can both try replacing `auth_request /bigbluebutton/connection/validatePad;` with `auth_request /bigbluebutton/connection/checkAuthorization;` at the nginx file and reload nginx with `sudo systemctl reload nginx` while we investigate this further

I have several BBB instances (with 2.2.35, updated using the latest bbb-install.sh) which showed the error 401 instead of shared notes. This modification fixed the issue here, too :)

**Comment by spreeni151** [comment] 2021-03-09 10:40
Just a thought: Could this be a new issue, maybe a compatibility issue with firefox 86.0?

**Comment by pedrobmarin** [comment] 2021-03-09 11:36
Hi @spreeni151 . Can you check if the problem persist in private tabs? This looks like might be related with old cookies as described in https://github.com/bigbluebutton/bigbluebutton/issues/11497#issuecomment-791356293 .

**Comment by spreeni151** [comment] 2021-03-09 11:47
Thank you very much @pedrobmarin ! In private tabs the shared notes are shown. So I can give my students a quick tip for a work-around. So, you could be right with the cookies, although other browsers don't have problems with it. 
What do you think, is there something I can do about it in my configuration or do I have to wait for one of the next updates?

**Comment by pedrobmarin** [comment] 2021-03-09 12:12
Unfortunately there is this inconvenience with cookies right now, sorry about that. Each browser can deal with cookies a little bit different and user's add-ons can affect it too. We already changed our Etherpad fork to avoid settings resilient cookies but I believe this will only be available in the next release (can't say what day will that be).

**Comment by spreeni151** [comment] 2021-03-09 13:24
Thank you, pedrobmarin, for explanation. This makes the problem much clearer to me. Its good to know, that a solution is in development. Have a nice day :-)

**Comment by odenbach** [comment] 2021-03-10 14:36
I just had the same problem. Here it was something completely different: The new package contains a new version of /etc/bigbluebutton/nginx/web. New are the lines

                location = /bigbluebutton/connection/validatePad {
                        internal;
                        proxy_pass               http://127.0.0.1:8090;
                        proxy_pass_request_body  off;
                        proxy_set_header         Content-Length "";
                        proxy_set_header         X-Original-URI $request_uri;
                }

The problem was that we used apply-config.sh to change some values in this file (mainly to increase maximum upload size) . Debian realized that we had modified a config file and did not overwrite it. Instead the new version was installed as web.dpkg-dist.

So all I had to do was rename web.dpkg-dist to web, re-apply our modifications by running apply-config.sh and then reload nginx. After that everything worked again as expected.

**Comment by hex-m** [comment] 2021-03-10 17:52
Thanks @odenbach! From `/var/log/apt/term.log`:

```
Configuration file '/etc/bigbluebutton/nginx/web'                                                                                                 
 ==> Modified (by you or by a script) since installation.                                                                                         
 ==> Package distributor has shipped an updated version.                                                                                          
   What would you like to do about it ?  Your options are:                                                                                        
    Y or I  : install the package maintainer's version                                                                                            
    N or O  : keep your currently-installed version                                                                                               
      D     : show the differences between the versions                                                                                           
      Z     : start a shell to examine the situation                                                                                              
 The default action is to keep your current version.                                                                                              
*** web (Y/I/N/O/D/Z) [default=N] ?
```

I suggested in [another issue](https://github.com/bigbluebutton/bbb-install/issues/330) that `bbb-install.sh` should overwrite local changes, as lasting changes should be (re-)applied with `apply-config.sh`.

**Comment by baltaner** [comment] 2021-03-10 21:46
Hello @pedrobmarin,
for me the suggestion from @odenbach worked!
That mean: 
```
rename web.dpkg-dist to web, redo your suggested changes to the nginx file, re-run bbb-install.sh
```
The problem was the /etc/bigbluebutton/nginx/web - file which wasn't updated correctly.

**Comment by blastrider** [comment] 2021-03-22 12:48
> You can both try replacing `auth_request /bigbluebutton/connection/validatePad;` with `auth_request /bigbluebutton/connection/checkAuthorization;` at the nginx file and reload nginx with `sudo systemctl reload nginx` while we investigate this further

This worked for met too, why doen't it come by default ? I mean in the original package while installing BBB ?
And what's precisely happening while requesting validatePad/checkAuthorization ?

**Comment by pedrobmarin** [comment] 2021-03-22 12:54
@blastrider I can't tell if there is an unique problem going on. The one that makes more sense to me right now is this https://github.com/bigbluebutton/bigbluebutton/issues/11565#issuecomment-795508979. `validatePad` should work on a clean deploy.

**Comment by blastrider** [comment] 2021-03-22 12:58
> @blastrider I can't tell if there is an unique problem going on. The one that makes more sense to me right now is this [#11565 (comment)](https://github.com/bigbluebutton/bigbluebutton/issues/11565#issuecomment-795508979). `validatePad` should work on a clean deploy.

In all cases thank a lot for your work !

**Comment by pedrobmarin** [comment] 2021-04-01 19:42
We made several changes for Etherpad and released in https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.36. I'll close this issue and,if anything new comes up we can discuss in a new issue to avoid confusion.

**Closed by pedrobmarin** 2021-04-01 19:42 UTC

**Comment by premmohantyagi** [comment] 2022-01-07 17:50
Thanks- works for my also
