### ISSUE TITLE
BBB 2.3-dev Start meeting from Greenlight and never get to BigBlueButton

### ISSUE THREAD

**Issue by caniwi** [bigbluebutton/bigbluebutton#10328] opened 2020-08-26 05:32 UTC
**Describe the bug**
Start a meeting from Greenlight.  Get the animated 3 cirlces and the BBB blue background.  Never goes any further.

**To Reproduce**
1. Log into Greenlight
2. Click on Start or Join for your home room
3. Get blue screen

**Expected behavior**
You would get an echo test, notepad, chat and default presentation.

**Actual behavior**
Seems to fail before the echo test starts.

**Screenshots**
see attached bbb-23-devtools-output.txt

**BBB version (optional):**
bbb-conf --version

ii  bbb-apps-akka                               2.3.0-2                                         all          BigBlueButton Apps (Akka)
ii  bbb-config                                  1:2.3.0-5                                       amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                                1:2.3.0-1                                       amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                         2:2.3.0-2                                       amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                       1:1.6.7-1                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                              2.3.0-1                                         all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                                   1:2.3.0-1008                                    amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                                 1:0.8.7-1                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation                   1:2.3.0-2                                       amd64        BigBluebutton playback of presentation
ii  bbb-record-core                             1:2.3.0-3                                       amd64        BigBlueButton record and playback
ii  bbb-transcode-akka                          2.3.0-1                                         all          BigBlueButton Transcoder
ii  bbb-web                                     1:2.3.0-1                                       amd64        BigBlueButton API
ii  bbb-webrtc-sfu                              1:2.3.0-1                                       amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                               1:2.3.0-4                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                      7:4.2.2-1bbb1~ubuntu18.04                       amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                          7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                         7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                          7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                         7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                        7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                           7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                                 0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                         7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                        7:4.2.2-1bbb1~ubuntu18.04                       amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox 79 Google Chrome 84

**Additional context**
Attached syslog output

**Comment by caniwi** [comment] 2020-08-26 05:36
[bbb-23-devtools-output.txt](https://github.com/bigbluebutton/bigbluebutton/files/5127776/bbb-23-devtools-output.txt)
[bbb-23-syslog.txt](https://github.com/bigbluebutton/bigbluebutton/files/5127777/bbb-23-syslog.txt)

**Comment by ffdixon** [comment] 2020-08-26 10:31
The next update to BigBlueButton 2.3-dev (coming soon) will have the fix for this issue.  We'll notify users when it's available with a post to [bigblueubtton-dev](https://groups.google.com/forum/#!forum/bigbluebutton-dev).

**Comment by caniwi** [comment] 2020-08-26 23:42
Thanks ffdixon.

**Comment by peternagelsa** [comment] 2020-08-27 07:50
Good morning. I would like to comment on this issue, it might be helpful to the developers. The issue is well known by now (Get the animated 3 cirlces and the BBB blue background. Never goes any further), let me reiterate my install:

Ubuntu 18.04
BBB 2.3Dev 
Greenlight 2.7.1

Nextcloud 19.0.1
(a) Adding the API credentials in my Nextcloud install works (the API URL and secret key is accepted)
(b) Rooms can be created by joining the room produces the same error as stated above

Moodle 3.9.1
(a) Adding the API credentials in my Moodle install works (the API URL and secret key is accepted)
(b) Rooms can be created and joined and DOES NOT produce the same error as stated above. What is obviuosly different, or at least to me, is that in Moodle you can acctually determine who the moderator would be, thus you do not join as 'owner' of the room but as moderator

This might not mean anything, but I thought of sharing it anyway 

Peter

**Comment by g-v-egidy** [comment] 2020-08-28 12:45
Is there a workaround available until the next release? Like manually patching a file or similar?

**Comment by bjo81** [comment] 2020-08-31 07:39
Fixed in 2.3-alpha-2

**Comment by peternagelsa** [comment] 2020-08-31 08:09
Just to report, it has been fixed in 2.3-alpha-2, thanks to all the developers!

**Closed** 2020-08-31 08:44 UTC
Labels: HTML5 Client
