### ISSUE TITLE
Exclude chat and other content from being recorded

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#2837] opened 2015-10-15 15:05 UTC
Sometimes, in a meeting, there is a need to not record some content (e.g. chat). Allow the moderator or presenter to choose which content to be recorded.

**Comment by pedrobmarin** [comment] 2021-04-16 18:16
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11122

**Closed by pedrobmarin** 2021-04-16 18:16 UTC
Labels: component: chat, type: enhancement
