### ISSUE TITLE
BBB does not respect the maxParticipants parameter

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/bigbluebutton#9078] opened 2020-04-14 11:26 UTC
We rely on `maxParticipants` on our app and it is very essential to us.
We encounter many bugs with it.

**To Reproduce**
1. Go to https://mconf.github.io/api-mate/
2. Set `maxParticipants` to 4
3. Create a meating
4. join as moderator/moderator (1 Participant)
5. join as moderator/moderator (2 Participants)
6. join as moderator/moderator (3 Participants)
7. join as moderator/moderator (4 participants) -> Redirect to https://blindsidenetworks.com/ 
In practice this an error of reaching the max participants. This is from the browser devtool:
```
https://t012.rna1.blindsidenetworks.com/?errors=[%7B%22message%22:%22The%20number%20of%20participants%20allowed%20for%20this%20meeting%20has%20been%20reached.%22,%22key%22:%22maxParticipantsReached%22%7D]
```
8. Logout as one of the attendee (Now there is just 2 participants)
9. join as attendee (or moderator) -> same error.
10. Wait some arbitrary time and maybe you can able to join (sometimes can sometimes can not)

Another issue is when a room gets too many joins in same time. The limit of `maxParticipants` do not get respected at all. Rooms with 150 max participants get attendee of ~400 participants.

**Comment by jibon57** [comment] 2020-04-14 15:34
Issue had been opened already: https://github.com/bigbluebutton/bigbluebutton/issues/8990

**Comment by pedrobmarin** [comment] 2020-04-14 15:44
#8510

**Comment by matiasilva** [comment] 2020-06-15 10:38
Closing as it is a duplicate of the above mentioned issues.

**Closed by matiasilva** 2020-06-15 10:38 UTC
