### ISSUE TITLE
Screen share problem if Youtube video is playing

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#7707] opened 2019-07-01 17:05 UTC
If you start and stop a screen share while a Youtube video is playing then you stop the Youtube video the presentation area keep stuck on spinning arrows.

**Comment by prlanzarin** [comment] 2019-07-01 17:13
This is a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/7439.

**Closed** 2019-07-01 17:13 UTC
