### ISSUE TITLE
Customize the Layout of HTML5Client

### ISSUE THREAD

**Issue by NiceboyWiseboy** [bigbluebutton/bigbluebutton#9333] opened 2020-04-29 12:24 UTC
Hello,
 
I want to customize the layout of HTML5Client. Is there a way to do it?

Thank you,
Best Regards

**Comment by frank-miller9** [comment] 2020-04-29 13:02
See: http://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client

**Comment by Entretoize** [comment] 2020-05-04 18:20
Is there anything more complicated ?

**Comment by NiceboyWiseboy** [comment] 2020-05-16 10:35
> See: http://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client

Followed the guide, but the meeting doesn't start.
Also tried to build the code into METEOR PRODUCTION APP, but  also didn't got worked out as well.

**Comment by iSamof** [comment] 2020-05-16 11:11
Just FYI - the dev team are working on a Layout Editor. If your requirement is not super urgent and critical, you may want to wait for the Layout Editor. That is what we are doing.

**Comment by basisbit** [comment] 2020-06-08 12:56
Duplicate of #5836

**Closed by basisbit** 2020-06-08 12:56 UTC
Labels: HTML5 Client
