### ISSUE TITLE
BigBlueButton should return an error on meeting creation for invalid meeting_id, meeting_name, etc.

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#3245] opened 2016-07-28 19:37 UTC
We need to define what set of characters are allowed in the various parameters of the meeting create call, and validate that the parameters follow those rules (returning an error if invalid characters are provided).

Some examples of things we have seen cause issues:
`meetingID` containing a `,` character results in a working meeting, but you can't look up recordings for it later because `,` is a special character in the recording lookup.
A copy-pasted `0x0b` (LINE TABULATION) in the `name` field was allowed on the create call, but the BigBlueButton client failed to load in the live session.

**Comment by ffdixon** [comment] 2016-07-28 19:42
> A copy-pasted 0x0b (LINE TABULATION) in the name field was allowed on the create call, but the BigBlueButton client failed to load in the live session.

For this case, it might be better to strip out such 'gremlins'.  Otherwise, if we return an error message such as "Invalid Character in the name", since the character is invisible, the user might not realize the cause.

**Comment by capilkey** [comment] 2016-07-28 19:44
Either strip it out or replace with a "safe" character like "-".

**Comment by kepstin** [comment] 2016-07-28 19:47
Alright, I agree that for user-readable text fields, it probably makes sense to strip characters rather than return an error. In this case, I'd probably suggest either removing or replacing all characters marked as "control" characters in the unicode specs (Type `Cc`)

For programmatic stuff like the meetingID field, I would still prefer to return an error (meetingID should be autogenerated by software, not manually entered by users)

**Comment by ritzalam** [comment] 2017-03-16 15:58
I am setting the following as the valid chars for external meeting id.

private static final Pattern VALID_ID_PATTERN = Pattern.compile("[a-zA-Z][a-zA-Z0-9- ]*$");

Also I am replacing control chars in the meeting name to '?'

  public static String stripControlChars(String text) {
    return text.replaceAll("\\p{Cc}", "?");
  }

I notice that the name is optional and we set the name to "" if not passed. Can't we make this required? Or set a default meeting name?

**Comment by kepstin** [comment] 2017-03-16 16:05
This is far too restrictive:
`Pattern.compile("[a-zA-Z][a-zA-Z0-9- ]*$");`
we have several integrations using meeting ids containing e.g. underscores which would fail with this system.
For now, my suggestion is to only reject meeting IDs which contain a comma `,` - we can do some analysis and figure out what other restrictions to apply later.

For control characters, I suggest completely removing them (replace with empty string) rather than using '?' since they're usually invisible anyways.

**Comment by ffdixon** [comment] 2017-03-21 17:49
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/3735

**Closed by ffdixon** 2017-03-21 17:49 UTC
Labels: API, Docs, Web
