### ISSUE TITLE
Textbox in whiteboard stopped working for Firefox users

### ISSUE THREAD

**Issue by agru** [bigbluebutton/bigbluebutton#11522] opened 2021-03-01 08:29 UTC
After upgrading from 2.2.31 to 2.2.33 the whiteboard textbox stopped working in Firefox. Users are able to select the tool, can draw the rectangle are for the text field, but after releasing the mouse button the area disappears and it is not possible to enter characters.

Issue is confirmed for Firefox 85.* and 86* on Linux, 78.5.0 ESR and 86 on Windows.

**Comment by Subdarub** [comment] 2021-03-01 08:41
Can confirm Firefox 86 on Windows.

Google Chrome (88) is fine , so is chromium edge (88)

**Comment by lonesomewalker** [comment] 2021-03-01 09:04
fixed by #11477

**Comment by prlanzarin** [comment] 2021-03-01 13:19
Duplicate of #10744.

**Closed by prlanzarin** 2021-03-01 13:19 UTC
