### ISSUE TITLE
Slides on second Screen

### ISSUE THREAD

**Issue by FabianCernota** [bigbluebutton/bigbluebutton#9174] opened 2020-04-21 07:13 UTC
Hello,
is it possible to display the presentation on a second screen? Then you can see the video chats better and display the slides in full size.

Greetings
Fabs

**Comment by prlanzarin** [comment] 2021-04-05 00:38
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11403

(that one is better described and also tethered to an open PR that actually tackles this)

**Closed by prlanzarin** 2021-04-05 00:38 UTC
Labels: type: enhancement
