### ISSUE TITLE
Recorded session - video doesn't match audio after BBB 2.2.3

### ISSUE THREAD

**Issue by peterpetrov** [bigbluebutton/bigbluebutton#9139] opened 2020-04-18 20:40 UTC
**Describe the bug**
When recording a session since BBB 2.2.3 the video seems to be "stretched". It start fine with barely noticed delay but at the end the video does look like going with a second or more delay. In fact it looks like video length is more than the audio and the delay is gradual. 

**To Reproduce**
Record a session with camera on for 30 min. Then talk at the end of the session in front of the camera. After the recording is ready check it out in the start, middle and the end. Longer recordings have longer delay at the end. 

**Expected behavior**
No delays at all. All worked fine up to BBB 2.2.2

**Actual behavior**
Already explained.

**Screenshots**
If required i can supply publicly available recordings.

**Desktop (please complete the following information):**
This happen on multiple events, different devices and it is concurrent on all of them

**Smartphone (please complete the following information):**
Same as above

**Additional context**
No

**Comment by jibon57** [comment] 2020-04-18 20:42
I am referencing our discussion: 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bigbluebutton-dev/_ONLyvnkCRU/hus_p0_QCAAJ

**Comment by peterpetrov** [comment] 2020-04-19 12:44
I was able to perform a manual check on a raw video and exported video and audio. The result is that the exported video is somehow stretched. I would need someone from the dev team to perform the test themselves so they can confirm the status of the issue. I will go further finding out eventually if i can fix it.

**Comment by peterpetrov** [comment] 2020-04-19 13:10
https://wetransfer.com/downloads/28be1205d226f73ec13b8eff1f78c8fc20200419130530/9124b85428f0c1c9493a90475b01009820200419130549/fc8040

Here is the raw recording of an event where the issue occur after the publish process is complete.

**Comment by matiasilva** [comment] 2020-06-18 11:37
Duplicate of #8815. As suggested there, update to the latest version. Feel free to follow up in the previously mentioned issue or in the mailing list.

**Closed by matiasilva** 2020-06-18 11:37 UTC
Labels: Recording
