### ISSUE TITLE
Make it a easier to read poll results

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#17007] opened 2023-03-12 23:44 UTC
**Describe the bug**
The poll results would be easier to read on the presentation with a white background and different font.

**To Reproduce**
Create and publish a poll in BigBlueButto 2.6-rc.7

**Expected behavior**
Easier to read poll results

**Actual behavior**
Here's what they currently look like

<img width="227" alt="image" src="https://user-images.githubusercontent.com/290351/224581254-09b6ebe3-042d-4c22-bc5c-a176080939f3.png">

And with a solid white background and different font, they would be much easier to read

<img width="229" alt="image" src="https://user-images.githubusercontent.com/290351/224581221-4976ba46-7793-4856-9ffb-3c4c942a8ffb.png">

**BBB version:**
BigBlueButton 2.6-rc.7

**Comment by antobinary** [comment] 2023-03-13 11:05
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/16917

**Closed by antobinary** 2023-03-13 11:05 UTC
Labels: module: client
