### ISSUE TITLE
logging out to feedback page does not disconnect media streams

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#7441] opened 2019-05-14 20:56 UTC
When an individual user logs out of the meeting via: settings menu > log out, audio and webcam streams are not disconnected until the feedback form is submitted or the user closes the browser.

Audio still transmits to the meeting (and users still connected) 

Webcam remains on the log out feedback page:

![Screen Shot 2019-05-14 at 4 54 18 PM](https://user-images.githubusercontent.com/18176998/57731678-39826000-7669-11e9-83ca-241e2d28533b.png)

**Comment by capilkey** [comment] 2019-05-14 21:00
Previous issue regarding the local webcam not being removed on logout https://github.com/bigbluebutton/bigbluebutton/issues/7083

**Comment by antobinary** [comment] 2019-05-15 11:32
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/7198

**Closed by antobinary** 2019-05-15 11:32 UTC
Labels: HTML5 Client
